### ISSUE TITLE
iSponsorBlock segments not appearing in seek bar

### ISSUE THREAD

**Issue by Shady-3** [qnblackcat/uYouPlus#1]
No colors or whatsoever appear in the seek bar but other than that the SponsorBlock works perfectly AFAIC, it skips segments, gives me the message with the unskip button and the modified time also works.

![81AA0410-7483-4367-BAAB-4CF919DBB4CD](https://user-images.githubusercontent.com/47725473/140892268-15fbcc72-04bf-4984-bfb8-c0e875042414.png)

iPad (6th generation)
IOS 15.1 (19B74)

**Comment by qnblackcat** [comment]
It’s a known issue with iSponsorBlock. Please see the Known issues section.
