### ISSUE TITLE
[Bug] Most settings buttons in uYou crash the app.

### ISSUE THREAD

**Issue by Cralex** [qnblackcat/uYouPlus#10]
Hello,
I just updated to v16.42.3-2.1 using Altstore from the previous release on my iPhone SE 2020. (I deleted the old uYou+ first.) Most of the buttons in the uYou -> YT Settings section are causing the app to crash instantly. Specifically, I can’t press Video Controls Overlay, Buttons Under the Video Player, Navigation Bar, Hide Tabs, or Other Settings. I can, however, reorder tabs.
Thanks for the great tweak!

**Comment by alexandrius** [comment]
Can confirm same issue

**Comment by qnblackcat** [comment]
@Cralex @alexandrius 
please include your spec: iOS version, device model, sideload tool...

I can't not reproduce the crash on my phone (iPhone 8/14.7.1/Sideloadly)

https://user-images.githubusercontent.com/52943116/144172378-c1c3ecd0-23f6-4548-a177-ca39d605a564.mp4

**Comment by alexandrius** [comment]
@qnblackcat iPhone 12 Pro, iOS 15.0.2, Xcode

**Comment by AtlasTheProto** [comment]
Confirming same issue
iPhone 13, iOS 15.0.2
AltStore direct IPA sideload, latest UYP stable release 
https://user-images.githubusercontent.com/17933206/144327989-884658a4-9467-4348-8364-654893d89dd0.MOV

**Comment by pakpenyo** [comment]
Yep, it's crash with latest stable.
iPhone 11 pro, 15.1 Beta 3.
Sideloadly, and 3rd party private signing services.

**Comment by talibando** [comment]
same issue
iphone xr, 15.1, sideloadly

**Comment by qnblackcat** [comment]
Thank you for your feedback! Apparently, uYou (2.1) doesn't seem to work with the latest version of YouTube. 
I made an older version of uYou+, which is based on YouTube 16.42.3. It also features iSponsorBlock 1.0-11. Please try this version. 
I'm sorry for the inconvenience!

[uYouPlus 16.42.3 & iSponsorBlock 1.0-11](https://www.dropbox.com/s/63ck6dmcmcctcif/uYouPlus_16.42.3_iSponsorBlock_1.0-11.ipa?dl=0)

**Comment by alexandrius** [comment]
@qnblackcat Works great. 
> I'm sorry for the inconvenience!
Come on. Thank you for work!

**Comment by PoomSmart** [comment]
@qnblackcat If we could get the crash log it would be great.

**Comment by qnblackcat** [comment]
@alexandrius @talibando @pakpenyo 

Any update? Some told me that remove the app and install it again fixed the bug

**Comment by alexandrius** [comment]
> @alexandrius @talibando @pakpenyo
> 
> Any update? Some told me that remove the app and install it again fixed the bug

It works just fine like I said

**Comment by qnblackcat** [comment]
@alexandrius 
Please try the latest version of uYou+
https://github.com/qnblackcat/uYouPlus/releases

**Comment by pakpenyo** [comment]
> @alexandrius Please try the latest version of uYou+ https://github.com/qnblackcat/uYouPlus/releases

uYouPlus_16.46.5_2.1 still crash.
Sideloadly.

**Comment by Slurpassassin** [comment]
I crash as well. Latest version, iphone 8, altstore

**Comment by qnblackcat** [comment]
> > @alexandrius Please try the latest version of uYou+ https://github.com/qnblackcat/uYouPlus/releases
> 
> uYouPlus_16.46.5_2.1 still crash. Sideloadly.

1. What is your device specs?
2. Have you tried to delete the app and install it again?
3. Please send me the crash log: Head to the Settings app - Privacy - Analytics & Improvements - Analytics Data - YouTube...

**Comment by pakpenyo** [comment]
> 

Iphone 11 pro, 15.1, sideloadly, and yes, I always delete them first.
[log.zip](https://github.com/qnblackcat/uYouPlus/files/7799993/log.zip)

**Comment by ivankrdenas** [comment]
Same issue guys. iPhone 12 mini 15.1.1 latest uYou version installed.
[YouTube-2022-01-03-163638.ips.zip](https://github.com/qnblackcat/uYouPlus/files/7804149/YouTube-2022-01-03-163638.ips.zip)

**Comment by lbibass** [comment]
I am also having the same issue. iPhone 13 Pro, 15.1.

**Comment by alexandrius** [comment]
Any update on this?

**Comment by Macleykun** [comment]
Issue is still present on the latest version.

**Comment by Skywalker8510** [comment]
I'm also having this issue after downloading for the first time today. i grabbed the latest release on an iPhone 12 on 15.1.1

**Comment by miIktoast** [comment]
Issue still persists for:
- Video Controls Overlay
- Buttons Under Video Player
- Navigation Bar
- Hide Tabs
- Other Settings 

**System**
- 11 pro max
- iOS 15.1
- AltStore 1.4.8
- uYouPlus 17.06.3-2.1

[YouTube-2022-03-02-125557.zip](https://github.com/qnblackcat/uYouPlus/files/8172303/YouTube-2022-03-02-125557.zip)

**Comment by qnblackcat** [comment]
Let's hope MiRO can fix this issue in the next update. For now, please try the version based on YouTube 16.42.3 if you encounter this issue.

**Comment by PoomSmart** [comment]
The crash log concerns usage of in-app settings library https://github.com/FouadRaheb/FRPreferences, the issue residing in uYou itself.

**Comment by qnblackcat** [comment]
> The crash log concerns usage of in-app settings library https://github.com/FouadRaheb/FRPreferences, the issue residing in uYou itself.

Seems like it only happens on early version of iOS 15 (15.0-15.1.1)

**Comment by qnblackcat** [comment]
This should be fixed in [v17.34.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.34.3-2.1)
