### ISSUE TITLE
[Questions] Why some videos HDR are only available in 480P

### ISSUE THREAD

**Issue by KAHALB** [qnblackcat/uYouPlus#100]
Device info
iOS/iPadOS version: 15.4.1
Device model:iphone 11
Sideload tool (Ex: AltStore, Sideloadly...)Altstore
Version of uYouPlus: v17.12.5-2.1-beta

**Comment by qnblackcat** [comment]
Not sure I understand you. Any screenshots?

**Comment by ifRemix** [comment]
If you enable VP9 support in Settings - videos without HDR are shown in 4K. But some videos with HDR have a maximum resolution of 480P HDR.
If you disable VP9 support in Settings - all videos and videos with HDR without HDR have a maximum resolution of 1080p.
Moreover, Safari shows the maximum resolution on the same videos that are max 480P or 1080P in the app with no problem.
iOS 15.4.1  iPad Pro 12.9 M1, iPhone 12 Pro, uYouPlus v17.12.5-2.1 release.
![B467C8EC-76F9-45B0-8FE4-BABED6ADBA4A](https://user-images.githubusercontent.com/97290980/162846609-5891c55b-bb4e-4a49-b988-8250c063f4dd.jpeg)
![02169969-6953-4E99-9E94-DDCD23F2230C](https://user-images.githubusercontent.com/97290980/162846618-d96f9eed-b457-4aa9-ad99-3685b0897d59.jpeg)

**Comment by JONTTM** [comment]
I also experienced this but only on some HDR videos, not all of them.

**Comment by ifRemix** [comment]
Not sure, but I think it refers to HDR video where 60fps. i'll have to do some more testing.

**Comment by JONTTM** [comment]
> Not sure, but I think it refers to HDR video where 60fps. i'll have to do some more testing.

Yes this makes sense because the HDR video that played in 4k for me was 30fps

**Comment by ifRemix** [comment]
20 fps works too. the only problem seems to be with 60fps HDR.

**Comment by qnblackcat** [comment]
This will be fixed in the next update. Note that **adding HDR for 720p+ quality will be low priority**. So, please, don't ask.
<p align="center" width="100%">
    <img width="40%" src="https://user-images.githubusercontent.com/52943116/164500109-1e59ca3a-5d4c-459c-922d-86b2b66ec09c.jpg">
</p>
