### ISSUE TITLE
[Bug] Pip not working correctly since installed

### ISSUE THREAD

**Issue by namanhishere** [qnblackcat/uYouPlus#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- **iOS/iPadOS version:** iOS 16.1.1 (20B101)
- **Device model:** iPhone Xr
- **Sideload tool (AltStore, Sideloadly, TrollStore,...)**: AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): lastest (v18.08.1-2.3.1)

### Describe the bug

I cannot get the pip working correctly since I installed uYouPlus. 
Here is the screen-recording: https://user-images.githubusercontent.com/53372786/223498897-b529a29a-b5cf-43e4-a91c-b7030ee65789.mov
I already tried to re-sideloading uYou+ but this cannot made it work correctly

### Steps to reproduce the issue

I got that for the first time install

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
Could you show me your setting of YouPiP?

**Comment by namanhishere** [comment]
Hi @qnblackcat 
Here is my YouPIP config
![image](https://user-images.githubusercontent.com/53372786/223603366-61c89b00-1c15-47b7-a6dd-b56a51509179.png)

**Comment by IAmSkeez** [comment]
Idk if you know this but I found you can fix it temporarily by disabling youpip then restarting app, and enabling it again and another restart after that. Hope that helps!

**Comment by namanhishere** [comment]
Hi, 
I maybe found the problem came from my Youtube Premium account

On the same device but when I turn on the incognito, I can get the pip working perfectly as well
https://user-images.githubusercontent.com/53372786/223617927-8cde328a-0e6e-4dea-a67c-e9bc92e1a334.MOV

**Comment by qnblackcat** [comment]
1. If you have Premium, you can safely disable YouPiP because Premium user already had PiP
2. I’m using Premium rn and PiP works great for me

**Comment by gaurav-varshneya** [comment]
> Idk if you know this but I found you can fix it temporarily by disabling youpip then restarting app, and enabling it again and another restart after that. Hope that helps!

Can confirm that this fixed my issue. Thanks @IAmSkeez!

**Comment by namanhishere** [comment]
> 1. If you have Premium, you can safely disable YouPiP because Premium user already had PiP
> 
> 2. I’m using Premium rn and PiP works great for me

Hi @qnblackcat 
Thanks for your help. But sadlly it did not help me fix it as well
https://user-images.githubusercontent.com/53372786/223690394-fc13b2c0-ecc8-4db7-b2e9-9b3316b7b477.MOV

**Comment by qnblackcat** [comment]
I assume you enabled PiP in YouTube's General settings?
