### ISSUE TITLE
[Bug] uYou tab icon invisible when watching Shorts with light appearance enabled

### ISSUE THREAD

**Issue by therealFoxster** [qnblackcat/uYouPlus#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4
- Device model: 13 mini
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): [v18.07.5-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.07.5-2.3.1)

### Describe the bug

I can't see the uYou icon in the tab bar when watching Shorts with light appearance enabled.
![IMG_E96969F2828F-1](https://user-images.githubusercontent.com/77606385/223651519-f91b45ad-af2f-4ad3-8ed3-e89a45962484.jpeg)

### Steps to reproduce the issue

1. Enable light appearance
2. Watch Shorts
3. Bam

### Are you using the newest version of uYouPlus? If not, why?

❌ No, I'll explain at the end of the template

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

I've experienced this on [v18.07.5-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.07.5-2.3.1) and below. [v18.08.1-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.08.1-2.3.1) doesn't seem to have this issue but introduces #552 again. Coincidence?

**Comment by qnblackcat** [comment]
Fixed in uYou 3.0

**Comment by qnblackcat** [comment]
Fixed in [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)
