### ISSUE TITLE
Error 200 or 206 when Video Downloads are finished

### ISSUE THREAD

**Issue by IAnimeGuy** [qnblackcat/uYouPlus#1003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.1.1 (See Additional Context)
- Device model: IPad 8th Gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): (I tried multiple) TrollStore, AppDB, Scarlet
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 2.1 / 18.08.1

### Describe the bug

![B67D0976-D156-40B8-8792-51EEF6E5CA88](https://user-images.githubusercontent.com/118938615/223796511-828de201-dddd-4165-8747-a215216b8828.png)
Every Video I tried does not seem to work, it always gives me either Error 200 or 206

### Steps to reproduce the issue

1. Open uYou+
2. Click on the Video
3. Install the Video in any Quality
4. Wait till Download is finished
5. Finished!

### Crash log (if the app crashes)

```shell
No Crash involved
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

IPadOS Version - Yes, this may be the latest/close to latest Version or IPadOS but I have tested many Apps and even older Versions of uYou+ that had working downloads, but I prefer using the latest Version as it is over all better, the only Problems are the Downloads and the Log in issue (will make another bug report)

**Comment by IAnimeGuy** [comment]
In the Sideload tool, I did not mean to write “TrollStore” as it doesn’t work on my IPad

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/issues/238
