### ISSUE TITLE
[Bug] Crash on iOS 16.1.2

### ISSUE THREAD

**Issue by khaiphan9x** [qnblackcat/uYouPlus#1004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.1.2
- Device model: XR
- Sideload tool (AltStore, Sideloadly, TrollStore,...): BullfrogAssistant, ESign
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.08.1-2.3~1

### Describe the bug

Can not open app

### Steps to reproduce the issue

1. Sideload youtube v18.08.1 with v2.3~1 dylib
2. Install successfully 
3. Crash immediately when opening the app
4. try with v18.08.1-2.1
5. Its working

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by gharshit606** [comment]
Its the issue with bullsfrog app itself. I also faced the same issue and this bug started since last update to bullsfrog according to issue reported by other users too. You should try other installers like Altstore, Sideloadly, etc… to sideload as they are working fine with it with no app crash.

**Comment by qnblackcat** [comment]
According to @gharshit606 , you should use other sideload tools
