### ISSUE TITLE
[Questions] Sign Youtube 18.04.9 with uYou 2.3~1

### ISSUE THREAD

**Issue by khaiphan9x** [qnblackcat/uYouPlus#1006]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

I try to sign Youtube 18.04.9 with uYou 2.3~1 but there is an error that cannot open the app. If I want to sign fully, what dylib needs to be added to the app?

### Additional context

Sorry, I told the author:
   Bác Đạt hướng dẫn mình sign với, không biết thiếu những dylib nào

 The components I use to sign the app:
* [Youtube 18.04.9](https://terabox.com/s/1HOpeHfjMNYqbyAIJGqfkkA) 
* [uYou 2.1](https://miro92.com/repo/debs/com.miro.uyou_2.1_iphoneos-arm.deb) 
* [uYou 2.3~1](https://miro92.com/repo/debs/com.miro.uyou_2.3~1_iphoneos-arm.deb)

**Comment by qnblackcat** [comment]
It looks like you’re trying to build your custom version of uYou. uYou itself doesn't support iOS 16, this should fix the crash 

https://github.com/qnblackcat/uYouPlus/pull/224
