### ISSUE TITLE
[Questions] Legal activities from Youtube

### ISSUE THREAD

**Issue by schweppes-0x** [qnblackcat/uYouPlus#101]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###
What are the risks of Youtube starting any legal activities agains uYou+ ? The same has happened to a bunch of other developers. Take YoutubeVanced for instance, they kept the app going for some years and like 1 month ago they had to shut down due to legal reasons. They lost everything they had build in those years. It would be a waste if the same happened to uYou+. Is it possible to counteract this ?

**Comment by qnblackcat** [comment]
I can tell you that Google will come after uYouPlus, sooner or later. The main reason is that I'm distributing YouTube IPA, which is kinda *illegal*. I might have to take down all IPAs in the worst case. Luckily, anyone can make their own uYouPlus iPA if they have the right tools.

Anyway, this is not an issue so I'll close it.

**Comment by schweppes-0x** [comment]
It could prove usefull if there was a tutorial how to build the IPA's. I'm sure that they're hard working on preventing any 3rd parties like uYou+ to take disadvanted of their API.

**Comment by qnblackcat** [comment]
It is a tutorial how to build uYou+
https://github.com/qnblackcat/uYouPlus/wiki/Building
