### ISSUE TITLE
[Bug] ‘Most Replayed’ graph not showing up for most videos

### ISSUE THREAD

**Issue by CookieMonsterVocals** [qnblackcat/uYouPlus#1010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.3.1
- Device model: iPhone XS
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.08.1-2.3.1

### Describe the bug

Previously when watching videos using uYouPlus a graph would show up for pretty much every video—now they almost never appear.

### Steps to reproduce the issue

Simply load a video and drag the seekbar.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

I can’t speak for the official YouTube app as I don’t know how to install it simultaneously with uYouPlus, but on desktop, using a web browser, the graphs show up all the time making me think this is specific to uYouPlus.

**Comment by qnblackcat** [comment]
https://youtu.be/dihQuwrf9yQ

Does it work in this video?

**Comment by CookieMonsterVocals** [comment]
> 

Yes, it’s working for me with that video.

Any clue as to why these graphs are showing up less consistently?

**Comment by qnblackcat** [comment]
Just YouTube casually messing up everything I guess 🤷‍♂️ Happens in the official YouTube app as well
