### ISSUE TITLE
[Share] Youtube 18.09.4 Latest and uYouPlus 2.3.1 option

### ISSUE THREAD

**Issue by khaiphan9x** [qnblackcat/uYouPlus#1011]
This version is made by the developer Vietnamese

[Download here](https://www.mediafire.com/file/kl0uv4kgjq4ude9/uYouPlus_v18.09.4_2.3.1.ipa/file)

Thanks for @LK Team

**Comment by qnblackcat** [comment]
Last warning: spam something like this again and you’ll be banned.
