### ISSUE TITLE
Notifications function for this app is missing in IOS 

### ISSUE THREAD

**Issue by Carrotcruncheruk** [qnblackcat/uYouPlus#1019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version:
- Device model:
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of uYouPlus (**latest or newest is NOT a version number!**):

### Describe the bug

The notification function is completely missing in notifications in iOS. It’s vanished if you try to select notifications in the app it just takes you to the settings in iOS and the notification function is gone it’s not there vanished !  I did try deleting the app and reinstalling it a few times, didn’t make any difference.

### Steps to reproduce the issue

1. Install app
2. Try to enable notifications 
3. The function has vanished

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by CookieMonsterVocals** [comment]
This problem sucks. For now I recommend you just use the previous app version. That’s what I’m doing.

**Comment by Carrotcruncheruk** [comment]
You can only use the old app for a new ID on Google if you signed on once already and then you signed out you can't sign back in again without creating a whole new Google account which is pretty annoying so I'm just gonna stick with this app and just wait a few days, I'm pretty sure the devs will solve the problem They always do!

**Comment by Carrotcruncheruk** [comment]
One solution I just found is to use this current version of the app to log into YouTube once you've logged into YouTube, then you sideloady to install the previous version of the app it overwrite the newer version, and you get the notifications back mission accomplished!

**Comment by Carrotcruncheruk** [comment]
Just to add, it appears that notifications aren't working despite trying what I said before the auction for the notifications is there but no notifications arrive
