### ISSUE TITLE
[Bug] Still can’t sign in on the latest version

### ISSUE THREAD

**Issue by rzre** [qnblackcat/uYouPlus#1020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.3.1
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.08.1~2.3~1

### Describe the bug

I still can’t sign in with the newest version 
![72D71A03-2E2F-460D-8A1A-F103F8DCB929](https://user-images.githubusercontent.com/85282759/225102024-7e8757a2-2309-4bec-80ca-c4b7f28022f4.jpeg)

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

No

**Comment by Carrotcruncheruk** [comment]
How are you installing the update ? Did you remove the old version first ?

**Comment by Carrotcruncheruk** [comment]
Just to add I can replicate this bug, the account shows in the account section of the app but it won't let you use it

**Comment by JustJ45on** [comment]
I had a older one first. Deleted it and the sideloaded the newest version.

**Comment by Carrotcruncheruk** [comment]
I was able to replicate the bug, my solution was to use another Google account that I've got and with that I was able to sign in instantly, my steps were to go to manage accounts, remove all accounts, uninstall the app, restart the device, reinstall the app and then use a different Google account. Then I was able to sign in, it also works if you create a new google account, although it does ask for a phone number to confirm the account which is pretty annoying, but I was able to sign in that way as well so what it looks like is that Google are actually barring certain accounts that have used the app before, I don't know what the solution for that is, but no doubt some clever Dev on here will figure out a way they always do! 😂

**Comment by JustJ45on** [comment]
Thank you for helping. Making a new account worked! 😊

**Comment by Carrotcruncheruk** [comment]
Your welcome !

**Comment by kapi3511** [comment]
Is there any way to log in into existing google account?

**Comment by JustJ45on** [comment]
Not that I know. But what you may can do is transfer data. You can search it on internet. Here is someone who explained how to do it: https://www.easeus.com/amp/pc-transfer/transfer-youtube-data-to-another-account.html

Hope this helped.

**Comment by kapi3511** [comment]
I was able to log in with the old shortcut method, in #904

**Comment by thonkinator** [comment]
I was able to sign in with this version before, but after uninstalling and reinstalling I can't sign in anymore. It doesn't even let me sign in with other google accounts, and I can't get the shortcut method to work.

**Comment by AvnerKmskk** [comment]
hey, I've found recently the fix of the bug. Try installing it via eSign.
