### ISSUE TITLE
How to update uYou's itself. (Not uYouPlus)

### ISSUE THREAD

**Issue by Metercedes** [qnblackcat/uYouPlus#1021]
Whenever I open the uYouPlus app, it tells me to update the uYou. I press on update and it directs me to another GitHub link to which the original belongs. But the extremely old version of YT they are. What should I do?

![image](https://user-images.githubusercontent.com/51666146/225137153-e7ad5723-650c-4cab-a9d3-f243ae52d4e0.png)

**Comment by Carrotcruncheruk** [comment]
Ignore it press skip
