### ISSUE TITLE
how to upload videos ? 

### ISSUE THREAD

**Issue by agentstyle** [qnblackcat/uYouPlus#1028]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Is there any way to upload videos on the app. The official app has a + icon that lets you upload shorts and videos. I wish to get this on the mod version too.

**Comment by githubashutoshsoni** [comment]
Yes would love to get this in next release

**Comment by qnblackcat** [comment]
uYou’s settings > Hide Tabs > Turn off Hide Shorts Tab

Or you can just do a Haptic touch on YouTube icon > Create
