### ISSUE TITLE
[Bug] Search page not loading

### ISSUE THREAD

**Issue by DW-Arthur** [qnblackcat/uYouPlus#103]
Sometimes when after searching, it will only load 1 page, scrolling down will get stuck at loading stage.

To reproduce, search anything, scroll all the way down. 3/4 time it will get stuck at loading.
![84BEA7AA-093E-4EF2-8FE7-E88FBE8B2871](https://user-images.githubusercontent.com/39779028/162655072-7141c77e-9d94-4d3e-9c1d-98e672b6fd33.png)

**Comment by qnblackcat** [comment]
Doesn‘t seem to be an issue of uYou+ for me. Are you sure this doesn‘t happen on stock YouTube?

**Comment by DW-Arthur** [comment]
> Doesn‘t seem to be an issue of uYou+ for me. Are you sure this doesn‘t happen on stock YouTube?

The stock Youtubr doesn't have this issue.

**Comment by qnblackcat** [comment]
I can't reproduce this issue at all. Try to wait and see if the issue resolved on its own

**Comment by DW-Arthur** [comment]
> I can't reproduce this issue at all. Try to wait and see if the issue resolved on its own

Thanks for the reply! The issue still have not resolved. I think I will wait for the next update to see if it fixes it. 
I was wondering how to update the uYou+ with altstore? Do I need to delete the app and reinstall with the new update IPA file?

**Comment by qnblackcat** [comment]
If you have access to AltStore beta, you can add my AltStore repo here: https://qnblackcat.github.io/AltStore/apps.json

Otherwise, you have to overwrite the old version with the new ipa. DO NOT delete the old version or you’ll lose all your app’s data & pref

**Comment by DW-Arthur** [comment]
> @DW-Arthur any update?

I re-installed uYou+ and it fixed the issue.
