### ISSUE TITLE
There is no provisioning profile with the requested identifier on this team.

### ISSUE THREAD

**Issue by ogkimra** [qnblackcat/uYouPlus#1036]
Facing this while installing/refreshing uyou.

AltStore.AppleDeveloperError 3017

**Comment by ogkimra** [comment]
Is this altserver side issue?

**Comment by jaff80** [comment]
https://twitter.com/altstoreio/status/1638237156777816071

**Comment by Hingeco** [comment]
Altsever messed up the code then fixed it only if your pay to be a patron.. the rest will get the fix in about a week.. 
just a cash grab hang in there

**Comment by yodaluca23** [comment]
> Altsever messed up the code then fixed it only if your pay to be a patron.. the rest will get the fix in about a week.. 
> just a cash grab hang in there

It's not actually AltStore that changed anything, it's Apple that changed their API...

**Comment by Hingeco** [comment]
Actually no it was altstore... sideloadly uses the same api and it still works

**Comment by jaff80** [comment]
New update is free now: https://twitter.com/altstoreio/status/1638599316762664974

**Comment by qnblackcat** [comment]
Please update AltStore

**Comment by Foxtrod89** [comment]
I got similar issue
`Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.TzxK7x/extracted/App.app/Frameworks/widevine_cdm_secured_ios.framework : 0xe8008015 (A valid provisioning profile for this executable was not found.)` during the signing step of AltStore.
