### ISSUE TITLE
[Bug] Create tab cannot be reordered

### ISSUE THREAD

**Issue by CappytRex** [qnblackcat/uYouPlus#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 15.4.1
- Device model: iPhone SE 3rd Gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): TrollStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.08.1-2.3~1

### Describe the bug

After attempting to manually reorder the Create Tab to the middle of the bottom bar, the Create Tab stays at the rightmost spot, and no other movements are able to affect it. All other tab reorderings work as intended.

### Steps to reproduce the issue

1. Disable the Hide Create Tab option
2. Restart the app
3. Reorder the Create Tab to any position
4. Restart the app
5. Create Tab stuck in rightmost position

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
#107
