### ISSUE TITLE
Can’t leave a comment under videos

### ISSUE THREAD

**Issue by ethanguin** [qnblackcat/uYouPlus#1039]
![IMG_0381](https://user-images.githubusercontent.com/17581144/227669630-71410212-39f1-4c7b-933e-66f41653deef.png)

Error 403 when trying to comment on any video/short:
The operation couldn't be
completed. (com.google.HTTPStatus error 403.)

I have been unable to reproduce this error on the official YouTube app. It seems as though the connection uYouPlus is using to access Google’s servers isn’t allowed to update comment data.

**Comment by ethanguin** [comment]
I have also looked for any other issues that may be similar, but the only one I found was a closed issue that was saying all comment sections were restricted.

**Comment by CurssedCoffin** [comment]
This happens to me when I'm using a VPN. Close VPN does work for me to comment.

**Comment by qnblackcat** [comment]
Please complete the issue template
