### ISSUE TITLE
[Bug] Download speed is extremely slow.

### ISSUE THREAD

**Issue by wild-a** [qnblackcat/uYouPlus#104]
### Device info
- iOS/iPadOS version: iOS 15.5
- Device model: iPhone 13 Pro Max
- Sideload tool (Ex: AltStore, Sideloadly...) Sideloadly
- Version of uYouPlus: 7.12.5_2.1

### Describe the bug
Download speed has been extremely slow for the past few versions. I have tried it on 5G, home wifi, work wifi with same results.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
![IMG_1356](https://user-images.githubusercontent.com/74679016/162658196-1ab152da-71be-451a-a944-ceaffe57c717.PNG)
![IMG_1357](https://user-images.githubusercontent.com/74679016/162658297-05a4e585-fdb9-49ce-9547-5a606d5f401d.PNG)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
