### ISSUE TITLE
[Feature Request] Disable Google tracking and metrics

### ISSUE THREAD

**Issue by Shadowspear123** [qnblackcat/uYouPlus#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version:  ios 16.1
- Device model: iphone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 
v18.08.1-2.3.1

### Describe the bug

It would be nice if the google tracking, analytics, and metrics could be removed from the app. It would make the app smaller and lighter. It would also make the app faster and make it use less data. Additionally it’s better for privacy and security. 

### Steps to reproduce the issue

N/A

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
sorry but we don't have any plan to something like this
