### ISSUE TITLE
[Questions] Bundle ID different when sideloading through Altstore

### ISSUE THREAD

**Issue by Shadowspear123** [qnblackcat/uYouPlus#1041]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

When I was installing the app via Altstore, I noticed the bundle Id was 

com.google.ios.youtube.GUA2A4966Z

I don’t think this was the bundle ID before. In the FAQ it says to make sure the bundle id is 

com.google.ios.youtube

Why is the bundle Id different? Where did the extra stuff come from?

**Comment by yodaluca23** [comment]
Altstore probably automatically adds a bunch of that crap so that you can side load multiple of the same app

**Comment by qnblackcat** [comment]
The bundle ID doesn't matter. You can ignore it unless you're using an extremely old version of uYou+ (< 17.21.3-2.1)
