### ISSUE TITLE
[Bug] SideStore/AltStore: Unable to install the app from the staging directory

### ISSUE THREAD

**Issue by HexCodeFFF** [qnblackcat/uYouPlus#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4
- Device model: iPhone 14 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sidestore 0.3.2-pr.321+d43fd4f, heard this happens with AltStore too
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.08.1-2.3.1

### Describe the bug

Some kinds of app installs cause the error "Unable to install the app from the staging directory". People in the SideStore discord say that this error has to do with the way uYouPlus is compiled. the error doesn't occur with other apps.

### Steps to reproduce the issue

1. install uyouplus and some other app totaling 3 apps
2. do some action to try to get sidestore to install uyouplus again (backing up data is one, deleting sidestore to get it to forget what's installed is another)
3. sidestore will error

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Yes i'm aware this is probably a alt/sidestore issue but it sounds like it could be possible for a fix to happen on uyouplus's end as well

**Comment by qnblackcat** [comment]
Sorry, I can’t fix this. Try AltStore/Sideloadly maybe

**Comment by HexCodeFFF** [comment]
The bug happens on AltStore also
