### ISSUE TITLE
Adblock not working 

### ISSUE THREAD

**Issue by zoplo** [qnblackcat/uYouPlus#1048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: iPhone 14 pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.08.1-2.3.1

### Describe the bug

I’m using v18.08.1-2.3.1 (the latest version) of uYou+ and for some reason sometimes I still get ads when I watch videos. I enabled the option to remove YouTube ads but every time I reopen the app, it toggles itself off. Is there any fix around this or is it a bug?

### Steps to reproduce the issue

Click any video to start and an ads will show 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
#996
