### ISSUE TITLE
[Questions] Default zoom to fill

### ISSUE THREAD

**Issue by JamesDAdams** [qnblackcat/uYouPlus#1049]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Hi,

i’s possible to have an option to always zoom to fill when we start a video .

thanks.

**Comment by qnblackcat** [comment]
![E5EB3050-D9DA-4D46-BE22-46BE1479C4D9](https://user-images.githubusercontent.com/52943116/229410487-09014c2a-eb54-4435-b73e-258312a4578e.png)
This is a built-in featute of YouTube
