### ISSUE TITLE
[Bug] Fail to install/update

### ISSUE THREAD

**Issue by anafvana** [qnblackcat/uYouPlus#1050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.3.1
- Device model: iPhone 14
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 17.49.6

### Describe the bug

I cannot update or freshly install the latest version of uYou++. I have also tested [v18.07.5-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.07.5-2.3.1), and it did not work, but the majority of the attempts (and there were countless) were to install [v18.08.1-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.08.1-2.3.1)

I have tried:
- downloading the IPA and installing through AltStore
- using the link that auto-installs in AltStore
- completely uninstalling uYou++ and re-installing afresh while having YouTube installed
- completely uninstalling uYou++ and installing afresh without YouTube installed
- installing the latest version on top of v17.49.6 while having YouTube installed
- Installing the latest version on top of v17.49.6 without YouTube installed

I have restarted my phone multiple times (in-between most attempts), have ensured AltStore was running on the computer, have tried enabling JIT from the computer.

The results I got were either:
1. An error from AltStore
2. The process just disappearing from AltStore (being concluded with no error messages?)
3. No errors until I try the app, and then it says “YouTube is no longer available”
4. On one single occasion, after an installation that “disappeared”, I restarted the phone and tried to open uYou++. On that one occasion it worked for circa 5-10 minutes on v18.08.1 (I checked) and then the app closed itself and “YouTube is no longer available” popped up.

I suspect this is a uYou++ issue rather than an AltStore issue because I can still install v17.49.6 normally. If I’m wrong, lmk and I’ll reach out to AltStore instead.

It might also be of note that my final attempt was to (once again) try to install the newest version on top of v17.49.6. It took quite a long time on AltStore, but I got no error messages. I thought the update would have been completed, but when I entered uYou++ and checked the version, it was still v17.49.6

### Steps to reproduce the issue

1. Using AltStore, install v17.49.6 using the IPA method
5. Log into the app
6. Using AltStore, attempt to update to the latest version

ALTERNATIVELY

1. Download the latest version of uYou++
2. Using AltStore, select the file from your device and install

ALTERNATIVELY

1. Click the link provided on GitHub that automatically redirects to AltStore
2. Allow for it to install (or update; either case fails)

All versions fail, whether it is with or without the original YouTube app on the phone.

### Crash log (if the app crashes)

```shell
AltServer.ServerError 2008

Failed to load Info.plist from bundle at path /private/var/containers/Bundle/Application/FB17E6D6-1752-47EB-BC9B-B502EF7A4795/App.app/PlugIns/MessagesExtension.appex; Extra info about "/private/var/containers/Bundle/Application/FB17E6D6-1752-47EB-BC9B-B502EF7A4795/App.app/PlugIns/MessagesExtension.appex/Info.plist": Couldn't stat /private/var/containers/Bundle/Application/FB17E6D6-1752-47EB-BC9B-B502EF7A4795/App.app/PlugIns/MessagesExtension.appex/Info.plist: No such file or directory
```

```
NSCocoaErrorDomain 512

The file “MaterialContributionsSwitch.strings” couldn’t be saved in the folder “lo.lproj”.
```

### Are you using the newest version of uYouPlus? If not, why?

❌ No, I'll explain at the end of the template

I can’t update.

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

This issue has been present for some time (it’s not the first time I try to update and fail, I just never went to the same lengths before).
I have recently updated AltStore, and have checked for updates. None are available currently.
This issue has been present since before I last updated AltStore.
I also refreshed AltStore using AltServer and checked for updates there.

**Comment by qnblackcat** [comment]
Have you read the FAQ?
