### ISSUE TITLE
[Bug] Getting virus warning when installing uYouPlus (Trojan:Script/Sabsik.FL.A!ml)

### ISSUE THREAD

**Issue by andsoitgoes** [qnblackcat/uYouPlus#1052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.5
- Device model: iPad Pro 2017, iPhone 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloady
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.08.1-2.3.1

### Describe the bug

When installing via Sideloady, I get a virus warning message about the youtube.ipa file stored in my windows temp directory

### Steps to reproduce the issue

1. Run Sideloady and add uYouPlus ipa
2. Start install
3. Get error with Defender about the script

I'm not sure what's going on here, but I'm getting quite concerned about this script error. I'm hoping it's just a false positive, but I'd like to get this figured as it's obviously a bit disconcerting.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by yodaluca23** [comment]
I think this is a problem with sideloady. It happens with any app that you sideload I don't think it's identifying the IPA file I think identifying the sideloady program it's probably just a false positive, because if you scan the IPA file you and see you get no alerts.

**Comment by andsoitgoes** [comment]
That makes more sense, thanks for the clarification! I did scan the IPA and it came back fine, I'll add this as an issue for Sideloady!
