### ISSUE TITLE
[Bug] After updating to 16.4, uyou download broke due to a move file error

### ISSUE THREAD

**Issue by PalmTamino** [qnblackcat/uYouPlus#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4
- Device model: iPhone 12 Mini
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): feb 18 [v18.08.1-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.08.1-2.3.1)

### Describe the bug

It downloads, but after the download worked, it fails.

### Steps to reproduce the issue

1. Get iOS 16.4
2. Try to download anything using uyou++
3.  See error

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Video: https://streamable.com/7a81w3

**Comment by qnblackcat** [comment]
#238

**Comment by PalmTamino** [comment]
> #238

No, this has not to do with #238. Its a bug on it's own in iOS 16.4. I had no problems before on downloading if I used Sideloadly and my Developer account. No matter what I do, it won't work anymore, on my 16.3.1 iPad it still works.

**Comment by PalmTamino** [comment]
@qnblackcat I downgraded to iOS 16.3.1 where I don't have this issue anymore. This is a seperate problem and not a duplicate. Please reopen!

**Comment by proway46** [comment]
> 

how can downgrade?
