### ISSUE TITLE
[Questions] How to disable YouTube shorts completely 

### ISSUE THREAD

**Issue by hexclann** [qnblackcat/uYouPlus#1059]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

I'm running uYouPlus 18.08.1 from GitHub installed using Altstore. Is it possible to disable YouTube shorts completely? For example, YouTube Revanced on Android has a similar feature where you can turn off the YouTube shorts.

**Comment by leewhat** [comment]
uYou - Other Settings - Remove Shorts Section in YT Home
uYou - Hide Tabs - Hide Shorts Tab

**Comment by qnblackcat** [comment]
Answered above

**Comment by jadtl** [comment]
> uYou - Other Settings - Remove Shorts Section in YT Home 

This setting does not seem to appear on the latest version, is there another way to remove them now?

**Comment by leewhat** [comment]
uYou - Home - Hide Shorts Cells

**Comment by HoodBlah** [comment]
Is there a way of disabling all shorts except for the ones in my subscriptions?

**Comment by kocoman2** [comment]
> Is there a way of disabling all shorts except for the ones in my subscriptions?

how to disable in subscriptions? its showing the shorts in my subscriptions tab

thx
