### ISSUE TITLE
[Enhancement] Option to disable posts on home

### ISSUE THREAD

**Issue by JONTTM** [qnblackcat/uYouPlus#106]
Please I need my sanity back

I don't want to see this stuff anymore
![BC98E272-D5EB-419F-A098-4DF161365F62](https://user-images.githubusercontent.com/14990787/163058957-1dcaf654-1ec7-4ce4-a3a2-efd9bf11ec82.png)

**Comment by qnblackcat** [comment]
I don't think I can do it. You can make a request in upstream of uYou tho

https://github.com/MiRO92/uYou-for-YouTube
