### ISSUE TITLE
[SUGGESTION(S)] Whitelist channels + Folders for downloaded videos + uYou page as Startup Page

### ISSUE THREAD

**Issue by Shazuli** [qnblackcat/uYouPlus#1061]
***Hi***

Here's some suggestions I'd think would be nice for uYouPlus, in no particular order.

### Whitelist channels to not remove ads on
Pretty explanatory; a list you can put channel names in who's videos should not have their ads blocked on. Or perhaps even better: Show ads, but a button to remove the playing ad anyways if you want to. I like to support the smaller channels I'm watching, even if just a little bit.

### Folders for downloaded videos
It would be nice if we could organise our downloads even further. I like it separates videos and just sound videos, but it would be nice if we could put them into additional folders too.

Right now when playing music it will also play the audio books I've also downloaded, so being to separate them would be nice.

And this couldn't just be for audio downloads, but videos too. So if you want to for example download a whole playlist you select the quality to download it in and it will automatically create- and put the videos in a separate folder under Videos.

### Being able to set uYou page as Startup Page in configs
You can set all the regular tabs as the Startup Page, but not uYou. I'd prefer seeing my download library first and then select other tab.

**Comment by theoccurrence** [comment]
Does uYou download work for you? For me it's been excruciatingly slow since about a year

**Comment by Shazuli** [comment]
> Does uYou download work for you? For me it's been excruciatingly slow since about a year
I've just been using it for a month or so, but it says it's downloading ~40 KB/s.

**Comment by qnblackcat** [comment]
I think you should open a new thread on uYou’s repo

https://github.com/MiRO92/uYou-for-YouTube
