### ISSUE TITLE
[Questions] Google blocking accounts that use this?

### ISSUE THREAD

**Issue by alexchandel** [qnblackcat/uYouPlus#1067]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

[Several commenters](https://github.com/qnblackcat/uYouPlus/discussions/683) have suggested Google blocks accounts that are signing in to this app from signing in.  Is this true?  Or are their accounts simply being flagged for something like suspicious activity due to multiple bad sign-in attempts?

**Comment by hexlay** [comment]
I have been using this for quite some time, but my account is still going strong, so i don't think so

**Comment by Carrotcruncheruk** [comment]
> I have been using this for quite some time, but my account is still going strong, so i don't think so

One swallow doesn't make a summer.

**Comment by qnblackcat** [comment]
This is a very hard question, and I cannot give you a correct answer. Since you care about privacy that much, I wouldn’t suggest you use uYouPlus (or any tweaked YouTube app).
