### ISSUE TITLE
[Bug] Create button stuck to right side of tab bar

### ISSUE THREAD

**Issue by jonttm** [qnblackcat/uYouPlus#107]
### Device info
- iOS/iPadOS version: 15.3.1
- Device model: iPhone 13
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore
- Version of uYouPlus: 2.1

### Describe the bug
Create button won't follow order of tabs

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Just show the create button in settings, change the order of any tabs, restart app

![49763C0A-2681-418F-9AF8-454E89079633](https://user-images.githubusercontent.com/14990787/163059416-ac883651-2be5-4a88-84f0-afacb10931d6.png)
![2C57A415-0DBD-4863-840B-8C700B0F863B](https://user-images.githubusercontent.com/14990787/163059436-f421dfc2-9620-4162-9720-8bdd74d534a6.png)

**Comment by mistik0611** [comment]
I have the same problem too, is there a fix?
![CCBF6E7B-630B-48C3-90A2-F9C221AE6336](https://user-images.githubusercontent.com/106174376/170083304-0474b389-6c2b-434f-a4f2-0bb0548354f9.jpeg)
![6D5BB5BB-7BBA-4BD2-9A3F-D50760873AFE](https://user-images.githubusercontent.com/106174376/170083334-0df8a82c-f8ae-471b-875f-7455145acf23.jpeg)

**Comment by yodaluca23** [comment]
Also having this problem I just want the tabs to be normal.., D: I also would like to be able to remove the uYou tab

**Comment by yodaluca23** [comment]
@JONTTM Why don't you use TrollStore if your on IOS 15?

**Comment by CappytRex** [comment]
Didn't find this bug report when searching for it, my bad

**Comment by qnblackcat** [comment]
Fixed in uYou v3.0.2+
