### ISSUE TITLE
Build and Release uYouPlus Workflow Action Fails

### ISSUE THREAD

**Issue by Chimbul** [qnblackcat/uYouPlus#1070]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

For the last 3 days I've been trying to build uYouPlus on my fork and it had failed. No code changes, I just keep it up to date with this git and try latest changes. Same error, same place every time. Here is the error:

![Screenshot 2023-04-12 102717](https://user-images.githubusercontent.com/8114661/231490994-4f380758-ec02-4664-b4d6-f85b06cc8422.png)

![Screenshot 2023-04-12 102841](https://user-images.githubusercontent.com/8114661/231491671-bae8dd82-aada-4d10-9c0c-81796338afcf.png)

Thanks

**Comment by Chimbul** [comment]
Changed and ran 

`@property (atomic, assign, readwrite) float playbackRate;`

and had this error:

![Screenshot 2023-04-12 112917](https://user-images.githubusercontent.com/8114661/231507564-6d2051df-4fc8-4588-98d8-ad2826f3fd97.png)

Changed and ran

`%property (atomic, assign, readwrite) float playbackRate;`

and had this error:

![Screenshot 2023-04-12 113516](https://user-images.githubusercontent.com/8114661/231508509-5ea8ed3d-ad3d-4d5e-8158-1018d49fe60d.png)

**Comment by Chimbul** [comment]
Well my friend after some trial and error with some research I found the winner line:

`%property (nonatomic, assign) float playbackRate;`

Action workflow completed, IPA created, IPA sideloaded and uYouPlus opened and so far is "working".
I do not know what that stuff inside the parenthesis do, but it worked. Thanks for your quick response.

**Comment by qnblackcat** [comment]
thanks
