### ISSUE TITLE
[Bug] Dislike count disappers when scrolling

### ISSUE THREAD

**Issue by jaff80** [qnblackcat/uYouPlus#1071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.4.1 (20E252)
- Device model: iPhone 13 Pro Max
- Sideload tool: AltStore
- The specific version of uYouPlus: v18.08.1-2.3.1

### Describe the bug

The dislike count disappears when scrolling while watching a video (the video can be paused). It can come back when viewing the video in full screen. 

### Steps to reproduce the issue

1.  Tap on a video
2.  Scroll down
3.  Scroll back up, and the dislike count disappears

https://user-images.githubusercontent.com/113552154/231644360-b6c0ba89-dcb6-4951-8ec7-7f819f039a38.mp4

### Crash log (if the app crashes)

```shell
The app does not crash.
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

This issue might be https://github.com/qnblackcat/uYouPlus/issues/596

**Comment by qnblackcat** [comment]
Please open a new issue on Return YouTube Dislike repo
https://github.com/PoomSmart/Return-YouTube-Dislikes
