### ISSUE TITLE
Update uYou to v3.0

### ISSUE THREAD

**Issue by asportnoy** [qnblackcat/uYouPlus#1076]
Just got notified that it's available. Looks like a pretty big update! Would love to have support for it in uYouPlus.

Changelog: https://reddit.com/r/jailbreak/comments/12omp7v/update_uyou_v30_the_best_tweak_for_the_youtube_app/

**Comment by Felting** [comment]
Check out uyouplusextra

**Comment by dayanch96** [comment]
finally downloading works on dev certs

**Comment by Felting** [comment]
Fork the repo and build on github actions with youtube ipa and uyou 3.0

**Comment by qnblackcat** [comment]
[v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)
