### ISSUE TITLE
[Bug] Downloading speed slow on my device

### ISSUE THREAD

**Issue by dhawan1997** [qnblackcat/uYouPlus#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4.1
- Device model: iPhone 14 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): e-Sign
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.15.1-3.0

### Describe the bug

I don't see the uYouLocal ubutton only the regular uYou download button, I believe. I have checked the latest update, and compared to the previous version, at least the file will download where it was first used, only to give an error. Now the speed varies and is extremely slow. I don't know if there is a bug in my device. Or is it generally a known issue?

I am attaching a screenshot of my speed test for my school wifi, my 5g mobile data, and my house wifi. And the corresponding download speed of the uYou app. I don't have any VPN installed on my device.

Please guide me as even I want to enjoy high speed available in the new update.

![School wifi speed](https://user-images.githubusercontent.com/82213570/232652236-85fad4f5-f382-4c87-86db-bc487c2ece59.jpg)

![School wifi download](https://user-images.githubusercontent.com/82213570/232652259-bb52b3b0-0bc1-425b-893c-6be28153c53e.jpg)

![5g speed](https://user-images.githubusercontent.com/82213570/232652292-9677c869-56d1-4689-be72-4c897d28f4a8.jpg)

![5g download](https://user-images.githubusercontent.com/82213570/232652312-cb82e8c2-54cd-419f-815e-43dd11f343ff.jpg)

![Home wifi speed](https://user-images.githubusercontent.com/82213570/232652326-6eb66493-5b84-491c-ac7c-5c241c7ff991.PNG)

![Home wifi download](https://user-images.githubusercontent.com/82213570/232652349-9a55afe2-d84f-4745-a9fc-222dd3ee3628.jpg)

### Steps to reproduce the issue

1. Open any video
2. Click on uYou button to download, select quality from menu.
3. See the downloading speed in uYou bar

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
Since MiRO92 is updating uYou again, please open a new thread on uYou’s repo: https://github.com/MiRO92/uYou-for-YouTube

**Comment by dhawan1997** [comment]
Hey thank you for your response. I just checked MiRO92 GitHub for uYou. I also tried installing via e-sign and sign.ipasign.cc.

Both times the uYou IPA crashes. On the forum, it says uYou is not compatible with my ios16. 

https://github.com/MiRO92/uYou-for-YouTube/issues/251#issuecomment-1511212075

I am confused as to how foundation uYou is not compatible, but uYouplus is!? That is really cool.

Is there any other advice you suggest I can do to improve my downloading speed through uYouPlus?

**Comment by dhawan1997** [comment]
https://user-images.githubusercontent.com/82213570/232852922-448f5360-f4e8-4eaf-a2e6-034d8451060c.mp4

Please see the video, it shows how the first time the video is downloading slowly, but second time it improves, yet it is capped at 2mbps
