### ISSUE TITLE
[Bug] Comments on YouTube Shorts doesn't load

### ISSUE THREAD

**Issue by notoriousjay08** [qnblackcat/uYouPlus#1081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 3.0 recently, but this was an issue on earlier versions

### Describe the bug

Whenever I view a short and then try to load the comments a blank screen appears and no comments show up. This has nothing to do with the previous issue #1038 it doesn't say the comments are disabled

https://user-images.githubusercontent.com/131211904/232920654-3d2b0e1e-3afb-4342-bf2f-9920d9946474.mov

![2023-04-18 18 28 42](https://user-images.githubusercontent.com/131211904/232920776-2efaab63-c8c9-468c-8aac-4871e54f83a4.png)

### Steps to reproduce the issue

1. Click on a short
2. Tap on the comments
3. A blank screen appears

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

This has nothing to do with the previous issue #1038 it doesn't say the comments are disabled

**Comment by qnblackcat** [comment]
You sure the YouTube app itself is not buggy??
