### ISSUE TITLE
AirPlay Completely Stops Working

### ISSUE THREAD

**Issue by TronziaHQ** [qnblackcat/uYouPlus#1083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 15.3.1
- Device model: iPhone XR
- Sideload software: Trollstore 
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.15.1-3.0

### Describe the bug

In short the bug starts when you try to screenshare/Airplay to say an AppleTV. 
The video player goes black and unresponsive and stays like that until you stop the AirPlay and it goes back to normal.

### Steps to reproduce the issue

1. Open an video and press Airplay to for example an AppleTV.
That’s basically it really, Not much else to it.

### Crash log (if the app crashes)

```shell
No crashes.
```

### Are you using the newest version of uYouPlus? If not, why?

❌ No, I'll explain at the end of the template

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Well the reason I don’t use it right now is only because screen-share / Airplay don’t work. I use a completely different and very aging YouTube ipa from months ago. Not related to uYouPlus even. 

The reason, This app don’t work the other one does.

**Comment by TronziaHQ** [comment]
Ill try to use the latest stable version instead

**Comment by TronziaHQ** [comment]
Changing to v18.08.1-2.3.1 did not solve the issue btw.

**Comment by qnblackcat** [comment]
#1033
