### ISSUE TITLE
[Bug] Can't install uYouPlus v18.15.1-3.0

### ISSUE THREAD

**Issue by schweppes-0x** [qnblackcat/uYouPlus#1084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS: latest 
- iPhone 13 Pro
- AltStore, 
- uYouPlus v18.15.1-3.0:

### Describe the bug

I cant install this version. Tried multiple times but doesnt work. Afterwards AltStore gets message "AltStore is not available". And after this i need to intall ALtstore again via PC.

### Steps to reproduce the issue

1. Download latest release vesrion 
2. Intall with altstore

### Crash log (if the app crashes)

```shell
Altstore get's unavailable
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
Dont think this is uYou’s fault. Try to use Sideloadly instead
