### ISSUE TITLE
Ads in search results again 

### ISSUE THREAD

**Issue by DetachHead** [qnblackcat/uYouPlus#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 15.1.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): trollstore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.15.1-3.0

### Describe the bug

Ads are appearing in search results again as of the latest update (18.15.1-3.0)

![38897A9D-E1DA-465A-9D62-CF333AF8235E](https://user-images.githubusercontent.com/57028336/233224276-6a497e25-0ad7-4785-b3f8-4b1ebffe6f95.jpeg)

Original issue: #81

### Steps to reproduce the issue

1. Go to search tab
2. Make a search

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
uYou 3.0 should block all search ads. If it is not, please report this issue to MiRO92

https://github.com/MiRO92/uYou-for-YouTube

**Comment by DetachHead** [comment]
https://github.com/MiRO92/uYou-for-YouTube/issues/256
