### ISSUE TITLE
[Bug] Update 18.14.1 lost ads block function

### ISSUE THREAD

**Issue by hello159873** [qnblackcat/uYouPlus#1087]
After updating to version 18.14.1 i lost the ability to disable ads, already check all the setting in uyou, and some setting crash the app too

**Comment by hello159873** [comment]
Prove of my app getting ads
![Uploading 5012F187-3013-4973-AA81-EC348FDBB109.png…]()

**Comment by goodcccc** [comment]
open uYou setting and tap Other Setting, turn on the Block Ads feature

**Comment by qnblackcat** [comment]
I never release v18.14.1. Looks like you are using uYou. uYou’s repo is a better place for reporting uYou’s issue

https://github.com/MiRO92/uYou-for-YouTube
