### ISSUE TITLE
[Bug] Sometimes Videos will just stop loading untill you refresh 

### ISSUE THREAD

**Issue by Hex34568** [qnblackcat/uYouPlus#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version:15.7
- Device model: IPad (6th Generation)
- Sideload tool (Esign)
- The specific version of uYouPlus (**[v18.08.1-2.3.1]**):

### Describe the bug

The bug is being around for a while but I don't know anyone else has faced the same issue As far as I remember it was present in (uYou+ 17. x.x.x) versions as well...

https://user-images.githubusercontent.com/103202023/233310534-1c79a5fe-7f74-4a12-92f4-d90e55af7d06.MOV

### Steps to reproduce the issue

It happens randomly and I don't know if this issue was present in the original Youtube app.

### Are you using the newest version of uYouPlus? If not, why?

❌ No, I'll explain at the end of the template

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Except for the issue I described, I couldn't find any other issues, uYou+ has been working really fine with no issues at all... and the reason why I am not on the latest version is that it's still a prerelease version I’ll update the app as soon as it becomes a stable release

**Comment by qnblackcat** [comment]
I doubt this is an issue of uYou/uYou+. Could be YouTube  app just doesn't want to work correctly 🤷‍♂️ 

And yes, you better stay away from the pre-release version.

**Comment by Hex34568** [comment]
> I doubt this is an issue of uYou/uYou+. Could be YouTube app just doesn't want to work correctly 🤷‍♂️
> 
> And yes, you better stay away from the pre-release version.

Alright thanks
