### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by LillieH001** [qnblackcat/uYouPlus#109]
Hello, recently I was made aware of you merging in features from my YouTube Reborn v3 project. This is a violation of my gplv3 license as per uyou, the project you base this off is not open source, which gpvl3 requires everything in a project to be open source. Also gplv3 requires the project to be under the same license which this project is not under. Can you please remove my code, I don't want to take further action.

**Comment by qnblackcat** [comment]
Oh. I understand it. Would you mind if I make a separate tweak based on YouTube Reborn and inject it to uyou+ using theos-jailed?

**Comment by LillieH001** [comment]
No, that would still be a license violation as per uyou is not open source which gplv3 requires all of the stuff used in a project to be open source and this project doesn't use the gplv3 license either (as stated in my first message, both those are in violation of my gplv3 license).

**Comment by qnblackcat** [comment]
I’ve just removed all the violation codes. Sorry for bothering you!
