### ISSUE TITLE
uYouLocal gone?

### ISSUE THREAD

**Issue by naddel91** [qnblackcat/uYouPlus#1093]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Cannot find the option to boost Download speeds.
Where is Local gone?

Best wishes!

**Comment by qnblackcat** [comment]
uYouLocal is the default download option of uYou now

**Comment by Nixuge** [comment]
Miro doesn't have a good method to download videos, all he'd had to do is just use yt-dlp, but he keeps on writing his own downloader which is slow af
No fix unfortunately :/
