### ISSUE TITLE
[Questions] Different animations in iPad layout.

### ISSUE THREAD

**Issue by Shy1nx** [qnblackcat/uYouPlus#1095]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [x] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

When you enable the iPad layout, the animations changes. And actually they're not good looking as the stock ones. When you do the fullscreen gesture, a bad animation comes out. I don't think it's a bug, I think it's the iPad animations. Can't we use iPad layout with stock animations?

**Comment by qnblackcat** [comment]
Sorry but I can’t do that
