### ISSUE TITLE
Is there no Auto-refresh feature with Sideloadly?

### ISSUE THREAD

**Issue by ogkimra** [qnblackcat/uYouPlus#1096]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I have 3 apps and a non-developer apple account. 2 apps auto refresh before the 7 day validity expires if I keep my pc open but uYou+ wont auto update, I need to fresh install it again every 7 days. Is this how it is meant to work or Is it a bug? I read the FAQ and it said to reinstall everytime so just want to confirm because auto refresh in sideloadly is kinda new to me.

**Comment by qnblackcat** [comment]
Wrong place to report Sideloadly’s issue...

**Comment by ogkimra** [comment]
The other apps are getting auto refreshed but uyou isnt, so its still sideloadly's issue? I am confused ;-;
