### ISSUE TITLE
[Questions] Could you please bring back sort by oldest

### ISSUE THREAD

**Issue by ayoosh007** [qnblackcat/uYouPlus#1097]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Please bring back sort by oldest to youtube it’s a huge QOL change

### Additional context

If possible could you also make the option to share url with timestamps embedded

**Comment by qnblackcat** [comment]
I can't. Sorry
