### ISSUE TITLE
[Bug] it stays in the logo youtube

### ISSUE THREAD

**Issue by chupit0** [qnblackcat/uYouPlus#1098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 15.5
- Device model: 13 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): trollstore, altstore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.15.1-3.0)

### Describe the bug

when downloading any video or audio, when closing the app completely while downloading it gets stuck on youtube logo and doesn't reopen the app stays on youtube logo.
 uyou 3.0

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
uYou’s repo is a better place for reporting uYou’s issue

https://github.com/MiRO92/uYou-for-YouTube
