### ISSUE TITLE
[Bug] uYou gesture controls don’t work in latest release

### ISSUE THREAD

**Issue by Blockr22** [qnblackcat/uYouPlus#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS version:16.4.1
- Device model:iPhone 14
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sidestore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.15.1

### Describe the bug

Same as title

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
#506
