### ISSUE TITLE
(bug）can’t keep 1080p even i have opened high picture quality.

### ISSUE THREAD

**Issue by LucasIsGood** [qnblackcat/uYouPlus#11]
![IMG_0025](https://user-images.githubusercontent.com/56297860/143843473-a09c3ad9-fd0d-4f58-bafb-728d6b13ed05.png)
![IMG_0023](https://user-images.githubusercontent.com/56297860/143843804-2849645e-07b3-47fe-b8bb-7f7dcd756ed1.png)

**Comment by qnblackcat** [comment]
Are you sure Legacy PiP is disabled?

**Comment by LucasIsGood** [comment]
![IMG_0028](https://user-images.githubusercontent.com/56297860/143907938-26f37f57-ca82-4244-8bae-d7a856728dd9.png)
yeah it’s disabled

**Comment by qnblackcat** [comment]
The video in your post, it doesn‘t even have 2K quality

**Comment by qnblackcat** [comment]
You should use the Default video quality settings from uYou, not YouTube

**Comment by LucasIsGood** [comment]
u mean i should use uYou instead of uYou plus and use the default video settings ,right?

**Comment by qnblackcat** [comment]
> You should use the Default video quality settings from uYou

![D8385D73-E811-47CC-85DF-354A4686AE47](https://user-images.githubusercontent.com/52943116/143980782-ba6aee81-e13e-4159-93a4-1c3d325cc1de.png)

**Comment by LucasIsGood** [comment]
![IMG_0034](https://user-images.githubusercontent.com/56297860/144013078-5383f1dc-4eb7-481d-898c-cbce00abec22.png)
it worked！！！thanks for your help！

**Comment by qnblackcat** [comment]
No problem!
