### ISSUE TITLE
Playlists Don't Show

### ISSUE THREAD

**Issue by punchyouinthenuts** [qnblackcat/uYouPlus#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.4.1
- Device model: iPhone 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): appdb
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.16.2-3.0

### Describe the bug

Clicking on a playlist displays a blank page (tried to upload videos and GIFs but neither would upload). Clicking on playlist results in first image, followed by second image.

![IMG_5589](https://user-images.githubusercontent.com/53103127/234940213-f9ae306d-c744-4e14-9a95-01c81096f252.png)
![IMG_5590](https://user-images.githubusercontent.com/53103127/234940230-bb349eec-4469-49ba-a111-7cc4f69841cb.png)

### Steps to reproduce the issue

1. Close and re-open app
2. Delete and reinstall
3. Tried every playlist

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

I didn't have this issue until I upgraded to this version. Even when downgrading the issue remains.

**Comment by qnblackcat** [comment]
Sorry. I never release _v18.16.2-3.0_

**Comment by punchyouinthenuts** [comment]
> Sorry. I never release _v18.16.2-3.0_

This is what it shows on appdb

![image](https://user-images.githubusercontent.com/53103127/234941796-8664f520-77fb-436e-9793-0fc65072ff93.png)

**Comment by qnblackcat** [comment]
I’m sorry. That wasn't me.
