### ISSUE TITLE
[Questions] End for Qnblackcat

### ISSUE THREAD

**Issue by gh0sti** [qnblackcat/uYouPlus#1102]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

for @qnblackcat how come you will be done with updating this project?

**Comment by RandomLuckyGuy** [comment]
As what I’ve read his done with it because of the oled I guess.
@qnblackcat need more info, Oled is not an issue for me.
uYou+ forever.

**Comment by yodaluca23** [comment]
> As what I’ve read his done with it because of the oled I guess.
> 
> @qnblackcat need more info, Oled is not an issue for me.
> 
> uYou+ forever.

I don't think that's why… But yeah, it was working fine for me in the pre-release as well

**Comment by azalty** [comment]
Pretty sad to see. Support, documentation, all that was great :)

❤️

**Comment by qnblackcat** [comment]
> As what I’ve read his done with it because of the oled I guess.
> @qnblackcat need more info, Oled is not an issue for me.
> uYou+ forever.

We had a dozen of more serious issues in the past. Most of them are resolved eventually. OLED dark mode is just another issue, nothing special about it

**Comment by qnblackcat** [comment]
If you’re still wondering, I explained the situation here

https://twitter.com/t70438299/status/1651733875880779781?

**Comment by WoodpeckerBaby** [comment]
> > The app will be updated by other developers. This is probably the last time I - qnblackcat, update uYouPlus. Enjoys!
> 
> 
> 
> Do you already have someone in mind?
> 
> 
> 
> Looks like the most popular fork of this repo is https://github.com/arichorn/uYouPlusExtra (by @arichorn), but not sure if he actually wants to take over or was just a contributor
> 
> (He responded in his Q&A: https://github.com/arichorn/uYouPlusExtra/discussions/29#discussion-5138632)
> 
> 

I think those two project should just merge, but I sense that the developers may have beef or ideological differences.

**Comment by peterrauscher** [comment]
Thanks for all of your hard work. Good luck moving forward in life!
