### ISSUE TITLE
[Bug] Set app as default Youtube links opener

### ISSUE THREAD

**Issue by Saud-97** [qnblackcat/uYouPlus#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS
- Device model: iPhone 14 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**):  v18.14.1-3.0

### Describe the bug

I would like to delete the official Youtube and make the modded uYou+ youtube the default player for all youtube links.

### Steps to reproduce the issue

1.  Open a youtube link from any app
2.  The link will be opened in the default browser instead of this app.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

I have found a similar question to another youtube player here on this [Reddit](https://www.reddit.com/r/sideloaded/comments/pwcyhm/question_how_to_make_uyoureborn_the_default_app/). However this involves sharing the youtube link manually and triggering a shortcut.

**Comment by yodaluca23** [comment]
Please Read [the FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-deep-link-aka-open-in-the-youtube-app-doesnt-work) before making a new issue...
