### ISSUE TITLE
[Bug] Button misplace in Shorts videos

### ISSUE THREAD

**Issue by galaxy4627** [qnblackcat/uYouPlus#111]
### Device info
- iOS/iPadOS version: 15.5
- Device model: Iphone 13 pro
- Sideload tool (Ex: AltStore, Sideloadly...) Sideloadly
- Version of uYouPlus: 17.15.1_2.1

### Describe the bug
Buttons are misplaced on YouTube Shorts.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Simply watch Shorts.
![IMG_5020](https://user-images.githubusercontent.com/100154768/163927703-717d5120-30d4-4c43-b388-8260f79b1cf8.png)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by paulscholes0258** [comment]
I confirm I have the same problem. please fix. thanks .

**Comment by DeZomTheProto** [comment]
Same problem here, iPhone Xr IOS 14.2.

**Comment by arichorn** [comment]
Same issue too. Those buttons are always in the way when using YouTube shorts on iPads.

**Comment by IceBotYT** [comment]
Now it does not appear at all for me

**Comment by qnblackcat** [comment]
merge with issue https://github.com/qnblackcat/uYouPlus/issues/170
