### ISSUE TITLE
[Questions] uYouPlus+Sideloadly can not download video

### ISSUE THREAD

**Issue by HuongNV83** [qnblackcat/uYouPlus#1113]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

I am using sideloadly (0.41.2) install uYouPlus(18.14.1), but Youtube can't download video (download failed). Can you fix it or any solution for this.

![IMG_0955](https://user-images.githubusercontent.com/63854457/236396366-d98a9920-1dc1-4a50-b78d-f82b95479e04.png)

**Comment by xorbital** [comment]
As far as I know to use the YouTube download mechanism you need to subscribe to YouTube Premium, however you can use uYou:
- Open the video you want to download
- In the top right, look for the uYou Logo (usually below the cogwheel)
- Tap it, select the desired quality
![IMG_DB591E48625F-1](https://user-images.githubusercontent.com/53773184/236613606-0ec68283-272e-401f-8c88-fea9a40e337b.jpeg)

**Comment by HuongNV83** [comment]
Thank you!
