### ISSUE TITLE
[Questions] How do I download Videos?

### ISSUE THREAD

**Issue by SkyKingPX** [qnblackcat/uYouPlus#1114]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

How do I download them? I cannot find any button for this

**Comment by xorbital** [comment]
In the video player, press the uYou logo on the top right (usually below the cogwheel)

**Comment by SkyKingPX** [comment]
Where @xorbital ![image](https://user-images.githubusercontent.com/95442431/236613641-95e0d306-c82a-4eaf-a259-e253cbbb434c.jpeg)

**Comment by xorbital** [comment]
It should look like this:
![IMG_DB591E48625F-1](https://user-images.githubusercontent.com/53773184/236613778-b8fce7f2-ea5b-4ea3-a5b4-b10158404e07.jpeg)
Seems like that button is disabled for you.
- Open up the App, tap "uYou" in the bottom right corner of the screen
- Open up the settings (red cogwheel) on the top right
- Tap "Video Player" under "YT Settings"
- Enable "uYou"

**Comment by SkyKingPX** [comment]
Thank you. Now I see it.

But a last question: Can I download whole Playlists?

**Comment by SkyKingPX** [comment]
And why I can't see a Playlist? https://user-images.githubusercontent.com/95442431/236615199-998f8060-186d-41d3-8a2a-7f3e6ed4e329.MOV

**Comment by SkyKingPX** [comment]
@xorbital

**Comment by xorbital** [comment]
I don’t think you can download playlists with uYou

The playlist you showed in the video displays fine for me, are you on the latest version of uYou+? If yes, have you tried reinstalling?

**Comment by SkyKingPX** [comment]
I can try it.

**Comment by SkyKingPX** [comment]
I tried it with the ipa from the Releases and now all is working 🙂
