### ISSUE TITLE
uYou+ installation only shows uYou information in settings page

### ISSUE THREAD

**Issue by Staubgeborener** [qnblackcat/uYouPlus#1115]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

this is a thing I always wondered about but couldn’t find anything in the internet: I am using uYou+ 18.08.1. in the settings page there is now word about uYou+ but about uYou v2.1, also hitting this update button leads to the uYou website. But I can use uYou+ features like the implementation of iSponsorBlock. 

Here is a video of the behavior which explains and shows everything: https://imgur.com/a/hrrGZDJ

**Comment by xorbital** [comment]
uYou+ is a bundle of multiple tweaks, including **uYou**, so if you open **uYou** within the app and go to their project page, we’ll, it’ll take you to their project page.
Just like going into „YouTube Settings - uYouPlus - Check for updates“ will take you to this repository.

By the way, uYou+ now includes uYou 3.0 in the latest version that was released a week ago, so you might want to update.

**Comment by Staubgeborener** [comment]
Alright, good to know. I was quite confused. Is there an easy way to update uYou+ or do I have to download the latest release every time from GitHub?

**Comment by xorbital** [comment]
You could subscribe to AltStores Patreon to access custom repositories which would allow you to update on your device (given that AltServer is running). Please also read the Readme / Repository main page under [Downloads](https://github.com/qnblackcat/uYouPlus#download)
Personally, I use Sideloadly, I find it to be much more stable.
It seems like the update to the latest version might require a fresh install (removing the old one first) if you have issues browsing playlists.

**Comment by Staubgeborener** [comment]
ok, thanks so far. I will close this issue.
