### ISSUE TITLE
[Bug] Chance For The Comments Section To Be Blank

### ISSUE THREAD

**Issue by CodeExo4tic** [qnblackcat/uYouPlus#1119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.4.1 (a)
- Device model: iPhone 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.14.1-3.0

### Describe the bug

When watching mostly Shorts and then opening the Comments section, there is a chance that it will just be blank. No amount of refresh will fix it. Closing YT fixes the issue sometimes, but it returns after some time.

### Steps to reproduce the issue

1. Watch YT Videos or Shorts
2. Open Comment Sections
3. N/A

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by anonymousaga** [comment]
![IMG_2764](https://github.com/qnblackcat/uYouPlus/assets/68388009/58bea79b-591d-4c36-b75c-a70522816b3e)
Like this? This is the issue im having.

**Comment by CodeExo4tic** [comment]
> ![IMG_2764](https://user-images.githubusercontent.com/68388009/238156679-58bea79b-591d-4c36-b75c-a70522816b3e.png)
> Like this? This is the issue im having.

Yes exactly like this

**Comment by qnblackcat** [comment]
YouTube’s issue
