### ISSUE TITLE
App crashes when going into YouTube settings

### ISSUE THREAD

**Issue by korboybeats** [qnblackcat/uYouPlus#112]
### Device info
- iOS/iPadOS version: iPadOS 15.3.1
- Device model: M1 iPad Pro 2021
- Sideload tool (Ex: AltStore, Sideloadly...) Signulous
- Version of uYouPlus: v17.15.1-2.1

### Describe the bug
uYouPlus crashes when trying to go into native YouTube settings.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

[https://imgur.com/GGHK6iJ](url)

**Comment by qnblackcat** [comment]
Get the ipa of YouTube v16.42.3

**Comment by korboybeats** [comment]
> Get the ipa of YouTube v16.42.3

It doesn't crash on v17.14.2

**Comment by korboybeats** [comment]
> Get the ipa of YouTube v16.42.3

It crashes on 16.42.3_2.1 as well

**Comment by qnblackcat** [comment]
Might be an issue of iPad. How does the settings of vanilla YouTube on iPad look like?

**Comment by korboybeats** [comment]
> Might be an issue of iPad. How does the settings of vanilla YouTube on iPad look like?

![E5E27792-9D9E-4F1E-BBD4-E10ABF7B1216](https://user-images.githubusercontent.com/80824905/164015923-c9f635c8-8fe7-4454-9121-c588a0065371.png)

**Comment by korboybeats** [comment]
> can you try this IPA?
> 
> [uYouPlus_17.15.1_2.1_iPad_F1](https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/ERw1Rt6h_qVKsNoi1vxliv0BU9i54OxpiGDXsk_6SBEZjw?download=1)

That works 🙏
