### ISSUE TITLE
[Bug] double tap to seek does nothing 

### ISSUE THREAD

**Issue by user2393** [qnblackcat/uYouPlus#1120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS 16.2:
- Device model: 12 mini
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 3.0

### Describe the bug

Double tap to seek and it doesn't do anything, just plays again from the exact same second. -.-

### Steps to reproduce the issue

1. Double tap to seek 
2. Doesn't work 
3. ???

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
uYou’s issue, similar to #802
