### ISSUE TITLE
Did you remove the SponsorBlock?

### ISSUE THREAD

**Issue by peter9811** [qnblackcat/uYouPlus#1122]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Did you remove the SponsorBlock?
I tried to search but I didn't found it

**Comment by fred2348** [comment]
Is it possible you installed UYou instead of UYouPlus?

**Comment by peter9811** [comment]
I don’t know what happened but two days ago I was listening music and didn’t skip the intro and I was looking for the settings on the YouTube setting, but apparently don’t stay on the same location like Android 

Today when I update the Sideloadly for another 7 days, apparently works again… WDF 

I yeah, I can see the Ivón on the Home Screen of YouTube. Thanks for help me

**Comment by qnblackcat** [comment]
We didn’t remove iSponsorBlock
