### ISSUE TITLE
[Questions] In support of qnblackcat - Thanks for everything!

### ISSUE THREAD

**Issue by gmanc2** [qnblackcat/uYouPlus#1124]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

I watch an inordinate amount of youtube, and your skill in development has saved me days/months of frustration with youtube and ads. I really have to thank you for the time you've spent developing this, and I really wish you wouldn't quit. I'm sure I and others would love to send you a few bucks to continue. The time and effort you've spent making this don't go unnoticed, and again from me and all of the community you've built, thank you! If you ever need help with anything in the future feel free to ask I'd love to help!

**Comment by PsycloneTM** [comment]
Why is he quitting?

**Comment by qnblackcat** [comment]
@gmanc2 

Hello there, I really appreciate your kind. The main reason I stopped participating in the development of uYou+ is simply because I'm too busy with life. 

If you want to contribute, you can support other developers here: https://github.com/qnblackcat/uYouPlus#support-the-developers

**Comment by ntt77** [comment]
@qnblackcat thank for your helpful YouTube mod.
but could you place the guideline about what we should do to update the uYouPlus here, maybe some members here could help you to continue develop uYouPlus.

**Comment by gmanc2** [comment]
> @gmanc2
> 
> Hello there, I really appreciate your kind. The main reason I stopped participating in the development of uYou+ is simply because I'm too busy with life.
> 
> If you want to contribute, you can support other developers here: https://github.com/qnblackcat/uYouPlus#support-the-developers

I started learning how to work in the Apple ecosystem I might contribute in the future, Gmanc2#4316 is my discord if you would like to collaborate. I really wish you the best in your endeavors and hope you return sometime in the future! Best of luck 😄❤️

**Comment by Blarnix** [comment]
Thank you for everything. I want to learn how to develop apps and I hope that I'm going to be able to help this app stay alive. I have to stress how important this app is for using YouTube, I can't watch YouTube on my iPhone without it. Thank you again.
