### ISSUE TITLE
[Bug] stuck on startup alert (with follow me on twitter option)

### ISSUE THREAD

**Issue by Serjio3** [qnblackcat/uYouPlus#1128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4
- Device model: iPhone 12 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**):v18.14.1-3 latest update april 28

### Describe the bug

I installed uyouplus on iphone using altstore through [qnblackcat](https://github.com/qnblackcat)
/
[uYouPlus](https://github.com/qnblackcat/uYouPlus)
the app installed successfully, when I start the app, it stuck on startup screen alert (uYou the best tweak for the Youtube....) and option to follow @MiRO92 on twitter, I have followed MiRO92 on twitter , tried from safari and brave browsers but the startup screen alert never disappear and I can't access anything
I tried to reinstall app but same issue

![proof Image ](https://github.com/qnblackcat/uYouPlus/assets/133970918/992d285f-e7f0-4ef6-8a4f-68ff8bbff267)

### Steps to reproduce the issue

1. Downloaded app using altstore
2. launched
3.the problem occur
![proof Image ](https://github.com/qnblackcat/uYouPlus/assets/133970918/992d285f-e7f0-4ef6-8a4f-68ff8bbff267)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by Sethycakes** [comment]
Why was this issue closed? Was it fixed? This is happening to me on the latest version (18.14.1_3.0). I even tried downgrading to 17.48.2_2.1 and I'm still experiencing this.
