### ISSUE TITLE
[Bug] When trying to download a thumbnail the app crashes

### ISSUE THREAD

**Issue by gogeta01** [qnblackcat/uYouPlus#1131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.5
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): [v18.14.1-3.0]

### Describe the bug

When trying to download aa thumbnail the app crashes

### Steps to reproduce the issue

1.  Try to download a thumbnail of a video
2.  ......
3. Crash

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
sorry but I don't think there is an option to download a video thumbnail
