### ISSUE TITLE
[Bug] Why I can not install uYou+.ipa to my iPhone

### ISSUE THREAD

**Issue by trankien200691** [qnblackcat/uYouPlus#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS version: 16.2
- Device model: iPhone 13 PRM
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.14.1-3.0

### Describe the bug

I have used uYou+ for almost 2 years and now I am facing a problem that I don't know how to fix it. My computer is already installed AltServer, and iCloud and I can install AltStore on my phone easily. But when I open it, and tap the (+) button to add the uYou+, the AltStore app is always loading. What should I do?

### Steps to reproduce the issue

1. install AltStore to my iPhone from the computer after inputting the user/password of the iCloud account
2. open AltStore on the phone and tap on the Add button to add youtube.ipa file
3. the AltStore app on the phone is still loading without any notification
4. If I force to close the app before youtube has been installed, the AltStore is also "no longer available" like the youtube app when it expires

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by jimmyedagawa78** [comment]
I faced the same issue on my iPhone 13 running beta 16.5 with altstore installed via Windows 11
In my experience, the only workaround is to uninstall the app completely and reinstall it every time you want to update the app.

**Comment by trankien200691** [comment]
> I faced the same issue on my iPhone 13 running beta 16.5 with altstore installed via Windows 11 In my experience, the only workaround is to uninstall the app completely and reinstall it every time you want to update the app.

actually, I usually re-install the app every week but I just realized that the AltStore Profile has disappeared in the VPN And Device Management, but I don't know how to revoke it again because nothing happens if I pluggin' the phone into the laptop has AltServer

**Comment by LolekLiam** [comment]
or just use sideloadly
