### ISSUE TITLE
[Questions] Add new patch

### ISSUE THREAD

**Issue by YT-Advanced** [qnblackcat/uYouPlus#1135]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Dear sir. Today I'm insterested in building app. I have checked all feauture that your Youtube Modded app have but some of patch by PoomSmart is not included. Can you add it or modify the docs for helping people add it to the app.

Vietnamese: Hello bác, chả là hôm nay lướt facebook tình cờ thấy app của bác được các anh em giới thiệu. Em có xem qua các tính năng trong phần feauture thì thấy có 1 số cái chưa được thêm vào app của bác. Nếu bác không phiền thì có thể thêm mấy patch đó vào được không ạ. Em cảm ơn, list em để bên dưới chỗ Additional context nhé.

### AMOLED mode:
- https://github.com/PoomSmart/YTDarker
- https://github.com/PoomSmart/YTDarker-uYou
### Video Overlay:
- https://github.com/JamieBerghmans/HideYTOverlay (Hide Youtube Overlay Background)
- https://github.com/PoomSmart/YouMute (Add Mute button to overlay)
### For Short:
- https://github.com/PoomSmart/YTShortsProgress (Add Youtube Short Progress Bar)
- https://github.com/PoomSmart/YTUnShorts (Remove Youtube Short)
- https://github.com/Galactic-Dev/YTNoShortsButton (Hide Youtube Short Button)
### Others:
- https://github.com/PoomSmart/YTSystemAppearance (Enable setting appearance based on system in YouTube app)

**Comment by dayanch96** [comment]
Everything except YTDarker and HideYTOverlay already included as far as i know. you can add other tweaks manually if you want

**Comment by YT-Advanced** [comment]
@dayanch96 Can you tell me how to add it please ?

**Comment by dayanch96** [comment]
https://github.com/Al4ise/Azule

**Comment by qnblackcat** [comment]
> Hello bác, chả là hôm nay lướt facebook tình cờ thấy app của bác được các anh em giới thiệu. Em có xem qua các tính năng trong phần feauture thì thấy có 1 số cái chưa được thêm vào app của bác. Nếu bác không phiền thì có thể thêm mấy patch đó vào được không ạ. Em cảm ơn, list em để bên dưới chỗ Additional context nhé.

Tất cả các tweak bạn liệt kê đều có sẵn trong uYou+ rồi nhé, đa số là được bật sẵn luôn, còn lại có thể thấy trong setting của uYou
