### ISSUE TITLE
Attempting to delete downloads freezes the app

### ISSUE THREAD

**Issue by Dyynex** [qnblackcat/uYouPlus#1137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version:
- Device model: iPhone 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.14.1-3.0

### Describe the bug

When pressing delete for any downloads in uYou tab it freezes the app. This also happens when clicking clear downloaded/clear all in the uYou settings, as well as when trying to rename things. Requires force closing app

### Steps to reproduce the issue

1. Open uYou tab
2. Click 3 dots on a downloaded video/audio
3. Click delete

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
please report this issue to MiRO92 which is the dev of uYou https://github.com/MiRO92/uYou-for-YouTube
