### ISSUE TITLE
Tapping “Play next in queue” shows YouTube Premium page

### ISSUE THREAD

**Issue by IceBotYT** [qnblackcat/uYouPlus#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.5
- Device model: iPhone 14 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.14.1-3.0

### Describe the bug

When I tap “Play next in queue” it opens up the YouTube Premium page. Is it possible to unlock this for non-Premium members?

https://github.com/qnblackcat/uYouPlus/assets/34712694/4fc7896d-9888-47a9-8351-a8e784607fdb

### Steps to reproduce the issue

1. Find any video
2. Open the context menu (three dots)
3. Tap “Play next in queue”

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by dayanch96** [comment]
Its not bug. Its new feature which requires premium

**Comment by chadify** [comment]
> Its not bug. Its new feature which requires premium

Is it possible to enable this with uYou without premium?

**Comment by dayanch96** [comment]
> > Its not bug. Its new feature which requires premium
> 
> Is it possible to enable this with uYou without premium?

No

**Comment by favna** [comment]
In that case can uYou+ add a feature to hide this item? It's messing extremely much with my muscle memory to press the top option that used to be add to watch later. From a UX perspective (or lack therefore rather) YouTube clearly put this item on top on purpose, it's a very clear dark pattern.

**Comment by level3tjg** [comment]
> In that case can uYou+ add a feature to hide this item? 

I'll add it sometime this afternoon

**Comment by PoomSmart** [comment]
```
%hook YTMenuItemVisibilityHandler

- (BOOL)shouldShowServiceItemRenderer:(YTIMenuConditionalServiceItemRenderer *)renderer {
    return renderer.icon.iconType == 251 ? NO : %orig;
}

%end
```

**Comment by evkaw** [comment]
sorry, how would i disable the feature? I'm on the newest version

**Comment by HexCodeFFF** [comment]
Could this be a toggleable feature or detect premium status? I have premium and I want to be able to use this feature in uYouPlus

**Comment by chadify** [comment]
> %hook YTMenuItemVisibilityHandler
> 
> - (BOOL)shouldShowServiceItemRenderer:(YTIMenuConditionalServiceItemRenderer *)renderer {
>     return renderer.icon.iconType == 251 ? NO : %orig;
> }
> 
> %end

Side question: is possible to hide home button(not present in youplus options) and open directly subscriptions page?
