### ISSUE TITLE
Oled mode doesn’t support an oled keyboard 

### ISSUE THREAD

**Issue by AdiA105** [qnblackcat/uYouPlus#114]
It can definitely be done as seen in uyou OLED.

**Comment by qnblackcat** [comment]
If this ipa doesn't work then I'm have no idea

[uYouPlus_17.15.1_2.1_F3.ipa](https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/EWrA2cb6QBhJkAv_wyMZD90BxCDdF0YOI_cNiO7StzgATQ?download=1)

**Comment by AdiA105** [comment]
> If this ipa doesn't work then I have no idea
> 
> 
> 
> [uYouPlus_17.15.1_2.1_F3.ipa](https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/EWrA2cb6QBhJkAv_wyMZD90BxCDdF0YOI_cNiO7StzgATQ?download=1)

Works great but the bottom bar and word prediction are still grey

**Comment by qnblackcat** [comment]
Closed because I don’t think it’s possible to colored the keyboard on jailed device

**Comment by AdiA105** [comment]
This is not true. This ipa has real full OLED [uyou OLED](https://appdb.to/app/cydia/1900000869)

**Comment by qnblackcat** [comment]
I‘ll take a look at it later
