### ISSUE TITLE
[Bug] URL not supported - code 1002

### ISSUE THREAD

**Issue by IDontKnowWhatNameToPutHere** [qnblackcat/uYouPlus#1141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 14.0
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (latest or newest is NOT a version number!): v18.14.1-3.0

### Describe the bug

![D5A773BF-984A-4F6A-AE17-47100DD2A200](https://github.com/qnblackcat/uYouPlus/assets/78613501/68d8d834-38f7-49bc-ba49-864672391eac)

### Steps to reproduce the issue

1. Go on video and open up the video download gui
2. Click Audio Only (webm)
3. Not downloading but instead displays Error 0 - URL not supported

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

I did already make an issue about this, got told to update but it still doesnt work

**Comment by qnblackcat** [comment]
uYou's issue. Please report the problem to MiRO92: https://github.com/MiRO92/uYou-for-YouTube
