### ISSUE TITLE
[Question] safe place to download YouTube for fork

### ISSUE THREAD

**Issue by dragonplus8** [qnblackcat/uYouPlus#1146]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Where  be a safe place to download the ipa so i know it hasn’t been tampered with?

**Comment by level3tjg** [comment]
https://github.com/qnblackcat/uYouPlus/releases

Compare the SHA256 from the change logs with the downloaded ipa's hash to validate
