### ISSUE TITLE
[Bug] A blocking screen don't allow me to view uYouPlus

### ISSUE THREAD

**Issue by medamine2** [qnblackcat/uYouPlus#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4.1
- Device model: iPhone 12
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.14.1

### Describe the bug

- After installing uYouPlus , I get this interface banning me to use it :

![351559287_777588160737412_6186945880982427818_n](https://github.com/qnblackcat/uYouPlus/assets/10543926/b5ce8a91-a1b9-41e8-9bc1-c702f9e1a053)

Can you help, please?

Thanks

### Steps to reproduce the issue

1.  Installa uYouplus
2.  Open it from the phone's home
3.  Having the screen ban me from using uYouPlus
![351559287_777588160737412_6186945880982427818_n](https://github.com/qnblackcat/uYouPlus/assets/10543926/d9ebc001-fe00-4c41-a865-5a2db0782754)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by yodaluca23** [comment]
It looks like some sort of accessibility feature like a text enlargement is making it not the right size. You could try making a app, specific settings profile for YouTube, and tweaking the accessibility features till you can get past it.
