### ISSUE TITLE
Remove from videos the UI buttons.

### ISSUE THREAD

**Issue by mpekaross** [qnblackcat/uYouPlus#1148]
Is there a way to remove the playback speed, And those uyou buttons? Those aren't removable in the latest version.

 ![image](https://github.com/qnblackcat/uYouPlus/assets/118194554/f9121de8-a71a-4a29-94c6-c3f7a3652682)

**Comment by dayanch96** [comment]
Open uYou tab -> settings icon -> player options

**Comment by mpekaross** [comment]
> Open uYou tab -> settings icon -> player options

Yooo I am blind I didn't saw them anyway thanks mate.
