### ISSUE TITLE
uYouPlus_18.14.1_3.0 (123.9)

### ISSUE THREAD

**Issue by Gfgvh12** [qnblackcat/uYouPlus#1149]
Im in ios 14.2 and when I swipe up out of the youtube app the pip shows up. However when I close my phone the youtube video stops playing and I have to reopen my phone to be able just to play the youtube video. I dont have a problem with Uyou v 17.48.2.1 on my iPhone 12 ios 15. Why is pip not playing when i close my phone??

**Comment by level3tjg** [comment]
Picture in picture doesn't have background playback in iOS 14.
