### ISSUE TITLE
[Bug] Can;t install uYouPlus 8.14.1_3.0

### ISSUE THREAD

**Issue by schweppes-0x** [qnblackcat/uYouPlus#1153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: Latest iOs (16.5)
- Device model: Iphone 13Pro
- Sideload tool AltStore AND Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 8.14.1_3.0

### Describe the bug

I cant seem to install this version on my phone ? I also tried older versions but nothing worked. I get this error:
![image](https://github.com/qnblackcat/uYouPlus/assets/88944709/cc7cf7d1-706f-46bf-bdb3-75a3f7d14a6d)

### Steps to reproduce the issue

1. download version
2. try installing
3. get error

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by kobitate** [comment]
Check the FAQ one more time…

**Comment by 420-420** [comment]
I download this on my 16.5 with sideloadly that’s the only one I can use on that device. But here’s the deal go to advanced options on sideloadly check the box with app spoofer bottom right and make sure under signing mode it’s Apple ID spoofer is checked off scarlet and AltStore didn’t work on that device on my jb ones i can use whatever so try that. Someone suggested that a while ago here and it needs to be sideloaded like every 5-7 days but it works. Hope I helped

**Comment by aco228** [comment]
> I download this on my 16.5 with sideloadly that’s the only one I can use on that device. But here’s the deal go to advanced options on sideloadly check the box with app spoofer bottom right and make sure under signing mode it’s Apple ID and inject Dylan’s/ frameworks and side load spoofer is checked off scarlet and AltStore didn’t work on that device on my jb ones i can use whatever so try that. Someone suggested that a while ago here and it needs to be sideloaded like every 5-7 days but it works. Hope I helped

I have no idea what you wrote :D
