### ISSUE TITLE
Build and Release uYouPlus Workflow Action Fails, Again

### ISSUE THREAD

**Issue by Chimbul** [qnblackcat/uYouPlus#1155]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

For the past few days I've been trying to build uYouPlus on my fork and it had failed. No code changes, I just keep it up to date with this git and try latest changes. Same error, same place every time. Here is the error:

![image](https://github.com/qnblackcat/uYouPlus/assets/8114661/95b88392-ed64-446a-95b3-5e77d3e0fe4f)

Thanks !!

**Comment by qnblackcat** [comment]
In your workflow file, edit     
```runs-on: macos-latest``` 
to
```runs-on: macos-11```

**Comment by iamnabilzaman** [comment]
==> Error: Failed to unzip YouTube.ipa
==> Unpacking YouTube.ipa…
make: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/mod/jailed/package/ipa-jailed.mk:11: internal-package] Error 1
Error: Process completed with exit code 2.

now I'm facing this error....

**Comment by qnblackcat** [comment]
You sure your direct link is working correctly?

**Comment by qnblackcat** [comment]
Wrong link. Try other host

![70FB7F15-1CDE-4A2E-A422-0103A6AD2FC0](https://github.com/qnblackcat/uYouPlus/assets/52943116/cfc6e108-2e82-44d6-94e3-945f12d7da68)

**Comment by qnblackcat** [comment]
Don’t blindly trust the command. Your second link is obv not a direct link.

**Comment by iamnabilzaman** [comment]
okay let me try with another platform weshare ok?

**Comment by iamnabilzaman** [comment]
same error:- ==> Error: Failed to unzip YouTube.ipa
make: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/mod/jailed/package/ipa-jailed.mk:11: internal-package] Error 1
==> Unpacking YouTube.ipa…
Error: Process completed with exit code 2.

environment showing this:-
Run wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa && echo -e "==> \033[1mYouTube v17.39.4 downloaded! \033[0m"

2023-06-19 09:31:10 URL:https://drive.google.com/uc?id=1UQNrowUvYRC-rA1mvJ17MUfdu_HTNZVK&export=download [22[8](https://github.com/iamnabilzaman/uYouPlus/actions/runs/5310182305/jobs/9611818160#step:10:8)6] -> "main/YouTube.ipa" [1]
==> YouTube v17.3[9](https://github.com/iamnabilzaman/uYouPlus/actions/runs/5310182305/jobs/9611818160#step:10:10).4 downloaded!

**Comment by qnblackcat** [comment]
As I said above, you didn’t use a direct link to the IPA. Try to open the link in a private window to verify it first

**Comment by qnblackcat** [comment]
I literally have nothing to say anymore. Feel free to google what is Direct link (or direct download link)

Here is an example of a direct link: https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/EXCeU5EulHVPk8vsfINwsdQBPahQfTWSKYqIoTWewgNcrg?download=1

**Comment by qnblackcat** [comment]
iOS 12 is not supported 

> successfully build but now app is not opening.....

**Comment by iamnabilzaman** [comment]
is it possible to build with uYouPlus v2.1?

**Comment by vanhieu1509** [comment]
tar: Error opening archive: Unrecognized archive format
==> Error: Failed to extract uYou
![image](https://github.com/qnblackcat/uYouPlus/assets/17454858/ed7a5a6b-c2e5-4d54-84af-6be661ee162e)

**Comment by onepartsam** [comment]
> tar: Error opening archive: Unrecognized archive format
> ==> Error: Failed to extract uYou
> ![image](https://user-images.githubusercontent.com/17454858/247070854-ed7a5a6b-c2e5-4d54-84af-6be661ee162e.png)

I got this error too

**Comment by lequan81** [comment]
> tar: Error opening archive: Unrecognized archive format ==> Error: Failed to extract uYou ![image](https://user-images.githubusercontent.com/17454858/247070854-ed7a5a6b-c2e5-4d54-84af-6be661ee162e.png)

Please copy the ipa file to your own OneDrive, and set its permission to public. Change your embed link to a direct download link, and everything should work as it should.

**Comment by Chimbul** [comment]
![247070854-ed7a5a6b-c2e5-4d54-84af-6be661ee162e-copy](https://github.com/qnblackcat/uYouPlus/assets/8114661/69f2cf31-0bd7-43da-8eff-1c1a58d20fd4)

This highlighted here is wrong, you should not need to change the uYou version number. Most common valid number versions for uYou are the default 3.0 and 2.3~1 .

![image](https://github.com/qnblackcat/uYouPlus/assets/8114661/02f61acd-8716-41cf-90e2-096697211488)

The only 2 places you change , is the decrypted IPA url and the YouTube version number. The rest can stay as default.

**Comment by vanhieu1509** [comment]
> ![247070854-ed7a5a6b-c2e5-4d54-84af-6be661ee162e-copy](https://user-images.githubusercontent.com/8114661/247722759-69f2cf31-0bd7-43da-8eff-1c1a58d20fd4.png)
> 
> This highlighted here is wrong, you should not need to change the uYou version number. Most common valid number versions for uYou are the default 3.0 and 2.3~1 .
> 
> ![image](https://user-images.githubusercontent.com/8114661/247729990-02f61acd-8716-41cf-90e2-096697211488.png)
> 
> The only 2 places you change , is the decrypted IPA url and the YouTube version number. The rest can stay as default.

Thank, this OK

**Comment by QziP22** [comment]
![Screenshot 2023-06-23 at 08-18-27 Build and Release uYouPlus · QziP22_uYouPlus@25625b7](https://github.com/qnblackcat/uYouPlus/assets/65273600/c14341fd-fee5-43e8-9cc3-c90fae399c9c)


:/

**Comment by Chimbul** [comment]
Did you changed your workflow file like this?

uYouPlus/blob/main/.github/workflows/buildapp.yml

edit
`runs-on: macos-latest`
to
`runs-on: macos-11`

**Comment by QziP22** [comment]
I changed it while the process was running. (whoops)

im running a new one right now

**Comment by Chimbul** [comment]
I believe all of this started when [DontEatMyContent](https://github.com/therealFoxster/DontEatMyContent) was added. I noticed https://github.com/arichorn/uYouPlusExtra was building fine until [DontEatMyContent](https://github.com/therealFoxster/DontEatMyContent) was added yesterday. I tried to build today and it failed with the same issue.  The solution is the same as we use here. I don't know it might be coincidence.

**Comment by Dangvinh777** [comment]
![image](https://github.com/qnblackcat/uYouPlus/assets/100329768/a0aebcb9-879d-404a-9950-506746652414)
I have this problem, I have changed for macos-11 and 12 but the problem seem not to be solved

**Comment by Foxtrod89** [comment]
> Did you changed your workflow file like this?
> 
> uYouPlus/blob/main/.github/workflows/buildapp.yml
> 
> edit `runs-on: macos-latest` to `runs-on: macos-11`

same on this one and doesn't help at all.
```
> Making all for library libcolorpicker…
==> Linking library libcolorpicker (arm64)…
ld: warning: -multiply_defined is obsolete
ld: warning: search path '/Users/lovermac/Downloads/uYouPlus/.theos/obj/install/Library/Frameworks' not found
ld: warning: search path '/Users/lovermac/Downloads/uYouPlus/.theos/obj/install/var/jb/Library/Frameworks' not found
ld: framework 'Preferences' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [/Users/lovermac/Downloads/uYouPlus/.theos/obj/arm64/libcolorpicker.dylib] Error 1
make[4]: *** [/Users/lovermac/Downloads/uYouPlus/.theos/obj/arm64/libcolorpicker.dylib] Error 2
make[3]: *** [internal-library-all_] Error 2
make[2]: *** [libcolorpicker.all.library.variables] Error 2
make[1]: *** [internal-all] Error 2
make: *** [internal-all] Error 2
Failed building uYouPlus

```
