### ISSUE TITLE
[Questions] Will uYouPlus ever be fixed to work with AppSync Unified and Filza?

### ISSUE THREAD

**Issue by Mukul1127** [qnblackcat/uYouPlus#1156]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I see from the FAQ and from my experiences that uYouPlus will crash with AppSync Unified but can it be fixed as I feel the jailbreak experience with Checkra1n/Palera1n on my devices at least is more stable that with AltStore being a hassle to refresh and SideStore being really buggy. It also seems like on device solutions like ReProvision Reborn and AltDaemon are unfixed for the latest versions of iOS or rootless as well.

### Additional context

I fully support and understand if this is too much work or a hassle to support.

**Comment by BruhDudeWew** [comment]
It will launch if you use Sideloadly's Ad-Hoc Sign with AppSync Unified, but the UI is sometimes bug out and the app won't save the log in info.

**Comment by Mukul1127** [comment]
> Why don’t you just use TrollStore?

I wasn't aware of Trollstore so I ended up updating to ios 16
