### ISSUE TITLE
[Bug] Compiling issues - (clang) error

### ISSUE THREAD

**Issue by columbusux** [qnblackcat/uYouPlus#1166]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

When Make new build…

### Describe the bug

When i make new build every thing is ok except (fix compiling & build package) Section 

And i think what i see is clang version error

### Steps to reproduce the issue

1- 
![IMG_5853](https://github.com/qnblackcat/uYouPlus/assets/117425464/ec95bac7-824b-4eee-a498-12e639ea5b9a)

2- 
![IMG_5854](https://github.com/qnblackcat/uYouPlus/assets/117425464/b546b5b1-f1d2-4ee9-b328-9f7282f5e909)

3-
![IMG_5855](https://github.com/qnblackcat/uYouPlus/assets/117425464/3ee72f76-c04d-40ec-87a0-6ee44e466626)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by yodaluca23** [comment]
Change it from running on `macos-latest` to `macos-11`

**Comment by columbusux** [comment]
> Change it from running on `macos-latest` to `macos-11`

I am using the action in github (Build and Release uYouPlus) had the issue, and in which line can I change it because I searched and did not find the clang version I would like to look into and fix it if possible

**Comment by yodaluca23** [comment]
> I am using the action in github (Build and Release uYouPlus) had the issue, and in which line can I change it because I searched and did not find the clang version I would like to look into and fix it if possible

Line 47.

**Comment by columbusux** [comment]
> > I am using the action in github (Build and Release uYouPlus) had the issue, and in which line can I change it because I searched and did not find the clang version I would like to look into and fix it if possible
> 
> Line 47.

I update to new clang llvm 16.0.6 and error 2 disappear but i got new error which’s say ( sysroot) and I couldn’t find that same path…

-error Pic
![IMG_5871](https://github.com/qnblackcat/uYouPlus/assets/117425464/4218c407-b50b-4fd7-8228-ae0c7aa9ab7f)
