### ISSUE TITLE
[Bug] No watch history

### ISSUE THREAD

**Issue by Bugallow** [qnblackcat/uYouPlus#117]
### Device info
- iOS/iPadOS version: 14.2
- Device model: Ipad Air 4
- Sideload tool (Ex: AltStore, Sideloadly...): Altstore
- Version of uYouPlus: 16.38.2 & 17.15.1

### Describe the bug
Stopped updating my watch history about a week ago. None of the accounts linked work. It works fine with other apps. 
I was on 16.38.2 when this happened, updated today to 17.15.1 but still the same. 

### How to reproduce the bug
Just watch a video and go to "Library" no videos will be added to your history.

### Additional context:
Just to make sure I checked my privacy settings. Watch History is enabled (both on the app and on google). Also, this bug is present on all 4 accounts I have linked to the uYouPlus app. My history works fine on my android device and on my smart TV.

**Comment by Bugallow** [comment]
Nevermind. It was my dns causing coflict.

**Comment by ShivamAmin** [comment]
Ok, so since the solution was not posted, the urls can be found here: https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

> video-stats.l.google.com
> s.youtube.com
