### ISSUE TITLE
I can’t turn off autoplay

### ISSUE THREAD

**Issue by MartinLoner** [qnblackcat/uYouPlus#1171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version:14.3
- Device model:iPhone 12 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...):TrollStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**):18.14.1

### Describe the bug

I can’t turn off the autoplay no matter what, I tried turning off all tweaks, reinstalling, older versions, uninstalling youtube related tweaks but turning off autoplay just removes the countdown and still plays the up next video.

### Steps to reproduce the issue

1. Watch a video until the end
![6A1D48FC-8525-43B5-A598-FEA6E801A391](https://github.com/qnblackcat/uYouPlus/assets/75475473/a4c1a86c-ac97-4ad2-b323-0d5c74691af9)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
update to v19.02.1 or higher
