### ISSUE TITLE
[Bug] Shorts cells not hidden from Home menu even with respective setting turned on in uYou settings

### ISSUE THREAD

**Issue by curiousdreamer** [qnblackcat/uYouPlus#1175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: **iOS 16.5.1**
- Device model: **iPhone 14**
- Sideload tool (AltStore, Sideloadly, TrollStore,...): **Altstore**
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): **18.14.1-3.0**

### Describe the bug

Even though the setting in uYou+ settings "Hide Shorts Cells" is on, and is on for all 4 Youtube accounts, I only see shorts on my Homepage on a non-Gmail Google account for Youtube (for reference, it's an iCloud account). My other 3 accounts, one of which is another non-Gmail Google account (Hotmail) and 2-Gmail Google accounts, hide Shorts cells/shelf in the Homepage. 

I also have downloaded the stock app to check mainly for bugs alongside the tweak, but for reproducing the issue, I tried only keeping the tweak for right now but the issue persists. Also I remove extensions every time I reinstall the tweak.

I have also tried keeping stock uYou+ settings and only turning on "Hide Shorts cells" in uYou+ settings and the problem persists.

App has not crashed in this whole process so I'm not sure if I should still provide a log but I'm willing to do so in a comment or in a similar issue.

### Steps to reproduce the issue

1. Delete the stock app, then delete the tweak.
2. Redownload tweak only by sideloading on Altstore.
3. Go to settings on uYou tab (red gear icon) and click on "Hide Shorts cells" under Home.
4. Refresh app (swipe up)
5. Check other accounts and see that it only affects my non-Gmail Google account.

https://github.com/qnblackcat/uYouPlus/assets/138384248/c96f6280-ed3e-43e9-88b1-214b2d80cd9f

https://github.com/qnblackcat/uYouPlus/assets/138384248/b95823fb-8167-4397-a0d4-7154ff0750f8

https://github.com/qnblackcat/uYouPlus/assets/138384248/ffc094b5-fda0-4c99-b34d-4daeb69dcaac

https://github.com/qnblackcat/uYouPlus/assets/138384248/69ecdd21-ba2e-403d-b340-b4428d5a301b

First video is my "problem account" ("Hide Shorts cells" settings does not work on this account). I didn't have the stock app installed when I took these videos.

Second (Gmail Google), third (non-Gmail Google), and fourth (Google) video depicts accounts where the "Hide Shorts cells" option does work after doing all above steps. You can usually see them go away in real time or there will be a black bar where the Shorts shelf specifically used to be. Although some vertical videos that are not necessarily Youtube shorts (will play in normal player) still slip through.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by curiousdreamer** [comment]
Bug has been resolved, all 4 channels work as intended with specified setting on. Not sure what happened but refreshing the app after 7 days this time fixed the issue.

**Comment by curiousdreamer** [comment]
Update: bug has now popped up again. Now "migrated" to another account, this time, a Google-Gmail account, after another week refresh in Altstore.

**Comment by qnblackcat** [comment]
[please update to v19.01.1 or higher](https://github.com/qnblackcat/uYouPlus/releases/tag/v19.02.1-3.0.1)
