### ISSUE TITLE
[Bug] Replace this with your title

### ISSUE THREAD

**Issue by eobi1976** [qnblackcat/uYouPlus#1176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version:
- Device model:
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of uYouPlus (**latest or newest is NOT a version number!**):

### Describe the bug

The feature where you were able to slide your finger which made the video skip forward or backward seems to either be gone or not working. Which is weird because when you slide your finger to make to increase/decrease the volume , that feature still works.

would anyone know if that feature is coming back or if it’s still here , can you tell me where it is in settings

### Steps to reproduce the issue

1. 
![IMG_0660](https://github.com/qnblackcat/uYouPlus/assets/64454237/0d122e92-1b21-419f-a58c-0784f63f004b)

2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by robpneu** [comment]
I think the default for the bottom area changed to "Brightness" intead of s"Seek". Can you check the Player Gesture Controls uYou settings? (uYou button on the bottom bar then the gear icon in the top right, scroll down to "Player Gesture Controls")

**Comment by eobi1976** [comment]
Yes it works thanks so much

**Comment by robpneu** [comment]
Good to hear! I think you can mark this as closed.
