### ISSUE TITLE
[Enhancement] Option to Disable High-Contrast Icons

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#118]
I think it would be pretty amazing to have the ability to disable high contrast in light/dark mode, it would be amazing to have the old icon color on uYou+ for me I personally use this app and I would love to have this option.
I hope this question or enchancement is good and a option we need.

**Comment by arichorn** [comment]
and I personally think it would go along well with the new Oled Dark Mode Option!

**Comment by qnblackcat** [comment]
Sorry but I will not do it

**Comment by arichorn** [comment]
Well, YouTube Studio Mobile had it but alright. I suggested it cuz it can help eye strain for certain amount of people.
