### ISSUE TITLE
latest uYouPlus version?

### ISSUE THREAD

**Issue by parthnayak7448** [qnblackcat/uYouPlus#1189]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Do somebody gonna release new version of uYouPlus with latest YouTube version?

**Comment by auddis** [comment]
[YouTube 18.27.3](https://github.com/auddis/uYouPlus/releases/tag/v18.27.3-3.0-(12)) tested on 11 pro

**Comment by Drewtopia** [comment]
> @qnblackcat can you please make a new official release?

They no longer work on this

**Comment by bbfdesign** [comment]
Are there any alternatives ? I have used on my Android, before i switched to Apple, antoher App. On FireTV SmartYouTube is my favorite. I hope there will be a alternative to regular YT App.

**Comment by yodaluca23** [comment]
> Are there any alternatives ? I have used on my Android, before i switched to Apple, antoher App. On FireTV SmartYouTube is my favorite. I hope there will be a alternative to regular YT App. 

If u mean a tweaked YouTube Apple TV app, then yea gl, I've been wanting one too, with no luck, theirs [Yattee](https://apps.apple.com/us/app/yattee/id1595136629), that's a third party app, but nothing like uYou+....

**Comment by bbfdesign** [comment]
pooh... That doesn't sound very uplifting. Too bad - I simply lack the knowledge to do something here. What are the reasons for this? What about the fork of Audis? There seems to be a newer version here, but there is no real community here.

**Comment by niko247** [comment]
@bbfdesign
@yodaluca23
I found alternative, I used [uYouPlusExtra](https://github.com/arichorn/uYouPlusExtra)
Which is fork of this repo with updates, works pretty well, new versions and no ads
https://github.com/arichorn/uYouPlusExtra/releases

**Comment by yodaluca23** [comment]
> @bbfdesign
> 
> @yodaluca23
> 
> I found alternative, I used [uYouPlusExtra](https://github.com/arichorn/uYouPlusExtra)
> 
> Which is fork of this repo with updates, works pretty well, new versions and no ads
> 
> https://github.com/arichorn/uYouPlusExtra/releases

Yea, it's what I've been using

**Comment by bbfdesign** [comment]
Thank you - I will check it ... great

**Comment by StefanLobbenmeier** [comment]
@BasiloneDraus you might want to take a look at https://github.com/qnblackcat/uYouPlus/wiki/Installation

(I use alt store)

**Comment by parthnayak7448** [comment]
@auddis new version latest in your repo is missing. Can you get latest version?
