### ISSUE TITLE
[Experimental-Bug] Oled Dark Mode Colors aren’t colored correctly on iPads

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#119]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

- iPadOS version: 15.4.1
- Device model: iPad Pro 2017 (2nd Gen)
- Sideload tool: Altstore
- Version of uYouPlus: 17.15.1-2.1

Oled Dark Mode wasn’t fully ready for the tabs Explore, Subscriptions & uYou
They are still using most of the default YouTube Dark Mode, I can see why Oled Dark Mode was experimental.

1. Check out tabs each one and see if it’s possibly fixable 
2. Check if it’s only occurring on either iPhones or iPads

No Crash log.

I don’t have any other responses but I’m glad I help solving experimental features
![F34B0137-DF08-4BDA-9701-CDB0F4B72EE6](https://user-images.githubusercontent.com/78001398/164122537-5c686788-3473-40bc-9799-fb3b1e23c725.jpeg)
![84EFA9CD-D05F-4B01-B4CA-F7E367122D9F](https://user-images.githubusercontent.com/78001398/164122587-a2ae7007-9977-42da-8fc9-0c10ca3e23d5.jpeg)
![E5CE26D5-AE59-430B-8A6D-594729945238](https://user-images.githubusercontent.com/78001398/164122597-2799c0f0-b346-4b15-8a44-74160c03950f.jpeg)

**Comment by qnblackcat** [comment]
Can’t support iPad cz I don’t own an iPad. Sorry

**Comment by arichorn** [comment]
Oh. Didn’t know.

**Comment by qnblackcat** [comment]
If you know how use [Flex], I could give it a try

**Comment by arichorn** [comment]
What?
