### ISSUE TITLE
[Bug] Unable to download videos as the button does not show up

### ISSUE THREAD

**Issue by Logboy2000** [qnblackcat/uYouPlus#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iPadOS 16.1
- Device model: iPad Air 4th Gen
- Sideload tool: AltStore
- The specific version of uYouPlus: YouTube_18.14.1_uYou_3.0

### Describe the bug

![FC88184E-FA7F-4F93-A260-28BD47922FC3](https://github.com/qnblackcat/uYouPlus/assets/72185335/455279cb-9161-4d01-a866-487e1ead1483)
![1DF7F5A8-AB6D-472B-814B-CCE8BB0369E7](https://github.com/qnblackcat/uYouPlus/assets/72185335/72d8f7f2-957f-4ff9-a353-7db626eee861)

### Steps to reproduce the issue

1. Download YouTube_18.14.1_uYou_3.0
2. Side load using AltStore
3. Observe the missing button

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by PalmTamino** [comment]
Same here, in the player directly it’s still possible, but not outside.

**Comment by Logboy2000** [comment]
> Same here, in the player directly it’s still possible, but not outside.

Oh thank you!
I also had the button in the player disabled so i was unaware.

Also devs, please add back those buttons, at least as an option.
