### ISSUE TITLE
[Enhancement] Add the YouTube dislike return tweak

### ISSUE THREAD

**Issue by iMonZ** [qnblackcat/uYouPlus#12]
Hey is it possible to add the tweak from this repo?
https://repo.lillieweeb001.xyz/

**Comment by qnblackcat** [comment]
Not right now
1. The tweak is not stable enough 
2. [According to the dev](https://www.reddit.com/r/jailbreak/comments/r58lrr/request_youtube_dislikes_return_from_lillies_repo/hmlq7h0/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3), it may break iPad compatibility.
3. Some people still have the dislike count

**Comment by qnblackcat** [comment]
@iMonZ 
please try this version
https://www.dropbox.com/s/x9ebgj4av1esomi/uYouPlus%2016.46.5%20%26%20YouTubeDislikeReturn%201.2.0.ipa?dl=0

**Comment by RandomUsername404** [comment]
@qnblackcat 
> please try this version
<img src="https://user-images.githubusercontent.com/18629430/145017668-963b80d7-54ab-4836-aad5-605c2e2e5391.png" width=50% height=50%>

FYI the tweak works great (see pic), but now pressing most uYou options will crash the app. I don't know if it's related.
<img src="https://user-images.githubusercontent.com/18629430/145017762-ca775429-233b-4574-a41f-b9dd2df98192.png" width=50% height=50%>

_iPhone 6S iOS 15.1_

**Comment by qnblackcat** [comment]
@RandomUsername404 
yeah. I'm aware of that problem (https://github.com/qnblackcat/uYouPlus/issues/10)
Anyway, you can try this older version of uYouPlus with **YouTube Dislike Return**

**Comment by RandomUsername404** [comment]
@qnblackcat 
Everything works great in this version, thanks a lot!

**Comment by iMonZ** [comment]
Sounds great!
Hope to see this plug-in soon!

**Comment by ErSpieltHD** [comment]
Yeah I'm liking this idea. Hope we see it in action soon

**Comment by ErSpieltHD** [comment]
> ~~Not right now~~
> 
> ~~1. The tweak is not stable enough (does not work for me)~~
> 
> ~~2. [According to the dev](https://www.reddit.com/r/jailbreak/comments/r58lrr/request_youtube_dislikes_return_from_lillies_repo/hmlq7h0/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3), it may break iPad compatibility.~~
> 
> ~~3. Some people still have the dislike count~~
> 
> 
> 
> If I got the permission from the developer of **YouTube Dislike Return**, it will be added in the next update!

And anything new?

**Comment by qnblackcat** [comment]
> > ~Not right now~
> > ~1. The tweak is not stable enough (does not work for me)~
> > ~2. [According to the dev](https://www.reddit.com/r/jailbreak/comments/r58lrr/request_youtube_dislikes_return_from_lillies_repo/hmlq7h0/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3), it may break iPad compatibility.~
> > ~3. Some people still have the dislike count~
> > If I got the permission from the developer of **YouTube Dislike Return**, it will be added in the next update!
> 
> And anything new?

Please read closely before asking. Have you read the conversation above??

**Comment by ErSpieltHD** [comment]
> > > ~Not right now~
> 
> > > ~1. The tweak is not stable enough (does not work for me)~
> 
> > > ~2. [According to the dev](https://www.reddit.com/r/jailbreak/comments/r58lrr/request_youtube_dislikes_return_from_lillies_repo/hmlq7h0/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3), it may break iPad compatibility.~
> 
> > > ~3. Some people still have the dislike count~
> 
> > > If I got the permission from the developer of **YouTube Dislike Return**, it will be added in the next update!
> 
> > 
> 
> > And anything new?
> 
> 
> 
> Please read closely before asking. Have you read the conversation above??

Yeah did you get perms? Your last update was like ages ago

**Comment by koningcool** [comment]
Are you going to update this in the release versions aswell?

**Comment by qnblackcat** [comment]
> Are you going to update this in the release versions aswell?
> 
> edit: so making a new release

a new release will be released soon if nothing goes wrong

**Comment by qnblackcat** [comment]
**YouTube Dislike Return** has been added in the latest version of uYou+
https://github.com/qnblackcat/uYouPlus/releases/tag/v16.46.5-2.1

**Comment by iMonZ** [comment]
> **YouTube Dislike Return** has been added in the latest version of uYou+
> https://github.com/qnblackcat/uYouPlus/releases/tag/v16.46.5-2.1

Thank you so much.
It works!

Could you update YouTubeDislikeReturn to the latest comit if you have time? This would be great to have Shorts support!
Thanks
@qnblackcat

**Comment by MaxG-Enpal** [comment]
Hey @qnblackcat do you know where you got the source code of this tweak?
I just can't find it.
I'm asking because the Developer released an update for this tweak.

**Comment by alexandrius** [comment]
> @RandomUsername404 yeah. I'm aware of that problem (#10) Anyway, you can try this older version of uYouPlus with **YouTube Dislike Return**
> 
> [uYouPlus 16.42.3 & YouTube Dislike Return 1.2.0](https://www.dropbox.com/s/9q1edy6oynh745v/uYouPlus%2016.42.3%20%26%20YouTubeDislikeReturn%201.2.0.ipa?dl=0)

Can you resurrect this file ?

**Comment by qnblackcat** [comment]
> Hey @qnblackcat do you know where you got the source code of this tweak?
> I just can't find it.
> I'm asking because the Developer released an update for this tweak.

Somehow I missed your comment: 
https://github.com/PoomSmart/Return-YouTube-Dislikes/tree/retry-on-fail

**Comment by qnblackcat** [comment]
> > @RandomUsername404 yeah. I'm aware of that problem (#10) Anyway, you can try this older version of uYouPlus with **YouTube Dislike Return**
> > [uYouPlus 16.42.3 & YouTube Dislike Return 1.2.0](https://www.dropbox.com/s/9q1edy6oynh745v/uYouPlus%2016.42.3%20%26%20YouTubeDislikeReturn%201.2.0.ipa?dl=0)
> 
> Can you resurrect this file ?

Why? That version is out of date

**Comment by alexandrius** [comment]
> > > @RandomUsername404 yeah. I'm aware of that problem (#10) Anyway, you can try this older version of uYouPlus with **YouTube Dislike Return**
> > > [uYouPlus 16.42.3 & YouTube Dislike Return 1.2.0](https://www.dropbox.com/s/9q1edy6oynh745v/uYouPlus%2016.42.3%20%26%20YouTubeDislikeReturn%201.2.0.ipa?dl=0)
> > 
> > 
> > Can you resurrect this file ?
> 
> Why? That version is out of date

yeah but latest release crashes
