### ISSUE TITLE
[Bug] OLED HUD black text 

### ISSUE THREAD

**Issue by pelegs29** [qnblackcat/uYouPlus#120]
### Device info:
- iOS version: 15.4.1
- Device model: iPhone 12
- Sideload tool: AltStore 
- Version of uYouPlus: 17.15.1

### Describe the bug
Day passed since I’ve turned on the experimental OLED black mode HUD, and the whole text in the app became black 

![50A712B0-8271-41B5-A056-76413A299DE1](https://user-images.githubusercontent.com/80215741/164381477-cd03c855-c5ab-412d-9e1b-5ff7f5352e33.png)

**Comment by qnblackcat** [comment]
That’s why you must set YouTube’s appearance to Dark theme first. Please read the description closely next time.
if you turn on YouTube dark mode, everything should be fine

**Comment by arichorn** [comment]
Umm qnblackcat that’s not the true reason. I did that and when I tried to comment on a video, the text seemed like it was invisible and I pretty sure I didn’t have light mode on.

**Comment by qnblackcat** [comment]
I cannot reproduce your the issue so IDK what need to be fixed. Sorry
