### ISSUE TITLE
[Questions] I can't install when I sign using iOS App Signer

### ISSUE THREAD

**Issue by halpz** [qnblackcat/uYouPlus#1200]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

When I sign the ipa using a wildcard profile and my distribution certificate, Xcode says it is unable to install. but if I use the same cert and provisioning profile in ESign, the app installs fine.

does the IPA need a specific identifier to install / verify properly ? or what am I missing here? (other IPAs seem to install fine using my preferred method)

**Comment by qnblackcat** [comment]
I'm sorry but this is this beyond my knowledge
