### ISSUE TITLE
[REQUEST] Update uYouPlus with uYou v3.0.1, and latest YouTube version if possible

### ISSUE THREAD

**Issue by dora727** [qnblackcat/uYouPlus#1202]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Title. uYou released ver 3.0.1 today which fixed some bugs + new features for uYou. So new version for uYouPlus based on uYou 3.0.1 will be a good thing lol

**Comment by dora727** [comment]
btw i know dark mode is broken, so would be nice if a fix released

**Comment by Practicalbutterfly5** [comment]
Please this. YouTube is showing me regular ads now and 3.0.1 uyou fixes this.

**Comment by deardaveed** [comment]
yes, please! upvoted
