### ISSUE TITLE
[Questions] Can you download a video without opening it?

### ISSUE THREAD

**Issue by AngeloAndreaIsola** [qnblackcat/uYouPlus#1203]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I was wondering if it's possible to download a video without having to open it and then click the download button from the uYouPlus interface.

**Comment by qnblackcat** [comment]
Not possible
