### ISSUE TITLE
[Bug] “Hide Shorts Cells” does not remove the Shorts cells from the homepage.

### ISSUE THREAD

**Issue by GainingAccess** [qnblackcat/uYouPlus#1204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: IOS 16.5.1(c)
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.14.1-3.0

### Describe the bug

Hide Shorts Cells (option in uYou home settings) stopped removing the shorts cells, from the home page. 
![IMG_3193](https://github.com/qnblackcat/uYouPlus/assets/110878258/f830f34a-1d40-4d9c-b3b1-66b1cfb48329)
![IMG_3194](https://github.com/qnblackcat/uYouPlus/assets/110878258/839cd7ef-4ac3-4c54-aba3-b21ff943439b)

### Steps to reproduce the issue

1. Enable “Hide Shorts Cells” in uYou’s “Home” settings.
2. Restart the app.
3. The Shorts Cells are still in the homepage.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by gamersi** [comment]
I have the same issue

**Comment by bvoq** [comment]
Yea! This is the main reason for me to uyouplus.
Thanks everyone for making this and if this could be fixed of course it would be a god sent.

**Comment by mapssonline** [comment]
What type of account do you have? Youtube seems to break some things baseed on account

**Comment by bvoq** [comment]
https://github.com/arichorn/uYouPlusExtra is working for me.

**Comment by zediaa** [comment]
anyone find a fix? this just started happening to me

**Comment by BoxIsMyNamee** [comment]
this bug is fucking me up. I despise the shorts lmao. They pull me in so easily. I loved having them blocked. Need this fixed! 😭🙌

**Comment by mikeMisha** [comment]
This NEEDS to be fixed. This is one of the main reasons people use this.

**Comment by eureka1111** [comment]
This is the main reason I use uYouPlus as well. Please somebody come up with a fix for this. I am willing to pay some money if needed. Maybe we could get some kind of a tip jar going for this feature.

**Comment by DanylLeStyle** [comment]
Any fix yet ? Or is the uyou+ project dead ?

**Comment by ephun** [comment]
+1

**Comment by therealFoxster** [comment]
Seems to have been fixed in uYou v3.0.3
