### ISSUE TITLE
[Questions] The Downloads are sorted per year.

### ISSUE THREAD

**Issue by derMeister21** [qnblackcat/uYouPlus#1208]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Is it possible to sort the downloads correctly according to the year it was downloaded? So that the latest download is displayed at the top of the list.

**Comment by qnblackcat** [comment]
you should contact the dev of uYou https://github.com/MiRO92/uYou-for-YouTube
