### ISSUE TITLE
YTOLDUI]How to bring back the old Youtube Video player buttons without the transparency effect

### ISSUE THREAD

**Issue by Hex67** [qnblackcat/uYouPlus#1209]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

-Question forwarded from-

https://github.com/PoomSmart/YTABConfig/discussions/80

As you can see in the Pictures below, youtube used to have nice plain-styled video player buttons so I was wondering if there's any AB config to remove the button background also is there any way to bring back the rectangular Thumbnails? The new youtube UI gives me anxiety💀

OLD UI:
![3E537F8B-BF3F-48DE-B0C7-F4D5933F2FBF](https://github.com/qnblackcat/uYouPlus/assets/100369493/498c1374-cb32-43b0-b520-40d8425f7fd0)

Latest version UI: (Fake Youtube version is enabled so ignore the old UI)
![A7D7ED35-15BC-4F4B-93DC-DD30C4DAB42B](https://github.com/qnblackcat/uYouPlus/assets/100369493/e4afc8f6-e869-4f5a-b417-78343428417d)

The Youtube version I have currently installed is 18.01.6-2.3.1
IPadOS: 15.7

Signed via Esign: (with a custom certificate)
Bundle ID: com.google.ios.youtube (Unmodified)

I hope @qnblackcat will take a look at this. (even though she left)

### Additional context
Edit:
Just wanted to mention Youtube Revanced for Android has an option to remove the player button background.

**Comment by qnblackcat** [comment]
this could work

```
%hook YTMainAppControlsOverlayView
- (void)didMoveToWindow {
    %orig;
    MSHookIvar<YTTransportControlsButtonView *>(self, "_previousButtonView").backgroundColor = [UIColor clearColor];
    MSHookIvar<YTTransportControlsButtonView *>(self, "_nextButtonView").backgroundColor = [UIColor clearColor];
    MSHookIvar<YTTransportControlsButtonView *>(self, "_playPauseButton").backgroundColor = [UIColor clearColor];
}
%end
```

**Comment by Hex67** [comment]
> this could work
> 
> ```
> %hook YTMainAppControlsOverlayView
> - (void)didMoveToWindow {
>     %orig;
>     MSHookIvar<YTTransportControlsButtonView *>(self, "_previousButtonView").backgroundColor = [UIColor clearColor];
>     MSHookIvar<YTTransportControlsButtonView *>(self, "_nextButtonView").backgroundColor = [UIColor clearColor];
>     MSHookIvar<YTTransportControlsButtonView *>(self, "_playPauseButton").backgroundColor = [UIColor clearColor];
> }
> %end
> ```

I can’t build your IPA in github workflow. it always gives me an error in the "Fix compiling and build package"
![38E8ABA8-774A-4F00-BB8A-2CFE533ED161](https://github.co
[logs_3.zip](https://github.com/qnblackcat/uYouPlus/files/12514306/logs_3.zip)
m/qnblackcat/uYouPlus/assets/100369493/8e787656-79a1-4315-a9b8-c284e1e70b61)

**Comment by Hex67** [comment]
> Hi, you have to edit the workflow file (.github/workflows/buildapp.yml) so it will run on macos-11. See [#1155 (comment)](https://github.com/qnblackcat/uYouPlus/issues/1155#issuecomment-1596717793)

thanks :)
