### ISSUE TITLE
[Questions] I downloaded the new version

### ISSUE THREAD

**Issue by SandwichPlays** [qnblackcat/uYouPlus#1211]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I downloaded the new version but in my old version i have downloads so how can i transfer it to the new version?

**Comment by qnblackcat** [comment]
just overwrite the old version with the new one
