### ISSUE TITLE
Still ads 

### ISSUE THREAD

**Issue by J45onDev** [qnblackcat/uYouPlus#1214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: ios 17 beta 5
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.14.1-3.0

### Describe the bug

iSponsorBlock is enabled and i am still getting ads

### Steps to reproduce the issue

1. Open the app
2. Pick a video
3. Ads pop up

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by yodaluca23** [comment]
Search already open issues before opening a new one.

https://github.com/qnblackcat/uYouPlus/issues/1160#issuecomment-1599430121

**Comment by auddis** [comment]
Search for uYouPlusExtra or YTLitePlus on github, they’re being actively updated for now
