### ISSUE TITLE
[Bug] Workflow exits at Preprocessing Tweak.x… stage

### ISSUE THREAD

**Issue by theoware** [qnblackcat/uYouPlus#1215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: N/A
- Device model: N/A
- Sideload tool (AltStore, Sideloadly, TrollStore,...): N/A
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 3.0 (main branch)

### Describe the bug

When trying to build uYouPlus using the GitHub actions script, the workflow exits after the following error (I will attach the whole log from the "Fix compiling & Build Package" step). I've changed macos-latest to macos-11.

[11_Fix compiling & Build Package.txt](https://github.com/qnblackcat/uYouPlus/files/12302322/11_Fix.compiling.Build.Package.txt)

### Steps to reproduce the issue

1. Run the workflow with the correct inputs
2. Have the issue
...
4. Profit

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Please at least temporarily fix the macos version issue

**Comment by UnoCap** [comment]
Apply the following commit and try again: https://github.com/arichorn/uYouPlusExtra/commit/0c20ac5305265377d512a580525cadcc4d1b8304

**Comment by theoware** [comment]
That seems to have fixed it, thanks
