### ISSUE TITLE
[Enhancement?] Replace iOS default skip back/forward buttons with seek +-15s?

### ISSUE THREAD

**Issue by maxistviews** [qnblackcat/uYouPlus#1219]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Perhaps this is already in the app and I haven’t found it, but I would love to be able to seek back and forth with my mic/car media controls by seeking Instead of going to the next YouTube video. Would be extremely useful when watching long form video essays or courses. 

### Additional context

I Hope this is okay to post here. Apologies if in the wrong place.

**Comment by qnblackcat** [comment]
not possible
