### ISSUE TITLE
New uYou update v3.0.1

### ISSUE THREAD

**Issue by IceBotYT** [qnblackcat/uYouPlus#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 17.0 public beta 1
- Device model: iPhone 14 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.14.1-3.0

### Describe the bug

There's a new uYou update and I have no idea how to install it 😅
![IMG_4272](https://github.com/qnblackcat/uYouPlus/assets/34712694/380e2838-ecf0-46c0-95c6-e277aa8b03fe)

### Steps to reproduce the issue

1. Open the app

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by Mukul1127** [comment]
The app has to be built with uYou 3.1, but qnblackcat has stopped developing, you can download uYouPlusExtra instead from here https://github.com/arichorn/uYouPlusExtra

**Comment by IceBotYT** [comment]
> The app has to be built with uYou 3.0.1, but qnblackcat has stopped developing, you can download uYouPlusExtra instead from here https://github.com/arichorn/uYouPlusExtra

Thank you so much!

**Comment by sachinOraon** [comment]
Provided repo isn’t accessible anymore 🥹
https://github.com/arichorn/uYouPlusExtra

**Comment by IceBotYT** [comment]
It has since rebranded to https://github.com/arichorn/uYouEnhanced

**Comment by sachinOraon** [comment]
Thanks for the reply but this one also isn’t accessible https://github.com/arichorn/uYouEnhanced

**Comment by IceBotYT** [comment]
They changed usernames between the time I replied and you replied 🤦‍♂️

https://github.com/arichornlover/uYouEnhanced
