### ISSUE TITLE
Age restriction bypass for videos

### ISSUE THREAD

**Issue by TheDoctor200** [qnblackcat/uYouPlus#1222]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Can age restriction bypass for videos please be added in the next update of uyou plus?

There is already a simple safari Userscript (js script) for YouTube: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass

**Comment by jaff80** [comment]
I would also like to see this be added.

**Comment by jaff80** [comment]
@Carterpersall It turns off when you reopen YouTube.

**Comment by qnblackcat** [comment]
This feature is completely broken, which is why it is disabled automatically
