### ISSUE TITLE
[Bug] Unable to exit fullscreen

### ISSUE THREAD

**Issue by jaff80** [qnblackcat/uYouPlus#1224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.6 (20G75)
- Device model: iPhone 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.14.1-3.0

### Describe the bug

I was watching a video and went into fullscreen, but when I tried to exit, I couldn't. Not even rotating my device would exit fullscreen. I had to close the app and reopen it. I have not seen the bug again yet.

https://github.com/qnblackcat/uYouPlus/assets/113552154/78656688-6d57-469f-9651-60be7484d918

### Steps to reproduce the issue

1.  Open YouTube
2.  Tap on a video
3.  Go fullscreen

### Crash log (if the app crashes)

```shell
The app does not crash.
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
probably YT's bug

**Comment by P-Li0n** [comment]
I am having this issue as well, and can consistently reproduce the bug on iPad (iPadOS 17.5.1) / uYouEnhanced (19.08.2-3.0.3) @qnblackcat 
I cannot swipe down to exit the player, or hit the button to do so. When I rotate the screen, the experience breaks completely

**Comment by jaff80** [comment]
@P-Li0n Try using [8mb.video](https://8mb.video/) or YouTube.
