### ISSUE TITLE
[Questions] How to bring back uYou tab after hiding it?

### ISSUE THREAD

**Issue by 3DStyle** [qnblackcat/uYouPlus#1226]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I hid the uYou tab from the app screen and now I can't access the uYou settings, at least not in a way I can think of.
How can I access the uYou settings if the tab is hidden, or how do I bring it back? Reinstalling the tweak didn't help.

Thanks.

**Comment by qnblackcat** [comment]
YouTube's setting > General > uYou
