### ISSUE TITLE
Quality resolutions missing

### ISSUE THREAD

**Issue by imadofficial** [qnblackcat/uYouPlus#123]
When you watch a video (e.g. Linus Tech Tips) you can only see resolutions up to 1080p and HDR is not available either.![image](https://user-images.githubusercontent.com/59332263/164885237-cf2df06a-4efe-43d6-b4d6-990828d97ded.png)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
