### ISSUE TITLE
[Suggestion] Add YTCastConfirm

### ISSUE THREAD

**Issue by hero3210** [qnblackcat/uYouPlus#124]
Please add YTCastConfirm
https://github.com/JamieBerghmans/YTCastConfirm

Thanks

**Comment by qnblackcat** [comment]
Does the tweak work on the latest version of YouTube?

**Comment by hero3210** [comment]
> Does the tweak work on the latest version of YouTube?

Yes

**Comment by qnblackcat** [comment]
added in v17.16.4-2.1

**Comment by hero3210** [comment]
Thank you
