### ISSUE TITLE
[Questions] The future of new releases

### ISSUE THREAD

**Issue by SoCuul** [qnblackcat/uYouPlus#1244]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I noticed that many updates are being committed to the master branch, but there hasn't been a full release in months. Is there a chance that you could make the master branch create build archives so we can install the latest development version without having to build it ourselves?

**Comment by level3tjg** [comment]
This is challenging because building a tweaked ipa requires an unmodified ipa of the latest version of YouTube. That requires a jailbroken iOS device to decrypt, which can't easily be automated. We could compile deb files for jailbroken users but I feel a majority of users aren't jailbroken. Keeping this open because I think it's a good idea, just don't know how I'd implement it right now.

**Comment by yodaluca23** [comment]
> This is challenging because building a tweaked ipa requires an unmodified ipa of the latest version of YouTube. That requires a jailbroken iOS device to decrypt, which can't easily be automated. We could compile deb files for jailbroken users but I feel a majority of users aren't jailbroken. Keeping this open because I think it's a good idea, just don't know how I'd implement it right now.

You might be able to make something to fetch the latest YouTube ipa from https://armconverter.com/decryptedappstore automatically...

**Comment by SoCuul** [comment]
Also, for some reason when I try to build it I either get an build failure (which is fixed by changing the macos version used for the build), but that results in the build failing as well.

**Comment by level3tjg** [comment]
> You might be able to make something to fetch the latest YouTube ipa from https://armconverter.com/decryptedappstore automatically...

I'll check this out, looks promising

> Also, for some reason when I try to build it I either get an build failure (which is fixed by changing the macos version used for the build), but that results in the build failing as well.

Sync the change I just made, should work then

**Comment by SoCuul** [comment]
Oh perfect, thanks!

**Comment by SoCuul** [comment]
Just tried to open it, and it crashes on startup.

**Comment by SoCuul** [comment]
@level3tjg you got any suggestions on how to fix this? Could my logs help?

**Comment by level3tjg** [comment]
> @level3tjg you got any suggestions on how to fix this? Could my logs help?

If you could make a new bug issue and attach crash logs I can take a look

**Comment by SoCuul** [comment]
> > @level3tjg you got any suggestions on how to fix this? Could my logs help?
> 
> If you could make a new bug issue and attach crash logs I can take a look

Sorry, but where exactly would I find these crash logs haha.

**Comment by yodaluca23** [comment]
> > If you could make a new bug issue and attach crash logs I can take a look
> 
> Sorry, but where exactly would I find these crash logs haha.

https://github.com/qnblackcat/uYouPlus/blob/main/.github/ISSUE_TEMPLATE/bug.yaml#:~:text=If%20somehow%20the%20app%20crashes%2C%20you%20must%20provide%20the%20crash%20log.%20It%20can%20be%20found%20in%20your%20device%27s%20Settings%20App%20%3E%20Privacy%20%3E%20Analytics%20%26%20Improvements%20%3E%20Analytics%20Data%20%3E%20Youtube%2Dxxx%2Dxxx.ips

Also, please make a new issue, it's best to keep separate issues separate...
