### ISSUE TITLE
[Bug] installing error

### ISSUE THREAD

**Issue by cozy06** [qnblackcat/uYouPlus#1247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 17.0.2
- Device model: ipad air 4
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Xcode
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): uYouPlus_18.14.1_3.0.ipa

### Describe the bug

installing error

### Steps to reproduce the issue

1. installing .ipa
2. open xcode
3. run simulator
4. install app
5. ERROR!!

### Crash log (if the app crashes)

```shell
Error installing  '/Users/cozy06/Downloads/uYouPlus_18.14.1_3.0.ipa', ERROR: Error Domain=com.apple.dt.CoreDeviceError Code=3002 "Failed to install the app on the device." UserInfo={NSURL=file:///Users/cozy06/Downloads/uYouPlus_18.14.1_3.0.ipa, NSLocalizedDescription=Failed to install the app on the device., NSUnderlyingError=0x6000074fe2e0 {Error Domain=com.apple.dt.CoreDeviceError Code=3000 "The item at uYouPlus_18.14.1_3.0.ipa is not a valid bundle." UserInfo={NSURL=file:///Users/cozy06/Downloads/uYouPlus_18.14.1_3.0.ipa, NSLocalizedFailureReason=Failed to read the bundle., NSLocalizedDescription=The item at uYouPlus_18.14.1_3.0.ipa is not a valid bundle.}}}
Domain: com.apple.dt.DVTCoreDevice
Code: -1
User Info: {
    DVTErrorCreationDateKey = "2023-10-09 09:34:32 +0000";
}
--


System Information

macOS Version 14.0 (Build 23A344)
Xcode 15.0 (22265) (Build 15A240d)
Timestamp: 2023-10-09T18:34:32+09:00
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by Cheese-Echidna** [comment]
Can confirm similar issue running iOS 17.0.3 on iPhone XR with Alt Store 1.7 and uYouPlus version 18.14.1_3.0. 
When I try to install through Alt Store the progress bar hangs and never completes. If I then close the Alt Store app at any point it becomes unavailable and I need to reinstall from PC.

**Comment by dmegatool** [comment]
Yeah same. It never completes and Alt Store becomes unvailable.

**Comment by sebastianjena** [comment]
Same on latest iOS+iPhone 14 Pro, it hangs on AltStore

**Comment by sunjianan9900** [comment]
any update?

**Comment by qnblackcat** [comment]
I doubt this is an issue of uYou+, try update/reinstall AltStore
