### ISSUE TITLE
Cant install ipa with igg deb with Sideloadly

### ISSUE THREAD

**Issue by parkslvm1** [qnblackcat/uYouPlus#1279]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

I wanted to sideload a Game with the igamegod.deb file but i couldnt install it with sideloady. „There was an Issue during installation 0: APIInternalError (Error Domain)
![IMG_0025](https://github.com/qnblackcat/uYouPlus/assets/156958049/ee4f07ab-f120-454a-9219-222790afb941)

### Additional context

Dies anyone know how to fix that please? I have been trying for a Long time but didnt get it to work.

**Comment by qnblackcat** [comment]
Obviously a Sideloadly's issue
