### ISSUE TITLE
[Bug] OLED mode doesn’t work on 17.16.4

### ISSUE THREAD

**Issue by QziP22** [qnblackcat/uYouPlus#128]
### Device info
- iOS/iPadOS version: 15.1.1
- Device model:12 Pro
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore
- Version of uYouPlus: 17.16.4

### Describe the bug
It worked perfectly fine on 17.15.2, however on 17.16.4 it does not. The app is in dark mode along with the iPhone theme. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by qnblackcat** [comment]
Try this
1. Turn on Oled darkmode
2. Switch to Light mode
3. Switch to Dark mode
4. Restart the app

**Comment by VoltIcaRus** [comment]
> Try this
> 
> 1. Turn on Oled darkmode
> 2. Switch to Light mode
> 3. Switch to Dark mode
> 4. Restart the app

it work.
