### ISSUE TITLE
Previous version of Youtube asking for update 

### ISSUE THREAD

**Issue by vivekch0976** [qnblackcat/uYouPlus#1281]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Hello, currently I am using uYouPlus_18.14.1_3.0 of Youtube. Since 24 Jan whenever I open it, it asking for update. I checked on Appstore current version is 19.03.2. When we will get the updated version of App? I appriciate your efforts to make a add free society.
Thank you!

**Comment by ThatBlackAstronaut** [comment]
I'm not a dev, but in sideloadly you can edit the version of the app. I changed the version I was on to replicate the latest. it broke some functionality and you cant click on videos (v17.something) so you can attempt but be careful.
