### ISSUE TITLE
Home - Hide Short Cells Not working

### ISSUE THREAD

**Issue by FredTrivett** [qnblackcat/uYouPlus#1284]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Why are the shorts not being hidden?

### Additional context

I have just downloaded uYouPlus and when I go to settings - home - hide shorts cells, it does not work. The shorts are still appearing on my feed. I don't know if I did something wrong or if it is a bug.

**Comment by martinoturrina** [comment]
I think this is due to the new type of cell introduced lately which are bigger, and they are not yet supported by the tweaks. I think we need to wait a bit more to get this back

**Comment by qnblackcat** [comment]
Fixed in uYou 3.0.2 [according to MiRO92](https://miro92.com/repo/depictions/changelog.html?p=com.miro.uyou). New release coming soon
