### ISSUE TITLE
[Questions] Implement uYouLocalization

### ISSUE THREAD

**Issue by Deci8BelioS** [qnblackcat/uYouPlus#1285]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Is it possible to implement uYouLocalization to uYouPlus

https://github.com/dayanch96/uYouLocalization

**Comment by qnblackcat** [comment]
IMO, It's not that important. Don't want to deal with more unnecessary stuff. We better wait until MiRO92 officially add localization
