### ISSUE TITLE
[Questions] Is it possible to unlock the queue or add some implementation of it?

### ISSUE THREAD

**Issue by l4kr** [qnblackcat/uYouPlus#1287]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Youtube has put the queue system under premium. Would there be a way to have a queue? Whether bypassing Youtubes premium or having some workaround?

**Comment by qnblackcat** [comment]
not possible, sorry
