### ISSUE TITLE
[Bug] App crashes when selecting uYouLocal download

### ISSUE THREAD

**Issue by qnblackcat** [qnblackcat/uYouPlus#129]
### Device info
- iOS/iPadOS version: all
- Device model: all
- Sideload tool: all
- Version of uYouPlus: v17.16.4-2.1

### Describe the bug
App crashes when selecting uYouLocal download in the video controls overlay

### Crash log (if possible)
[Crashlog.txt](https://github.com/qnblackcat/uYouPlus/files/8569520/text-17F294A59978-1.txt)

**Comment by TimestaticYT** [comment]
I have the same bug on iOS 15.5 and uYouPlus version 17.22.3. I’m on an iPhone 12. I used AltStore repository for the sideloading.

the bug is the same as described here.

i do not know where to get the crash report and it isn’t described in faq

**Comment by qnblackcat** [comment]
should be fixed in the next release

**Comment by TimestaticYT** [comment]
Woooo, really excited about this fix since uYouLocal is a lot faster than uYou downloads normally! Thanks 🙏
