### ISSUE TITLE
[v19.02.1-3.0.1] “hide channel watermark” doesn’t work

### ISSUE THREAD

**Issue by reticivis-net** [qnblackcat/uYouPlus#1292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4
- Device model: iPhone 14 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Scarlet

### Describe the issue

The hide channel watermark setting doesn’t work
![IMG_4234](https://github.com/qnblackcat/uYouPlus/assets/35177464/4ea2a00c-8cea-4db9-bee9-0d5b3386c908)

### Steps to reproduce

1. Enable “hide channel watermark”
2. Restart app
3. Go to a video with channel watermark

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by qnblackcat** [comment]
could you provide the video link?

**Comment by reticivis-net** [comment]
https://youtu.be/KK3mS4bQ5JM

also I noticed the watermark doesn’t appear until you full screen, tap to bring up controls, then tap to dismiss them

**Comment by therealFoxster** [comment]
Should be fixed in #1296
