### ISSUE TITLE
[v19.02.1-3.0.] New video player settings appear, causing YTClassicVideoQuality not to work.

### ISSUE THREAD

**Issue by jaff80** [qnblackcat/uYouPlus#1298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: iOS 17.3 (21D50)
- Device model: iPhone 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): AltStore

### Describe the issue

When watching a video, if you click on the gear icon, you will see a settings menu, and when tapping on "Quality," you get options for "Auto," "Higher picture quality," "Data saver," and "Advanced." This causes YTClassicVideoQuality not to work.

### Steps to reproduce

1. Open YouTube
2. Tap on a video
3. Tap on the gear icon
4. Tap on "Quality"

![IMG_6989](https://github.com/qnblackcat/uYouPlus/assets/113552154/180df963-530e-454a-b2d9-8c6ef9799d82)

![IMG_6990](https://github.com/qnblackcat/uYouPlus/assets/113552154/2b1bdfb3-2802-4d84-a9a7-22001a041ac4)

https://github.com/qnblackcat/uYouPlus/assets/113552154/82e06a4f-d6fd-4409-ab08-230a713f493a

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by qnblackcat** [comment]
YTClassicVideoQuality no longer works independently on newer YT versions. You have to enable _Show quality button_ in _Video overlay_ setting
