### ISSUE TITLE
[Questions] I install the latest .ipa version and it seems like it contains only the unmodified youtube

### ISSUE THREAD

**Issue by x4080** [qnblackcat/uYouPlus#1299]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I dont know if I made a mistake or not, but when I installed the uyou (non plus) version, it works as expected but with bug that when we scroll down, the top contents all dissapeared

The Uyou+ version seems dont have the popup that told me that I'm running uyou - it just... like regular youtube app.
Is there something I should click first ? On jb ipad BTW

Thanks

**Comment by qnblackcat** [comment]
If you use uYouPlus, always get the latest ipa from here: https://github.com/qnblackcat/uYouPlus/releases

**Comment by x4080** [comment]
@qnblackcat I think I use the ipa from there
