### ISSUE TITLE
[Bug] Subtitles won't activate

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#13]
**Device info**
- iOS/iPadOS version: 15.2
- Device model: 12
- Sideload tool (Ex: AltStore, Sideloadly...): Sideloadly

**Describe the bug**
- Subtitles won't activate

**How to Reproduce the bug**
_(Please attach videos or screenshots if possible)_
Go to any video and try to enable subtitles.

https://user-images.githubusercontent.com/40891294/144919017-54de59bd-1ee2-410e-9b42-877db6d6191e.MOV

Video: [Video](https://youtu.be/UAKPoAn2cB0)

**Additional context**

**Comment by qnblackcat** [comment]
Are you still facing this issue?

**Comment by ErSpieltHD** [comment]
Nope, seems to be working again. Thanks and sorry for the duplicated issues.

**Comment by qnblackcat** [comment]
No problem
