### ISSUE TITLE
[v3.0.1] Impossible to log into a Google Account

### ISSUE THREAD

**Issue by DBeitniz** [qnblackcat/uYouPlus#1302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.3.1
- Device model: iPhone 13
- Sideload tool: AltStore

### Describe the issue

It is impossible to log in my YouTube account, after I try to do it and enter my email on the google website that popes up it says “You can’t sign in to this app because Google can’t confirm that it’s safe.”, please fix this.

### Steps to reproduce

1. Go to the home page
2. Click on the account icon
3. Click on “Sign in”
4. Enter email in the pop-up website
5. Get the error message (Without even entering password)
![IMG_0280](https://github.com/qnblackcat/uYouPlus/assets/107348169/b5729fef-fa44-4dcf-942a-121aa85ba929)

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by 420-420** [comment]
This works for my unjailed phone on iOS 17 alt store does not. You have to use [Sideloadly](https://sideloadly.io/)

drag the IPA on to [Sideloadly](https://sideloadly.io/)
Click advanced options 
BEFORE INSTALLING, make sure these two options are enabled: "Inject dylibs/frameworks" and also "Sideload Spoofer". Make sure you only have those two checked in the Tweak Injection section.
Press the start button
Login to your itunes account 
Go should work this way

**Comment by segg21** [comment]
Duplicate: https://github.com/qnblackcat/uYouPlus/issues/1212

**Comment by qnblackcat** [comment]
Make sure you sure you get the ipa from here: https://github.com/qnblackcat/uYouPlus/releases
