### ISSUE TITLE
Update the wiki for Trollstore 2

### ISSUE THREAD

**Issue by CycloKid** [qnblackcat/uYouPlus#1310]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Trollstore 2 released a while ago, and newer iOS versions are supported now. Could the wiki be updated to reflect the newer TrollStore?

### Additional context

An updated table can be found here:
https://ios.cfw.guide/installing-trollstore/

**Comment by qnblackcat** [comment]
Done
