### ISSUE TITLE
How to disable this?

### ISSUE THREAD

**Issue by hi-im-karma** [qnblackcat/uYouPlus#1311]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

How do I disable this thing? „UK hits…“
![IMG_1642](https://github.com/qnblackcat/uYouPlus/assets/73917917/12424d5d-340f-4726-bb00-675a7b2696dd)

**Comment by qnblackcat** [comment]
Disable *Show in-video info cards* in the General setting of YouTube
