### ISSUE TITLE
1080p Premium not available? (I’m YT Premium member)

### ISSUE THREAD

**Issue by KarmaBeast** [qnblackcat/uYouPlus#1312]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Im paying for YT premium. On my Android with Revanced Extented(and iOS stock YT) I can still play 1080p Premium. As you can see in this screenshot:
![IMG_1643](https://github.com/qnblackcat/uYouPlus/assets/73917917/6a09c43c-c451-467c-9e8e-0b5d9f5cb9b7)

But the same video on uyou+ is not available in 1080p Premium:
![IMG_1644](https://github.com/qnblackcat/uYouPlus/assets/73917917/bc570367-eee6-4513-94b3-68c73d1a2b4d)

Video link: https://youtu.be/gadinpHHjWU?si=CzjbPd679M_B16Zh

**Comment by MG-LSJ** [comment]
Aa far as I remember, ios doesn't have a separate high bit rate option.

Cause I read somewhere that the only "free/hack" way to enable this feature on other platform is to set your youtube client as ios.

I may be worng on this.

**Comment by hi-im-karma** [comment]
> Aa far as I remember, ios doesn't have a separate high bit rate option.
> 
> Cause I read somewhere that the only "free/hack" way to enable this feature on other platform is to set your youtube client as ios.
> 
> I may be worng on this.

What that hell are you even on about? I had this feature with the stock YT on my iPhone. It became first available on iOS only before any other device.

**Comment by qnblackcat** [comment]
I'm a YouTube Premium user, too. I can see 1080p Premium on my main phone, but not the others. Strange...

![IMG_C0B3697B7A04-1](https://github.com/qnblackcat/uYouPlus/assets/52943116/7d683dca-d250-492d-8290-76463d89f29f)

**Comment by hi-im-karma** [comment]
The fact that I shows you the 1080p Premium option but not me is strange enough. I just don't get it, and it's a big deal to me. 1080p is important to me 😔

**Comment by PoomSmart** [comment]
There are A/B flags related to premium quality, try looking for and playing around something with "hbr" + "premium" + "playbackCap".

**Comment by hi-im-karma** [comment]
> There are A/B flags related to premium quality, try looking for and playing around something with "hbr" + "premium" + "playbackCap".

I will try those out. But why would I need to mess around with AB flags when this feature is available by default in the stock app and modded apps on Android (Revanced Extented)

In the AppStore app I have it available, but the second I try any uyou apps it's unavailable.

**Comment by hi-im-karma** [comment]
Still not available...

**Comment by PoomSmart** [comment]
`YTHotConfig.premiumClientSharedConfigEnablePremiumHbrPlaybackCap ` should be enabled.

**Comment by hi-im-karma** [comment]
> `YTHotConfig.premiumClientSharedConfigEnablePremiumHbrPlaybackCap ` should be enabled.

First of all I have that already enabled, but double checked anyway. Secondly why would we need to depend on AB flags so that we could use features that way pay for? (YouTube Premium member) 

On all stock YT apps be it on the AppStore or Googles Playstore, and modded YT apps such as Revanced Extented this feature is available to me by default. Cuz I pay for YouTube Premium. It's still only missing in all uyouplus, uyouenhanced apps 😔

**Comment by PoomSmart** [comment]
"Why would we depend on AB flags?"

Simply put, it's YouTube you are talking about. They can turn on or off any flags depending on what YouTube client you actually use. Not something we can control. ¯\_(ツ)_/¯

**Comment by PoomSmart** [comment]
Fixed with a new version of YTClassicVideoQuality which has been out for some time.

**Comment by PoomSmart** [comment]
Not sure if it'd auto-select but you can try the latest commit of uYouPlus. It's been long since this specific issue in YTClassicVideoQuality was fixed.
