### ISSUE TITLE
[Bug] In OLED Mode, comments text input box on Shorts is black text on black background.

### ISSUE THREAD

**Issue by tevyisertyin** [qnblackcat/uYouPlus#133]
### Device info
- iOS/iPadOS version: 15.4.1
- Device model: iPhone XS Max
- Sideload tool (Ex: AltStore, Sideloadly...): AltStore
- Version of uYouPlus: 17.16.4-2.1

### Describe the bug
When writing a comment on a Short with OLED Mode turned on, the text input box is black text on a black background, so it is impossible to see what you are typing.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Use uYouPlus while logged in to a Google account
Watch a YouTube Short
Tap the Comment button on the right
Try to type anything in the text input field that appears. Black text on black background.
![1B323A03-90A7-4B3B-B687-87399BE03357](https://user-images.githubusercontent.com/104609012/165880155-aa152631-f176-4aca-8658-7df3de154f73.jpeg)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
Not Applicable

### Additional context:
None

**Comment by VoltIcaRus** [comment]
# 128
have you tried this

**Comment by tevyisertyin** [comment]
> #128
> have you tried this

Okay, I’ve just tried it, and the problem is only temporarily fixed, and requires this specific sequence of actions:
1. Make sure “Settings > General > Appearance > Use device theme” is set
2. Turn on OLED Mode and quit uYouPlus
3. Turn on Light Mode on iPhone using Control Center
4. Run uYouPlus
5. Turn on Dark Mode on iPhone using Control Center. uYouPlus will then turn on OLED Mode.

If I do this, then the comments text input box on YouTube Shorts will be black text on white background
![7120B508-96A1-461F-BFBB-A8932FB89EEE](https://user-images.githubusercontent.com/104609012/165984591-74721ff6-0b88-41b3-a193-efc326ec1d6e.jpeg)

However, once you restart the app, this fix stops working, and you have to do the whole sequence again.

**Comment by qnblackcat** [comment]
this section doesn't work correctly on vanilla YouTube: white box & black text even in dark theme (left picture) 
Guess I will not fix it

**Comment by qnblackcat** [comment]
![2CC72364-40E1-4DCF-963C-DBB2D5F955E1](https://user-images.githubusercontent.com/52943116/166008168-e5f7a9fe-5668-4d4d-8346-2cac26b1024c.jpeg)

this section doesn't work correctly on vanilla YouTube: white box & black text even in dark theme (left picture) 
Guess I will not fix it

**Comment by tevyisertyin** [comment]
I thought the idea of this app was to enhance the way the YouTube app works, but it’s your choice 🙂

**Comment by qnblackcat** [comment]
Aright, it should be fixed in the next release

**Comment by tevyisertyin** [comment]
Awesome, thank you!

**Comment by qnblackcat** [comment]
Lmk if the issue persists in v17.18.4-2.1
