### ISSUE TITLE
NOT SAFE??? What the Foxtrot-Uniform-Charlie-Kilo????

### ISSUE THREAD

**Issue by W9JYD** [qnblackcat/uYouPlus#1339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version:  17.3.1
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Sideloadly (using custom bundleID `com.qrz.w9jyd.ios.youtube`)

### Describe the issue

![IMG_0051](https://github.com/qnblackcat/uYouPlus/assets/58867813/3d3830bf-f07d-4cce-86a2-661f2db314c9)
@qnblackcat  are you gonna do anything about this??? I have tried everything. EVERYTHING.

I AM USING THE LATEST VERSION. DON'T TELL ME OTHERWISE. 

@google you need to stop breaking shit.

### Steps to reproduce

1. Install. 
2. Login with your Google account.
3. Get this bullshit from @google saying it's unsafe.
4. Book a flight to Mountain View, CA and strangle Sundar Pichai.

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by yodaluca23** [comment]
It's because you're using a different BundleID.

**Comment by W9JYD** [comment]
> It's because you're using a different BundleID.

Got damn it you’re right. I did that and it didn’t work and even though it’s Sofa King Wee Todd Ed that Google does this mess but I gave it another try. I deleted the app with the custom BundleID and just re-sideloaded it without any custom BundleID or app name. 

However, when signing in, after the process is completed, the app closes on you. But IDGAF and I’m not raising an issue against that because after relaunching I have absolutely zero problem.

**Comment by testi61** [comment]
please tell me how to remove BundleID((

**Comment by yodaluca23** [comment]
> please tell me how to remove BundleID((

Just don't change it, if your using the GitHub actions workflow, don't change anything in the bundle ID option, leave it default. And make sure whatever sideloading tool you're using isn't changing it automatically.

**Comment by testi61** [comment]
I download last YT version from developer cloud, than upload to Dropbox and use GitHub workflow.
After that, I download and upload to AltStore clicking “with extensions”
