### ISSUE TITLE
[Bug] repo doesn't install in altstore, screen shot attached

### ISSUE THREAD

**Issue by mailinglists35** [qnblackcat/uYouPlus#134]
### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: 

### Describe the bug
repo doesn't install in altstore

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:

**Comment by mailinglists35** [comment]
![image](https://user-images.githubusercontent.com/2054302/166063515-e54a6c41-b3e4-42a5-9a7b-68db2fc61984.png)

![image](https://user-images.githubusercontent.com/2054302/166063482-3fc96505-5f23-4d6e-8a27-55c1e031c03f.png)

**Comment by mailinglists35** [comment]
iphone 13 mini ios 15.1.1

**Comment by mailinglists35** [comment]
also crashes with uyouplus

**Comment by qnblackcat** [comment]
Managing AltStore repo only available with AltStore beta (from AltStore patron)
