### ISSUE TITLE
[Questions] Autoplay next video does not work in latest version of the app

### ISSUE THREAD

**Issue by iqbal1992** [qnblackcat/uYouPlus#1340]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### Device info
iOS/iPadOS version: 17.4
Device model: iPhone 12 pro max
Sideload tool: Sideloadly
Version of uYouPlus: 19.08.2-3.0.3

### My question
In the latest version, Next youtube video does not autoplay. Player just stops at replay button at the end. Am I missing to enable/disable any tweak or is it a bug ?

**Comment by IDontKnowWhatNameToPutHere** [comment]
me too

**Comment by RavenFR** [comment]
Same here, thought i had an option turned on until i updated to the latest version, past couple of updates have just not autoplayed

**Comment by anniechau** [comment]
I had to downgraded back to the 18.1.4 version for it to work properly again

**Comment by bhackel** [comment]
I think it's a label bug uYou. Try **enabling** the feature in uYou Settings -> Video Player -> No Suggested Videos at The Video End. This should actually do the opposite and enable the suggested video popup.

**Comment by iqbal1992** [comment]
> I think it's a label bug uYou. Try **enabling** the feature in uYou Settings -> Video Player -> No Suggested Videos at The Video End. This should actually do the opposite and enable the suggested video popup.

Confirmed. It is working. Just that 8 second countdown is annoying before the next video plays.

**Comment by Ludo1598** [comment]
> I think it's a label bug uYou. Try **enabling** the feature in uYou Settings -> Video Player -> No Suggested Videos at The Video End. This should actually do the opposite and enable the suggested video popup.

Thanks for your help it works again

**Comment by huyle0406** [comment]
> I think it's a label bug uYou. Try **enabling** the feature in uYou Settings -> Video Player -> No Suggested Videos at The Video End. This should actually do the opposite and enable the suggested video popup.

Thank you, confirmed it works

**Comment by plia7** [comment]
> I think it's a label bug uYou. Try **enabling** the feature in uYou Settings -> Video Player -> No Suggested Videos at The Video End. This should actually do the opposite and enable the suggested video popup.

Thanks, it worked for me on iOS 14.4.1 and uYou 3.0.3.
Do you have any workaround for this bug too by chance:

https://github.com/MiRO92/uYou-for-YouTube/issues/420

**Comment by pronox0** [comment]
> > I think it's a label bug uYou. Try **enabling** the feature in uYou Settings -> Video Player -> No Suggested Videos at The Video End. This should actually do the opposite and enable the suggested video popup.
> 
> Thanks, it worked for me on iOS 14.4.1 and uYou 3.0.3. Do you have any workaround for this bug too by chance:
> 
> [MiRO92#420](https://github.com/MiRO92/uYou-for-YouTube/issues/420)

As said above, don’t tag miro for any bugs, he is not workin on that kind of stuff.
