### ISSUE TITLE
[Questions] Error building action workflow

### ISSUE THREAD

**Issue by HamsterHawk** [qnblackcat/uYouPlus#1341]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Hi, im trying to build the app to get the IPA because i apparently need to do that now but im getting this error and i dont have any clue how to resolve it 

![rD1cFJr](https://github.com/qnblackcat/uYouPlus/assets/39222940/eef6bcc3-4456-4066-90e7-137a9529b989)

please help thanks

**Comment by N0cky** [comment]
Can confirm, same error for me

**Comment by k3v1nwrld** [comment]
+1, this issue has been around for a week or so but no one has been talking about it apparently

**Comment by apexmod2** [comment]
Getting same error too

**Comment by Wulgaren** [comment]
same here

**Comment by Amathou** [comment]
+1

**Comment by kerness** [comment]
+1

**Comment by soscaster** [comment]
same here

**Comment by dcm2610** [comment]
+1

**Comment by WongPuikyun** [comment]
+1

**Comment by MrBanhBao** [comment]
+1

**Comment by MrDirectory** [comment]
+1

**Comment by vkhiep** [comment]
iSponsorBlock missing @
bundle = [NSBundle bundleWithPath:ROOT_PATH_NS("/Library/Application Support/iSponsorBlock.bundle")];
bundle = [NSBundle bundleWithPath:ROOT_PATH_NS(@"/Library/Application Support/iSponsorBlock.bundle")];

**Comment by iqbal1992** [comment]
> iSponsorBlock missing @ bundle = [NSBundle bundleWithPath:ROOT_PATH_NS("/Library/Application Support/iSponsorBlock.bundle")]; bundle = [NSBundle bundleWithPath:ROOT_PATH_NS(@"/Library/Application Support/iSponsorBlock.bundle")];

If so, how to change it then ?

**Comment by Dangvinh777** [comment]
same problem 
![image](https://github.com/qnblackcat/uYouPlus/assets/100329768/ef0460db-900d-4d88-a9d2-478ebac29709)

**Comment by shadow-mafi** [comment]
+1

**Comment by vkhiep** [comment]
> same problem ![image](https://private-user-images.githubusercontent.com/100329768/311343854-ef0460db-900d-4d88-a9d2-478ebac29709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5Mjg3MjQsIm5iZiI6MTcwOTkyODQyNCwicGF0aCI6Ii8xMDAzMjk3NjgvMzExMzQzODU0LWVmMDQ2MGRiLTkwMGQtNGQ4OC1hOWQyLTQ3OGViYWMyOTcwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQyMDA3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmUwYzlkM2RjOWNiZmNiMzY0ZWU5MzAzNjkzYzcxZTc3OWYxZTQ5OTI0Y2Q2M2ZlODU1NTVkMWZmN2ZjYmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ws6s4YbMU3SARRMynslIG5IG-CBGUQ1y4EhsB6MRvcQ)

downgraded Theos "buildapp.yml"
- name: Setup Theos
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          ref: master   <---- change
          path: theos
          submodules: recursive

new:
       - name: Setup Theos
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          ref: 4bcc52914e0eeca719288522938185decaa8a1cb
          path: theos
          submodules: recursive

**Comment by vkhiep** [comment]
> If so, how to change it then ?

downgraded Theos "buildapp.yml"

name: Setup Theos
uses: actions/checkout@v4.1.1
with:
repository: theos/theos
ref: master <---- change
path: theos
submodules: recursive
new:
- name: Setup Theos
uses: actions/checkout@v4.1.1
with:
repository: theos/theos
ref: 4bcc52914e0eeca719288522938185decaa8a1cb
path: theos
submodules: recursive

**Comment by shadow-mafi** [comment]
did it work ?

**Comment by shadow-mafi** [comment]
> > If so, how to change it then ?
> 
> downgraded Theos "buildapp.yml"
> 
> name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> 
> * name: Setup Theos
>   uses: actions/checkout@v4.1.1
>   with:
>   repository: theos/theos
>   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
>   path: theos
>   submodules: recursive

so how does it solve the problem ?

**Comment by Dangvinh777** [comment]
> > > If so, how to change it then ?
> > 
> > 
> > downgraded Theos "buildapp.yml"
> > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > 
> > * name: Setup Theos
> >   uses: actions/checkout@v4.1.1
> >   with:
> >   repository: theos/theos
> >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> >   path: theos
> >   submodules: recursive
> 
> so how does it solve the problem ?

It worked for me, but I don't know how it operation lol

**Comment by vkhiep** [comment]
> > > If so, how to change it then ?
> > 
> > 
> > downgraded Theos "buildapp.yml"
> > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > 
> > * name: Setup Theos
> >   uses: actions/checkout@v4.1.1
> >   with:
> >   repository: theos/theos
> >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> >   path: theos
> >   submodules: recursive
> 
> so how does it solve the problem ?

change file .github/workflows/buildapp.yml
Working 100%

**Comment by shadow-mafi** [comment]
> > > > If so, how to change it then ?
> > > 
> > > 
> > > downgraded Theos "buildapp.yml"
> > > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > > 
> > > * name: Setup Theos
> > >   uses: actions/checkout@v4.1.1
> > >   with:
> > >   repository: theos/theos
> > >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> > >   path: theos
> > >   submodules: recursive
> > 
> > 
> > so how does it solve the problem ?
> 
> change file .github/workflows/buildapp.yml Working 100%

another error on setuping theos

**Comment by Dangvinh777** [comment]
> > > > > If so, how to change it then ?
> > > > 
> > > > 
> > > > downgraded Theos "buildapp.yml"
> > > > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > > > 
> > > > * name: Setup Theos
> > > >   uses: actions/checkout@v4.1.1
> > > >   with:
> > > >   repository: theos/theos
> > > >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> > > >   path: theos
> > > >   submodules: recursive
> > > 
> > > 
> > > so how does it solve the problem ?
> > 
> > 
> > change file .github/workflows/buildapp.yml Working 100%
> 
> another error on setuping theos

Can u take a screenshot for debugging easier ?

**Comment by vkhiep** [comment]
> > > > > If so, how to change it then ?
> > > > 
> > > > 
> > > > downgraded Theos "buildapp.yml"
> > > > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > > > 
> > > > * name: Setup Theos
> > > >   uses: actions/checkout@v4.1.1
> > > >   with:
> > > >   repository: theos/theos
> > > >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> > > >   path: theos
> > > >   submodules: recursive
> > > 
> > > 
> > > so how does it solve the problem ?
> > 
> > 
> > change file .github/workflows/buildapp.yml Working 100%
> 
> another error on setuping theos

Theo not theojail

**Comment by shadow-mafi** [comment]
> > > > > > If so, how to change it then ?
> > > > > 
> > > > > 
> > > > > downgraded Theos "buildapp.yml"
> > > > > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > > > > 
> > > > > * name: Setup Theos
> > > > >   uses: actions/checkout@v4.1.1
> > > > >   with:
> > > > >   repository: theos/theos
> > > > >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> > > > >   path: theos
> > > > >   submodules: recursive
> > > > 
> > > > 
> > > > so how does it solve the problem ?
> > > 
> > > 
> > > change file .github/workflows/buildapp.yml Working 100%
> > 
> > 
> > another error on setuping theos
> 
> Theo not theojail

sorry i changed it now

**Comment by shadow-mafi** [comment]
> > > > > > If so, how to change it then ?
> > > > > 
> > > > > 
> > > > > downgraded Theos "buildapp.yml"
> > > > > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > > > > 
> > > > > * name: Setup Theos
> > > > >   uses: actions/checkout@v4.1.1
> > > > >   with:
> > > > >   repository: theos/theos
> > > > >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> > > > >   path: theos
> > > > >   submodules: recursive
> > > > 
> > > > 
> > > > so how does it solve the problem ?
> > > 
> > > 
> > > change file .github/workflows/buildapp.yml Working 100%
> > 
> > 
> > another error on setuping theos
> 
> Theo not theojail

thanks worked like a charm !

**Comment by HamsterHawk** [comment]
> > If so, how to change it then ?
> 
> downgraded Theos "buildapp.yml"
> 
> name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> 
> * name: Setup Theos
>   uses: actions/checkout@v4.1.1
>   with:
>   repository: theos/theos
>   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
>   path: theos
>   submodules: recursive

this solution is confusing im sorry. also it says theo-jailed for me in the original screenshot and not theos

**Comment by vkhiep** [comment]
> > > If so, how to change it then ?
> > 
> > 
> > downgraded Theos "buildapp.yml"
> > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > 
> > * name: Setup Theos
> >   uses: actions/checkout@v4.1.1
> >   with:
> >   repository: theos/theos
> >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> >   path: theos
> >   submodules: recursive
> 
> this solution is confusing im sorry. also it says theo-jailed for me in the original screenshot and not theos


Theos not Theos-jailed

![E8C67B30-70FA-43BC-A591-AFDCA5000B04](https://github.com/qnblackcat/uYouPlus/assets/129315542/be19184c-9b00-40ec-a6d6-9eb88778946f)

**Comment by anniechau** [comment]
> > > > If so, how to change it then ?
> > > 
> > > 
> > > downgraded Theos "buildapp.yml"
> > > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > > 
> > > * name: Setup Theos
> > >   uses: actions/checkout@v4.1.1
> > >   with:
> > >   repository: theos/theos
> > >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> > >   path: theos
> > >   submodules: recursive
> > 
> > 
> > this solution is confusing im sorry. also it says theo-jailed for me in the original screenshot and not theos
> 
> Theos not Theos-jailed
> 
> ![E8C67B30-70FA-43BC-A591-AFDCA5000B04](https://private-user-images.githubusercontent.com/129315542/311364328-be19184c-9b00-40ec-a6d6-9eb88778946f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MzE2MzQsIm5iZiI6MTcwOTkzMTMzNCwicGF0aCI6Ii8xMjkzMTU1NDIvMzExMzY0MzI4LWJlMTkxODRjLTliMDAtNDBlYy1hNmQ2LTllYjg4Nzc4OTQ2Zi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMjA1NTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM0YWI4NzI2NzRjMjQ0ODNkNGMwMDQ3N2Q0ZjczZmEwNDUzYWY3NWE3NTkwMjg4NDZlN2QzYjJmNTBiNTg0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N5-wZkYCR7DVOZEVTMxCY6Z9mJndlBr7RdAY7XVqH9Q)
Cảm ơn anh ạ

**Comment by vkhiep** [comment]
> > > If so, how to change it then ?
> > 
> > 
> > downgraded Theos "buildapp.yml"
> > name: Setup Theos uses: actions/checkout@v4.1.1 with: repository: theos/theos ref: master <---- change path: theos submodules: recursive new:
> > 
> > * name: Setup Theos
> >   uses: actions/checkout@v4.1.1
> >   with:
> >   repository: theos/theos
> >   ref: 4bcc52914e0eeca719288522938185decaa8a1cb
> >   path: theos
> >   submodules: recursive
> 
> this solution is confusing im sorry. also it says theo-jailed for me in the original screenshot and not theos

![1D9183C4-53AC-46CA-AF9F-FBDBBABAA65B](https://github.com/qnblackcat/uYouPlus/assets/129315542/e694504c-74bf-42b7-ba88-032bd09be010)

**Comment by HamsterHawk** [comment]
ah i see. i fixed my silly mistake and it worked. thank you!

**Comment by k3v1nwrld** [comment]
Please do not mark this as fixed, just because a workaround was found it does not mean it is fixed

**Comment by mitul72** [comment]
> Please do not mark this as fixed, just because a workaround was found it does not mean it is fixed

I agree on that one

**Comment by qnblackcat** [comment]
Guys, I'm on vacation right now. I will look at this later. Sorry for the inconvenience.

**Comment by k3v1nwrld** [comment]
> Guys, I'm on vacation right now. I will look at this later. Sorry for the inconvenience.

This really hasnt anything to do with uYouPlus, the problem is with iSponsorBlock @iCrazeiOS

**Comment by iCrazeiOS** [comment]
Seems like theos' recent libroot changes have caused iSB compilation to fail?

Odd. I will take a look later today

**Comment by iCrazeiOS** [comment]
Just pushed a fix to iSponsorBlock - everything should be fine now 😄

**Comment by k3v1nwrld** [comment]
I think the errors are still the same...
![image](https://github.com/qnblackcat/uYouPlus/assets/75213647/842b2cab-58dd-40dc-9d3e-600d3d8c9b33)

**Comment by k3v1nwrld** [comment]
Hey @qnblackcat the issue is fixed now, we just need you to update submodules since they are disabled for forks

**Comment by vkhiep** [comment]
> Hey @qnblackcat the issue is fixed now, we just need you to update submodules since they are disabled for forks

update-submodules.disabled change update-submodules.yml 
Store GitHub token into secrets with permissions to write to parent repository

**Comment by Dangvinh777** [comment]
![image](https://github.com/qnblackcat/uYouPlus/assets/100329768/0526c79c-aa55-450a-a085-52c25df766d4)
I have this problem, I have checked all option of token

**Comment by vkhiep** [comment]
> ![image](https://private-user-images.githubusercontent.com/100329768/311487831-0526c79c-aa55-450a-a085-52c25df766d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTA2MDMsIm5iZiI6MTcxMDA1MDMwMywicGF0aCI6Ii8xMDAzMjk3NjgvMzExNDg3ODMxLTA1MjZjNzljLWFhNTUtNDUwYS1hMDg1LTUyYzI1ZGY3NjZkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwNTU4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjE0NDI4YTM5YWMyNzlkZjRkOTQ2ZTRmMDZmMDhmOTk1NjBiMjFjMWY5OGI2NGU1OGEzZDVhZGI0MWNiZTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZtDJxA8Mw5zlTDWcBP6jK8K6c43imfbwuHhOwRwUQc4) I have this problem, I have checked all option of token

update submodules đi b, nếu ko biết update submodules thì tạm sửa file build.yml, đoạn 68 ref: master thay bằng ref: 4bcc52914e0eeca719288522938185decaa8a1cb

**Comment by vkhiep** [comment]
> ![image](https://private-user-images.githubusercontent.com/100329768/311487831-0526c79c-aa55-450a-a085-52c25df766d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTExOTQsIm5iZiI6MTcxMDA1MDg5NCwicGF0aCI6Ii8xMDAzMjk3NjgvMzExNDg3ODMxLTA1MjZjNzljLWFhNTUtNDUwYS1hMDg1LTUyYzI1ZGY3NjZkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwNjA4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzI5ZmIxNGE1ZGUzMGY3YjFhY2Q4OTgzNzk2ODljNDk5YmY2N2YwMDg2OWRiZGVmNDlkNDUzOWQ5ODBlYzE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o_imPzvJVHYO1YuwvToDd8uBDJs6QoRAYkBXFkZFygA) I have this problem, I have checked all option of token

bạn không có quyền up trực tiếp vào đây chỉ up bên bạn thôi, đổi mấy cái qnblackcat thành tên bạn

**Comment by Dangvinh777** [comment]
> > ![image](https://private-user-images.githubusercontent.com/100329768/311487831-0526c79c-aa55-450a-a085-52c25df766d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTExOTQsIm5iZiI6MTcxMDA1MDg5NCwicGF0aCI6Ii8xMDAzMjk3NjgvMzExNDg3ODMxLTA1MjZjNzljLWFhNTUtNDUwYS1hMDg1LTUyYzI1ZGY3NjZkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwNjA4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzI5ZmIxNGE1ZGUzMGY3YjFhY2Q4OTgzNzk2ODljNDk5YmY2N2YwMDg2OWRiZGVmNDlkNDUzOWQ5ODBlYzE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o_imPzvJVHYO1YuwvToDd8uBDJs6QoRAYkBXFkZFygA) I have this problem, I have checked all option of token
> 
> bạn không có quyền up trực tiếp vào đây chỉ up bên bạn thôi, đổi mấy cái qnblackcat thành tên bạn

à mình hiều rồi,mình cảm ơn nhiều

**Comment by Dangvinh777** [comment]
![image](https://github.com/qnblackcat/uYouPlus/assets/100329768/c83ad232-0043-472e-bac6-c07d5da686e7)
Cập nhật xong submodules vẫn tiếp tục gặp vấn đề này
