### ISSUE TITLE
Can not build uYouPlus with method 1

### ISSUE THREAD

**Issue by Nakio204** [qnblackcat/uYouPlus#1345]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

How can I fix this error

"iSponsorBlock.xm:19:47: error: member reference base type 'const char[50]' is not a structure or union
==> Compiling iSponsorBlock.xm (arm64)…
            bundle = [NSBundle bundleWithPath:ROOT_PATH_NS("/Library/Application Support/iSponsorBlock.bundle")];
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/rootless.h:10:30: note: expanded from macro 'ROOT_PATH_NS'
#define ROOT_PATH_NS(nsPath) JBROOT_PATH_NSSTRING(nsPath)
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/libroot/libroot.h:20:36: note: expanded from macro 'JBROOT_PATH_NSSTRING'
#define JBROOT_PATH_NSSTRING(path) __CONVERT_PATH_NSSTRING(libroot_dyn_jbrootpath, path)
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/libroot/libroot.h:17:47: note: expanded from macro '__CONVERT_PATH_NSSTRING'
        [NSString stringWithUTF8String:converter(path.fileSystemRepresentation, tmpBuf)]; \
                                                 ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/rules.mk:390: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.61968dba.o] Error 1
rm /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.mm
make[3]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:52: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.dylib] Error 2
make[2]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make[1]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/rules.mk:146: iSponsorBlock.all.tweak.variables] Error 2
make: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2
Error: Process completed with exit code 2."

### Additional context

_No response_

**Comment by kyutori** [comment]
Me too

**Comment by hiepvk** [comment]
> ### Have you read the FAQ?
> * [x]  Yes, I did read the FAQ
> 
> ### Is there an existing issue/question for this?
> * [x]  I have searched the existing issues
> 
> ### Do you think this is a bug?
> ❌ No, I don't think this is a bug. I will explain below
> 
> ### My question
> How can I fix this error
> 
> "iSponsorBlock.xm:19:47: error: member reference base type 'const char[50]' is not a structure or union ==> Compiling iSponsorBlock.xm (arm64)… bundle = [NSBundle bundleWithPath:ROOT_PATH_NS("/Library/Application Support/iSponsorBlock.bundle")]; ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ /Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/rootless.h:10:30: note: expanded from macro 'ROOT_PATH_NS' #define ROOT_PATH_NS(nsPath) JBROOT_PATH_NSSTRING(nsPath) ^~~~~~~~~~~~~~~~~~~~~~~~~~~~ /Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/libroot/libroot.h:20:36: note: expanded from macro 'JBROOT_PATH_NSSTRING' #define JBROOT_PATH_NSSTRING(path) __CONVERT_PATH_NSSTRING(libroot_dyn_jbrootpath, path) ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ /Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/libroot/libroot.h:17:47: note: expanded from macro '__CONVERT_PATH_NSSTRING' [NSString stringWithUTF8String:converter(path.fileSystemRepresentation, tmpBuf)]; ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~ 1 error generated. make[4]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/rules.mk:390: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.61968dba.o] Error 1 rm /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.mm make[3]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:52: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.dylib] Error 2 make[2]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2 make[1]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/rules.mk:146: iSponsorBlock.all.tweak.variables] Error 2 make: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2 Error: Process completed with exit code 2."
> 
> ### Additional context
> _No response_

change build.yml line 68 :
- name: Setup Theos
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          ref: 4bcc52914e0eeca719288522938185decaa8a1cb
          path: theos
          submodules: recursive

**Comment by hiepvk** [comment]
change line 68 build.yml 
ref: master
replaced
ref: 4bcc52914e0eeca719288522938185decaa8a1cb

**Comment by hiepvk** [comment]
> Me too

change line 68 build.yml
ref: master
replaced
ref: 4bcc52914e0eeca719288522938185decaa8a1cb

**Comment by Nakio204** [comment]
let me try

**Comment by kyutori** [comment]
It workes. Thank you!

**Comment by Nakio204** [comment]
OMG, it works for me too. Thanks so much bro, from Vietnam with love <3

**Comment by hiepvk** [comment]
> OMG, it works for me too. Thanks so much bro, from Vietnam with love <3

Biết VN từ đâu cmt tiếng việt cho đỡ mệt :))
