### ISSUE TITLE
.

### ISSUE THREAD

**Issue by AlexPajitnofv** [qnblackcat/uYouPlus#1347]

**Comment by hiepvk** [comment]
> ### Have you read the FAQ?
> * [x]  Yes, I did read the FAQ
> 
> ### Is there an existing issue/question for this?
> * [x]  I have searched the existing issues
> 
> ### Do you think this is a bug?
> ✅ Yes, I believe this is a bug. I will open a new issue with the bug template
> 
> ### My question
> Just found out that uYouPlus started updating again and their latest release fixes the rearrangement issue for the tabs, but went to their github and saw the ipa download got taken down by Google.
> 
> I followed their instructions on how to build via Github Actions, but got stuck at the step where I put in the "direct download link" to the decrypted ipa there. When I use the OneDrive link to the ipa, it gives "Error 403: Forbidden" and exit code 8, then just fails. I download the ipa, upload it on my own Google Drive, now it says something about the End-of-central-directory signature not found and exit code 9 (I tried uploading it in the form of a zip and renaming both the ipa and the zip to just "YouTube", same issue). Has anyone else tried building the ipa and ran into this same problem?
> 
> ### Additional context
> _No response_

Direct URL to the decrypted YouTube ipa
dropbox: https://dl.dropboxusercontent.com/scl/fi/xxxxx/xxxxx.ipa?rlkey=xxxxx&dl=0
onedrive: https://onedrive.live.com/download?cid=xxxxxx&resid=xxxxxx&authkey=xxxxxx&em=2
https://drive.google.com/folderview?id=xxxxx&usp=sharing <--- Not a direct download link

**Comment by hiepvk** [comment]
> Thank you for your kindness. But all your links are 404 error.

The above is an example for you, but here is my direct link
https://dl.dropboxusercontent.com/scl/fi/z76utpmg8mess834xrqxt/ytb-19.09.4.ipa?rlkey=oakyj3nthodvpf7rfpj3bjffd&dl=0

**Comment by AlexPajitnofv** [comment]
Thanks! I solve problem about exit code 9. But this time problem happens about exit code 2. Do you know how can I solve this problem?

**Comment by hiepvk** [comment]
> Thanks! I solve problem about exit code 9. But this time problem happens about exit code 2. Do you know how can I solve this problem?

change line 68 file build.yml
ref: master
replace with
ref: 4bcc52914e0eeca719288522938185decaa8a1cb

**Comment by AlexPajitnofv** [comment]
I already saw your answer in another question. But I don't know how can I replace "ref: master" with "ref: 4bcc52914e0eeca719288522938185decaa8a1cb"

**Comment by AlexPajitnofv** [comment]
It works! Thanks, dude!
