### ISSUE TITLE
Cannot build uYouPlus with method 1

### ISSUE THREAD

**Issue by strangetheproot** [qnblackcat/uYouPlus#1349]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I'm trying to build uYouPlus using method 1 and I keep getting this error on the "Fixing compiling & Build Package" stage:

Run cd /Users/runner/work/uYouPlus/uYouPlus/main
  cd /Users/runner/work/uYouPlus/uYouPlus/main
  sed -i '' "[2](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:2)7s#.*#BUNDLE_ID = com.google.ios.youtube#g" Makefile
  sed -i '' "26s#.*#DISPLAY_NAME = YouTube#g" Makefile          
  make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1
  echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
  echo -e "==> \0[3](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:3)3[1mSHASUM2[5](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:5)[6](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:6): $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
  echo -e "==> \033[1mBundle ID: com.google.ios.youtube\033[0m"
  shell: /bin/bash -e {0}
  env:
    THEOS: /Users/runner/work/uYouPlus/uYouPlus/theos
    UYOU_VERSION: v19.0[8](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:8).2-3.0.3
    BUNDLE_ID: com.google.ios.youtube
    APP_NAME: YouTube
  
==> Downloading uYou…
tar: Error opening archive: Unrecognized archive format
==> Error: Failed to extract uYou
tar: Error opening archive: Failed to open 'Tweaks/uYou/data.tar*'
make: *** [Makefile:63: before-all] Error 1
Error: Process completed with exit code 2.

**Comment by sfksuperman** [comment]
Where to find **"A decrypted YouTube ipa"**? Does it mean that nobody will provide modded ipa ever like arichornlover?

**Comment by TheNightRider12** [comment]
You can find the decrypted YouTube IPA on places like AppDB
https://appdb.to/?name=YouTube&compatibility=ios

**Comment by sfksuperman** [comment]
> You can find the decrypted YouTube IPA on places like AppDB https://appdb.to/?name=YouTube&compatibility=ios

It's asking me to link my device first to download or install.

**Comment by TheNightRider12** [comment]
> > You can find the decrypted YouTube IPA on places like AppDB https://appdb.to/?name=YouTube&compatibility=ios
> 
> It's asking me to link my device first to download or install.

Correct. You have to link your device to AppDB before you can download the IPA. Idk why they do that, but they do. Once you link your device then you can download the IPA and then upload it wherever and then build from Actions from there.

**Comment by vkhiep** [comment]
> ### Have you read the FAQ?
> * [x]  Yes, I did read the FAQ
> 
> ### Is there an existing issue/question for this?
> * [x]  I have searched the existing issues
> 
> ### Do you think this is a bug?
> ❌ No, I don't think this is a bug. I will explain below
> 
> ### My question
> I'm trying to build uYouPlus using method 1 and I keep getting this error on the "Fixing compiling & Build Package" stage:
> 
> Run cd /Users/runner/work/uYouPlus/uYouPlus/main cd /Users/runner/work/uYouPlus/uYouPlus/main sed -i '' "[2](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:2)7s#._#BUNDLE_ID = com.google.ios.youtube#g" Makefile sed -i '' "26s#._#DISPLAY_NAME = YouTube#g" Makefile make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1 echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT echo -e "==> \0[3](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:3)3[1mSHASUM2[5](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:5)[6](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:6): $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m" echo -e "==> \033[1mBundle ID: com.google.ios.youtube\033[0m" shell: /bin/bash -e {0} env: THEOS: /Users/runner/work/uYouPlus/uYouPlus/theos UYOU_VERSION: v19.0[8](https://github.com/strangetheproot/uYouPlus/actions/runs/8216348665/job/22470830385#step:11:8).2-3.0.3 BUNDLE_ID: com.google.ios.youtube APP_NAME: YouTube
> 
> ==> Downloading uYou… tar: Error opening archive: Unrecognized archive format ==> Error: Failed to extract uYou tar: Error opening archive: Failed to open 'Tweaks/uYou/data.tar*' make: *** [Makefile:63: before-all] Error 1 Error: Process completed with exit code 2.
> 
> ### Additional context
> _No response_

The version of uYou 3.0.3, đừng thay đổi

**Comment by EyalRotem** [comment]
I too have an issue - but mine is related to the "Prepare YouTube IPA" stage -
![Screenshot 2024-03-10 111319](https://github.com/qnblackcat/uYouPlus/assets/12516268/09d1788c-13c5-4c1b-bdf6-21068c40c228)

tried different sites, links and what not...
the decrypted IPA is from [here](https://github.com/qnblackcat/Decrypted-IPAs)

**Comment by viguiry** [comment]
You can find the Decripted ipa there (Decripted IPAs by one of the dev): https://github.com/qnblackcat/Decrypted-IPAs?tab=readme-ov-file
Personnaly, Method 1 didn't work when I tried with google drive and onedrive. Because I know the problem can come from the File host, I browsed for a different free host. https://www.file.io/ and worked.
![Untitled1](https://github.com/qnblackcat/uYouPlus/assets/48199094/13669c76-919f-4458-b631-332d908ef629)
![Untitled](https://github.com/qnblackcat/uYouPlus/assets/48199094/14e4ef06-b328-4919-8df6-6b53f155a204)

**Comment by EyalRotem** [comment]
Using file.io worked for me too! Thanks for the suggestion!

**Comment by sfksuperman** [comment]
[This link](https://github.com/qnblackcat/Decrypted-IPAs?tab=readme-ov-file) has not latest YouTube till date. And, I'm worried even if using ipa from there, what should we fill in below details?

1. iOS SDK version to be used during build
2. The version of uYou
3. Modify the bundle ID. Not recommended
4. Modify the name of the app on the Home Screen. Not recommended


![image](https://github.com/qnblackcat/uYouPlus/assets/34414624/cc586a5f-38d5-42fc-a66e-8241a7d9323c)

**Comment by sfksuperman** [comment]
And how much hours will it take to complete?
![image](https://github.com/qnblackcat/uYouPlus/assets/34414624/2f2a49db-50ac-4961-8383-bd2e34be2cd1)

**Comment by AhmedElsayed0** [comment]
<img width="1113" alt="Screenshot 2024-03-10 at 14 29 34" src="https://github.com/qnblackcat/uYouPlus/assets/46785742/92057156-094b-4b33-bd15-cdfc397acdc8">

[https://github.com/qnblackcat/Decrypted-IPAs?tab=readme-ov-file](url) i got the latest one from here but when i tried to build it i got this error here? any help

**Comment by sfksuperman** [comment]
> <img alt="Screenshot 2024-03-10 at 14 29 34" width="1113" src="https://private-user-images.githubusercontent.com/46785742/311513417-92057156-094b-4b33-bd15-cdfc397acdc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzg4MTIsIm5iZiI6MTcxMDA3ODUxMiwicGF0aCI6Ii80Njc4NTc0Mi8zMTE1MTM0MTctOTIwNTcxNTYtMDk0Yi00YjMzLWJkMTUtY2RmYzM5N2FjZGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDEzNDgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZmE1NDhmN2MxMDRhODViMjBmNzE0YzYyM2I2ODUzY2NlMjNjMjUwMDJhMmFjODdlZjM3NDc5NTU3NjQ2ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xZLwyF_3WbWIlF99_3FKq1B15ZiR2qaDr3ePveE9cx8">
> [https://github.com/qnblackcat/Decrypted-IPAs?tab=readme-ov-file](url) i got the latest one from here but when i tried to build it i got this error here? any help

Can you answer this? 👉 https://github.com/qnblackcat/uYouPlus/issues/1349#issuecomment-1987212566

**Comment by SleepyPrince** [comment]
I am having issue when compiling iSponserBlock
> Making all in Tweaks/iSponsorBlock…
> Making all for tweak iSponsorBlock…
==> Preprocessing iSponsorBlock.xm…
==> Compiling SponsorBlockSettingsController.m (arm64)…
==> Compiling MBProgressHUD.m (arm64)…
==> Compiling SponsorSegment.m (arm64)…
==> Compiling SponsorSegmentView.m (arm64)…
==> Compiling SponsorBlockRequest.m (arm64)…
==> Compiling SponsorBlockViewController.m (arm64)…
iSponsorBlock.xm:19:47: error: member reference base type 'const char[50]' is not a structure or union
==> Compiling iSponsorBlock.xm (arm64)…
            bundle = [NSBundle bundleWithPath:ROOT_PATH_NS("/Library/Application Support/iSponsorBlock.bundle")];
rm /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.mm
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/rootless.h:10:30: note: expanded from macro 'ROOT_PATH_NS'
#define ROOT_PATH_NS(nsPath) JBROOT_PATH_NSSTRING(nsPath)
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/libroot/libroot.h:20:36: note: expanded from macro 'JBROOT_PATH_NSSTRING'
#define JBROOT_PATH_NSSTRING(path) __CONVERT_PATH_NSSTRING(libroot_dyn_jbrootpath, path)
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/uYouPlus/uYouPlus/theos/vendor/include/libroot/libroot.h:17:47: note: expanded from macro '__CONVERT_PATH_NSSTRING'
        [NSString stringWithUTF8String:converter(path.fileSystemRepresentation, tmpBuf)]; \
                                                 ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/rules.mk:390: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.61968dba.o] Error 1
make[3]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:52: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.dylib] Error 2
make[2]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
make[1]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/rules.mk:146: iSponsorBlock.all.tweak.variables] Error 2
make: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2
Error: Process completed with exit code 2.

Not sure what I missed.

**Comment by k3v1nwrld** [comment]
You can close this issue now as it is fixed. As for youtube decrypted ipas, search for them online (decrypt.day/armconverter.com are trusted sources from the community) and upload them to some file.io

**Comment by yodaluca23** [comment]
> You can close this issue now as it is fixed. As for youtube decrypted ipas, search for them online (decrypt.day/armconverter.com are trusted sources from the community) and upload them to some file.io

Idk about decrypt.day, but with ArmConverter, you can just use the download link straight from ArmConverter for the workflow...

**Comment by enokseth** [comment]
> [This link](https://github.com/qnblackcat/Decrypted-IPAs?tab=readme-ov-file) has not latest YouTube till date. And, I'm worried even if using ipa from there, what should we fill in below details?
> 
> 1. iOS SDK version to be used during build
> 2. The version of uYou
> 3. Modify the bundle ID. Not recommended
> 4. Modify the name of the app on the Home Screen. Not recommended
> 
> ![image](https://private-user-images.githubusercontent.com/34414624/311509698-cc586a5f-38d5-42fc-a66e-8241a7d9323c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDU2NzEsIm5iZiI6MTcxMDcwNTM3MSwicGF0aCI6Ii8zNDQxNDYyNC8zMTE1MDk2OTgtY2M1ODZhNWYtMzhkNS00MmZjLWE2NmUtODI0MWE3ZDkzMjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE5NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMjk1NjdiNDVmY2Q4YzlkMmE3ZjFhNWE2ZDQ4ZGY5MzM0YjlhOWU0ZWI2NWE3MThhYzZkMDZhYzk1MjNmODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EjqmQNrmiBFgfEYtRpyG1sLZSLDeVMLNbJz3Urf3ECg)

this is because where you input the link of IPA, you have not .ipa at the end of string is necessary in language like CSS HTML To launch an action like "download" ;) and all is the same things in this balisage languages.

**Comment by TheKivster** [comment]
Got the same error despite using two different file hosts. Anyone find a solution?

**Comment by SleepyPrince** [comment]
I use Dropbox, change the copied link ends from "dl=0" to "dl=1" works for me

**Comment by qnblackcat** [comment]
a temporary solution has been added at https://github.com/qnblackcat/uYouPlus/commit/4c819c69dad93047f6d36aac9b6fba3558d822a8

**Comment by iiasceri** [comment]
Same issue tried everything with the latest 19.19.7

**Comment by RustyBanana27** [comment]
having this problem right now what’s the solution

**Comment by W9JYD** [comment]
> Personnaly, Method 1 didn't work when I tried with google drive and onedrive. Because I know the problem can come from the File host, I browsed for a different free host. https://www.file.io/ and worked. 

Yeah... that ish happened to me... I tried iCloud and OneDrive... same. Your suggestion worked. Got an ad-free YT now!

(I usually pay for Premium, but I wanted a Mac this month so I had to pause the sub..)

Thanks again and 73s, W9JYD

**Comment by falsealarmsnoozing** [comment]
Run mkdir -p theos/lib/iphone/rootless
==> Downloading uYou…
tar: Error opening archive: Unrecognized archive format
==> Error: Failed to extract uYou
tar: Error opening archive: Failed to open 'Tweaks/uYou/data.tar*'
make: *** [Makefile:63: before-all] Error 1
Error: Process completed with exit code 2.

**Comment by paris1111q1q1q1** [comment]
mee too!

**Comment by enokseth** [comment]
> mee too!
> 
> 

Due to your version of YouTub ipa or your link, doing like this : 'https://www.mediafire.com/file/youtubeipà'

**Comment by paris1111q1q1q1** [comment]
No the IPA downloads but then it
Run mkdir -p theos/lib/iphone/rootless
==> Downloading uYou…
tar: Error opening archive: Unrecognized archive format
==> Error: Failed to extract uYou
tar: Error opening archive: Failed to open 'Tweaks/uYou/data.tar*'
make: *** [Makefile:63: before-all] Error 1
Error: Process completed with exit code 2.

**Comment by rex118da** [comment]
> No the IPA downloads but then it Run mkdir -p theos/lib/iphone/rootless ==> Downloading uYou… tar: Error opening archive: Unrecognized archive format ==> Error: Failed to extract uYou tar: Error opening archive: Failed to open 'Tweaks/uYou/data.tar*' make: *** [Makefile:63: before-all] Error 1 Error: Process completed with exit code 2.

same here

**Comment by nguyendoai7777** [comment]
> No the IPA downloads but then it Run mkdir -p theos/lib/iphone/rootless ==> Downloading uYou… tar: Error opening archive: Unrecognized archive format ==> Error: Failed to extract uYou tar: Error opening archive: Failed to open 'Tweaks/uYou/data.tar*' make: *** [Makefile:63: before-all] Error 1 Error: Process completed with exit code 2.

same here

**Comment by falsealarmsnoozing** [comment]
since its not maintained anymore i switch to other versions and i use this [one](https://github.com/NotDarkn/uYouBuild/releases/tag/v19.39.1-3.0.4)

**Comment by nguyendoai7777** [comment]
great thank's bro

________________________________
Từ: falsealarmsnoozing ***@***.***>
Đã gửi: 01 Tháng Mười Hai 2024 13:06
Đến: qnblackcat/uYouPlus ***@***.***>
Cc: doainn ***@***.***>; Comment ***@***.***>
Chủ đề: Re: [qnblackcat/uYouPlus] Cannot build uYouPlus with method 1 (Issue #1349)


since its not maintained anymore i switch to other versions and i use this one<https://github.com/NotDarkn/uYouBuild/releases/tag/v19.39.1-3.0.4>

**Comment by falsealarmsnoozing** [comment]
Go to Enhanced settings, its under youtube main settings. As Shorts video and titles will not match, ENABLE VERSION SPOOFING and choose any version. This will fix the problem. Been using for more than a week now.
