### ISSUE TITLE
[Bug] opening "YT SETTINGS" menu items crashes the app

### ISSUE THREAD

**Issue by mailinglists35** [qnblackcat/uYouPlus#135]
### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: 

iphone 13 mini 15.1.1 latest github release sideloadely (altstore crashes when attempting to use it for uyou and ytmusicultimate)
### Describe the bug
crash log https://www.pastefile.com/77v9mq

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:

**Comment by qnblackcat** [comment]
YouTube music is not supported by uYou. Invalid issue!
