### ISSUE TITLE
Can't build with the first method (Process completed with exit code 1)

### ISSUE THREAD

**Issue by VVVektormanIO** [qnblackcat/uYouPlus#1357]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I can't build, at the Prepare YouTube IPA stage it gives an Error: Process completed with exit code 1.

![msedge_umuFfrHMzg](https://github.com/qnblackcat/uYouPlus/assets/117126880/be9bc2c9-524d-48e3-9044-51dfc032cbdc)

**Comment by yuukiAme** [comment]
Two questions.

1. Are you sure the IPA download URL that you linked in the Build work? Is it a direct download to .ipa file?
2. Is the .ipa file the unedited decrypted ipa from App Store?

**Comment by VVVektormanIO** [comment]
> Two questions.
> 
> 1. Are you sure the IPA download URL that you linked in the Build work? Is it a direct download to .ipa file?
> 2. Is the .ipa file the unedited decrypted ipa from App Store?

@yuukiAme 

As I understand it, I need to take the YouTube IPA, attach it to a YouTube.zip archive and upload it to some storage/file sharing site. That's what I did. I ended up trying the ipa from here https://github.com/qnblackcat/Decrypted-IPAs as recommended in other discussions here, also tried with an ipa I pulled from an iPhone using the iMazing app, the YouTube was downloaded from the AppStore. "File sharing" also recommended here www.file.io.

Let's just say it doesn't matter anymore. As I was writing this, it hit me and I decided to try NOT making an archive. Thanks, all this time I was so close..... 
The thing is, I thought I needed an archive because the first time I tried to build, I read another error at the same stage and it said something along the lines of "YouTube.zip, YouTube.zip.zip.zip and the like were not found". I decided to do everything in archives. But there was another problem, the first time I used Google Drive, which, as I've already read, is not very friendly. 

So, I finished it, and it's successfully finished. Thank you.

**Comment by Menojohnson** [comment]
I am having a similar issue however the last line says "Process completed with exit code 2." 

Not sure what this means. I have confirmed that the ipa I am using is YouTube and decrypted and that it is a direct link to download. I even used file.io and still get the same results. Any help would be appreciated. Thanks

**Comment by yuukiAme** [comment]
> I am having a similar issue however the last line says "Process completed with exit code 2."
> 
> Not sure what this means. I have confirmed that the ipa I am using is YouTube and decrypted and that it is a direct link to download. I even used file.io and still get the same results. Any help would be appreciated. Thanks

Make another issue and attach screenshots and logs. I can take a look at it if you want.

**Comment by Menojohnson** [comment]
> > I am having a similar issue however the last line says "Process completed with exit code 2."
> > Not sure what this means. I have confirmed that the ipa I am using is YouTube and decrypted and that it is a direct link to download. I even used file.io and still get the same results. Any help would be appreciated. Thanks
> 
> Make another issue and attach screenshots and logs. I can take a look at it if you want.
> 
> @Menojohnson , I found your build log.
> 
> > YouTube v19.10.5 downloaded!
> 
> You're using the wrong version of Youtube IPA `19.10.5.` Use the `19.08.02` instead. You forked the main branch that used Youtube IPA v19.08.02. The code didn't run properly on iSponsorblock. The error started from there.
> 
> > 1 error generated.
> > make[4]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/rules.mk:390: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.61968dba.o] Error 1
> > make[3]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:52: /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.dylib] Error 2
> > make[2]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/instance/library.mk:37: internal-library-all_] Error 2
> > make[1]: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/rules.mk:146: iSponsorBlock.all.tweak.variables] Error 2
> > make: *** [/Users/runner/work/uYouPlus/uYouPlus/theos/makefiles/master/aggregate.mk:12: internal-all] Error 2
> > rm /Users/runner/work/uYouPlus/uYouPlus/main/.theos/obj/arm64/iSponsorBlock.xm.mm
> > Error: Process completed with exit code 2.

Thanks for replying, I acquired the correct version and received the same error the fisrt time and on the second run i received the following "GitHub Actions has encountered an internal error when running your job" I think this is on githubs end but not sure.
