### ISSUE TITLE
[Questions] where do i get "A decrypted YouTube ipa. You must upload it to a cloud storage service (Dropbox, OneDrive, Google Drive or whatever you want). After that, get the direct download link to the IPA."

### ISSUE THREAD

**Issue by ComfortableMilk4454** [qnblackcat/uYouPlus#1360]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

where do i get "A decrypted YouTube ipa. You must upload it to a cloud storage service (Dropbox, OneDrive, Google Drive or whatever you want). After that, get the direct download link to the IPA." im a noob with this stuff.

### Additional context

any and all responses are much appreciated! thanks so much and have a lovely day/night, and thank you to all the devs for your hard work making this amazing app!

**Comment by yuukiAme** [comment]
Read [qnblackcat's Readme on Decrypted-IPAs](https://github.com/qnblackcat/Decrypted-IPAs)

That's one way to do-it-yourself. Or you could try [appdb](https://appdb.to/?name=YouTube). They do require you to sign in and link your device.

**Comment by iqbal1992** [comment]
There is a shortcut for shorcuts app. That can help you to get decrypted ipas. Google it and you’ll get it.

**Comment by Codepro3000** [comment]
Same problem I don't know anything about github and how to get the link. I made the workflow, but i can't get the link to work

**Comment by ComfortableMilk4454** [comment]
@iqbal1992 if you're talking about https://ipa.decrypt.day/app/id544007664/ the site wants me to install a chrome extension and im pretty sure its malware.

**Comment by yuukiAme** [comment]
> Same problem I don't know anything about github and how to get the link. I made the workflow, but i can't get the link to work

Are you referring to this?

>"...After that, get the direct download link to the IPA."

For example: in Google Drive,

1. you have to upload the decrypted IPA to your own drive. Verify this IPA is the proper version and actually decrypted, otherwise the build will **FAIL**.

2. After the upload is completed, you must **share** that IPA to **anyone with the link** 

3. Open the URL in the browser.

4. It will open a page and hit **download**. A virus scan page will ask you if you want to download. 
 
5. You hit the **download anyway** and the download starts. 

6. **You have to COPY that DIRECT LINK and put that exact URL** in the `Build and Release uYouPlus`.

    - That URL should looks something like this if you're using Google Drive.

```
https://drive.usercontent.google.com/download?id=1a2s3d4f5g6h7j8k&export=download&confirm=t&uuid=123456abc-56as-789z-123a-9876543abcd
```

Referring the [Wiki-Building](https://github.com/qnblackcat/uYouPlus/wiki/Building) if you have no idea what I'm talking about in step 6..

`Direct URL to the decrypted YouTube IPA. The version of YouTube will be detected automatically.`  before you can `run workflow`.

7. The build should run almost immediately as long as GitHub build can reach the IPA.

**Comment by ComfortableMilk4454** [comment]
@yuukiAme i understand all that but i have no idea how to obtain the decrypted ipa. i think this is also what @Codepro3000 is struggling with too.

**Comment by yuukiAme** [comment]
https://github.com/qnblackcat/uYouPlus/issues/1360#issuecomment-2000066428

Literally the OneDrive within the URL I referred to, in qnblackcat's Youtube folder, `Youtube_19.08.2_Qn_.ipa` is in there. If you don't want to do-it-yourself... Just download that IPA and use that decrypted IPA.

**Comment by ComfortableMilk4454** [comment]
yeah ive done that for the time being but i believe thats not up to date is it? its not that i dont want to do it myself, its that i dont know how to lol. if you know how please let me know.

**Comment by yuukiAme** [comment]
Use [frida-ios-dump](https://github.com/AloneMonkey/frida-ios-dump).

You will need a jailbroken device and MacOS. Watch [this video](https://youtu.be/jLlwLoLEIys?feature=shared&t=316) to see it in action.

**Comment by ComfortableMilk4454** [comment]
oh i see. i dont want to jailbreak my device because then itll void the warranty and i have applecare :(. thanks tho. ill stick with the onedrive method! thanks for your help :)

**Comment by ComfortableMilk4454** [comment]
@Codepro3000 here's the ipa using the onedrive method @yuukiAme showed me. https://github.com/ComfortableMilk4454/uYouPlus/actions/runs/8303415987/artifacts/1331115671

**Comment by ComfortableMilk4454** [comment]
Yw! If the link ever stops working let me know I'm happy to upload it to mega or drive or something.

**Comment by Codepro3000** [comment]
> Yw! If the link ever stops working let me know I'm happy to upload it to mega or drive or something.

It’s not working for me. I don’t know if it’s just for me

**Comment by thissitesuckseveryusernametaken** [comment]
> @Codepro3000 here's the final ipa with uYouPlus installed using the onedrive decrypted ipa @yuukiAme showed me. https://github.com/ComfortableMilk4454/uYouPlus/actions/runs/8303415987/artifacts/1331115671

Thank you for this. Theres a new release out but after multiple attempts to run the workflow, i keep getting exit code 8. Any chance you have the most recent?

**Comment by stefe4563** [comment]
> > @Codepro3000 here's the final ipa with uYouPlus installed using the onedrive decrypted ipa @yuukiAme showed me. https://github.com/ComfortableMilk4454/uYouPlus/actions/runs/8303415987/artifacts/1331115671
> 
> Thank you for this. Theres a new release out but after multiple attempts to run the workflow, i keep getting exit code 8. Any chance you have the most recent?

Im having the same problem aswell rn

**Comment by ComfortableMilk4454** [comment]
@thissitesuckseveryusernametaken wdym new release? under https://github.com/qnblackcat/uYouPlus/releases the most recent is feb 27th which is the one thats used in https://github.com/qnblackcat/uYouPlus/issues/1360#issuecomment-2002102190.

**Comment by yodaluca23** [comment]
If y'all are using ArmConverter, then you can just right click on the download symbol and click copy link address and use that as your direct link instead of downloading it and re-uploading it somewhere else...

**Comment by Jordan21002** [comment]
I'm getting exit code 8 as an error, not sure what I'm doing wrong??

**Comment by thespillmonkey** [comment]
YT now also crashing with this current release too.

**Comment by FuzzYnu** [comment]
> YT now also crashing with this current release too.

Disable ISponsorBlock, that should fix it.

**Comment by jmunford** [comment]
> > YT now also crashing with this current release too.
> 
> Disable ISponsorBlock, that should fix it.

how do you do that? I cannot find this option.

**Comment by FuzzYnu** [comment]
> > > YT now also crashing with this current release too.
> > 
> > 
> > Disable ISponsorBlock, that should fix it.
> 
> how do you do that? I cannot find this option.

![IMG_3157](https://github.com/qnblackcat/uYouPlus/assets/168762364/9a710029-19a7-43b8-9872-9cc00446fd20)

**Comment by konjuc** [comment]
> @Codepro3000 here's the final ipa with uYouPlus installed using the onedrive decrypted ipa @yuukiAme showed me. https://github.com/ComfortableMilk4454/uYouPlus/actions/runs/8303415987/artifacts/1331115671

the link isn’t working for me

**Comment by muhzinkhan** [comment]
> @Codepro3000 @ComfortableMilk4454
> 
> > Same problem I don't know anything about github and how to get the link. I made the workflow, but i can't get the link to work
> 
> Are you referring to this?
> 
> > "...After that, get the direct download link to the IPA."
> 
> For example: in Google Drive,
> 
> 1. you have to upload the decrypted IPA to your own drive. Verify this IPA is the proper version and actually decrypted, otherwise the build will **FAIL**.
> 2. After the upload is completed, you must **share** that IPA to **anyone with the link**
> 3. Open the URL in the browser.
> 4. It will open a page and hit **download**. A virus scan page will ask you if you want to download.
> 5. You hit the **download anyway** and the download starts.
> 6. **You have to COPY that DIRECT LINK and put that exact URL** in the `Build and Release uYouPlus`.
>    
>    * That URL should looks something like this if you're using Google Drive.
> 
> ```
> https://drive.usercontent.google.com/download?id=1a2s3d4f5g6h7j8k&export=download&confirm=t&uuid=123456abc-56as-789z-123a-9876543abcd
> ```
> 
> Referring the [Wiki-Building](https://github.com/qnblackcat/uYouPlus/wiki/Building) if you have no idea what I'm talking about in step 6..
> 
> `Direct URL to the decrypted YouTube IPA. The version of YouTube will be detected automatically.` before you can `run workflow`.
> 
> 7. The build should run almost immediately as long as GitHub build can reach the IPA. Good luck!

![Screenshot (215)](https://github.com/qnblackcat/uYouPlus/assets/145433144/11321d5b-c22b-4856-bb25-4bf961dd5584)

**Use this link** from the downloads page of your browser instead of the link from the browser URL to build the ipa from GitHub workflow

**Comment by mohamadsharabi** [comment]
> @thissitesuckseveryusernametaken wdym new release? under https://github.com/qnblackcat/uYouPlus/releases the most recent is feb 27th which is the one thats used in [#1360 (comment)](https://github.com/qnblackcat/uYouPlus/issues/1360#issuecomment-2002102190).

hey bro can u provide me a link for youtube cuz i face error 9 in workflow process : 
2024-05-27 00:09:42 URL:https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fdrive.usercontent.google.com%2Fdownload%3Fid%3D1wRu5WNEJ-_U19ldtRSHFGM2UW4FEEimS%26export%3Ddownload%26authuser%3D0%26confirm%3Dt%26uuid%3D70c788e7-7d1e-45cf-b7d2-61ee17009081%26at%3DAPZUnTUxxVdVgbI4pJuGdFX4f2OW%3A1716768336108&followup=https%3A%2F%2Fdrive.usercontent.google.com%2Fdownload%3Fid%3D1wRu5WNEJ-_U19ldtRSHFGM2UW4FEEimS%26export%3Ddownload%26authuser%3D0%26confirm%3Dt%26uuid%3D70c788e7-7d1e-45cf-b7d2-61ee17009081%26at%3DAPZUnTUxxVdVgbI4pJuGdFX4f2OW%3A1716768336108&ifkv=AaSxoQzbJH1j3vWUYTr1kkCFBWOaE1g1Css3SqXqOn-9TIwibo-8r3aeLHMW9knLSv_CO2cS8poJgA&passive=1209600&service=wise&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S-83769853%3A1716768582316265 [169933] -> "main/YouTube.ipa" [1]
[YouTube.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of YouTube.zip or
        YouTube.zip.zip, and cannot find YouTube.zip.ZIP, period.
Error: Process completed with exit code 9.

**Comment by ComfortableMilk4454** [comment]
@mohamadsharabi 

> hey bro can u provide me a link for youtube cuz i face error 9 in workflow process :(

https://drive.google.com/drive/folders/126wPQzZbnYlgRsEp59awzK6qH_rFFSzs?usp=sharing

**Comment by mohamadsharabi** [comment]
> @mohamadsharabi
> 
> > hey bro can u provide me a link for youtube cuz i face error 9 in workflow process :(
> 
> https://drive.google.com/drive/folders/126wPQzZbnYlgRsEp59awzK6qH_rFFSzs?usp=sharing

thank you, do you know a way to bypass the 7 days limitation or make it unlimited to install IPAS in  iPhone without jailbreak ?

**Comment by ComfortableMilk4454** [comment]
dont think thats possible from what i know

**Comment by Voidrunner42** [comment]
Can I get a new link? Preferably with the new version :)

**Comment by NimuthuGanegoda** [comment]
Now I have the same problem

**Comment by ComfortableMilk4454** [comment]
> Can I get a new link? Preferably with the new version.

@Voidrunner42 i stopped using uYouPlus because of many bugs but i can show you how to build it yourself, hmu on discord my username is `estrobink3509`.

**Comment by ComfortableMilk4454** [comment]
> Now I have the same problem

@NimuthuGanegoda what error are you getting?

**Comment by Tobia12** [comment]
I am getting exit code 8/9.

**Comment by eyal282** [comment]
> @mohamadsharabi
> 
> > hey bro can u provide me a link for youtube cuz i face error 9 in workflow process :(
> 
> https://drive.google.com/drive/folders/126wPQzZbnYlgRsEp59awzK6qH_rFFSzs?usp=sharing

MOOOOM GOGLE MURDERED MY APP AGAIN.

**Comment by iamtushr** [comment]
i need the link


> > @mohamadsharabi
> > > hey bro can u provide me a link for youtube cuz i face error 9 in workflow process :(
> > 
> > 
> > https://drive.google.com/drive/folders/126wPQzZbnYlgRsEp59awzK6qH_rFFSzs?usp=sharing
> 
> MOOOOM GOGLE MURDERED MY APP AGAIN.

the link is not working..please upload fresh link

**Comment by siam69git** [comment]
im getting exit code 2

**Comment by oscardotmp4** [comment]
> im getting exit code 2

same bruh i just want a fix

**Comment by paris1111q1q1q1** [comment]
exit code 2.

**Comment by clqies** [comment]
> Yw! If the link ever stops working let me know I'm happy to upload it to mega or drive or something.

hi! i know its been basically forever, would you mind sending a new link because the link doesn't seem to be working anymore.

**Comment by pierreccortez** [comment]
> ¡Qué bien! Si el enlace deja de funcionar, avísame. Con gusto lo subiré a Mega, Drive o algo así.

Hola estoy intentando descargar la información del ipa pero no está, habrá otro lugar como obtenerlo?
