### ISSUE TITLE
Home App / Blank App 

### ISSUE THREAD

**Issue by enokseth** [qnblackcat/uYouPlus#1362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.3.1
- Device model: IPhone 12 / 64GB
- Sideload tool (AltStore ): ![IMG_0122](https://github.com/qnblackcat/uYouPlus/assets/84675089/b87cbaa5-8e6c-486a-974b-26eb1c95ab28)

### Describe the issue

No Refresh ta startup, app is Blank.

### Steps to reproduce

1. Install app with AltStore
2. Open App and modifing uYouplus param’s, like discale short, autoplay, autoplay not Work 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by DanielAvinoam** [comment]
I have the same issue, seems it's only for a certain account and not my others
Went through the account settings and try to spot the difference, they look the same to me
![image](https://github.com/qnblackcat/uYouPlus/assets/71561723/201326ef-902e-47f4-8ff3-99ab86516ed8)

**Comment by enokseth** [comment]
> J'ai le même problème, il semble que ce ne soit que pour l'un de mes comptes et pas pour les autres.J'ai parcouru les paramètres du compte et j'ai essayé de repérer la différence, ils me semblent les mêmes ![ Image](https://private-user-images.githubusercontent.com/71561723/313704701-201326ef-902e-47f4-8ff3-99ab86516ed8.png? jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzQwMzAsIm5iZiI6MTcxMDcc3MzczMCwicGF0aCI6Ii83MTU2MTcyMy8zMTM3MDQ3MDEtMjAxMzI2ZWYtOTAyZS00N2Y0LThmZjMtOTlhYjg2NTE2ZWQ4LnBuZz9YLUFtei1Bb SSK-6E5nM1O6kmkhA1f616HcF-CpgDyZ_M-mXBQUlxU) ok, je veux dire que YouTube a modifié l'index Of pour faire des bogues de l'application, c'est plus difficile à maintenir et @Miro92 et qnblackcat travaillent dur sur ^^

I would really like to have the uYouPlus code to understand how it works and why not help them

**Comment by Skoshche** [comment]
I had this issue when I was signed into my gmail on YouTube, but not necessarily selected a "YouTube account" as you can have multiple per email. I realized this because if I went to my subscriptions feed it was marked as empty. 
Once I selected an actual YouTube account it fixed itself, I believe the community posts were what was causing the issue.

**Comment by enokseth** [comment]
> I had this issue when I was signed into my gmail on YouTube, but not necessarily selected a "YouTube account" as you can have multiple per email. I realized this because if I went to my subscriptions feed it was marked as empty. 
> Once I selected an actual YouTube account it fixed itself, I believe the community posts were what was causing the issue. 

Ok do thank's for response and bug track ;) ! I going to try this

**Comment by O-PM** [comment]
Same with me when checking subscriptions

**Comment by enokseth** [comment]
Work again magically ^^ !

**Comment by akifurrahman** [comment]
Found a solution. Go to “uYou ——> Other Settings ——> Remove YouTube ads” and turn it off. You will be getting ads on the youtube homepage but not in the videos (atleast thats the case for me)

**Comment by enokseth** [comment]
Yes error is patched you can close this issue ! Thanks

https://github.com/qnblackcat/uYouPlus/assets/84675089/44df4fbc-a356-4ad6-96f5-5eea2e91fc36
