### ISSUE TITLE
crash when trying to watch videos

### ISSUE THREAD

**Issue by lentas1** [qnblackcat/uYouPlus#1364]

**Comment by lentas1** [comment]
it just crashes

**Comment by Electrical6565** [comment]
Turn off sponsorblock

**Comment by Akoi89** [comment]
> Turn off sponsorblock

That fixes it for now, thanks!

**Comment by Nexinity7** [comment]
> Turn off sponsorblock 

back to watching videos! thanks!

**Comment by lentas1** [comment]
> Turn off sponsorblock

i try it now, ty

**Comment by lentas1** [comment]
works now :)

**Comment by Nexinity7** [comment]
why did you close this, this is an active bug

**Comment by lentas1** [comment]
i cant sign in but it is not that important. Atleast i can watch vids

**Comment by lentas1** [comment]
> why did you close this, this is an active bug

reopened :)
