### ISSUE TITLE
[Questions] I Can't build with the first method

### ISSUE THREAD

**Issue by Bob4716** [qnblackcat/uYouPlus#1367]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

how i buil? i follow [guide](https://github.com/qnblackcat/uYouPlus/wiki/Building) but dont work :/ how i can builde my ipa? 

![asdasd](https://github.com/qnblackcat/uYouPlus/assets/96495576/6fd0a383-863e-4e70-a8f8-475edaefcca4)

the Run workflow is missing.

**Comment by gmanc2** [comment]
Mine was able to work. Did you uncheck/check the copy main branch only box? Also, try searching workflow_dispatch in the filter.
![image](https://github.com/qnblackcat/uYouPlus/assets/4944080/ce2f3b8a-91b7-4189-bb53-5173a8934a06)


Unrelated question: Can anyone point me to which version of YouTube you are supposed to use? Also, where can I get an unencrypted IPA?

**Comment by Bob4716** [comment]
> Mine was able to work. Did you uncheck/check the copy main branch only box? Also, try searching workflow_dispatch in the filter.
> 
> ![image](https://github.com/qnblackcat/uYouPlus/assets/4944080/ce2f3b8a-91b7-4189-bb53-5173a8934a06)
> 
> 
> 
> 
> 
> Unrelated question: Can anyone point me to which version of YouTube you are supposed to use? Also, where can I get an unencrypted IPA?

Okay thanks I try later.

Answer for your questions:

I think it might as well be the latest version.

1) Install [TrollDecrypt](https://github.com/donato-fiore/TrollDecrypt)

2) if you have jail phone download tweak - CocoaTop
If you have non-jail device download IPA - [CocoaTop](https://github.com/D0m0/CocoaTop)

Two ipa TrollDecryp and CocoaTop just add to TrollStore.

3) open YouTube and leave it on, Open CocoaTop and search YouTube leave it on, open TrollDecrypt and from CocoaTop rewrite the PID (Process ID) from YouTube and click decrypt. Wait and follow this path to the file: / var/mobile/Containers/Data/Application/ trolldecryptor  and this is it now just share ipa via clod to pc and follow build.
