### ISSUE TITLE
[Questions] What should I enter in the "iOS SDK Version to be used during build"?

### ISSUE THREAD

**Issue by noobdesigner922** [qnblackcat/uYouPlus#1369]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

When I try to ask GitHub Actions, there's a box for iOS SDK version to be used during build. The default value is set to 16.4. Should I let it be 16.4 or should I change it to the iOS version I'm running (17.4.1)?

<img width="332" alt="SCR-20240324-lsoj" src="https://github.com/qnblackcat/uYouPlus/assets/72648637/61387034-eb30-413d-853e-7f5d9a694a24">

**Comment by qnblackcat** [comment]
I'm sorry, we've never asked for this. This is probably another fork of uYou. You should ask for help there
