### ISSUE TITLE
[Questions] Replace with your question

### ISSUE THREAD

**Issue by Mehranullah2017** [qnblackcat/uYouPlus#1371]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Please develop.deb for jailbroken devices
Thanks

### Additional context

Fix ipad crashing problem when play \ing video in full screen on landscape mode only
Donot crashes in portrait mode

**Comment by george2781** [comment]
uYouPlus, when compiled, is a compilation of tweaks intended for jailbroken devices mixed into a single IPA file. If you want to replicate a uYouPlus-like setup you can see all the tweaks used in the README.

As for your crashing issue, please open a new issue with the `bug` template and provide more information.
