### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by swapduzoo** [qnblackcat/uYouPlus#1376]
The youplus application side loaded on 14p crash everytime i want to watch a video

**Comment by VictorBalbo** [comment]
Probably related to https://github.com/qnblackcat/uYouPlus/issues/1361#issue-2188862106
For now, the solution seems to be disabling iSponsorBlock

**Comment by O-PM** [comment]
> Probably related to [#1361 (comment)](https://github.com/qnblackcat/uYouPlus/issues/1361#issue-2188862106) For now, the solution seems to be disabling iSponsorBlock

Had the same problem and this fix it thanks!

**Comment by RWBeginnings** [comment]
Same problem, fixed on iPhone 11

> Probably related to [#1361 (comment)](https://github.com/qnblackcat/uYouPlus/issues/1361#issue-2188862106) For now, the solution seems to be disabling iSponsorBlock

**Comment by texaswheelock** [comment]
> Probably related to [#1361 (comment)](https://github.com/qnblackcat/uYouPlus/issues/1361#issue-2188862106) For now, the solution seems to be disabling iSponsorBlock

For those looking how to do this. 

One the top of the main screen, click the shield with a gear inside of it. Uncheck the Enabled box. 

It crashed one more time when I did this, but I suspect you have to completely relaunch the app for the change to go into affect.

**Comment by qnblackcat** [comment]
should be fixed in the latest commit. If you can't build the IPA, workaround:

https://x.com/PoomSmart/status/1773308512145203429

https://x.com/PoomSmart/status/1783110381462069456
