### ISSUE TITLE
how does the building work i keep trying it and its not working

### ISSUE THREAD

**Issue by Ironarm1** [qnblackcat/uYouPlus#1379]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

it always stops at the ipa part someone please help
![image_2024-03-28_143016977](https://github.com/qnblackcat/uYouPlus/assets/165313782/87af72ed-e4c9-45bb-82b3-0cbf8fc36276)

**Comment by george2781** [comment]
Hi there! It appears you are providing your workflow with a google drive link, unfortunately, that is NOT a direct link to the file and will not allow the workflow to download the IPA you are attempting to use with the workflow.

Try going to that link, downloading your IPA file, then right clicking on the download information in your browser and clicking something like "copy download link", then use that to build.

Please keep me updated on how it goes!

**Comment by megatech1966** [comment]
I don’t understand what to type in direct link to ipa.

**Comment by george2781** [comment]
In the "direct link to IPA" field you need to put a link in which visiting it will ONLY download that IPA (in rudimentary terms anyway), so like I mentioned you should upload your decrypted IPA to google drive, set it so anyone with the link can access it, then download it, then right click on the download and "copy download link", then use that link for that field.

**Comment by megatech1966** [comment]
All sorted

**Comment by defrt** [comment]
just check Actions in this repository and check out latest build and release action

**Comment by qnblackcat** [comment]
Use a direct link to the IPA and everything should work properly
