### ISSUE TITLE
[Questions] Can you replace the guide for installing the YouTube app?

### ISSUE THREAD

**Issue by lilblue22** [qnblackcat/uYouPlus#1380]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Please update the guide I am so lost and confused by it as when I follow the guide and get to the point of installing the YouTube app  it literally just says file does not exist and upon checking the GitHub page here the IPA files are not available to download, just the source files. If you are going to change how to install it you should update the guide.

The guide: https://github.com/qnblackcat/uYouPlus/wiki/AltStore-(macOS-&-Windows-&-Linux)#-macos

When clicking the link that goes to http://tinyurl.com/4vzwk5hx it says Safari cannot open the page because the link is invalid. I tried to install using the AltStore app and it says can't install because  the file does not exist.

### Additional context

uYouPlus (uYou+) could not be downloaded. The file doesn’t exist.

NSCocoaErrorDomain 4

I was able to download "RedditFilter" with no problems at all

**Comment by officiallor** [comment]
Take a look here:

https://github.com/qnblackcat/uYouPlus/releases/tag/v19.08.2-3.0.3   (wiki link)
https://github.com/qnblackcat/uYouPlus/issues/1423  (comments)
