### ISSUE TITLE
YouTube app crash

### ISSUE THREAD

**Issue by Vien78** [qnblackcat/uYouPlus#1381]
When opening a video, it freezes for half a second then gets me back to Home Screen. I have tried reinstalling the app but nothing works for now.

The only thing that works are shorts

**Comment by Xanderman27** [comment]
Same. I wonder if YouTube is trying to patch us out. It was working flawlessly earlier today.

**Comment by JTG-gaming** [comment]
Same Issue, built today
App crashes when opening any video
IPA version 19.12.3
iPadOS 17.4.1 iPad Mini 6

**Comment by JTG-gaming** [comment]
Yep, issue already fixed in latest iSponsorBlock commits
Just need to wait for someone to update all the submodules here again, or pull the change into your own repo manually.

**Comment by tigeryu8900** [comment]
Submodules are updated

**Comment by doohab** [comment]
I can’t find iSponsorBlock settings anywhere inside you+ settings. My device is not jailbroken tho.

**Comment by megatech1966** [comment]
> Turn off iSponsorblock and it should stop crashing

Where is iSponsorblock?
