### ISSUE TITLE
[v19.08.2-3.0.3] Error 1 and 2 when i build - problem with SDK

### ISSUE THREAD

**Issue by Bob4716** [qnblackcat/uYouPlus#1382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 16.1
- Device model: iPhone X (10.6)
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): TrollStore

### Describe the issue

I encountered a build issue that resulted in the following errors:

Error 1:

`Your branch is up to date with 'origin/master'.
mv: rename *.sdk to /Users/runner/work/uYouEnhanced/uYouEnhanced/theos/sdks/*.sdk: No such file or directory`

`Error: Process completed with exit code 1.`

i fix this issue to add 16.1 and is fix error 1.

Error 2:

`==> Error: Your chosen SDK, “iPhoneOS16.4.sdk”, does not appear to exist.
make: *** [/Users/runner/work/uYouEnhanced/uYouEnhanced/theos/makefiles/master/rules.mk:74: before-all] Error 1
Error: Process completed with exit code 2.`

`Error: Your chosen SDK, “iPhoneOS16.4.sdk”, does not appear to exist.`?? i add 16.1

i search issue and people said  uYou have issue with ios 16 but i try ios 15.5 and i have same issue :/

idk how to fix this issue.

### Steps to reproduce

1.  Error 1:  `Your branch is up to date with 'origin/master'.
mv: rename *.sdk to /Users/runner/work/uYouEnhanced/uYouEnhanced/theos/sdks/*.sdk: No such file or directory`

`Error: Process completed with exit code 1.`

2. Error 2:  `==> Error: Your chosen SDK, “iPhoneOS16.4.sdk”, does not appear to exist.
make: *** [/Users/runner/work/uYouEnhanced/uYouEnhanced/theos/makefiles/master/rules.mk:74: before-all] Error 1
Error: Process completed with exit code 2.`

`Error: Your chosen SDK, “iPhoneOS16.4.sdk”, does not appear to exist.`

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by george2781** [comment]
Hi there! I presume you're building with GitHub actions too, in which case you're limited to sdks available in https://github.com/theos/sdks

The `iPhoneOS16.5.sdk` that the workflow runs with by default should be totally fine when it comes to compiling (I successfully built uYouPlus for my iPhone 7 (GSM) (iphone9,3) running iOS 15.8.2 using it).

**Comment by Bob4716** [comment]
> Hi there! I presume you're building with GitHub actions too, in which case you're limited to sdks available in https://github.com/theos/sdks
> 
> 
> 
> The `iPhoneOS16.5.sdk` that the workflow runs with by default should be totally fine when it comes to compiling (I successfully built uYouPlus for my iPhone 7 (GSM) (iphone9,3) running iOS 15.8.2 using it).

Yea, Okay i try thanks

**Comment by LeejinHHyuk** [comment]
> Hi there! I presume you're building with GitHub actions too, in which case you're limited to sdks available in https://github.com/theos/sdks
> 
> The `iPhoneOS16.5.sdk` that the workflow runs with by default should be totally fine when it comes to compiling (I successfully built uYouPlus for my iPhone 7 (GSM) (iphone9,3) running iOS 15.8.2 using it).

It's doesn't work ㅜㅜ it makes error1

**Comment by Bob4716** [comment]
Oh really? Please dev fix this.

**Comment by george2781** [comment]
From the looks of things you're trying to build uYouEnhanced, NOT uYouPlus, I will try to build uYouEnhanced myself however ideally if you're having issues with uYouEnhanced specifically you should report issues over there.

**Comment by george2781** [comment]
uYouEnhanced picks from [this list of sdks](https://github.com/arichornlover/sdks/), so you've got to pick one from in there :)

**Comment by george2781** [comment]
Oh that's weird. ESPECIALLY considering I picked 17.2, NOT 16.4.

![image](https://github.com/qnblackcat/uYouPlus/assets/42376099/219263e0-592f-4bc9-a531-d7418ed5c5bc)

**Comment by george2781** [comment]
Looks like the makefile is hardcoded for 16.4, compiling with that worked flawlessly, though I haven't tested the result.

**Comment by enokseth** [comment]
You just changed the names without changing them all upstream, your error does not come from the selected SDK version nor from Theos, when you "Fork This repository" you will have to uncheck the "main branch only" option and fork it correctly. project, then you will also have to fork 
https://github.com/softprops/action-gh-release, also this one 

https://github.com/kabiroberai/theos-jailed

and this one 

https://github.com/qnblackcat/github-action-create-pr-parent-submodule

and this one

https://github.com/Randomblock1/theos-action


and change line in the buildapp.yaml and or makefile if you need to do.

**Comment by Bob4716** [comment]
> You just changed the names without changing them all upstream, your error does not come from the selected SDK version nor from Theos, when you "Fork This repository" you will have to uncheck the "main branch only" option and fork it correctly. project, then you will also have to fork https://github.com/softprops/action-gh-release, also this one
> 
> https://github.com/kabiroberai/theos-jailed
> 
> and this one
> 
> https://github.com/qnblackcat/github-action-create-pr-parent-submodule
> 
> and this one
> 
> https://github.com/Randomblock1/theos-action
> 
> and change line in the buildapp.yaml and or makefile if you need to do.

okay i do...  its works thank you very much

**Comment by Space-Trucker** [comment]
>and change line in the buildapp.yaml and or makefile if you need to do.

Do i have to uncheck main branch for other repo forks too? 

what lines do i need to change? first time, been trying for a few days now. thanks

**Comment by Space-Trucker** [comment]
> > and change line in the buildapp.yaml and or makefile if you need to do.
> 
> Do i have to uncheck main branch for other repo forks too?
> 
> what lines do i need to change? first time, been trying for a few days now. thanks

Also what names do i need to change?

**Comment by Bob4716** [comment]
> >and change line in the buildapp.yaml and or makefile if you need to do.
> 
> 
> 
> Do i have to uncheck main branch for other repo forks too? 
> 
> 
> 
> what lines do i need to change? first time, been trying for a few days now. thanks 

Just fork this 4 project + uYouPlus and when you fork uncheck this option "Main branch only" when if you do all this step go to uYou project --> action --> and you have there create ... or similar think and just continue...

**Comment by Bob4716** [comment]
> > > and change line in the buildapp.yaml and or makefile if you need to do.
> 
> > 
> 
> > Do i have to uncheck main branch for other repo forks too?
> 
> > 
> 
> > what lines do i need to change? first time, been trying for a few days now. thanks
> 
> 
> 
> Also what names do i need to change?

Like I said if you do it on GitHub website or do you want build it yourself? If not just do it essay way on GitHub thare you don't need to change anything.
