### ISSUE TITLE
[v19.08.2-3.0.3] Install YouTube failed

### ISSUE THREAD

**Issue by vaibd** [qnblackcat/uYouPlus#1385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4.1
- Device model: iPad Air 5th gen
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): AltStore

### Describe the issue

Cant install the new version, getting this error.

Tried reinstalling AltStore, with extension and without extension.

` This app is not compatibile with this device. This app specifies a value for UISupportedDevices in its Info.plist as [iPhone10,1, iPhone10,4, iPhone12,8, iPhone14,6, iPhone8,1, iPhone8,4, iPhone9,1, iPhone9,3, iPod9,1], but none of the identifiers in this device's compatibility list are present in this app's supported devices. This device is compatible with [iPad13,16, iPad13,1]. `

### Steps to reproduce

1. 
2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by jaff80** [comment]
How did you fix this? I get this message: "This app is not compatibile with this device. This app specifies a value for UISupportedDevices in its Info.plist as [iPhone10,1, iPhone10,4, iPhone12,8, iPhone14,6, iPhone8,1, iPhone8,4, iPhone9,1, iPhone9,3, iPod9,1], but none of the identifiers in this device's compatibility list are present in this app's supported devices. This device is compatible with [iPhone14,3, iPhone13,4]."

**Comment by yodaluca23** [comment]
Where did you get the .ipa from?
If you dumped it yourself, make sure you remove UIdevices This can be done with a tool, such as Pyzule.

**Comment by jaff80** [comment]
> Where did you get the .ipa from? If you dumped it yourself, make sure you remove UIdevices This can be done with a tool, such as Pyzule.

Yes, I did the dump myself. I used an app called "AppsDump2" on my iPhone 7 (iOS 15.7.8), which has TrollStore (2.0.15). Can you tell me more information about Pyzule? Thanks!

**Comment by yodaluca23** [comment]
> Yes, I did the dump myself. I used an app called "AppsDump2" on my iPhone 7 (iOS 15.7.8), which has TrollStore (2.0.15). Can you tell me more information about Pyzule? Thanks!

Well, for one I recommend using either bagbak or BFdycrypt.

Pyzule is a .ipa, modification tool that allows you to do several things including inject tweaks change bundleID, remove UIdevices, etc. You can remove UIdevices, from the IPA, which is the reason you're getting said error as each app you download is slightly different depending on each device as it has UIdevices for just that device if you remove them, it'll work on any device.

https://github.com/asdfzxcvbn/pyzule
