### ISSUE TITLE
[Bug] Black Box on video player

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#139]
### Device info
- iOS/iPadOS version: 15.4.1
- Device model: iPad Pro 10.5 (2017)
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: 17.17.4

### Describe the bug
This bug happens mostly on streams and videos, it’s a bug that shows a black box on the left side of the video player and I don’t know why this exists, I only witnessed it on uyouplus not normal YouTube.

### How to reproduce the bug
Here’s an image of it, I don’t have any explanation on how it’s there but have an image of this problem.
![5B6C0540-363B-444F-96A5-7FA9C34D1BF1](https://user-images.githubusercontent.com/78001398/166611213-6f998e66-8f70-454c-8c8f-c53159aa2e13.jpeg)

**Comment by qnblackcat** [comment]
Try disable oled dark mode

**Comment by arichorn** [comment]
It’s not the oled dark mode. I kept it on and then I restarted YouTube and than it fixes the problem, this is the weirdest bug but I don’t know if it will come back which may suck.

**Comment by arichorn** [comment]
Hey qnblackcat, I know what that black box is.
It’s the live chat except functions sometimes break and ends up with just a black box/screen on the left without having the ability to simply disable it. and I did have it off.
If you don’t see it in a stream, you can go across streams and somhow get the bug to trigger when going to certain amounts of live streams.

**Comment by qnblackcat** [comment]
So it‘s a bug of YouTube ?

**Comment by qnblackcat** [comment]
Close due to inactive. Feel free to re-open it later

**Comment by arichorn** [comment]
It’s fixed in the recent version of YouTube
