### ISSUE TITLE
[19.12.3-3.0.3] Home Tab broken

### ISSUE THREAD

**Issue by SomDGit** [qnblackcat/uYouPlus#1390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4.1
- Device model: iPhone 14 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): AltStore

### Describe the issue

When you set the "Default Startup Page" to "You/Library" from the uYou Settings the Home page becomes blank whenever you nagivate to it.

![IMG_2054](https://github.com/qnblackcat/uYouPlus/assets/152484443/f8f9c755-3238-41c1-b5ec-5cbfce085103)

### Steps to reproduce

1. Change Default Startup Page to You/Library
2. Navigate to Home tab

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

I used the official repo from GitHub with my self supplied decrypted YouTube IPA.

**Comment by Xytrizareal** [comment]
prob a invalid decrypted one

doubt its a bug as it works for me xD

**Comment by SomDGit** [comment]
Oh ok

**Comment by likkai** [comment]
Fix: switch to another account, then switch back again

**Comment by SomDGit** [comment]
How do you mean exactly? I changed my startup page to You/Library and then when I opened the app I switched accounts and then switched back, but that did not fix it.

**Comment by likkai** [comment]
> How do you mean exactly? I changed my startup page to You/Library and then when I opened the app I switched accounts and then switched back, but that did not fix it.

What I did was add my alternative account, change to that account, then change back to my main account. Try it a few times, it worked for me

**Comment by SomDGit** [comment]
Oh ok, this bug is not a super big issue for me because I am fin with having the YouTube app start in the Home tab. I guess I will just wait for the developers to fix this bug.

**Comment by mystarkfuture** [comment]
I was also impacted by this issue. Of course the home page not getting loaded is a big problem. 

But around 12 hours ago, this issue seem disappeared. The home page started working as expected. Please check if you still have this issue.

**Comment by SomDGit** [comment]
The issue unfortunately still persists for me.

**Comment by uladzzimir** [comment]
I have the same issue when I set the subscriptions as a start page and hid all the bar buttons except "Home, Subscriptions and You". the solution was to disable hiding the "uYou" tab

**Comment by SomDGit** [comment]
Wow that actually worked! Thanks!

**Comment by jiznon** [comment]
Same issue here, fresh install. I've found that the issue only happens with one of my accounts (both are tied to the same gmail account) -- my google account is from the stone ages where you had a Google Videos account, and i refused to migrate over to the new accounts with channels (i forget the exact terms since its been ages). The old username has the issue, but the "official" account doesn't have the issue

**Comment by SomDGit** [comment]
Oh ok

**Comment by emlodro** [comment]
> Fix: switch to another account, then switch back again

this seems to have worked!! ty

**Comment by SomDGit** [comment]
Nice

**Comment by SomDGit** [comment]
I am getting the issue again now, even if I do not choose You/Library as my start up page. The home sceen is blank at first but when I scroll some elements start to appear but not all of them. Quite annoying haha.

**Comment by SomDGit** [comment]
Has this been fixed?
