### ISSUE TITLE
[v19.08.2-3.0.3] Add your title here...

### ISSUE THREAD

**Issue by Chaudhary1842** [qnblackcat/uYouPlus#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 
- Device model: 
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 

### Describe the issue

When I open video youtube just crash

### Steps to reproduce

1. 
2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by EwenRiallanOcto** [comment]
The problem has already been reported here : https://github.com/qnblackcat/uYouPlus/issues/1393

**Comment by therealFoxster** [comment]
Try [this new build](https://therealfoxster.github.io/altsource-viewer/view/app/?source=https://therealfoxster.github.io/altsource/apps.json&id=com.google.ios.youtube#version-history) and lmk if it still crashes

**Comment by Sid-Lais** [comment]
> Try [this new build](https://therealfoxster.github.io/altsource-viewer/view/app/?source=https://therealfoxster.github.io/altsource/apps.json&id=com.google.ios.youtube#version-history) and lmk if it still crashes

This one works. No crashes so far
