### ISSUE TITLE
[v19.12.3-3.0.3] Casting issue

### ISSUE THREAD

**Issue by timfea926** [qnblackcat/uYouPlus#1395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): ESign 

### Describe the issue

When I click the Cast icon it tells me to go to Settings and enable Local Network access. The thing is Local Network is already enabled! This seems to be a problem across all tweaked YT apps.

### Steps to reproduce

1. Open uYouPlus v19.12.3-3.0.3
2. Click the Cast icon at the top 
3. When the prompt shows up Enable Local Network Access, open the Settings app and click YouTube to confirm that Local Network is in fact checked off
4. With Local Network enabled, close uYouPlus and restart, then try clicking the Cast icon again. If you have my problem, you will continue to get the same prompt to enable local network access even though you’ve already done so.
![IMG_4390](https://github.com/qnblackcat/uYouPlus/assets/50429353/4003fcb4-edf6-47e1-b43a-aa27c7424eaa)

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

Like everyone else, I also have the problem with Sponsorblock causing the app to crash. Right now it’s disabled so I can actually watch videos.

**Comment by IphoneCake** [comment]
I had the same bug. I was able to work around it with a workaround by simply turning off the WLAN and then pressing the cast function again. If you have an Alexa Fire TV Stick or Cube, it should also be found, even if you are not connected to the Wi-Fi. Now press connect and you can stream via your smartphone again. However, this only works as long as the stick or Cube has power and remains switched on. If you disconnect the device from the power supply, simply repeat the steps.
I would be very grateful for a fix from Miro or arichornlover

Kind regards
Dominik

**Comment by Yunogamer** [comment]
using it over cellular works fine, link the destination device by manual code. access casting to add the code by youtube settings, not the casting icon on main screen.

looks like broken by some tweak change not google or it be broken both ways not just wifi..

**Comment by Stavrak2** [comment]
19.07.5 appears to work

at a guess we’re running sideloaded versions and it’s checking the specific YouTube app identifier has the setting turned on and not finding it

**Comment by IphoneCake** [comment]
Yes, the same applies to me. I use the uyouEnhanced [v19.02.1-3.0.1]
The uyouEnhanced version should have been released around the date 01.18.2024. 
I had updated to 3.0.3 [v19.10.5-3.0.3](https://github.com/arichornlover/uYouEnhanced/releases/tag/v19.10.5-3.0.3) recently, because I wanted to update again and only had problems. Sponsor block no longer worked, app kept crashing, so hardly usable. That was about a month ago. I then installed uyouEnhanced [v19.02.1-3.0.1] Version again via sideload, everything worked again as before, no problems. This also lasted for about 1 month.
Until recently the update 17.4.1 was installed via Itunes, because I wanted to make a backup of my IPhone 14 Pro Max. 
Then the massive casting problems started. 
As the previous speakers have already said, turn off WIFI and do it via cellular. It is best to connect to the TV beforehand using a manual code with the iPhone. I currently use a Fire TV Cube from Amazon with the "Smarttube" application. It should definitely work with this interaction. 
I would be interested to know, which IOS versions you have installed or whether it really is a Google problem, as older versions of uyouEnhanced are also affected by the problem. 

Kind regards 
Dominik

**Comment by Write** [comment]
I can confirm the bug happens on sideloaded YouTube even without any addons / plugins added.

**Comment by Stavrak2** [comment]
I think I’ve fixed it. Here’s how:

Go to You —> Settings —> A/B —> Enable to show A/B settings (if not already enabled). Reopen YouTube

again go to You —> Settings —> A/B. In search settings enter ‘local’. Enable the one ending ‘wififixes’ and the one ending ‘reliabilityfixes’. Go back, force close and app and reopen.

Seems to work for me.

**Comment by timfea926** [comment]
Unfortunately, these changes did not work for me. However, I am still using 19.4.3 as I rely on others to get me the latest IPA copies since I don't know how to convert the zip files. Could this be the reason?

**Comment by Write** [comment]
> Unfortunately, these changes did not work for me.

Yup it stopped working for me too. weird.. -.-

**Comment by Bigmac375** [comment]
This bug appeared after update, and the fix listed does not work, except for the switch to cellular. uYou enhanced current version works fine when casting

**Comment by Stavrak2** [comment]
> > I think I’ve fixed it. Here’s how:
> > Go to You —> Settings —> A/B —> Enable to show A/B settings (if not already enabled). Reopen YouTube
> > again go to You —> Settings —> A/B. In search settings enter ‘local’. Enable the one ending ‘wififixes’ and the one ending ‘reliabilityfixes’. Go back, force close and app and reopen.
> > Seems to work for me.
> 
> Thanks a lot, it seems to work for me too !
> 
> I couldn't find wififixes you mentioned but I just enabled
> 
> cxClientEnablelosLocalNetworkPermissionReliabilityFixes
> 
> And it works great so far
> 
> ![image](https://private-user-images.githubusercontent.com/541722/323226118-6e6e6930-b138-40ae-ad5e-9ea50a7efec7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjQxNDMsIm5iZiI6MTcxNDM2Mzg0MywicGF0aCI6Ii81NDE3MjIvMzIzMjI2MTE4LTZlNmU2OTMwLWIxMzgtNDBhZS1hZDVlLTllYTUwYTdlZmVjNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMDQxMDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTIyM2JkNmRlNzczZWE2ODA0NjMyMmQwOWMyODYyOGExZDA0NWM2NWEzZWJjNWUxMDZmODUwZTA0NGY3N2IwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ffME3X-H2RpuYgbClkceG2S2zTYqy0ieckqd02DtzBQ)

Can you screenshot what appears when you search the word 'local'? As one of the flags appears when I do that which you may not have enabled (or not been able to)

**Comment by Freenex1911** [comment]
These changes **do not** work for me either. I still get the casting issue.
<img src="https://github.com/qnblackcat/uYouPlus/assets/15677860/34f2089f-13e0-43fc-9a49-48963a88867a" height="500">

Model: iPhone 15 Pro
iOS: 17.4.1
uYouPlus: 19.10.7-3.0.3

**Comment by tdsf** [comment]
Working with only those 2 toggled.
![image](https://github.com/qnblackcat/uYouPlus/assets/13088363/266bad02-65f6-4133-9558-e554ac0c8006)

**Comment by Freenex1911** [comment]
It works! I just had to disable the `cxClientEnableIosLocalNetworkPermissionUsingSockets` option too.

**Comment by khermancreative** [comment]
Can’t find
cxClientEnableIosLocalNetworkPermissionReliabilityFixes either… uYouPlus ipa version 19.09.2-3.0.3 and AltStore 1.7.

**Comment by rbouma** [comment]
Can confirm after also disabling YTColdConfig.cxClientEnableIosLocalNetworkPermissionUsingSockets what @YabberWalkie suggested its working.

**Comment by webmatrixxxl** [comment]
Not working for me on iOS

**Comment by Stavrak2** [comment]
> This configuration does not working for me on iOS

What, exactly, have you done?

**Comment by webmatrixxxl** [comment]
> > This configuration does not working for me on iOS
> 
> What, exactly, have you done?

Total: 4
YTColdConfig.cxClientEnableIosLocalNetworkPermissionReliabilityFixes: 1
YTColdConfig.cxClientEnableIosLocalNetworkPermissionUsingSockets: 0
YTColdConfig.cxClientEnableIosLocalNetworkPermissionWifiFixes: 1
YTHotConfig.isPromptForLocalNetworkPermissionsEnabled: 1


YouTube 19.17.2
uYou 3.0.3
I
iOS latest

**Comment by diegoorosa** [comment]
Still not working for cast, all the settings was already like the one mentioned.

**Comment by TheFern2** [comment]
> It works! I just had to disable the `cxClientEnableIosLocalNetworkPermissionUsingSockets` option too.

Same for me now I can AirPlay but the quality is very bad? Any idea how to fix it or if there is a fix or another way to get better quality?

**Comment by plexolot** [comment]
Solution from YabberWalkie does not work for me.

I dont have:
YTHotConfig.isPromptForLocalNetworkPermissionsEnabled

![Image](https://github.com/user-attachments/assets/3d734650-4e01-4e9f-97a5-8c26cc877236)

**Comment by Stavrak2** [comment]
I’m the person who originally posted the Wi-Fi fixes above. 

This and a number of other issues have made me move to YTLitePlus which I believe works better now, casting works, downloading of videos works 

Give it a go https://github.com/YTLitePlus/YTLitePlus
