### ISSUE TITLE
uyou+ Crashing issue

### ISSUE THREAD

**Issue by abubakrabdeen** [qnblackcat/uYouPlus#1396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 15.8.2
- Device model: iphone 7
- Sideload tool:TrollStore

### Describe the issue

Every time I try to open a video it crashes directly ,everything runs ok except running a video.

https://github.com/qnblackcat/uYouPlus/assets/142250859/68240d36-eaf3-49d7-bd9c-dab9395f5704

### Steps to reproduce

1. 
2. 

### Crash log

```shell
https://files.fm/u/xvtv2n6me5
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by szymcelo** [comment]
Same problem, except it happen to me in official app as well, YouTube made update. After I updated the official app, it works flawlessly. (Official one only)

**Comment by yuukiAme** [comment]
Turn off iSponsorblock.

**Comment by abubakrabdeen** [comment]
> Same problem, except it happen to me in official app as well, YouTube made update. After I updated the official app, it works flawlessly. (Official one only)

Tbh official youtube works without crashes with me

**Comment by abubakrabdeen** [comment]
> Turn off iSponsorblock.

Solved , Thanks alot mate

**Comment by iulo** [comment]
@yuukiAme Where is it? path please?
