### ISSUE TITLE
[v19.08.2-3.0.3] Red progress bar option stopped working (build Mar 31, 2024)

### ISSUE THREAD

**Issue by eduedp** [qnblackcat/uYouPlus#1397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version:  16.3.1
- Device model: iPhone 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.):  Trollstore

### Describe the issue

The red progress bar does not remain permanently red anymore.

On previous versions of uYouPlus, if you enabled the option [Setting -> uYouPlus -> Red progress bar], the progress bar would be permanently red all the time.

Now on the latest version I built from Mar 31, 2024 commit, this options have no effect. The progress bar acts like on original Youtube app, turning red just when you interact with the video, and turning back to white after some seconds.

### Steps to reproduce

1. Play any video in landscape or portrait mode, see the progress bar is white, and just change to red when you interact with the video.
2. Enable [Setting -> uYouPlus -> Red progress bar]
3. Play any video in landscape or portrait mode and see nothing has changed, the progress bar still acts like on step 1.

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

I was using the latest released version v19.08.2-3.0.3 before oficial releases were taken down and on that version it was working.
But I had to build and update to the latest commit yesterday to fix that iSponsorBlock bug that was crashing on all videos.

**Comment by PoomSmart** [comment]
Fixed in the latest commit
