### ISSUE TITLE
Download completion handler never called when signed with distribution certificate

### ISSUE THREAD

**Issue by castdrian** [qnblackcat/uYouPlus#1398]
This is an issue I have observed with   multiple applications, not just uyp, downloads will succeed up to the end after which the file is never saved and the completion handler is never called, whereas it works fine when signed with a local development certificate

**Comment by worriorbg** [comment]
Same here - every download freezes on 100%. 
App is signed with a paid developer certificate (Apple ID Sideload).

Does any one have a workaround for this? 

![Stuck on 100%](https://github.com/qnblackcat/uYouPlus/assets/5908742/df885134-55b9-4bcc-aea4-79b88aac84ed)

**Comment by Edouard127** [comment]
Same issue here, any workaround ?

**Comment by fwmaietta** [comment]
Same Issue. Has anybody figured out a workaround?

**Comment by fwmaietta** [comment]
> This is an issue I have observed with multiple applications, not just uyp, downloads will succeed up to the end after which the file is never saved and the completion handler is never called, whereas it works fine when signed with a local development certificate

I'm having the same issue. I tried installing over the air with my distribution cert, as well as signing with an iOS development cert and an Apple Development cert and side loading through Xcode. I still couldn't get the downloads to finish with any of them.

**Comment by therysin** [comment]
Same issue here signing with a paid certificate.

**Comment by castdrian** [comment]
fyi since I didn't mention this in my OP, this is due to the wildcard app id so you essentially need to sign with an explicit app id for the application to be able to use the required system capabilities

**Comment by therysin** [comment]
> fyi since I didn't mention this in my OP, this is due to the wildcard app id so you essentially need to sign with an explicit app id for the application to be able to use the required system capabilities

I signed with the default app ID, not a random app ID. Are you saying it works with the random app ID?

**Comment by castdrian** [comment]
the applications bundle id and app id are not the same thing

**Comment by joshuaseltzer** [comment]
Did you guys ever figure this out? I'm not using a wildcard ID, but using a paid developer account. Experiencing the same download issues.
