### ISSUE TITLE
Video history not being tracked

### ISSUE THREAD

**Issue by lolKaizen** [qnblackcat/uYouPlus#1399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: IOS 17.4.1
- Device model: 15 pro
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): altstore

### Describe the issue

History is not tracked when videos are played through the app.

### Steps to reproduce

1. Open app
2. Play video 
3. Check history
4. Video doesn’t appear in history

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

History is properly tracked on YouTube website

**Comment by yodaluca23** [comment]
Did you read the FAQs?

https://github.com/qnblackcat/uYouPlus/wiki/FAQs#q-my-watch-history-not-syncing
