### ISSUE TITLE
[Bug] Create Buttons still visible

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#14]
**Device info**
- iOS/iPadOS version: 15.2
- Device model: 12
- Sideload tool (Ex: AltStore, Sideloadly...): Sideloadly

**Describe the bug**
- The buttons "Create Short" and "Create Clip" are still visible under the video although disabled in uYou.

**How to Reproduce the bug**
_(Please attach videos or screenshots if possible)_

![image](https://user-images.githubusercontent.com/40891294/144919647-170e5921-b5e5-4668-a9aa-b6d8fcf2fb35.jpeg)
![image](https://user-images.githubusercontent.com/40891294/144919680-d7694b2d-160e-444f-bcc6-850e5046ec53.jpeg)

**Additional context**

**Comment by qnblackcat** [comment]
It's a known issue of **uYou**. Please follow this theard: https://github.com/MiRO92/uYou-for-YouTube/issues/47
