### ISSUE TITLE
[Bug] PiP loading when watching YouTube livestreams

### ISSUE THREAD

**Issue by luhcrankem** [qnblackcat/uYouPlus#140]
iOS/iPadOS version: 14.2
Device model: iPhone XS
Sideload tool (Ex: AltStore, Sideloadly...) AltStore
Version of uYouPlus: 2.1

![image](https://user-images.githubusercontent.com/98666421/166804820-cf8b1123-05c1-4610-9c33-dfe5a4d45ed5.png)

**Comment by qnblackcat** [comment]
I can’t reproduce it. Bear in mind that YouPiP works best with iOS 14.5 and higher.

@PoomSmart can you recall it?

**Comment by qnblackcat** [comment]
YouPiP works best with iOS 14.5 and up. Considering to upgrade to your iOS version.

**Comment by qnblackcat** [comment]
Closed due to inactive
