### ISSUE TITLE
Videos not loading correctly on the homepage

### ISSUE THREAD

**Issue by 4zwc** [qnblackcat/uYouPlus#1401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version:  ios 16.3.1
- Device model: iphone 11 A13
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.):  Trollstore

### Describe the issue

uYouPlus seems to be having issues loading youtube videos when you first open the app. a video or two will show up but scrolling down itll just be empty until you swipe up and down and then a few videos will show up.

### Steps to reproduce

1. open youtube app

![image](https://github.com/qnblackcat/uYouPlus/assets/66004822/bc6e3a37-ca9a-4484-b4bd-e3f83e6fc93e)

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by VIEWVIEWVIEW** [comment]
does this only happen on the account you already had added?
If you add a new Google account to the YouTube app and switch to that channel, does that happen with one too?

When I add a new Google account, it doesn't happen on that one.

**Comment by Hacksev** [comment]
Me too!!!

**Comment by akifurrahman** [comment]
https://github.com/qnblackcat/uYouPlus/issues/1413#issuecomment-2065784577

**Comment by RealBlackAstro** [comment]
![767F0463-7E23-434F-9FC8-8A0CD7F94F96](https://github.com/qnblackcat/uYouPlus/assets/167844123/e1d92318-a9b0-4d5e-abaf-4bf0723b8428)
so uhh I did the thing and YouTube feeds me this nonsense. we need a fix asap.
