### ISSUE TITLE
[Wiki] Update build wiki to accommodate easier building 

### ISSUE THREAD

**Issue by Sid-Lais** [qnblackcat/uYouPlus#1403]
Latest Build wiki steps seems to be confusing for many people. Many cloud storage seems to be not working properly. A new update to the wiki with working cloud provider steps would be beneficial for everyone.

**Comment by Sid-Lais** [comment]
https://github.com/Sid-Lais/uYouPlus/wiki/Building

Made the changes and added the steps for working dropbox link

**Comment by defrt** [comment]
Just go actions in this repository and check out latest build and release action
