### ISSUE TITLE
[19.08.2-3.0.3] Shorts ads started reappearing

### ISSUE THREAD

**Issue by lukas27892** [qnblackcat/uYouPlus#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4
- Device model: iPhone 14
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): SideStore 

### Describe the issue

![image](https://github.com/qnblackcat/uYouPlus/assets/77806315/5e7ed68c-d075-412f-a750-a357be00d436)

### Steps to reproduce

1. Open uyouplus 19.08.2-3.0.3
2. Go to shorts and scroll down until you see an ad

### Crash log

```shell
No response
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by mardeyar** [comment]
I don't have anything to offer to help but I'm also seeing ads getting through on shorts
