### ISSUE TITLE
[Questions] App is crashing 

### ISSUE THREAD

**Issue by kingcheeese** [qnblackcat/uYouPlus#1408]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

App is crashing when trying to play a video. tried reinstalling the app with and without extensions but no luck

**Comment by InvisibleRasta** [comment]
same thing happening for me on 2 different devices

**Comment by lvprelvpre** [comment]
Disable Sponsorblock block.  Known issue

#1364

**Comment by lihuelworks** [comment]
Same here, disabling sponsorblock fixed it. Would still like to use Sponsorblock tho
