### ISSUE TITLE
[v19.08.2-3.0.3] Homepage, scrolling glitch

### ISSUE THREAD

**Issue by mermiad** [qnblackcat/uYouPlus#1413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4.1
- Device model: iphone 12 pro
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): sideloadly

### Describe the issue

The Home tab is glitching a bit, when scrolling a lot of the videos/shorts switch between invisible and visible. Is this happening to anyone else ? It’s difficult to browse through the tab because of that. It happens also a bit after the first vid in the subscriptions tab but the rest works fine. Is this because of a specific option turned on ? Thank you. 

### Steps to reproduce

1. This is how it looks when it’s opened.
![IMG_3963](https://github.com/qnblackcat/uYouPlus/assets/166369177/687111ff-fdd3-4dec-9ca2-4b0e779bbacd)

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by ChosenZero** [comment]
same here

**Comment by akifurrahman** [comment]
Found a solution. Go to “uYou ——> Other Settings ——> Remove YouTube ads” and turn it off. You will be getting ads on the youtube homepage but not in the videos (atleast thats the case for me)

**Comment by mermiad** [comment]
> Found a solution. Go to “uYou ——> Other Settings ——> Remove YouTube ads” and turn it off. You will be getting ads on the youtube homepage but not in the videos (atleast thats the case for me)

Thank you! It does work. Too bad you need to have the ads for it when it works fine when you log onto another account. It's not too bothersome though so, thank you.

**Comment by dpyy** [comment]
fix owrks, but I wish to kill ads again

**Comment by fshskyline** [comment]
So the “fix” is to disable the 1 setting which is one of the main reasons people use uYou in the first place…

**Comment by akifurrahman** [comment]
"Well yes, but actually no". This settings shows ads on the YouTube homepage, not before the videos in the video player.

**Comment by ElminL** [comment]
> "Well yes, but actually no". This settings shows ads on the YouTube homepage, not before the videos in the video player, Which is kinda tolerable ig.

Not all true, I get ads in my videos when I disable it.

**Comment by akifurrahman** [comment]
> > "Well yes, but actually no". This settings shows ads on the YouTube homepage, not before the videos in the video player, Which is kinda tolerable ig.
> 
> Not all true, I get ads in my videos when I disable it.

Strange, that's not the case for me

**Comment by GoobyBooby** [comment]
Had this happened to me, I disabled the "Remove Youtube Ads" and everything was fine until now. It's the same behaviour but in the Watch Later playlist. Did someone solved this?

**Comment by Prombeere** [comment]
Still no fix?

**Comment by ashmodai6** [comment]
Actually I confirm that the same happens for me : yes toggling this settings replace the blank spaces by .. ads ... which is not great but even worst is the fact that I get ads in videos as well which basically kill 99% of the value of replacing the youtube app by an alternative (at least for me)

**Comment by voxpop9** [comment]
> Found a solution. Go to “uYou ——> Other Settings ——> Remove YouTube ads” and turn it off. You will be getting ads on the youtube homepage but not in the videos (atleast thats the case for me)

After seeing how some people still get ads in videos and some do not, i have figured out the additional steps to the full solution.

Step 1: Disable ad blocker in uYou settings as described above.

Step 2: Go to You -> Settings (gear icon) -> A/B -> and enable it. If yours is already enabled, disable it, restart, and then enable it again, followed by another restart.

This should not only return the home page, but should remove the Ads. I did however notice that sometimes it doesn't work, so you would have to restart the app.

**Comment by seulgiism** [comment]
suddenly out of nowhere got this glitch as well. don't know what triggered it, didn't had it before.

**Comment by gtsync** [comment]
> > Found a solution. Go to “uYou ——> Other Settings ——> Remove YouTube ads” and turn it off. You will be getting ads on the youtube homepage but not in the videos (atleast thats the case for me)
> 
> After seeing how some people still get ads in videos and some do not, i have figured out the additional steps to the full solution.
> 
> Step 1: Disable ad blocker in uYou settings as described above.
> 
> Step 2: Go to You -> Settings (gear icon) -> A/B -> and enable it. If yours is already enabled, disable it, restart, and then enable it again, followed by another restart.
> 
> This should not only return the home page, but should remove the Ads. I did however notice that sometimes it doesn't work, so you would have to restart the app.

What is the A/B setting?

**Comment by voxpop9** [comment]
> > > Found a solution. Go to “uYou ——> Other Settings ——> Remove YouTube ads” and turn it off. You will be getting ads on the youtube homepage but not in the videos (atleast thats the case for me)
> > 
> > 
> > After seeing how some people still get ads in videos and some do not, i have figured out the additional steps to the full solution.
> > Step 1: Disable ad blocker in uYou settings as described above.
> > Step 2: Go to You -> Settings (gear icon) -> A/B -> and enable it. If yours is already enabled, disable it, restart, and then enable it again, followed by another restart.
> > This should not only return the home page, but should remove the Ads. I did however notice that sometimes it doesn't work, so you would have to restart the app.
> 
> What is the A/B setting?

I have always assumed it stood for Ad Blocker. Doesn't work however, so ignore it.

**Comment by gtsync** [comment]
> > > > Found a solution. Go to “uYou ——> Other Settings ——> Remove YouTube ads” and turn it off. You will be getting ads on the youtube homepage but not in the videos (atleast thats the case for me)
> > > 
> > > 
> > > After seeing how some people still get ads in videos and some do not, i have figured out the additional steps to the full solution.
> > > Step 1: Disable ad blocker in uYou settings as described above.
> > > Step 2: Go to You -> Settings (gear icon) -> A/B -> and enable it. If yours is already enabled, disable it, restart, and then enable it again, followed by another restart.
> > > This should not only return the home page, but should remove the Ads. I did however notice that sometimes it doesn't work, so you would have to restart the app.
> > 
> > 
> > What is the A/B setting?
> 
> I have always assumed it stood for Ad Blocker. Doesn't work however, so ignore it.

I suppose I should’ve been more clear. I was asking which setting in the A/B menu (that is accessed from YouTube settings rather than uYou settings).

**Comment by voxpop9** [comment]
> > > > > Found a solution. Go to “uYou ——> Other Settings ——> Remove YouTube ads” and turn it off. You will be getting ads on the youtube homepage but not in the videos (atleast thats the case for me)
> > > > 
> > > > 
> > > > After seeing how some people still get ads in videos and some do not, i have figured out the additional steps to the full solution.
> > > > Step 1: Disable ad blocker in uYou settings as described above.
> > > > Step 2: Go to You -> Settings (gear icon) -> A/B -> and enable it. If yours is already enabled, disable it, restart, and then enable it again, followed by another restart.
> > > > This should not only return the home page, but should remove the Ads. I did however notice that sometimes it doesn't work, so you would have to restart the app.
> > > 
> > > 
> > > What is the A/B setting?
> > 
> > 
> > I have always assumed it stood for Ad Blocker. Doesn't work however, so ignore it.
> 
> I suppose I should’ve been more clear. I was asking which setting in the A/B menu (that is accessed from YouTube settings rather than uYou settings).

Nevermind, I just realized that was to show the A/B settings. Ignore my solution.

**Comment by CattoYT** [comment]
Can confirm that this glitch is also happening with me on trollstore and sideloadly.

**Comment by voxpop9** [comment]
I have found a better temporary solution: In the uYou settings, turn "iPad layout" on. You can keep ad block on.

**Comment by ElminL** [comment]
⚠️I FOUND A SOLUTION THAT DOESNT INVOLVE REMOVING ADS.⚠️
SIMPLY TURN ON "Force IPhone Layout" it's in UYouPlus settings. Not the one in general. It's simply one below the setting Return YouTube Dislike.

I haven't tested this enough but my home layout works as it should without ads or any problems.

If you're on iPad use "force iPad layout" which is in "other settings" in general>UYou settings>other setttings>force iPad layout.

**Comment by ElminL** [comment]
> So the “fix” is to disable the 1 setting which is one of the main reasons people use uYou in the first place…

I found the fix

⚠️I FOUND A SOLUTION THAT DOESNT INVOLVE REMOVING ADS.⚠️
SIMPLY TURN ON "Force IPhone Layout" it's in UYouPlus settings. Not the one in general. It's simply one below the setting Return YouTube Dislike.

I haven't tested this enough but my home layout works as it should without ads or any problems.

If you're on iPad use "force iPad layout" which is in "other settings" in general>UYou settings>other setttings>force iPad layout.

**Comment by ElminL** [comment]
> fix owrks, but I wish to kill ads again

⚠️I FOUND A SOLUTION THAT DOESNT INVOLVE REMOVING ADS.⚠️
SIMPLY TURN ON "Force IPhone Layout" it's in UYouPlus settings. Not the one in general. It's simply one below the setting Return YouTube Dislike.

I haven't tested this enough but my home layout works as it should without ads or any problems.

If you're on iPad use "force iPad layout" which is in "other settings" in general>UYou settings>other setttings>force iPad layout.

**Comment by oliviaiacovou** [comment]
> ⚠️I FOUND A SOLUTION THAT DOESNT INVOLVE REMOVING ADS.⚠️
> SIMPLY TURN ON "Force IPhone Layout" it's in UYouPlus settings. Not the one in general. It's simply one below the setting Return YouTube Dislike.
> 
> I haven't tested this enough but my home layout works as it should without ads or any problems.
> 
> If you're on iPad use "force iPad layout" which is in "other settings" in general>UYou settings>other setttings>force iPad layout.

not working for me unfortunately

**Comment by voxpop9** [comment]
> > ⚠️I FOUND A SOLUTION THAT DOESNT INVOLVE REMOVING ADS.⚠️
> > SIMPLY TURN ON "Force IPhone Layout" it's in UYouPlus settings. Not the one in general. It's simply one below the setting Return YouTube Dislike.
> > I haven't tested this enough but my home layout works as it should without ads or any problems.
> > If you're on iPad use "force iPad layout" which is in "other settings" in general>UYou settings>other setttings>force iPad layout.
> 
> not working for me unfortunately

Perhapse u also need to use version 3.0.4 of uYou when you make your own IPA

**Comment by ElminL** [comment]
> > ⚠️I FOUND A SOLUTION THAT DOESNT INVOLVE REMOVING ADS.⚠️
> > SIMPLY TURN ON "Force IPhone Layout" it's in UYouPlus settings. Not the one in general. It's simply one below the setting Return YouTube Dislike.
> > 
> > I haven't tested this enough but my home layout works as it should without ads or any problems.
> > 
> > If you're on iPad use "force iPad layout" which is in "other settings" in general>UYou settings>other setttings>force iPad layout.
> 
> not working for me unfortunately

I have the latest version with most of the commits. Maybe try to get a different version.

**Comment by ElminL** [comment]
> > > ⚠️I FOUND A SOLUTION THAT DOESNT INVOLVE REMOVING ADS.⚠️
> 
> > > SIMPLY TURN ON "Force IPhone Layout" it's in UYouPlus settings. Not the one in general. It's simply one below the setting Return YouTube Dislike.
> 
> > > I haven't tested this enough but my home layout works as it should without ads or any problems.
> 
> > > If you're on iPad use "force iPad layout" which is in "other settings" in general>UYou settings>other setttings>force iPad layout.
> 
> > 
> 
> > not working for me unfortunately
> 
> 
> 
> Perhapse u also need to use version 3.0.4 of uYou when you make your own IPA

There isn't a 3.0.4? I thought there's only 3.0.3 with commits done to it. I have 3.0.3

**Comment by voxpop9** [comment]
> > fix owrks, but I wish to kill ads again
> 
> ⚠️I FOUND A SOLUTION THAT DOESNT INVOLVE REMOVING ADS.⚠️ SIMPLY TURN ON "Force IPhone Layout" it's in UYouPlus settings. Not the one in general. It's simply one below the setting Return YouTube Dislike.
> 
> I haven't tested this enough but my home layout works as it should without ads or any problems.
> 
> If you're on iPad use "force iPad layout" which is in "other settings" in general>UYou settings>other setttings>force iPad layout.

Cam confirm this works for me

**Comment by voxpop9** [comment]
nvm neither solution worked, i had incorrect settings

**Comment by ElminL** [comment]
> nvm neither solution worked, i had incorrect settings

It has to be your version of the ipa. I had to update mine to a better version of more of the commits.

**Comment by voxpop9** [comment]
> > nvm neither solution worked, i had incorrect settings
> 
> It has to be your version of the ipa. I had to update mine to a better version of more of the commits.

Check if you accidentally disabled remove ads in you, that's what happened to me

**Comment by qnblackcat** [comment]
Sorry for the inconvenience, guys. We will be implementing PoomSmart's method to block ads soon. I believe it will resolve all the known issues with ads and blocking shorts.

**Comment by ElminL** [comment]
> > > nvm neither solution worked, i had incorrect settings
> 
> > 
> 
> > It has to be your version of the ipa. I had to update mine to a better version of more of the commits.
> 
> 
> 
> Check if you accidentally disabled remove ads in you, that's what happened to me

It's on, cause I'm not getting any ads on my feed. And it's on in my settings.

**Comment by ElminL** [comment]
> Sorry for the inconvenience, guys. We will be implementing PoomSmart's method to block ads soon. I believe it will resolve all the known issues with ads and blocking shorts.
> 
> 
> 
> 

Great thanks for the effort. But this "force iPhone layout" works perfectly for me. Practically acts as it should now.

**Comment by voxpop9** [comment]
> Sorry for the inconvenience, guys. We will be implementing PoomSmart's method to block ads soon. I believe it will resolve all the known issues with ads and blocking shorts.

Thank you!

**Comment by fshskyline** [comment]
Strangely enough after updating to 3.0.4 (I had been notified days prior but never got round to it) it appears to be working as normal now, but what’s even stranger is “Remove YouTube Ads” is disabled yet I’m getting no ads, not gonna complain about that though or touch anything! 😂

**Comment by ElminL** [comment]
> Sorry for the inconvenience, guys. We will be implementing PoomSmart's method to block ads soon. I believe it will resolve all the known issues with ads and blocking shorts.
> 
> 
> 
> 

Idk if this is a new issue or not but when looking at videos scrolling under a video it has the same delayed loading times as the recommended screen(recommended I fixed already)

**Comment by ElminL** [comment]
So the issue with blank recommendation page is back. It's occurred randomly even after it's been working fine for a week or so. The issue continues. I had to turn off ad block again.

**Comment by ClassicxPY** [comment]
I had this issue. Solved it with uyou -> settings -> other settings -> remove YouTube ads -> off

at first I got ads in the video, restarted the app and that did the trick. I’ll see ads on the homescreen  sometimes (not in video). If you are seeing ads in the video try toggling that setting a few times. A/B did nothing. v. 3.0.4 uyou enhanced.

**Comment by voxpop9** [comment]
Temporary solution that i found is to keep add block on. The page will be empty, but if you scroll down far enough, videos start to pop back up. Some will blink in and out of existence.

**Comment by ElminL** [comment]
> Temporary solution that i found is to keep add block on. The page will be empty, but if you scroll down far enough, videos start to pop back up. Some will blink in and out of existence.

That's literally what the "glitch/bug" is. That is literally the problem. lol

**Comment by voxpop9** [comment]
> > Temporary solution that i found is to keep add block on. The page will be empty, but if you scroll down far enough, videos start to pop back up. Some will blink in and out of existence.
> 
> That's literally what the "glitch/bug" is. That is literally the problem. lol

My bad, didn't notice.

**Comment by GoobyBooby** [comment]
I found a solution, hopefully it works for you too. To solve it go to uYou in the bottom right corner -> Settings top right -> Scroll to "Youtube Settings" section -> Home -> Turn off Hide Shorts Cells. I had this enabled some time ago and by disabling it fixed it for me.
I have also disabled Remove YouTube Ads (banner ads on home tab) but I didn't see any, maybe another setting in uYouEnhanced are blocking them?

**Comment by roafhtun** [comment]
Doesn't work for me the fixed. The issue exists.

**Comment by ElminL** [comment]
> Doesn't work for me the fixed. The issue exists.

Yup. I did my own version of the ipa using the latest commits. And it still didn't work. It actually made it worse. I would have the issue no matter what setting I changed.

**Comment by ElijahKujo** [comment]
can confirm this is still not fixed

**Comment by a4562248** [comment]
[YouTubeAd.sgmodule.zip](https://github.com/user-attachments/files/16154970/YouTubeAd.sgmodule.zip)

I solved this problem. The first step: uYou -> Settings -> Other Settings -> Remove YouTube Ads -> Off; The second step: Load the YouTube ad-blocking module in shadowrocket. This can perfectly solve the blank problem. 

 I'm an iPhone 13mini, and the system is iOS15. Or you can look for modules applicable to other systems.  @qnblackcat @ElminL @ElijahKujo @roafhtun @mermiad

**Comment by ElminL** [comment]
> [YouTubeAd.sgmodule.zip](https://github.com/user-attachments/files/16154970/YouTubeAd.sgmodule.zip)
> 
> 
> 
> I solved this problem. The first step: uYou -> Settings -> Other Settings -> Remove YouTube Ads -> Off; The second step: Load the YouTube ad-blocking module in shadowrocket. This can perfectly solve the blank problem. 
> 
> 
> 
>  I'm an iPhone 13mini, and the system is iOS15. Or you can look for modules applicable to other systems.  @qnblackcat @ElminL @ElijahKujo @roafhtun @mermiad 

Does anyone know if this guy is legit? @ing us to download some random zip file?

**Comment by oliviaiacovou** [comment]
mine was fixed until yesterday

**Comment by PoomSmart** [comment]
Fixed in the latest commit.
