### ISSUE TITLE
crash when tapping thumbnail from homepage

### ISSUE THREAD

**Issue by benAcrowder** [qnblackcat/uYouPlus#1416]
anytime I try to watch a video the app crashes. I can navigate all around through the tabs and settings but trying to access a video and crash. I thought autoplay maybe a culprit and turned that off with no effect. I also navigated around the settings looking for anything that might seem like it could cause this 🤷‍♂️

Shorts work BTW. 

thanks for the awesome app. I'm on the latest dev beta for 17.5

**Comment by ElminL** [comment]
Just go to your A/B setting and turn it on. Then go back and open A/B and search for the word “Modular” it will be the only setting appearing. Then you have to turn it off and restart your app.

**Comment by Sayrix** [comment]
It don't works for me even when i disable the modular thing in A/B

**Comment by ElminL** [comment]
If that doesn't work then disable the iSponsorBlock. It's the shield icon at the top in the main recommendations page.

**Comment by benAcrowder** [comment]
this worked for me!🎉🎉🎉

thanks very much!

**Comment by Sayrix** [comment]
Hi, even with iSponsorBlock it don't works for me. 😔
Here is a record https://gofile.io/d/6tpNwd

**Comment by ElminL** [comment]
> Hi, even with iSponsorBlock disabled it don't works for me. 😔
> Here is a record https://gofile.io/d/6tpNwd

Disable your playback speed controls.
Go to settings, general, uYou, video player, playback speed controls.

If that doesn't work, you might need to find a new latest download of the ipa.

https://github.com/ComfortableMilk4454/uYouPlus/actions/runs/8303415987/artifacts/1331115671

This guy did all the work, just open download, and open the .zip. It will unpack the ipa, with that you just need to import to your phone and install it via whatever you're using.

**Comment by Sayrix** [comment]
Thanks it worked, i have disabled all uyou things because i pay youtube premium, what i wanted is just sponsorblock

**Comment by ElminL** [comment]
> Thanks it worked, i have disabled all uyou things because i pay youtube premium, what i wanted is just sponsorblock

SponsorBlock could still work. It works for me as long as i have modular turned off. I recommend trying to have sponsor block back on to see.

**Comment by Sayrix** [comment]
Yup with SponsorBlock it works and with every video player disabled
![image](https://github.com/qnblackcat/uYouPlus/assets/43046854/41ea14dd-bbdf-4f1d-af11-2f531371320e)

**Comment by Sayrix** [comment]
When i only disabled the playback speed it don't worked so i disabled everything and then it worked
