### ISSUE TITLE
Crashing, when Playback Speed Controls toggle is on

### ISSUE THREAD

**Issue by ALM0GI0** [qnblackcat/uYouPlus#1420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4
- Device model: iPad mini 6
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 

### Describe the issue

All videos crashing

### Steps to reproduce

1. Open a video.
2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information
Will only crash when playback speed controls is on under video player settings in the uyou section of the app

**Comment by sledgehammer617** [comment]
Same issue here, crashes when opening a video but not shorts.

Disabling Sponsorblock does not fix the issue this time.

**Comment by mtr1012** [comment]
Me same. Crash after few days since sideloaded

**Comment by Erahgon** [comment]
Same here! It just started this morning for me! It was working fine last night (about 8 hours ago). I hadn't updated or refreshed the app either, and refreshing the app didn't help.

**Comment by mtr1012** [comment]
> Same here! It just started this morning for me! It was working fine last night (about 8 hours ago). I hadn't updated or refreshed the app either, and refreshing the app didn't help.

It's so weird 😂. Working perfectly for a few days and become unusable for no reason 🥺

**Comment by Erahgon** [comment]
> It's so weird 😂. Working perfectly for a few days and become unusable for no reason 🥺

Yeah... Makes me think that it's something on the server end that's causing it.

I also noticed that it seems to start playing the video, whole trying to load the rest of the UI elements in the player screen (comments section, related videos and so on) and crashes without those elements loading. I lack the expertise to connect the dots, but hopefully this observation can help?

**Comment by ALM0GI0** [comment]
Hold up, let me try that

**Comment by ALM0GI0** [comment]
> I turned off everything in uyou player settings and it works fine now

Can confirm that this works, but let’s try to see exactly which feature it is that is causing it to crash

**Comment by Valernikkk** [comment]
> > I turned off everything in uyou player settings and it works fine now
> 
> Can confirm that this works, but let’s try to see exactly which feature it is that is causing it to crash

I checked now, that is speed control buttons

**Comment by ALM0GI0** [comment]
Amazing, this is the same by me

**Comment by sledgehammer617** [comment]
> > > I turned off everything in uyou player settings and it works fine now
> > 
> > 
> > Can confirm that this works, but let’s try to see exactly which feature it is that is causing it to crash
> 
> I checked now, that is speed control buttons

This worked for me, speed control buttons seem to be the culprit! Nice catch.

**Comment by j21w91** [comment]
I turned that all off but issue still persists for me. Can’t play anything except Shorts

**Comment by mtr1012** [comment]
> I turned that all off but issue still persists for me. Can’t play anything except Shorts

Restart the app and it will working

**Comment by PoomSmart** [comment]
Full crash log?

**Comment by PoomSmart** [comment]
```
If the app crashes, please provide the crash log. It can be found in Settings > Privacy > Analytics & Improvements > Analytics Data > Youtube-xxx-xxx.ips
```

**Comment by ALM0GI0** [comment]
I don’t see “Analytics & Improvements“ button in the privacy tab of the settings on YouTube on iPad.

**Comment by punchyouinthenuts** [comment]
This works on a uYouEnhanced version of YouTube 19.14.2. It does not work on a uYouPlus version of 19.15.1. On the latter version I have disabled all uYou settings, still crashes. Added disabling iSponsorBlock and disabling _ enableModularPlayerBarController_ asPoomSmart suggested, still continues to crash.

**Comment by ALM0GI0** [comment]
> [YouTube-2024-04-18-030128.txt](https://github.com/qnblackcat/uYouPlus/files/15032232/YouTube-2024-04-18-030128.txt)

Here @PoomSmart

**Comment by PoomSmart** [comment]
The crash log seems to point to Return YouTube Dislike tweak, but I couldn't make sense of it yet.

**Comment by j21w91** [comment]
> > I turned that all off but issue still persists for me. Can’t play anything except Shorts
> 
> Restart the app and it will working

Nope still not working. Basically everything turned off. Restarted the app (I mean.. it crashes anyways so it restarts itself naturally) and I have restarted my phone. Same behaviour - push on any video and the app closes
