### ISSUE TITLE
[Questions] notarising for altstore pal

### ISSUE THREAD

**Issue by melikootje** [qnblackcat/uYouPlus#1421]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

 No, I dont believe this is a bug. I will not open a new issue with the bug template

### My question

Can you try notorizing this by apple so i can download it using my altstore pal subscription ?

**Comment by melikootje** [comment]
Notarizing is different from app review btw, see https://www.macrumors.com/2024/01/25/alternative-app-store-notarization-process/

it only checks if it doesnt have any malware or executable code in terms of security, so i think it could just go well

**Comment by melikootje** [comment]
That is just an assumption tho.. someone can just try it, it wont make it suddenly unusable… so whats the problem with the devs trying to look if it even works or not?

**Comment by yodaluca23** [comment]
> That is just an assumption tho.. someone can just try it, it wont make it suddenly unusable… so whats the problem with the devs trying to look if it even works or not?

We don't want any more attention from YouTube, all the tweak apps already got one DMCA notice for distributing it unofficially YouTube will most certainly get even more upset with us if we try to distribute it semi officially...

**Comment by boterocamilo** [comment]
> > > That is just an assumption tho.. someone can just try it, it wont make it suddenly unusable… so whats the problem with the devs trying to look if it even works or not?
> > 
> > 
> > We don't want any more attention from YouTube, all the tweak apps already got one DMCA notice for distributing it unofficially YouTube will most certainly get even more upset with us if we try to distribute it semi officially...
> 
> I don’t get your point. This project already has repositories for distributing it, also in AltStore. The only difference would be, that the ipa would be notarized, while currently it’s not. If that is the only difference YouTube would have to go after apple. Right?

In the AltStore PAL version you cannot add sources containing not-notarized apps, unfortunately.
