### ISSUE TITLE
Ipad PIP button crash

### ISSUE THREAD

**Issue by Charlie102308** [qnblackcat/uYouPlus#1427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: Ipad 17.4.1
- Device model: Ipad pro gen 6
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Altstore

### Describe the issue

Video crash after clicking PIP button, normal pip (not by turning on the pip button option)
works

### Steps to reproduce

1. Use ipad and turn on pip button option
2. click on any video and click the pip button

### Crash log

```shell

https://file.io/s5FEdKdCcF97

```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

Only occurred on Ipad and not on Iphone
--Update:
Now it also occur on iphone too

**Comment by PoomSmart** [comment]
Fixed in the latest commit.
