### ISSUE TITLE
[Bug] App crashes when tapping on  channel of stream donator

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#143]
### Device info
- iOS/iPadOS version: dev beta
- Device model: N/A
- Sideloadly
- Version of uYouPlus: lts

### Describe the bug
When trying to go to a channel of a user who recently donated to a streamer the app crashes

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

See above

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
Couldn't find it

### Additional context:
N/A

**Comment by qnblackcat** [comment]
should be fixed in the next release
