### ISSUE TITLE
Hide buttons at the top of shorts?

### ISSUE THREAD

**Issue by Wrestor** [qnblackcat/uYouPlus#1436]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Is there maybe a setting (that I missed) or A/B flag I can enable to disable the "search, camera and more" buttons at the top of shorts?
<img src="https://github.com/qnblackcat/uYouPlus/assets/54822494/27174b21-a14f-4f97-a4fe-83307c3b85f7" width=30% height=30%>

### Additional context

**Disclaimer**: Im on an older build of uYouPlus, because it’s the latest one that asks to enable notifications, which makes it possible to [manipulate the bell mode](https://github.com/qnblackcat/uYouPlus/issues/978) (notifications[which I then get from the official YT version that I have installed]).

**Comment by qnblackcat** [comment]
Here is a quick solution. You could add this code to `uYouPlus.xm`, then rebuild the IPA

```
@interface YTReelHeaderView : UIView
@end
%hook YTReelHeaderView
- (void)didMoveToWindow {
    %orig;
    self.subviews[0].hidden = YES;
}
%end
```
