### ISSUE TITLE
[v19.08.2-3.0.3] Crash when watching a video

### ISSUE THREAD

**Issue by JackAuxLanternes** [qnblackcat/uYouPlus#1438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: iOS 17.4.1
- Device model: iPhone 15 Pro Max
- Sideload tool: AltStore

### Describe the issue

When I click on a video, the app crash instantly. Shorts work perfectly.
I didn’t change anything in the options.

### Steps to reproduce

1. Click on a video

### Crash log

```shell
https://pastebin.com/AZNuh31s
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by nqlp** [comment]
Same issue here. Shorts work, but video does not.

iPadOS version: 16.3.1
Device model: iPad (9th generation)
Sideload tool: TrollStore

**Comment by andywmoe** [comment]
Try disabling iSponsorBlock.

**Comment by Jordan21002** [comment]
> Try disabling iSponsorBlock.

Where do I find iSponsorblock to disable it? I'm having the same issue.

**Comment by JackAuxLanternes** [comment]
You can disable it here
![Home screen](https://github.com/qnblackcat/uYouPlus/assets/56066207/c7a6c9ab-5552-4b28-82c0-99f6daa71ffd)
![Sponsorblock menu](https://github.com/qnblackcat/uYouPlus/assets/56066207/ce7646fe-4177-4b63-8a0e-a40a304a935d)
