### ISSUE TITLE
Error Exit Code 8 when Building and Releasing

### ISSUE THREAD

**Issue by Jordan21002** [qnblackcat/uYouPlus#1441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version:  17.4.1
- Device model: iPhone 14
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 

### Describe the issue

<img width="415" alt="image" src="https://github.com/qnblackcat/uYouPlus/assets/168492948/c3e27812-c60e-4799-b68b-053c27f34038">

I'm getting this error when I try to build and release uYouPlus? I've tried multiple different decrypted Youtube files that I downloaded from https://27man-my.sharepoint.com/personal/qn____27man_onmicrosoft_com/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fqn%5F%5F%5F%5F27man%5Fonmicrosoft%5Fcom%2FDocuments%2FDecrypted%20IPAs%2FYouTube and uploaded to my own OneDrive, and then copied the shared link into GitHub.. Not sure what is wrong?

### Steps to reproduce

1. 
2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by EgyptianComrade** [comment]
https://github.com/qnblackcat/uYouPlus/discussions/1383
this will help

**Comment by fevev45857** [comment]
if you need i built the las ipa update, thats the link to download:
[uYouPlus_19.17.2_3.0.3](https://drive.google.com/file/d/1ceowM4Prf0-7GCpJBxQK5TfETsRyZzlK/view?usp=sharing).
