### ISSUE TITLE
[3.0.3] YouTube Picture in Picture is causing device to get very hot, add toggle to turn it off?

### ISSUE THREAD

**Issue by xSimone** [qnblackcat/uYouPlus#1442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version:  16.3
- Device model: 14 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.):  TrollStore

### Describe the issue

Picture in Picture is buggy according to my research and is causing excess device heat, getting very hot and chewing battery even when on charge.

### Steps to reproduce

Minimise YouTube on an iOS 16-16.3 device

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

I think this issue isn't with uYou but YouTube itself, so my post asks if it's possible to have a settings toggle to disable the Picture in Picture feature, or a button on the picture in picture window to turn it off .. or if possible, the tweak to somehow fix the issue itself.

https://www.youtube.com/watch?v=ESMzmx1dGwc

**Comment by xSimone** [comment]
> youPiP

Sorry, is this a different tweak entirely named 'YouPIP' and nothing to do with uYou?

**Comment by y4wnn** [comment]
oh sorry, im actually using uyou enhanced and not uyou plus, youpip is bundled with the former. Does it not come with uyou plus? In that case, what about the normal youtube's pip setting in general?

**Comment by xSimone** [comment]
OKAY that's very interesting. Let me check. From memory mine is just called 'uYou' in Sileo.

**Comment by xSimone** [comment]
![2024-05-07 23 30 11](https://github.com/qnblackcat/uYouPlus/assets/16178961/4197d2d9-a67f-4993-8667-08f4b52c0827)
![2024-05-07 23 30 06](https://github.com/qnblackcat/uYouPlus/assets/16178961/c80ae52e-54d7-40b0-a72b-7524eeac65f6)

**Comment by y4wnn** [comment]
i sideloaded uyou enhanced through altstore instead so unfortunately im not familiar with sileo, but just going off the author name this seems to be the original uyou by miro. uyou plus and enhanced are maintained by qnblackcat and arichorn respectively, with extra features compared to uyou (which seems to include youpip). 
this q&a is actually on the uyouplus repo:p

**Comment by xSimone** [comment]
Oh, whoops... shit.. thanks. I'll check out the other versions.

**Comment by xSimone** [comment]
Uggh I didn't even notice.. 

![image](https://github.com/qnblackcat/uYouPlus/assets/16178961/35c45aee-aa1a-46f2-b743-b58a6d4b7fdb)

**Comment by y4wnn** [comment]
it's okay man but is your problem persisting?

**Comment by xSimone** [comment]
> it's okay man but is your problem persisting?

So when listening to LoFi Girl which helps me sleep, my phone if left with PIP running will pretty much set it on fire. This issue is still persistant now.

I'll have to try out uYou+ / Enhanced.

Which do you think is the best?
