### ISSUE TITLE
[v19.12.3-3.0.3]%20Add%20your%20title%20here...

### ISSUE THREAD

**Issue by bballkj7** [qnblackcat/uYouPlus#1443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 
- Device model: 
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 

### Describe the issue

Videos crash, NOT shorts, only normal videos. Tried disabling sponsorblock, disabling modularplayerbar controller, and more, and it’s weird because it was working fine for 3-4 days then it stopped working (no updates)

### Steps to reproduce

1. It just crashes and wont play any (non-short) video.
2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by Iulian23** [comment]
I literally started having the issues you're describing just now. I was 5 commits behind with my fork and on YouTube-v19.15.1.

I literally just synced my fork and rebuilt the app using the YouTube-v19.17.2 decrypted ipa file and now it works just fine again.

Maybe try with a newer version of the decrypted youtube app and see if that works for you aswel.

**Comment by yesyesy0ar** [comment]
> I literally started having the issues you're describing just now. I was 7 commits behind with my fork and used the YouTube-v19.15.1 file.
> 
> I literally just synced my fork and rebuilt the app using the YouTube-v19.17.2 decrypted ipa file and now it works just fine again.
> 
> Maybe try with a newer version of the decrypted youtube app and see if that works for you aswell.

can you upload your result? :D does not work for me

**Comment by ComfortableMilk4454** [comment]
here you are @lulian23:
- [link to uYouPlus injected iPA](https://drive.google.com/drive/folders/126wPQzZbnYlgRsEp59awzK6qH_rFFSzs?usp=sharing)
- for reference, [here's the decrypted ipa i used](https://27man-my.sharepoint.com/personal/qn____27man_onmicrosoft_com/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fqn%5F%5F%5F%5F27man%5Fonmicrosoft%5Fcom%2FDocuments%2FDecrypted%20IPAs%2FYouTube%2FYouTube%5F19%2E16%2E3%5FQn%5F%2Eipa&parent=%2Fpersonal%2Fqn%5F%5F%5F%5F27man%5Fonmicrosoft%5Fcom%2FDocuments%2FDecrypted%20IPAs%2FYouTube) (straight from [qnblackcat's Decrypted-IPAs OneDrive folder](https://github.com/qnblackcat/Decrypted-IPAs))
- enjoy!

**Comment by ComfortableMilk4454** [comment]
@yesyesy0ar here you are:
- [link to uYouPlus injected iPA](https://drive.google.com/drive/folders/126wPQzZbnYlgRsEp59awzK6qH_rFFSzs?usp=sharing)
- for reference, [here's the decrypted ipa i used](https://27man-my.sharepoint.com/personal/qn____27man_onmicrosoft_com/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fqn%5F%5F%5F%5F27man%5Fonmicrosoft%5Fcom%2FDocuments%2FDecrypted%20IPAs%2FYouTube%2FYouTube%5F19%2E16%2E3%5FQn%5F%2Eipa&parent=%2Fpersonal%2Fqn%5F%5F%5F%5F27man%5Fonmicrosoft%5Fcom%2FDocuments%2FDecrypted%20IPAs%2FYouTube) (straight from [qnblackcat's Decrypted-IPAs OneDrive folder](https://github.com/qnblackcat/Decrypted-IPAs))
- enjoy!

**Comment by gmanc2** [comment]
I just rebuilt the app using the latest YouTube version, and I got the dreaded "We can't confirm this app is safe" message when I tried to sign back in. I'll try your version and see if it works, but I think Google is actively screwing us again. 

> @yesyesy0ar here you are:
> 
> * [link to uYouPlus injected iPA](https://drive.google.com/drive/folders/126wPQzZbnYlgRsEp59awzK6qH_rFFSzs?usp=sharing)
> * for reference, [here's the decrypted ipa i used](https://27man-my.sharepoint.com/personal/qn____27man_onmicrosoft_com/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fqn%5F%5F%5F%5F27man%5Fonmicrosoft%5Fcom%2FDocuments%2FDecrypted%20IPAs%2FYouTube%2FYouTube%5F19%2E16%2E3%5FQn%5F%2Eipa&parent=%2Fpersonal%2Fqn%5F%5F%5F%5F27man%5Fonmicrosoft%5Fcom%2FDocuments%2FDecrypted%20IPAs%2FYouTube) (straight from [qnblackcat's Decrypted-IPAs OneDrive folder](https://github.com/qnblackcat/Decrypted-IPAs))
> * enjoy!

**Comment by gmanc2** [comment]
Update: **BE AWARE** the most recent version of either [uYouPlus](https://github.com/qnblackcat/uYouPlus/commit/d4b2243788a699c96f8ee50bc44d9eb5e182f59e) on the latest commit or YouTube Version 19.17.2 breaks your ability to sign-in with the same error message we used to get _"you can't sign in to this app because google can't confirm that it's safe"_ use uYouPlus_19.16.3-3.0.3

**Comment by TheRealestNico** [comment]
After using the linked version of uYou+ it still instantly crashes when opening normal videos

**Comment by Iulian23** [comment]
> > I literally started having the issues you're describing just now. I was 7 commits behind with my fork and used the YouTube-v19.15.1 file.
> > I literally just synced my fork and rebuilt the app using the YouTube-v19.17.2 decrypted ipa file and now it works just fine again.
> > Maybe try with a newer version of the decrypted youtube app and see if that works for you aswell.
> 
> can you upload your result? :D does not work for me

Here's the decrypted ipa file i used: [https://www.dropbox.com/scl/fi/kz5mwud0l46xqumon655u/YouTube-v19.17.2.ipa?rlkey=4xb74eq0ewig8baxhnc0h522v&st=vso3avap&dl=0](url)

and here's the finished build: [https://www.dropbox.com/scl/fi/cqnhbek1x2ple3phofemc/uYouPlus_19.17.2-3.0.3.ipa?rlkey=j5hw0wm6uj7mx9cybgtvz50s5&st=fi5ht6wo&dl=0](url)

**Comment by Iulian23** [comment]
> Update: **BE AWARE** the most recent version of either [uYouPlus](https://github.com/qnblackcat/uYouPlus/commit/d4b2243788a699c96f8ee50bc44d9eb5e182f59e) on the latest commit or YouTube Version 19.17.2 breaks your ability to sign-in with the same error message we used to get _"you can't sign in to this app because google can't confirm that it's safe"_ use uYouPlus_19.16.3-3.0.3

Yhis only happens if you never ever used uyou before and you never signed in prior to installing the newest version. 

Mine crashes with an error message and when i launch it again it works. And i am already logged in. So the account gets saved somehow.

**Comment by bballkj7** [comment]
I used version spoofer in settings: uYouEnhanced (doesnt work with uYouPlus) and changed to 18.48.3. Works with sponsor block now. Thanks reddit!On Apr 30, 2024, at 8:57 PM, TheRealestNico ***@***.***> wrote:﻿
After using the linked version of uYou+ it still instantly crashes when opening normal videos

**Comment by tumo07** [comment]
i have opened this issue and dev fixed it
make sure you get your fork synced because they updated it
then compile the file again and it should work

**Comment by tumo07** [comment]
#1428
