### ISSUE TITLE
[v19.08.2-3.0.3] iSponsorBlock is not work

### ISSUE THREAD

**Issue by sahazu** [qnblackcat/uYouPlus#1445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4.1
- Device model: iPhone 15 pro
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): AltStore

### Describe the issue

when iSponsorBlock is enabled, YouTube crashes when opening any video

### Steps to reproduce

1. 
2. 

https://github.com/qnblackcat/uYouPlus/assets/82225736/eee47b27-ce85-41c6-97c0-fe89e18da8ff

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by y4wnn** [comment]
I think updating the app version fixes it (no issues with 19.16.3 - 3.0.3), otherwise try changing this setting to off in A/B 
![image](https://github.com/qnblackcat/uYouPlus/assets/168842664/ecf9ca5b-a7fa-4fb8-95d5-0294ceafa980)

**Comment by sahazu** [comment]
Thank you. It worked.
