### ISSUE TITLE
The "all section" videos disappear and are sometimes gone

### ISSUE THREAD

**Issue by MagicDude17** [qnblackcat/uYouPlus#1446]
If you change the discovery section from "all" to anything else it will go back to normal and the thumbnails and videos load. So it's an issue only in the "all" section.

**Comment by ColdNSs** [comment]
Same issue here. Scroll down and you can see videos again

**Comment by royeshao** [comment]
After I scroll down, and click the video, the APP will crash, and jump to homepage. 
Will you have the same issue? my version uYouPlus-19.08.2-3.0.3.ipa

**Comment by auddis** [comment]
Yeah, can’t say what’s causing it but I’m also experiencing this. Scroll down and they eventually appear, scroll up and they disappear again. 
Makes me wonder if it’s related to a certain element being blocked and YouTube doesn’t deliver until X number of pixels are scrolled through as it expects [element] to take up [X] pixels

**Comment by Ayzzzzzzzzzzz** [comment]
I checked it, its because of the block ads feature. I hope someone fixes this soon. it drives me crazy. No tweak works, not uyou or ytkiller. They all use the same way of blocking ads on the homescreen. In videos it works just fine

**Comment by royeshao** [comment]
I tried to use the old version "uYouPlus_19.02.1_3.0.1.ipa", and it works for me. I can use it normally so far, please try it. :D

**Comment by KerwinLW** [comment]
I had tried this and it works but you will have ad on home screen but all other functions is still working. 
[#1435 ](https://github.com/qnblackcat/uYouPlus/issues/1413#issuecomment-2065784577)

**Comment by voxpop9** [comment]
I have found a new solution: Turn iPad layout on.

**Comment by Nominel** [comment]
Please update, this is fixed in latest commits.

**Comment by voxpop9** [comment]
Still broken
version: 19.25.3-3.0.4

**Comment by Nominel** [comment]
Try using YouTube v19.22.3. Works for me

**Comment by voxpop9** [comment]
> Try using YouTube v19.22.3. Works for me

Still Broken. Tried 19.22.3-3.0.3 and 3.0.4

**Comment by Nominel** [comment]
Yup it’s returned somehow
