### ISSUE TITLE
[v3.0.3] Crashing on video click

### ISSUE THREAD

**Issue by darkpixlz** [qnblackcat/uYouPlus#1447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.5
- Device model: iPhone 12 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Sideloadify

### Describe the issue

I cannot click on any videos, the app crashes instantly. Unrelated to iSponsorBlock crashes, I shut it off and it is still happening.

### Steps to reproduce

1. Launch the app
2. Click on a video

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by Niko-ux** [comment]
@darkpixlz Go to uYou ➤ ⚙ (Settings) ➤ Video Player
and disable _Playback Speed Controls_.

**Comment by Jamerrone** [comment]
> @darkpixlz Go to uYou ➤ ⚙ (Settings) ➤ Video Player
> 
> and disable _Playback Speed Controls_. _ iSponsorBlock can remain enabled.

Does not work for me:
https://github.com/qnblackcat/uYouPlus/assets/16142485/c5ccf735-33c7-42c4-b169-17e32f9f8c2b

**Comment by Niko-ux** [comment]
@Jamerrone Turn the app off and on again.

**Comment by Jamerrone** [comment]
> @Jamerrone Turn the app off and on again. When the application crashes, it doesn't switch off at all – I point this out so that it doesn't serve as an excuse :)

I get that, I have tried it a couple of times without crashing the app, but it still didn't work for me :(

**Comment by NDTChan** [comment]
Try this: Go to uYou -> iSponsorBlock -> disable the _Enabled_ -> Click random on a video -> Crash -> Go to uYou again -> iSponsorBlock -> enable the _Enabled_ -> Try to click on video -> It works for me 🧑‍💼

**Comment by Jamerrone** [comment]
> Try this: Go to uYou -> iSponsorBlock 🛡️  -> disable the _Enabled_ -> Click randomly on any video -> Crash -> Go to uYou again -> iSponsorBlock 🛡️  -> enable the _Enabled_ -> Try to click on video -> It works for me 🧑‍💼 

This is the most weird solution for any bug I have ever found, but you know what? It works like a charm! Thank you.

**Comment by NDTChan** [comment]
> > Try this: Go to uYou -> iSponsorBlock 🛡️  -> disable the _Enabled_ -> Click randomly on any video -> Crash -> Go to uYou again -> iSponsorBlock 🛡️  -> enable the _Enabled_ -> Try to click on video -> It works for me 🧑‍💼 
> 
> This is the most weird solution for any bug I have ever found, but you know what? It works like a charm! Thank you.

You're welcome 😗

**Comment by xxxkowal** [comment]
just build the newest release :]
