### ISSUE TITLE
UYou ++ crashes when i click on video

### ISSUE THREAD

**Issue by im1cedOut** [qnblackcat/uYouPlus#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 
- Device model: 
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 

### Describe the issue

UYou ++ is a great app, it has all the features that i need. But for some reason every single time i click on a video, it crashes the app. And shorts work fine, but videos dont.

### Steps to reproduce

1. open UYou plus
2. click on video

### Crash log

```shell
i cannot find the crash log. There seems to be no crash log but the app keeps on crashing.
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

![IMG_5971](https://github.com/qnblackcat/uYouPlus/assets/168774831/8bf7e8e9-f1d0-4478-83c7-785659517399)

**Comment by eli-sauvage** [comment]
Hi, could you share how you solved the issue ? I have the exact same problem.

**Comment by im1cedOut** [comment]
You just go and disable Isponsor block :)
