### ISSUE TITLE
“Play next” and “PiP button”

### ISSUE THREAD

**Issue by david-elkind** [qnblackcat/uYouPlus#1450]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

This is more a feature request:

* To have YouTube Premium’s “play next”
* To have PiP disabled by default but when watching a video, have a button that starts a PiP session for that specific video.

thanks ahead!

### Additional context

Thanks for all the work, this is beyond amazing.

**Comment by level3tjg** [comment]
-  The queue functionality is server sided, that's why it's hidden by default
- YouPiP provides an option in its settings to add a button instead of automatically starting PiP

**Comment by david-elkind** [comment]
Hi,

I have "Use PiP button" and "Use video tab bar PiP Button" enabled but there doesn't seem to be a PiP button. Am I missing something? Sorry for the trouble. I could provide additional information if needed.

**Comment by david-elkind** [comment]
@level3tjg
