### ISSUE TITLE
[v19.08.2-3.0.3] App crashes the moment i click to watch a video (not a short)

### ISSUE THREAD

**Issue by Paburrito** [qnblackcat/uYouPlus#1452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version:  Both iOS and iPadOS are version **17.4.1**

- Device model: iPhone 13 Pro Max and iPad Pro 12.9 5th gen

- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Both devices were sideloaded through **AltStore**

### Describe the issue

The app crashes whenever i try to click on a video to watch, happens the moment i do a click on it, whether it's the iPhone or the iPad, the behavior is the same

### Steps to reproduce

1. Open uYouPlus
2. Navigate to a video you desire to watch and click on it
3. Right after the click, the app crashes

### Crash log

```shell
I've gotten the crash log of both my devices and compressed them into a zip file, uploaded with the Additional information section of this form, i hope this helps and works for what you need as well

Bit of additional information, i tried reproducing the issue with the official Youtube App as well, and I am able to watch videos no problem
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

[Crash Logs - YouTube-2024-05-07.zip](https://github.com/qnblackcat/uYouPlus/files/15242667/Crash.Logs.-.YouTube-2024-05-07.zip)

**Comment by ComfortableMilk4454** [comment]
try this ipa https://drive.google.com/drive/folders/126wPQzZbnYlgRsEp59awzK6qH_rFFSzs?usp=sharing

**Comment by Paburrito** [comment]
Tried it on the iPad, seems to be working alright on initial tests, will update as soon as i tested it on the iPhone as well

**Comment by Paburrito** [comment]
Yep! seems to be working flawlessly again, both on the iPad and the iPhone, thank you very much!

**Comment by ComfortableMilk4454** [comment]
anytime :)

**Comment by tridq68** [comment]
Can you resend me the version uYouPlus your link above expired
