### ISSUE TITLE
[v19.16.3-3.0.3] Thêm tiêu đề lỗi ở đây.…

### ISSUE THREAD

**Issue by Minhthuydoan** [qnblackcat/uYouPlus#1453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 
- Device model: 
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 

### Describe the issue

I can’t download video
![IMG_5106](https://github.com/qnblackcat/uYouPlus/assets/169242313/80a286bd-39ed-4ea6-b4cd-677920132fb2)

### Steps to reproduce

1. 
2. 

### Are you using the latest version of uYouPlus? If not, why?

❌ yes

### Does the issue happen with the official YouTube app from the App Store?

✅ Yes, I can reproduce this issue in the official YouTube app from the App Store

**Comment by rbouma** [comment]
Yeah for me same problem, it stays on "Downloading..." and it will not finish. For shorts and normal video's

**Comment by Minhthuydoan** [comment]
> Yeah for me same problem, it stays on "Downloading..." and it will not finish. For shorts and normal video's

Really I really disappointed about that. I use uyou because downloading is easy. It's sad that that hasn't been fixed
