### ISSUE TITLE
[v19.08.02-3.0.3] Watch Later scrolling glitch, videos don't apper

### ISSUE THREAD

**Issue by GoobyBooby** [qnblackcat/uYouPlus#1457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4.1
- Device model: iPhone 14 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): SideStore

### Describe the issue

It's the same behaviour as in thumbnails not loading in the Home page (that I fixed by disabling the "Remove Youtube Ads"), but now I get this in the Watch Later playlist. The "Remove Youtube Ads" setting is disabled. Videos start appearing when I scroll down but some of them are missing, the first ~5 videos from the playlist, with no alternative to open them.

### Steps to reproduce

1. Open Watch Later
2. This is how it looks
![IMG_5909](https://github.com/qnblackcat/uYouPlus/assets/22904252/fc9c1206-d9d0-467e-bae0-be81ce0220fe)
![IMG_5910](https://github.com/qnblackcat/uYouPlus/assets/22904252/92607d3c-d5e5-4d9a-96b2-ae971dbb54b3)

### Are you using the latest version of uYouPlus? If not, why?

❌ No, I'll explain with additional information below

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

Didn't felt the need to upgrade, don't know how to build the ipa myself.

**Comment by eliliam** [comment]
I am actually starting to get this same behavior in the main home feed as well, it's become increasingly more of an issue and persists across app restarts.

**Comment by eduedp** [comment]
I had this also. Removed youtube and installed 19.23.2 with 3.0.4. It reseted all my config, but now it’s working.
