### ISSUE TITLE
[v19.08.2-3.0.3] Add your title here...

### ISSUE THREAD

**Issue by FPCBallon** [qnblackcat/uYouPlus#1461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 
- Device model: 
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 

### Describe the issue

![IMG_1886](https://github.com/qnblackcat/uYouPlus/assets/139563465/3e89db42-19cb-45a8-8c0b-5ee917810883)
![IMG_1887](https://github.com/qnblackcat/uYouPlus/assets/139563465/f4b26733-3d11-443e-a8d7-7a34fb419e1c)

shorts section is on the home even if it is disabled to appear at home section

### Steps to reproduce

1. 
2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by Cjanzen-1** [comment]
https://github.com/qnblackcat/uYouPlus/issues/1506#issuecomment-2196260547
Temporary fix
