### ISSUE TITLE
[v19.08.2-3.0.3] App is crashing while Opening any Video Instantly

### ISSUE THREAD

**Issue by MoeFayed** [qnblackcat/uYouPlus#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: IOS 16.3.1
- Device model: Iphone 14 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): altstore

### Describe the issue

I've updated the app which was working  just fine and downoaded the latest version.

 Shorts are working fine but when I am trying to open a video, the app closes instantly..

one time I got a message asking to report the crash silently..

![DEB0B168-EDAA-4B51-880F-3CC552D83E19](https://github.com/qnblackcat/uYouPlus/assets/170043171/f87a2d0c-280c-45ce-beb7-e395bb8e0c8b)
![FA85B5A0-68E0-428B-BADB-C590BDA97B57](https://github.com/qnblackcat/uYouPlus/assets/170043171/e5ed3bb5-b108-4d59-b4af-4d6a3bbea170)

### Steps to reproduce

1. 
2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by MoeFayed** [comment]
https://github.com/qnblackcat/uYouPlus/assets/170043171/3d4aa6e0-1136-40da-b50a-4e4d0a50b70c

Video

**Comment by MoeFayed** [comment]
I searched the closed bugs and found it to be related to issue #1323 

I tried disable isponsorblock and videos worked fine

**Comment by Computahwiz-Github** [comment]
happens to me as well. uyouplus and uyouenhanced. either crashes instantly unless isponsorblock is disabled. unfortunate because i had a previous version working flawlessly most of this whole year. wanted to try to update so that i can actually log into my google account again (only option is to click yes in app) iphone xs max ios 15.1 dopamine

**Comment by qnblackcat** [comment]
Try this https://twitter.com/poomsmart/status/1773308512145203429?

**Comment by Computahwiz-Github** [comment]
unfortunately, it did not work. but looking forward to the next update. also thanks for all that you and poomsmart do!
