### ISSUE TITLE
Error: exit with Code 2 when running github actions build

### ISSUE THREAD

**Issue by xxxkowal** [qnblackcat/uYouPlus#1464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS 17.5
- Device model: iPhone 15 pro
- Sideload tool: Altstore

### Describe the issue

Im trying to build using github actions and I have a decrypted youtube IPA with a link that seems to be working but I keep getting the following error.
![image](https://github.com/qnblackcat/uYouPlus/assets/37215980/2a938ff5-4221-4fae-a476-37495520ebe6)

im trying build youtube 19.19.7

### Steps to reproduce

1. 
2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by dizzyfizzy101** [comment]
i have the same problem

**Comment by waterdragon78** [comment]
same here

**Comment by qnblackcat** [comment]
I'm currently on a short vacation. I'll take a look at this next week.

**Comment by xxxkowal** [comment]
still error2 
![image](https://github.com/qnblackcat/uYouPlus/assets/37215980/710f6e52-bdc0-418f-9110-27fc65a84ce9)

**Comment by xxxkowal** [comment]
still error2
![image](https://github.com/qnblackcat/uYouPlus/assets/37215980/19ffb54a-43b9-44eb-8ab8-97fec077c3b9)

**Comment by ComfortableMilk4454** [comment]
it was fixed, did you sync your fork with uYouPlus' before building and releasing uYouPlus?

**Comment by xxxkowal** [comment]
> it was fixed, did you sync your fork with uYouPlus' before building and releasing uYouPlus?

Ahhh sorry i forgot :<. Now everything works ^^

**Comment by pedralmeida22** [comment]
Forked today, got this error:


<img width="1294" alt="image" src="https://github.com/qnblackcat/uYouPlus/assets/40249872/5511012f-a973-46de-8a4e-2e1ae1a366c3">

**Comment by ComfortableMilk4454** [comment]
> Forked today, got this error:
> <img alt="image" width="1294" src="https://private-user-images.githubusercontent.com/40249872/334969481-5511012f-a973-46de-8a4e-2e1ae1a366c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMjM2MjMsIm5iZiI6MTcxNzAyMzMyMywicGF0aCI6Ii80MDI0OTg3Mi8zMzQ5Njk0ODEtNTUxMTAxMmYtYTk3My00NmRlLThhNGUtMmUxYWUxYTM2NmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDIyNTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NzBhMjZiZGExZDFiZjdiOTU4NzY2MjI5ODNkZDE5NjBjOWVhNTFhODA5NTViZTQ4YmM2NmEwNmEyZmVmN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZLakIoYle2OZ1HHD3CzLaEAswRC_O3I3Rz313FTGuyY">

if your fork is completely up to date with the latest of uYouPlus', idk what could be causing it. but for now until someone with more knowledge than me can help you here's the link to the latest uYouPlus injected to v19.19.5 of YT (which was released on may 12, 2024 [not the latest YT version but best i could do cuz i dont have a jailbroken device so i cant get the latest vanilla yt ipa])—https://drive.google.com/drive/folders/126wPQzZbnYlgRsEp59awzK6qH_rFFSzs?usp=sharing. hope this helps.
