### ISSUE TITLE
 Error The Actions

### ISSUE THREAD

**Issue by LilCiro** [qnblackcat/uYouPlus#1466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4
- Device model: İphone 13
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Altstore

### Describe the issue

actions always fails

### Steps to reproduce

![image](https://github.com/qnblackcat/uYouPlus/assets/94236924/61b29d49-5d76-4755-8a8e-a6b1e2e73680)

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by mnett0** [comment]
Same

**Comment by MeleMannen** [comment]
I have the same issue

**Comment by paoloponzano** [comment]
Same here

**Comment by andr3i1010** [comment]
same here

**Comment by kei-sidorov** [comment]
For the maintainers: `miro92.com` started redirecting to some browser-check page, so `curl` can't download file directly.

**Comment by MeleMannen** [comment]
That worked! Thanks!

**Comment by DenuxPlays** [comment]
Same issue
Would be great if this would get patched inside the repo

**Comment by andr3i1010** [comment]
> Same issue Would be great if this would get patched inside the repo

clone the repo, edit the Makefile, run the action and you should be fine

**Comment by LilCiro** [comment]
> uYouEnhanced'in bakımcısı burada, **Makefile** dosyasındaki aşağıdaki bölüm aşağıdaki çatalınızda verilmiştir.****
> 
> Satır 64
> 
> ```
> 		curl -s -L "https://www.dropbox.com/scl/fi/01vvu5lm8nkkicrznku9v/com.miro.uyou_$(UYOU_VERSION)_iphoneos-arm.deb?rlkey=efgz7po8kqqvha8doplk1s3ky&dl=1" -o $(UYOU_DEB); \
> ```

Thank you, I was on holiday and couldn't check it
