### ISSUE TITLE
Settings page redesign removes settings options for uYou+ and various other tweaks

### ISSUE THREAD

**Issue by pha1n0q** [qnblackcat/uYouPlus#1468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: iOs 15.7.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Trollstore

### Describe the issue

A redesign of the settings page removes the ability to view/change uYouPlus settings and other tweaks’ settings. The redesign could be caused by an A/B test, but I can’t even make sure as I can’t see the A/B settings.

![9938CFB9-0544-4FC9-974B-37FFF35B6147](https://github.com/qnblackcat/uYouPlus/assets/88598340/d199d113-b8d9-4c9a-9502-d023948a4703)
![EA93E59C-6EBF-44CD-9766-398973B896B1](https://github.com/qnblackcat/uYouPlus/assets/88598340/8aac6e28-2d0f-44f3-a602-e4415e4810fd)

### Steps to reproduce

1. Open the settings page

### Are you using the latest version of uYouPlus? If not, why?

❌ No, I'll explain with additional information below

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

I’m one commit behind — currently using https://github.com/qnblackcat/uYouPlus/commit/b0ab41ed0c183407be2914a15adeb87a095ea41a

**Comment by qnblackcat** [comment]
please rebuild the iPA and try again
