### ISSUE TITLE
[v19.08.2-3.0.3] The file "App.ipa" doesn't exist.

### ISSUE THREAD

**Issue by ISamAtlas** [qnblackcat/uYouPlus#1471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [ ] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 16.7.8
- Device model: IPhone 8 (Model Number: MQ722LL/A)
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 
AltStore

### Describe the issue

It says:
Operation failed
The file "App.ipa" doesn't exist.

And when I check the error log it's just empty.

I just installed AltStore for this so it could be faulty installation but yeah I don't know.

### Steps to reproduce

![IMG_4660](https://github.com/qnblackcat/uYouPlus/assets/104479629/e5be11d9-2780-46e7-8c89-df2b072062b5)
![IMG_4661](https://github.com/qnblackcat/uYouPlus/assets/104479629/f5267ec2-7c5d-4ce5-a232-1b8de28821ce)

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by papatenko** [comment]
Unfortunately, the IPA file has been **removed** due to [Google’s request](https://twitter.com/t70438299/status/1765541359803650334?). To install the app, build it using this guide: [Wiki-Building](https://github.com/qnblackcat/uYouPlus/wiki/Building).

**Comment by quarkquartet** [comment]
> Unfortunately, the IPA file has been **removed** due to [Google’s request](https://twitter.com/t70438299/status/1765541359803650334?). To install the app, build it using this guide: [Wiki-Building](https://github.com/qnblackcat/uYouPlus/wiki/Building).

Does it means we cannot use background refresh anymore? I found it refuses to refresh recently and I have to manually build the ipa every time.

**Comment by papatenko** [comment]
I'm not sure, I built an older version of the IPA before Google took it down, and refreshing has worked perfectly fine on my phone. 

I wish I could help but the only suggestion I can give would be to try [Trollstore](https://trollstore.org/), since I've heard that side loader doesn't require refreshing. I haven't tried it but it's worth a shot.

**Comment by quarkquartet** [comment]
> I'm not sure, I built an older version of the IPA before Google took it down, and refreshing has worked perfectly fine on my phone.
> 
> I wish I could help but the only suggestion I can give would be to try [Trollstore](https://trollstore.org/) since I've heard that side loader doesn't require refreshing. I haven't tried it but it's worth a shot.

Yes I just tried. Background refresh is still possible, just we cannot update it anymore without compiling the new version.
