### ISSUE TITLE
App Crashes Upon Opening Video

### ISSUE THREAD

**Issue by Dipstick8462** [qnblackcat/uYouPlus#1473]
I have downloaded the latest version of uYou Enhanced using AltStore, and upon opening any video at all, the app suddenly crashes and brings you back to the homescreen, there hasn't been any workaround that I was able to find.

**Comment by LameLionYT** [comment]
Turn off i SponsorBlock. That fixed the issue for me. https://github.com/qnblackcat/uYouPlus/issues/1323

**Comment by Dipstick8462** [comment]
I turned it off and now it works for me too! So because of this bug, is there just not a way to use SponsorBlock at all?
