### ISSUE TITLE
Crash app when openning

### ISSUE THREAD

**Issue by Dangvinh777** [qnblackcat/uYouPlus#1474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 14.0.8
- Device model: Iphone 11
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): TrollStore

### Describe the issue

After installing by URL method of Trollstore, I can't open Youtube app, It just crash immediately.I use newest decrypted IPA of Youtube and don't have any problem during building IPA file of uYou.

https://github.com/qnblackcat/uYouPlus/assets/100329768/0c194d59-2a91-4894-8935-838d43ab826b
 Here are my crash logs:
[YouTube-2024-05-31-104001.000.txt](https://github.com/user-attachments/files/15508061/YouTube-2024-05-31-104001.000.txt)
[YouTube-2024-05-31-104001.txt](https://github.com/user-attachments/files/15508063/YouTube-2024-05-31-104001.txt)

### Steps to reproduce

1. 
2. 

### Crash log

```shell
I attached crash log in Issue decription part.
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by Dangvinh777** [comment]
It's only work with decrypted IPA from version 19.20.2 and earlier

**Comment by Goodhew** [comment]
You can edit the Makefile to use uYou version 3.0.4. That will allow you to use YouTube v19.21.3

**Comment by KOX599** [comment]
> You can edit the Makefile to use uYou version 3.0.4. That will allow you to use newer versions of YouTube

how?

**Comment by PoomSmart** [comment]
Most likely uYou drops support for iOS 14

```
dependent dylib '/System/Library/Frameworks/AVFAudio.framework/AVFAudio' not found
```
