### ISSUE TITLE
[19.08.2-3.03] Controls freeze when entering full screen

### ISSUE THREAD

**Issue by P-Li0n** [qnblackcat/uYouPlus#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: iPadOS 17.5.1
- Device model: iPad Air 5th Gen
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): AltStore

### Describe the issue

When I am in full screen viewing and attempt to exit, via either the button on the bottom right or the swiping down gesture, all of the controls freeze and I am forced to quit the app entirely. The bug only happens when I am in landscape mode - in portrait mode, I'm able to exit the full screen player without issue.

Interestingly, the audio continues to play for ~15 seconds after I quit the app entirely. I cannot pause it or stop it, despite the app being entirely closed. I have tried tweaking many overlay settings and nothing seems to resolve the issue. It can also be seen that the top bar on the iPad returns (you can see the time, clock, wifi and battery status as if it's not in full screen even though it is. I have tried to attach a screen recording, however the file size is too large. 

### Steps to reproduce

1. Enter full screen video
2. Either select the exit full screen button on the bottom right, or swipe down to exit full screen viewing
3. All controls lock, playback cannot be paused, all buttons are non-responsive

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by AquaChocomint** [comment]
Same issue on iPadOS 15.4.1, with TrollStore installed.

**Comment by techtipsforteens** [comment]
Have the same issue on my 5th Gen iPad Air iPadOS 17.5.1 on AltStore.

**Comment by JTG-gaming** [comment]
Same issue, ipad mini 6th gen iPadOS 17.5.1, ipa version 19.22.6

**Comment by WhiskyLe** [comment]
Same issue, ipad 10th gen iPad OS 17.5.1, ipa version 19.22.6 loaded with sideloadly on a developer account

**Comment by rursache** [comment]
same issue. its fixed if i turn off "uYou", "uYou Repeat", "playback speed controls" and "uyou fullscreen to the right" in `uYou tab > gear icon > video player `

**Comment by frezzyQ** [comment]
> same issue. its fixed if i turn off "uYou", "uYou Repeat", "playback speed controls" and "uyou fullscreen to the right" in `uYou tab > gear icon > video player `

WORKING THANKS, YOU SAVED ME A LOT OF NERVES 🙏🏻

**Comment by Deissson** [comment]
I still have this issue on 19.21.2, iOS 18
