### ISSUE TITLE
PiP miniplayer disable stays after reopening the video

### ISSUE THREAD

**Issue by jeffzyliu** [qnblackcat/uYouPlus#148]
Steps:
1. Turn on "disable PiP in miniplayer" in settings
1. Open a video in miniplayer
1. Quit app (audio keeps playing without PiP video)
1. Re-enter app and swipe up to open the full video from the miniplayer, without tapping elsewhere
1. Quit app

PiP does not get re-enabled for me here. If I re-enter and re-exit the app, it works. If I pause and play the video again, it also works. But just maximizing the video again does not turn on PiP the first time.

**Comment by jeffzyliu** [comment]
Sorry, bump! @qnblackcat 

for info:
iPhone 10
iOS 15.4.1
AltStore
17.9.2

**Comment by qnblackcat** [comment]
@level3tjg is there anything you can do about this issue?

**Comment by jeffzyliu** [comment]
thank you for working on this!

**Comment by jeffzyliu** [comment]
So sorry to bother again!

The issue has been fixed but it seems another one has been introduced.

Same device
iOS 15.5
UYouPlus 17.25 (same release that fixed this)

To set this up, clear the app from the app switcher to start from a clean slate. First open and close any video. If you don't do this the bug doesn't happen; it only happens on the second video you watch, and a few other obscure cases I couldn't reliably reproduce.

Next, open a video from the home or subscriptions feed, and then immediately exit out the app to home screen. PiP does not start. If I interact with it (pause/unpause, maybe open description/comments) and then exit the app, PiP also does not start. However, if I fullscreen and unfullscreen, it works.

It also works as expected on the second time entering and exiting the app again, and it works just fine when I minimize to miniplayer and maximize again.

I know this is probably still being worked on already, but just recording my experience if it helps you test and reproduce any bugs.
