### ISSUE TITLE
Homepage UI does not load

### ISSUE THREAD

**Issue by jrwj97** [qnblackcat/uYouPlus#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.5.1
- Device model: 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): This issue occurs when sideloaded via Sideloadly and AltStore.

### Describe the issue

The home page UI does not load. If i scroll down on the home page, things start to load but incorrectly (Missing thumbnails, channel names, etc.). I have tried using version 3.0.2 and 3.0.3 and the issue still reoccurs.  

### Steps to reproduce

1. 
![IMG_3946](https://github.com/qnblackcat/uYouPlus/assets/94819530/b9e8eab4-597b-484d-8b44-965c31777a49)
![IMG_3947](https://github.com/qnblackcat/uYouPlus/assets/94819530/4eea2faa-e9c9-46d6-af0d-b33d8e2737a5)

No steps to reproduce. This occurs every time the app is opened. 

### Are you using the latest version of uYouPlus? If not, why?

❌ No, I'll explain with additional information below

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

I have attempted to install versions 3.0.3 and 3.0.2 and the issue remains.

**Comment by iqbal1992** [comment]
These are the ads I think which are getting replaced by empty blocks.

**Comment by RxSauce** [comment]
nah not just ads the shorts arent showing either this problem bug just started happening to me like a day or 2 ago aswell

**Comment by sabzeruz** [comment]
experince the same issue

**Comment by Chad90b** [comment]
same issue. also while scrolling the entire page will randomly turn completely black, removing all content

**Comment by TheKivster** [comment]
This is happening to me too. It didn’t used to happen.

**Comment by MrAbattoir** [comment]
This happens to me as well.
Work around is to go into uYou settings > Other Settings and deselect Remove YouTube Ads.
But this obviously removes one of the apps greatest mods.

**Comment by tamusandesh99** [comment]
This has happened to me too on ios 17. Now whenever I click on video, the app crashes. Any fix?

**Comment by Arturia169** [comment]
> 这也发生在我身上。解决方法是进入 uYou 设置>其他设置，然后取消选择移除 YouTube 广告。但这显然删除了应用程序最伟大的模组之一。

Thanks, this setup restores the main page, but the page appears to be full of ads!

**Comment by RxSauce** [comment]
> > 这也发生在我身上。解决方法是进入 uYou 设置>其他设置，然后取消选择移除 YouTube 广告。但这显然删除了应用程序最伟大的模组之一。
> 
> Thanks, this setup restores the main page, but the page appears to be full of ads!

also puts ads back on videos

**Comment by maxens-git** [comment]
same issue

**Comment by xxxkowal** [comment]
+1

**Comment by ollieeddo** [comment]
same issue

**Comment by david-elkind** [comment]
Same here

**Comment by adabugra** [comment]
same issue

**Comment by mjh657** [comment]
Same

**Comment by ComfortableMilk4454** [comment]
same. can devs please fix this? 
![blank_screen_bug](https://github.com/qnblackcat/uYouPlus/assets/43555540/3507bedd-27e4-43f2-98ef-dee67cdb0edd)

**Comment by evheniy-dan** [comment]
I have the same issue. Disabling ads kinda fixed it but... Is there a fix with adblocker on?

**Comment by GordonQuick** [comment]
A fix that works but isn't exactly the same is to just click on one "New to you" (or any other option). Those feeds work like normal, only the regular startpage is bugged.

**Comment by RxSauce** [comment]
a guaranteed fix is using uyou with ytkillerplus which costs like 2-3 bucks sadly but worth it.

**Comment by BendakSK** [comment]
Experiencing the same issue as well.

**Comment by hanjaja** [comment]
Temporary fix: Turning on iPad layout.

uYou settings > Other Settings > Turn on iPad Layout

**Comment by Fundamenta117** [comment]
+1

**Comment by MizukagamiTsuki** [comment]
Experiencing the same issue as well.
iPhone 13 mini 
iOS15.0  
YT19.19.5 
uYou3.0.3

**Comment by ComfortableMilk4454** [comment]
> same. can devs please fix this? ![blank_screen_bug](https://private-user-images.githubusercontent.com/43555540/338008176-3507bedd-27e4-43f2-98ef-dee67cdb0edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDI4MTMsIm5iZiI6MTcxODM0MjUxMywicGF0aCI6Ii80MzU1NTU0MC8zMzgwMDgxNzYtMzUwN2JlZGQtMjdlNC00M2YyLTk4ZWYtZGVlNjdjZGIwZWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA1MjE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NTI0YzA2YjM2M2Q1NzJiNTQzOTMzYTE5NGE2ZDk0MWY0NmY2MWUwMjYwMjBhMTViMGEzMDA2ODVlZjA3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gGbTQHZbWRysc87zA2LsQi8-JLs9-saWj2Dm_QA-whc)

@PoomSmart

**Comment by Kizovani** [comment]
Same issue, also in my case - the app crashes upon clicking on any video, after disabling "Remove YouTube Ads" home page is back (with ads) but videos still crash on click.

**Comment by DenuxPlays** [comment]
Is this being worked on?

**Comment by KoalaUnknown** [comment]
+1

**Comment by xChrisHTx** [comment]
Yeah also come across that bug, have a iPhone 13 Pro. iPhone 13 seems to the be only model where this is happening. On my dads iPhone XS everything still works

**Comment by DenuxPlays** [comment]
No I am using an iPhone 12 and I got the same issue.
(Switched to YouTubeRebornPlus while waiting for a fix)

**Comment by KoalaUnknown** [comment]
> Yeah also come across that bug, have a iPhone 13 Pro. iPhone 13 seems to the be only model where this is happening. On my dads iPhone XS everything still works

It happened on my 12 Pro.

**Comment by StoreCarCharIsInNoSave** [comment]
+1

**Comment by saccharinesky** [comment]
+1 se 2020

**Comment by iqbal1992** [comment]
Guys, Build the .ipa using YouTube version 19.22.3 and this issue will be resolved.

**Comment by KoalaUnknown** [comment]
[A 19.22.3 decrypted IPA](https://archive.org/details/com.google.ios.youtube-19.22.3-Decrypted)

**Comment by KoalaUnknown** [comment]
> Guys, Build the .ipa using YouTube version 19.22.3 and this issue will be resolved.

I am still experiencing this issue on YouTube version 19.22.3

**Comment by iqbal1992** [comment]
> > Guys, Build the .ipa using YouTube version 19.22.3 and this issue will be resolved.
> 
> 
> 
> I am still experiencing this issue on YouTube version 19.22.3

Here. Try this .ipa

https://filebin.net/nuzjte77kao6kuer

**Comment by KoalaUnknown** [comment]
> Here, try this .ipa

Im still experiencing the issue on that .ipa.

**Comment by ahmed1186** [comment]
> > > Guys, Build the .ipa using YouTube version 19.22.3 and this issue will be resolved.
> > 
> > 
> > I am still experiencing this issue on YouTube version 19.22.3
> 
> Here, try this .ipa
> 
> https://filebin.net/nuzjte77kao6kuer


> > > Guys, Build the .ipa using YouTube version 19.22.3 and this issue will be resolved.
> > 
> > 
> > I am still experiencing this issue on YouTube version 19.22.3
> 
> Here, try this .ipa
> 
> https://filebin.net/nuzjte77kao6kuer

Worked for me, Thank you 🙏

- iPadOS 18 
- iOS 17.5.1

**Comment by ShadowRoi** [comment]
> > > Guys, Build the .ipa using YouTube version 19.22.3 and this issue will be resolved.
> > 
> > 
> > I am still experiencing this issue on YouTube version 19.22.3
> 
> Here, try this .ipa
> 
> https://filebin.net/nuzjte77kao6kuer

Can confirm this fixed it. @jrwj97 You can now close this issue.

**Comment by DenuxPlays** [comment]
> > > > Guys, Build the .ipa using YouTube version 19.22.3 and this issue will be resolved.
> > > 
> > > 
> > > I am still experiencing this issue on YouTube version 19.22.3
> > 
> > 
> > Here, try this .ipa
> > https://filebin.net/nuzjte77kao6kuer
> 
> Can confirm this fixed it. @jrwj97 You can now close this issue.

Downgrading the yt-version is not "fixed"
It's just a workaround

**Comment by ShadowRoi** [comment]
> Downgrading the yt-version is not "fixed" It's just a workaround

Oh that's not the latest version?? Interesting, it seems then that I just had a really REALLY old version. Everything seems to work fine in that version for now at least.

**Comment by xChrisHTx** [comment]
> > Downgrading the yt-version is not "fixed" It's just a workaround
> 
> Oh that's not the latest version?? Interesting, it seems then that I just had a really REALLY old version. Everything seems to work fine in that version for now at least.

Yeah, same. This .ipa works fine for me. Thank you guys

**Comment by iqbal1992** [comment]
> > Downgrading the yt-version is not "fixed" It's just a workaround
> 
> 
> 
> Oh that's not the latest version?? Interesting, it seems then that I just had a really REALLY old version. Everything seems to work fine in that version for now at least. 

19.22.3 came out 3 weeks ago. So you are not at a very old version. Just 3 weeks behind and as soon as fix will come, you can make new one. 

Btw, I trued the build with new Youtube version. It had the same issue that is blank page but also some bottom bar icons missing, that's why I didn't recommend that here.

**Comment by ComfortableMilk4454** [comment]
@PoomSmart would u be able to provide the latest vanilla yt ipa that doesn't have this issue when uYouPlus is injected? for security reasons id like to build it myself and i don't have a jailbroken device

**Comment by Fundamenta117** [comment]
> > > > Guys, Build the .ipa using YouTube version 19.22.3 and this issue will be resolved.
> > > 
> > > 
> > > I am still experiencing this issue on YouTube version 19.22.3
> > 
> > 
> > Here, try this .ipa
> > https://filebin.net/nuzjte77kao6kuer
> 
> Can confirm this fixed it. @jrwj97 You can now close this issue.

it has worked only for the home page but not for subscriptions page 
15 pro max 
ios 17.5.1

**Comment by xxxkowal** [comment]
So works on newset yt version XD?

**Comment by Arturia169** [comment]
> > > Guys, Build the .ipa using YouTube version 19.22.3 and this issue will be resolved.伙计们，使用 YouTube 版本 19.22.3 构建 .ipa，此问题将得到解决。
> > 
> > 
> > I am still experiencing this issue on YouTube version 19.22.3我在 YouTube 版本 19.22.3 上仍然遇到此问题
> 
> Here, try this .ipa在这里，试试这个 .ipa
> 
> https://filebin.net/nuzjte77kao6kuer

It works fine for me with this version, but I can't adjust the playback rate of the video.

**Comment by hawwwwwk** [comment]
the filebin is no longer avaliable :(

**Comment by KoalaUnknown** [comment]
> the filebin is no longer avaliable :(

Build it with [this IPA](https://archive.org/details/com.google.ios.youtube-19.22.3-Decrypted) and change the version to 3.0.4.

**Comment by iqbal1992** [comment]
> the filebin is no longer avaliable :(

https://filebin.net/kubm14u7efqp709n
