### ISSUE TITLE
[Questions] There is nothing in Build and Release uYouPlus

### ISSUE THREAD

**Issue by SOMkill** [qnblackcat/uYouPlus#1484]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I don't have any "Run Workflows" in the "Action" tab. I've been coming here for a week now and have never seen anything appear. I have seen only one question on this topic and no answer
Can anyone help me? Ask questions if you need to, I will try to answer them all.
![11A60670-B17B-4A41-A79E-5624B8FBFE5D](https://github.com/qnblackcat/uYouPlus/assets/87482757/4bd762b3-a5c4-4eda-a749-edb0292b3290)

**Comment by pairofcrocs** [comment]
https://github.com/qnblackcat/uYouPlus/releases

**Comment by SOMkill** [comment]
@Cactism Thank you very much for your help! your answer really helped me!
