### ISSUE TITLE
Build process failed with exit code 2

### ISSUE THREAD

**Issue by Charlie102308** [qnblackcat/uYouPlus#1486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

Build process with the branch being up to date to the upstream

### Describe the issue

<img width="1098" alt="螢幕截圖 2024-06-08 11 02 53" src="https://github.com/qnblackcat/uYouPlus/assets/94617775/f62c193f-5034-4747-a8ea-ed36d1e7c29f">
https://file.io/2fgDeAV7s9yv
https://file.io/Yy9dPGH9soYP
the two link contains logs to my build process of uYouPlus

### Steps to reproduce

1. when using the action tab and build a new uYouPlus, it happens

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by The-Jani** [comment]
#1481
