### ISSUE TITLE
I cannot build the ipa because I get Username/Password Authentication Failed error.

### ISSUE THREAD

**Issue by b007zk** [qnblackcat/uYouPlus#1493]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

0s
Run wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
Username/Password Authentication Failed.
Error: Process completed with exit code 6.

**Comment by b007zk** [comment]
Hmm so i tried downloading a later decrypted IPA and that one built fine...

**Comment by b007zk** [comment]
Hmm so i tried downloading a later decrypted IPA and that one built fine...

**Comment by charleshu32** [comment]
How to solve this problem I have the same problem as you My YouTube ipa version is 19.23.3
