### ISSUE TITLE
Adblock is not working on shorts

### ISSUE THREAD

**Issue by adabugra** [qnblackcat/uYouPlus#1495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.5.1
- Device model: Iphone 15 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Sideloadly

### Describe the issue

The ads are not getting blocked while watching shorts videos.
![image](https://github.com/qnblackcat/uYouPlus/assets/57899270/328d8e3e-09ce-48f4-bc55-1891f60abcb3)

### Steps to reproduce

1. Scroll videos until you see an ad in shorts tab

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

✅ Yes, I can reproduce this issue in the official YouTube app from the App Store

**Comment by davidrittri** [comment]
Same

**Comment by transcoded-dot-net** [comment]
i imagine this may have something to do with Youtube planning on injecting their ads, compiled with how nothing comes up gui-wise.

**Comment by PoomSmart** [comment]
The latest version includes YouTube X which blocks shorts ads.

**Comment by MadWalnut** [comment]
@PoomSmart I just built a new IPA from source and updated via SideStore but still get ads. Does this require a fresh install?

**Comment by Wrestor** [comment]
I started getting ads on shorts today when using an older version of uYouPlus (18.07.5_2.3.1). Are ads in shorts fixed in the newest build of uYouPlus? @PoomSmart @MadWalnut

**Comment by MadWalnut** [comment]
@Wrestor I just installed `19.34.2-3.0.4`. Seems to be fixed for me.
