### ISSUE TITLE
[latest] Crashes on start up

### ISSUE THREAD

**Issue by DenuxPlays** [qnblackcat/uYouPlus#1499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.5.1
- Device model: iPhone 12
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Altstore

### Describe the issue

After YouTube-X was added the app crashes instantly.

### Steps to reproduce

1. execute the workflow
2. load the app via altstore

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by iqbal1992** [comment]
Same with me and I was about to post it too. using the latest build of youtube.

**Comment by xxxkowal** [comment]
Yea me too use latest version with YouTube X. Probably YouTube X crash ^^

**Comment by amrtheb** [comment]
same here latest youtube version too.

**Comment by juant87** [comment]
bump. synced fork and still crashing on start

**Comment by sogstillsleep** [comment]
Think I found a solution!

I was having the same issue with the latest version of YT (19.24.3), but I got it to work without crashing on startup by using decrypted version 19.22.23 of YouTube and changing the uYou version to 3.0.4 when building uYou+ through the workflow

You could probably get it to work with later versions by changing line 17 of the Makefile in your fork, but 19.22.23 works fine for me so I don't think it's worth going through the trouble to reinstall 🫡

i14p, iOS 17.5.1, used Sideloadly to sideload

**Comment by juant87** [comment]
> Think I found a solution!
> 
> I was having the same issue with the latest version of YT (19.24.3), but I got it to work without crashing on startup by using decrypted version 19.22.3 of YouTube and changing the uYou version to 3.0.4 when building uYou+ through the workflow
> 
> Y̶o̶u̶ c̶o̶u̶l̶d̶ p̶r̶o̶b̶a̶b̶l̶y̶ g̶e̶t̶ i̶t̶ t̶o̶ w̶o̶r̶k̶ w̶i̶t̶h̶ l̶a̶t̶e̶r̶ v̶e̶r̶s̶i̶o̶n̶s̶ b̶y̶ c̶h̶a̶n̶g̶i̶n̶g̶ l̶i̶n̶e̶ 1̶7̶ o̶f̶ t̶h̶e̶ M̶a̶k̶e̶f̶i̶l̶e̶ i̶n̶ y̶o̶u̶r̶ f̶o̶r̶k̶, b̶u̶t̶ 1̶9̶.2̶2̶.3̶ w̶o̶r̶k̶s̶ f̶i̶n̶e̶ f̶o̶r̶ m̶e̶ s̶o̶ I̶ d̶o̶n̶'t̶ t̶h̶i̶n̶k̶ i̶t̶'s̶ w̶o̶r̶t̶h̶ g̶o̶i̶n̶g̶ t̶h̶r̶o̶u̶g̶h̶ t̶h̶e̶ t̶r̶o̶u̶b̶l̶e̶ t̶o̶ r̶e̶i̶n̶s̶t̶a̶l̶l̶ 🫡
> 
> tried changing the YouTube version in the Makefile, still crashes with anything over 19.22.3; i guess decrypted ver. 19.22.3 is required. still works great though, so there was probably no real difference anyway 👍
> 
> i14p, iOS 17.5.1, used Sideloadly to sideload

do you have 19.22.3? I can't find it anywhere. most places have .24.2 or 24.3

**Comment by sogstillsleep** [comment]
yeah i do, this link should still work: https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.24.3?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwMDgyNjUwLCJpYXQiOjE3MTg5MjA3MjIsImV4cCI6MTcxODkzMTUyMiwiYXBwaWQiOjU0NDAwNzY2NCwiYXBwdmVyIjoiMTkuMjQuMyJ9.En7U5hDeDQFL777nLE6P7ld3G_cKCIsMVWNYSosgl48

if it doesn't though, go to https://armconverter.com/decryptedappstore/us and sign in with your iOSGods account (or make one if you don't have one)

**Comment by juant87** [comment]
> yeah i do, this link should still work: https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.22.3?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwMDgyNjUwLCJpYXQiOjE3MTg5MTkzNDYsImV4cCI6MTcxODkzMDE0NiwiYXBwaWQiOjU0NDAwNzY2NCwiYXBwdmVyIjoiMTkuMjIuMyJ9.sBB4ZieCaB_r8ROlm1MVXfoeK8JBS8yfk2X9JB1-x_Q
> 
> if it doesn't though, go to https://armconverter.com/decryptedappstore/us and sign in with your iOSGods account (or make one if you don't have one), go to the YouTube icon, and there should be a small history icon either next to or under "Download Decrypted"

WORKED!!!

**Comment by iqbal1992** [comment]
19.22.3 worked like charm and also those black dead spaces are gone now!!! 🎉

**Comment by xxxkowal** [comment]
> > yeah i do, this link should still work: https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.22.3?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwMDgyNjUwLCJpYXQiOjE3MTg5MTkzNDYsImV4cCI6MTcxODkzMDE0NiwiYXBwaWQiOjU0NDAwNzY2NCwiYXBwdmVyIjoiMTkuMjIuMyJ9.sBB4ZieCaB_r8ROlm1MVXfoeK8JBS8yfk2X9JB1-x_Q
> > if it doesn't though, go to https://armconverter.com/decryptedappstore/us and sign in with your iOSGods account (or make one if you don't have one), go to the YouTube icon, and there should be a small history icon either next to or under "Download Decrypted"
> 
> WORKED!!!

doesnt work, can u upload decypted youtube 19.22.3 to gdrive or dropbox or whateva but working link :D, thanks

**Comment by iqbal1992** [comment]
> > > yeah i do, this link should still work: https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.22.3?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwMDgyNjUwLCJpYXQiOjE3MTg5MTkzNDYsImV4cCI6MTcxODkzMDE0NiwiYXBwaWQiOjU0NDAwNzY2NCwiYXBwdmVyIjoiMTkuMjIuMyJ9.sBB4ZieCaB_r8ROlm1MVXfoeK8JBS8yfk2X9JB1-x_Q
> 
> > > if it doesn't though, go to https://armconverter.com/decryptedappstore/us and sign in with your iOSGods account (or make one if you don't have one), go to the YouTube icon, and there should be a small history icon either next to or under "Download Decrypted"
> 
> > 
> 
> > WORKED!!!
> 
> 
> 
> doesnt work, can u upload decypted youtube 19.22.3 to gdrive or dropbox or whateva but working link :D, thanks

https://filebin.net/mho9v51t40x9zpgy

Here you go.
