### ISSUE TITLE
[Bug] App crashes at notifications

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#15]
**Device info**
- iOS/iPadOS version: 15.2
- Device model: 12
- Sideload tool (Ex: AltStore, Sideloadly...): Sideloadly

**Describe the bug**
- whenever you try to configure the notifications from a channel the app crashes

**How to Reproduce the bug**
_(Please attach videos or screenshots if possible)_

https://user-images.githubusercontent.com/40891294/144919989-5813c672-a623-4b96-95d8-e6ac4cedefb9.MOV

**Additional context**

**Comment by qnblackcat** [comment]
It seems like this issue also happens on the jailbreak version of uYou. I opened a new issue on uYou’s repo here: https://github.com/MiRO92/uYou-for-YouTube/issues/94

Anyway, sideloaded apps are not able to receive push notifications (_most of the time_). If you managed to make it work, you can avoid this error by configuring the notifications under any video
![A79A184C-D9EB-4FA5-9BC3-84510067E5F3](https://user-images.githubusercontent.com/52943116/145698411-a7eadf47-49d1-4085-a33b-e91a0be335c4.png)

**Comment by ErSpieltHD** [comment]
Huh? Notifications always worked for me even on other sideoaded apps.

Yes, you are right. Changing it at the channel makes it crash. Below the video it works.

**Comment by qnblackcat** [comment]
I assume you're using appdb pro or SignTools since they support push notifications. If you use a free developer account or other signing services, push notifications will not work.
