### ISSUE TITLE
[Questions] When will uYouPlus get an update

### ISSUE THREAD

**Issue by DBeitniz** [qnblackcat/uYouPlus#1500]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

So there’s a new version of uYou (I think it was 3.0.4), are you planning to update the app? And maybe fix some of well known issues with ad blocking, like them not working or the home screen bugged out because ads are replaced.

**Comment by iqbal1992** [comment]
Well uyouplus is already using uyou 3.0.4 and as for blank home page, build the .ipa using YouTube version 19.22.3 and blank page issue will be resolved. And adblocking never been the issue for me personally, because not a single time I have seen any ads on this app.
