### ISSUE TITLE
[Questions] How to get a youtube decrypted ipa

### ISSUE THREAD

**Issue by jedai47** [qnblackcat/uYouPlus#1502]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

As per build instructions

**Comment by iulo** [comment]
https://github.com/qnblackcat/uYouPlus/discussions/559

**Comment by defrt** [comment]
https://armconverter.com/decryptedappstore/us/youtube

**Comment by LCY000** [comment]
Is the Youtube on armconverter uYouPlus?
