### ISSUE TITLE
Home page not loading videos properly 

### ISSUE THREAD

**Issue by allorionmusic** [qnblackcat/uYouPlus#1506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: iOS 17.5.1
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): signulous 

### Describe the issue

There is a lot of issues talking about it but nothing works, already turned off the ad block for homepage, already tried using another version, nothing works.
![IMG_0021](https://github.com/qnblackcat/uYouPlus/assets/83040651/ca03b2bf-f846-4bc4-b368-9d79cbdf0139)
![IMG_0022](https://github.com/qnblackcat/uYouPlus/assets/83040651/c8f85f2a-231f-4e6b-bdde-cc30544219a8)

### Steps to reproduce

1. go to your home page
2. scroll down, it may appear some videos but it will be glitchy

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by Cjanzen-1** [comment]
You can get around the glitch by disabling ad blocking on the home page.
Go to settings > General > uYou > Other Settings and disable remove YouTube ads. 
This **will not** disable ad blocking in videos just for the home page. However I have had a glitch where I rarely get an ad at the start of a video which is for a different thread

**Comment by mystarkfuture** [comment]
> You can get around the glitch by disabling ad blocking on the home page. Go to settings > General > uYou > Other Settings and disable remove YouTube ads. This **will not** disable ad blocking in videos just for the home page. However I have had a glitch where I rarely get an ad at the start of a video which is for a different thread

If i disable adblocking as described above, ads are showing up at the start and middle of all videos. So, this is not a viable workaround.

**Comment by Nominel** [comment]
Disabling it does not fix the issue at all for me

**Comment by allorionmusic** [comment]
> You can get around the glitch by disabling ad blocking on the home page.
> 
> Go to settings > General > uYou > Other Settings and disable remove YouTube ads. 
> 
> This **will not** disable ad blocking in videos just for the home page. However I have had a glitch where I rarely get an ad at the start of a video which is for a different thread

This doesn't work for me, already tried as I said above

**Comment by samophlange** [comment]
Turning off Hide Shorts Cells (settings, YouTube settings, home) fixes this for me.

I had the same issue with YTLitePlus, so maybe something changed on YouTube’s end with the Shorts Cells. Idk

**Comment by Nominel** [comment]
It is off for me and I still have the issue

**Comment by allorionmusic** [comment]
> Turning off Hide Shorts Cells (settings, YouTube settings, home) fixes this for me.
> 
> 
> 
> I had the same issue with YTLitePlus, so maybe something changed on YouTube’s end with the Shorts Cells. Idk

Already tried too! I think the dev should look into it

**Comment by kinggamma123** [comment]
Rebuilding the IPA with the latest changes seems to have fixed it for me :)

**Comment by SubjectGinger** [comment]
+1 this issue still persists, even on the latest commits as of July 4.

**Comment by Nominel** [comment]
Seems to be fixed on latest commits with new YouTube version. UI is bugged though

**Comment by allorionmusic** [comment]
It's fixed in newer uYouPlus versions! Thanks for the help
