### ISSUE TITLE
[Bug] No auto PiP

### ISSUE THREAD

**Issue by Casio7380** [qnblackcat/uYouPlus#151]
Device info
- iOS/iPadOS version:  iOS 15.4.1
- Device model: IPhone X  
- Sideload tool : AltStore
- Version of uYouPlus: _17.18.4_2.1

PiP is not working  automatically when I exit uYou+. 

https://user-images.githubusercontent.com/101881483/167714500-1fe6ebca-0f8f-4b7c-a1ca-6fa30c3f90b4.MOV

If it’s not a bug, please put it back please.

**Comment by qnblackcat** [comment]
Make sure
1. Picture in Picture is enabled in YouTube setting > General
2. Picture in Picture is enabled in iOS setting > General > Picture in Picture
3. **Use PiP button** and ** Use Video Tab Bar PiP Button** is disabled in YouTube settings > YouPiP

**Comment by qnblackcat** [comment]
Closed due to inactive
