### ISSUE TITLE
v19.26.5-3.0.4 Buttons not visible

### ISSUE THREAD

**Issue by AgentEinstein** [qnblackcat/uYouPlus#1517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.5.1
- Device model: iPad Pro (11-inch) 3rd generation
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.):  Altstore

### Describe the issue

Most buttons don't appear, including the ones on the task bar at the bottom, the sides in youtube shorts, and at the bottom of youtube videos. The subscribe button only appears if you're not already subscribed to the channel.
![image](https://github.com/qnblackcat/uYouPlus/assets/93837219/140c0870-0462-4566-822d-c28ac8035ec8)
![image](https://github.com/qnblackcat/uYouPlus/assets/93837219/940972cf-fcd5-4bbe-bf93-960c1e514836)
![image](https://github.com/qnblackcat/uYouPlus/assets/93837219/4c0005cd-bd4b-47a8-9c2f-fd393f64b509)
![image](https://github.com/qnblackcat/uYouPlus/assets/93837219/d2dc4603-c1f8-434f-a210-a91917fb6529)

### Steps to reproduce

1. Install uyou+ with altstore
2. Open the app
3. Issue is visible upon opening, and clicking on any youtube video or short

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by xxxkowal** [comment]
https://github.com/qnblackcat/uYouPlus/issues/1508
