### ISSUE TITLE
[Questions] qnblackcat, can you add the latest decrypted YT ipa to your onedrive?

### ISSUE THREAD

**Issue by ComfortableMilk4454** [qnblackcat/uYouPlus#1519]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

latest YT decrypted ipa i see on [qnblackcat's onedrive](https://27man-my.sharepoint.com/:f:/g/personal/qn____27man_onmicrosoft_com/EkS28ZkQ0URNiqRj873R5QgB4JAWymdhp8KdZ5r-EqLoGA?e=6fwTd8) is v19.19.5, but i need the latest one (19.26.5 as of writing) to fix the [blank homepage issue](https://github.com/qnblackcat/uYouPlus/issues/1483) that i'm currently experiencing with v19.19.5. @qnblackcat would you be able to upload a v19.26.5 YT decrypted iPA? thanks so much and i love uYouPlus btw, amazing app! i would do it myself but i don't want to jailbreak because i have applecare and afaik jailbreaking voids the applecare. thanks so much again :)

**Comment by defrt** [comment]
https://armconverter.com/decryptedappstore/us/youtube

**Comment by ComfortableMilk4454** [comment]
You sure this is safe? It wants me to make an account

**Comment by ComfortableMilk4454** [comment]
@TheNightRider12 oki ty! which one would you recommend out of the two?

**Comment by ComfortableMilk4454** [comment]
gotcha, thanks so much!

**Comment by LCY000** [comment]
> @ComfortableMilk4454 I would go with armconverter. But back when I did this a lot more (4 or 5 years ago), iPhonecake was my go to for various IPAs. But I would go with armconverter. Just make an account on iOS Gods, then sign into that account on armconverter. You can download 3 apps a day with the free limit. If you hit that limit, then you can always go to iPhonecake as a backup.

Is the Youtube on armconverter uYouPlus?

**Comment by ComfortableMilk4454** [comment]
@LCY000 no its just the vanilla yt ipa, but you can use it to get a uYouPlus iPA. if you need help with that pls reach out to me on discord @`comfortablemilk4454`
