### ISSUE TITLE
[Bug] Oled Keyboard Black Box?

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#152]
### Device info
- iOS/iPadOS version: 15.4.1
- Device model: iPad Pro 2 (10.5 Inch)
- Sideload tool: Altstore
- Version of uYouPlus: 17.18.4-2.1

### Describe the bug
I have no clue how this happened but I think it had something to do when enabling the oled keyboard on a tablet instead of an iPhone.

### How to reproduce the bug
I can’t somehow discuss how it happened so here’s an image of how it looks.
![F7A8288D-8D8E-48E7-86FF-CE54BE83A488](https://user-images.githubusercontent.com/78001398/167950804-2240e607-dfc0-4db5-baf4-615fef7261ae.jpeg)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:
Notice: I wish issues on iPads were fixed but you don’t have one yet so any oled bug I see on the iPad(s) then I will pretty much guarantee it will fail :(

**Comment by qnblackcat** [comment]
Disable the OLED keyboard then. It likely like won’t be fixed since I don’t own an iPad
