### ISSUE TITLE
[Questions] how long between the building of each uyou+ should i rebuild it

### ISSUE THREAD

**Issue by krispyking24** [qnblackcat/uYouPlus#1521]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

this is a question not a bug. (clarifying the title) as in if i build it today how many days or weeks should i check back and rebuild it to have the new changes.

**Comment by Nominel** [comment]
Depends on the commits, personally unless I have an issue I just leave it alone
