### ISSUE TITLE
Can’t enable notifications

### ISSUE THREAD

**Issue by SuperFico2100** [qnblackcat/uYouPlus#1525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: iOS 17.4
- Device model: iPhone 12 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): AltStore

### Describe the issue

I can’t enable uYouPlus notifications, trying to do so in YouTube settings just sends you to the settings app.
![IMG_2036](https://github.com/qnblackcat/uYouPlus/assets/74871659/58555a48-45f5-4c91-9803-e58f44bc1d84)
![IMG_2035](https://github.com/qnblackcat/uYouPlus/assets/74871659/2f3f7117-dd10-40c4-ac64-852c65d32e9c)

### Steps to reproduce

1. Go to YouTube settings, Notifications
2. Look

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by castdrian** [comment]
you cannot use notifications when you signed your app without the notification entitlement, as you evidently did by using altserver to sign, not a bug, just you not researching
