### ISSUE TITLE
uYouPlus_19.08.2-3.0.3 | App crashing after exiting full screen video

### ISSUE THREAD

**Issue by piyushrs** [qnblackcat/uYouPlus#1527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: iPadOS 17.5.1
- Device model: iPad Pro 11 3rd Gen
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): AltStore

### Describe the issue

Whenever I play a video in full screen and then want to exit full screen mode, the app stops responding. Note: Video keeps playing, but everything else freezes and I have to restart the app for it to work again. 

### Steps to reproduce

1. Open app
2. Play any video
3. Go full screen
4. Exit full screen

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by Reverrb** [comment]
Same situation as you. The only one that works for me is 19.02.1-3.03 and everything before it.

**Comment by Finalet** [comment]
Same problem here, makes the iPad app unusuable.

**Comment by piyushrs** [comment]
Found a work around for this issue, before exiting full screen, go portrait mode and then exit. Somehow that doesn’t crash the app :/

**Comment by PoomSmart** [comment]
Older YT IPAs will be marked as `won't fix`. Consider building the IPA from the latest YT version.
