### ISSUE TITLE
[Bug] With iPad Layout there is no Shorts tab.

### ISSUE THREAD

**Issue by Shy1nx** [qnblackcat/uYouPlus#153]
### Device info
- iOS/iPadOS version: iOS 15.4.1
- Device model: iPhone 7 Plus
- Sideload tool (Ex: AltStore, Sideloadly...) Sideloadly
- Version of uYouPlus: 17.18.4-2.1

### Describe the bug
I like the iPad layout with big phones. But I like to watch Shorts videos too. So when I enable the iPad layout the Shorts tab disappears. Maybe it’s the way of retail iPad app for YouTube, I’m not sure. But can you bring shorts tab to iPad layout?

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
It’s always like I described in my phone.

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by Shy1nx** [comment]
When I set the Startup page as Shorts,
Blank page and Loading Error info appears.

**Comment by qnblackcat** [comment]
I can’t do that. Sorry

**Comment by Shy1nx** [comment]
No problem bro.
Hide Create Clip, Create Shorts and Download buttons are not working on my phone. I mean the below video buttons. Is it fixable?

**Comment by arichorn** [comment]
The reason why shorts isn’t in iPad mode is because the iPad version of YouTube has no Shorts and isn’t accessible.
