### ISSUE TITLE
Why cant i fork the repository?

### ISSUE THREAD

**Issue by YarielBaerga** [qnblackcat/uYouPlus#1530]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Im trying to build it and i got everything, but there is no fork button for me, can someone help me?
![Screenshot 2024-07-19 154909](https://github.com/user-attachments/assets/f2f2087c-09c4-43f6-a7ba-a6bd4e776eb1)

**Comment by rursache** [comment]
the fork button is on the main repo page, not in wiki. learn to use github first
