### ISSUE TITLE
Ads appear in search results 

### ISSUE THREAD

**Issue by defrt** [qnblackcat/uYouPlus#1535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 
- Device model: 
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 

### Describe the issue

when you search on YouTube, there is a lot of ads appear in search results

### Steps to reproduce

1. Search 
![Uploading IMG_4621.png…]()

2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by garbofrogman** [comment]
Same here. I noticed that “Remove YouTube ads” is not enabled in uYou settings but I can’t seem to enable it, so it could be an uYou bug. 
When enabling the setting, ads still show. After restarting the app (required for changes to take effect), the toggle is back to disabled state.
