### ISSUE TITLE
YouTube randomly asks to rate itself but the option to send is grayed out.

### ISSUE THREAD

**Issue by AdiA105** [qnblackcat/uYouPlus#154]
This happens randomly throughout the day. Im not sure what's causing this but when I click cancel it will still ask me a couple of hours later...![image](https://user-images.githubusercontent.com/104014894/168023035-852428c5-0587-4f65-82e7-1d3086493950.png)

**Comment by qnblackcat** [comment]
I believe uYouPlus has nothing to do with this issue. How pathetic is YouTube begging for help...
