### ISSUE TITLE
[19.29.1-3.0.4] Certain videos immediately crash on load, others don't

### ISSUE THREAD

**Issue by HaaniMirza** [qnblackcat/uYouPlus#1541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: iOS 18 beta 4
- Device model: iPhone 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Signulous

### Describe the issue

Some videos are crashing on load, I have yet to find a common thread between the affected videos. This was the first video I experienced the issue with:

https://github.com/user-attachments/assets/86447615-b60d-465f-8691-8eab9b922b5b

It's definitely not the fact that the video is 8 years old, this video from yesterday from Modern Vintage Gamer also crashes on load:

https://github.com/user-attachments/assets/0fcc45fc-991c-451e-a568-a6d4c3897763

Most videos work just fine, but if I find a video that crashes, I really don't have another option but to just watch it on another device (or the YouTube website but let's be real that isn't a real option):

https://github.com/user-attachments/assets/b2a33756-f978-4b6a-b81d-71694e7d4f54

### Steps to reproduce

1. Open a video affected by this crash, for example https://youtu.be/B53zaGZE3QU?si=-AOf2TaJb-h2kBdr or https://youtu.be/KZvSEdFGyxE?si=SO1HaGpViHwKaDUS
2. Observe crashing

### Crash log

```shell
I don't appear to have a crash log in the listed location. The 'Privacy' option in settings has only 'Ad Settings', 'Blocked Contacts', and 'YouTube Terms of Service'.
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by PoomSmart** [comment]
Should be fixed with the latest commit.

**Comment by HaaniMirza** [comment]
> Should be fixed with the latest commit.

Thank you!
