### ISSUE TITLE
Succressfully built IPA not shown under releases

### ISSUE THREAD

**Issue by Osmodia666** [qnblackcat/uYouPlus#1545]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

I successfully built the uYouPlus IPA, but I dont have a tab called Releases in my Repo. 
Is this a bug or am I missing something?
![Screenshot 2024-08-10 215717](https://github.com/user-attachments/assets/982a82e2-03cc-4bc2-a355-cf01d1d8741a)
![y](https://github.com/user-attachments/assets/3613b9db-c7e3-43cd-866d-2ab92878acd3)

**Comment by BorrowedName** [comment]
It's saved as a draft unless you release it. Click on Releases and there should be a file there for you to download.

**Comment by juant87** [comment]
check upload artifact as well, i had the issue and i reran it with upload artifact. file appeared on that run
