### ISSUE TITLE
[Bug] YTCastConfirm

### ISSUE THREAD

**Issue by sleeping10** [qnblackcat/uYouPlus#156]
### Device info
- iOS/iPadOS version: 15.4.1
- Device model: iPhone se (2020)
- Sideload tool AltStore
- Version of uYouPlus: v17.18.4-21

### Describe the bug
The latest update broke YTCastConfirm, so you don't have to confirm before getting the cast options.

### reproduce 
https://user-images.githubusercontent.com/37278143/168141552-d0660a00-353c-4629-808a-cf24b8ded80c.MOV

**Comment by qnblackcat** [comment]
Did you remove vanilla YouTube ?

**Comment by sleeping10** [comment]
Yes, I don't have that version installed.

**Comment by qnblackcat** [comment]
Please try v17.19.3-2.1 and lmk if the issue persists.

**Comment by sleeping10** [comment]
![image](https://user-images.githubusercontent.com/37278143/169611200-a361bd05-7706-409e-be89-691030715271.png)
Still same

**Comment by hero3210** [comment]
this issue does not exist on jailbroken iPhone with official youtube app & YTCastConfirm installed. 
- v17.18.4 works fine
- v17.19.3 works fine
 
 
 Non jailbroken:
- uYouPlus ipa v17.17.4 works fine
- uYouPlus ipa v17.18.4 shows both the YTCastConfirm pop up & the "available casting devices" (the menu that is supposed to show up after you agree to cast in the YTCastConfirm pop up) at the same time.
- uYouPlus ipa v17.19.3 still has the same issue.


also I think you should update YTMiniplayerEnabler to v0.0.3

**Comment by qnblackcat** [comment]
should be fixed in the next release

**Comment by qnblackcat** [comment]
Please try v17.20.3-2.1 and leave a feedback

**Comment by hero3210** [comment]
> Please try v17.20.3-2.1 and leave a feedback

works fine
Thanks
