### ISSUE TITLE
[v3.0.3] Blank page on home page

### ISSUE THREAD

**Issue by fukemy** [qnblackcat/uYouPlus#1569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 18
- Device model: iPhone12
- Sideload tool : AltStore

### IPA source

lasted source 3.0.3

### Describe the issue

see video here

### Steps to reproduce

1. download ipa 3.0.3
2. install using altstore
3. open on iphone with ios 18

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by PianoMan7** [comment]
Yeah I'm getting this too on 3.0.4 (iPhone 15 Pro Max) on iOS 17.6.1.

**Comment by pbount** [comment]
Same here. Has been bugging me for the past few months.

**Comment by foursplaysroblox** [comment]
anyway to fix it?

**Comment by PianoMan7** [comment]
Not sure why you're closing this @fukemy, but yeah, I switched to YTLitePlus a few days ago too based on an r/sideloaded thread. None of the issues that uYouPlusPlus is having so far.

**Comment by PianoMan7** [comment]
What's the significance of qnblackcat?
