### ISSUE TITLE
[v3.0.4] YouPiP not working on iOS 18.0

### ISSUE THREAD

**Issue by peterge1998** [qnblackcat/uYouPlus#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 18.0
- Device model: iPhone 15 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Signulous

### IPA source

via the Signulous App Library

### Describe the issue

I have enabled PiP in Settings > General > Picture in Picture on my iPhone.
I have enabled PiP, Use PiP Button and Non-backgroundable PiP in YouTube > Settings > YouPiP too and restarted the app:
![image](https://github.com/user-attachments/assets/d24c8ab6-a1bb-4180-b47d-9b970c77a947)
But its not working and the button is doing nothing if i press it.

### Steps to reproduce

1. Enable those settings
2. restart
3. swipe to go to homescreen or press button and nothing happens

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by peterge1998** [comment]
I have tried enabling Legacy PiP too, it doesnt work too :(

**Comment by juant87** [comment]
turn off youpip and restart. the phone’s native pip should kick in. 
keep in mind some videos don’t allow pip

**Comment by peterge1998** [comment]
i have disabled youpip and restarted. After trying ~10 videos, none of them worked.
The native pip does not work here too.
There seems to be a bug here, that's why I posted this issue ;(

**Comment by peterge1998** [comment]
It works if I enable the Picture-inpicture option in settings > General. Maybe this is related to my Premium account :o
