### ISSUE TITLE
[question] hard coded ipa link

### ISSUE THREAD

**Issue by krispyking24** [qnblackcat/uYouPlus#1577]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

would google care if a fork of this repo has a hard coded link to the ipa. the reason i want to do this is so i don’t have to constantly put the link in manually this allows me to auto compile when i sync the repo with this parent repo

**Comment by PoomSmart** [comment]
There should never be a direct link to IPA be it in a fork or not.
