### ISSUE TITLE
[v19.08.2-3.0.3] , apps not appearing when I scroll after launching

### ISSUE THREAD

**Issue by Attar18** [qnblackcat/uYouPlus#1586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version:  18.1
- Device model:  iPhone 15 plus
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): 
Altstore 

### IPA source

The uyou plus website

### Describe the issue

Videos don’t appear until I scroll down, sometimes it is more severe than this, no videos appearing for several scrolls.
![IMG_9237](https://github.com/user-attachments/assets/fc1034d8-2e8b-4915-bc8f-bdd48b3e3925)
![IMG_9238](https://github.com/user-attachments/assets/f6c983c6-5c09-4ca0-b179-05d22d727136)

### Steps to reproduce

1.  Launch the app
2. Scroll down 

### Crash log

```shell
None
```

### Are you using the latest version of uYouPlus? If not, why?

❌ No, I'll explain with additional information below

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

I’m on version 3.0.3, I can’t find version 3.0.4 anywhere

**Comment by afridi7** [comment]
The error seems to be in YTAsyncCollectionView

This might be helpful:
https://youtu.be/XFvs6eraBXM
Timestamp: 1:30

**Comment by yasoob** [comment]
Experiencing the same issue for some time now. The app has become unusable because of this.

**Comment by PoomSmart** [comment]
The uYouPlus website is not affiliated with this  uYouPlus GitHub project.
