### ISSUE TITLE
Application crashes when launched within LiveContainer

### ISSUE THREAD

**Issue by ryenots** [qnblackcat/uYouPlus#1591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.5.1
- Device model: iPhone XS Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): SideStore, LiveContainer

### IPA source

Via this link: https://decrypt.day/app/id544007664

### Describe the issue

When using LiveContainer to launch uYouPlus, Either LiveContainer or uYouPlus is crashing. LiveContainer is functioning for me with other apps, so it may be an issue with uYouPlus, though I am not sure. Here is a link to LiveContainer:
https://github.com/khanhduytran0/LiveContainer

### Steps to reproduce

1. Follow steps to launch uYouPlus within LiveContainer
2. The app will fail to launch and LiveContainer will restart to the launcher page

### Crash log

```shell
The following is a LiveContainer crash log, uYou/Youtube crash logs are not available for this crash.
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

I have not tested trying to sign the official YouTube app within LiveContainer.

**Comment by yodaluca23** [comment]
Not every app is compatible with Live Container...

**Comment by yodaluca23** [comment]
https://github.com/khanhduytran0/LiveContainer/issues/130
