### ISSUE TITLE
[latest] cant build ipa from actions

### ISSUE THREAD

**Issue by hehbveh** [qnblackcat/uYouPlus#1596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version:  na
- Device model: na
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): na

### IPA source

https://armconverter.com/decryptedappstore/us

### Describe the issue

keep geting this error when "Fix compiling & Build Package": 

Run mkdir -p theos/lib/iphone/rootless
==> Downloading uYou…
tar: Error opening archive: Unrecognized archive format
==> Error: Failed to extract uYou
tar: Error opening archive: Failed to open 'Tweaks/uYou/data.tar*'
make: *** [Makefile:63: before-all] Error 1
Error: Process completed with exit code 2.

### Steps to reproduce

1.  actions >build
2. 

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by O-PM** [comment]
GitHub must be acting up cause it’s not working for me either. Been trying to four hours.

**Comment by Jackolix** [comment]
Same for me

**Comment by ALM0GI0** [comment]
I looked into it and in seems that something is wrong with miro92 servers

**Comment by Jackolix** [comment]
> I looked into it and in seems that something is wrong with miro92 servers

but i can retrieve and unpack the file. maybe there is something wrong from the github side

**Comment by fghjklpo98765** [comment]
same issue

**Comment by Mariner10** [comment]
Running into the same issue.

**Comment by Gullzway** [comment]
Just saw this. I'm trying to build with Github and it's failing looking for a zip file?
Isn't it supposed to be linked to the ipa?

"[YouTube.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of YouTube.zip or
        YouTube.zip.zip, and cannot find YouTube.zip.ZIP, period.
Error: Process completed with exit code 9."

**Comment by NoamHarel1** [comment]
same here

**Comment by philippbla** [comment]
still not working

**Comment by peterjumper** [comment]
same here

**Comment by hehbveh** [comment]
> > I looked into it and in seems that something is wrong with miro92 servers
> 
> but i can retrieve and unpack the file. maybe there is something wrong from the github side

i tried to build it locally rather then from GitHub actions and I'm having the same problem which implies that the error is on miro92 server

**Comment by TheAtomGuy** [comment]
I just added the .deb file in uYou tweaks folder and it built it successfully for me.

**Comment by Jackolix** [comment]
> I just added the .deb file in uYou tweaks folder and it built it successfully for me.

didnt work for me, i put it in tweaks and tweaks/uYou folder

**Comment by hehbveh** [comment]
Thank you

**Comment by hehbveh** [comment]
> I just added the .deb file in uYou tweaks folder and it built it successfully for me.
still having no luck, did you make any changes to the buildapp.yml or the makefile? if yes can you kindly share?

**Comment by philippbla** [comment]
No, check out my fork to see exactly what I did - I only added the .deb file into the Folder /Tweaks/uYou/com.miro.uyou_3.0.4_iphoneos-arm.deb and ran the pipeline

**Comment by hehbveh** [comment]
> No, check out my fork to see exactly what I did - I only added the .deb file into the Folder /Tweaks/uYou/com.miro.uyou_3.0.4_iphoneos-arm.deb and ran the pipeline

Yes but you mentioned that it didn't work for you to do that, that's why i replied to @TheAtomGuy , __ want to know what he did to get it working.

**Comment by hehbveh** [comment]
> No, check out my fork to see exactly what I did - I only added the .deb file into the Folder /Tweaks/uYou/com.miro.uyou_3.0.4_iphoneos-arm.deb and ran the pipeline

nm, I checked it out and followed what you did and it is now working for me, ty!

**Comment by nirav-raval** [comment]
Finally figured it out!!!

Looks like this fork is not upto date. Just delete this fork and create new one from : https://github.com/arichornlover/uYouEnhanced


Decrypted Link (Youtube V 19.44.4): https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.44.4?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExNTczMjk5LCJpYXQiOjE3MzEwMzA0NDIsImV4cCI6MTczMTA0MTI0MiwiYXBwaWQiOjU0NDAwNzY2NCwiYXBwdmVyIjoiMTkuNDQuNCJ9.yti6AOGujnDNV1KPHY5_LIagplIXzz1SgRDvoLQQ7Ak

**Comment by hehbveh** [comment]
> Finally figured it out!!!
> 
> Looks like this fork is not upto date. Just delete this fork and create new one from : https://github.com/arichornlover/uYouEnhanced
> 
> Decrypted Link (Youtube V 19.44.4): https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.44.4?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExNTczMjk5LCJpYXQiOjE3MzEwMzA0NDIsImV4cCI6MTczMTA0MTI0MiwiYXBwaWQiOjU0NDAwNzY2NCwiYXBwdmVyIjoiMTkuNDQuNCJ9.yti6AOGujnDNV1KPHY5_LIagplIXzz1SgRDvoLQQ7Ak

uYouEnhanced is a fork of this repository with different features, not an "updated" version of this repository. We just have to wait for the devs to push an update.

**Comment by yodaluca23** [comment]
> Finally figured it out!!!
> 
> 
> 
> Looks like this fork is not upto date. Just delete this fork and create new one from : https://github.com/arichornlover/uYouEnhanced
> 
> 
> 
> 
> 
> Decrypted Link (Youtube V 19.44.4): https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.44.4?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExNTczMjk5LCJpYXQiOjE3MzEwMzA0NDIsImV4cCI6MTczMTA0MTI0MiwiYXBwaWQiOjU0NDAwNzY2NCwiYXBwdmVyIjoiMTkuNDQuNCJ9.yti6AOGujnDNV1KPHY5_LIagplIXzz1SgRDvoLQQ7Ak

Bro just leaked his token 💀💀💀

**Comment by nirav-raval** [comment]
what are they used for?

> > Finally figured it out!!!
> > Looks like this fork is not upto date. Just delete this fork and create new one from : https://github.com/arichornlover/uYouEnhanced
> > Decrypted Link (Youtube V 19.44.4): https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.44.4?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExNTczMjk5LCJpYXQiOjE3MzEwMzA0NDIsImV4cCI6MTczMTA0MTI0MiwiYXBwaWQiOjU0NDAwNzY2NCwiYXBwdmVyIjoiMTkuNDQuNCJ9.yti6AOGujnDNV1KPHY5_LIagplIXzz1SgRDvoLQQ7Ak
> 
> Bro just leaked his token 💀💀💀

what are they used for?

**Comment by Bananaman811** [comment]
> I just added the .deb file in uYou tweaks folder and it built it successfully for me.

That fixed it for me, thanks.

**Comment by Survingo** [comment]
see #1581

**Comment by hehbveh** [comment]
> see #1581

that's not the reason, because macOS 12  will but still isn't deprecated

**Comment by eswiig** [comment]
[Build uYouPlus] failed
You are using macOS 12.
We (and Apple) do not provide support for this old version.

**Comment by hehbveh** [comment]
> [Build uYouPlus] failed You are using macOS 12. We (and Apple) do not provide support for this old version.

again, the problem is on the side of miro92's repo he added Cloudflare bot detection so runners cant download the .deb. However if @qnblackcat will just add the .deb to his repo without making every runner go out and download it we wont have this issue.

also you can still use macOS 12 till 12/3 it just gives that error because it want everybody to update already as noted "Deprecation will begin on 10/7/24 and the image will be fully unsupported by 12/3/24". So that's not the cause of the build failing, its because of the captcha that runners don't support.

**Comment by huynguyen96419** [comment]
Nobody in project can't fix that? i tried many ways but still error

**Comment by Jackolix** [comment]
> Nobody in project can't fix that? i tried many ways but still error

fork the project from [philippbla](https://github.com/philippbla/uYouPlus)

**Comment by huynguyen96419** [comment]
> > Nobody in project can't fix that? i tried many ways but still error
> 
> fork the project from [philippbla](https://github.com/philippbla/uYouPlus)

It work, tks so much!

**Comment by NutchapolSal** [comment]
> It's due to Miro adding cloudflare to their side, working on a pr to fix this.

Maybe have the user input a direct link to file to the workflow (just like what you have to do with the Youtube IPA)?

**Comment by PoomSmart** [comment]
Fixed.
