### ISSUE TITLE
[Questions] How to update uYou (installed via AltStore)

### ISSUE THREAD

**Issue by antondalov** [qnblackcat/uYouPlus#160]
I have an older version on my iphone and I would like to update to the newest one. I have installed it with AltStore (via AltServer on windows). How do I update the app ? Do I need to delete the older one ?

**Comment by techynAR** [comment]
> I have an older version on my iphone and I would like to update to the newest one. I have installed it with AltStore (via AltServer on windows). How do I update the app ? Do I need to delete the older one ?

Simply download the new ipa and sign it using AltStore. No need to delete the previous version. Doing so, uYou+ will get updated to the latest version.

**Comment by Skywalker8510** [comment]
so you're telling me that iv been deleting the old version every time for no reason

**Comment by techynAR** [comment]
I used to do the same mistake as you are doing a few weeks ago :(

**Comment by qnblackcat** [comment]
The answer from @techynAR is correct. Do not remove the current version, just overwrite it with the newer
