### ISSUE TITLE
[v19.45.4-3.0.4] All icons missing

### ISSUE THREAD

**Issue by Som314** [qnblackcat/uYouPlus#1602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 18.1
- Device model: iPhone 14 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): AltStore

### IPA source

https://decrypt.day/app/id544007664

### Describe the issue

All the icons in the YouTube app are gone, you and still interact by them by clicking where they should appear, it is just that they are not visually loading up.

![photo_2024-11-16_19-14-50](https://github.com/user-attachments/assets/c21b5751-df10-46e7-ac00-dc85d7e1bf70)
![photo_2024-11-16_19-14-49](https://github.com/user-attachments/assets/d0d7906f-c11d-43b2-ac93-424d54369290)

### Steps to reproduce

1. This bug occurs as soon as I sideload the IPA file.

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by hehbveh** [comment]
Having same problem

**Comment by Som314** [comment]
I switched to YTLite, I find that it works a lot better than uYou. Here is a link if you are interesed: https://ytliteplus.github.io/

**Comment by hehbveh** [comment]
I’ll look into it ty

**Comment by mini** [comment]
Just ran into this

The fix in this [other issue](https://github.com/qnblackcat/uYouPlus/issues/1508#issuecomment-2296735529) worked for me

**Comment by Som314** [comment]
Ok nice
