### ISSUE TITLE
[Bug] Application Missing application-identifier entitlement

### ISSUE THREAD

**Issue by jeffzyliu** [qnblackcat/uYouPlus#161]
### Device info
- iOS/iPadOS version: 15.4.1
- Device model: Iphone 10
- Sideload tool AltStore
- Version of uYouPlus: 17.19.2 (2.1)

### Describe the bug
Application missing app-identifier entitlement upon install via AltStore source AND manual sideloading. Earlier version 17.18.4 is fine.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:

**Comment by angrykid8** [comment]
I'm experiencing the same. iPhone X on 15.1

**Comment by jeffzyliu** [comment]
Closing since I assume this is fixed on the F2/F3 version.
