### ISSUE TITLE
[19.47.7-3.0.4] VP9 Codec Not Working

### ISSUE THREAD

**Issue by falchion10** [qnblackcat/uYouPlus#1614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 18.2 Developer Beta 2
- Device model: iPhone 16 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): Sideloadly

### IPA source

https://armconverter.com/decryptedappstore/us/YouTube

### Describe the issue

The VP9 Codec option in "Video quality preferences" shows "Hardware VP9 Support: 0". 
![Screenshot](https://github.com/user-attachments/assets/d158ada6-8c61-4ab9-9f00-6ef3217bf794)

### Steps to reproduce

1. Open uYouPlus
2. Go to Settings --> Video quality preferences
3. The "Use VP9" option shows with "Hardware VP9 Support: 0"

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by falchion10** [comment]
According to the official [YTUHD GitHub](https://github.com/PoomSmart/YTUHD), the private entitlement responsible for handling this, `com.apple.coremedia.allow-alternate-video-decoder-selection`, is removed when any YouTube app is sideloaded, making it impossible to fix.

**Comment by PoomSmart** [comment]
It works, but the only thing that works is the availability of 1440p+ video quality selection. The hardware acceleration on the other hand doesn't work if sideloaded.

I think at the time the contributors hadn't realized it would pose so much battery issue - or some people thought they are fine with this drawback.
