### ISSUE TITLE
YouTube crashes

### ISSUE THREAD

**Issue by Pavxgaming** [qnblackcat/uYouPlus#1615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

-iPhone 6s
-iOS 15.1
-TrollStore

### IPA source

Fleckstore premium

### Describe the issue

Upon opening any video except from, shorts, the YouTube app will crash 100% of the time

### Steps to reproduce

1. Open the app
2. Open the video

### Crash log

```shell
Unfortunately, I don’t have that setting and I can’t check the log.
```

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

Does the check for updates button work? It doesn’t for me

**Comment by gigaiis** [comment]
I have the same problem, I installed the next version 19.08.2-3.0.3
when I disable iSponsorBlock the problem disappears
