### ISSUE TITLE
[Questions]is it possible to add something that completely removes yt shorts.

### ISSUE THREAD

**Issue by Skywalker8510** [qnblackcat/uYouPlus#162]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###
is it possible to add something that completely removes YT shorts? I know there's a setting to remove them in uyou but the short videos still clutter up my subscription feed as normal videos and I don't want to see them most of the time.

**Comment by qnblackcat** [comment]
**Remove YouTube Shorts Section in YouTube Home** is working fine for me.

**Comment by Skywalker8510** [comment]
it gets rid of the shorts format. the videos still show up as regular videos tho

**Comment by qnblackcat** [comment]
So you want to remove all videos that are less than 30 seconds? I don't think it's possible

**Comment by Skywalker8510** [comment]
oh ok
