### ISSUE TITLE
How do I know which YouTube version uYouPlus needs?

### ISSUE THREAD

**Issue by dinhnhu291** [qnblackcat/uYouPlus#1621]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

If i build with youtube version below 19.20.xxx
I see that.
But if i build with lasted youtube version, i missing all icon UI

So… How do I know which YouTube version uYouPlus needs?

![IMG_5049](https://github.com/user-attachments/assets/714fb659-f38f-4646-a995-1e717e590393)

**Comment by hellobrother222** [comment]
The missing icons come from activating the youtube fix to log in. Once you log in, disable the youtube fix and you’ll be ok. Use Youtube v19.33.2

**Comment by TypicalShavonne** [comment]
Check readme section for youtube ipa version

**Comment by PoomSmart** [comment]
This alert is from uYou, so it's uYouPlus to really decide.
