### ISSUE TITLE
[3.0.4 Commit f71c480] New YouSpeed submodule does not appear in Video Overlay settings tab

### ISSUE THREAD

**Issue by gmanc2** [qnblackcat/uYouPlus#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 18.3
- Device model: 13 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): AltStore

### IPA source

decrypted app store

### YouTube version

19.42.1

### Describe the issue

I installed the latest version of uYouPlus and the Video Speed Overlay from YouSpeed does not show up in Video Overlay.![image](https://github.com/user-attachments/assets/6b814e3c-cb40-4c20-a10d-4ddd01d1a00a)

uYou 3.0.4 Commit f71c480
YouTube version 19.42.1

### Steps to reproduce

1. Open Youtube Settings
3. Navigate to Video Overlay
4. YouSpeed enable setting is not present

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

### Additional information

https://github.com/PoomSmart/YouSpeed/issues/4#issue-2762388673

**Comment by PoomSmart** [comment]
Fixed in the latest commit.
