### ISSUE TITLE
[Bug] uYou doesn't Open after updating to 17.19.2-2.1 in Altstore

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#163]
### Device info
- iOS/iPadOS version: 15.5
- Device model: iPad Pro 2 (10.5)
- Version of uYouPlus: 17.19.2-2.1

### Describe the bug
App doesn't open after updating uYou, this is the first time this occured when updating it

### How to reproduce the bug
I have no clue but try checking the code if altstore is broken

### Crash log (if possible)
[YouTube-2022-05-16-170817.txt](https://github.com/qnblackcat/uYouPlus/files/8703754/YouTube-2022-05-16-170817.txt)

### Additional context
I have no more information about this.

**Comment by arichorn** [comment]
since I can't use uYou at the moment, I'll stick for normal youtube until I'll see the true problem

**Comment by jeffzyliu** [comment]
I opened #161, I'm also getting this error. I was able to manually sideload last version's IPA to get back on the app.

**Comment by arichorn** [comment]
guess I'll revert it too. I think the "improved performance" might've broken the app. just a guess on why this happened to me or us.

**Comment by arichorn** [comment]
[Open in AltStore (v17.18.4-2.1)](https://tinyurl.com/bdzxtdrx)
here's the previous version y'all, this one is the one that works correctly so don't use the new one until it's solved :(

**Comment by qnblackcat** [comment]
Try Sideloadly

**Comment by arichorn** [comment]
I don't trust Sideloadly due to Trojan-related ipas or other and saying "Try Sideloadly" isn't a way to respond with. it doesn't help and doesn't help in any way possible. the real reason is the Altstore Identifier not being able to work.

**Comment by qnblackcat** [comment]
@arichorn I use Sideloadly and it works fine on my test device. Idk what to fix if I can’t even recall it 🤷‍♂️

**Comment by qnblackcat** [comment]
@jeffzyliu @arichorn try [this version](https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/Ear_2OnnyvZJkygaAXrX27MBeaju8sRVnIbfRa1jv0XJYA?download=1)

**Comment by jeffzyliu** [comment]
> @jeffzyliu @arichorn try [this version](https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/Ear_2OnnyvZJkygaAXrX27MBeaju8sRVnIbfRa1jv0XJYA?download=1)

@qnblackcat it worked for me! Thanks for the ipa

**Comment by arichorn** [comment]
Thanks! It’s resolved on the newer version! This issue is now closed! :D
