### ISSUE TITLE
[Enhancement] Option for removal of Next/Previous video overlay control

### ISSUE THREAD

**Issue by simonlokk** [qnblackcat/uYouPlus#164]
Hello!
First and most importantly, thank you for the time and effort you put into this tweak! I have a small suggestion for a future release. It would be nice to have the option to remove the next/previous buttons from the video controls overlay. Some older youtube tweaks had this and it was a nice addition. Some may find the next/previous overlay video buttons not particularly useful and when viewing a video in a small window size it becomes very easy to accidentally hit them while double tapping to skip forward or back within video. Hope this makes sense.

Thanks again for your time

**Comment by qnblackcat** [comment]
Hide those buttons or Disable them (unclickable). Which one is better?

**Comment by arichorn** [comment]
Actually hiding them is a good tweak, I only want the pause/play button on YouTube, if this happens, then this will be awesome

**Comment by qnblackcat** [comment]
Added in v17.19.3. Lmk if it works

**Comment by arichorn** [comment]
Update: the thing is it works after using it for 4 days! Good job with this addition! :D
