### ISSUE TITLE
[Bug]Home bar does not hide while playing video in full screen

### ISSUE THREAD

**Issue by Anertz** [qnblackcat/uYouPlus#165]
### Device info
- iOS 15.4.1/15.5
- Device model: iPhone12
- Sideload tool  AltStore
- Version of uYouPlus:  v17.19.2-2.1-F3 / v17.19.2-2.1

### Describe the bug
Home bar does not hide while playing video in full screen.
Reverting to a previous version of uYou will fix this problem.
### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Play videos in full screen

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by arichorn** [comment]
Same as the Stupid 3 Dots (Mulitasking) for me personally I want uYou to disable the 3 dots after the home bar is hidden in full screen :(

**Comment by qnblackcat** [comment]
Does it happen with the original version of YouTube from AppStore?

**Comment by MrDirectory** [comment]
Yes, the original version from there also does have that bug.

**Comment by Anertz** [comment]
Yes, there was a problem with the original Youtube, I should have verified it before reporting the bug, sorry. Thanks as always for the great Tweaked IPA!

**Comment by qnblackcat** [comment]
Try to enable **Fake YouTube version** in**YouPiP** setting

**Comment by MrDirectory** [comment]
Nope, that doesn't fix the issue.

**Comment by qnblackcat** [comment]
v17.19.3-2.1 is available

**Comment by qnblackcat** [comment]
Fixed in v17.19.3-2.1
