### ISSUE TITLE
[Enhancement] Make the sponsorblock dialog smaller/hide it

### ISSUE THREAD

**Issue by nikhilcn5** [qnblackcat/uYouPlus#166]
### Device info
- iOS/iPadOS version: 15.4
- Device model: iPhone 13 mini
- Sideload tool :AltStore,
- Version of uYouPlus: 2.1

### How to reproduce the bug
_(Please attach videos or screenshots if p
![168478879-23f01313-c383-4a97-9f0a-52305a2dcd90](https://user-images.githubusercontent.com/36162439/168797994-5635bd48-9751-4e37-b9bd-ce9cf599b1a6.jpeg)
ossible)_

**Comment by qnblackcat** [comment]
https://github.com/Galactic-Dev/iSponsorBlock/issues/34

**Comment by arichorn** [comment]
I think when the developer made the sponser block, the dev mus’ve only made most of it for the iPad due to its bigger displays and screens, I think that explains why it’s too big or oversized on iPhones, but I think it’ll be fixed eventually

**Comment by oomek** [comment]
Why is it closed? Does it mean no chance for a hide button? That would help a lot, because of many false positives.

**Comment by arichorn** [comment]
qnblackcat didn’t develop iSponserBlock @oomek that’s why it was closed as not planned. If you want this to happen I suggest going here https://github.com/Galactic-Dev/iSponsorBlock
It’s the place where the real developer made the stuff happen.
