### ISSUE TITLE
[Enhancement] force-disable or remove Multitasking (iPadOS 15 Exclusive, does not work on other os’s)

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#168]
### Device info
- iPadOS version: 15.5
- iPad model: iPad Pro 10.5
- Sideload tool: AltStore
- Version of uYouPlus: 17.19.2-2.1-F3

### Describe the Enhancement
As you might of noticed, YouTube make sure of you to use multitasking on the app which ruins the whole uYou experience having it off makes uYou better and probably have all of its features fixed like the Mini Players and such, i don’t know if this is option is possible, if it’s not easy to do then somewhat disable the whole thing.

### How to make this change possible
there are ways to disable it, I can clearly see people hates this on YouTube, but personally I think it might be kind of hard to remove it or disable it.

**Comment by arichorn** [comment]
I’m suggesting to remove it because the latest version of uYou now makes the option to appear everywhere within the app

**Comment by qnblackcat** [comment]
IMO, it's impossible to achieve what you want on a jailed device. I also don't own an iPad so you should ask other developers.
