### ISSUE TITLE
[Bug] Missing Shorts Button and Downloads Not Working

### ISSUE THREAD

**Issue by ChromiumPanda** [qnblackcat/uYouPlus#170]
### Device info
- iOS/iPadOS version: 15.4
- Device model: iPhone 13
- Sideload tool: Sideloadly
- Version of uYouPlus: 2.1

### Describe the bug
- Buttons for downloading video is missing from shorts player.
![image](https://user-images.githubusercontent.com/105122141/168972483-631973f5-493a-433d-92ac-de3388005aaa.png)
- Attempting to download shorts with URL causes download to not finish completely despite saying 100%. Video does not play, or open normally. It brings up an option to open the video in a browser, instead of in the app, when pressing "Play on Youtube". 
![image](https://user-images.githubusercontent.com/105122141/168976787-1e6361a4-8a13-4020-9b33-1783204b9ab7.png)

![image](https://user-images.githubusercontent.com/105122141/168976812-83b09e64-7e69-445a-8199-4c3e23746fbc.png)

Opening the link takes it to this page:
![image](https://user-images.githubusercontent.com/105122141/168972689-4fe43beb-b4ac-4100-aa22-5761c3b1dff2.png)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/issues/158

**Comment by sdykae** [comment]
Which version is this implemented  in ;(?

**Comment by level3tjg** [comment]
> Which version is this implemented in ;(?

[v17.34.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.34.3-2.1)+
