### ISSUE TITLE
[Enhancement] Using yt-dlp for downloading videos/audio

### ISSUE THREAD

**Issue by antondalov** [qnblackcat/uYouPlus#171]
## Describe the problem

The current tool(youtube-dl) which is used is outdated and very slow. The download rates are pretty much below 0.5 Mb/s even with 5G or good WiFi-network. 

## Suggestion
There are many other alternative packages which provide a better download rate. The yt-dlp ([GitHub page](https://github.com/yt-dlp/yt-dlp)) is a great package with many features. I think using this package will be a great W for everybody using uYouPlus.

**Comment by qnblackcat** [comment]
This is beyond my knowledge. Sorry!

**Comment by antondalov** [comment]
Wouldn't anybody be able to make a PR for this ?
