### ISSUE TITLE
[Questions] Does it work with iOS 15.5 ?

### ISSUE THREAD

**Issue by schweppes-0x** [qnblackcat/uYouPlus#172]
As the title already suggests, does it work with the newest version (15.5) ?  Has anyone already tried using it ?

**Comment by arichorn** [comment]
I did, and it works pretty well on my iPad (iPadOS 15.5)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus#download

**Comment by schweppes-0x** [comment]
I can confirm, it works!
