### ISSUE TITLE
[Enchantment] Remove recommendations in search results

### ISSUE THREAD

**Issue by ShadowRoi** [qnblackcat/uYouPlus#173]
Ever wanted to search something in youtube and you have these super annoying Recommendations that pop up in search results while you scroll down to find the video you want? 
Yes i have experienced that feeling a lot and probably none of us is interested in seeing these stuff, these should belong in the home page and not search results. There are stuff like "For You" "Previously watched" etc. 
![2022-05-21_11-05](https://user-images.githubusercontent.com/105967373/169642307-bbd00d62-b341-4aa7-bab0-be16b7c87941.png)

Luckily in the desktop there were made some blocking rules in uBlock that has solved this. Is it possible if can be ported to the Mobile version? Here are the rules: https://www.reddit.com/r/youtube/comments/rpmx2y/how_to_remove_related_to_your_search_related

Also i had read somewhere that there the ads in search results were difficult to block?

**Comment by arichorn** [comment]
This might be possible and I would love the For You page to be hidden in YouTube’s search system

**Comment by qnblackcat** [comment]
I won't do it. Sorry!
