### ISSUE TITLE
[Enhancement] Make Minimal Player option

### ISSUE THREAD

**Issue by TheLidlMan** [qnblackcat/uYouPlus#174]
### Describe this
![IMG_2961](https://user-images.githubusercontent.com/75203773/169660887-e864e76b-0f35-4c16-a212-8c045b628638.PNG)

The option in settings to remove the circled things in the image above (uYou menu, Like and Dislike Button and Recommenced, Title, Speed Control, Sponsor Block options) when in full screen or all the time. Either as individual settings for each area? **or** as all in one go as in just one slider for minimal player? **Which ever is easier**

Thanks

**Comment by qnblackcat** [comment]
I can’t do it. Sorry
