### ISSUE TITLE
[Enhancement] a easier search results deletion button

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#176]
### Device info
- iOS/iPadOS version: 15.5.0
- Device model: iPad Pro 10.5 + iPhone 11
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore
- Version of uYouPlus: 

### Describe the issue
This is just a new option for a search improvement, I think everyone had this problem for years on the normal YouTube and I’m about to tell you how this would work.

### How to reproduce the problem
![48026DC7-371B-4FA1-AA03-3D2922010614](https://user-images.githubusercontent.com/78001398/169722716-9d9e43ba-2542-4af8-bf9f-c3d034af6c86.jpeg)
This image shows this, it has a major problem that i or we have to deal with, if you swipe left on them it will sometimes not respond to you which is the most annoying thing to have on the app.

![E47FCE4D-E5B9-4AC9-A25C-A39C23AD7043](https://user-images.githubusercontent.com/78001398/169722759-0d38a0d8-863a-4fcd-a74f-0245b61e66cd.png)
this option, this isn’t a real image but I added a X at the right of the searched text, which pressing it would likely remove it and easier then swiping on it multiple times. I do feel like it’s not possible so I should expect it to get denied but qnblackcat, I hope this was a good idea!

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by qnblackcat** [comment]
I can’t do it, plus I don't think it improves anything 🤷‍♂️

**Comment by arichorn** [comment]
Sorry. YouTube had an annoying system and sometimes swiping left to the screen won’t work and will not show "DELETE" on the search, always had to restart YouTube to bypass it but it’s fine I guess.
