### ISSUE TITLE
[Bug] Swipe up to see more related videos not working

### ISSUE THREAD

**Issue by DW-Arthur** [qnblackcat/uYouPlus#179]
### Device info
Ios 15.5
uYou+ 17.20

### Describe the bug

I can no longer swipe up to see more related videos

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:
![554C5712-17F3-4956-8724-A334BE681EAA](https://user-images.githubusercontent.com/39779028/170587852-66e5bfe9-e017-4efb-aef1-8b60d85a6db2.png)

**Comment by qnblackcat** [comment]
Sorry. This is my fault. It will be fixed in the next update. 
For now, try this: go to uYou‘s setting > Video controls overlay > turn on and off **Related Videos at the end the videos** > Restart the app
