### ISSUE TITLE
[Bug] Cannot access other videos in full screen without exiting fullscreen

### ISSUE THREAD

**Issue by MarioMastr** [qnblackcat/uYouPlus#181]
### Device info
- iOS/iPadOS version: iOS 15.5
- Device model: iPhone SE 2020
- Sideload tool: AltStore 
- Version of uYouPlus: v17.20.3-2.1

### Describe the bug
This seems to happen only with the newest release, but I can't seem to access other videos by swiping up in full screen anymore. 

### How to reproduce the bug
1. Have the latest uYouPlus version. 
2. Go into full screen and try to swipe up to find other videos. 

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:

**Comment by qnblackcat** [comment]
Fixed in v17.21.3-2.1
