### ISSUE TITLE
[Enhancement] Enable Shorts scroll bar

### ISSUE THREAD

**Issue by hero3210** [qnblackcat/uYouPlus#183]
Thanks for your hard work.

Please add [the code from here](https://reddit.com/r/jailbreak/comments/v29yvk/_/iasl1l0/)  to enable the scroll bar for Shorts. 

Thanks.

**Comment by arichorn** [comment]
@qnblackcat I have putted the source code right here so it’ll be easier and idk why YouTube didn’t force enable the scroll/progress bar, hero3210 actually has a good point when it comes to this.
```
%hook YTReelPlayerViewControllerSub
- (BOOL)shouldEnablePlayerBar {
    return YES;
}
%end
```

**Comment by qnblackcat** [comment]
Done
