### ISSUE TITLE
[Enhancement] Add YouAreThere - another Poomsmart

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#184]
### Describe It
Disables the "Video paused. Continue watching?" popup in the YouTube app when you play a long video.
This should stop the annoying pop up on the iPhone or iPad :(

### Link
https://poomsmart.github.io/repo/depictions/youarethere.html

**Comment by qnblackcat** [comment]
This feature is already available in uYou‘s setting

**Comment by arichorn** [comment]
I didn’t know, I readed the readme.md and looked at the tweaks that were already listed or added, at least I tried.
