### ISSUE TITLE
[Bug] Notification Bell Icon crashes the app

### ISSUE THREAD

**Issue by Manujito** [qnblackcat/uYouPlus#185]
When inside a channel, when tapping on the notification bell icon, the app crashes.

Tested on the past couple version via AltStore and Signulous. Same behavior.

**Comment by hero3210** [comment]
Can confirm this happens.
I believe this is a uYou bug since it also happens with official YouTube app & uYou tweak on jailbroken devices.

**Comment by qnblackcat** [comment]
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/83
