### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dxwil** [qnblackcat/uYouPlus#186]
### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:

**Comment by qnblackcat** [comment]
invalid issue
