### ISSUE TITLE
Error: Could not find any video in this playlist

### ISSUE THREAD

**Issue by RadioactivePeaches** [qnblackcat/uYouPlus#187]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️
yes

### Device info
- iOS/iPadOS version: 15.5
- Device model: iPhone SE
- Sideload tool (Ex: AltStore, Sideloadly...): AltStore 
- Version of uYouPlus: 2.1

### Describe the bug
When downloading a video via uYouPlus, it gives the error Error: Could not find any video in this playlist, and cannot download any videos, and have to be downloaded manually.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
open uYouPlus, go to the library tab, select a playlist, and tap on the uYou logo at the top, and the error will appear.

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by qnblackcat** [comment]
This is an issue of uYou, nothing I can do. See https://github.com/MiRO92/uYou-for-YouTube/issues/62

**Comment by RadioactivePeaches** [comment]
alright.
