### ISSUE TITLE
[Bug] Buggy miniplayer on iOS 16

### ISSUE THREAD

**Issue by TheLidlMan** [qnblackcat/uYouPlus#189]
### Device info
- iOS/iPadOS version: 16.0
- Device model: iPhone 12
- Sideload tool (Ex: AltStore, Sideloadly...) : Signulous 
- Version of uYouPlus: v17.22.3-2.1

### Describe the bug
The when closing down the video the video player goes funky and opening

### How to reproduce the bug
Set the MiniPlayer in settings on YouTube and then open and close player to mini one

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
https://user-images.githubusercontent.com/75203773/172252296-3d50ba26-e0b0-4149-8497-bf2ba363ffc0.MOV

### Additional context:

**Comment by qnblackcat** [comment]
Does it happen with ** New miniplayer bar style (BigYTMiniPlayer)** disabled?

**Comment by Skywalker8510** [comment]
miniplayer doesn't seem to be buggy for me on altstore

**Comment by Skywalker8510** [comment]
> Will it happen if **New miniplayer bar style (BigYTMiniPlayer)** is disabled?

that doesn't bug out either. I'm on all store with a free dev account and dev mode turned on on my phone

**Comment by TheLidlMan** [comment]
The fix it's to disable it (BigMiniPlayer) and then enable it after app restart in the middle
