### ISSUE TITLE
[Enhancement] Bring back ability to sort channel's videos by oldest first

### ISSUE THREAD

**Issue by tevyisertyin** [qnblackcat/uYouPlus#191]
In the latest versions of the YouTube app, the option to sort a channel's videos has been reduced to two options ("Recently uploaded" and "popular"). Is there any way to restore it to the previous behaviour (i.e. have it sort by "Most popular", "Date added (oldest)" or "Date added (newest)")?

**Comment by qnblackcat** [comment]
I can’t do it and I think it won't be easy 🤔

For now, you can enable **Fake YouTube version** in YouPiP’s setting to get the old YouTube’s UI, which has “Sort by oldest”

**Comment by tevyisertyin** [comment]
Thanks for the suggestion. Doing that means that the newest fix for scrubbing through Shorts won't work, though. Decisions, decisions... 🤔
