### ISSUE TITLE
[Bug] No video duration info in Watch Later section

### ISSUE THREAD

**Issue by lonsdaleite** [qnblackcat/uYouPlus#193]
### Device info
- iOS/iPadOS version: 15.5
- Device model: iPhone 12, iPad Mini 6
- Sideload tool: AltStore
- Version of uYouPlus: 17.22.3-2.1

### Describe the bug
There is no video duration info on preview in Watch Later section in Library. Duration info presents in official YouTube client v17.22.3 but not in uYou 17.22.3-2.1. Also checked 17.19.2-2.1, it has the same problem.

**Comment by qnblackcat** [comment]
![5A04366B-76EF-41B4-94DF-2D863FC14AD5](https://user-images.githubusercontent.com/52943116/172345137-05eaabca-54e5-42d5-9c48-1c8445ab9d80.jpeg)

https://github.com/qnblackcat/uYouPlus/releases
