### ISSUE TITLE
[uYouPlus-Code-Error] Buildapp.yml doesn’t work

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#197]
### uYouPlus info
- uYouPlus: latest commit - added buildapp Github action

### Describe this repository
I was here to warn you that the Buildapp.yml won’t work
You’ll get this error

Error: Resource not accessible by integration

and just so you know, I was the one using the buildapp.yml just to make sure it’ll work for you.
but if you already know this then you can close the issue.

**Comment by qnblackcat** [comment]
> I was here to warn you that the Buildapp.yml won’t work

It works for me. That’s why I pushed it to my repo. 

> Error: Resource not accessible by integration
There are a bunch of post about this problem on Github. Have you even tried to Google it?

**Comment by qnblackcat** [comment]
@ISnackable perhaps you know the reason?

**Comment by ISnackable** [comment]
Looking at the logs, it seems that the actions is failing to create a release.

Looks like GitHub restricts the [default permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) scope for the `GITHUB_TOKEN` on forked repos. You could probably manually configure the permissions in the job [permission field](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions), in the workflow file itself.

I believe you only need to adjust the `contents` [permission](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#permission-on-contents).

```yml
jobs:
  build:
    name: Build uYouPlus
    runs-on: macos-latest

    permissions:
      contents: 'write'
```

**Comment by arichorn** [comment]
it actually builded! The permissions worked like you said!
![FCFD137E-D48C-4ED2-8B3D-BED0DB50971F](https://user-images.githubusercontent.com/78001398/172987195-6d66e192-60ae-42cf-9519-4f292d0c2eb2.jpeg)

**Comment by qnblackcat** [comment]
> You could also opt to use [actions/upload-artifact@v3](https://github.com/actions/upload-artifact)… 

can you open a Pull request?

**Comment by arichorn** [comment]
> > You could also opt to use [actions/upload-artifact@v3](https://github.com/actions/upload-artifact)…
> 
> can you open a Pull request?

I forgot about the artifacts, didn’t think that through

**Comment by ISnackable** [comment]
> Sure, opened a PR at #200 

![image](https://user-images.githubusercontent.com/52971804/172991673-601191cd-03a9-4fb8-8004-bb91c906c2a8.png)

**Comment by ISnackable** [comment]
Hey @qnblackcat, saw that you created [buildapp.yml](https://github.com/qnblackcat/uYouPlus/blob/main/.github/workflows/buildapp_release.yml) file, for release. Do you perhaps want to combine both into a single file? We could add an input checkbox for whether a draft release should be created. This way, user won't be confused on which workflow to run.

**Comment by qnblackcat** [comment]
> Hey @qnblackcat, saw that you created [buildapp.yml](https://github.com/qnblackcat/uYouPlus/blob/main/.github/workflows/buildapp_release.yml) file, for release. Do you perhaps want to combine both into a single file? We could add an input checkbox for whether a draft release should be created. This way, user won't be confused on which workflow to run.

Sounds good. But I thought people can’t run the release workflow because of the Github token?

**Comment by ISnackable** [comment]
> Sounds good. But I thought people can’t run the release workflow because of the Github token?

It should work fine if the GitHub token permission is explicitly defined in the workflow file. I have made a PR at qnblackcat/CercubePlus#7 and #222.
