### ISSUE TITLE
Is there a way to/setting to disable tracking for return dislike button?

### ISSUE THREAD

**Issue by CycIoneTM** [qnblackcat/uYouPlus#198]

**Comment by qnblackcat** [comment]
Not sure I understand your question? Can you explain more?

**Comment by CycIoneTM** [comment]
> Not sure I understand your question? Can you explain more?

![E0C5B276-1765-4DF5-9B08-507DC4ABD9DD](https://user-images.githubusercontent.com/27637025/172972796-caf1e7dc-86cd-4d23-ac15-c4c74ff39337.jpeg)

As of the last update you are asked if you’d like to allow tracking. My question was if there was anyway of disabling/unallowing tracking.

**Comment by qnblackcat** [comment]
You can disable it in YouTube's setting > General
