### ISSUE TITLE
Very slow downloads on uYouLocal

### ISSUE THREAD

**Issue by SpecialOperations** [qnblackcat/uYouPlus#2]
![IMG_0846](https://user-images.githubusercontent.com/30572191/141022798-020d0ade-9b0d-498e-8573-b71f7d12bb60.png)
I'm experiencing very slow downloads using uYouLocal, even on 480p. I used a USB-C to Ethernet adapter on a gigabit connection, so my own download speed is certainly not the issue. Is the download speed getting throttled somehow?

iPad Pro 11-inch (2018)
iOS 15.1 (19B74)

**Comment by qnblackcat** [comment]
YouTube slows down the download speed for some reasons. Nothing we can do about it.
