### ISSUE TITLE
Unable to download the .ipa file

### ISSUE THREAD

**Issue by theawegan** [qnblackcat/uYouPlus#201]
Facing this error when I try  to unpack the ipa

[BECEE9E9-7AE4-4BAD-9C38-23A048A3F637](https://user-images.githubusercontent.com/44398661/173079666-25400aaf-e84b-48f1-b037-97b5a8aea779.jpeg)

**Comment by qnblackcat** [comment]
Is that a new install of uYouPlus, or it‘s an update of uYouPlus?

**Comment by theawegan** [comment]
I had it previously on my phone and had the same error message trying to update it so I decided to re-install it but it still persists. (Forgot to mention I’m on iOS 16 b1 - iPhone 13PM.)

**Comment by theawegan** [comment]
Update: I am using the latest version (17.22.3_2.1)

**Comment by arichorn** [comment]
Wait how am I the only one able to install uYouPlus on iOS 16?
uYou works fine for me, the issues y’all having has to do with Developer Mode, Internet or some of the apple devices.

**Comment by Eugene1026** [comment]
have you found a fix for this issue? i cannot update the app using altstore, on ios 16 db 1 as well

**Comment by arichorn** [comment]
You can. Delete the Sideloaded YouTube App and then it should be solved when sideloadinf it again

**Comment by Eugene1026** [comment]
thats that worked for me

**Comment by arichorn** [comment]
No problem!

**Comment by qnblackcat** [comment]
@theawegan have you tried the solution above?

**Comment by MoroboshiKirari** [comment]
> 그것은 uYouPlus의 새로운 설치인가요, 아니면 uYouPlus의 업데이트인가요?  

나도 같은 문제가 있어.

> Is that a new install of uYouPlus, or it‘s an update of uYouPlus?

I'm having this same problem.
i'm south korean user.
To explain, the new version has been updated, so if I 'sideloading' in Altstore, the app itself will not work.
just infinity loading.
and i go to background and touch Altstore , Altsotre pop-up says 

"Altstore is not available"

The only solution is if the problem occurs
1. reinstall altstore ( quit altserver too , just restart)
2. uninstall uyouplus 
3. install new version uyouplus
4. then, it's worked.

**Comment by MoroboshiKirari** [comment]
> @theawegan have you tried the solution above?

So I thought it might be only Altstore's problem, but it wasn't.
Updates from other apps work well, but freezing occurs only when you update uyouplus, and altstore does not work.

**Comment by TheNerdyBlock** [comment]
I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install. 
![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)

**Comment by MoroboshiKirari** [comment]
> I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install. 
> 
> ![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)
> 
> 



yuu using Mac?

**Comment by TheNerdyBlock** [comment]
> > I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install.
> > ![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)
> 
> yuu using Mac?

No, Windows 11

**Comment by MoroboshiKirari** [comment]
> > > I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install.
> 
> > > ![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)
> 
> > 
> 
> > yuu using Mac?
> 
> 
> 
> No, Windows 11


I have a problem with the altstore mobile application. First of all, I don't think there is such an issue in Windows 11.

you try sideloading at mobile applications?

**Comment by TheNerdyBlock** [comment]
> > > > I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install.
> > 
> > 
> > > > ![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)
> > 
> > 
> > > 
> > 
> > 
> > > yuu using Mac?
> > 
> > 
> > No, Windows 11
> 
> I have a problem with the altstore mobile application. First of all, I don't think there is such an issue in Windows 11.
> 
> you try sideloading at mobile applications?

Altstore on mobile gets the same error as the guy above.

**Comment by MoroboshiKirari** [comment]
> Altstore on mobile gets the same error as the guy above, and other apps install fine.


One of the most typical issues I've experienced is downloading the 'uyouplus' update .ipa file from my phone and 'sideloading' through 'altstore', and it stops between 80% and 90%.

Have you ever experienced the same issue as me?

**Comment by MoroboshiKirari** [comment]
> > > > > I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install.
> 
> > > 
> 
> > > 
> 
> > > > > ![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > yuu using Mac?
> 
> > > 
> 
> > > 
> 
> > > No, Windows 11
> 
> > 
> 
> > I have a problem with the altstore mobile application. First of all, I don't think there is such an issue in Windows 11.
> 
> > 
> 
> > you try sideloading at mobile applications?
> 
> 
> 
> Altstore on mobile gets the same error as the guy above, and other apps install fine. 



I tried several times to experience the same issue as you, but failed.

i don't know why

**Comment by MoroboshiKirari** [comment]
Developers are instructing you to erase the 'uyouplus' app and do 'sideloading' again. But that is not a fundamental solution.

This is because it is not an issue that occurs in other apps, but only in uyouplus.

**Comment by TheNerdyBlock** [comment]
> > > > > > I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > ![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > yuu using Mac?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > No, Windows 11
> > 
> > 
> > > 
> > 
> > 
> > > I have a problem with the altstore mobile application. First of all, I don't think there is such an issue in Windows 11.
> > 
> > 
> > > 
> > 
> > 
> > > you try sideloading at mobile applications?
> > 
> > 
> > Altstore on mobile gets the same error as the guy above, and other apps install fine.
> 
> I tried several times to experience the same issue as you, but failed.
> 
> i don't know why

It fails right after saying installing... in Sideloadly, it then shows the error in the screenshot
![Screenshot 2022-06-30 014000](https://user-images.githubusercontent.com/48140896/176601101-f6d2ff4d-154d-4e73-89eb-9a67fd51d606.png)

**Comment by MoroboshiKirari** [comment]
It's not that the app doesn't work right away, but I'm frustrated because it suddenly happens without these issues.

**Comment by MoroboshiKirari** [comment]
> > > > > > > I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > ![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > yuu using Mac?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > No, Windows 11
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I have a problem with the altstore mobile application. First of all, I don't think there is such an issue in Windows 11.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > you try sideloading at mobile applications?
> 
> > > 
> 
> > > 
> 
> > > Altstore on mobile gets the same error as the guy above, and other apps install fine.
> 
> > 
> 
> > I tried several times to experience the same issue as you, but failed.
> 
> > 
> 
> > i don't know why
> 
> 
> 
> It fails right after saying installing... in Sideloadly, it then shows the error in the screenshot
> 
> ![Screenshot 2022-06-30 014000](https://user-images.githubusercontent.com/48140896/176601101-f6d2ff4d-154d-4e73-89eb-9a67fd51d606.png)
> 
> 
> 
> 

ah you using 'sideloadly' !
i'm using Altserver + Altstore
I'll consider using it next time.

What are its advantages over altstore?

**Comment by TheNerdyBlock** [comment]
> > > > > > > > I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > ![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > yuu using Mac?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > No, Windows 11
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > I have a problem with the altstore mobile application. First of all, I don't think there is such an issue in Windows 11.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > you try sideloading at mobile applications?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Altstore on mobile gets the same error as the guy above, and other apps install fine.
> > 
> > 
> > > 
> > 
> > 
> > > I tried several times to experience the same issue as you, but failed.
> > 
> > 
> > > 
> > 
> > 
> > > i don't know why
> > 
> > 
> > It fails right after saying installing... in Sideloadly, it then shows the error in the screenshot
> > ![Screenshot 2022-06-30 014000](https://user-images.githubusercontent.com/48140896/176601101-f6d2ff4d-154d-4e73-89eb-9a67fd51d606.png)
> 
> ah you using 'sideloadly' ! i'm using Altserver + Altstore I'll consider using it next time.
> 
> What are its advantages over altstore?

They are both very solid, I’m only using sideloadly because updating apps is easier, you don’t have to move the ipa onto the device. You can install the app directly.

**Comment by MoroboshiKirari** [comment]
> > > > > > > > > I have the same issue when updating the app on Altstore and Sideloadly. It only lets me sideload through a fresh install.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > > ![image](https://user-images.githubusercontent.com/48140896/176591464-8309fce9-2611-424b-8302-33d90fb588c4.png)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > yuu using Mac?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > No, Windows 11
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > I have a problem with the altstore mobile application. First of all, I don't think there is such an issue in Windows 11.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > you try sideloading at mobile applications?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Altstore on mobile gets the same error as the guy above, and other apps install fine.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I tried several times to experience the same issue as you, but failed.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > i don't know why
> 
> > > 
> 
> > > 
> 
> > > It fails right after saying installing... in Sideloadly, it then shows the error in the screenshot
> 
> > > ![Screenshot 2022-06-30 014000](https://user-images.githubusercontent.com/48140896/176601101-f6d2ff4d-154d-4e73-89eb-9a67fd51d606.png)
> 
> > 
> 
> > ah you using 'sideloadly' ! i'm using Altserver + Altstore I'll consider using it next time.
> 
> > 
> 
> > What are its advantages over altstore?
> 
> 
> 
> They are both very solid, I’m only using sideloadly because updating apps is easier, you don’t have to move the ipa onto the device. You can install the app directly. 

very cool,
i'll must try nexttime when updated uyouplus new version.
then, i'll try same thing , and comment to you

**Comment by qnblackcat** [comment]
Here is the solution. You only need to do it once. The issue should not happen anymore: 
1. Uninstall AltStore & uYouPlus
2. Reinstall AltStore & uYouPlus

I‘ll add this to the FAQ page

**Comment by MoroboshiKirari** [comment]
hi, new version updated 

i try new version sideloadly ,
it's not problem, normally worked.
