### ISSUE TITLE
[Suggestion] Remove YouTube featured Ads on home tab. 

### ISSUE THREAD

**Issue by TheNerdyBlock** [qnblackcat/uYouPlus#207]
Remove annoying Ads from home screen. 
![IMG_0080](https://user-images.githubusercontent.com/48140896/173270396-4b058e79-2869-4df2-95a2-145029d78d5a.PNG)

**Comment by arichorn** [comment]
This most likely has a chance of uYouPlus not being able to remove this.
I think the featured ads are server-side and most likely be impossible to permanently hide them.
But if there are possibilities then the developer of this is smart.

**Comment by qnblackcat** [comment]
A workaround has been secretly added since [v17.24.4-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.24.4-2.1) to hide this kind of ads. Have you still encounter it?

**Comment by TheNerdyBlock** [comment]
I’m pretty sure it’s fixed, thank you!

**Comment by qnblackcat** [comment]
I’ll mark this as complete here. Lmk if you see the ads again
