### ISSUE TITLE
[Enhancement] iOS 16 support

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#209]
The latest ipa version worked just fine with ios 16 for more than a week and now suddenly crashes out of nowhere.

Re-sideloading didn't work. Reinstalling (deleting app) also didn't work.

**Comment by arichorn** [comment]
> The latest ipa version worked just fine with ios 16 for more than a week and now suddenly crashes out of nowhere.
> 
> Re-sideloading didn't work. Reinstalling (deleting app) also didn't work.

Actually this happened to me just like how yours happened, I had iOS 16 installed over a week and then it stopped working.
