### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by bolognayballs** [qnblackcat/uYouPlus#210]
Uyou won’t download video stuck on 0% 
iOS 14.4.2 sideloaded 
![3C2AA673-F53F-40AD-8230-C50017690A8C](https://user-images.githubusercontent.com/69094717/173462421-6f7b8ae5-f5b2-4f8d-9431-c1de9b8b7e7c.png)
 with http://signumsign.me/

uyou version 2.1

**Comment by qnblackcat** [comment]
Does the issue persist?

**Comment by qnblackcat** [comment]
Closed due to inactive. I assume this and #238 is the same issue.

**Comment by bolognayballs** [comment]
It’s not the same issue I use a vip AppStore service not altstore 


Sent from Yahoo Mail for iPhone


On Wednesday, June 29, 2022, 10:49 PM, Nguyễn Đạt ***@***.***> wrote:




Closed due to inactive. I assume this and #238 is the same issue.
