### ISSUE TITLE
[Enchantment] Option to change Youtube language within the app

### ISSUE THREAD

**Issue by ShadowRoi** [qnblackcat/uYouPlus#211]
I just realized that in order to change the app language you have to change the language in your entire phone. I remember that in the past you could change it just for the app i think.

Is there a way we can bring back this feature?

**Comment by qnblackcat** [comment]
No. You can set the app’s language individually. Go to iOS’s setting > YouTube > Language

**Comment by ShadowRoi** [comment]
@qnblackcat I wanted to debug it. So in my phone French play as they should but the greek translation doesn't. I checked the code and i can't find something that occurs to this as i checked the other translations as well. Any ideas?

**Comment by qnblackcat** [comment]
So the ISO name of Greek is `el`according to https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes
