### ISSUE TITLE
[Questions]How should I update app?

### ISSUE THREAD

**Issue by clc0321** [qnblackcat/uYouPlus#214]
I have read the FAQ
I tried to update uYouPlus using the same method after new installation, but the Altstore keeps getting various errors. So before each update should I uninstall the original version and reinstall it?
###

**Comment by Aransh** [comment]
Same issue on sideloadly, something is broken... Working fine with other ipas so I don't think this is server-sided

**Comment by qnblackcat** [comment]
there is a reason why i made the issue temple. If you don’t provide any info then i have no idea what‘s going on

**Comment by ShadowRoi** [comment]
In my case i did update uYouPlus using AltStore just fine using iOS 15.4 to the latest uYouPlus 17.23.6_2.1 without any issues. In my case all i do is download the updated IPA and install it through AltStore which will **overwrite the old uYouPlus to the new one** without resetting the Settings or removing the downloaded Videos/Audios at uYou

**Comment by clc0321** [comment]
Thanks guys, I think the installation process just terminated unexpectedly.
