### ISSUE TITLE
[Bug] Dislike still visible

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#22]
If you disable the dislike button under the video it's still visible.

Maybe you could add the functionality to hide the like buttons and the other buttons too?

**Comment by ErSpieltHD** [comment]
I think it's because of the updates to the dislike button (they hid the counter etc) why this is no longer working

**Comment by qnblackcat** [comment]
Duplicate of https://github.com/MiRO92/uYou-for-YouTube/issues/47
