### ISSUE TITLE
Pip randomly stops working

### ISSUE THREAD

**Issue by JWick7796** [qnblackcat/uYouPlus#220]
The YouPip is a hit and a miss, it works sometimes and doesn't sometimes. Most of the times, app restart and then enabling pip button and then disabling it in the youPip menu fixes it. 

PFB screen recording
https://drive.google.com/file/d/1nsMYLvmqJi8cGlLu8DG_jNlYPPlUc5KZ/view?usp=drivesdk

uYou+ is perfect and I don't want to go back to cercube garbage. Please look into this

iPhone: 13 Pro Max
iOS: 15.5
Version: 17.22.3

**Comment by qnblackcat** [comment]
Does this work? https://github.com/qnblackcat/uYouPlus/issues/97#issuecomment-1115830170

**Comment by qnblackcat** [comment]
Closed due to inactive
