### ISSUE TITLE
[Bug] Mentioning In comments is Black

### ISSUE THREAD

**Issue by ShadowRoi** [qnblackcat/uYouPlus#223]
### Device info
- iOS/iPadOS version: iOS 15.4
- Device model: IPhone 13 Pro
- Sideload tool: AltStore
- Version of uYouPlus: 17.23.6 - 2.1

### Describe the bug
Whenever in comments I am replying someone the mentioning is straight up completely black when typing. After I post the comment then I can see the mention just fine.

### How to reproduce the bug
Click to someone comment and press Reply to reply to them 
![PNG image](https://user-images.githubusercontent.com/105967373/173893801-abb1fde5-dac2-4b42-a241-25b34d8e739a.png)

**Comment by qnblackcat** [comment]
This is a very weird bug of YouTube? It won’t happen if a video is playing in the miniplayer.

**Comment by ShadowRoi** [comment]
@qnblackcat Now i see that if i go to youtube videos and try to reply to someone it doesn't happen. If i go to my notifications that someone had replied to me and go to reply to comments from there then it does happen. That's so weird. Does this happen to you too?

**Comment by qnblackcat** [comment]
As I said before, this bug only happens if no video is playing, and it’s most likely an issue with YouTube itself. 

Enable Fake YouTube Version in YouPiP’s setting should fix it
