### ISSUE TITLE
[Bug] Auto Play on playlists doesnt work

### ISSUE THREAD

**Issue by JWick7796** [qnblackcat/uYouPlus#225]
### Device info
- iOS/iPadOS version:  15.5
- Device model: iPhone 13 pro max
- Sideload tool: Signed with signTunes
- Version of uYouPlus: 17.23.6

### Describe the bug
AutoPlay doesn't work on playlists when app is not in foreground.
Playing normal videos will autoplay to the next video but when playing a playlist, the player pauses after every song unless the app is in foreground.

### How to reproduce the bug
pick any playlist and play a song and turn off screen. Song will pause after song completes.

**Comment by qnblackcat** [comment]
I can’t reproduce the issue

**Comment by arichorn** [comment]
Either a uYou issue itself or YouTube somewhat broke it

**Comment by qnblackcat** [comment]
Closed due to inactive. Plus I can't *fix* something that is still working fine.
