### ISSUE TITLE
[Bug] Unable to download videos

### ISSUE THREAD

**Issue by IcySnex** [qnblackcat/uYouPlus#226]
### Device info
- iOS/iPadOS version: 15.5
- Device model: iPhone 13 Pro
- Sideload tool: Scarlet
- Version of uYouPlus: v17.23.6-2.1-F2

### Describe the bug
Trying to download a video/audio will result in an error.
Error message: „Error: 200 - ERR: Unable to move file from file:///var/mobile/Library/Caches… to file:///var/mobile/Containers/Data… could not be moved because you do not have the required permissions…“

### How to reproduce the bug
Try to download any video/audio. It will download normally but in the end it fails.
![5640E857-4631-4C0A-88BF-07E141766750](https://user-images.githubusercontent.com/81762750/174273559-3fa2b8ee-4bfc-447c-b106-31ea7fa2e965.png)

### Additional context:
 Also just wanted to say: This app is awesome, great work. This is the best YouTube mod app for iOS. There are a few more minor bugs like the Buttons under videos dont change but thats not a big deal. Thanks for making it!

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
