### ISSUE TITLE
video download [Questions]

### ISSUE THREAD

**Issue by bymcs** [qnblackcat/uYouPlus#229]
hello i cant download video
error code : error 200
uYouPlus version : v17.23.6-2.1-F2 and v17.23.6-2.1
iOS : 15.5
Signing service : Signtunes
Error picture : 

![IMG_0794](https://user-images.githubusercontent.com/56798318/174478872-f277930c-81c8-4695-9f17-a91fc72070f6.jpg)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
