### ISSUE TITLE
[Bug] Video Quality doesn't change

### ISSUE THREAD

**Issue by eIiot** [qnblackcat/uYouPlus#231]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 15.5
- Device model: iPhone 24 Pro
- Sideload tool: AltStore
- Version of uYouPlus: 17.23.6

### Describe the bug
Video Quality doesn't change

### How to reproduce the bug
Although the video quality selector may say 144p, the video quality is always high, I would suspect ~1080p?

![image](https://user-images.githubusercontent.com/39346975/174523535-f19997ac-95a3-48b1-8a83-319bb9d865d1.jpeg)
![image](https://user-images.githubusercontent.com/39346975/174523543-01ea1c79-662f-4fc0-ad5c-92fd18be1687.jpeg)

**Comment by qnblackcat** [comment]
1. To show exactly the quality of the video: go to YouTube‘s setting > General > enable Stats for Nerds, then show the Stats for Nerds popup in the video player

2. Did you enable Legacy PiP?

**Comment by Casio7380** [comment]
> * To show exactly the quality of the video: go to YouTube‘s setting > General > enable Stats for Nerds, then show the Stats for Nerds popup in the video player
> * Did you enable Legacy PiP?

I have the same problem ( It’s not changing automatically to 1080p) : 
![83FB1A17-60A9-4664-8863-7536AD1A262E](https://user-images.githubusercontent.com/101881483/174675559-bd3da3b0-f82c-4f54-8427-8700700839bd.jpeg)
![6BCDE618-D94E-4563-B07D-1F918511AE50](https://user-images.githubusercontent.com/101881483/174675566-414a43f6-fa17-4818-aab1-f81159a16413.jpeg)
![663F55D0-2C28-4D29-9165-31748575D95B](https://user-images.githubusercontent.com/101881483/174675569-bc836db5-53c0-4a13-a912-43dbe5cb110b.jpeg)

**Comment by eIiot** [comment]
Vp9 is disabled

**Comment by Casio7380** [comment]
> disable VP9 Codec. That’s the thing that’s causing it

Still not working :/

**Comment by arichorn** [comment]
Then I don’t know, it might be a YouTube Bug because I don’t know which tweak it’s causing it to break

**Comment by Casio7380** [comment]
> Then I don’t know, it might be a YouTube Bug because I don’t know which tweak it’s causing it to break

It’s not a YouTube bug. On the normal YouTube(from the App Store), I don’t have this problem.

**Comment by qnblackcat** [comment]
Please answer my question. Did you enable Legacy PiP? I wouldn‘t recommend you using Legacy PiP

**Comment by Casio7380** [comment]
> Please answer my question. Did you enable Legacy PiP? I wouldn‘t recommend you using Legacy PiP
I turn it off and now it’s working. Thanks.

**Comment by Casio7380** [comment]
> Please answer my question. Did you enable Legacy PiP? I wouldn‘t recommend you using Legacy PiP

I turn it off and now it’s working. Thanks.

**Comment by qnblackcat** [comment]
@eIiot Any update?

**Comment by arichorn** [comment]
Also there is another issue with video quality, the video quality or three dot options in the video player will be invisible or hidden. and this issue happens if you ever change the text colors on uYouPlus. Just an alternative issue that’s similar to this.

**Comment by eIiot** [comment]
> @eIiot Any update?

Yeah, it fixed itself when I enabled legacy PiP... not sure why
