### ISSUE TITLE
[Enhancement] Remove YouTube Auto adding video to playlist 

### ISSUE THREAD

**Issue by ShadowRoi** [qnblackcat/uYouPlus#232]
When you have more than 1 playlist created where you have videos from other creators like songs and other stuff for instance. Whenever I click to add a video to playlist it doesn’t prompt me to choose in which playlist I want it but rather automatically adds it to the most recent one I think?

Can we make it so it always prompts us to choose where to add instead for being automatic?

**Comment by qnblackcat** [comment]
Instead of clicking on the Save button, should hold it, which will show the **Save video to...**  popup
