### ISSUE TITLE
[Suggestion] Add YTNoShorts

### ISSUE THREAD

**Issue by lhvy** [qnblackcat/uYouPlus#233]
### Device info
- iOS/iPadOS version: iOS 16.0 Beta 1
- Device model: iPhone 11 Pro Max
- Sideload tool: Sideloadly
- Version of uYouPlus: v17.23.6-2.1-F2

### Describe the suggestion

I noticed your other repo, CercubePlus credited [YTNoShorts](https://github.com/MiRO92/YTNoShorts), and thought it would be good addition to uYouPlus too. Perhaps it could be added if you were happy with this suggestion?

**Comment by qnblackcat** [comment]
YTNoshorts is already a built-in feature of uYou. Just go to uYou‘s setting > Other Settings > Remove Shorts Section in YT Home
