### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by galaxy4627** [qnblackcat/uYouPlus#236]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️
Yes, did not help

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 15.5
- Device model: iPhone 13 Pro (iPhone14,2)
- Sideload tool (Ex: AltStore, Sideloadly...) Signulous
- Version of uYouPlus: 

### Describe the bug

So, downloading videos use to work fine however now when using signulous to sign uYou+ I am no longer able to download videos because I keep receiving  "ERR 200: Unable to move file from file."
### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

Use signulous and try and download videos
### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by danielnma** [comment]
The FAQ is no longer correct. I used an Apple Development Certificate (I have no Apple Deployment Certificates on this machine), and I still have the error once its signed and installed.
