### ISSUE TITLE
[Bug] uYou download: filesystem permission error when using Apple Development Certificate to sign IPA (error 200)

### ISSUE THREAD

**Issue by danielnma** [qnblackcat/uYouPlus#238]
### Device info
- Devices: iPad 2020 on iPadOS 15.1.1 and iPhone X on iOS 15.5
- uYouPlus: 16.42.3_2.1
- Xcode with iOS App Signer

### Describe the bug
The bug is as described in the FAQ: "Error 200: Unable to move a file from…" ([link](https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-uyou-download-is-not-working-error-200-unable-to-move-a-file-from))

### How to reproduce the bug
Resign the IPA using iOS App Signer and install:
1. Choose a valid and current Apple Development Certificate 
2. Use a wildcard iOS Team Provisioning Profile
3. Do not change the Application ID, Display Name, or version
4. Install the resigned IPA onto any registered iPadOS/iOS device with Xcode's device manager
5. Experience the bug

### Additional context:
The FAQ suggests this is because the user used an Apple Distribution Certificate instead of an Apple Development Certificate. This is not the case as can be seen in the steps to reproduce the bug. I am a current Apple Developer.

**Comment by qnblackcat** [comment]
That’s interesting 🤔 can you try using the apple development certificate with an explicit profile?

**Comment by hero3210** [comment]
the same issue (Error 200) appears when using dev cert with SignTools.

it does not happen when using uYou on a jailbroken device.

**Comment by chupit0** [comment]
i get the same 200 error when trying to download any audio or video
signing app with signum.

**Comment by Akhenaten121** [comment]
Will there ever be a fix for this download error 200 problem?

**Comment by moh-ter** [comment]
Strangely, signing the app with Sideloadly fixes the download issue (Local Anisette mode).

so, to sum up:
- Downloading works on jailbroken devices with the official tweak. ✅
- Downloading does not work with distribution certificates using SignTools.
- Downloading does not work with development certificates & wildcard provisioning profile using iOS App Signer.
- Downloading works with Normal accounts using Anisette in Sideloadly. ✅
- Downloading works with Developer accounts using Anisette in Sideloadly. ✅
- Downloading works with TrollStore. ✅

**Comment by moh-ter** [comment]
> That’s interesting 🤔 can you try using the apple development certificate with an explicit profile?

you were right, explicit profiles work.

**Comment by Aholicknight** [comment]
Having the same problem with ESign

**Comment by Aholicknight** [comment]
> you were right, explicit profiles work.

Do you use Signulous? I have Signulous to sign IPAs and have no idea how to export or generate a explicit profile

**Comment by Mikasa-san** [comment]
Is there any fix ?

**Comment by mapeles** [comment]
I believe this issue is also related to #335.

**Comment by elisaado** [comment]
Using an explicit profile works for me as well, that does however replace any app already installed with that profile which makes it an unfavourable option.

**Comment by understaff** [comment]
Hello, I have a question. Is it possible to change the download location or the location when accessing the downloaded file? In what line of code can I see this?
Actually it is possible to fix notifications and downloads with a developer account but you have to change the location when you want to access the bundle uyou @qnblackcat ?

**Comment by qnblackcat** [comment]
> Hello, I have a question. Is it possible to change the download location or the location when accessing the downloaded file? In what line of code can I see this?
> Actually it is possible to fix notifications and downloads with a developer account but you have to change the location when you want to access the bundle uyou @qnblackcat ?

Not possible. Please ask the dev of uYou instead

**Comment by abbasmusawis** [comment]
Hi
Anyone please send a video showing how to create a compatible signing certificate using apple developer account?
I tried but downloading still not working 
I couldn't find find any good videos on youtube either

**Comment by qnblackcat** [comment]
Fixed in [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)

**Comment by understaff** [comment]
> Fixed in [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)

oh it's true brother how did you fix it? wow now i have fully functional notifications + downloads you are great.  🥇
