### ISSUE TITLE
[Bug] App dors not appear in entertainment folder in App Library

### ISSUE THREAD

**Issue by qfoxb** [qnblackcat/uYouPlus#242]
### Device info
- iOS/iPadOS version: 15.5
- Device model: iPhone 13
- Sideload tool:Sideloadly
- Version of uYouPlus: v17.24.4-2.1

### Describe the bug
App does not appear in "Entertainment" folder in the App Library unlike the Stock YouTube app

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
- Uninstall stock YouTube app
- Install uYouPlus
- Open App Library
- App is not in Entertainment category

**Comment by qnblackcat** [comment]
This problem is a limitation of sideloading, and uYou+ has nothing to do with it. 
For now, try to use IPAEdit. The tool has an option to edit the app’s category when sideloading.
https://github.com/ethandgoodhart/IPAEdit
