### ISSUE TITLE
[Bug] The download function "uYouLocal" does not work well

### ISSUE THREAD

**Issue by nish4464** [qnblackcat/uYouPlus#247]
### Device info
- iOS/iPadOS version: 15.5
- Device model: iPhone 7
- Sideload tool: AltStore
- Version of uYouPlus: v17.15.1～

### Describe the bug
- If you press the uYouLocal button displayed on the floating UI of the video playback, it will be forcibly terminated.
- I confirmed that it cannot be used even if the version is forged to 16.46.5.
- I was able to use uYouPlus up to 17.14.2 without any problems.

### How to reproduce the bug
Load any video
https://user-images.githubusercontent.com/108281977/175959514-2d18a0d0-1d41-42e6-bec9-ac5c9ce37876.MOV

### Crash log (if possible)
Load the crash log from OneDrive
https://1drv.ms/u/s!AvmEECIQxxKNjTuTyEFOqxQuD7VI

### Additional context:
- I'm Japanese and I'm applying Google Translate, so there's something wrong with it.

**Comment by qnblackcat** [comment]
This issue has been fixed recently. Just wait until the next release

**Comment by qnblackcat** [comment]
@nish4464 try [v17.25.1-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.25.1-2.1)

**Comment by qnblackcat** [comment]
Please re-open if issue persists
