### ISSUE TITLE
[Enhancement] Improve fullscreen controls on the ipad 

### ISSUE THREAD

**Issue by heronemis** [qnblackcat/uYouPlus#25]
First of all, thank you for maintaining this project! YouTube is unusable without it.

I have some thoughts about entering and leaving fullscreen view on the iPad:

- On iPhone, it is possible to slider up and down to enter and leave fullscreen. I miss this on the iPad as well. I know it is possible to pinch, but that rarely works for me.
- The little square for fullscreen is so small its hard to hit. Is it possible to make it larger?
- I use uYouPlus on an iPad with an attached keyboard and miss having a keyboard shortcut for fullscreen. Maybe F?

Thanks!

**Comment by qnblackcat** [comment]
Perhaps you want [YTAutoFullScreen](https://poomsmart.github.io/repo/depictions/ytautofullscreen.html) by Poomsmart?

**Comment by qnblackcat** [comment]
Close due to inactive.
