### ISSUE TITLE
[Bug] Unable to play videos that are inappropriate and offensive despite restriction mode off.

### ISSUE THREAD

**Issue by 776f6c6f6e67** [qnblackcat/uYouPlus#250]
- iOS/iPadOS version:  IOS 15.5
- Device model: iPhone 11 Pro Max
- AltStore
- Version of uYouPlus:  all

Example: https://www.youtube.com/watch?v=pfw2AVqcne0

On browser mode there is an option to click "I UNDERSTAND AND WISH TO PROCEED", this option is not showing up on uYouPlus, there is no other way to play the video.

**Comment by qnblackcat** [comment]
Turn off **Disable Age Restriction** in uYou's setting > Other settings

**Comment by 776f6c6f6e67** [comment]
Works now, thanks!
