### ISSUE TITLE
[Bug] new version sideload freezing issues 

### ISSUE THREAD

**Issue by MoroboshiKirari** [qnblackcat/uYouPlus#255]
### Device info
- iOS/iPadOS version: iOS16 Developer Beta 2
- Device model: iPhone 13 pro max
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore
- Version of uYouPlus: 17.25.1

### Describe the bug

i'm using Translator,  Please understand that the context is not smooth. sorry about that 🙏🙏

(I am aware that there are risks with installing beta softwares and I am not trying to whine here but just trying to inform that this is an issue.)

To explain, the new version has been updated, so if I 'sideloading' in Altstore, the app will not work.
just infinity loading and freezing.
so i go to background( or quit Altstore) and touch Altstore , Altstore pop-up says

"Altstore is not available" >> not work , only ways reinstall Altstore.

The only solution is if the problem occurs

1.reinstall altstore ( quit altserver too , and restart)
2.uninstall uyouplus previous version 
3.install new version uyouplus
4. sideloading worked, altstore worked

So I thought it might be only Altstore's problem, but it wasn't.
Updates from other apps work well, but freezing occurs only when update uyouplus, and altstore does not work.

**Comment by qnblackcat** [comment]
1. Uninstall AltStore & uYouPlus
2. Reinstall AltStore & latest version of uYouPlus
3. The issue should not happen anymore

Or you can just use Sideloadly instead of AltStore.

**Comment by MoroboshiKirari** [comment]
> 1. Uninstall AltStore & uYouPlus
> 2. Reinstall AltStore & latest version of uYouPlus
> 3. The issue should not happen anymore
> 
> Or you can just use Sideloadly instead of AltStore.

Do you think it's just an OS compatibility issue?

**Comment by qnblackcat** [comment]
No. I don't think so

**Comment by MoroboshiKirari** [comment]
> No. I don't think so

Have you ever seen such an issue?

**Comment by qnblackcat** [comment]
No. I haven‘t. But I‘m pretty sure it wont happen anymore if you follow my instruction

**Comment by MoroboshiKirari** [comment]
> No. I haven‘t. But I‘m pretty sure it wont happen anymore if you follow my instruction

You're right.  I think that the solution is effective but not a fundamental solution. 😭

**Comment by MoroboshiKirari** [comment]
> No. I haven‘t. But I‘m pretty sure it wont happen anymore if you follow my instruction

There is also a possibility of OS and application compatibility, so it seems necessary to look at it slowly over time.

**Comment by MoroboshiKirari** [comment]
> No. I haven‘t. But I‘m pretty sure it wont happen anymore if you follow my instruction

It may not be a big problem right now, but I wrote it for users who are struggling with the same issue as me.
