### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by guacaplushy** [qnblackcat/uYouPlus#256]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###
I'm getting ads in YouTube shorts on 17.23.6... is this a new feature or is this a bug?

**Comment by qnblackcat** [comment]
strange. Any screenshot?

**Comment by qnblackcat** [comment]
Anyway, this looks like a bug. You should open a new issue and complete the bug [template](https://github.com/qnblackcat/uYouPlus/issues/new?assignees=&labels=bug&template=bug.md&title=%5BBug%5D)
