### ISSUE TITLE
[Questions] Is anyone else experiencing this?

### ISSUE THREAD

**Issue by Hazem42** [qnblackcat/uYouPlus#257]
I was watching a video in pip mode while scrolling through Twitter and my phone heated up so bad. Is this a bug or what?

#Device info
- IPhone 12 Pro Max 
- IOS 15.5

**Comment by qnblackcat** [comment]
try to disable VP9 codec. That's the only thing I can tell you

**Comment by Hazem42** [comment]
> try to disable VP9 codec. That's the only thing I can tell you

I don't have it on, but I restarted my phone and it seems to be fixed now!🤷‍♂️
