### ISSUE TITLE
[uYouPlus Code Error] Hide Promotion Card - traitCollection

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#258]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

- Version of uYouPlus: 17.25.1

### Describe the error
I’m just here to tell you about the traitCollection not working. I’m not the guy who caused this but at least you know there was an issue in the uYouPlus.xm code

### How to reproduce the error
![8F26DFBA-A4FD-4411-A49A-6613750ABED1](https://user-images.githubusercontent.com/78001398/176629507-3268cb33-a2e3-4815-af5a-94d5cf11138c.jpeg)

### Additional context:
 Surprisingly I told you the error and I’m sorry for not pull requesting since I already have my modified stuff in the code

**Comment by qnblackcat** [comment]
OK
