### ISSUE TITLE
uYouPlus安装问题

### ISSUE THREAD

**Issue by GD2021** [qnblackcat/uYouPlus#26]
uYouPlus用gbox自签不能用，在电脑上用Sideloadly签就可以，为什么呢？

**Comment by qnblackcat** [comment]
Eww. What?? Please use English

**Comment by GD2021** [comment]
UYouPlus can't use gbox self-sign. Just use Sideloadly on the computer. Why?

**Comment by qnblackcat** [comment]
I don‘t know what is Gbox, sounds like a signing service? 
The IPA works with Sideloadly but not Gbox. That means something is wrong with Gbox 🤷‍♂️ Nothing wrong with the iPA itself

**Comment by GD2021** [comment]
thanks！
