### ISSUE TITLE
[Bug] Ads in Shorts

### ISSUE THREAD

**Issue by guacaplushy** [qnblackcat/uYouPlus#263]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0 beta 2
- Device model: iPhone SE 2020
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore
- Version of uYouPlus: 17.23.6

### Describe the bug
Ads in browsing shorts

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Scroll through the browse shorts thing.
Video: https://user-images.githubusercontent.com/56302322/176956181-79334166-321f-42d3-8aa0-32ff6109ae52.MOV

### Crash log (if possible)
_(The crash log can be found in the Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:
 
Started happening recently. The ads appear with nothing but the ad itself.

**Comment by WoodpeckerBaby** [comment]
I also noticed many ads when searching in the youtube app. Is this expected or is this a bug?
