### ISSUE TITLE
[Bug] Missing History button

### ISSUE THREAD

**Issue by Br0ck-Butl3r** [qnblackcat/uYouPlus#264]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: IOS 15.5
- Device model: Iphone 11
- Sideload tool (Ex: AltStore, Sideloadly...): AltStore
- Version of uYouPlus: 1.4

### Describe the bug
Due to what I can only assume YouTube updating their UI on mobile, I can't access my youtube history.  In the my library menu, not only is there no history button, but where the official youtube app has text in the upper right corner saying "view all", there is no such text on uYou plus

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by qnblackcat** [comment]
Please update to the latest version of uYouPlus

**Comment by qnblackcat** [comment]
Any news?

**Comment by qnblackcat** [comment]
Closed due to inactive
