### ISSUE TITLE
[Request] When playing a single video in a loop.

### ISSUE THREAD

**Issue by nish4464** [qnblackcat/uYouPlus#265]
When playing a single video in a loop, the related video tab, video title, and channel description are automatically displayed when the video ends.
Since the loop is set, the video will be played from the beginning, but the related video tab, video title, and channel description will not be hidden...

Is it possible to prevent the related videos, video titles, and channel description from being automatically displayed only when the video is played in a loop?

See a video.
https://user-images.githubusercontent.com/108281977/176984523-15428bd3-1aa9-411f-b8ac-dc94f3bb4bd0.MOV

**Comment by qnblackcat** [comment]
Did it happen with official YouTube from AppStore?

**Comment by nish4464** [comment]
Yes, it also happens with the official youtube app.

**Comment by nish4464** [comment]
> Did it happen with official YouTube from AppStore?

Yes, it also happens with the official youtube app.

**Comment by qnblackcat** [comment]
> Yes, it also happens with the official YouTube app.

Better wait until YouTube fixes it then :/

**Comment by qnblackcat** [comment]
Closed because this is obv an issue of the YouTube app itself.
