### ISSUE TITLE
Do we have to jailbreak in order to install this!?

### ISSUE THREAD

**Issue by creativrss** [qnblackcat/uYouPlus#27]
**Device info:**
- iOS/iPadOS version: 15
- Device model: iPhone 7
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: Latest

**Describe the bug:**
- 

**How to reproduce the bug:**
_(Please attach videos or screenshots if possible)_

**Additional context:**
_(Add any other context about the problem here)_

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus#faq
