### ISSUE TITLE
[Bug] “Hide Explore Tab” doesn’t work on iPhone

### ISSUE THREAD

**Issue by economics-nuri** [qnblackcat/uYouPlus#273]
![AF51E5AB-C43A-493A-A69E-F0ED549E5049](https://user-images.githubusercontent.com/108129106/177939846-58ab49ea-9848-4f0a-886d-46e3cf5e3b18.jpeg)
![7DC17739-E0AB-4041-8979-67993BBD7A94](https://user-images.githubusercontent.com/108129106/177939860-7bd5ed04-7ebc-4ff0-9cb9-35cbd9f5dd4a.jpeg)

### Device info
- iOS/iPadOS version: 15.5
- Device model: iPhone 13 Pro
- Sideload tool (Ex: AltStore, Sideloadly...): AltStore
- Version of uYouPlus: 17.25.1

### Describe the bug
“Hide Explore Tab” doesn’t work on iPhone, but it works on iPad.

**Comment by economics-nuri** [comment]
![0DFA9D30-5836-4B63-8382-198B8C4C5DC0](https://user-images.githubusercontent.com/108129106/177996196-d0a354dc-953b-4dc7-bcc2-b79b7a69f9a1.jpeg)
Sorry, that option is always off.
> I‘m pretty sure the Explore tab doesn‘t even exists on iPhone, unless you enabled **Replace Shorts tab with Explore tab (YTReExplore)** in uYouPlus’s setting. Try to disable that option, and turn on **Hide Shorts Tab** in uYou’s setting

**Comment by qnblackcat** [comment]
I‘m sorry. What exactly is your problem? Of course **Hide Explore Tab** doesn’t work on iPhone since Explore Tab doesn't exist on iPhone.

Also, I can see there is no Explore Tab in your picture above?!

**Comment by economics-nuri** [comment]
> I‘m sorry. What exactly is your problem? Of course **Hide Explore Tab** doesn’t work on iPhone since Explore Tab doesn't exist on iPhone.
> 
> Also, I can see there is no Explore Tab in your picture above?!

I mean, Explore tab always exists on iPhone. “Hide Explore tab“ can’t hide Explore tab and I’ve never turned on “Replace Shorts tab with Explore tab”.

**Comment by economics-nuri** [comment]
![3BE850FB-15C7-407E-A32C-F4280C800590](https://user-images.githubusercontent.com/108129106/177998995-e25c944c-cb6b-459e-8daa-52202188f971.jpeg)

**Comment by qnblackcat** [comment]
Sorry! **Hide Explore Tab** means hiding the Explore Tab in the Pivot bar on iPad.
