### ISSUE TITLE
[Bug]Cannot install 17.26.2_2.1 on iOS 16 B3v2

### ISSUE THREAD

**Issue by pelegs29** [qnblackcat/uYouPlus#278]
### Device info
- iOS version: iOS 16 B3v2 (20A5312j)
- Device model: iPhone 12
- Sideload tool : AltStore
- Version of uYouPlus: 17.26.2_2.1

### Description of the bug
Cannot install the lastest version of uYou+ on the latest beta of iOS 16,
tried : 
- Reinstalling AltStore and try again
- Sign the app on Wifi, on Cable, using the new sideload method of AltServer (drag ipa)

the app almost finishes installing but stuck at the end. altstore gets stuck and only force close stops it.
altstore supports the latest iOS 16 B3v2.

on my other device (iPad Pro running iOS 15.5) updated with no problem .
version 17.25.1_2.1 currently works and run on the latest beta.

**Comment by qnblackcat** [comment]
Doesn‘t sound like an issue of uYouPlus. Perhaps something is wrong with AltStore. Maybe try to install AltStore & uYouPlus later?

**Comment by levochkaa** [comment]
> Only after completely removing uYou+ and restarting my device I've successfully installed the latest version.

Had the same issue, helped, thanks! Maybe @qnblackcat put it in README somewhere? For people, that gonna face the same issue. I found this one only on the third time, 'cause I was scrolling open issues and this one is closed already.

Thought, that I'm going to use a web version😅

**Comment by MarioMastr** [comment]
> > Doesn‘t sound like an issue of uYouPlus. Perhaps something is wrong with AltStore. Maybe try to install AltStore & uYouPlus later? 
> 
> Only after completely removing uYou+ and restarting my device I've successfully installed the latest version.

Thanks soooo much for the fix ❤️
