### ISSUE TITLE
[Questions] How do I disable the overlay like [ - |1.00x| + ] and the other buttons?

### ISSUE THREAD

**Issue by UnrealThingTriesCode** [qnblackcat/uYouPlus#280]
it would have a better place in the menu  with like, share dislike etc

**Comment by Squareheron942** [comment]
It’s not very intuitive, but what you need to do is not go into the settings, but rather to the uYou page on the bottom right, and then on the top right you will find a different set of settings, including the extra set of overlay icons. One issue I have noticed is that 2 of the buttons will return on their own.

**Comment by qnblackcat** [comment]
Go to uYou‘s setting (bottom right) > Video controls overlay > disable which one you don’t need

**Comment by qnblackcat** [comment]
> that 2 of the buttons will return on their own.

What are those 2 buttons I wonder?

**Comment by UnrealThingTriesCode** [comment]
Ahh, thanks guys! Cheers
