### ISSUE TITLE
uYouPlus Incoming call bug.

### ISSUE THREAD

**Issue by iamzishankk** [qnblackcat/uYouPlus#282]
While watching a Youtube video, whenever I receive a call from the banner call, re springs my device. 10 to 15 times happed to me. 

Please look into the matter. 

I’m using latest version of uYouPlus.

I’m on iOS 16 beta 3. 
Device: iPhone XR

**Comment by qnblackcat** [comment]
Please open a new issue (BUG) and complete the template.
