### ISSUE TITLE
[Bug] uYouPlus Incoming call device respring issue. 

### ISSUE THREAD

**Issue by iamzishankk** [qnblackcat/uYouPlus#283]
### Device info
- iOS/iPadOS version: iOS 16 Dev Beta 3 (20A5312j)
- Device model: iPhone XR
- Sideload tool (AltStore)
- Version of uYouPlus: 17.24.4_2.1

### Describe the bug

While watching a Youtube video, whenever I receive a call from the banner call, re springs my device. 10 to 15 times happened to me.

Please look into the matter.

**Comment by qnblackcat** [comment]
Does the issue still occur?

**Comment by iamzishankk** [comment]
> Does the issue still occur?

Now working fine.. thanks 😊

**Comment by iamzishankk** [comment]
You can close it now

**Comment by qnblackcat** [comment]
I think it's more like an issue of iOS. But anyway
