### ISSUE TITLE
Pls replace the youtube logo with premium logo

### ISSUE THREAD

**Issue by sparsh1220** [qnblackcat/uYouPlus#284]
Hey developer can you do add only one thing I guess everybods want it pls change the youtube logo with premium logo inside so it doesnt seem unpremium

**Comment by AbsurdIdealist** [comment]
everybody?

**Comment by rgvxsthi** [comment]
I'm happy with the way it is currently!

**Comment by JackPlaysGames0510** [comment]
sorry mate but to be honest with you this is a stupid idea

**Comment by qnblackcat** [comment]
Sorry, but I think this option is completely useless. Also, I don’t want to mess up with Google.

**Comment by GizmoHD4Life** [comment]
btw. if you use altstore you can change the icon anyway. i think only with beta tho
