### ISSUE TITLE
Cant reinstall the IPA via Sideloadly [Bug]

### ISSUE THREAD

**Issue by nimatih** [qnblackcat/uYouPlus#287]
### Device info
- iOS/iPadOS version: iOS 16 Beta 3
- Device model: iPhone 13 Pro Max
- Sideload tool: Sideloadly
- Version of uYouPlus: 17.26.2_2.1

### Describe the bug

Can't reinstall the IPA until I delete the app from my phone and hit install. 
Gives me the below error. 

There was an issue during installation: 0: PackageInspectionFailed (Failed to load Info.plist from bundle at path /private/var/containers/Bundle/Application/C3F95083-1849-4441-9CE8-DCD10B61A327/YouTube.app/PlugIns/MessagesExtension.appex; Extra info about "/private/var/containers/Bundle/Application/C3F95083-1849-4441-9CE8-DCD10B61A327/YouTube.app/PlugIns/MessagesExtension.appex/Info.plist": Couldn't stat /private/var/containers/Bundle/Application/C3F95083-1849-4441-9CE8-DCD10B61A327/YouTube.app/PlugIns/MessagesExtension.appex/Info.plist: No such file or directory)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by martinoturrina** [comment]
This is still happening to me after complete uninstall of both uYouPlus and Altstore. Also with resets in between. Any idea?

**Comment by leshniak** [comment]
I can confirm the issue. Even with the procedure from FAQ. iOS 16 Public Beta 2.

**Comment by martinoturrina** [comment]
Still happening on iOS 16 beta 5 with complete uninstall and reboot before re-installing altstore and the IPA

**Comment by martinoturrina** [comment]
@qnblackcat can we open this back?

**Comment by leshniak** [comment]
@qnblackcat
1. I've removed Sideloadly
2. Deleted `/Library/Mail/Bundles/SideloadlyPlugin.mailbundle`
3. Deleted uYou+
4. Installed everything again

The bug STILL EXISTS and is really annoying.

**Comment by leshniak** [comment]
Still present.

**Comment by PhilipLPYT** [comment]
I also have this problem on iOS 16.0. On iPadOS 15.6.1 sideloading works.

**Comment by Justini1702** [comment]
i found 1 way to fix that prob. You can delete the app had been installed before and reinstall. I've try and success.

**Comment by PhilipLPYT** [comment]
> i found 1 way to fix that prob. You can delete the app had been installed before and reinstall. I've try and success.

I have also tried it and after uninstalling the app I didn’t have to tick the disable plugins box and it works :)

**Comment by nimatih** [comment]
> i found 1 way to fix that prob. You can delete the app had been installed before and reinstall. I've try and success.

But that also deleted the files downloaded into the app :(
