### ISSUE TITLE
Do you plan to support Sideloading on M1?

### ISSUE THREAD

**Issue by wondergit113** [qnblackcat/uYouPlus#291]
###
When sideloading to M1 macOS machines, uYouPlus crashes on startup. See below for error code. When using Sideloadly, you can load a custom libcolorpicker.dylib and can successfully launch the app but such Sideload configurations aren't possible with PlayCover (a more user friendly side loading app on M1 macOS machines).

Is it possible to make updates to the IPA to support side loading to M1 without additional steps?

Thank you

`Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libcolorpicker.dylib
Referenced from: /Users/USER/Library/Containers/io.playcover.PlayCover/YouTube.app/Frameworks/iSponsorBlock.dylib
Reason: tried: '/Users/user/Library/Containers/io.playcover.PlayCover/YouTube.app/Frameworks/libcolorpicker.dylib' (mach-o file (/Users/user/Library/Containers/io.playcover.PlayCover/YouTube.app/Frameworks/libcolorpicker.dylib), but incompatible platform (have 'iOS', need 'MacCatalyst')), '/Users/user/Library/Containers/io.playcover.PlayCover/YouTube.app/Frameworks/libcolorpicker.dylib' (mach-o file (/Users/user/Library/Containers/io.playcover.PlayCover/YouTube.app/Frameworks/libcolorpicker.dylib), but incompatible platform (have 'iOS', need 'MacCatalyst')), '/usr/lib/libcolorpicker.dylib' (no such file)
(terminated at launch; ignore backtrace)`

You can download a libcolorpicker.dylib that works from here:
https://github.com/yarshure/libcolorpicker/tree/master/.theos/obj/debug/arm64

**Comment by qnblackcat** [comment]
I‘m awake of this issue. Unfortunately, I don’t own an arm Mac, so uYouPlus will not support arm Mac (at least for now)

ps: I don’t see any reason why we need to sideload YouTube on a Mac OS device?! 🤷‍♂️

**Comment by wondergit113** [comment]
uYouPlus is just a better YouTube experience than the web (in my experience). don't have to mess about with additional Safari plugins, respects media controls, includes the extensions I use (iSponsor).

I guess if I had to choose, I'd take an Apple TV build over one that supported macOS.

**Comment by rgvxsthi** [comment]
Hi @wondergit113 , you might look into [Yattee](https://github.com/yattee/yattee) which supports macOS as well as SponsorBlock.
