### ISSUE TITLE
Uyou+ crashing when using uyou settings

### ISSUE THREAD

**Issue by samrd-2** [qnblackcat/uYouPlus#292]
### Device info
- iOS/iPadOS version: 15.1.1
- Device model:iPhone 12
- Sideload tool:AltStore
- Version of uYouPlus:v17.26.2-2.1

Issue; Same as title

How to reproduce:https://user-images.githubusercontent.com/67169985/179360857-f58e51b2-a8d1-4921-affa-75a039658c1d.MOV

Crash log: https://pastebin.com/

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
