### ISSUE TITLE
YouTube links don't open uYou app.

### ISSUE THREAD

**Issue by OpenSource03** [qnblackcat/uYouPlus#293]
### Device info
- iOS/iPadOS version: 16 beta 3
- Device model: iPhone 12
- Sideload tool: AltStore
- Version of uYouPlus: 2.1

### Describe the bug
YouTube links aren't opened in app, but on YouTube.com instead...

### How to reproduce the bug
https://streamable.com/ij994y

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
