### ISSUE TITLE
[Bug] Open in YouTube Extensions not working iOS 16

### ISSUE THREAD

**Issue by sleeping10** [qnblackcat/uYouPlus#294]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: Public beta 16
- Device model:iPhone se 2020
- Sideload tool AltStore
- Version of uYouPlus: 17.26.2

### Describe the bug
The Open in YouTube Extension doesn't show up in safari. So started to use the user script again that works fine [user script](https://github.com/qnblackcat/uYouPlus/issues/69)

**Comment by qnblackcat** [comment]
Are you sure you followed the instruction?

https://github.com/CokePokes/YoutubeExtensions#youtubeextensions

**Comment by brlala** [comment]
> Are you sure you followed the instruction?
> 
> https://github.com/CokePokes/YoutubeExtensions#youtubeextensions

not working for me as well, on iOS16, selected keep app plugins while installing

**Comment by sleeping10** [comment]
> Are you sure you followed the instruction?
> 
> 
> 
> https://github.com/CokePokes/YoutubeExtensions#youtubeextensions

Have you removed it from the IPA you uploaded? Because on iOS 15, I did not have to follow these steps; I just had to enable the extension. Now on iOS 16, I can't enable the extension because it doesn't show up

**Comment by LuxiP7** [comment]
For me the extensions shows up normally but disappears after a day or two without any notice. Reinstalling uYouPlus brings it back.

**Device info**
- iOS version: 16 Public Beta
- Device Model: 12 Mini
- Sideload tool: Altstore
- Version of uYouPlus: v17.26.2-2.1

**Comment by sleeping10** [comment]
Strange doesn't show up at all for me but user-script works fine.

**Comment by sleeping10** [comment]
Okey thanks 👍👍👍
