### ISSUE TITLE
[Bug]uyou download/pip options not showing under the player

### ISSUE THREAD

**Issue by overwerked** [qnblackcat/uYouPlus#296]
### Device info
- iOS/iPadOS version: 16 Public Beta
- Device model: 13 Pro Max
- Sideload tool: AltStore
- Version of uYouPlus: 2.1 (YouTube version: 17.26.2

### Describe the bug
uYou buttons under the player disappear without having the hide feature enabled

### How to reproduce the bug
![42AD7584-4980-44D6-B8B0-D1AF0E789898](https://user-images.githubusercontent.com/82577117/179748876-a5cfd401-831d-4752-8536-f8f8255a7e98.jpeg)
![55C68D70-2265-44D7-9754-124C0AF4160F](https://user-images.githubusercontent.com/82577117/179748881-38c1b9f9-9f92-4dd9-8470-5c0ca913d531.jpeg)

**Comment by qnblackcat** [comment]
Tweaking buttons under the video player doesn't work with the sideloaded version of uYou. Similar to https://github.com/qnblackcat/uYouPlus/issues/41.
