### ISSUE TITLE
Error when building IPA: bash: -project: command not found

### ISSUE THREAD

**Issue by royerlraph79** [qnblackcat/uYouPlus#297]
Why the hell does it say that?
<img width="1440" alt="Screen Shot 2022-07-20 at 6 15 27 PM" src="https://user-images.githubusercontent.com/30907279/180091834-96954b2d-b5e7-4f95-ae1f-316092c44b60.png">

**Comment by qnblackcat** [comment]
Have you installed Xcode Command Line Tools?

If Xcode Command Line Tools is installed but you still have this error, manually select Xcode Command Line Tools in `Xcode > Preferences > Location > Xcode Command Line Tools`

**Comment by royerlraph79** [comment]
Yes they are installed and I even ran the command xcode-select to change its developer directory and it does this:
<img width="1440" alt="Screen Shot 2022-07-21 at 2 27 04 AM" src="https://user-images.githubusercontent.com/30907279/180144579-949d8257-c1f7-4c2b-b717-9f55350bfc1d.png">
<img width="1440" alt="Screen Shot 2022-07-21 at 2 27 13 AM" src="https://user-images.githubusercontent.com/30907279/180144598-8c87eda3-205c-4002-b1d2-7bbd7ad39b15.png">

**Comment by qnblackcat** [comment]
Please manually select Xcode Command Line Tools in `Xcode > Preferences > Location > Xcode Command Line Tools`

**Comment by royerlraph79** [comment]
But I can’t, they don’t show up! Look at the screenshots

**Comment by royerlraph79** [comment]
These are the default ones, not the ones installed with the terminal

**Comment by qnblackcat** [comment]
I clearly see `Xcode 13.4.1` in this screenshot
https://user-images.githubusercontent.com/30907279/180144598-8c87eda3-205c-4002-b1d2-7bbd7ad39b15.png

**Comment by royerlraph79** [comment]
Okay, now wtf am I doing wrong
[Terminal Saved Output.txt](https://github.com/qnblackcat/uYouPlus/files/9157040/Terminal.Saved.Output.txt)
?

**Comment by qnblackcat** [comment]
Do you put iOS 15 SDK in `theos/sdks`?

**Comment by royerlraph79** [comment]
Yes I did

**Comment by qnblackcat** [comment]
Is it an iOS 15.0 sdk? If not, update the TARGET sdk in `Alderis > lcpshim > Makefile`

**Comment by royerlraph79** [comment]
It is an iOS 15.5 sdk. I updated to iOS 15.6, should I use this sdk instead?

**Comment by royerlraph79** [comment]
And what if I don't want Alderis and iSponsorBlock?

**Comment by qnblackcat** [comment]
> It is an iOS 15.5 sdk. I updated to iOS 15.6, should I use this sdk instead?

You can use it as long as it's a patched iOS 15.5 sdk (which has private framwork included), don't forget to update the Makefile in `Alderis > lcpshim > Makefile`

If it is not a patched sdk, you can just use my SDK

**Comment by qnblackcat** [comment]
> And what if I don't want Alderis and iSponsorBlock?



Then your Makefile should look like this:

```
TARGET = iphone:clang:latest:13.0
uYouPlus_USE_FLEX = 0
uYouPlus_USE_FISHHOOK = 0
ARCHS = arm64
MODULES = jailed
FINALPACKAGE = 1
CODESIGN_IPA = 0

TWEAK_NAME = uYouPlus
DISPLAY_NAME = YouTube
BUNDLE_ID = com.google.ios.youtube
 
uYouPlus_INJECT_DYLIBS = Tweaks/uYou/Library/MobileSubstrate/DynamicLibraries/uYou.dylib .theos/obj/YTUHD.dylib .theos/obj/YouPiP.dylib .theos/obj/YouTubeDislikesReturn.dylib .theos/obj/YoutubeSpeed.dylib
uYouPlus_FILES = uYouPlus.xm Settings.xm
uYouPlus_IPA = ./tmp/Payload/YouTube.app
uYouPlus_FRAMEWORKS = UIKit
uYouPlus_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
SUBPROJECTS += Tweaks/YTUHD Tweaks/YouPiP Tweaks/Return-YouTube-Dislikes Tweaks/YTSpeed
include $(THEOS_MAKE_PATH)/aggregate.mk

before-package::
	@echo -e "==> \033[1mMoving tweak's bundle to Resources/...\033[0m"
	@cp -R Tweaks/YouPiP/layout/Library/Application\ Support/YouPiP.bundle Resources/
	@cp -R Tweaks/uYou/Library/Application\ Support/uYouBundle.bundle Resources/
	@cp -R lang/uYouPlus.bundle Resources/
```

**Comment by royerlraph79** [comment]
> > It is an iOS 15.5 sdk. I updated to iOS 15.6, should I use this sdk instead?
> 
> You can use it as long as it's a patched iOS 15.5 sdk (which has private framwork included), don't forget to update the Makefile in `Alderis > lcpshim > Makefile`
> 
> If it is not a patched sdk, you can just use my SDK

Where can I find an iOS 15 patched sdk? The ones on Theos repo don’t even reach iOS 15

**Comment by qnblackcat** [comment]
> Where can I find an iOS 15 patched sdk? The ones on Theos repo don’t even reach iOS 15

My bad. I forgot to add the download link of iOS 15 sdk to the Wiki. Here is what you need: https://github.com/chrisharper22/sdks

**Comment by royerlraph79** [comment]
Alright, thanks. Now what?
<img width="1440" alt="Screen Shot 2022-07-27 at 12 52 33 AM" src="https://user-images.githubusercontent.com/30907279/181164353-e9ba63d8-430f-417a-b34e-f23c2f06d770.png">

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/iSponsorBlock#building

**Comment by royerlraph79** [comment]
This is getting ridiculou
<img width="1440" alt="Screen Shot 2022-07-27 at 1 04 57 AM" src="https://user-images.githubusercontent.com/30907279/181165660-91758b33-2b97-4852-9483-f26e6a612cf1.png">
s

**Comment by qnblackcat** [comment]
1. Make sure theos-jailed is configured correctly.
2. Make sure you run the `buildapp.sh`

**Comment by qnblackcat** [comment]
Have you managed to compile the IPA?

**Comment by royerlraph79** [comment]
Nope

**Comment by qnblackcat** [comment]
whats the problem now?

**Comment by royerlraph79** [comment]
It's too complicated 🤦🏻‍♂️ nothing works when I do it

**Comment by qnblackcat** [comment]
I suggest you use the Github action method then
