### ISSUE TITLE
[Bug] uYouLocal button duplicates on reopening

### ISSUE THREAD

**Issue by Bradovman** [qnblackcat/uYouPlus#30]
**Device info:**
- iOS/iPadOS version:  1.14.6
- Device model: Ipad 8th gen
- Sideload tool: Altstore
- Version of uYouPlus: 16.45.4-2.1

**Describe the bug:**
- uYouLocal buttons will duplicate when you go out of app and back in. This pushes other buttons such as like or dislike off screen.

**How to reproduce the bug:**
Make sure uYou local button is enable
Go into a video and press the home button then go back. There will be another button
Every time you do this another button will appear
![IMG_0886](https://user-images.githubusercontent.com/45505531/146843141-e067a17b-1f38-4881-87b3-4e3a59237458.jpg)

**Additional context:**
This might just be a uYou issue.

**Comment by TheJeremyP** [comment]
On iPad I'm seeing uYou, uYouLocal, and uYouPiP buttons duplicating after rotating to landscape and back.

**Comment by qnblackcat** [comment]
Since YouTube v17.x and higher, all the buttons of uYou under the video player _(uYou download, uYouLocal download, uYouPiP)_ are not visible at all. Not sure if we can consider this a bug if it doesn't happen anymore, technically.

**Comment by qnblackcat** [comment]
> Since YouTube v17.x and higher, all the buttons of uYou under the video player _(uYou download, uYouLocal download, uYouPiP)_ are not visible at all. Not sure if we can consider this a bug if it doesn't happen anymore, technically.
