### ISSUE TITLE
[Bug] Some YouTube comment replies don’t load correctly

### ISSUE THREAD

**Issue by badprogramshere** [qnblackcat/uYouPlus#303]
### Device info
- iOS/iPadOS version: 14.0.1
- Device model: iPhone 11
- Sideload tool: AltStore
- Version of uYouPlus: 17.26.2

### Describe the bug

When you first open a comment thread on the app, the replies for that comment show up as normal. However, when you select another comment, the replies for the first comment appear. This repeats for all subsequent videos until you close the app.

### How to reproduce the bug

Here is a link demonstrating the bug:
https://streamja.com/mrMZK

### Crash log (if possible)

N/A

### Additional context:
 
Note that I am jailbroken with Taurine - however, I have uninstalled all YouTube-related tweaks.

**Comment by qnblackcat** [comment]
Does this issue happen with stock YouTube from AppStore?

**Comment by manhbi18112005** [comment]
The issue also happens in my device. Sometimes the initial command loads but the replies don't load even though the indicator shows that there are many replies in that thread.

**Comment by manhbi18112005** [comment]
> Does this issue happen with stock YouTube from AppStore?

The function works correctly in the stock version.

**Comment by qnblackcat** [comment]
I cannot reproduce the isssue. Sounds like an issue of YouTube itself.

**Comment by qnblackcat** [comment]
According to this post, it is an issue of YouTube.
https://www.reddit.com/r/youtube/comments/wb16nc/youtube_bug_wont_let_me_see_replies_to_comments/

**Comment by qnblackcat** [comment]
Closed because this is obv an issue of the YouTube app itself.
