### ISSUE TITLE
[Enhancement] an option to disable YouTube’s new swipe-up-in-fullscreen

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#306]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device information
- iOS/iPadOS: 15.6
- Device model: iPad Pro 10.5
- Version of uYouPlus: 

### Describe this Enhancement
This feature has been added for awhile when version YouTube 17.01.4
However you probably won’t agree but having this unnecessary feature on an iPad ruins YouTube’s 2-finger-in-fullscreen that was added years ago and it is still the best thing

### The new gesture that made me stay in uYouPlus 16.42.3 🙄
https://user-images.githubusercontent.com/78001398/180780445-19101e84-4d55-44d8-a876-fac04b8a8955.MOV
However there’s another problem, whenever cleaning the screen on a iPad screen while watching a video you’ll accidentally get out of full screen because of this. but this feature is very good for iPhones though.

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does this issue happen with the official YouTube from AppStore?
Of course.

**Comment by qnblackcat** [comment]
Sorry but we don’t have any plan to add this request

**Comment by arichorn** [comment]
so it isn’t possible then. Sorry then, I’ll wait when uYou releases it then
