### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by TheLidlMan** [qnblackcat/uYouPlus#307]
Is there any way to give money support to you directly? You have links for all the other devs you use?

**Comment by qnblackcat** [comment]
Thanks. This is very kind of you. I believe you’re looking for this: [Support the developers](https://github.com/qnblackcat/uYouPlus#support-the-developers)

**Comment by TheLidlMan** [comment]
> Thanks. This is very kind of you. I believe you’re looking for this: [Support the developers](https://github.com/qnblackcat/uYouPlus#support-the-developers)

I already support them but I don't think your username is there? MiRO92,PoomSmart and Galactic-dev? Are these any of yours directly?

**Comment by qnblackcat** [comment]
Thank you <3 I do have a Paypal account here: https://www.paypal.com/paypalme/qnblackcat

**Comment by qnblackcat** [comment]
Thanks for your gift. I appreciate it <3
