### ISSUE TITLE
[Bug] Impossible to connect using Google Account

### ISSUE THREAD

**Issue by Zalatis** [qnblackcat/uYouPlus#309]
### Device info
- iOS/iPadOS version: iOS 15.6 (19G71)
- Device model: iPad 9th generation
- Sideload tool: AltStore (Free Dev)
- Version of uYouPlus: [17.26.2_2.1](https://github.com/qnblackcat/uYouPlus/releases/download/v17.26.2-2.1/uYouPlus_17.26.2_2.1.ipa)

### Does the issue happen with the official YouTube from AppStore?
No

**Comment by qnblackcat** [comment]
I have no idea why is this happening to you. Maybe some kind of security feature? 
Anyway, I’m afraid that I can do nothing about this issue.
