### ISSUE TITLE
[Questions] Black circles in the background of YT-player buttons

### ISSUE THREAD

**Issue by RevENGE-code** [qnblackcat/uYouPlus#310]
Hey qnblackcat,

First of all, thanks for maintaining uYouPlus so well! Now for my question, do you plan an adding an option to turn off the "new" annoying black circles (as seen in the image below) covering the fast-forward, stop and fast-backward buttons?

![image](https://user-images.githubusercontent.com/54822494/181138553-2bc35df9-dae1-4eb2-99e9-915b643fbe18.jpeg)

**Comment by qnblackcat** [comment]
This is a new UI change from YouTube. Nothing I can do.

**Comment by qnblackcat** [comment]
Actually, I could take a look at it once I get the new UI
