### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by MatthiasSomay** [qnblackcat/uYouPlus#315]
I can’t seem to log in with my google account, I keep getting this message. It probably has something to do with my security settings, but I can’t seem to figure out where to adjust them. Other Google apps work fine
![1C02748E-5412-4286-A621-337EB167C1BC](https://user-images.githubusercontent.com/44980895/181477738-5a29981b-347a-4a75-af19-15b21aeee10a.jpeg)

**Comment by qnblackcat** [comment]
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/309 and https://github.com/qnblackcat/uYouPlus/issues/314
