### ISSUE TITLE
After about 1 day or so I can't open uyou and it says that "YouTube is no longer available"

### ISSUE THREAD

**Issue by LottoLemons** [qnblackcat/uYouPlus#316]
After about 1 day or so I can't open uyou and it says that "YouTube is no longer available". 
YouTube still stays open and fully works in my recent apps although when I try to open it from the Home Screen it says that it's no longer available. If I close it from the recent apps then I can no longer open it. I've installed uyou using the ipa file from 3utools instead of AltStore. Am I doing anything wrong?

**Comment by qnblackcat** [comment]
This has nothing to do with uYouPlus, please try other sideload tools (AltStore, Sideloadly,…)
