### ISSUE TITLE
[Bug] you can't sign in to this app because Google can't confirm that it's safe

### ISSUE THREAD

**Issue by jawNthenewbie** [qnblackcat/uYouPlus#319]

**Comment by hpopescu88** [comment]
Same issue, but not with every google account

**Comment by BandarHL** [comment]
Can you please provide more details about the problem?

**Comment by hpopescu88** [comment]
https://share.icloud.com/photos/0912jcMMuYLUNVXzs8vURI3cQ

I made a screen recording.

**Comment by Anertz** [comment]
Someone posted a solution to my Reddit post. Apparently Google is using the Bundle ID to determine whether to block the login. The same 'com.google.ios.youtube' as the official YoutubeApp seems to fix it.
https://www.reddit.com/r/sideloaded/comments/waeu2f/comment/ii1wshw/?utm_source=share&utm_medium=web2x&context=3

**Comment by BandarHL** [comment]
Well YouTube never let us Login in Tweaked version, and the Bundle ID not only reason to determine to block login most part depends on Keychain.
That’s why back in the day when I developed Tweak called Hollow write this code to Fix blocking login.
https://gist.github.com/BandarHL/492d50de46875f9ac7a056aad084ac10

**Comment by BandarHL** [comment]
But you still need to be in original Bundle of YouTube.

**Comment by PoomSmart** [comment]
I noticed a difference in `SSOKeychain` returned values of `+[SSOKeychain {sharedA,a}ccessGroup]` methods.

Official: `EQHXZ8M8AV.com.google.common.SSO`
Sideloaded: `HWW5CTH5AN.*`

Do you think this is the issue? @BandarHL

**Comment by BandarHL** [comment]
Nah that will not work, because you need to match the keychain-access-group in your entitlements.
<img width="682" alt="Screen Shot 2022-07-29 at 1 16 30 PM" src="https://user-images.githubusercontent.com/31299470/181738474-41e17294-78ca-4d4c-bb5a-2e7b4e4d79c4.png">
<img width="682" alt="Screen Shot 2022-07-29 at 1 16 36 PM" src="https://user-images.githubusercontent.com/31299470/181738567-15f5f12f-7875-4ab6-b9c6-e9703ed778e8.png">

**Comment by BandarHL** [comment]
I'm looking around the problem (with MokeyApp to debugging) and wrote some codes that might be the solution, it works fine even with different bundle ID
![IMG_917219290029-1](https://user-images.githubusercontent.com/31299470/181770970-43ee68c1-f8ed-4c19-9527-97782fa80fa2.jpeg)
<img width="1512" alt="Screen Shot 2022-07-29 at 4 29 31 PM" src="https://user-images.githubusercontent.com/31299470/181771041-bd29d331-787a-4573-8e3a-728360741abe.png">

**Comment by BandarHL** [comment]
I send Dat the dylib to try it.
Maby the problem affects some devices

**Comment by jawNthenewbie** [comment]
> I send Dat the dylib to try it. Maby the problem affects some devices

Could you

**Comment by BandarHL** [comment]
It’s seems the problem with account itself, because if you try another account it works fine.
Maybe if the account doesn’t have phone number or 2FA not enabled

**Comment by hpopescu88** [comment]
I tried disabling 2FA but the issue is still present

**Comment by qnblackcat** [comment]
For now, the only way to fix Google sign-in is keeping the original bundle ID of YouTube (`com.google.ios.youtube`) when sideload uYouPlus. This is not a real solution since not everyone has a paid developer certificate/account.

Btw, some accounts are not affected by this problem at all. Strange...

**Comment by hpopescu88** [comment]
> For now, the only way to fix Google sign-in is keeping the original bundle ID of YouTube (`com.google.ios.youtube`) when sideload uYouPlus. This is not a real solution since not everyone has a paid developer certificate/account.
> 
> Btw, some accounts are not affected by this problem at all. Strange...

How can someone keeps the original bundle ID? I can try this solution to verify if it’s working

**Comment by qnblackcat** [comment]
@hpopescu88 create a Wildcard profile. Then use it with your .p12 certifcate to sideload uYou+

**Comment by IMAXuOUT** [comment]
[
![EF3DC16C-FEB9-4BAD-83A1-9EE75B28AC1C](https://user-images.githubusercontent.com/110356528/182046227-eb437ca7-bc0e-42fe-a646-41ee4055f153.jpeg)
](https://support.google.com/accounts/answer/6010255?hl=en&visit_id=637948991534979749-864845815&p=less-secure-apps&rd=1#more-secure-apps-how&zippy=%2Cif-less-secure-app-access-is-on-for-your-account)

**Comment by IMAXuOUT** [comment]
There may be another solution… you have to change the challenge/response in the url… this modification must be done internally, and will not work if initiated externally.
![58B706B7-EFF6-428C-A669-4832D67052F8](https://user-images.githubusercontent.com/110356528/182046577-4648a9b8-a2ef-4bb3-bde7-7da4fa6ff468.jpeg) 

Below is from the original/genuine YouTube app.. I don’t know if it’s a random key… it may be different on your end… 

challenge=s4yLrChkccWT8oTzv0CHHASXx2uE_3khZnHWhIBIFzA&sfas=1&flowName=GlifSetupSafariVC#igresponse=KpoKCpUKeJwVlKnu9XgBQP8jIRMS5OBIJkE16XrbGj6697a97a_7Yprbfb9dbtcQMnZeYRQGgUSRjB6HQIAYCQoMT4Dh4zzDOeen33z5G4HvgRE4A8M8BVuU_VGoXlUZtUlN8_G8WwzXMve9oaymJbeATUhz2lRTvSw7KqpkUrpZuBIdDiyWwgXweDErL1gmftVcyTAM5-XM_9E5xswvlrsmGVOC67as_pWfDofU1DnDEIdTBBOtT1KZMfFsGrl8Yy50nPwWBpgN9blpKwPDyp6nvTZnZJmWrMAy1-KCPF8iCiNPhpHd53bXp6fYElir9lxAu3TcMZXUSuoDmjKtnauOoggcqfAuBgAjtKm4hUYulpu6LFjEMRMxL3w1dyTKpCMuW3m_uKsTsHxCNZ6MCNxwjXpOhEnztOHt3I82hRseoMqDyoDFXZLDq45SXNl6IQCJev98MYmQwZlnKBDCZKFap-1SNH7v7bWdCVZjE7C3DXVQPFRyaMdBhrAbJz9OLs9T4bbrSUJb5OyH0nvDzLynmWS_9RIzObJEJCxv1JVK3l1MLymjsgdJUFyOiuDFRK65itnoAhg9b1Ltv6nHbSpg6VUAOWs1MhZVPpoAzx4DjVCME6cL2YYbIl2BbHJE7wZvN4rR8a2ToRTZVr6bqrE4m-Dtm_aSB9HrO3FpOibmFKEKYlsLbRE24vBekehTIDa_MuyhkNfURtoeb3xPRamVLl-YsY8gLyE7gXuAWDvXDuvemFjvyblCmhQqCC6UvzmVO8Dd5DZNg-7ci4eeTAls3tfyhfClyArrIw5oom_70kbWDQjHSrhv19fSrkMtZtcH5hWJg9eO2T4ebmQLGgZL7iNjt7SHdl19hgzbOdukbUHIpzFPPt8NYc6DVkg5Wa4imnP3YXGRqGZn11eXMCaQBZUaPX1LBlMuVwFoLgyX4AAlNj_FUpFO3UhgWjclq49sZdv72QI0oKjFICYkGDv8kFUUON5IFm-rbPr7ownwd1_5kIO6oFqXs_HToyMGpZJ6eVzZwj1FzY15kx9r3ze4hAgq8sxE5vbAuTabGzA4MH5J1BY7p5OeAUOiWKE8AJFKn3V2HvnNk07K811-d8QiSXspP3y8PYFLEIk68lr7OmqriODDbY8MAZnAY0JBLx57FSXgpXvDRBd5xFCgzM--7i-JdJ-4ehC3mWHnrs_Fx47OQNnrFztVgkC-FhLMG2AmJC2O-qlYvOV7Ouvi2h2lb6yBClG2J89bEx4PrjGKtZdzS_7cbQTd78BPxi6AgYTbO6zSm92nImkt2pKokAdW6DWg3ck3yFQ3E5YTWEwDoi_SkG4rj1OH4WEJONlrdc0dEiQMxmUWklMPhTiIWzW-Rucm92Zk1WWFcLepA0vmCaycZfU-pKtp3DSPgKAuC7g8mIUt8WskH5EX54fLtPZ4RIqFNwu5LsNmrQT2EppvWBrT6k5EFMeNsW5npfleNUIiP4-BsHUFUZY5xZm31O7duDzjgsUG7T2JFTJaYISpivTkIMSygYnoGXx-pnoT8bvep4mbu-_qLPzUSFI9X_LtUd199JhulgCcJdTX0r4QAVGdJBtdLHUp7ZxcG5Tao5q9dhZIKr5Y3DEveZmoito7jIRU9Laf04DvNN-LdVp7NzY0X7_4-icfHz_-_XS--_Tzj38Qf_jrF3_79NXHx7__-N__jJ9--fHx8c23P_z518iffvaXHfntr35Pd__6_p8Upv_uf33MHE8QAQ==

**Comment by BandarHL** [comment]
> There may be another solution… you have to change the challenge/response in the url… this modification must be done internally, and will not work if initiated externally. ![58B706B7-EFF6-428C-A669-4832D67052F8](https://user-images.githubusercontent.com/110356528/182046577-4648a9b8-a2ef-4bb3-bde7-7da4fa6ff468.jpeg)
> 
> Below is from the original/genuine YouTube app.. I don’t know if it’s a random key… it may be different on your end…
> 
> challenge=s4yLrChkccWT8oTzv0CHHASXx2uE_3khZnHWhIBIFzA&sfas=1&flowName=GlifSetupSafariVC#igresponse=KpoKCpUKeJwVlKnu9XgBQP8jIRMS5OBIJkE16XrbGj6697a97a_7Yprbfb9dbtcQMnZeYRQGgUSRjB6HQIAYCQoMT4Dh4zzDOeen33z5G4HvgRE4A8M8BVuU_VGoXlUZtUlN8_G8WwzXMve9oaymJbeATUhz2lRTvSw7KqpkUrpZuBIdDiyWwgXweDErL1gmftVcyTAM5-XM_9E5xswvlrsmGVOC67as_pWfDofU1DnDEIdTBBOtT1KZMfFsGrl8Yy50nPwWBpgN9blpKwPDyp6nvTZnZJmWrMAy1-KCPF8iCiNPhpHd53bXp6fYElir9lxAu3TcMZXUSuoDmjKtnauOoggcqfAuBgAjtKm4hUYulpu6LFjEMRMxL3w1dyTKpCMuW3m_uKsTsHxCNZ6MCNxwjXpOhEnztOHt3I82hRseoMqDyoDFXZLDq45SXNl6IQCJev98MYmQwZlnKBDCZKFap-1SNH7v7bWdCVZjE7C3DXVQPFRyaMdBhrAbJz9OLs9T4bbrSUJb5OyH0nvDzLynmWS_9RIzObJEJCxv1JVK3l1MLymjsgdJUFyOiuDFRK65itnoAhg9b1Ltv6nHbSpg6VUAOWs1MhZVPpoAzx4DjVCME6cL2YYbIl2BbHJE7wZvN4rR8a2ToRTZVr6bqrE4m-Dtm_aSB9HrO3FpOibmFKEKYlsLbRE24vBekehTIDa_MuyhkNfURtoeb3xPRamVLl-YsY8gLyE7gXuAWDvXDuvemFjvyblCmhQqCC6UvzmVO8Dd5DZNg-7ci4eeTAls3tfyhfClyArrIw5oom_70kbWDQjHSrhv19fSrkMtZtcH5hWJg9eO2T4ebmQLGgZL7iNjt7SHdl19hgzbOdukbUHIpzFPPt8NYc6DVkg5Wa4imnP3YXGRqGZn11eXMCaQBZUaPX1LBlMuVwFoLgyX4AAlNj_FUpFO3UhgWjclq49sZdv72QI0oKjFICYkGDv8kFUUON5IFm-rbPr7ownwd1_5kIO6oFqXs_HToyMGpZJ6eVzZwj1FzY15kx9r3ze4hAgq8sxE5vbAuTabGzA4MH5J1BY7p5OeAUOiWKE8AJFKn3V2HvnNk07K811-d8QiSXspP3y8PYFLEIk68lr7OmqriODDbY8MAZnAY0JBLx57FSXgpXvDRBd5xFCgzM--7i-JdJ-4ehC3mWHnrs_Fx47OQNnrFztVgkC-FhLMG2AmJC2O-qlYvOV7Ouvi2h2lb6yBClG2J89bEx4PrjGKtZdzS_7cbQTd78BPxi6AgYTbO6zSm92nImkt2pKokAdW6DWg3ck3yFQ3E5YTWEwDoi_SkG4rj1OH4WEJONlrdc0dEiQMxmUWklMPhTiIWzW-Rucm92Zk1WWFcLepA0vmCaycZfU-pKtp3DSPgKAuC7g8mIUt8WskH5EX54fLtPZ4RIqFNwu5LsNmrQT2EppvWBrT6k5EFMeNsW5npfleNUIiP4-BsHUFUZY5xZm31O7duDzjgsUG7T2JFTJaYISpivTkIMSygYnoGXx-pnoT8bvep4mbu-_qLPzUSFI9X_LtUd199JhulgCcJdTX0r4QAVGdJBtdLHUp7ZxcG5Tao5q9dhZIKr5Y3DEveZmoito7jIRU9Laf04DvNN-LdVp7NzY0X7_4-icfHz_-_XS--_Tzj38Qf_jrF3_79NXHx7__-N__jJ9--fHx8c23P_z518iffvaXHfntr35Pd__6_p8Upv_uf33MHE8QAQ==

In the blog, they say you can disable this safety. Go to https://myaccount.google.com/lesssecureapps and turn 'Allow less secure apps' On, because this new option by default is Off.
<img width="857" alt="Screen Shot 2022-08-01 at 1 28 06 AM" src="https://user-images.githubusercontent.com/31299470/182047779-ab74ef5e-b9a2-441b-a175-484b2dd931f9.png">

**Comment by martenmatrix** [comment]
If you have 2FA enabled you are unable to modify that setting. You will have to create an app-specific password, which you can do [here](https://myaccount.google.com/apppasswords).

**Comment by BandarHL** [comment]
> If you have 2FA enabled you are unable to modify that setting. You will have to create an app-specific password, which you can do [here](https://myaccount.google.com/apppasswords).
> 
> But I am unable to even get to the "Type your password" screen.

You use it instead of your original password. (I think)

**Comment by qnblackcat** [comment]
@BandarHL 
So Google literally removed the option to turn on “ Allow less secure apps“. It’s always off now.
We have to use app-specific password, but we can’t even get to the password screen.

**Comment by hpopescu88** [comment]
> If you have 2FA enabled you are unable to modify that setting. You will have to create an app-specific password, which you can do [here](https://myaccount.google.com/apppasswords).
> 
> But I am unable to even get to the "Type your password" screen.

Even if you disable 2FA completely, you won't be able to get to the screen for password, so this isn't a solution.

**Comment by IMAXuOUT** [comment]
Another possible solution is to create a custom shortcut, whereby when you share a url with that shortcut, it copies it, and it opens it in the YouTube app… URL from the original YouTube app sign-in…

**Comment by brahm0** [comment]
I hope somehow it can be resolved. Is there a way like on Android where there is a special client that facilitates loging into google.

**Comment by brahm0** [comment]
> I hope somehow it can be resolved. Is there a way like on Android where there is a special client that facilitates loging into google.

I successfully installed and signed into uyou using sideloadly. No issues whatsoever.

**Comment by qnblackcat** [comment]
@brahm0 
1. Is this the first time you install & sign in to uYouPlus on your device?
2. Not everyone is affected by this issue. In this case, you’re pretty lucky

**Comment by brahm0** [comment]
> @brahm0
> 
> 1. Is this the first time you install & sign in to uYouPlus on your device?
> 2. Not everyone is affected by this issue. In this case, you’re pretty lucky

Yes , this is the first time I’m installing and signing in to uYou. I’m on iOS 15.6

**Comment by at001475** [comment]
I don’t know if mine is the special case. But, I can’t sign in every account I have and two devices I own

**Comment by mbucc9000** [comment]
This isn’t just a uYou problem either. Cercene and other YouTube clients don’t work (not a surprise). One of my accounts don’t work but my second one does. I’ve never had 2FA on the second account before so maybe there is a pattern there. 

Meaning if an account has never had 2FA then it’s not affected.

**Comment by Morku** [comment]
I had to reinstall uYou+ on 29th July. I had **no** issue to Log-In.
Used 17.26.2_2.1 with Signulous **without editing** signing settings on iPhone XS Max 15.6. Location: Germany

My Google Account has 2FA **enabled** (since always) with Passwort+YubiKey (Security Key) as only allowed Log-In method.
I don't have set any app-sepcific password. So having 2FA en-/disabled might not be the reason.

I hope this information helps to find a pattern which might trigger this error.

**Comment by podupuis** [comment]
Same issue here after doing a factory reset of my iphone 8 plus.

**Comment by Broxar** [comment]
I tried sideloadly but still not working :|

**Comment by ExpoYT** [comment]
I have made a Reddit post about this issue with several others reporting the sign in error as well: https://www.reddit.com/r/sideloaded/comments/wftosl/yt_cannot_sign_in_error_as_well_multiple_ipas/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Disabling 2FA did not work and unlike how some others reported I cannot get ANY google account to log in, all say it’s unsafe to log in. I really hope we can find a solution this application is excellent!

**Comment by shanperera** [comment]
Spent a good amount of time trying to figure out a way to use the default bundle id when signing the IPA with a free developer account, no luck.

I had to use a sideload/signing service that allows signing with the default bundle id `com.google.ios.youtube`, much cheaper than getting an Apple Dev cert, I was able to sign in afterwards. It's a good option for people who want a cheaper workaround until a better alternative is found.

**Comment by abayomi185** [comment]
@shanperera what service did you use?

**Comment by shanperera** [comment]
@abayomi185 I used signtunes but I imagine any other service would work just as well.

**Comment by ExpoYT** [comment]
> @abayomi185 I used signtunes but I imagine any other service would work just as well.

 Can you explain why this requires a paid signing service if all you need to do is change the bundle id to the real thing? I have tried changing the bundle id in Sideloadly, but I get an error message. What makes this happen though?

**Comment by shanperera** [comment]
@ExpoYT
> Can you explain why this requires a paid signing service if all you need to do is change the bundle id to the real thing? I have tried changing the bundle id in Sideloadly, but I get an error message. What makes this happen though?

I'm not an iOS dev so take this with a grain of salt and someone please correct me if I'm wrong. I think changing the bundle id to the default id for an IPA uses functionality that is only available to someone with a paid dev certificate. So if your Sideloadly config uses a free developer account then this won't work.

When you use a signing service you're essentially paying to use one of their many dev certs to sign the IPA and install it on your phone as if you were an iOS developer testing their own app.

**Comment by mbucc9000** [comment]
> Spent a good amount of time trying to figure out a way to use the default bundle id when signing the IPA with a free developer account, no luck.
> 
> I had to use a sideload/signing service that allows signing with the default bundle id `com.google.ios.youtube`, much cheaper than getting an Apple Dev cert, I was able to sign in afterwards. It's a good option for people who want a cheaper workaround until a better alternative is found.

Would you mind making a short guide on this (if it’s not against the rules)?

thanks

-M

**Comment by Primemeow** [comment]
Alright so here's how you do it
Go to signtunes' website
Pay the $9.50 (via PayPal or Stripe, it's $7.60 if you do crpyto), make sure it's linked to your UDID
If stripe doesn't work but it still takes your money, open a ticket on their Discord (it happened to me, someone will sign you)
Go to /signer from the website
Put in your UDID, the custom bundle ID of `com.google.ios.youtube`
check the box labeled "Use default bundle ID"
Upload the IPA, make sure to tap upload (you can make the IPA public if you want, it doesn't matter)
Once it's uploaded, tap the name of the app, then tap install
If it's done correctly, it'll let you log in

**Comment by mbucc9000** [comment]
> Alright so here's how you do it Go to signtunes' website Pay the $9.50 (via PayPal or Stripe, it's $7.60 if you do crpyto), make sure it's linked to your UDID If stripe doesn't work but it still takes your money, open a ticket on their Discord (it happened to me, someone will sign you) Go to /signer from the website Put in your UDID, the custom bundle ID of `com.google.ios.youtube` check the box labeled "Use default bundle ID" Upload the IPA, make sure to tap upload (you can make the IPA public if you want, it doesn't matter) Once it's uploaded, tap the name of the app, then tap install If it's done correctly, it'll let you log in @mbucc9000

Thank you! Very clear and concise! Only $9.50 for a year ain't too bad. I appreciate ya.

-M

**Comment by podupuis** [comment]
> Alright so here's how you do it Go to signtunes' website Pay the $9.50 (via PayPal or Stripe, it's $7.60 if you do crpyto), make sure it's linked to your UDID If stripe doesn't work but it still takes your money, open a ticket on their Discord (it happened to me, someone will sign you) Go to /signer from the website Put in your UDID, the custom bundle ID of `com.google.ios.youtube` check the box labeled "Use default bundle ID" Upload the IPA, make sure to tap upload (you can make the IPA public if you want, it doesn't matter) Once it's uploaded, tap the name of the app, then tap install If it's done correctly, it'll let you log in @mbucc9000

For some reasons, It doesn't seem to be working for me. Even if I change the bundle ID

**Comment by ExpoYT** [comment]
> > Alright so here's how you do it Go to signtunes' website Pay the $9.50 (via PayPal or Stripe, it's $7.60 if you do crpyto), make sure it's linked to your UDID If stripe doesn't work but it still takes your money, open a ticket on their Discord (it happened to me, someone will sign you) Go to /signer from the website Put in your UDID, the custom bundle ID of `com.google.ios.youtube` check the box labeled "Use default bundle ID" Upload the IPA, make sure to tap upload (you can make the IPA public if you want, it doesn't matter) Once it's uploaded, tap the name of the app, then tap install If it's done correctly, it'll let you log in @mbucc9000
> 
> For some reasons, It doesn't seem to be working for me. Even if I change the bundle ID

You still can’t sign in or are having another issue? I am going to follow this guide myself so I hope it’s not the sign in problem still.

**Comment by podupuis** [comment]
> > > Alright so here's how you do it Go to signtunes' website Pay the $9.50 (via PayPal or Stripe, it's $7.60 if you do crpyto), make sure it's linked to your UDID If stripe doesn't work but it still takes your money, open a ticket on their Discord (it happened to me, someone will sign you) Go to /signer from the website Put in your UDID, the custom bundle ID of `com.google.ios.youtube` check the box labeled "Use default bundle ID" Upload the IPA, make sure to tap upload (you can make the IPA public if you want, it doesn't matter) Once it's uploaded, tap the name of the app, then tap install If it's done correctly, it'll let you log in @mbucc9000
> > 
> > 
> > For some reasons, It doesn't seem to be working for me. Even if I change the bundle ID
> 
> You still can’t sign in or are having another issue? I am going to follow this guide myself so I hope it’s not the sign in problem still.

Yup. Still doesn't work for me.

**Comment by Primemeow** [comment]
@podupuis Did you try doing it both with and without that checkbox ticked? If it lets you turn on notifications that’s a good sign

**Comment by podupuis** [comment]
> 

I have tried both. Still doesn't work for me

**Comment by shanperera** [comment]
What's the error you are getting? You may have better luck asking for help on their discord channel, they respond pretty quick and would have a better understanding of what's going on.

**Comment by podupuis** [comment]
> @podupuis What's the error you are getting? You may have better luck asking for help on their discord channel, they respond pretty quick and would have a better understanding of what's going on.

I'm still getting '' can't sign in to this app because Google can't confirm that it's safe ''

**Comment by shanperera** [comment]
@podupuis 

This is assuming you paid for Signtunes and provided the correct UDID when you paid for the subscription. 

Uninstall the Youtube and uYou+ app from your device then follow these steps exactly in the video in Safari using your iPhone or iPad.

https://user-images.githubusercontent.com/19804723/182992108-1677e065-533a-4a6a-815d-50d2a9fc885d.mp4


After clicking on the link like in the end of the video, there will be a popup that will ask if you want to install the app. Press Install, once it's done installing the app then you should be able to login. 

If you're still having issues after this, then you should ask in the Signtunes Discord since they will know the next best steps.

**Comment by qnblackcat** [comment]
New discussion should go to here: https://github.com/qnblackcat/uYouPlus/discussions/341

**Comment by qnblackcat** [comment]
Please go to [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-you-cant-sign-in-to-this-app-because-google-cant-confirm-that-its-safe-warning-when-signing-in) to see the workaround for this problem.
