### ISSUE TITLE
[Enhancement] OLED theme

### ISSUE THREAD

**Issue by Grizzlywolf** [qnblackcat/uYouPlus#32]
Could we maybe get an OLED(black theme) for the app?

**Comment by RexyAU** [comment]
[youtubeoled.zip](https://github.com/qnblackcat/uYouPlus/files/7800493/youtubeoled.zip)

Here you go, extract the .zip and inject youtubeoled.deb using sideloadly.

Most UI elements inside the app become pure black for oled.

Ensure your iOS device is using dark mode to auto enable.

**Comment by ErSpieltHD** [comment]
@RexyAU

From where can I get tweaks? I can only find finished IPAs or just links to add it to Cydia etc. (which I don't have)

**Comment by RexyAU** [comment]
> @RexyAU
> 
> From where can I get tweaks? I can only find finished IPAs or just links to add it to Cydia etc. (which I don't have)

I found this oled patch on flex and converted it to a deb file. You can use https://www.ios-repo-updates.com/ which has lots of free cydia tweak deb files to download from directly, or if you have a spare device that is jailbroken you can extract the dylibs of the tweaks you want with filza file manager and then inject them into your sideloaded apps. 

For sideloaded apps you want to inject in, the tweaks will only work if it wasn't designed in a way to access files outside of the sandboxed app, otherwise the app will either crash or not do what was expected.

**Comment by ErSpieltHD** [comment]
And how to make a tweak out of PoomSmart/IAmYouTube without jailbreaked device?

**Comment by RexyAU** [comment]
@ErSpieltHD

You can use Theos to compile tweaks. Btw for that IAmYouTube tweak the deb file is in the packages folder.

[com.ps.iamyoutube_1.1.1_iphoneos-arm.deb.zip](https://github.com/qnblackcat/uYouPlus/files/7802978/com.ps.iamyoutube_1.1.1_iphoneos-arm.deb.zip)

**Comment by ErSpieltHD** [comment]
> [youtubeoled.zip](https://github.com/qnblackcat/uYouPlus/files/7800493/youtubeoled.zip)
> 
> Most UI elements inside the app become pure black for oled.


Could you rather use YTSystemAppearance as I don't like pure black?

https://www.ios-repo-updates.com/repository/poomsmart/package/com.ps.ytsystemappearance/

**Comment by RexyAU** [comment]
@ErSpieltHD

YTSystemAppearance is included in uYou+. It automatically sets youtube to light or dark mode depending on your current iOS device theme. If you don't want pure black for oled devices then don't inject the youtubeoled.deb file, and then you will use the standard youtube dark theme.

**Comment by cricketgangu** [comment]
Is there a certain version of uYouPlus that the youtubeoled deb file is meant to work with? I tried injecting it into the most recent release with azule and the app doesn't open.

**Comment by RexyAU** [comment]
> Is there a certain version of uYouPlus that the youtubeoled deb file is meant to work with? I tried injecting it into the most recent release with azule and the app doesn't open.

It works with all versions. Haven't tested with Azule because i have been injecting it on the fly with sideloadly.

**Comment by qnblackcat** [comment]
Added in v17.15.1-2.1
