### ISSUE TITLE
Cant go over X2.0 Speed on any video

### ISSUE THREAD

**Issue by harisshaukat96** [qnblackcat/uYouPlus#321]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_ ok

### Device info
- iOS/iPadOS version: ios 16 beta 3
- Device model: iphone 11
- Sideload tool: altstore
- Version of uYouPlus: 17.04.3

### Describe the bug
Video Wont go higher then x2.0 despite there being options for that

### Crash log (if possible)
Cant find it.

### Does the issue happen with the official YouTube from AppStore?
it literally cant the over x2.0 is in your app not the official one

### Additional context: 
It goes back to x2.0 when i try to up it

**Comment by harisshaukat96** [comment]
Video wont upload

**Comment by harisshaukat96** [comment]
So i cant show it

**Comment by qnblackcat** [comment]
@harisshaukat96 have you tried [v17.30.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.30.3-2.1)?

**Comment by qnblackcat** [comment]
Closed due to inactive
