### ISSUE TITLE
[Bug] no TV available

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#325]
Since YTCastConfirm (or earlier) the YT App doesn't remember my connected AirPlay devices aka. TV.

This is really annoyingly as I have to renter my YT TV Code every time.

Please fix.

![image](https://user-images.githubusercontent.com/40891294/181905654-f2c30f76-3ea5-4167-a4cc-cc3bd8151859.jpeg)

**Comment by qnblackcat** [comment]
Please read & complete the issue template
