### ISSUE TITLE
Heating issue

### ISSUE THREAD

**Issue by randomuser10800** [qnblackcat/uYouPlus#326]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: IOS 15.6
- Device model: Iphone 13
- Sideload tool: Sideloadly
- Version of uYouPlus: uYouPlus_17.25.1_2.1

### Describe the bug
Playing any video which is more than 1080p (1440p, 2160p) heats up the device and it get pretty warm on the back.

### How to reproduce the bug
![image](https://user-images.githubusercontent.com/108909664/182010635-e3da46af-07a1-48af-908f-8e58c677a01d.png)

### Crash log (if possible)
Don't know.

### Does the issue happen with the official YouTube from AppStore?
No, the official app plays it fine without getting warm.

### Additional context: 
It's been happening to me since older versions too.

**Comment by qnblackcat** [comment]
It‘s a known issue of YTUHD. See https://github.com/qnblackcat/uYouPlus/wiki/FAQ and https://github.com/qnblackcat/uYouPlus/issues/6
