### ISSUE TITLE
[Bug] App Crashes

### ISSUE THREAD

**Issue by aiknayan** [qnblackcat/uYouPlus#328]
### Device info
- iOS:  15.1
- Device model: iPhone 11
- Sideload tool : AltStore 
- Version of uYouPlus: v17.26.2-2.1

### Describe the bug
YouTube crashes if I go through uYou<YT SETTINGS

### Does the issue happen with the official YouTube from AppStore?
No

### Additional context: 
 uYouPlus: v16.xxxx Works Fine

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
