### ISSUE TITLE
[Questions] iSponsorBlock icon animation

### ISSUE THREAD

**Issue by myodan** [qnblackcat/uYouPlus#33]
Let me tell you first. Sorry if this issue should have been forwarded to `uYou` or `iSponsorBlock`. I'm not exactly sure who to contact about this. If it's not a `uYouPlus issue`, please close this issue immediately!

Not a bug, but the animation of the ``iSponsorBlock`` icon disappearing from the video overlay is unnatural.

What do you think of the above suggestion?

**Comment by qnblackcat** [comment]
I'm not sure if we can call it a bug to be honest. For now, I recommend you disable the iSponsorblock buttons in the video player.
