### ISSUE TITLE
[Questions] Theos Unable to build ipa with a modern yt tweak

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#331]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

### Question: Cause of the Theos Error
Actually. This is the error you’ll get if you try to run and build the ipa (only occurs if adding newer tweaks by yourself)
![3E6158C4-AAB7-4CB2-B00F-4C709C780B06](https://user-images.githubusercontent.com/78001398/182514919-04816f97-c869-4318-a5f4-73036f177ecf.jpeg)

### Question 2: Can’t you just update Theos?
Of course I could do this but it’s not a good idea for someone like me to do it because doing it on a forked project will always be gone since I always delete branches including my main branch that aren’t updateable but overrall I will always have to update theos every time in my forked repo.

### Question 3: can’t you remove the tweak?
of course not. If I do that then my version of the yt’s ipa will not use the tweak which is a very disappointing move to do.

#### I made these questions just so I can easily explain everything in this one message!

**Comment by qnblackcat** [comment]
I‘m sorry. If you add new tweaks, you have to configure your project so it can be compiled!? 🤷‍♂️ This is not something I can “fix”

**Comment by arichorn** [comment]
the tweak was "YTABConfig" but I’ll see if I can somehow fix it with YTAppDelegate.h
But hope compiling it works! 👌

**Comment by arichorn** [comment]
Also qnblackcat. Happy uYou Anniversary!
uYou is one year’s old as of today! 🎉🎊
