### ISSUE TITLE
Sharesheet for downloaded videos are not sized correctly

### ISSUE THREAD

**Issue by WoodpeckerBaby** [qnblackcat/uYouPlus#337]
### Device info
- iOS/iPadOS version: latest
- Device model: iPad Pro 10.5
- Sideload tool: AltStore
- Version of uYouPlus: latest

### Describe the bug

Sharesheet position and size is messed up for downloaded videos. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
![image](https://user-images.githubusercontent.com/14303318/182861941-946e555d-1d30-4032-a1ab-ae6b6c5fec18.png)

Download a video, then click share. 

### Does the issue happen with the official YouTube from AppStore?
Well, this has nothing to do with YouTube.

**Comment by qnblackcat** [comment]
This is obv an issue of uYou. You should open a new issue in upstrean uYou: https://github.com/MiRO92/uYou-for-YouTube

**Comment by qnblackcat** [comment]
see https://github.com/MiRO92/uYou-for-YouTube/issues/157
