### ISSUE TITLE
[Bug] In dark mode, some elements do not apply properly to the dark theme.

### ISSUE THREAD

**Issue by myodan** [qnblackcat/uYouPlus#34]
**Device info:**
- iOS/iPadOS version: `iOS 15.2`
- Device model: `iPhone 13 Pro Max`
- Sideload tool: `AltStore`
- Version of uYouPlus: `16.46.5-2.1`

**Describe the bug:**
- In dark mode, some elements do not apply properly to the dark theme.

**How to reproduce the bug:**
- In Dark Mode, go to the uYou Settings tab.

**Screenshot:**
<img src="https://user-images.githubusercontent.com/41239679/147858361-a5e8fdb7-ebea-4e69-bc3a-5c1e363e3806.PNG" width="30%"/>

**Additional context:**
Sorry if this issue should have been forwarded to `uYou`. I'm not exactly sure who to contact about this. I'm not exactly sure who to contact about this. If it's not a uYouPlus issue, please close this issue immediately!

**Comment by qnblackcat** [comment]
I would report it to MiRO if I were you.

https://github.com/MiRO92/uYou-for-YouTube
