### ISSUE TITLE
[Bug] YTUHD not working

### ISSUE THREAD

**Issue by TheLidlMan** [qnblackcat/uYouPlus#342]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16 B4
- Device model: iPhone 12 and iPad Pro (2018)
- Sideload tool: Signulous
- Version of uYouPlus: 17.30.2-21

### Describe the bug
After enabling VP9 codec in settings and restarting the app there is still no 4k or 1440p option like before?
![image](https://user-images.githubusercontent.com/75203773/183032668-1ff6d1de-d03d-4d35-8086-6e1da419fc8a.png)
### How to reproduce the bug
Enable VP9 codec in settings and then try 4k YouTube video

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
No

### Additional context:

**Comment by qnblackcat** [comment]
My bad! v17.30.3-2.1 is a pre-release because I don’t have enough time to fully test it. 
I informed PoomSmart about this issue, hope he could address it soon

**Comment by TheLidlMan** [comment]
> My bad! v17.30.3-2.1 is a pre-release because I don’t have enough time to fully test it. 
> 
> I informed PoomSmart about this issue, hope he could address it soon

No worries, totally understandable. Thanks for putting a new version out. 🥳🥳

**Comment by arichorn** [comment]
I have this issue too you aren’t the only one with it ☝️

**Comment by qnblackcat** [comment]
This will be fixed in the next release
