### ISSUE TITLE
[Bug] time seek on shorts no longer working

### ISSUE THREAD

**Issue by jeffzyliu** [qnblackcat/uYouPlus#343]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 15.6
- Device model: iPhone X
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore
- Version of uYouPlus: 17.30.3 (2.1)

### Describe the bug

The tweak for dragging the time progress bar to seek on shorts was working in the past, and no longer works as of 17.30.3.

The time progress bar also looks grey instead of red as before.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

Open any short and try to drag to seek.

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

N/A

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

N/A

### Additional context:

**Comment by qnblackcat** [comment]
This will be fixed in the next release

**Comment by arichorn** [comment]
I already tested it out but on my iPad it completely hides the bar at the bottom of the shorts? So I will have no idea when it ends or having the ability to rewind it or forward it

**Comment by jeffzyliu** [comment]
Newest release fixed it for me, @arichorn is it good for you too now?

**Comment by arichorn** [comment]
nope, I'm pretty sure the iPad version of YouTube uses a different scroll bar method but the iPhone can see it!
