### ISSUE TITLE
Is there any way to disable the video player gestures?

### ISSUE THREAD

**Issue by LottoLemons** [qnblackcat/uYouPlus#345]
Right now I have both of them set to seek but it's still really annoying. I habe not seen a button in the app for this so I'm wondering if there's any other way to disable them. Thanks!

**Comment by qnblackcat** [comment]
> ...I have both of them set to seek

What're they?

> ...I habe not seen a button in the app for this so I'm wondering if there's any other way to disable them

What button? Disable what?

Please explain in more details

**Comment by LottoLemons** [comment]
I'm talking about the gestures you can use in the video player to set the volume, change the brightness stuff like that. Is there any way to disable them? They're kinda annoying

**Comment by qnblackcat** [comment]
Go to uYou's setting > Video controls overlay > Disable uYou Gesture Controls

**Comment by LottoLemons** [comment]
> Go to uYou's setting > Video controls overlay > Disable uYou Gesture Controls

Thanks!
