### ISSUE TITLE
Playing a downloaded audio then a normal video from YouTube creates a cacophony

### ISSUE THREAD

**Issue by LottoLemons** [qnblackcat/uYouPlus#346]
### Device info
- iOS/iPadOS version: iOS 16 developer beta 4
- Device model: iPhone 13
- Sideload tool: Altstore
- Version of uYouPlus: 17.26.2_2.1

### Describe the bug
When you play a downloaded audio, then a video that isn't downloaded, they both play at the same time

### How to reproduce the bug
Play an audio from the uYou plus folder, then play a normal video from YouTube 

### Crash log (if possible)
N/A

### Does the issue happen with the official YouTube from AppStore?
No. 

### Additional context:

**Comment by qnblackcat** [comment]
you should open a new issue on upstream uYou: https://github.com/MiRO92/uYou-for-YouTube

in the meantime, just don’t play uYou audio and YouTube video at the same time
