### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by eIiot** [qnblackcat/uYouPlus#347]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0
- Device model: iPhone 13 Pro
- Sideload tool: AltStore
- Version of uYouPlus: 16.46.5

### Describe the bug
When OLED Dark Mode is enabled, some UI components remain in dark mode.

### How to reproduce the bug
![image](https://user-images.githubusercontent.com/39346975/183140546-ccec744b-456f-4356-a0cf-9c7d8866e896.jpeg)
![image](https://user-images.githubusercontent.com/39346975/183140943-b345bc28-d447-48e8-9b1c-4bb4f2a62a9f.jpeg)
- Enabled amoled dark mode
- Use app as normal

### Does the issue happen with the official YouTube from AppStore?
N/A

**Comment by qnblackcat** [comment]
Please update to the latest version of uYou+
