### ISSUE TITLE
[Bug] Age Restricted Videos Not Playing Properly

### ISSUE THREAD

**Issue by Blarnix** [qnblackcat/uYouPlus#349]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: _iOS 15.6_
- Device model: _iPhone 13,1 (12 Pro)_
- Sideload tool: _AltStore_
- Version of uYouPlus: _17.30.3_

### Describe the bug

_Attempting to watch any age restricted content simply doesn't work, shows this screen with no ability to refresh to fix it:_
_![image](https://user-images.githubusercontent.com/61402697/183236658-650d344a-c74f-48ca-b52b-984da8d16f56.png)_

_Just started on this update I believe and I've found no workaround so far._

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
_Turn off age restriction, watch restricted video, no luck._

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
_N/A_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
_Not that I know of._
### Additional context: 
_N/A_

**Comment by qnblackcat** [comment]
Try this? https://github.com/qnblackcat/uYouPlus/issues/250
