### ISSUE TITLE
Cast button not working

### ISSUE THREAD

**Issue by BitNotFound** [qnblackcat/uYouPlus#35]
When pressing the cast button at the upper right in videos or the home screen, the app only shows a button to learn more, cancel, or "Find devices automatically" and says to "Tap to allow local network access in Settings".

When I click the button, it brings me to the settings page for the app, but gives no option to turn on local network access.

Is there something I may be missing, or is this a bug?

**Comment by qnblackcat** [comment]
Are you keeping the vanilla YouTube app?

**Comment by BitNotFound** [comment]
Yes I was! I removed the regular Youtube app and it works fine now.

Thanks!
