### ISSUE TITLE
[Bug] Doenst wanna play sensitive topic videos

### ISSUE THREAD

**Issue by GizmoHD4Life** [qnblackcat/uYouPlus#353]
### Device info
- iOS/iPadOS version: 16
- Device model: iPhone 12
- Sideload tool: Altstore
- Version of uYouPlus: Latest as of now (exceeded 10 app ids so cant remember)

### Describe the bug

When playing a video that starts with a youtube disclaimer about the video containing suicidal topics and other stuff, it wants you to "click to try again" but if you do so, it will just reload the video. which makes it impossible to watch the video

### How to reproduce the bug

go to a video talking about sensitive topics (suicide, etc)

tap play or tap on the screen

### Does the issue happen with the official YouTube from AppStore?

No

**Comment by qnblackcat** [comment]
Try this? https://github.com/qnblackcat/uYouPlus/issues/250

**Comment by GizmoHD4Life** [comment]
Seems Like It Worked. Thank You So Much!
