### ISSUE TITLE
[Questions]Support for Testflight

### ISSUE THREAD

**Issue by dtantono** [qnblackcat/uYouPlus#358]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by qnblackcat** [comment]
It’s **impossible**

**Comment by dtantono** [comment]
@qnblackcat The reason is Testflight is much more easier to install and we don't need to plug the iPhone to the PC regularly for sideloading regularly. Is it because of the developer licence fee?

**Comment by qnblackcat** [comment]
@dtantono Apple won‘t let the app go through. That's it

**Comment by iRayanKhan** [comment]
You can use a signing service such as SignTunes to keep the app installed for 365 days without a computer.
