### ISSUE TITLE
[Bug] [Feature]  Previous and Next buttons missing

### ISSUE THREAD

**Issue by gmanc2** [qnblackcat/uYouPlus#363]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.6
- Device model: 13 Pro Max
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore
- Version of uYouPlus: v17.30.3-2.1

### Describe the bug
The next and previous buttons are missing when playing a video. I have the hide button turned off in the settings.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Watch a video and the arrows for going to the next or previous episode. 

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
No

**Comment by gmanc2** [comment]
This might be a bug, or maybe youtube changed it? I looked it up, and other people say it's gone, and some say they have it. I have it on my normal youtube app. If they did change it, could you add them back?

**Comment by arichorn** [comment]
That’s not a bug I don’t think, I’m pretty sure sometimes in the app, YouTube hides them, but trust me this happened too when I had the option disabled

**Comment by qnblackcat** [comment]
YouTube removed them intentionally 

https://www.reddit.com/r/youtube/comments/wlq3zk/ok_who_removed_the_skip_and_playback_buttons/

**Comment by gmanc2** [comment]
@qnblackcat Is it possible to add them back in future release?

**Comment by qnblackcat** [comment]
Try [v17.35.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.35.3-2.1).
