### ISSUE TITLE
[Enhancement] Well-Deserved uYouPlus changes

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#364]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### uYouPlus info
- Version of uYouPlus: 17.30.3

### Enhancement
as you might of know uYou that used 16.42.3 does have a lot of issues whenever using the latest version, it unfortunately not all uYou settings work on the latest version like **Buttons Under the Video Player** which not all options work at the moment, I don’t actually know what to call this enhancement also.

But overall there should be a new tab in the settings tab to fix eve more problems with uYou and uYou’s settings bugs if possible but I know you already got some solved when seeing the uYouPlus.xm file but I think having more resolved issues or workarounds and more localization around uYou until uYou gets another release in the future.

### Additional context: 
I did list a lot of bugs at the bottom of the topic if you wanted to know. https://github.com/MiRO92/uYou-for-YouTube/issues/152 also you can close this topic if you want, I was saying something about uYouPlus’s issues. Hope this helps qnblackcat! ✌️

**Comment by qnblackcat** [comment]
Please understand that not all issues of uYou can be fixed without the source code

**Comment by arichorn** [comment]
I know that qnblackcat, just showing you information and it still sucks to see it in closed-sourced til this day
