### ISSUE TITLE
[Request] Clickbait Thumbnail Remover

### ISSUE THREAD

**Issue by amit-bh** [qnblackcat/uYouPlus#368]
Would it possible to add a feature to get rid of clickbait thumbnails similar to this Firefox extension: https://addons.mozilla.org/en-US/firefox/addon/clickbait-remover-for-youtube/

It replaces thumbnails on videos by taking a frame from the actual video.

**Comment by qnblackcat** [comment]
Sorry but I don’t think it‘s possible
