### ISSUE TITLE
[Bug] Error when submitting segments

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [qnblackcat/uYouPlus#369]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️ Yes

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iPadOS 15.3.1
- Device model: ipad pro (10.5-inch)
- Sideload tool (Ex: AltStore, Sideloadly...): altstore
- Version of uYouPlus: uYouPlus_17.26.2_2.1

### Describe the bug
When I try to submit a segment in sponserblock, I get this error

```
Error code 400: bad request
```

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

1. Create a segment
2. Set the category
3. Tap submit segments

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
I couldn't find one from this month, so it probably wouldn't be useful.
### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
No, because youtube doesn't have sponserblock
### Additional context: 
Here's a screenshot of the error
![057330CB-8415-48BD-B054-55112F4B8DE1](https://user-images.githubusercontent.com/70973578/184287159-478b6f0e-04c8-4cf4-af30-6a327b1147aa.jpeg)

**Comment by qnblackcat** [comment]
Probably something is wrong with Sponsorblock‘s server.
https://status.sponsor.ajay.app/

**Comment by ego-lay-atman-bay** [comment]
Oooh. Yeah, that makes more sense.
