### ISSUE TITLE
Open youtube links from browser 

### ISSUE THREAD

**Issue by pote2639** [qnblackcat/uYouPlus#37]
It’s just me or uYou doesn’t opening youtube link from the other apps like Safari or Reddit?

**Comment by qnblackcat** [comment]
It is impossible to fix deep-link on sideloaded apps. Please take a look at the FAQ before asking.

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by ErSpieltHD** [comment]
https://github.com/PoomSmart/IAmYouTube
