### ISSUE TITLE
[Questions] Remove unused plugins/app extensions for free dev account users prior to installing IPA on device

### ISSUE THREAD

**Issue by denwi** [qnblackcat/uYouPlus#38]
Hey all,

I have tried searching the web on this issue but have not found a clear answer.
Is it possible to delete unused/unneeded extensions from the plugin folder within the IPA file to save on App IDs?
I ask since AltStore only allows an all or nothing approach in removing them during installing an IPA.
Assuming things like "NotificationServiceExtension" for example is useless for people without a paid dev account since push notifications don't work.

![ipa](https://user-images.githubusercontent.com/949405/147992753-4a565f55-867c-4671-ab3a-5270f710e274.png)

Thanks in advance

**Comment by qnblackcat** [comment]
It is possible to remove these Extensions, and yes, they‘re quite useless if you use the free developer certificate.
However, I want to keep them cz I‘m not sure how they work if a paid developer certificate is used.
For now, please select “Remove app Extensions” when installing via AltStore

**Comment by denwi** [comment]
> For now, please select “Remove app Extensions” when installing via AltStore

Thank you for the very prompt response.
Just to make sure, selecting "Remove app Extensions" won't cause issues with any of the other added features within uYouPlus?
I'm mostly concerned with keeping SponsorBlock working, hence I wanted to be selective with what I remove.

**Comment by qnblackcat** [comment]
Don’t worry. Removing app Extensions will not affect uYouPlus’s features 😉
