### ISSUE TITLE
A possible fix for downloads speeds

### ISSUE THREAD

**Issue by Colepng** [qnblackcat/uYouPlus#380]
From what I know when youtube changed the backends of videos download speeds droped off, but I found this program that fixed this issue. https://github.com/yt-dlp/yt-dlp, it might be helpful code to fix slow download speeds.

**Comment by arichorn** [comment]
Buddy. I’m not sure qnblackcat can implement that when uYou is closed sourced.
I recommend showing it to MiRO92

**Comment by qnblackcat** [comment]
Um, this is the better place I think: https://github.com/MiRO92/uYou-for-YouTube

**Comment by arichorn** [comment]
I forgot to give them the url to uYou for YouTube sorry qnblackcat!

**Comment by Colepng** [comment]
Thanks
