### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by bolognayballs** [qnblackcat/uYouPlus#383]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###

pip  black screen when playing video iPhone XS. iOS 14.4.2 uyou second to newest version and signed with signum.fun 
![0801B757-A42A-40EA-99C1-6001C05D2A1F](https://user-images.githubusercontent.com/69094717/185048320-5e635b7d-dccc-42da-aaec-06ff5879bb0a.png)

**Comment by bolognayballs** [comment]
Why invalid label never fix any issue I have

**Comment by GizmoHD4Life** [comment]
You Should Follow The Template Provided When Clicking On Bug/Question. Also, should report this as a bug.

**Comment by bolognayballs** [comment]
When I publish as a bug it gets closed someone pls help me with making it the right 
Way

**Comment by GizmoHD4Life** [comment]
![image](https://user-images.githubusercontent.com/60453357/185651596-67335a53-d1b5-41e9-b29b-533ad173b8b3.jpeg)

![image](https://user-images.githubusercontent.com/60453357/185651623-e3fbd4ba-75ce-4a84-b8af-4c948b8fd5fe.jpeg)

![image](https://user-images.githubusercontent.com/60453357/185651639-8c302402-a374-46f0-8fe2-7e8c3a23094b.jpeg)

Hope This Helps
