### ISSUE TITLE
[Questions] Create a .deb out of a part of the uYouPlus.xm source code (./buildapp.sh not working)

### ISSUE THREAD

**Issue by binnichtaktiv** [qnblackcat/uYouPlus#386]
Can someone help me to create a .deb or something I can inject to Youtube to fix iOS 16 crash? I tried to build it myself but I get errors everytime...😭 Can someone pls help me? Im trying 5 days now lmao
I always get errors like this.......
I have no experience with something like that and would be happy if someone could help me
![image](https://user-images.githubusercontent.com/96953964/185228570-59be5331-63da-4a24-bd12-1f9d60625be1.png)
![image](https://user-images.githubusercontent.com/96953964/185228730-ea8f81e4-eeb3-494a-90b6-ce8e56466311.png)

**Comment by qnblackcat** [comment]
Running the buildapp.sh generates an uYouPlus IPA, not a deb.
Since you want to build a .deb out of a part of the uYouPlus.xm source code, simply creates the theos project with the part of the code that you need.

**Comment by binnichtaktiv** [comment]
Can you explain what you mean with "simply creates the theos project with the part of the code that you need"? I never did something like this before. What do I have to do? Clone the project and then modify the .xm? And what number do I have to select in Theos?

**Comment by qnblackcat** [comment]
I suggest you do some research about theos. You already had the source code, all you need is setup theos and run the `make package` command 🤷‍♂️

>…. what number do I have to select in Theos?

Create an iphone-tweak
