### ISSUE TITLE
[Bug] App Crashes After Scrolling In Shorts

### ISSUE THREAD

**Issue by GizmoHD4Life** [qnblackcat/uYouPlus#391]
### Device info
- iOS/iPadOS version: 16.4
- Device model: iPhone 12
- Sideload tool: Altstore
- Version of uYouPlus: 17.26.2

### Describe the bug

trying to scroll 3 times in the shorts section makes the app crash. 2 times is fine

### How to reproduce the bug

go to shorts

scroll 3 times

### Does the issue happen with the official YouTube from AppStore?

No

**Comment by GizmoHD4Life** [comment]
seems to be the same as #253

**Comment by qnblackcat** [comment]
Duplicate of #253

**Comment by GizmoHD4Life** [comment]
Dont Really Know If This Is New But Somebody mentioned that when using a sevond acc, the crash does not occur. for me however, it doesnt seem to work for me. 

also do you have any idea why this happens yet?
