### ISSUE TITLE
[Bug] No timestamps on Subscriptions tab

### ISSUE THREAD

**Issue by SpecialOperations** [qnblackcat/uYouPlus#4]
![image](https://user-images.githubusercontent.com/30572191/141210543-804827ce-e60f-4e99-b75e-aa339fcba006.png)
As you can see from the attachment, there is no time stamps on the bottom right of the video thumbnails.

**Comment by qnblackcat** [comment]
https://github.com/MiRO92/uYou-for-YouTube/issues/12

https://github.com/MiRO92/uYou-for-YouTube/issues/54

=> It‘s a known issue.

**Comment by qnblackcat** [comment]
@SpecialOperations 
Please try this version. Make sure you Turn off "Remove YouTube Ads" in uYou's setting. Don't worry, you will not see any ads.

[uYouPlus 16.46.5-2.1-F1](https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/ETZtEz8nNNhHpXlqzawKriIBzLq8LatUHErFyROam_voKQ?download=1)

**Comment by asportnoy** [comment]
@qnblackcat I tried this release. The videos in the subscriptions page are fixed. However, my playlists are still missing timestamps.

**Comment by asportnoy** [comment]
The workaround in [v17.01.4-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.01.4-2.1) fixed this for me.

**Comment by qnblackcat** [comment]
The issue can be fixed by disabling “Hide YouTube Ads” in uYou’s settings. just leave a comment if you have any problem with the workaround
