### ISSUE TITLE
[Bug] Seek bar gets stuck at the bottom even after exiting full screen and video overlapping suggestions on the side

### ISSUE THREAD

**Issue by RollinggThunder** [qnblackcat/uYouPlus#400]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.6
- Device model: iPad Pro
- Sideload tool (Ex: AltStore, Sideloadly...) Sideloadly 
- Version of uYouPlus: Latest 

### Describe the bug
If auto full-screen enabled, seek bar is stuck at the bottom even after exiting the full screen mode, leading to main video overlapping with video suggestions on the side and causing accidental touches 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by qnblackcat** [comment]
**Latest** is not a version number

**Comment by qnblackcat** [comment]
not sure I understand you issue? Please attach a screenshot if possible
