### ISSUE TITLE
[Bug] App Crashes on “Shorts” tab 3rd video

### ISSUE THREAD

**Issue by torma616** [qnblackcat/uYouPlus#402]
The app is crashing every time I open the shorts tab and try to swipe up through to the fourth video. The first 3 videos play without issue, but the app crashes as soon as I swipe upwards on the third video.

This only seems to be affecting the shorts tab, because playing shorts from the homepage/search doesn’t cause the same issues.

To reproduce:
* Open YouTube
* Open Shorts tab
* Swipe through 4 videos

**Comment by qnblackcat** [comment]
Duplicate of #253
