### ISSUE TITLE
 Red video timeline bar is displayed at the bottom (could be because of iOS16?)[Bug]

### ISSUE THREAD

**Issue by Harumatsu91202024** [qnblackcat/uYouPlus#406]
### Device info
- iOS/iPadOS version: iOS 16 Developer Beta 7
- Device model: iPhone 13 Pro Max 
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore 
- Version of uYouPlus: uYouPlus_17.31.4_2.1
### Describe the bug
When playing a video, the red progress bar (I don’t know the name) is misplaced and displayed at the bottom of the screen.
![28A858A4-0C00-4750-A7D1-ACED2C1BED2A](https://user-images.githubusercontent.com/79664720/186419642-bb61ce3b-7fa8-4b1c-81af-3a057e84a005.jpeg)

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Open uyouplus and play any video
![B01E2A95-63F6-4571-8C1C-BBD36EC6B2CB](https://user-images.githubusercontent.com/79664720/186419807-b7019c11-5ab2-40fd-ae2d-eb8ef0d36946.jpeg)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
It doesn’t

**Comment by qnblackcat** [comment]
Please try [v17.35.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.35.3-2.1)

**Comment by qnblackcat** [comment]
Closed due to inactive
