### ISSUE TITLE
[Bug]Cant login cuz google says it’s not safe 

### ISSUE THREAD

**Issue by Gat44** [qnblackcat/uYouPlus#408]
### Device info
- iOS/iPadOS version: iOS 16 Public beta 4 
- Device model:iPhone XR
- Sideload tool (Ex: AltStore, Sideloadly...)Altstore
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_
-Uyouplus 17.31.4_2.1. IPA

### Describe the bug
Can’t login cuz google says its unsafe like fuck  #y’all
### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
![31E00110-4197-4E8A-9E38-E411FA88E797](https://user-images.githubusercontent.com/112017582/186501938-4b252d27-fd75-470b-b464-0c502b407546.png)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by Dynasty-Dev** [comment]
You know where you downloaded the ipa? ..the releases page? Yeah, above there’s a solution

**Comment by Gat44** [comment]
Hey thanks man I really appreciate it
