### ISSUE TITLE
[BUG] downloads don’t work properly 

### ISSUE THREAD

**Issue by bossx2** [qnblackcat/uYouPlus#409]
When it finishes downloading it shows error 200 can’t move from //:file path to another file path also opening uYou video overlay settings crash the app also playlist downloads don’t work it says no videos found in playlist and I honestly don’t know if it is a uYou issue or a uYou+ issue

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
