### ISSUE TITLE
Can you update Cercube to the latest version pls ?

### ISSUE THREAD

**Issue by WTFObstSalat** [qnblackcat/uYouPlus#412]
Pls update CercubePlus with the latest Cercube version „5.4.11“

**Comment by arichorn** [comment]
@WTFObstSalat i made a cercubeplus ipa that uses v5.3.11 + YTDisableHighContrastIcons Tweak
Hope I helped you obtaining this version of Cercube! Enjoy! https://github.com/arichorn/CercubePlusExtra/releases/tag/v17.33.2-5.3.11-(14)
