### ISSUE TITLE
[Bug] error when updating through altstore

### ISSUE THREAD

**Issue by tonysprenk** [qnblackcat/uYouPlus#413]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16 latest beta
- Device model: 12 pro max
- Sideload tool: AltStore
- Version of uYouPlus: current: 17.26.2-2.1, updating to 17.33.2-2.1

### Describe the bug
When trying to update in AltStore I get the error shown in the screen shot (screen shot is old but result is the same when trying to update to latest)

### How to reproduce the bug

Update in altstore 

![C95F932A-80DB-4C81-B0BE-5969D842FDF1](https://user-images.githubusercontent.com/38426377/187059073-e173e95e-8af9-4a23-a014-df8c2b579f1d.jpeg)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
