### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by IamCarron** [qnblackcat/uYouPlus#414]
Everyrtime I open a video the app crashes On IOS 15.6.1

**Comment by dfmcvn** [comment]
Experiencing the same problem on iOS 15.6.1, you can try [v17.26.2-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.26.2-2.1). It does not crash for now.

**Comment by qnblackcat** [comment]
Please complete the issue template

**Comment by han9over** [comment]
> Experiencing the same problem on iOS 15.6.1, you can try [v17.26.2-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.26.2-2.1). It does not crash for now.

It crashes on shorts in this version too.
