### ISSUE TITLE
[Bug] YouTube crashed when using OpenYoutube extension

### ISSUE THREAD

**Issue by dora727** [qnblackcat/uYouPlus#416]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0
- Device model: iPhone SE (3rd generation)
- Sideload tool (Ex: AltStore, Sideloadly...): Sideloadly
- Version of uYouPlus: 17.33.2_2.1

### Describe the bug
When using OpenYoutube extension to open a video on YouTube, YouTube crashed

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
[Video](https://user-images.githubusercontent.com/109880918/187121128-29facc5d-2c9b-4566-b556-267be3e09d7b.MOV) 

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
https://pastebin.com/nyP6wyQx

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by qnblackcat** [comment]
If you believe this is an issue of Open in YouTube Extension, this is a better place to report its issue: https://github.com/CokePokes/YoutubeExtensions

**Comment by qnblackcat** [comment]
Ops! I accidentally closed the issue

**Comment by level3tjg** [comment]
Does this happen every time you use the extension or just once in a while?

**Comment by dora727** [comment]
> Does this happen every time you use the extension or just once in a while?

Well, yesterday it happen every time, but when I reinstall uYouPlus, it worked for somehow

**Comment by arichorn** [comment]
This happens to me and whenever this extension expires it screws up the way it opens all the apps, like for example clicking a link to an app to take me to the browser even if I refreshed OpenYouTube

**Comment by arichorn** [comment]
Oops sorry that I said that in the wrong place, sorry qnblackcat!
