### ISSUE TITLE
[Bug] Does not play playlists/mixes when in background and unable to press the shuffle button

### ISSUE THREAD

**Issue by RainfireVT** [qnblackcat/uYouPlus#418]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.6
- Device model: Iphone 13 pro MLR53LL/A
- Sideload tool (Ex: AltStore, Sideloadly...)
AltStore
- Version of uYouPlus: 17.33.2_2.1

### Describe the bug

When playing playlists or mixes, the shuffle button does not work as well as the app has to be up for it to continue to play when background playing is applied.

### How to reproduce the bug
when you go into liked videos or into the main page for a mix, the shuffle is greyed out and cannot be pressed, the other part of the bug is when you listen to it on the phone and go out to do other things, it doesnt play automatically to the next song/video most of the time.

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by qnblackcat** [comment]
Closed due to inactive
