### ISSUE TITLE
Cannot find the app in appdb.to

### ISSUE THREAD

**Issue by svsk1ng** [qnblackcat/uYouPlus#42]
Hello, i am currently searching the app in appdb.to but i cannot find it.. am i doing something wrong or the app is not in the website anymore.. ? :)

**Comment by tosunkaya** [comment]
ur blind. even there is bold text on appdb https://github.com/qnblackcat/uYouPlus/releases
###### uYou+ (uYouPlus) has been moved to Github. I will not update uYou+ on appdb anymore. Future updates can be found on my Github: https://github.com/qnblackcat/uYouPlus! ######

**Comment by svsk1ng** [comment]
So if i understand right your saying there's is not way to download this app from appdb

**Comment by tosunkaya** [comment]
Really? I sent releases link. Just download the ipa from github. Also even still latest version is available on appdb too.

**Comment by svsk1ng** [comment]
I will just download the ipa and sideload it. But there's no way i can find the app in appdb. 
Thanks anw.

**Comment by tosunkaya** [comment]
Why? I can able to see on appdb atm. Here is reliable than appdb. The developer releases github. Random people upload to appdb, cant check if its modified maliciously.

**Comment by svsk1ng** [comment]
Yes your right its better to download the ipa and install it from here. Thank you fore your help

**Comment by qnblackcat** [comment]
> Yes your right its better to download the ipa and install it from here. Thank you for your help

Yeah. I did not upload the ipa to appdb. Someone else did that. 
However, if the download URL on appdb is from the Release tab, it should be fine ✅
