### ISSUE TITLE
[Bug] Unable to login, Google login warning: ” Google couldn't confirm this attempt to sign in is safe. If you think this is a mistake, you can close and try again to sign in.”

### ISSUE THREAD

**Issue by jereloh** [qnblackcat/uYouPlus#420]
### Device info
- iOS/iPadOS version: 15.6.1
- Device model: iPad Air 4th gen
- Sideload tool  AltStore
- Version of uYouPlus: v17.33.2-2.1

### Describe the bug
"Google couldn't confirm this attempt to sign in is safe. If you think this is a mistake, you can close and try again to sign in" warning when signing in. 

I have no issue on my other iPad 7th gen and iPhone 13. but they have been side-loaded since uYouPlus v16. This is a brand new installation on this iPad. Have tried to use the method to login through incognito safari but does not work.

### How to reproduce the bug
Green field altstore and uYouPlus installation.

**Comment by Micha3lo** [comment]
Pretty much the same issue for me. Freshly installed IPA via AltStore on iP 13 Pro with iOS 15.6.1, just throws this error whether its in app or in a browser.

**Comment by scarmoreyy** [comment]
Same issue here! 
iPhone 13 pro max
iOS 15.6.1
Fresh install via AltStore, login issue as stated.
Fresh install via sideloadly, same issue. 
Copy paste url trick does not work, creating new account works then signs me out after closing the app and can't login again, have to create new account every time.

**Comment by damienmauchamp** [comment]
Same issue here
iPad (6th gen), iPadOS 16 beta 8

No issue on my iPhone 12 (iOS 16 beta 8) though

**Comment by coey0814** [comment]
Same issue here
iPhone 13 mini
iOS 15.1

uYouPlus v 17.34.3

**Comment by lukman4** [comment]
Same issue here on a fresh install of uYouPlus. The workarounds also do not work.

Device info
* iOS/iPadOS version: 15.0
* Device model: iPhone 13 Pro Max
* Sideload tool: TrollStore
* Version of uYouPlus: v17.34.3-2.1

**Comment by stosumarte** [comment]
Same issue here.

iOS 15.1
iPhone SE (2020)
Sideload tool: Trollstore
Version of uYouPlus: v17.34.3-2.1

**Comment by qnblackcat** [comment]
You can discuss about the issue here: https://github.com/qnblackcat/uYouPlus/discussions/428

**Comment by qnblackcat** [comment]
This workaround should do the job: https://github.com/qnblackcat/uYouPlus/discussions/447

**Comment by qnblackcat** [comment]
Fixed in [v17.37.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.37.3-2.1) or higher
