### ISSUE TITLE
App Crash When Swiping Through Shorts [Bug]

### ISSUE THREAD

**Issue by MrAbattoir** [qnblackcat/uYouPlus#424]
### Device info
- iOS/iPadOS version: 16.0 (20A5358a)
- Device model: iPhone 13 Pro Max 256 , iPhone 10, iPhone 12 Pro Max
- Sideload tool: Sideloadly
- Version of uYouPlus: 2.1

### Describe the bug
When watching YouTube shorts, the app crashes after swiping through a few videos.

### How to reproduce the bug
Open shorts and swipe through a few videos

**Comment by qnblackcat** [comment]
Please update to v17.34.3-2.1 or higher
