### ISSUE TITLE
uYou+ repo “not compatible” with latest version of AltStore 

### ISSUE THREAD

**Issue by Squareheron942** [qnblackcat/uYouPlus#425]
As the title says, the repo linked in the downloads section doesn’t work with the newest version of AltStore so there’s no way to automatically have updates.

**Comment by qnblackcat** [comment]
Are you a patron of AltStore? Adding AltStore 3rd repo is only available in the beta version of AltStore, which only patrons of AltStore have access to

**Comment by Squareheron942** [comment]
Ah that must be it. I guess I should be reporting this to AltStore and not here, since their message is so vague. They have an option to add external repos but just tell you none of them are compatible.
