### ISSUE TITLE
[Questions] Anyone having issue with TrollStore that it cant install the Youtube Extension by CokePokes? 

### ISSUE THREAD

**Issue by mobochi** [qnblackcat/uYouPlus#426]
as https://www.reddit.com/user/opa334 released TrollStore 1.0.1 its possible to install the uYouPlus on iOS non JB devices and im one of those people, after installing the uYouPlus' latest version using TrollStore I noticed that the extension made by CokePokes as workaround to redirect YT links from Safari to the sideloaded uYouPlus is missing. The Sideloadly version does contain the extension but after uninstalling it and installing the uYouPlus through TrollStore its missing/gone.

edit: TrollStore post link: https://www.reddit.com/r/jailbreak/comments/x44cpj/free_release_trollstore_jailed_permasigned_app

**Comment by qnblackcat** [comment]
You really think this is an issue of uYouPlus?! For me, I don’t think so…
