### ISSUE TITLE
[Bug] latest version not installing

### ISSUE THREAD

**Issue by MarioMastr** [qnblackcat/uYouPlus#429]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16 Public Beta 4
- Device model: iPhone 11
- Sideload tool (Ex: AltStore, Sideloadly...) : AltStore
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_
17.34.3_2.1
### Describe the bug
It just doesn't install. It gives me this error. I've tried reinstalling AltStore, installing without extensions, rebooting my phone. It just doesn't work. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
![image](https://user-images.githubusercontent.com/84964352/188288464-99158b51-98ea-4907-9ddc-c418af61e099.png)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

### Additional context:

**Comment by MarioMastr** [comment]
This doesn't just apply to the latest version either.

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
