### ISSUE TITLE
[Bug] Disable age restriction doesn't work

### ISSUE THREAD

**Issue by JMcrafter26** [qnblackcat/uYouPlus#43]
**Device info:**
- iOS/iPadOS version: 15.2
- Device model:iPhone X
- Sideload tool (Ex: AltStore, Sideloadly...) Sideloadly.io
- Version of uYouPlus: newest

**Describe the bug:**
- disable age restriction doesn't work

**Comment by migmit** [comment]
15.2.2, iPad, AltStore, 17.1.4 — same thing.

**Comment by burgio777** [comment]
iPhone 13 Pro on iOS 15.6 same issue

**Comment by qnblackcat** [comment]
This is a server-side thing. We can do nothing about it.
