### ISSUE TITLE
[Bug] Can't login fix

### ISSUE THREAD

**Issue by svampebobber** [qnblackcat/uYouPlus#431]
Hey qnblackcat, love your work! Have you tried implementing this from juliovernes fork? He said he fixed the login. https://github.com/julioverne/uYouPlus/commit/2ff0f3fb56798f6482e2a5b4e126b4f93bc957fd - can you try implement this into your code?

**Comment by MrZomka** [comment]
It was already approved though?

**Comment by MrZomka** [comment]
Yep. It was already approved :(
![image](https://user-images.githubusercontent.com/25344028/188331000-719d6005-e3f1-4cff-ab91-975d19456695.png)

**Comment by svampebobber** [comment]
oh sorry
