### ISSUE TITLE
[Bug] Video length not showing on thumbnails (iPad only)

### ISSUE THREAD

**Issue by electroniix** [qnblackcat/uYouPlus#434]
### Device info
- iOS/iPadOS version: iPad Air 2020, iOS 15.0.1
- Sideload tool Trollstore
- Version of uYouPlus: Any

### Describe the bug
Problem only in subscriber-section

Not sure if its a bug or its a „feature“ on newer youtube versions on ipad only… If its a feature, please implement an option to bring back the video length

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
