### ISSUE TITLE
[Bug]无法下载，下载到了百分之百就就是错误4 Unable to move file from fi

### ISSUE THREAD

**Issue by betteruu** [qnblackcat/uYouPlus#437]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

### Additional context:

**Comment by qnblackcat** [comment]
Please complety the issue template
