### ISSUE TITLE
[Bug] Return YouTube Dislike not working with YouTube’s new UI

### ISSUE THREAD

**Issue by lululombard** [qnblackcat/uYouPlus#44]
**Device info:**
- iOS/iPadOS version: iOS 15.2
- Device model: iPhone 12 Pro Max
- Sideload tool: Signoulous
- Version of uYouPlus: v16.46.5-2.1

**Describe the bug:**
- The styling was updated and dislikes no longer show up

**How to reproduce the bug:**
_(Please attach videos or screenshots if possible)_
Load any video 
![image](https://user-images.githubusercontent.com/2182934/150157460-a22001b0-b73b-4b32-90a6-44245e790fb4.png)

**Crash log (if possible):**
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
No crash

**Additional context:**
_(Add any other context about the problem here)_

**Comment by qnblackcat** [comment]
Apparently, YouTube updated the new UI for (some!?) users, which broke RYD. 
Anyway, can you switch to another Google account?

**Comment by Henry-Villani** [comment]
I got the same issue.
If I sign in I get the new ui and dislikes stops working.
![Uploading B19A5DCC-6066-4AC6-926E-5F0C352C22E9.png…]()

**Comment by qnblackcat** [comment]
@PopeHensterIX Can we talk on Discord? You can contact me at Qn___#2870

**Comment by Void48** [comment]
I got the new UI. anything you need?

**Comment by migmit** [comment]
I have the old UI, no dislikes anyway.

**Comment by qnblackcat** [comment]
@migmit Poomsmart is working on it. Should be fixed soon I believe

**Comment by qnblackcat** [comment]
lol, I closed the wrong issue :/

**Comment by amberdambey** [comment]
Old UI and no dislike counter for me. I'm on the latest version
![DB808C87-395F-48E0-86EB-068A58ADEE2A](https://user-images.githubusercontent.com/99459304/155809583-761f4fd1-8460-41ea-814c-396da47694dc.jpeg)
Also, it'd be nice if the new swipe-up-in-fullscreen UI interface had its dislike count shown too. Just a suggestion

**Comment by migmit** [comment]
Actually, I've got a dislike counter under a video (not under the comments). I didn't do anything for that, it just happened.

**Comment by qnblackcat** [comment]
Enable **Fake YouTube version" in YouPiP's setting will bring back the old layout, which also allows RYD working correctly again

**Comment by arichorn** [comment]
I have the new UI. Everyone has it now since it’s been rolled out and Unfortunately YouTube Removed the Dislike Text/Counter so I have no idea how No Return Dislikes is gonna resolve that but right now we all should have YouPiP’s Fake YouTube Version Enable to see our dislikes & previous ui.
![BF9D446E-6D22-4EDA-8411-E2114A673B73](https://user-images.githubusercontent.com/78001398/184453246-9765d386-9a20-4f8d-97f1-1a448f754b74.jpeg)

**Comment by oomek** [comment]
Since my issue has been closed I'm posting here insted.
The dislike counter is gone again, it was working yesterday.
uYouPlus: v17.31.4-2.1

**Comment by arichorn** [comment]
I’m literally screwed too. The dislike counter is gone too.
The best thing we can do is enable YouPiP YouTube Fake Version until that eventually stops working too :(

**Comment by AbsurdIdealist** [comment]
Wait is the new ui out now?

**Comment by AbsurdIdealist** [comment]
Is it just for some channels or a universal thing now

**Comment by arichorn** [comment]
The new ui is officially out. It looks so bad and I hate how YouTube removed the Dislike Text. It’s like that they knew that was the only way to stop anyone from using Return YouTube Dislikes Tweak or Extension. and also I think desktop is gonna have this ui next.

**Comment by AbsurdIdealist** [comment]
it seems the latest ipa doesn’t have the new ui, how do you get it

**Comment by arichorn** [comment]
@AbsurdIdealist alright I went on uYouPlus and disabled the fake version and the new ui is gone, I didn’t notice I thought the new bad ui was still there, YouTube probably did that as a Server-Side change but still that new ui needs to not mess with the YouTube Return Dislike we use.

**Comment by oomek** [comment]
I actually had to enable fake version and the old ui with dislikes is back. Thaks for the tip.

**Comment by arichorn** [comment]
No problem!

**Comment by oomek** [comment]
Just noticed that enabling fake version breaks adding comments.

**Comment by arichorn** [comment]
> Just noticed that enabling fake version breaks adding comments. I see a spinner instead of an arrow button.

Same thing I’ll tell poomsmart about that

**Comment by qnblackcat** [comment]
RYD v1.6.8 has solved this issue and will be included in the next release
