### ISSUE TITLE
[Bug]VP9 randomly stops working for TrollStore version

### ISSUE THREAD

**Issue by gototheskinny** [qnblackcat/uYouPlus#441]
### Device info
- iOS/iPadOS version: 15.0
- Device model:ip12
- Sideload tool: TrollStore 1.0.7
- Version of uYouPlus: 17.35.3

### Describe the bug
vp9 randomly stops working and vids turnback to h264 (videos have vp9 versions)

### How to reproduce the bug
nothing to show bc i dont know what triggers this issue. TrollStore method supposed to be solve the native vp9 limitations.

### Does the issue happen with the official YouTube from AppStore?
NO
### Additional context:

**Comment by gototheskinny** [comment]
The issue is still there for v17.36.3

**Comment by PoomSmart** [comment]
YTUHD 1.2.10 will fix this issue.

**Comment by gototheskinny** [comment]
Thank you I appreciate it

**Comment by qnblackcat** [comment]
Fixed in **[v17.36.4-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.36.4-2.1)** or higher
