### ISSUE TITLE
[Bug] Fullscreen to the right not working after updating to iOS 16.

### ISSUE THREAD

**Issue by jouzka** [qnblackcat/uYouPlus#453]
### Device info
- iOS/iPadOS version: 16.0
- Device model: iPhone 12
- Sideload tool: Sideloadly
- Version of uYouPlus: v17.36.3-2.1

### Describe the bug

Ever since updating to iOS 16, the uYou option for opening videos in fullscreen to the right seems to have been broken, unless if using the dedicated button in the video player.

### How to reproduce the bug
Just activating the “fullscreen videos on the right” option in “other settings” section of uYou.

### Additional context: 
I’m sorry if this is an issue I should be reporting to uYou’s developer, which I’ll also be doing, but just in case I wanted to report this.

**Comment by tevyisertyin** [comment]
I'm on iOS 16.1 with uYouPlus 17.40.5-2.1, and "Fullscreen Videos on the Right" doesn't work using either method (clicking on YouTube's built-in Fullscreen button, or clicking on the "uYou Fullscreen to The Right" button that can be enabled in the "Video Controls Overlay" menu in uYou).

**Comment by jouzka** [comment]
> I'm on iOS 16.1 with uYouPlus 17.40.5-2.1, and "Fullscreen Videos on the Right" doesn't work using either method (tapping on YouTube's built-in Fullscreen button, or tapping on the "uYou Fullscreen to The Right" button that can be enabled in the "Video Controls Overlay" menu in uYou).

iOS 16.1 with uYouPlus 17.41.2-2.1. 

Strangely enough, tapping the “uYou Fullscreen to The Right” button from the “Video Controls Overlay” still works for me, and I do think it was also working on 17.40.5-2.1. I’m not sure why you’re experiencing this issue, but I do hope all these issues we’re having with uYou will get fixed soon. The automatic option for getting the fullscreen to right is still broken for me also.

**Comment by tevyisertyin** [comment]
> > I'm on iOS 16.1 with uYouPlus 17.40.5-2.1, and "Fullscreen Videos on the Right" doesn't work using either method (tapping on YouTube's built-in Fullscreen button, or tapping on the "uYou Fullscreen to The Right" button that can be enabled in the "Video Controls Overlay" menu in uYou).
> 
> iOS 16.1 with uYouPlus 17.41.2-2.1.
> 
> Strangely enough, tapping the “uYou Fullscreen to The Right” button from the “Video Controls Overlay” still works for me, and I do think it was also working on 17.40.5-2.1. I’m not sure why you’re experiencing it, but I do hope all these issues we’re having with uYou will get fixed soon. The automatic option for getting the fullscreen to right is still broken for me also.

I figure out what I was missing; I had to tap the "uYou Fullscreen to the Right" button twice to get the video to rotate 180 degrees. The automatic fullscreen to the right option remains broken.

**Comment by tevyisertyin** [comment]
> Try restarting ur iDevice

Unfortunately, that did not fix it for me.

**Comment by qnblackcat** [comment]
Please try [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)
