### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mikesheen32** [qnblackcat/uYouPlus#455]
- iOS/iPadOS version: ios 16
- Device model: iphone xs
- Sideload tool:  Sideloadly
- err 
![изображение](https://user-images.githubusercontent.com/69609903/190237371-14e30477-a8d2-4a63-8ca1-e3a7cc4ee0fe.png)

**Comment by parthnayak7448** [comment]
Hello I am also facing same error installing latest 17.36 version via altstore in my iPhone 12 pro max @qnblackcat

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by parthnayak7448** [comment]
@qnblackcat I tried to download uYou latest version but still receiving same error while installing 
Please if you can share exact steps to resolve it will be great help.
