### ISSUE TITLE
[Bug] Ads on search

### ISSUE THREAD

**Issue by jaff80** [qnblackcat/uYouPlus#456]
### Device info
- iOS/iPadOS version: iOS 15.7
- Device model: iPhone 7
- Sideload tool: AltStore
- Version of uYouPlus: v17.36.3-2.1

### Describe the bug
When you search for something, sometimes you get an ad.

### How to reproduce the bug
1: Open the app
2: search for a topic (example: Nintendo switch or fortnite)
[Image link](https://imgur.com/a/4KdYURF)

### Crash log (if possible)
The app does not crash

### Does the issue happen with the official YouTube from AppStore?
The official YouTube app does give you ads

**Comment by qnblackcat** [comment]
Duplicate of https://github.com/qnblackcat/uYouPlus/issues/81
