### ISSUE TITLE
[Bug] Various uYou settings don’t work

### ISSUE THREAD

**Issue by Hycade** [qnblackcat/uYouPlus#457]
Every option under the “Buttons under the video player” category in uYou settings don’t work. (Lemme know if additional info is needed). 

As of IOS 16, brightness gesture no longer works correctly. It’ll only adjust by 1 increment and that’s it. 

uYou repeat does not work in the background or until the video is reloaded at least 2-3 times. (Should use the native YT looper)

Note: not entirely sure how much control you have over uYou but I’m hoping these can be resolved.

**Comment by eliliam** [comment]
I see this was closed, but I am still seeing issues with the brightness gesture not working while on iOS 16.0.1 and using uYouPlus version v17.36.4-2.1

**Comment by Hycade** [comment]
> I see this was closed, but I am still seeing issues with the brightness gesture not working while on iOS 16.0.1 and using uYouPlus version v17.36.4-2.1

Closed because there’s already a report on it that has been officially responded too. These are all uYou issues. Plus I didn’t do the report properly anyways.
