### ISSUE TITLE
[Bug] Can not install latest version in ios 16

### ISSUE THREAD

**Issue by parthnayak7448** [qnblackcat/uYouPlus#458]
### Device info
- iOS/iPadOS version:  16.0
- Device model: iPhone 12 pro max
- Sideload tool (Ex: AltStore, Sideloadly...) tried with both 
- Version of uYouPlus: uYouPlus_17.36.3_2.1

### Describe the bug

when i try to install uYouplus or cercube below error appears 

I tried with both sideloadly and Altstore

I have paid developer account

I tried with remove app extensions and keep app extension as mentioned in FAQ but no solutions

### How to reproduce the bug

![91A5EC48-A1BA-40CB-9F43-FE1CD4C68C61](https://user-images.githubusercontent.com/19779385/190307507-d99b6fa1-4bce-4f23-82f0-a4c1566560b2.jpeg)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by qnblackcat** [comment]
Delele AltStore then re-install uYouPlus

**Comment by parthnayak7448** [comment]
@qnblackcat 

I tried every single thing but it is not happening its keep on saying same error

all others apps are installing correctly except cercubePlus or uYouPlus

please help me with this

it will be much appreciated please

**Comment by parthnayak7448** [comment]
Can I try to delete current cercube version and do brand new installation? 

I am afraid doing this will delete all my downloaded videos and audios. @qnblackcat

**Comment by rafaeldamasceno** [comment]
@qnblackcat This is definitely a new issue and different from #360. I haven't installed any YouTube app except uYouPlus since I purchased my phone (iPhone 13 Pro Max, iOS 16.0), and I also have the exact issue as here when installing v17.36.4-2.1.

v17.36.3-2.1 and under do NOT cause any issue with AltStore. So I'm guessing either the new YouTube version or the TrollStore changes are causing the issue.

**Comment by parthnayak7448** [comment]
Please install version previous v17.36.3-2.1 that will work fine. 

only uYou and Cercube version v17.36.3 and greater are causing issue I don't know we will able to use newer version untill bug is not resolved but for now we can keep using older version.

**Comment by qnblackcat** [comment]
@parthnayak7448 @rafaeldamasceno 

https://github.com/qnblackcat/uYouPlus/issues/466

This guy have uYouPlus v17.36.4-2.1 installed via AltStore on iOS 16.1. Yeah, definitely an issue of uYouPlus 😀

**Comment by rafaeldamasceno** [comment]
If we’re counting, I’d say there’s twice the amount of people having issues with installing the latest version 😜 All we have done is present the facts: every older version of uYouPlus installs without issue, latest version cannot be installed. 

In any case, I’m not here begging you to fix this or anything similar. In fact, the problem might really well be on AltStore/Sideloadly’s side.

What I would ask of you is if there was any change in the latest version in the extensions that would cause the sideloading apps to fail, so I could get better support from their side if you knew what caused this issue.

**Comment by qnblackcat** [comment]
> …every older version of uYouPlus installs without issue, latest version cannot be installed.

The latest version (17.36.4) was built the same way every other version was built. Not sure what's the difference here 🤔

***
> the problem might really well be on AltStore/Sideloadly’s side

Thank you for understanding it.

***
> What I would ask of you is if there was any change in the latest version in the extensions that would cause the sideloading apps to fail, so I could get better support from their side if you knew what caused this issue.

As I said above, all versions of uYouPlus were built the same way.

**Comment by parthnayak7448** [comment]
Can I try to delete current cercube version and do brand new installation?

I am afraid doing this will delete all my downloaded videos and audios.

**Comment by SethuSenthil** [comment]
I'm have the same issue on the newer versions! ![image](https://user- images.githubusercontent.com/20134046/198849827-7c57c255-0fdc-4b1b-9bd1-2dcc5279664c.png)
