### ISSUE TITLE
A Shortcut to open Safari links in uYouPlus

### ISSUE THREAD

**Issue by WoodpeckerBaby** [qnblackcat/uYouPlus#46]
One option is this for the developers to implement.

https://github.com/qnblackcat/uYouPlus/issues/37#issuecomment-1005084954

The other tried and tested option is to use a shortcut like the following. 

https://www.icloud.com/shortcuts/cb360215348541809221859bfb229d60

To make it run, you need to enable this in iOS Setting for the Shortcuts app. 

![image](https://user-images.githubusercontent.com/14303318/150652845-ad36f1c4-a754-42a4-b511-de22ac751f07.jpeg)

And you need to enable and click the shortcut in the Safari share menu activate it. Make share to select "always allow" for it to run on YouTube.com pages and open the mod YouTube app.

Enjoy!

**Comment by qnblackcat** [comment]
thanks, but I've already added this Shortcut to the FAQ page from the beginning
