### ISSUE TITLE
[Bug] PiP buffers

### ISSUE THREAD

**Issue by MarioMastr** [qnblackcat/uYouPlus#460]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.1 beta 2
- Device model: iPhone 11
- Sideload tool (Ex: AltStore, Sideloadly...): AltStore
- Version of uYouPlus:17.36.3-2.1

### Describe the bug
PiP buffers once I hit the button or go to the home button. Video example attached. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
1. Go to any video
2. Go to the home or press the button in the video control overlay to activate PiP
3. You may have to do it a few times to see it fully

https://user-images.githubusercontent.com/84964352/190477578-ec2f3f7b-8c44-496d-9ce2-5dae1eb2a21f.MOV

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_ well of course not (nvm apparently yes)

### Additional context:

**Comment by qnblackcat** [comment]
@PoomSmart this is kinda weird...

**Comment by PoomSmart** [comment]
The video takes forever to load.

**Comment by josheharvey** [comment]
Same issue here. iPhone 13 Pro running 16.1 beta.

**Comment by MarioMastr** [comment]
@qnblackcat I have more details for you. Turns out the delay is really varied between PiP activations. Sometimes it takes forever and sometimes it instantly activates. It's really strange.

**Comment by whibber** [comment]
Same issue. Started with 16.1.

**Comment by MarioMastr** [comment]
I think this is just an issue with the beta.

**Comment by josheharvey** [comment]
Interestingly if a video is in PIP (stuck in buffering screen) and it auto plays to the next video that one starts and plays normally in PIP.

**Comment by MarioMastr** [comment]
iOS 16.1 beta 2 appears to have just released, so I'll update and see if the issue has been fixed.

**Comment by MarioMastr** [comment]
Since updating to the new beta hasn't fixed things, I guess I'll say this:
I saw a temporary fix on Reddit. Once you activate PiP and see the buffer, go to Notification Centre and pause and resume the audio track

**Comment by asportnoy** [comment]
Can repro
iOS 16.1 DB2
iPhone 14PM
@MarioMastr's workaround above works for me

**Comment by gh0sti** [comment]
It has to be a bug with iOS 16.1 betas I'm sure Apple will fix it in a future beta. This happens in vanilla YouTube as well on 16.1 b2

**Comment by asportnoy** [comment]
Works fine in other apps (I tried Netflix and Nebula) so probably a YT bug if it happens on stock too

**Comment by MarioMastr** [comment]
Is it possible to get an update on work on any permanent fixes?

**Comment by Hycade** [comment]
Note: this is not an issue with uYou+, it’s a YouTube compatibility issue and cannot be resolved until 16.1 releases publicly. Currently there’s only 2 workarounds 

•Open the Camera
•Play/Pause from the control center, AirPods, or lock-screen.

**Comment by asportnoy** [comment]
> cannot be resolved until 16.1 releases publicly

Why is that? The iOS 16.1 release notes don't mention any API level changes, so I don't see why YouTube can't submit a fix to the app store.

Whether they would is a different story, but I'm curious as to why they can't.

**Comment by Hycade** [comment]
> Why is that? The iOS 16.1 release notes don't mention any API level changes, so I don't see why YouTube can't submit a fix to the app store.

Apple has yet to ever document all the changes to various API’s in their release notes especially after they’ve released the first public version (16.0). Until 16.1 releases publicly, apps with changes to compatibility cant be published to the App Store otherwise the approval process would return as denied.

**Comment by MarioMastr** [comment]
> > Why is that? The iOS 16.1 release notes don't mention any API level changes, so I don't see why YouTube can't submit a fix to the app store.
> 
> 
> 
> Apple has yet to ever document all the changes to various API’s in their release notes especially after they’ve released the first public version (16.0). Until 16.1 releases publicly, apps with changes to compatibility cant be published to the App Store otherwise the approval process would return as denied. 

Well twitch had a similar issue and a simple app update fixed it. Do I have any reason to believe that YouTube can't do the same thing?

**Comment by MarioMastr** [comment]
Another thing I just noticed is that the buffer takes substantially longer when you connect AirPods to the phone. Like without them PiP works in half a second, but with them it never finishes

**Comment by MarioMastr** [comment]
NOTE: If you have just updated or reinstalled the app and the issue appears to be fixed, don't be fooled. It hasn't. The issue will continue to rear its ugly head the more you use the newly installed app.

**Comment by MarioMastr** [comment]
It appears to be fixed with the latest developer beta (beta 3, it released like 2 hours ago), so this is your notice to update. I'll close the issue.
