### ISSUE TITLE
[Questions] CercubePlus: Hiding the SponsorBlock button in the Navigation bar

### ISSUE THREAD

**Issue by rakleed** [qnblackcat/uYouPlus#461]
Is it possible to hide the SponsorBlock button in the navigation bar like you did with the Cercube button?

**Comment by qnblackcat** [comment]
Then how could you acesss isponsorblock‘s setting?

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/issues/194#issuecomment-1151754382

**Comment by rakleed** [comment]
@qnblackcat is it possible then, instead of just hiding from the navigation bar, to transfer this button to YouTube settings or CercubePlus? Just then it would be convenient if all the settings were in one place.
