### ISSUE TITLE
[Bug] Cannot install 17.36.3_2.1 in AltStore

### ISSUE THREAD

**Issue by ToughPapaya** [qnblackcat/uYouPlus#462]
### Device info
- iOS/iPadOS version: 16.0
- Device model: iPhone SE 3 (2022)
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore
- Version of uYouPlus: 17.36.3_2.1

### Describe the bug
I have tried to install it at least 5 times. It always inexplicably stops at approximately 85%. This has never happened with any previous version of uYouPlus.

### How to reproduce the bug
Download the ipa file for 17.36.3_2.1. In Altstore, navigate to the "My Apps" tab. In the upper lefthand corner, click on the + icon. Select the ipa file. Click "Keep all extensions" when prompted.

### Crash log (if possible)
No crash log

### Does the issue happen with the official YouTube from AppStore?
N/A

### Additional context: 
Previous version of uYouPlus were installed on previous versions of ios (15.0 and 15.6). Could this be related? I did have to enable developer mode for uYouPlus to open after installing 16.0.

Edit: I am also having the same issue with installing the previous version, 17.35.3-2.1. I was able to install it in ios 15.6 but not 16.0. So is this an issue with 16.0? Also I have confirmed that developer mode is still enabled.

**Comment by Yunogamer** [comment]
all versions always do this to me, and only uyou does it.. always freezes and locks up altserver (have to force close it) process, have to delete uyou first then it will install.. but can never install on top of previous version to update it, like ALL other apps do fine..

**Comment by ToughPapaya** [comment]
> all versions always do this to me, and only uyou does it.. always freezes and locks up altserver (have to force close it) process, have to delete uyou first then it will install.. but can never install on top of previous version to update it, like ALL other apps do fine..

I always delete and install. I did that when I tried installing both versions I mentioned.

**Comment by qnblackcat** [comment]
Sorry but this is not something I can fix. I recommend you report an issue to the devs of AltStore.
