### ISSUE TITLE
error when installing with sideloadly

### ISSUE THREAD

**Issue by AdnanZXgamer** [qnblackcat/uYouPlus#463]
![image](https://user-images.githubusercontent.com/92264668/190535023-52e9dc16-7a91-4264-a523-b8eda4407432.png)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by AdnanZXgamer** [comment]
removed plugins i mean

**Comment by AdnanZXgamer** [comment]
hello?

**Comment by qnblackcat** [comment]
Then I have no idea. I suggest you use other tweaked YouTube apps
