### ISSUE TITLE
[Questions] Option to backup/restore all settings in the app/extensions?

### ISSUE THREAD

**Issue by Converseallstar95** [qnblackcat/uYouPlus#464]
I have the message extension plist error, so I always have to delete and reinstall the app to perform an update. Is it possible to add an option to backup YT app/uYou/SponsorBlock settings in one json, or similar, to be able to restore to after installing the app? Thanks!

**Comment by qnblackcat** [comment]
I don’t think it’s possible. I explained why the issue occur here https://github.com/qnblackcat/uYouPlus/issues/194#issuecomment-1151754382. If you feel annoyed every time updating the app, just remove all the extensions when AltStore asks you (or select Remove app extensions with Sideloadly)

**Comment by Converseallstar95** [comment]
> 

Thanks, yeah I've read that and understand the issue, but I do want the extensions. I don't have that issue on refreshing, only on updating the app over the app in place. Thanks though!

**Comment by qnblackcat** [comment]
You could always use the open in YouTube shortcut & Safari userscript

https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-deep-link-aka-open-in-the-youtube-app-doesnt-work
