### ISSUE TITLE
[Bug] uYouPlus disable background video playback doesn't work despite PiP removed from the IPA file

### ISSUE THREAD

**Issue by mchungy** [qnblackcat/uYouPlus#466]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version:  IOS 16.1
- Device model: iPhone 14 Pro
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore
- Version of uYouPlus: v17.36.4-2.1

### Describe the bug
Accroding to the FAQ section where it talks about removing background audio, it doesn't seem to work as I have tried it. 

### How to reproduce the bug
- Install the uYouPlus version 17.36.4-2.1
- Change .IPA to .zip to extract
- Extract
- Show packages of YouTube -> Frameworks 
- Delete PiP.dylib
- Compress Payload -> Change .zip -> .ipa
- Upload to AltServer

### Does the issue happen with the official YouTube from AppStore?
just altstore

**Comment by qnblackcat** [comment]
Where do you live? US I assume?

**Comment by mchungy** [comment]
I live in China

**Comment by qnblackcat** [comment]
This is kinda weird. On my test devices background playback only works when YouPiP is included. 

Have you tried to remove & reinstall the patched ipa?

**Comment by mchungy** [comment]
I have tried to remove and reinstall the patched IPA and it doesn’t seem to work.

Do you mind giving out the IPA file that you’ve created and see if it works on my IOS device?

**Comment by qnblackcat** [comment]
Did you turn off background playback in uYou‘s setting?

**Comment by mchungy** [comment]
There isn’t an option for that when i removed the the PiP.dyilb

**Comment by qnblackcat** [comment]
you need to remove YouPiP.dylib and disable background playback in uYou setting > Other settings

**Comment by mchungy** [comment]
I went through uYou setting and there isn't an option for Other Settings.

**Comment by qnblackcat** [comment]
You sure? uYou‘s setting is at the bottom right?

**Comment by mchungy** [comment]
Oh my, I didn't know there was a uYou settings button at the bottom right. I have checked through it and it seems to have fixed the issue. I thought it was through the YouTube Profile settings > uYouPlus. Thanks!

I think the FAQ should clarify a bit more on the steps on how to disable background playback but other then that. Thank you!
