### ISSUE TITLE
[Questions] Remove Playlist in Fullscreen

### ISSUE THREAD

**Issue by Pauli1Go** [qnblackcat/uYouPlus#467]
Is there any way to remove the Playlist Menu when in Fullscreen? If not could you add a Setting that deactivates this? Its really annoying.

**Comment by qnblackcat** [comment]
Can you just press the X button? :/

**Comment by Pauli1Go** [comment]
Yeah but it’s really annoying because it reopens every time und it’s such a dumb feature.

**Comment by qnblackcat** [comment]
```
%hook YTColdConfig
- (BOOL)isLandscapeEngagementPanelEnabled { return NO; }
%end
```

Add this code to uYouPlus.xm. Then build your own ipa. See https://github.com/qnblackcat/uYouPlus/wiki/Building for more info
