### ISSUE TITLE
[Questions] How come you say the google sign in is only for troll store users?

### ISSUE THREAD

**Issue by Dynasty-Dev** [qnblackcat/uYouPlus#469]
Hello, I have esign 4.6.3 (latest) with my gold tier subscription from udid and also the latest build of uyouplus and saw an option for troll store users to fix sign in. Before I enabled it I verified that I cannot sign in but after enabling it and restarting uyou it signed in fine and still works after a day. So I’m wondering why it said a troll store only, are there issues?

**Comment by qnblackcat** [comment]
Well, maybe keeping the default bundle ID makes the different. However, the vast majority of users don't have access to a paid certificate, therefore can't not keep the default bundle ID when sideloading the IPA. 
Anyway, a _complete_ solution for this problem has just been found and will be included in the next update
