### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by burgio777** [qnblackcat/uYouPlus#47]
**Device info:**
- iOS/iPadOS version: 15.3
- Device model: iPhone 13 Pro
- Sideload tool: AltStore
- Version of uYouPlus: 17.01.4_2.1

**Describe the bug:**
- even if i disable background video playing, when i exit the youtube app the video still plays in background.

**How to reproduce the bug:**
_(Please attach videos or screenshots if possible)_
go in to uYou settings, then navigate to "Other Settings" and disable background video playing 

**Crash log (if possible):**
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Additional context:**
_(Add any other context about the problem here)_

**Comment by qnblackcat** [comment]
see the FAQ

https://github.com/qnblackcat/uYouPlus/wiki/FAQ
