### ISSUE TITLE
[Bug] unable to re-install uYou Plus with sideloadly

### ISSUE THREAD

**Issue by firascriss7** [qnblackcat/uYouPlus#472]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16
- Device model: A11
- Sideload tool (Ex: AltStore, Sideloadly...) Sideloadly
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ uYouPlus_17.36.4_2.1

### Describe the bug

an error occurs when i try to re-install (to renew the 7 days period) on my iPhone X iOS 16 
![Sans titre](https://user-images.githubusercontent.com/29250587/191006874-213f34df-030c-4f36-8db4-f0b69d17b59f.png)
removing the app from my phone then clean install seems to fix it but i'm loosing my data with it
any help please

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

I can’t fix this problem.
