### ISSUE TITLE
[Questions] Edit to the FAQ in regard to Watch History Sync Fix: Check your DNS settings!

### ISSUE THREAD

**Issue by maxistviews** [qnblackcat/uYouPlus#476]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

I had an issue where I thought my watch history was not syncing despite disabling the youtube ads feature. Turns out it was just a DNS issue. I recently installed pihole and forgot to whitelist google's domains: https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212

It may be useful to add to the "The timestamp of videos in History, Playlist, Watch later is missing!" section in the FAQ that if this workaround doesn't work, Check your DNS settings!

![image](https://user-images.githubusercontent.com/17325179/191344914-a1b0e5b8-4b00-43bd-aa86-73a1f0526e15.png)

###

**Comment by qnblackcat** [comment]
Done
