### ISSUE TITLE
[Bug] uYou+ freezes when watch certain video

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [qnblackcat/uYouPlus#477]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iPadOS 15.3.1
- Device model: iPad Pro (10.5 inch)
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 17.37.3_2.1

### Describe the bug
I just updated uyou+ to 17.37.3_2.1, and now whenever I try to watch this video https://youtu.be/UPFyMA4WtYI the app basically freezes. It still plays the video, but I can't do anything. When closing the app, it keeps playing the audio for a little bit, which is weird.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Install uYouPlus 17.37.3_2.1, then go watch this video https://youtu.be/UPFyMA4WtYI

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
No, I don't think so. Plus, I don't even have it on my device. It does work in the previous release, so I switch to that version, at least until the issue is fixed.

**Comment by qnblackcat** [comment]
For now, disable iSponsorBlock

**Comment by ego-lay-atman-bay** [comment]
Well in that case, I might as well just stick to the previous version for now.

**Comment by qnblackcat** [comment]
Sure. I deleted the release

**Comment by ego-lay-atman-bay** [comment]
Oh, ok
