### ISSUE TITLE
Crashes when watching a video [Bug]

### ISSUE THREAD

**Issue by f1shpie** [qnblackcat/uYouPlus#478]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0
- Device model: iPhone 12
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_
17.34.3_2.1
### Describe the bug
App crashes whenever a video is clicked on.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

https://imgur.com/a/4FChuI4

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

https://pastebin.com/j7vYw6ka

### Does the issue happen with the official YouTube from AppStore? 
_(Well, YouTube itself is buggy sometimes...)_
No.
### Additional context: 
This only started happening earlier today

**Comment by TinTran64** [comment]
I'm having the same issue with similar stacktrace

**Comment by qnblackcat** [comment]
Developers spend time and effort to fix bugs in every release, but you refuse to update and then complain about problems? Please update to the latest version

**Comment by f1shpie** [comment]
Ah sorry I didn't notice there was an update

**Comment by edwardthehuman** [comment]
> Developers spend time and effort to fix bugs in every release, but you refuse to update and then complain about problems? Please update to the latest version

So aggressive! 😎”refuse” and “complain” bold words for a bug report. 👊

**Comment by f1shpie** [comment]
haha its no problem at all, no worries. i know how annoying end users can be while developing, i never thought i'd end up being one but here i am not even checking for an update.... it was a silly mistake on my end, cheers for creating such an awesome app dude :)
