### ISSUE TITLE
[Bug] No sponsorblock colors in seek bar

### ISSUE THREAD

**Issue by HmmSad** [qnblackcat/uYouPlus#48]
**Device info:**
- iOS/iPadOS version: 15.2.1
- Device model: iPhone XS Max
- Sideload tool: AltStore
- Version of uYouPlus: v17.01.4-2.1

**Describe the bug:**
- The video doesn't contain the sponsorblock colors in the seek bar

**How to reproduce the bug:**
Just open any video that would contain either an intro or an ad.
Ex. 
![6D6AE3F0-AD3A-46FA-8410-FC0590858E54](https://user-images.githubusercontent.com/97488923/151194224-2d517814-030b-432f-b5aa-4b21d4108478.jpeg)
Normal: 
![8F30C82E-CFBF-4102-9399-48E327D151C4](https://user-images.githubusercontent.com/97488923/151308317-ebfb1aa9-8a06-49c0-be8c-3d2d770cc514.jpeg)

It had worked in the last version: v16.46.5-2.1

**Comment by HmmSad** [comment]
Reinstalling seems to have fixed this issue.

**Comment by HmmSad** [comment]
I have tried reinstalling the app which causes the colors to appear, however after closing and relaunching the app it seems to have caused it to break and not appear.

**Comment by sleeping10** [comment]
Same problem

- iOS/iPadOS version: 15.3
- Device model: iPhone SE (2020)
- Sideload tool: AltStore
- Version of uYouPlus: v17.01.4-2.1

**Comment by asportnoy** [comment]
- iOS/iPadOS version: 15.4 (Developer Beta)
- Device model: iPhone XR
- Sideload tool: AltStore
- Version of uYouPlus: v17.01.4-2.1

**Comment by pelegs29** [comment]
fixed for me with the new update : v17.04.3-2.1 !

**Comment by asportnoy** [comment]
Can confirm also fixed for me. Side note: the release's title still has the old version number(v17.01.4-2.1)

**Comment by qnblackcat** [comment]
> Can confirm also fixed for me. Side note: the release's title still has the old version number (v17.01.4-2.1)

thank you for pointing it out <3
