### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by YungCatgirl** [qnblackcat/uYouPlus#480]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16.0
- Device model: iPhone 11
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 17.34.3

### Describe the bug

When i try to watch a video it crashes instantly. Previews are okay, but I can't watch anything.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

idk i just tried watching a video

https://www.youtube.com/watch?v=weD0rXYvOjU

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
https://pastebin.com/syp1jgzK
### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
nope, it doesn't.
### Additional context: 
new to iphones as well as reporting issues so sorry if i messed something obvious up

**Comment by baba420** [comment]
Are you on the latest release? Mine installation had the same problem like yours, but then I gave the latest version a try and everything was fine again.

**Comment by jobnbackpack** [comment]
I have the same issue since today.

**Comment by LeonDerDr** [comment]
I had the same issue today. 
v17.36.4-2.1 fixed it for me!

**Comment by dayanch96** [comment]
its sponsorblock bug. causes only in videos with sponsored segments
