### ISSUE TITLE
17.36.3-F2 TrollStore hw vp9 codec issue[Bug] 

### ISSUE THREAD

**Issue by gototheskinny** [qnblackcat/uYouPlus#486]
### Device info
- iOS/iPadOS version: ios 15.0
- Device model:ip12
- Sideload tool :TrollStore
- Version of uYouPlus: v17.36.3-F2

### Describe the bug
This update(v17.36.3-F2) broke vp9 hardware decoder support that came with TrollStore method. on v17.36.3 this problem doesn't occur.

### How to reproduce the bug
I guess there is no need for screenshots. 
u install f2 version instead of the previous build on an iphone 12 ios15.0 with TrollStore and there it is u just lost your vp9 hw decoding functionality.

### Does the issue happen with the official YouTube from AppStore?
its not about the official version.

**Comment by gototheskinny** [comment]
![image](https://user-images.githubusercontent.com/51786709/191773461-d8c8d804-b686-4076-a031-1552379bcaa0.jpeg)
Hardware support:1 shows up as 0 in f2 version

**Comment by qnblackcat** [comment]
That's really weird. Try [this](https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/Ecr58Mc1HiFJlfsmcEInTccB2Vi2_jox3v0h75CpSx9uDA?download=1)

**Comment by qnblackcat** [comment]
Fixed in [v17.37.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.37.3-2.1) and higher

**Comment by plooshi** [comment]
@qnblackcat is A10 supposed to have hardware VP9 because uyouplus says it doesnt

**Comment by qnblackcat** [comment]
@plooshi what is the value of “Hardare VP9 support”?

**Comment by gototheskinny** [comment]
> Fixed in [v17.37.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.37.3-2.1) and higher

Thank you! I appreciate it

**Comment by plooshi** [comment]
> @plooshi what is the value of “Hardare VP9 support”?

0

**Comment by qnblackcat** [comment]
If you‘re using v17.37.3-2.1 & the app was installed via TrollStore and “Hardare VP9 support” = 0, then your device is definitely not support hardware vp9.

**Comment by plooshi** [comment]
> If you‘re using v17.37.3-2.1 & the app was installed via TrollStore and “Hardare VP9 support” = 0, then your device is definitely not support hardware vp9.

i thought A10 did though... insteresting

**Comment by minbcrafter** [comment]
> If you‘re using v17.37.3-2.1 & the app was installed via TrollStore and “Hardare VP9 support” = 0, then your device is definitely not support hardware vp9.

Hello, I am on A11 (iPhone X, A11, iOS 15.1, installed through TrollStore) and “Hardware VP9 Support” is still showing 0. Any idea what I might be doing wrong? Because I also see that it says “requires CPU A11 or higher”, so I think the iPhone X should support VP9?

**Comment by qnblackcat** [comment]
@minbcrafter I‘m sorry, what version are you on?

**Comment by minbcrafter** [comment]
> @minbcrafter I‘m sorry, what version are you on?

17.39.5-2.1

**Comment by qnblackcat** [comment]
@minbcrafter and your version of TrollStore?

**Comment by minbcrafter** [comment]
> @minbcrafter and your version of TrollStore?

1.1.2

**Comment by qnblackcat** [comment]
Well, can you see 2k/4k quality with vanilla YouTube?

**Comment by minbcrafter** [comment]
> Well, can you see 2k/4k quality with vanilla YouTube?

Nope I cannot. The highest is 1080p

**Comment by qnblackcat** [comment]
@PoomSmart well, looks like VP9 codec needs A12+ chip

**Comment by gototheskinny** [comment]
> > Well, can you see 2k/4k quality with vanilla YouTube?
> 
> 
> 
> Nope I cannot. The highest is 1080p

Can you check stats for nerds in AppStore YouTube and look for video codec?
Is it vp09 or avc1? . Bc it could be a limitation on older devices and maybe there is a 1080p limitation for vp09 codec on a11.
