### ISSUE TITLE
[Bug] Disable background playback doesn’t work

### ISSUE THREAD

**Issue by Dr-Sauce** [qnblackcat/uYouPlus#488]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 15
- Device model: iPhone X
- Sideload tool (Ex: AltStore, Sideloadly...) TrollStore
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ v17.36.4-2.1-F2

### Describe the bug

Disabling background playback doesn’t disable the feature.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

Image is just for explanation.
![IMG_1762](https://user-images.githubusercontent.com/82555878/191912808-a115dbc4-647c-4cda-a40b-93e14be1cd03.jpeg)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
