### ISSUE TITLE
Binaries in latest IPA have no entitlements [Bug]

### ISSUE THREAD

**Issue by opa334** [qnblackcat/uYouPlus#489]
```
ldid -e /Users/opa334/Desktop/Payload/YouTube.app/YouTube
ldid: -e, -q, and -h requre a signed binary
```

In earlier versions they had entitlements. This causes several problems with TrollStore such as uYou downlods giving an error and other stuff.

**Comment by qnblackcat** [comment]
@opa334 oh I see. I totally forget that the Github action uses the default branch of theos-jailed, which completely removes all the binary‘s entitlements. This also explains issue #486

**Comment by qnblackcat** [comment]
For now, I'm using the ``--no-strip-codesig`` flag to keep the entitlements of the binary. Is there any advantage when using FAKESIGN_IPA?

https://github.com/kabiroberai/theos-jailed/blob/61a1999369502a76b210991dd0e5381abac8e7fc/module/bin/ipa.sh#L60
```
"$INSERT_DYLIB" --inplace --no-strip-codesig "@rpath/$(basename "$file")" "$app_binary"
```

**Comment by opa334** [comment]
ah lol I wasn't aware that was a thing, will update my fork, in general yes, because the stuff that comes after it will still make it loose it's entitlements, although I'm not 100% sure on that

**Comment by qnblackcat** [comment]
Are you sure? I have been using the `--no-strip-codesig` flag from the beginning, and all the entitlements are safe...

**Comment by opa334** [comment]
Hmm actually I'm not sure, it's probably fine if it worked for you before
