### ISSUE TITLE
[Bug] Dislike counts don't show up in landscape video suggestions

### ISSUE THREAD

**Issue by JacksonChen666** [qnblackcat/uYouPlus#49]
**Device info:**
- iOS/iPadOS version: iOS 15.0
- Device model: iPhone X
- Sideload tool (Ex: AltStore, Sideloadly...): AltStore
- Version of uYouPlus: uYouPlus_16.46.5_2.1 (not sure how to actually determine such info, so filename from download)

**Describe the bug:**
- The dislike count in the video suggestions while in landscape doesn't show the actual count

**How to reproduce the bug:**
- Open normal video
- Switch to landscape mode
- Swipe up to bring up video suggestions
- See dislike count
![Dislike count in landscape](https://user-images.githubusercontent.com/50755746/151457227-2689d6e5-99ef-45b5-8b72-98ab532bca59.jpeg)

**Crash log (if possible):**
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Additional context:**
The dislike count that already changes works as expected:
![Dislike count in portrait](https://user-images.githubusercontent.com/50755746/151457224-ca07ae2f-9fc1-4e28-b033-795e02451856.jpeg)

**Comment by qnblackcat** [comment]
Will be fixed in the next update

**Comment by qnblackcat** [comment]
Fixed in v17.04.3-2.1
