### ISSUE TITLE
[Bug] Background playback not possible on iPhone 14 Pro

### ISSUE THREAD

**Issue by Fichti92** [qnblackcat/uYouPlus#492]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16.0.2
- Device model: A2894 (14 Pro Max EU)
- Sideload tool Sideloadly
- Version of uYouPlus: 17.37.3_2.1.

### Describe the bug

When I listen Music or watch a video and I lock my screen, the music stops playing in the background.
But only on my new iPhone 14 Pro Max on my iPhone 12 Pro Max uYou works perfect.

The Same problem with Cercube. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by qnblackcat** [comment]
iOS behavior. See FAQ
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
