### ISSUE TITLE
[Bug] App crashes when playing video?!?

### ISSUE THREAD

**Issue by harisshaukat96** [qnblackcat/uYouPlus#497]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: ipados15.6.1
- Device model: iPad Air pro 11 inch
- Sideload tool (Ex: AltStore, Sideloadly...) altstore
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ uyou 2.1

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_ press a video?

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_ idk 

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_ I don’t know

### Additional context: 
IT CRASHES WHEN I PRESS ANY VIDEO

**Comment by fflorf** [comment]
Same happening to me

**Comment by WoodpeckerBaby** [comment]
Exactly same to me. Latest version. Started happening 1 hour ago.

**Comment by SenorWhyMe** [comment]
same just started to happen an hour ago sad enough shorts are the only thing that works

**Comment by WoodpeckerBaby** [comment]
Yeah, shorts are working but nothing else. Also seeing ads when searching.

**Comment by qnblackcat** [comment]
@harisshaukat96 @fflorf what is your version of uYouPlus? Also please update the crashlog

**Comment by SenorWhyMe** [comment]
v2.1 17.31.4

**Comment by qnblackcat** [comment]
> v2.1 17.31.4

Why don’t you update to the newest version!?? A dozen of issues have been fixed already

**Comment by SenorWhyMe** [comment]
will do just recently updating uyou never worked i have to delete the app from altstore then install it and re do all my settings

**Comment by SenorWhyMe** [comment]
> > v2.1 17.31.4
> 
> 
> 
> Why don’t you update to the newest version!?? A dozen of issues have been fixed already

updated it works

**Comment by fflorf** [comment]
Deleting the old version off my phone and downloading it again with the new version (v17.37.3-2.1), fixed everything.

**Comment by WoodpeckerBaby** [comment]
Just want to add that it seems that it only affects iPhone, but not iPad.

**Comment by qnblackcat** [comment]
> Exactly same to me. Version 17.34.3. Started happening 1 hour ago.

Why on earth are you staying on this old version? Do you know how many bugs has been fixed in the newer version? Please update to the latest version

**Comment by SenorWhyMe** [comment]
> > Exactly same to me. Version 17.34.3. Started happening 1 hour ago.
> 
> 
> 
> Why on earth are you staying on this old version? Do you know how many bugs has been fixed in the newer version? Please update to the latest version 

because your app doesn't update within altstore always fails so I don't update it manually

**Comment by qnblackcat** [comment]
@SenorWhyMe it’s not my fault AltStore failed to update the app. See the FAQ https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by SenorWhyMe** [comment]
> @SenorWhyMe it’s not my fault AltStore failed to update the app. See the FAQ https://github.com/qnblackcat/uYouPlus/wiki/FAQ

not blaming you just don't have time to manually update especially now with work , already know it's a altstore problem

**Comment by WoodpeckerBaby** [comment]
I have been having issue updating the app, even after deleting the original.![image](https://user-images.githubusercontent.com/14303318/192556114-16514cf9-7fd5-4105-96ef-dfc3a0c39103.jpeg)

**Comment by qnblackcat** [comment]
@WoodpeckerBaby well that sucks. Try to remove & reinstall AltStore as well

**Comment by qnblackcat** [comment]
Closed due to inactive
