### ISSUE TITLE
I can’t seem to install uyou+ over the previous version

### ISSUE THREAD

**Issue by hassan-waris** [qnblackcat/uYouPlus#498]
Hi as the title suggests I keep having to delete uyou+ everytime a new version comes out which is very annoying because I have downloaded content like music which I listen to a lot.

I have added a screenshot of what error I’m getting. 

If it helps I am using a iPhone 13 Pro Max running on iOS 16.1 beta 2

@
![54C6446B-3CE2-4E6E-B8C1-F4FDB9AD32FD](https://user-images.githubusercontent.com/29949941/192500665-c75fcdda-d46c-4b15-b837-17f680a26425.png)

**Comment by hassan-waris** [comment]
I’ve already tried deleting and re installing altstore… still no luck and then to take a step further I’ve even restored my iPhone but still no luck

**Comment by qnblackcat** [comment]
This is not something I can fix. See https://github.com/qnblackcat/uYouPlus/wiki/FAQ for more info
