### ISSUE TITLE
The PiP has a bug can’t seem to figure it out

### ISSUE THREAD

**Issue by hassan-waris** [qnblackcat/uYouPlus#499]
Basically I use Picture in Picture all the time, but recently I updated to the latest version on uyou+ and pip doesn’t seem to work I can hear the video playing but the picture isn’t showing at all,

when I went to go try make a screen recording just now for this post, I found that it shows up but I have to screen record first then the video will start working like nothing happened but I need to do this for every video I wanna play in YouTube

I’ve attached both screenshot and screen recording

https://user-images.githubusercontent.com/29949941/192515211-d7dd81b9-7cd3-44a1-87d5-10966a7a0e18.MOV

![065DE894-C6D3-4475-9C91-AA7F851D5A23](https://user-images.githubusercontent.com/29949941/192514863-5260ac86-a8ca-4cdc-808d-0761bf11a88e.png)

**Comment by MarioMastr** [comment]
Update to 16.1 beta 3
