### ISSUE TITLE
"Error fetching channel list for account"

### ISSUE THREAD

**Issue by MHX792** [qnblackcat/uYouPlus#5]
Login works, but this error persists and prevents showing subscriptions.

**Comment by qnblackcat** [comment]
Have you tried to delete the regular YouTube app?

**Comment by qnblackcat** [comment]
Closed due to inactive!

**Comment by CobreDev** [comment]
I'm having this same issue too, any ideas what the fix is? I'm on 15.1 on a 13 mini, with the stock YouTube app deleted

**Comment by qnblackcat** [comment]
> I'm having this same issue too, any ideas what the fix is? I'm on 15.1 on a 13 mini, with the stock YouTube app deleted

Well, I suggest you try another sideload tool.

**Comment by CobreDev** [comment]
> > I'm having this same issue too, any ideas what the fix is? I'm on 15.1 on a 13 mini, with the stock YouTube app deleted
> 
> Well, I suggest you try another sideload tool.

Anything I try is the same, whether that's Impactor (I'm part of an organization), SignTools, or Sideloadly

**Comment by qnblackcat** [comment]
> > > I'm having this same issue too, any ideas what the fix is? I'm on 15.1 on a 13 mini, with the stock YouTube app deleted
> > 
> > 
> > Well, I suggest you try another sideload tool.
> 
> Anything I try is the same, whether that's Impactor (I'm part of an organization), SignTools, or Sideloadly

I think a factory reset may help (It sucks I know)

**Comment by CobreDev** [comment]
Meh, I don't care about it *that* much

**Comment by edgeyboy** [comment]
I've had this issue using signtools with a random ID.

Using one that is `com.google.ios.youtube.whatever` resolved it.

**Comment by LeonManolo** [comment]
> In case anyone else is having this issue: I've had this issue using signtools with a random ID.
> 
> Using one that is `com.google.ios.youtube.whatever` resolved it.

Thanks working now!

**Comment by MHX792** [comment]
How did you do it? @edgeyboy @LeonManolo ? You can't register identifiers beginning with `com.google.ios.youtube.` on apple developer website: Error: 'An attribute in the provided entity has invalid value'

**Comment by LeonManolo** [comment]
> How did you do it? @edgeyboy @LeonManolo ? You can't register identifiers beginning with `com.google.ios.youtube.` on apple developer website: Error: `An attribute in the provided entity has invalid value – An App ID with Identifier 'com.google.ios.youtube.whatever' is not available. Please enter a different string.`

Yes the part "whatever" should be whatever you want. The whole id has to be unique "com.google.ios.youtube.heresomethingunique"
