### ISSUE TITLE
[Questions] Disabling features

### ISSUE THREAD

**Issue by JagodekSTREAM** [qnblackcat/uYouPlus#50]
Is there any way to disable this uyou features when watching a video?

**Comment by qnblackcat** [comment]
uYou‘s settings > Video controls overlay

**Comment by JagodekSTREAM** [comment]
where are the uyou's settings?

**Comment by qnblackcat** [comment]
At bottom-left of the app

**Comment by JagodekSTREAM** [comment]
ty im stupid sorry
