### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by nimatih** [qnblackcat/uYouPlus#500]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0.1
- Device model: iPhone 14 Pro Max
- Sideload tool (Ex: AltStore, Sideloadly...) Sideloadly
- Version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ [v17.37.3-2.1]

### Describe the bug
This bug/issue is still ongoing and as per my previous post many people are also facing this bug.
You can't reinstall the IPA until you delete the app completely (which also wipes out the data inside the app). 
The issue isn't with Sideloadly because other apps (even uYou Plus OLED) reinstalls without an issue.

The error is same as previous one. 

There was an issue during installation: 0: PackageInspectionFailed (Failed to load Info.plist from bundle at path /private/var/containers/Bundle/Application/C3F95083-1849-4441-9CE8-DCD10B61A327/YouTube.app/PlugIns/MessagesExtension.appex; Extra info about "/private/var/containers/Bundle/Application/C3F95083-1849-4441-9CE8-DCD10B61A327/YouTube.app/PlugIns/MessagesExtension.appex/Info.plist": Couldn't stat /private/var/containers/Bundle/Application/C3F95083-1849-4441-9CE8-DCD10B61A327/YouTube.app/PlugIns/MessagesExtension.appex/Info.plist: No such file or directory)

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by qnblackcat** [comment]
Check the FAQ: https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by qnblackcat** [comment]
And no. Nothing I can do about this issue
