### ISSUE TITLE
[Bug] Battery Drain and Background Closing

### ISSUE THREAD

**Issue by Blarnix** [qnblackcat/uYouPlus#502]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0.2 (20A380)
- Device model: iPhone 14 Pro Max A2651
- Sideload tool: AltStore 1.6b2
- Version of uYouPlus: v17.37.3 - 2.1

### Describe the bug: YouTube (possibly the new version in the latest release) is suddenly pretty bad on the iPhone 14 Pro Max. Battery drains quick (VP9 is off), the app will not stay in the background for more than 30 seconds to a minute, and I've seen lots of black screens when opening videos lately, can't seem to pin it down to the cause (possibly video quality in YouTube's settings??). Unsure if this is a cause by uYou+, but something about the new version seems to have this more.

I've also seen some unblocked ads, specifically when searching for videos. Also when searching for videos, I can't click some of them. Usually after I scroll for a little bit. Again, unsure why this is, I've tried to pin these issues down, but I'm really not sure. 

### How to reproduce the bug: As for the black screen, it's hard to reproduce as it's pretty random. It usually happens when you first open the app. After closing and playing the video again, it goes away for a bit. 
In the video I can't get either of those to happen (can't seem to cause them at will), but the Ad is visible in it. But to recreate it, you search for a video, scroll a bit, and click on a video to play it but it doesn't play. If you need more details, let me know.
![image](https://user-images.githubusercontent.com/61402697/192856183-168bfcb6-4c26-4f24-943b-6412851ba2bf.png)

https://user-images.githubusercontent.com/61402697/192856339-5d3fbdd7-e61e-440c-b703-b117ddec3e04.MOV

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_ 

Unsure, can't recreate in official app.

### Additional context:

**Comment by qnblackcat** [comment]
Can you update your version of iOS?

**Comment by Blarnix** [comment]
Not without enrolling in a beta version of iOS, no. I'm on the latest public release.

**Comment by hieunt1407** [comment]
It's happening to me as well. I was listening to live video and device getting extreme hot and drain battery when leave in background

**Comment by qnblackcat** [comment]
Any update on this?

**Comment by CurssedCoffin** [comment]
Same there. I charged up to 98% last night and set remind me later then leave it on the background. When I wake up this morning the battery was only 3%. Maybe I will provide a log later.
![ABE499CE-229A-414A-9402-1166B5E31E0F](https://user-images.githubusercontent.com/49067137/210025799-98d07922-32e2-48e2-9ae3-be981722649b.png)

**Comment by CurssedCoffin** [comment]
I‘m not sure if it's still background playing things. Maybe not, because it cannot use such a battery mount in 5 hours. I cannot find a log anywhere. It would be great if you can help me solve this problem.
Also, this happens randomly. I could meet this situation two or three times a month.
