### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by Kynastone** [qnblackcat/uYouPlus#504]
I have 2 problems. 
1. the app will crash watching shorts after i scroll the third. (Not entirely a bad thing since sometimes you just can’t stop scrolling 😅)
2. I use altstore, the signing was overdue so i refreshed my 2 sideloaded apps. 
the first works fine, uyou+ have one additional problem. Whenever i try to play a video it instacrash. Previewing a video is just fine.

**Comment by Kynastone** [comment]
Why fhe heck did someone closed my issue ???

**Comment by qnblackcat** [comment]
If you think it’s a bug. Open a new issue with the Bug template.

**Comment by Kynastone** [comment]
Ok a bit more of communication wouldn’t hurt though…
