### ISSUE TITLE
[Bug] RYD crashes Settings in uYouPlus v17.38.10

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#511]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.7
- Device model: iPad Pro M1
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) AltStore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 17.38.10 (preview)

### Describe the bug
Settings straight up crash in this version of YouTube. YouTube might’ve changed the methods on the settings page but I can’t confirm it or not.

### How to reproduce the bug
https://user-images.githubusercontent.com/78001398/193421478-804b80d6-af65-4b0f-b7ba-e758306d0ea7.mp4

### Crash log (if possible)
[October 1st 2022 uYouPlus CrashLog.txt](https://github.com/qnblackcat/uYouPlus/files/9690886/October.1st.2022.uYouPlus.CrashLog.txt)

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_ well yeah but using a newer version that wasn’t public on uYouPlus yet.

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_ nope. 👎

**Comment by qnblackcat** [comment]
wow, you report an issue on a version that doesn't even exist...

**Comment by level3tjg** [comment]
@PoomSmart Looks like this is caused by RYD localization not having a default value passed to `-[NSBundle localizedStringForKey:value:table:]`

**Comment by arichorn** [comment]
> wow, you report an issue on a version that doesn't even exist...

Well it exists in my repository, I was only telling you right now so you wouldn’t release it right now and let everyone have the settings crash

**Comment by PoomSmart** [comment]
@arichorn In your side loaded YouTube, is there a bundle called `RYD.bundle` ?

**Comment by PoomSmart** [comment]
I suspect `Makefile` needs to be updated for RYD.

**Comment by PoomSmart** [comment]
6b799b5c014cb9c38f44d5ce4b2f9bdd86624863 Updated/

**Comment by arichorn** [comment]
Awesome! I’ll try it in a bit!
