### ISSUE TITLE
[Bug] Take a Break

### ISSUE THREAD

**Issue by RssolYeet** [qnblackcat/uYouPlus#513]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0.2
- Device model: iPhone 13 Pro
- Sideload tool: AltStore
- The specific version of uYouPlus: v17.37.3-2.1

### Describe the bug
Cannot turn on remind me to take a break

### How to reproduce the bug
Try to turn it on
The toggle will light up. But once you hit confirm, the toggle will turn off automatically. 

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by qnblackcat** [comment]
Just disable “Remove YouTube Ads” in uYou‘s settings > Other settings. It won‘t affect the ability to block ads

**Comment by RssolYeet** [comment]
Where do you see this? All I can see is uYouplus settings and in there, there isn't an other setting section.

**Comment by qnblackcat** [comment]
uYou‘s settings is literally at the bottom right of the app?

**Comment by RssolYeet** [comment]
Sorry, was covering it up so I missed it. Solved.
