### ISSUE TITLE
[Bug]Missing Skip Ad button when using Chromecast

### ISSUE THREAD

**Issue by SenorWhyMe** [qnblackcat/uYouPlus#52]
**Device info:**
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: 

**Describe the bug:**
- 

**How to reproduce the bug:**
_(Please attach videos or screenshots if possible)_

**Crash log (if possible):**
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Additional context:**
_(Add any other context about the problem here)_

**Comment by qnblackcat** [comment]
I can see the skip ad button when casting to my TV. 
![IMG_3035](https://user-images.githubusercontent.com/52943116/162578493-cb14a8f5-e824-4f20-9986-740d8cab3305.jpg)

**Comment by SenorWhyMe** [comment]
weird seems to never show up for me

**Comment by qnblackcat** [comment]
Have you disabled the ads blocker of uYou?

**Comment by SenorWhyMe** [comment]
i haven't done that, didn't know i was supposed to , for chrome cast

**Comment by qnblackcat** [comment]
@SenorWhyMe you definitely should disable that option. Do it and lmk if the issue persists

**Comment by qnblackcat** [comment]
Close due to inactive
