### ISSUE TITLE
[Bug] 4k and above missing.

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#520]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16 dev beta 4 and 16.0.2
- Device model: 12
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_: 17.39.4_2.1.ipa

### Describe the bug
You can't choose 4k video quality and above. It gets cut off at 1080p.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

https://youtu.be/LXb3EKWsInQ
Open the quality selector.

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_: did

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_: nope

### Additional context: 
**YT will force you to pay for Premium in order to view vids in 4k in the near future.**

Please read this article and add a workaround in the near future if possible: https://appleinsider.com/articles/22/10/04/get-ready-to-pay-to-see-4k-video-on-youtube

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
