### ISSUE TITLE
[Bug] YouRememberCaption not working

### ISSUE THREAD

**Issue by k3v1nwrld** [qnblackcat/uYouPlus#522]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.0.2
- Device model:iPhone 11 Pro
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): TrollStore
- The specific version of uYouPlus: 17.38.10_**latest** or **newest** is NOT a version number!!_

### Describe the bug
So YouRememberCaption doesnt work when I play videos from subscriptions page.When I play vids from home page, it works fine.Youtube did something after v17.32.2, because thats the last version it works fine on

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by MarioMastr** [comment]
There is no proper uYouPlus release with 17.38.10. Try updating to 17.39.4_2.1.

**Comment by k3v1nwrld** [comment]
Updated and its still not working

**Comment by arichorn** [comment]
> There is no proper uYouPlus release with 17.38.10. Try updating to 17.39.4_2.1.

I think he was referring to my release of uYouPlus v17.38.10
I cannot resolve this issue since I have not fully experienced the code for app development or app tweaking.

**Comment by RHStonks** [comment]
> > There is no proper uYouPlus release with 17.38.10. Try updating to 17.39.4_2.1.
> 
> 
> 
> I think he was referring to my release of uYouPlus v17.38.10
> 
> I cannot resolve this issue since I have not fully experienced the code for app development or app tweaking.
> 
> I do hate this bug but hopefully it gets patched by the dev.

YouRememberCaption works fine on my A9 iPad but for some reason I also have an A13 iPhone 11 Pro like the OP and YouRememberCaption doesn't work. 

@arichorn I wonder why it works fine on my iPad but not iPhone. Both same iOS/iPad OS version and on the recent version of the app.

**Comment by qnblackcat** [comment]
Any update?

**Comment by PoomSmart** [comment]
@k3v1nwrld I believe you have to actually tap the gear icon at the top right when you are playing a video, then tap "Captions" and then the caption language you want it to be persistent across all videos.
