### ISSUE TITLE
Install problem: Failed to load Info.plist  [Questions]

### ISSUE THREAD

**Issue by will09122000** [qnblackcat/uYouPlus#524]
Trying to install the latest version with sideloadly and I get the following error:

`Installation failed: 0 PackageInspectionFailed (Failed to load Info.plist from bundle at path /private/var/containers/Bundle/Application/D0D89618-E807-4397-99A7-ABA8D26E9C30/YouTube.app/PlugIns/MessagesExtension.appex; Extra info about "/private/var/containers/Bundle/Application/D0D89618-E807-4397-99A7-ABA8D26E9C30/YouTube.app/PlugIns/MessagesExtension.appex/Info.plist": Couldn't stat /private/var/containers/Bundle/Application/D0D89618-E807-4397-99A7-ABA8D26E9C30/YouTube.app/PlugIns/MessagesExtension.appex/Info.plist: No such file or directory)`

- uYouPlus version: v17.39.4-2.1
- iPhone 11 Pro on iOS 16.0.2
- Sideloadly v0.27 on macOS Monterey
- Apple developer account

![SCR-20221005-k9y](https://user-images.githubusercontent.com/41238606/194073803-74d613ae-e493-40b6-a358-d382df108b9a.png)

![SCR-20221005-kbt](https://user-images.githubusercontent.com/41238606/194074265-dcc484ba-e2b2-4016-95ce-113de84d87ae.png)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by will09122000** [comment]
I get the same error when selecting 'Remove App Extensions (Plugins) in Sideloadly.

**Comment by jeffzyliu** [comment]
@qnblackcat same issue for me. Completely deleted and reinstalled with no app extensions and it still happens.

**Comment by qnblackcat** [comment]
@jeffzyliu i can not fix it. Sorry

**Comment by jeffzyliu** [comment]
Thanks for letting me know, unfortunate.

Maybe this is an issue if we install with extensions just once; perhaps reinstallation doesn't fix it. I hope AltStore/other platforms find a fix to permanently delete extension files if that's needed

**Comment by will09122000** [comment]
> @jeffzyliu i can not fix it. Sorry

Could you explain what might be causing it?
