### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#527]
Please publish a new release as there are multiple new translations (from this repo and from sub repos like YouPiP) and bug fixes (for example DontEatMyContent 1.0.1).

In the current uYouPlus version some translations (like german) aren't shown correctly.

**Comment by qnblackcat** [comment]
> I'd build one myself, but the GitHub Action fails.
> 
> https://user-images.githubusercontent.com/40891294/194372892-67ea5241-455a-4216-960a-ae9c5d18e5af.png

you must use a direct url to the YouTube IPA
