### ISSUE TITLE
Pls update Cercube+ 

### ISSUE THREAD

**Issue by WTFObstSalat** [qnblackcat/uYouPlus#528]
Can you update Cercube+ as son as you update uYou+ with the latest YouTube version pls? 

I and everyone else would be really thankful if you do that.

I know that this isn’t the right thread for this issue but there is no option to open an issue on the Cercube+ repo.

**Comment by qnblackcat** [comment]
ok

**Comment by WTFObstSalat** [comment]
Thank you very much for putting so much time in this repo and providing us these ipas ❤️
