### ISSUE TITLE
[Bug] uYouPlus will not rotate to landscape mode

### ISSUE THREAD

**Issue by GutHib1209** [qnblackcat/uYouPlus#53]
**Device info:**
- iOS/iPadOS version: 13.6.1
- Device model: IPhone 7
- Sideload tool: Sideloady
- Version of uYouPlus: v16.46.5-2.1

**Describe the bug:**
- The app will not rotate to landscape mode unless it's to watch a video in full screen. The screen will also not rotate while the video is minimized.

**How to reproduce the bug:**
Simply try and rotate your device while browsing Youtube.

**Comment by qnblackcat** [comment]
I‘m sorry but it doesn't sound like an issue of uYou+ at all 🤷‍♂️ iOS controls the rotation of apps, not the app itself
