### ISSUE TITLE
Cercube+ crashes 

### ISSUE THREAD

**Issue by WTFObstSalat** [qnblackcat/uYouPlus#530]
First thank you very much for updating to latest YouTube version. 

Unfortunately the app crashes after I tap on the Settings tap. 

I’m using the latest version of Cercube+ on an 
iPhone 13 Pro, latest iOS 16, signed with an dev acc

**Comment by qnblackcat** [comment]
I‘ll fix it when i get home

**Comment by WTFObstSalat** [comment]
Thx for the fix
