### ISSUE TITLE
[Bug] The application has a virus (Trojan)

### ISSUE THREAD

**Issue by thaibm92** [qnblackcat/uYouPlus#534]
The downloaded application has a virus, please help me fix it, previous versions don't have the virus

![image](https://user-images.githubusercontent.com/68208369/194688495-253c205c-e320-4ad0-b34c-5609ada03d2e.png)

**Comment by qnblackcat** [comment]
Window defender hates a lot of things, even when they‘re safe. Sorry but I cannot fix this.

> previous versions don't have the virus

Don’t you know that Window defender is updated regularly by Microsoft without user’s permission? Anyway, I recommend you either build your own IPA yourself, or simply don’t use uYouPlus at all if you think it’s not safe
