### ISSUE TITLE
[Bug] Age restricted videos don't load

### ISSUE THREAD

**Issue by NukeThief** [qnblackcat/uYouPlus#537]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0.2
- Device model: iPhone 13
- Sideload tool: AltStore
- The specific version of uYouPlus: 17.39.5-2.1

### Describe the bug
I have the uYou's age restriction bypass off but restricted videos still don't load. **I use the VP9 codec**

### How to reproduce the bug
https://user-images.githubusercontent.com/81801547/194745669-5e9c6d69-5f5b-4cf6-b2c0-4bc97ebea271.MOV
### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Does the issue happen with the official YouTube from AppStore?
No because the age restriction prompt appears on AppStore YT
### Additional context:

**Comment by qnblackcat** [comment]
The video you‘re playing is not even an age-restricted video...

**Comment by NukeThief** [comment]
![image](https://user-images.githubusercontent.com/81801547/194752303-a572fb89-6d48-46c6-b409-33ba15fccd18.png)
Are you sure about that?

**Comment by qnblackcat** [comment]
I assume you’re watching this video: https://youtu.be/G5BhVQ9HJYU

Then yes, I’m pretty sure it’s not an age-restricted video.

https://user-images.githubusercontent.com/52943116/194752505-43f76c64-dbe9-4f4f-badd-6eb540bf5e01.MP4

**Comment by NukeThief** [comment]
Sometimes yt dosen't force you to verify your age for me the vid gives the prompt
