### ISSUE TITLE
[Bug] Crashes on iOS 12  on launch

### ISSUE THREAD

**Issue by JanX2** [qnblackcat/uYouPlus#540]
### Device info
- iOS/iPadOS version: 12
- Device model: iPad Air
- Sideload tool AltStore
- The specific version of uYouPlus: 
uYouPlus_17.36.4_2.1.ipa
uYouPlus_17.36.4_2.1_F2.ipa
uYouPlus_17.37.3_2.1.ipa

### Describe the bug
Crashes on iOS 12  on launch.

### How to reproduce the bug
Launch on iOS 12. 

### Crash log (if possible)
Seems to crash too early for a log entry.

### Are you using the newest version of uYouPlus? If not, why?
I tried:
uYouPlus_17.36.4_2.1.ipa
uYouPlus_17.36.4_2.1_F2.ipa
uYouPlus_17.37.3_2.1.ipa

### Does the issue happen with the official YouTube from AppStore?
No. The official 17.38.10 is running fine.

### Additional context: 
-

**Comment by qnblackcat** [comment]
uYouPlus requires iOS 13.0+

**Comment by MarioMastr** [comment]
> Ok. The release notes for [v17.36.4-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.36.4-2.1) list this:
> 
> YouTube v17.36.4: re-adds support for iOS 12 & 13.
> 
> 

It's actually pretty strange. Google removed iOS 12 and 13 support in an update,probably to remove some space, but @PoomSmart said on Twitter that it only removed like 3MB. Google must have also thought that that was pointless, because they readded iOS 12 and 13 support in the VERY NEXT UPDATE.

**Comment by PoomSmart** [comment]
> > Ok. The release notes for [v17.36.4-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.36.4-2.1) list this:
> > 
> > YouTube v17.36.4: re-adds support for iOS 12 & 13.
> > 
> > 
> 
> It's actually pretty strange. Google removed iOS 12 and 13 support in an update,probably to remove some space, but @PoomSmart said on Twitter that it only removed like 3MB. Google must have also thought that that was pointless, because they readded iOS 12 and 13 support in the VERY NEXT UPDATE. 

And got rid of it again in 17.40.sth

**Comment by Absolucy** [comment]
Perhaps it'd be a good idea, for the tweaks that still support iOS 12, to make separate releases using YouTube v17.36.4 with the updated tweaks, for iOS 12/13 users?

**Comment by Mspy1** [comment]
Any working tweaks for 12?
