### ISSUE TITLE
[Bug] Crash on video play

### ISSUE THREAD

**Issue by ThatGuyDannyS** [qnblackcat/uYouPlus#541]
### Device info
- iOS/iPadOS version: iOS 13.5
- Device model: iPhone XR (Jailbroken)
- com.ichitaso.uyouplus (repo) as well as AltStore Sideload (direct from GitHub)
- The specific version of uYouPlus: 1.0.7

### Describe the bug

YouTube crashes on play. Cr4shed is logging ‘YouTubeDislikesReturn.dylib’ as the culprit. Info below:

Reason-
[<YTPlaybackStrippedWatchController 0x141dd7c10> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _playerViewController.

Have saw others post about this issue but couldn’t see any actual crash log info. Hope this helps.

**Comment by arichorn** [comment]
This is not a uYouPlus problem
Contact @ichitaso about it

**Comment by arichorn** [comment]
also what I think happened is that the YouTubeReturnDislikes Tweak might’ve stopped working on that version of yt due to Cilent-Side Changes for older versions

**Comment by qnblackcat** [comment]
I‘ve never released “v1.0.7”. Please get the latest version from https://github.com/qnblackcat/uYouPlus/releases

**Comment by arichorn** [comment]
No worries qnblackcat, he’s talking about the Jailbreak version of uYou+

**Comment by ThatGuyDannyS** [comment]
@arichorn - Thanks, had not realised ichitaso‘s release was different.

@qnblackcat - Apologise, 1.0.7 was in reference to the jailbreak version. However, I had also attempted to sideload the current version of uYouPlus via altstore which seemed to crash on app launch. Unfortunately, there were no culprit being logged - possibly an issue with my device. Will investigate.

**Comment by qnblackcat** [comment]
@ThatGuyDannyS I guess iSponsorBlock is the culprit. Try to remove the `iSponsorBlock.dylib` inside the ipa
