### ISSUE TITLE
[Bug] The logo has a white background!

### ISSUE THREAD

**Issue by rodukov** [qnblackcat/uYouPlus#543]
### Device info
- iOS/iPadOS version: 15.6.1
- Device model: iphone 5 se
- Sideload tool: Altstore
- The specific version of uYouPlus: latest

### Describe the bug
ℹ️ The fact is that when you enter the application, the company logo has an unpleasant white background. I assume you are using `.jpg` format, not `.png`. Just replace it and that's it!

### How to reproduce the bug
📘 Enable dark theme and restart the app
![photo_2022-10-10_22-36-06](https://user-images.githubusercontent.com/101352977/194940209-b44cb549-1108-439b-9535-97e978dad88e.jpg)

### Are you using the newest version of uYouPlus? If not, why?
✅ Latest version used

### Does the issue happen with the official YouTube from AppStore?
✅ In the official application the defect does not happen

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/issues/194#issuecomment-1151914340

`jpg, png`? I never modify the YouTube ipa

**Comment by rodukov** [comment]
> [#194 (comment)](https://github.com/qnblackcat/uYouPlus/issues/194#issuecomment-1151914340)
> 
> `jpg, png`? I never modify the YouTube ipa

Then what are your guesses as to why this is happening?

**Comment by MarioMastr** [comment]
has this issue been resolved for you yet? you can always build an ipa yourself if you dont trust the github ipas for whatever reason
