### ISSUE TITLE
[Questions] Is there any way to Export/Import your SponsorBlock User ID?

### ISSUE THREAD

**Issue by 2vsh** [qnblackcat/uYouPlus#544]
Heya, I was wondering if it was possible to export my sponsorblock ID from my desktop to the uYouPlus App. I'm using the AltStore as the (loader?) I don't really know the correct terminology, sorry. 

![brave_mBnSkh3xVF](https://user-images.githubusercontent.com/67459159/194951417-e7dd0e04-0c7c-4c44-8448-252fcef105f3.png)

**Comment by angelof-exe** [comment]
Ehi, sorry for late question, but how did you manage this?
