### ISSUE TITLE
[Questions] Apple CarPlay support?

### ISSUE THREAD

**Issue by Kief5555** [qnblackcat/uYouPlus#545]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

Yes.
###

Hey! I chill out in my car sometimes and want to watch YouTube via CarPlay.. but I can't. Are you guys able to make it app so it? Thanks. (For obvious reasons I won't watch it while
I'm driving)

Psst.. the video downloader is 403

**Comment by Kief5555** [comment]
@qnblackcat

**Comment by qnblackcat** [comment]
Not possible

**Comment by Kief5555** [comment]
Oh

**Comment by Kief5555** [comment]
What about 403 issue @qnblackcat
