### ISSUE TITLE
[Bug] Oled Dark Mode doesn’t work with the New YouTube UI

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#547]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.7
- Device model: M1 iPad Pro
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) Altstore
- The specific version of uYouPlus: 17.40.5 (This version of YouTube was built by me!)

### Describe the bug
YouTube might’ve changed the headers of Oled Dark Mode in v17.40.5 or newer, don’t release this version unless it’s resolved!

### How to reproduce the bug
![DB3C4B4E-77EA-447C-AA4B-7E58CA8976B2](https://user-images.githubusercontent.com/78001398/194958201-9c31237b-7030-4ebd-8872-81f558150913.png)
![D5BBF89E-44A5-496B-B4B7-7A8EB2BECBC6](https://user-images.githubusercontent.com/78001398/194958226-3fbfd155-1205-4fb3-88eb-94bc87b6e650.png)

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_ well yeah it is definitely but I built it with the newest ipa v17.40.5 to always stay up-to-date

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_ YouTube changed the Headers so it’s either both neutral

### Additional context: 
Sorry for building too fast, but I do always try to help and warn you about present YouTube versions

**Comment by arichorn** [comment]
Also do not go into the autoplay section in settings! YouTube broke it

**Comment by qnblackcat** [comment]
Works fine for me
![IMG_4261](https://user-images.githubusercontent.com/52943116/195351862-bbe43573-bb4f-414a-a832-e7357f342268.PNG)

**Comment by arichorn** [comment]
Yeah. It appears YouTube reverted it. I probably think it’s a client side change but all I know of that YouTube added a new background method in the YTCommonColorPalette

**Comment by qnblackcat** [comment]
> YouTube added a new background method for the YTCommonColorPalette

I believe they did not do that

**Comment by arichorn** [comment]
Then guess I was stupid then, maybe settings were just doing it on its own? I will retitle this issue

**Comment by arichorn** [comment]
I figured out it’s one of those A/B tests, It definitely has to do with those new Rounded YT Thumbnails

**Comment by qnblackcat** [comment]
Just tested on an iPad and OLED theme works fine as well.

**Comment by arichorn** [comment]
Like I said YouTube reverted it. I’m gonna say YouTube probably did a A/B config test, and this only happens when all the thumbnails in the home tab with rounded sides on each one. This is definitely happening.

**Comment by arichorn** [comment]
> Just tested on an iPad and OLED theme works fine as well.

Reading this, and yeah of course YouTube would do this, but in the future when YouTube officially adds the change, then you’ll get this issue like me on iPhone+iPad doesn’t matter which device.

**Comment by arichorn** [comment]
@qnblackcat here ya go, thanks to PoomSmart’s YTABConfig.

```
// Disable Rounded Thumbnails for v17.40.5-Present
%hook YTGlobalConfig
 - (BOOL)uiSystemsClientGlobalConfigEnableRoundedThumbnailsForNative { return NO; }
 %end
```
in v17.40.5 this toggle was on by default which resulted with Oled Dark Mode to not work, but it may be fixed in newer versions but do not know yet.

**Comment by qnblackcat** [comment]
> @qnblackcat here ya go, I found the exact thing that caused it and great thanks to PoomSmart’s YTABConfig so I would find the thing that caused the problem.
> 
> ```
> // Disable Darker Palette for v17.40.5-Present to prevent OLED Problems
> %hook YTColdConfig
>  - (BOOL)uiSystemsClientGlobalConfigUseDarkerPaletteBgColorForNative { return NO; }
>  %end
> ```
> 
> this doesn’t have to do with the Oled Dark Mode issue but just in case if you might need it

Cool

**Comment by arichorn** [comment]
I forgot to edit the message ignore what I said below, disableing this flag fixes the OLED ISSUE in settings
