### ISSUE TITLE
[Bug] No New App After Installation

### ISSUE THREAD

**Issue by El3ctroe** [qnblackcat/uYouPlus#549]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.7
- Device model: iPhone 8 Plus
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) AltStore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ v17.39.5-2.1

### Describe the bug
After downloading in AltStore no new app appears, search for Youtube and uYouPlus in the apps section nothing showed up, default youtube app has nothing changed.

### How to reproduce the bug
Download the version I downloaded through AltStore?

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_ Yes, newest version

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_ Well the default Youtube app shows up so no

### Additional context: 
I had an older version from like 9 months ago that I deleted after like a month of use. (so haven't had uYou+ in 8 months) Might have to do with that. 3 app Ids were taken up, I have 5/8 remaining. There is no Youtube app under the active section like there was on my older version.

**Comment by qnblackcat** [comment]
Try:
- Delete & reinstall both uYou+ and AltStore
- Download an app from AppStore so the uicache can be refreshed
- Reboot your device
- Switch to Sideloadly
After all, this is definitely not an issue of uYou+
