### ISSUE TITLE
[BUG] Error Couldn’t find any video in playlist

### ISSUE THREAD

**Issue by DrCoone** [qnblackcat/uYouPlus#555]
![0BFA8FA0-B1F1-4608-856A-3924569E144B](https://user-images.githubusercontent.com/11542140/195486293-6ab6c02b-2c5a-4e52-ab5b-0c85100f2ab9.jpeg)

Unable to download playlist in app

iPhone 12 Pro Max iOS15.1.1
App 2.1

**Comment by qnblackcat** [comment]
This is a known issue of uYou itself… 
https://github.com/MiRO92/uYou-for-YouTube/issues/62
