### ISSUE TITLE
[Bug] Legacy PiP breaks manual PiP

### ISSUE THREAD

**Issue by asportnoy** [qnblackcat/uYouPlus#56]
**Device info:**
- iOS/iPadOS version: 15.4 Developer Beta
- Device model: iPhone Xr
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore
- Version of uYouPlus: v17.04.3-2.1

**Describe the bug:**
Enabling legacy PiP causes PiP to always open despite the settings to only start on button press.

**How to reproduce the bug:**
![image](https://user-images.githubusercontent.com/14863373/152909310-6b17f4f5-d71a-4ebe-9b27-10ffd4fd901f.jpeg)
Use the settings above, then start playing a video and close the app.

**Crash log (if possible):**
N/A 

**Additional context:**
None

**Comment by qnblackcat** [comment]
@Poomsmart
I can confirm it also happens with YouPiP from Cydia

**Comment by qnblackcat** [comment]
https://github.com/PoomSmart/YouPiP/issues/42

**Comment by qnblackcat** [comment]
This bug is fixed in v17.09.1-2.1. You can re-open this issue if the bug still happens
https://github.com/qnblackcat/uYouPlus/releases/download/v17.09.1-2.1/
