### ISSUE TITLE
New YouTube UI has annoying contrast

### ISSUE THREAD

**Issue by MarioMastr** [qnblackcat/uYouPlus#560]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16.1 Dev Beta 5
- Device model: 11
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus: v17.39.5_2.1 _**latest** or **newest** is NOT a version number!!_

### Describe the bug
So the new YouTube UI has accents below and above the video that match the colour scheme of the next scene and it's bugging me out quite a lot. Is there any tweak that could be used to turn this off?

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
![image](https://user-images.githubusercontent.com/84964352/195693409-d5db9ea0-be98-4b1e-9da0-daac0535d3c8.png)
### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_
Yes
### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
Yes 
### Additional context:

**Comment by arichorn** [comment]
Yeah, turn on Fake YouTube Version in YouPiP section in settings

**Comment by MarioMastr** [comment]
> Yeah, turn on Fake YouTube Version in YouPiP section in settings and restart the app.

I think that option is actually broken. It doesn't work anymore.

**Comment by level3tjg** [comment]
I think this is activated by `-[YTColdConfig enableCinematicContainer]`, I'm not sure if disabling it will do anything though. It seems almost all of the new watch UI is server-sided

**Comment by arichorn** [comment]
Alright I’ll Implement this in my version of uYouPlus.

**Comment by arichorn** [comment]
@MarioMastr try this version of uYouPlus https://github.com/arichorn/uYouPlusExtra/releases/tag/v17.40.5-2.1-(258) this will have the workaround I implemented from level3tjg
Also just to warn you, the settings on my version of uYouPlus are completely different and reorganized so expect it to have their own sections & reordered options.

**Comment by MarioMastr** [comment]
@arichorn thank you so much <3

**Comment by MarioMastr** [comment]
It appears to have been broken again. I didn't update anything. It just broke.

**Comment by arichorn** [comment]
Then I don’t know what to do ;(

**Comment by qnblackcat** [comment]
Closed because this is obv a feature of YouTube, not an issue of uYou/uYouPlus
