### ISSUE TITLE
[Questions] buildapp.yml has deprecated code now ⚠️ 

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#561]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

### Deprecated Warnings ⚠️
on October 11th 2022 I’ve recently started to get a deprecated warning about **MacOS 11** and it’s removal date on December 1st 2022, and then a day later, I see **Node.js 12** getting deprecated and now getting removed on November 1st 2022. and I think **set-output** & **save-state** is getting the same treatment too but in a removal date is unknown.

### is this a big deal? 😔
Well not all. It still works for right now but it will soon to stop working for the users that uses buildapp.yml like me. But overrall I do have we can possibly still build an ipa and update it before the removal takes place. but if iSnackable knows about this problem then hope it gets resolved.

**Comment by qnblackcat** [comment]
The action runs on the `macos-latest`, so it’s just a warning before the runner migrates from macOS 11 to 12

**Comment by arichorn** [comment]
> The action runs on the `macos-latest`, so it’s just a warning before the runner migrates from macOS 11 to 12

I know but there’s other warnings I said above that you might need to be aware of
![FCCFD542-2EDB-4F3A-AC06-1A6DD4FB75CB](https://user-images.githubusercontent.com/78001398/195742503-1a7e6b8e-cca8-4c84-a661-b32720884c77.jpeg)

**Comment by arichorn** [comment]
Unfortunately there is nothing I could do about it but at least I tried before the code migration
