### ISSUE TITLE
Will Google Ban My Account

### ISSUE THREAD

**Issue by yodaluca23** [qnblackcat/uYouPlus#562]
Will this app get my Google account banned...? I know this is probably a stupid thing to ask but I CANNOT lose my Google account... Does this app disable sentry and logging to prevent YouTube from being able to know if I'm using this app? Can someone please tell me if anyone has ever been ban because they used this?

**Comment by arichorn** [comment]
Google does not ban your account if you use a third-party app unless it’s malicious. This app shouldn’t harm your google account.

**Comment by yodaluca23** [comment]
> Google does not ban your account if you use a third-party app unless it’s malicious. This app shouldn’t harm your google account.

But it like purposefully removes ads and gives you other paid features for free....

**Comment by arichorn** [comment]
Yeah, but those don’t effect your google account, I’ve been using uYou+ for nearly 6 months, nothing ever happened, so I can confirm to you none of that wouldn’t happen.

**Comment by qnblackcat** [comment]
Very unlikely but I still suggest you do not use uYouPlus since privacy is your priority.

**Comment by yodaluca23** [comment]
> Very unlikely but I still suggest you do not use uYouPlus since privacy is your priority. 

What is that supposed to mean?!!?!?!?

**Comment by qnblackcat** [comment]
@yodaluca23 the app is not fully open-source so I can’t say it’s 100% safe (more like 99,9%). Again, use it at your own risk 🤷‍♂️

**Comment by yodaluca23** [comment]
> @yodaluca23 the app is not fully open-source so I can’t say it’s 100% safe (more like 99,9%). Again, use it at your own risk 🤷‍♂️ 

But the guy that originally made the app, the closed source part, is well known in the community right so it's highly doubtful that he would put malicious code into it right? That's what my understanding was from a few Reddit posts that I had found.

**Comment by qnblackcat** [comment]
@yodaluca23 No one force you to use the app, if you think it’s not safe then simply don't use it 🤷‍♂️

**Comment by yodaluca23** [comment]
> @yodaluca23 No one force you to use the app, if you think it’s not safe then simply don't use it 🤷‍♂️

OK, thanks. But one last thing so you can verify for me that all the tweaks added are open source and safe/private, correct? It's only the original app source, which is on MiRO's Github, that's closed source and obfuscated that might not be safe... So if I can verify that MiRO's repository is safe then this is... correct?

**Comment by qnblackcat** [comment]
See version's info

https://github.com/qnblackcat/uYouPlus#download
