### ISSUE TITLE
[Questions] not working,,saying:‘Youtube is no longer available’ 

### ISSUE THREAD

**Issue by Samwilsonn** [qnblackcat/uYouPlus#564]
i just installed the latest version of uyouplus on my iphone11promax on SV 16.0.3 and when i click the youtube icon…it says “youtube is no longer available “
please help me…tell me what should i do!!
Thank you

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by proway46** [comment]
> 

Reinstall now
