### ISSUE TITLE
[Bug] black screen

### ISSUE THREAD

**Issue by Mmdxh** [qnblackcat/uYouPlus#567]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.4
- Device model: iPhone 12 pro
- Sideload tool Trollstore (happens in other sideloading tools too)
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 

v17.39.5-2.1

### Describe the bug

sometimes when I open a video I can watch like a second or two then it goes black, nothing fixes it other than closing the video and opening it until it works 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
it happens randomly

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_
Yes

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_ never happened to me before, only on uYou+

### Additional context:

**Comment by qnblackcat** [comment]
Like this? https://www.reddit.com/r/youtube/comments/xx9ioc/another_bug_lol/

**Comment by Mmdxh** [comment]
> Like this? https://www.reddit.com/r/youtube/comments/xx9ioc/another_bug_lol/

Yea, it looks like its from the YT reddit so its not a uYou+ issue, its weird though cause it has never happened to me until I started using uYou+

**Comment by mikeo** [comment]
Try disabling playback in feed in settings, general

Didnt wanna post on old issues but this does come up when you google the bug
