### ISSUE TITLE
Feature request YTABConfig by PoomSmart

### ISSUE THREAD

**Issue by Macleykun** [qnblackcat/uYouPlus#572]
Might be fun to add this one: YTABConfig 
See tweet: https://mobile.twitter.com/PoomSmart/status/1581590827604008967
See changelog: https://poomsmart.github.io/repo/depictions/ytabconfig.html
Source: https://github.com/PoomSmart/YTABConfig

**Comment by arichorn** [comment]
I tried implementing this in my forked repo but it is quite hard to implement YTABConfig

**Comment by arichorn** [comment]
It seems that YTABConfig has been implemented into uYouPlus by qnblackcat but as far as I know that the A/B Section isn’t visible as of right now.

**Comment by Macleykun** [comment]
Ooooh that’s great! I do hope it’ll work in cercube aswell! That’s my personal favorite :)

**Comment by qnblackcat** [comment]
Please wait till the next update

**Comment by Macleykun** [comment]
> Please wait till the next update

Sorry I didn’t meant to be impatient!

**Comment by arichorn** [comment]
> Ooooh that’s great! I do hope it’ll work in cercube aswell! That’s my personal favorite :)

It‘ll work, my version of CercubePlus has been inactive for a bit but I’ll see if I can somehow make it work on there?

**Comment by Macleykun** [comment]
> > Ooooh that’s great! I do hope it’ll work in cercube aswell! That’s my personal favorite :)
> 
> It‘ll work, my version of CercubePlus has been inactive for a bit but I’ll see if I can somehow make it work on there?

I’m ok waiting for th next update :) no worries! Thank you!
