### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Clayton630** [qnblackcat/uYouPlus#579]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.1
- Device model: iPhone 14 Pro Max
- Sideload tool: BullfrogAssistant
- The specific version of uYouPlus: 17.39.5

### Describe the bug

Unable to update the app (error failed to load info.plist), I need to uninstall it to update to a newer version

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_![image](https://user-images.githubusercontent.com/93291298/196136598-93c01ebb-e6df-48eb-bf7b-4ed0d3d41c40.png)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
