### ISSUE TITLE
[Bug] Crash on accessing Settings

### ISSUE THREAD

**Issue by burgio777** [qnblackcat/uYouPlus#581]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.1 Beta 5
- Device model: iPhone 14 Pro
- Sideload tool AltStore
- The specific version of uYouPlus: 17.40.5_2.1

### Describe the bug
YouTube crashes when i try to open its settings

### How to reproduce the bug
https://user-images.githubusercontent.com/87341927/196266049-1b9c7168-533b-4b6d-92db-9c0dcab47b83.MOV

**Comment by qnblackcat** [comment]
Are you sure you‘re on v17.40.5-2.1? Kinda weird cuz this issue has been fixed already. Also please provide the crash log.

**Comment by burgio777** [comment]
yes i'm sure. i wanted to share the log but i doesn't appear and the latest log i have its one from 3 days ago

**Comment by burgio777** [comment]
> I’ll suggest you delete the current uYou+ and reinstall the newest version. 

unless you released exactly now a new version that was the latest version

**Comment by moh-ter** [comment]
I tested it on unjailbroken iPhone on iOS 15.1.1 - sideloaded using SignTools

Can’t reproduce it

Also No issues in TrollStore & on iPad- sideloaded.

try to delete the app & resign it
usually weird bugs like this resolve after deleting the app.

**Comment by qnblackcat** [comment]
did you use get the IPA from my AltStore repo? I haven't update my repo for a while

**Comment by burgio777** [comment]
didn't know you had one, i downloaded it from github

**Comment by qnblackcat** [comment]
Try [v17.41.2-2.1](https://github.com/qnblackcat/uYouPlus/releases/latest)

**Comment by burgio777** [comment]
thank you! i'll install that now

**Comment by qnblackcat** [comment]
Please try older versions of uYou+

**Comment by burgio777** [comment]
> Please try older versions of uYou+

yeah i'm using 17.39 something and it's perfectly working

**Comment by qnblackcat** [comment]
Still crash in v17.42.7-2.1?

**Comment by burgio777** [comment]
didn't try yet, i'll update and try later today

**Comment by burgio777** [comment]
> didn't try yet, i'll update and try later today 

yeah it still crashes

**Comment by qnblackcat** [comment]
any update?

**Comment by qnblackcat** [comment]
Closed due to inactive
