### ISSUE TITLE
Feature Request: option to set default playback speed

### ISSUE THREAD

**Issue by anonymousaga** [qnblackcat/uYouPlus#582]
I may have missed this, but I can’t find a way to always make it play at 1.25x. Is it possible to add this? Thanks in advance. It resets every time I swipe the app out of the app switcher & reopen it.

**Comment by kuitog** [comment]
+1

**Comment by timwredwards** [comment]
+1 this would be awesome

**Comment by qnblackcat** [comment]
Added in [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)
