### ISSUE TITLE
[Bug] Now Playing API Showing Blank on YT Shorts

### ISSUE THREAD

**Issue by yodaluca23** [qnblackcat/uYouPlus#586]
### Device info
- iOS/iPadOS version: 16.0.3
- Device model: 14 Pro
- Sideload tool: AltStore
- The specific version of uYouPlus: v17.40.5-2.1

### Describe the bug

Now Playing glitches and just shows up blank.. Also shorts try to use Now Playing which doesn't happen in Vanilla YT (I don't think)

### How to reproduce the bug
Play a video in latest release, go to Lock Screen or anywhere else that uses the Now Playing API.

https://ibb.co/HqnS3hV
https://ibb.co/gWGPFMY

### Crash log (if possible)
N/A

### Are you using the newest version of uYouPlus? If not, why?
Yes, I am.

### Does the issue happen with the official YouTube from AppStore?
No

### Additional context: 
N/A

**Comment by level3tjg** [comment]
This is expected behavior in the official app when background playback is disabled, however uYou and YouPiP should be force enabling it. Could you update to the latest uYouPlus version and use YTABConfig to check if `disableIosUpdateNowPlayingInfoCenterForSomePlaybacks` or `disablePlaybackLockScreenController` are checked?

**Comment by yodaluca23** [comment]
> This is expected behavior in the official app when background playback is disabled, however uYou and YouPiP should be force enabling it. Could you update to the latest uYouPlus version and use YTABConfig to check if `disableIosUpdateNowPlayingInfoCenterForSomePlaybacks` or `disablePlaybackLockScreenController` are enabled?

I turned on "disableIosUpdateNowPlayingInfoCenterForSomePlaybacks" (couldn't find the other one...) and its still happening with shorts being blank...

**Comment by level3tjg** [comment]
> I turned on "disableIosUpdateNowPlayingInfoCenterForSomePlaybacks"

They should be disabled, not enabled.

> its still happening with shorts being blank

Again, expected behavior. Nothing will change that, just trying to figure out why it would be blank for normal videos.

**Comment by yodaluca23** [comment]
Is their anyway to make it not show in shorts...? since it doesn't happen in vanilla, it's very annoying and useless... Could uYou+ add some fix? in settings...? or something or another Add-On (Preferably not sense... limited app IDs... but...)

**Comment by qnblackcat** [comment]
I test this on several devices, all of them show blank image on Now Playing with Shorts videos. This is probably an issue of YouTube.
