### ISSUE TITLE
[Enhancement] Different icon options

### ISSUE THREAD

**Issue by reedrw** [qnblackcat/uYouPlus#59]
I love this app, but I think the YouTube icon is very ugly. iOS apps have the ability to change their own icon, so it would be nice if there was an option to change the home screen icon to something like the YouTube icon that was used from 2013 to 2015, attached below. Thank you!

<img src="https://static.wikia.nocookie.net/logopedia/images/5/51/Youtube_2013_icon.png"  width=30% height=30%>

**Comment by ivehrndz** [comment]
you can change icons using shortcuts. thats what i do when i dont like icons for apps.

**Comment by reedrw** [comment]
> you can change icons using shortcuts. thats what i do when i dont like icons for apps.

You can, but then the shortcuts app will open before the app opens, or if you use a profile to change your icons, a white screen will open before the app opens. It would be much nicer if the app just had an alternate icon

**Comment by qnblackcat** [comment]
You can custom app's icon using AltStore. Even if you don't use AltStore, there are many tools out there can do that. [This](https://github.com/ethandgoodhart/IPAEdit) is an example
