### ISSUE TITLE
[Bug] Dislike counter goes away after pressing "Not interested"

### ISSUE THREAD

**Issue by jaff80** [qnblackcat/uYouPlus#596]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16.0.3
- Device model: iPhone 13 Pro Max
- Sideload tool: AltStore
- The specific version of uYouPlus: v17.41.2-2.1
### Describe the bug
In some videos when you scroll down, you might see a section called "Products in current video". In the Products in current video section, you see three dots, when clicked, you are greeted with two options. The first one is called "About products" and the second one is called "Not interested" When you tap on Not interested and scroll back up, the dislike counter goes away and now simply says "Dislike" Tapping the dislike button will not bring the counter back nor opening the description. The counter only comes back after closing the video and watching it again.
### How to reproduce the bug
Watch a video
Scroll down until you see a section called "Products in current video"
Tap on the three dots
Tap "Not interested"
Scroll back up, and the dislike counter should say "Dislike"

https://user-images.githubusercontent.com/113552154/197085123-f744ce0e-582e-4544-a6ef-351fee6b94cb.mp4

### Crash log (if possible)
The app does not crash.

### Are you using the newest version of uYouPlus? If not, why?
Yes, I am using the newest version of uYouPlus.

### Does the issue happen with the official YouTube from AppStore?
No, the official YouTube app does not have a counter and only says "Dislike"

**Comment by qnblackcat** [comment]
To answer both of your issues: they‘re server-side rendering things. Nothing we can do about it
