### ISSUE TITLE
How to check uYouPlus version number within the app?

### ISSUE THREAD

**Issue by WoodpeckerBaby** [qnblackcat/uYouPlus#60]

**Comment by qnblackcat** [comment]
The version number is the IPA‘s name

**Comment by WoodpeckerBaby** [comment]
I installed using the direct link, I didn't have access to the IPA name, and I never had the file stored. 

You should put it somewhere in the UI, maybe in settings. 

Also please get rid of the uYou upgrade check interface. It's very confusing.
