### ISSUE TITLE
Error while installing the App

### ISSUE THREAD

**Issue by helixxger** [qnblackcat/uYouPlus#600]
I get this error when installing via AltStore.

An error occured while installing the app.
Failed to load Info.plist from bundle at path / private/var/containers/Bunale/Application/
AE33D8FF-CCCC-436A-87F3-4D11FF199915/
App.app/Pluglns/MessagesExtension.appex;
Extra info about "/private/var/containers/Bundle/
Application/AE33D8FF-
CCCC-436A-87F3-4D11FF199915/App.app/
Plugins/MessagesExtension.appex/Info.plist":
Couldn't stat /private/var/containers/Bundle/
Application/AE33D8FF-
CCCC-436A-87F3-4D11FF199915/App.app/
Pluglns/MessagesExtension.appex/Info.plist: No
such file or directory

![image](https://user-images.githubusercontent.com/76208371/197306402-89f12892-d8f1-42fb-af90-76da143e83a0.png)

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
