### ISSUE TITLE
[Bug][Questions]Hanging on install AltStore/Sideloady

### ISSUE THREAD

**Issue by gmanc2** [qnblackcat/uYouPlus#603]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.0.3
- Device model: 13 Pro MAx
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) Sideload/Altstore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ uYouPlus_17.41.2_2.1

### Describe the bug
I have a developer account, and this is a recent issue. I'm not sure whats causing it, but I tried to reinstall altstore and it worked fine I can even refresh fine, but when I try to install UYou+ it hangs right at the very end. I'm not sure if this is an altserver/altstore issue or it's an issue with the UYou+ app, but I have no way of telling as no errors are produced it just hangs. Please let me know if there is something I can do to fix this? Sideload gives an error regarding the package and file structure being messed up. 

### How to reproduce the bug Attempt to install uYou+ on any loader.
_(Please attach videos or screenshots if possible)_

### Crash log (if possible) N/A
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why? No, because I cant update it I'm stuck on the older version.
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_ 

### Does the issue happen with the official YouTube from AppStore? No
_(Well, YouTube itself is buggy sometimes...)_

**Comment by arichorn** [comment]
Alright, this kind of stuff happens to me a lot I got methods on resolving it
1. Change Internet Connection because it usually does the trick
2. Restart either or Mobile Device or Computer
3. Reopen Altserver on Computer
4. Reinstall Altserver/Altstore on the Mobile Device or Computer

**Comment by Blockr22** [comment]
Same issue happening here on my XS- MAX aswell. Tried restarting both pc & iPhone , internet connection, reinstall altstore on iPhone but doesn’t fix the issue. I have to delete uyou+ & reinstall new update. Very annoying & happening recently

**Comment by gmanc2** [comment]
> Alright, this kind of stuff happens to me a lot I got methods on resolving it
> 
> 1. Change Internet Connection because it usually does the trick
> 2. Restart either or Mobile Device or Computer
> 3. Reopen Altserver on Computer
> 4. Reinstall Altserver/Altstore on the Mobile Device or Computer

> Same issue happening here on my XS- MAX aswell. Tried restarting both pc & iPhone , internet connection, reinstall altstore on iPhone but doesn’t fix the issue. I have to delete uyou+ & reinstall new update. Very annoying & happening recently

I attempted all of that to no avail. I'm not sure whats happening. I'm worried that if I delete it, I will not be able to get it again.

**Comment by gmanc2** [comment]
Update: I deleted it and was able to install it on Sideloady. It might be an issue with altstore/server. I tried both the beta and non beta versions of altserver/store.

**Comment by arichorn** [comment]
> Update: I deleted it and was able to install it on Sideloady. It might be an issue with altstore/server. I tried both the beta and non beta versions of altserver/store.

Alright I’ll let everyone know about this method, uYou+ getting corrupted when updating happens all the time

**Comment by Yunogamer** [comment]
been doing this for a long time now.. its uyou+ thats broken. as any other app sideloads a newer version of it just fine. but coarse the uyou+ devs blame altstore as usual as they did when a last mentioned this not that long ago..

**Comment by arichorn** [comment]
> always have to delete it before installing newer version, thats the only thing that works.. for now..

It’s actually fine for me, it hasn’t happened ever since july 2022
I’ve been switching between this uYouPlus & My uYouPlus but still hasn’t happened

**Comment by Yunogamer** [comment]
> > always have to delete it before installing newer version, thats the only thing that works.. for now..
> 
> It’s actually fine for me, it hasn’t happened ever since july 2022 I’ve been switching between this uYouPlus & My uYouPlus but still hasn’t happened

theres another uyou+? maybe that one doesnt have this bug?

**Comment by qnblackcat** [comment]
If you have a developer account, use iOS App Signer or SignTools. Stay away from AltStore

**Comment by arichorn** [comment]
> theres another uyou+? maybe that one doesnt have this bug?

Well yeah, there’s another version which was by me which only adds missing features that seem to be needed from normal uYou+

**Comment by fun4stuff** [comment]
Hanging for me too. Is there an ETA for when it will be fixed?

**Comment by Blockr22** [comment]
Most of the people use altstore, plz fix this issue dev. Really difficult to update uyou+

**Comment by fun4stuff** [comment]
Not working with sideloadly either. looks like uYouPlus is finally dead.

**Comment by qnblackcat** [comment]
@gmanc2 https://github.com/qnblackcat/uYouPlus/issues/360#issuecomment-1214204795

**Comment by gmanc2** [comment]
@qnblackcat Does the IOS app signer require a mac? If so, is there an easy way to use signtools? Im not really sure how to accomplish signing the app.
