### ISSUE TITLE
iSponsorBlock not working when enabled

### ISSUE THREAD

**Issue by DolphinLaser** [qnblackcat/uYouPlus#605]
I am using v17.41.2-2.1 and am on iOS 16.0.3

I both updated my iOS version uYou+ version around the same time so I am not sure which is the culprit but iSponsorBlock no longer skips segments even though it is enabled. The on screen controls for iSponsorBlock also no longer appear.

This is also a fresh install of the app so all settings are default.

Relevant screenshots:

![C56E1206-35A4-4EF7-952D-36A77B4A89E4](https://user-images.githubusercontent.com/63314427/197419577-23866355-b78c-496a-b53d-68628400a02b.png)
![9A858396-B4F8-4B0C-9BEE-C09BD25C5EFD](https://user-images.githubusercontent.com/63314427/197419579-26fd6913-fcb3-4b80-a68c-7ada36c0595b.png)

**Comment by DolphinLaser** [comment]
After playing the video for a few minutes I noticed the sponsored segments show up on the timeline and the controls appear on the screen. It continues working until I close the app. The problem reappears whenever the app is closed and reopened.

**Comment by qnblackcat** [comment]
https://status.sponsor.ajay.app/

**Comment by qnblackcat** [comment]
Also please complete the issue template
