### ISSUE TITLE
[Questions] How do I add the uYou+ source repo into AltStore ?

### ISSUE THREAD

**Issue by antondalov** [qnblackcat/uYouPlus#607]
I can't seem to find a way to add the https://qnblackcat.github.io/AltStore/ reposiroy into my AltStore. How do i fix this ?

**Comment by yodaluca23** [comment]
You open AltStore and insert this link "https://qnblackcat.github.io/AltStore/apps.json" as an untrusted source... It's a beta feature right now, so you'll have to have at least the $2/Month level on AltStore's Patreon page and have your Patreon account linked to AltStore and then it'll give you the option to install the beta...

**Comment by qnblackcat** [comment]
Answered by @yodaluca23
