### ISSUE TITLE
[Bug] Cannot download Public playlist

### ISSUE THREAD

**Issue by kuitog** [qnblackcat/uYouPlus#608]
### Device info
- iOS/iPadOS version: 15.6
- Device model: Iphone xs max
- Sideload tool: Sideloadly
- The specific version of uYouPlus: v17.41.2-2.1

### Describe the bug
I open a public playlist of mine, click on the top left (uyou+ download button) and it throws an error: couldn't find any video in the playlist.
I also saw here that other users are experiencing it:
https://www.reddit.com/r/AltStore/comments/sfw6r3/question_is_there_a_fix_for_the_uyou_error/

Also: if I get the sharing link of the playlist and I paste it into the uY+ downloader, it starts the download of the 1st video only.

### How to reproduce the bug
See description

### Crash log (if possible)
No crash

### Are you using the newest version of uYouPlus? If not, why?
Yes

### Does the issue happen with the official YouTube from AppStore?
Can't reproduce on original YT

**Comment by qnblackcat** [comment]
Known issue of uYou

**Comment by MarioMastr** [comment]
For me the downloading just doesn't work in playlists. It says no quality to be found.

**Comment by Hex34568** [comment]
> Known issue of uYou

can u fix it?

**Comment by EscapeAltDelete** [comment]
> > Known issue of uYou
> 
> 
> 
> can u fix it?

He doesn't work on uyou only uyou+ as far as i know

**Comment by qnblackcat** [comment]
This feature will be removed in uYou 3.0
