### ISSUE TITLE
[Questions] Is there any way to hide iSponsorBlock icon from Navigation Bar?

### ISSUE THREAD

**Issue by NetAnarchy** [qnblackcat/uYouPlus#609]
Hi!
I’m very new to here, I would like to ask one question. I’m using iSponsorBlock feature, but its icon on Navigation Bar is sometimes felt annoying. Is there any way to hide or move its settings to other section? (e.g. YouTube Settings section)
Please anyone help us to solve this problem.
Thank you.

**Comment by qnblackcat** [comment]
Please ask the dev of iSponsorBlock https://github.com/Galactic-Dev/iSponsorBlock

**Comment by NetAnarchy** [comment]
Thank you for your reply!
And also thanks to you for your patient work, every moments!
I’m gonna support this project, so pls keep doing @qnblackcat !
Thank you so much 😊
