### ISSUE TITLE
1080p50

### ISSUE THREAD

**Issue by oomek** [qnblackcat/uYouPlus#61]
Hi. Does your fork address the issue of stream quality selector failing on 720p50, 1080p50 streams? uYou is still being stuck in 480p when the stream isn't 30 or 60 fps

**Comment by qnblackcat** [comment]
Someone else reported this issue on uYou’s github

https://github.com/MiRO92/uYou-for-YouTube/issues/85
https://github.com/MiRO92/uYou-for-YouTube/issues/56
