### ISSUE TITLE
[Help] I can't build uYouPlus using Theos

### ISSUE THREAD

**Issue by siieo** [qnblackcat/uYouPlus#611]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

I already read that https://github.com/qnblackcat/uYouPlus/wiki/Building - https://github.com/kabiroberai/theos-jailed/wiki/Installation

also I have sdks from 12.4 till 16.0b4

What about theos-jailed ? Already installed

###
<img width="655" alt="Screenshot 2022-10-26 at 8 28 46" src="https://user-images.githubusercontent.com/68543703/197934812-76ade69b-50fd-4b85-ac3f-18469af820a1.png">

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/issues/297#issuecomment-1190928885

Make sure you have iOS 15.5 SDK

**Comment by siieo** [comment]
<img width="353" alt="Screenshot 2022-10-26 at 8 41 13" src="https://user-images.githubusercontent.com/68543703/197936204-df63e6b2-8324-4b45-bf7d-e329bab178e3.png">

**Comment by qnblackcat** [comment]
I mean follow this comment https://github.com/qnblackcat/uYouPlus/issues/297#issuecomment-1190928885 and also make sure you have iOS 15.5 sdk

**Comment by siieo** [comment]
<img width="976" alt="Screenshot 2022-10-26 at 8 54 33" src="https://user-images.githubusercontent.com/68543703/197938099-318c2d8a-4a5b-433f-beb0-e8ea3ebd0e32.png">

The next level

**Comment by siieo** [comment]
never mind I got it to works now I just added RemoteLog.h to theos include
