### ISSUE TITLE
iPhone 14 PiP iOS 16.1

### ISSUE THREAD

**Issue by emiliowu** [qnblackcat/uYouPlus#612]
### **Device info**
iOS/iPadOS version: iOS 16.1
Device model: IPhone 14 Pro Max
Sideload tool: Sideloadly
Version of uYouPlus: v17.41.2-2.1

### **Describe the bug**
Ever since update to iOS 16.1, with PiP enabled and when playing a video but swiping up to minimize out of YouTube. The video goes into the dynamic island instead of PiP.

Not sure if its a setting I accidentally changed or if it is iOS 16.1. 

Before the update to iOS 16.1, I was able to swipe up on the home bar and the video will continue playing in a PiP window. Now, I needed to have "Use PiP Button" inside YouPIP checked and click on the PiP button found on buttons overlay on the player and then swipe up on the home bar to have the video continue to play in PiP.

**Comment by yodaluca23** [comment]
Yea it's happening to me too...

**Comment by arichorn** [comment]
This ain’t happening on my phone but PiP recently stopped working on my iPad for some reason so I had to use the YouPiP Button ever since.

**Comment by qnblackcat** [comment]
Any update?

**Comment by ciaociaoweb** [comment]
Still happening on iPadOS 16.2

**Comment by emiliowu** [comment]
I think the issue has been resolved. Not too sure with which version. But definitely the newer version. Also check if you have the Use PiP buttons turned off
![AADFD06F-4E3D-4548-B305-BE04577508CE](https://user-images.githubusercontent.com/6876039/212718190-2df2223f-850f-4d07-9fb0-6886342c4f04.jpeg)
