### ISSUE TITLE
[Bug] Like and dislike digits appearing only on dislike button

### ISSUE THREAD

**Issue by Nexxol** [qnblackcat/uYouPlus#613]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.1
- Device model: MQ1F3ZD/A
- Sideload tool : AltStore 
- The specific version of uYouPlus: v17.41.2-2.1

### Describe the bug

YouTube likes and dislike numbers are only on the dislike button
### How to reproduce the bug
![B5D1C9D4-B0D6-46DC-918F-368D38098B6B](https://user-images.githubusercontent.com/68960034/198009682-0f95a61a-4d24-4e8e-947a-05d793414a2d.jpeg)

### Are you using the newest version of uYouPlus? If not, why?
im using latest version

### Does the issue happen with the official YouTube from AppStore?
Nope

**Comment by PoomSmart** [comment]
That's the current limitation of Return YouTube Dislike tweak.
