### ISSUE TITLE
[Bug] Isponsor block not working

### ISSUE THREAD

**Issue by Hex34568** [qnblackcat/uYouPlus#618]
### Device info
- iOS/iPadOS version: 16.1
- Device model:Ipad 6 generation 
- Sideload tool (AltStore)
- The specific version of uYouPlus: latest
 
Video:
https://user-images.githubusercontent.com/103202023/198306685-2dd6b2d6-d7d2-47e7-ba90-8451a11df323.mov

### Describe the bug:

Isponsor block not working as u can see in the video it was working fine on ios 15.7. After i updated It just stopped working for no reason plz fix it now.

**Comment by MarioMastr** [comment]
sponsorblock's servers were down. theyve been going down a whole lot lately; im a bit concerned
