### ISSUE TITLE
[Bug] YT crashes after tapping on notification bell button

### ISSUE THREAD

**Issue by CySxL** [qnblackcat/uYouPlus#621]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS14.8
- Device model: iPhone 11 Pro Max
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...)
No. Officially installed from Appstore
- The specific version of uYouPlus: 
uYou 2.1 from Miro's repo.
YouTube 17.42.7 from Appstore

### How to reproduce the bug
1. Find an already subscribed channel and enter its home page.

2. Click on the notification bell icon at the right of subscription button. 
![image](https://user-images.githubusercontent.com/15531137/198642889-d5567c11-e7b5-4dda-b160-4cb9f60a3263.png)
3. YouTube crashes.

### Crash log (if possible)

Crash log from Cr4shed : https://pastebin.com/wSUA3qxW

Crash log from Settings : https://pastebin.com/9JKwFpvn

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_
No. I'm using uYou.
### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
No. tested in Safe mode.
### Additional context: 
Sorry for putting it here as I know Miro has been away from community a long while. uYou Plus team is the one who has ability yo solve this.

**Comment by qnblackcat** [comment]
This issue has been solved by level3tjg

https://github.com/qnblackcat/uYouPlus/pull/240/commits/f2cb699e3b7222121af38846564486029f00b09f

**Comment by CySxL** [comment]
> This issue has been solved by level3tjg
> 
> 
> 
> https://github.com/qnblackcat/uYouPlus/pull/240/commits/f2cb699e3b7222121af38846564486029f00b09f

Thanks a lot for pointing it out !!!
