### ISSUE TITLE
Feature request: a way to export settings from one version and import them into another version 

### ISSUE THREAD

**Issue by MarioMastr** [qnblackcat/uYouPlus#624]
This may not be possible, but since i can't update uYouPlus without deleting the existing app first, it would be really cool to be able to export and import settings so i dont have to waste time changing my settings back to how i like them.

**Comment by jackhinkle** [comment]
Agreed 100%. I know it might not be easy to implement, but if it's impossible to fix the whole update bug then I'd much rather have this.

**Comment by Hex34568** [comment]
> This may not be possible, but since i cant uyouplus without deleting the existing app first, it would be really cool to be able to export and import settings so i dont have to waste time changing my settings back to how i like them.

if u  use altstore u can reinstall the latest version without having to delete the old version and ur settings will not be deleted just don't delete the older version and install the latest ur settings will remain the same as the u had with the old version.

**Comment by LancerLucky** [comment]
> > This may not be possible, but since i cant uyouplus without deleting the existing app first, it would be really cool to be able to export and import settings so i dont have to waste time changing my settings back to how i like them.
> 
> 
> 
> if u  use altstore u can reinstall the latest version without having to delete the old version and ur settings will not be deleted just don't delete the older version and install the latest ur settings will remain the same as  u had with the old version.

I have tried reinstalling the latest version but get error. So the only work around I tried successfully is delete the existing one and then install the new version.

**Comment by LeviSnoot** [comment]
Fully agreed, in the current state I'd say it's even necessary to keep an install functioning. The solution @Hex34568 suggested I have tried before and has never worked. It just gets stuck infinitely installing the app (I've left the install running for over 30 minutes in the past). Only way for me to update rn is by removing the app and reinstalling.

**Comment by arichorn** [comment]
This is a great idea! Love this suggestion but I think it’ll be best if it was added onto YTABConfig! Being able to export flags is another cool thing to do!

**Comment by MarioMastr** [comment]
It's been a week since I opened this. I see some people have given my original comment the eyes. Any updates?

**Comment by asportnoy** [comment]
I'm also having issues with updating. Might be better to figure out why updating isn't working properly. Using Signolous btw

**Comment by MarioMastr** [comment]
Update: this is no longer necessary as altstore has fixed the issue of updating uyouplus
