### ISSUE TITLE
(Help)- Not installing

### ISSUE THREAD

**Issue by Blockr22** [qnblackcat/uYouPlus#625]
## Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###
Not installing on my iPhone XS max using altstore.
Some versions does install but recently more & more versions doesn’t install. Upgrade from old version to new doesn’t work aswell.

**Comment by eobi1976** [comment]
Yeah I’m having the same problem

**Comment by Blockr22** [comment]
Got it fixed, just had to remove any old uYou+ from storage settings & also remove altstore & reinstall it & then install latest version of uYou+. It seems like altstore is busted & needs a fix.
