### ISSUE TITLE
[Request] uyouplus date from oldest date from newest 

### ISSUE THREAD

**Issue by xuemio73** [qnblackcat/uYouPlus#627]
The sorting function of videos has disappeared, and sorting worked if it was operated from channel registration, but it has finally disappeared.  Sort videos Is it possible to add new order and old order?

**Comment by qnblackcat** [comment]
Not possible since it's controlled by server. Plus we also have other priorities

**Comment by arichorn** [comment]
> The sorting function of videos has disappeared, and sorting worked if it was operated from channel registration, but it has finally disappeared. Sort videos Is it possible to add new order and old order?

Use this version of uYouPlus https://github.com/arichorn/uYouPlusExtra/releases/tag/v16.42.3-2.1-(547)
It’s basically the same but 16.42.3 has the “Sort by Oldest” Option in the channel.

**Comment by arichorn** [comment]
> Not possible since it's controlled by server. Plus we also have other priorities

Actually there could be a possibility. It could be disabled in the App by default because the removal of this feature was probably hidden in the newer YouTube Versions. If I could specify where Sort By Oldest is at the it could be brought back
