### ISSUE TITLE
[Bug] App data keeps randomly resetting

### ISSUE THREAD

**Issue by AuroraWright** [qnblackcat/uYouPlus#63]
**Device info:**
- iOS/iPadOS version: 15.3.1
- Device model: iPhone 13
- Sideload tool (Ex: AltStore, Sideloadly...) xcode and iOS App Signer
- Version of uYouPlus: 17.06.3-2.1/17.04.3

**Describe the bug:**
- Not sure if this depends on any specific settings I've changed, but for me uYou Plus randomly resets all settings on a random interval between a few hours to a day of rather intensive usage. At some point videos will start playing in PiP when switching to a different app (which I disable) which is a sign that the reset occurred; and as soon as YouTube is killed/reopened the setup wizard shows again. The reset seems completely random and there's no apparent trigger, settings seem to be otherwise saved normally and persist when killing the app and rebooting the device.
I'm using an iPhone 13 on latest iOS (15.3.1) and a paid developer certificate from UDID registrations (I use iOS app signer on macOS for signing). I've observed this on both 17.04.3 and 17.06.3-2.1. I also tried disabling iCloud backups for the app, in case something weird was happening with that, to no avail.

**How to reproduce the bug:**
_(Please attach videos or screenshots if possible)_
It’s random

**Crash log (if possible):**
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
Nothing shows up relating to YouTube

**Additional context:**
_(Add any other context about the problem here)_

**Comment by AuroraWright** [comment]
these are the settings I change:
general:
- non backgroundable PiP to on
- use video tab bar PiP button to on
- use PiP button to on
- stats for nerds to on
- playback in feeds to off
auto-play to off
use vp9 codec to on
background & downloads:
- download over WiFi only to off
uyou:
see screenshot for some settings, plus
buttons under video player: hide download button to off
hide tabs: hide create tab to off
![3B5F0608-34FB-4F46-9B74-F1DD0C9EF690](https://user-images.githubusercontent.com/15571693/154646735-c025d837-e294-4bcb-b63e-0912da24c9c7.png)

**Comment by qnblackcat** [comment]
Thank you for your report!

It has been confirmed that sideload tools based on [ZSign](https://github.com/zhlynn/zsign) have this issue. However, I did not expect the same thing happens on iOS App Signer. For now, I highly recommend you use AltStore or Sideloadly instead

**Comment by AuroraWright** [comment]
After experimenting a bit, it seems that for this to work properly the bundle ID has to start with "com.google.ios.youtube" but not be exactly it. If it's exactly "com.google.ios.youtube" data will be randomly reset, if it's "com.google.ios.youtube.whatever" then it works fine. No clue why

**Comment by qnblackcat** [comment]
Did you remove the vanilla YouTube?

**Comment by AuroraWright** [comment]
> Did you remove the vanilla YouTube?

Yes. I think no one has issues with AltStore because it sets a bundle id like "com.google.ios.youtube.<TEAM ID>" (from what I can tell)

**Comment by AuroraWright** [comment]
> > Thank you for your report!
> > It has been confirmed that sideload tools based on [ZSign](https://github.com/zhlynn/zsign) have this issue. However, I did not expect the same thing happens on iOS App Signer. For now, I highly recommend you use AltStore or Sideloadly instead
> 
> What tools are based on ZSign?
> 
> I've tried Signulous and using E-Sign directly with my certificate to sign uyou+, but I still get the reset issue.

You need to change the bundle id to com. google.ios.youtube.whatever, as explained above. That fixes the issue, have been using uYou for a while now

**Comment by notrespire** [comment]
> > > Thank you for your report!
> 
> > > It has been confirmed that sideload tools based on [ZSign](https://github.com/zhlynn/zsign) have this issue. However, I did not expect the same thing happens on iOS App Signer. For now, I highly recommend you use AltStore or Sideloadly instead
> 
> > 
> 
> > What tools are based on ZSign?
> 
> > 
> 
> > I've tried Signulous and using E-Sign directly with my certificate to sign uyou+, but I still get the reset issue.
> 
> 
> 
> You need to change the bundle id to com. google.ios.youtube.whatever, as explained above. That fixes the issue, have been using uYou for a while now (I personally use a local SignTools instance)

Yea I tried that already. Using Signulous and E-Sign. It still resets randomly. I don't have the regular YouTube installed.

**Comment by AuroraWright** [comment]
It could be that

> > > > Thank you for your report!
> > 
> > 
> > > > It has been confirmed that sideload tools based on [ZSign](https://github.com/zhlynn/zsign) have this issue. However, I did not expect the same thing happens on iOS App Signer. For now, I highly recommend you use AltStore or Sideloadly instead
> > 
> > 
> > > 
> > 
> > 
> > > What tools are based on ZSign?
> > 
> > 
> > > 
> > 
> > 
> > > I've tried Signulous and using E-Sign directly with my certificate to sign uyou+, but I still get the reset issue.
> > 
> > 
> > You need to change the bundle id to com. google.ios.youtube.whatever, as explained above. That fixes the issue, have been using uYou for a while now (I personally use a local SignTools instance)
> 
> Yea I tried that already. Using Signulous and E-Sign. It still resets randomly. I don't have the regular YouTube installed.

It could be that those tools doesn't change it properly and/or for all the plugins, or that they don't patch the binaries to replace it there too (SignTools does this, and AltStore does the first thing at least).

**Comment by qnblackcat** [comment]
Is the issue still happening on `v17.21.3-2.1`?

**Comment by qnblackcat** [comment]
Closed due to inactive. Feel free to reopen it

**Comment by tfurci** [comment]
> Is the issue still happening on `v17.21.3-2.1`?

I am still geting this issue. Changing bundle id doesnt help. Seems like it triggers randomly as sometimes it can be few days before reseting. Using latest E-Sign

**Comment by elisaado** [comment]
Can confirm it is still happening on the latest v18

**Comment by HJebbour** [comment]
I only have this issue when I use ESign, it works with web IPA Signer and equivalent. But the only app that let me update uYou+ is ESign which has the reset issue..
