### ISSUE TITLE
[Bug] uYouLocal video and YouTube video playing simultaneously

### ISSUE THREAD

**Issue by CoolandonRS** [qnblackcat/uYouPlus#630]
### Device info
- iOS/iPadOS version: iOS 16.1
- Device model: iPhone 11
- Sideload tool: AltStore
- The specific version of uYouPlus: 2.1

### Describe the bug
When told to "play" (through Now Playing API) while a video is playing and videos are downloaded to uYouLocal it will start playing both the video and the first video downloaded to uYouLocal

### How to reproduce the bug
Have a video downloaded to uYou Plus
Watch a vidéo as normal
Pause it (through the player or Now Playing API)
Unpause it (through Now Playing API)

### Are you using the newest version of uYouPlus? If not, why?
I believe so

### Does the issue happen with the official YouTube from AppStore?
No

**Comment by CoolandonRS** [comment]
I can no longer reproduce this issue

**Comment by CoolandonRS** [comment]
I have found a consistent way to reproduce the bug.
- Have a video playing in MiniPlayer
- Go to the uYou tab and play a downloaded video
- Use the Now Playing API to pause the downloaded video
Now until the app is restarted, the Now Playing API will consistently start the previously playing downloaded video as well as whatever video may or may not be playing.

**Comment by qnblackcat** [comment]
@therealFoxster is working very hard on this

**Comment by therealFoxster** [comment]
I this still an issue? I haven't experienced this since 880603f.
