### ISSUE TITLE
YouTube Explore

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#631]
uU+ v17.42.7-2.1
Sideloadly
iOS 16.2
iP 14 Pro

The whole menu to choose from different categories like Gaming, Music etc is missing.

Also the sub menu when you tip on the Explore Button is missing as well.

![image](https://user-images.githubusercontent.com/40891294/199090600-e7c4c80e-c7ba-435d-bbd5-d37bb458b795.jpeg)

![image](https://user-images.githubusercontent.com/40891294/199090614-101060cb-f000-4798-9054-3ee3005eade8.jpeg)

**Comment by qnblackcat** [comment]
This is an UI change from YouTube, not a bug
