### ISSUE TITLE
Like and Dislike Button UI Issue

### ISSUE THREAD

**Issue by AbsurdIdealist** [qnblackcat/uYouPlus#632]
Hi all, 

Wondering if this was on purpose or a glitch? Is anyone else experiencing the same issue?

Sincere regards.
![IMG_0610](https://user-images.githubusercontent.com/109076134/199183409-329eee8e-77cc-4eba-be34-1802342d05a4.PNG)

**Comment by qnblackcat** [comment]
What do you mean? If you think this is an issue of RYD, open a new issue on RYD‘s repo: https://github.com/PoomSmart/Return-YouTube-Dislikes
