### ISSUE TITLE
[Bug] Aggregated like/dislike button

### ISSUE THREAD

**Issue by federicotorrielli** [qnblackcat/uYouPlus#633]
### Device info
- iOS/iPadOS version: iOS 16.1
- Device model: iPhone XS
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): Altstore-Linux
- The specific version of uYouPlus: v17.42.7-2.1

### Describe the bug
Aggregated like and dislike button. The numbers appear on the dislike button. See attached photo.

![IMG_0228](https://user-images.githubusercontent.com/31370059/199219102-c977a954-480d-4ee1-bfcd-a8d740dd3d5f.PNG)

### How to reproduce the bug
Watch a video.

### Does the issue happen with the official YouTube from AppStore?
Nope.

### Additional context: 
Nocom.

**Comment by qnblackcat** [comment]
https://github.com/PoomSmart/Return-YouTube-Dislikes/issues/35

**Comment by federicotorrielli** [comment]
> Out of topic, but Altstore-Linux???? Where'd you get it?

https://github.com/NyaMisty/AltServer-Linux
