### ISSUE TITLE
Feature Request: hide YT shorts drawer option

### ISSUE THREAD

**Issue by SuperJumpBros** [qnblackcat/uYouPlus#634]
Hello! I am a YouTube user, but tried using Shorts at one point. Now I have an addiction and would like to stop. I see you've added the option to hide the Shorts tab, but there is no option to completely remove the Shorts Drawer from the app. Can a patch be added for this?

**Comment by qnblackcat** [comment]
uYou‘s setting > Other settings > Remove Shorts….
