### ISSUE TITLE
[Bug] Like/Dislike count not displaying correctly

### ISSUE THREAD

**Issue by korboybeats** [qnblackcat/uYouPlus#635]
- iOS/iPadOS version: 15.5b4
- Device model: M1 iPad Pro
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) TrollStore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 17.42.7_2.1

### Describe the bug

Like/Dislike displaying incorrectly

### How to reproduce the bug

![327DE482-D612-41C2-AF0F-A34F0B126CA0](https://user-images.githubusercontent.com/80824905/199390163-501c5f77-bfa3-48db-8b91-287326bd7539.jpeg)

**Comment by qnblackcat** [comment]
https://github.com/PoomSmart/Return-YouTube-Dislikes/issues/35
