### ISSUE TITLE
[Bug] Opening channel from website in YouTube opening "null" channel

### ISSUE THREAD

**Issue by MarioMastr** [qnblackcat/uYouPlus#637]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.1
- Device model: iPhone 11
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_
17.43.1-2.1 (this version I use was built by @arichorn)
### Describe the bug
If I try to open a YouTube channel from safari in uYouPlus with the share menu, it always, no matter which channel I try to open, will take me to one called "null"

### How to reproduce the bug
https://user-images.githubusercontent.com/84964352/199429812-a0efc852-493d-4272-ba5f-c219696f9496.MOV

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_ custom built

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_ no because deep link

### Additional context: 
This issue has been happening for a while, but I just now got around to reporting it.

**Comment by MarioMastr** [comment]
@CokePokes

**Comment by qnblackcat** [comment]
Issue of Open In YouTube extension should go to its repo: https://github.com/CokePokes/YoutubeExtensions

**Comment by arichorn** [comment]
Definitely caused by The Extension

**Comment by arichorn** [comment]
I can also say that is Extension was intended for iOS 15 since I readed the readme.md file, maybe that’s why it broke, but can’t confirm it though.
