### ISSUE TITLE
[Request] Hide uYou tab in the navbar

### ISSUE THREAD

**Issue by jasim-mohd** [qnblackcat/uYouPlus#638]
for those with premium but needs all other features in uYouPlus

**Comment by arichorn** [comment]
You know if you hide the uYou tab bar, you will not have the ability to change the uYou settings from it, to be honest this was probably the reason why there was no toggle to turn it off in the first place.

**Comment by qnblackcat** [comment]
It should be requested on upstream uYou‘s repo https://github.com/MiRO92/uYou-for-YouTube

**Comment by arichorn** [comment]
Well I don’t know about that, the settings are in the uYou Tab!
