### ISSUE TITLE
Error when install with bullfrog assistant ! 

### ISSUE THREAD

**Issue by AnhNangCuaEm** [qnblackcat/uYouPlus#639]
![172F818F-2448-4652-B626-0DEB0E878BF8_1_101_o](https://user-images.githubusercontent.com/102863074/199487170-4c17ef14-e402-4aef-859c-f8ebd0896652.jpeg)
I was try to install on Ipad but it failed too.
What should I do ? 
IOS 16.1 , Ipad OS 16.1

**Comment by MarioMastr** [comment]
This isn't a Bullfrog Assistant specific issue by a long shot. Do you have any other uYouPlus version installed? If so, uninstall them from the icon on the home menu (not removing them in Bullfrog) and then try again.
