### ISSUE TITLE
[Bug] Videos are unable to download

### ISSUE THREAD

**Issue by romantra** [qnblackcat/uYouPlus#64]
**Device info:**
- iOS/iPadOS version: 15.1.1
- Device model: iPhone 11 Pro Max
- Sideload tool: ESign 4.3.7
- Version of uYouPlus: v17.06.3-2.1

**Describe the bug:**
- When I try to download a video it starts downloading normally the video but when it finishes I'm getting an error that says:
Error 200 - Unable to move file from file:///var/mobile/Library/Caches/com.apple.nsurlsessionid/Downloads/com.latin.*/CFNetworkDownload_YTTMnk.tmp...

Full error in the link: https://youtu.be/PZxcfL_MnfY

**How to reproduce the bug:**
_(Please attach videos or screenshots if possible)_

I'm in a unjailbreak state and I have side loaded the app using esign an a dev cert, but I'm unable to download the video since I don't have some permissions to transfer the file downloaded from a cache folder to the app folder.

When I use cercube I can download the videos without issues but I like more uYouPlus :)

**Crash log (if possible):**
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Additional context:**
_(Add any other context about the problem here)_
![Cargando 154822453...]

**Comment by romantra** [comment]
Video link added hope you could help us to solve it for the non jailbroken users thanks in advance!

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
