### ISSUE TITLE
Can the iSponsorblock element of uYouPlus be updated to support custom APIs?

### ISSUE THREAD

**Issue by PencilNotPen** [qnblackcat/uYouPlus#644]
As discussed here:

https://github.com/Galactic-Dev/iSponsorBlock/issues/61

The Sponsorblock default server is often down, meaning segments do not appear on videos. The browser extension already has support for changing the API to one which is not down, and I wonder if this could be incorporated into iSponsorblock in uYouPlus.

The link above goes to an issue on iSponsorblock's Github in case of needing to cooperate with the dev, and that issue links to an example aggregate server which can replace the default server. When the default is up, it goes through the default, but when it is down, it redirects requests to a couple of backups to keep Sponsorblock functioning.

This aggregate server could be used as the default in iSponsorblock, but probably a better idea is just to support a field in iSponsorblock's settings where a new server can be typed by the user, as in the browser extension.

Thanks!

**Comment by qnblackcat** [comment]
why don’t you request this feature on the mainstream of iSponsorBlock?! https://github.com/Galactic-Dev/iSponsorBlock

**Comment by PencilNotPen** [comment]
I have done, but it doesn’t seem very active in terms of recent commits. I wasn’t sure if you were updating it yourself or using the version as-is from isponsorblock, so I thought I’d mention it in both places. Cheers!
