### ISSUE TITLE
[Bug] video stops playing when screen is turned off, have to manually press play 

### ISSUE THREAD

**Issue by Skornickk** [qnblackcat/uYouPlus#647]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 14.3
- Device model: X
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) Trollstore 
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 17.4.2.7_2.1

### Describe the bug
video stops playing when device is locked, can be restarted  

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
1. go on video 
2. go to home screen to put video on PIP
3. lock the screen and playback is paused4.  
### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_
yes
### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
can’t check, no premium

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
