### ISSUE TITLE
[Questions] Default Video Playback Speed

### ISSUE THREAD

**Issue by megamorphg** [qnblackcat/uYouPlus#65]
### Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

Is there really no way to set a default video playback speed?

With so much videos to watch nowadays, it is common to set a default playback speed of 1.5x.

Please add this feature if possible.

**Comment by qnblackcat** [comment]
https://www.ios-repo-updates.com/repository/bigboss/package/com.lyvendia.ytspeed/amp/

[YTSpeed] is the closest thing we have for now. Feel free to buils your own IPA with YTSpeed included. 

https://github.com/qnblackcat/uYouPlus/wiki/Building

**Comment by qnblackcat** [comment]
The source code of YTSpeed: https://github.com/Lyvendia/YTSpeed

**Comment by megamorphg** [comment]
Thank you! I noticed that increasing the playback speed stays per session. This will be enough for me without having to build a new IPA and separated from your releases. :)

**Comment by qnblackcat** [comment]
That’s right. YouTube keeps the video speed until you close the player or kill the app

**Comment by lazyb5** [comment]
Would it be hard to implement, keeping set speed through close/killing of the app?
