### ISSUE TITLE
YouTube links in other apps failing to open to uYou+

### ISSUE THREAD

**Issue by C3N0** [qnblackcat/uYouPlus#653]
![IMG_4593](https://user-images.githubusercontent.com/117591114/200184532-e523a12a-273c-4916-8b0a-241a147fd7f2.png)
![IMG_4592](https://user-images.githubusercontent.com/117591114/200184533-fca21639-b5fd-40a0-b355-63c591fc34ba.png)

### Device info
- iOS/iPadOS version: iOS 16.2
- Device model: iPhone XS Max
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) Altstore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 17.42.7

### Describe the bug 
**When opening a link to YouTube from another app such as Discord, it opens to Safari instead of directing me to the YouTube app**

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
**Attached, Image 4592 is before (The link in Discord) and 4953 is after (After opening the link, it redirects me to Safari)**

### Crash log (if possible)
**In my case there is no crash reply.**

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_
**I believe I am using the latest version, just downloaded it yesterday.**

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
**No, YouTube embed links work perfectly fine**

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
