### ISSUE TITLE
[Questions] why I can't download any video or short or anything? When I try I get an error saying unable to move file from I don't know what and a red bar (Uyou+) help please

### ISSUE THREAD

**Issue by AngealAuditore** [qnblackcat/uYouPlus#66]
### Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
