### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by TeaRex-coder** [qnblackcat/uYouPlus#662]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.2 public beta 1
- Device model: iPhone 14
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) AltStore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 17.43.1-2.1

### Describe the bug
In a recent update to Youtube, a zoom feature was added

With the DontEatMyContent tweak enabled it breaks the zoom functionality

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Just pinch with two fingers to zoom

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
No it doesn't

**Comment by TeaRex-coder** [comment]
It looks like its being worked on https://github.com/therealFoxster/DontEatMyContent/issues/6#issuecomment-1309744684

**Comment by arichorn** [comment]
I have this issue too, this explains why my zoom in fullscreen has been bugged

**Comment by qnblackcat** [comment]
Solved in https://github.com/qnblackcat/uYouPlus/pull/670
