### ISSUE TITLE
[Bug] Welcome screen doesn't disappear after installation

### ISSUE THREAD

**Issue by khashabri** [qnblackcat/uYouPlus#664]
### Device info
- iOS/iPadOS version: 16.1.1
- Device model: iPhone XS
- Sideload tool AltStore
- The specific version of uYouPlus: YouPlus_17.43.1_2.1

### Describe the bug
The welcome screen doesn't disappear after installation making the app unsable. 
<img src="https://user-images.githubusercontent.com/50481847/201327324-24bcf699-cf1f-4f4a-9c2e-acfb4168d9a0.jpeg" width="300">

### How to reproduce the bug
Install and open the app.

**Comment by NataliaLopez17** [comment]
same thing just happened to me. The previous version too.

**Comment by NataliaLopez17** [comment]
Actually, it's happening on more previous versions too 😭

**Comment by NataliaLopez17** [comment]
@khashabri is there a very white continue text at the bottom that cannot be seen unless you're staring at it?

**Comment by level3tjg** [comment]
I'm guessing there is probably some changes to OnBoardingKit in 16.1 causing this... @NataliaLopez17 could you confirm you're also on 16.1?

**Comment by MattFrom72** [comment]
I'm having exactly the same issue on a new iPhone 14 Pro running iOS 16.2. I have tried a few versions of uYouPlus and they are all doing the same.

**Comment by Rubarius** [comment]
The same problem iphone 14 pro

**Comment by qnblackcat** [comment]
Will be fixed in the next release

**Comment by qnblackcat** [comment]
Fixed in [v17.49.6-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.49.6-2.1) and higher
