### ISSUE TITLE
[Bug] Shorts crash (again)

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#665]
### Device info
- iOS/iPadOS version: 16.2
- Device model: 14 Pro
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus: v17.43.1-2.1

### Describe the bug
Watching shorts randomly crashes the app. This time the shorts in the subscriptions tab crash and not those in the shorts tab

### Does the issue happen with the official YouTube from AppStore?: not that I've noticed

**Comment by qnblackcat** [comment]
Crashlog?

**Comment by qnblackcat** [comment]
_Please provide the crash log_

**Comment by qnblackcat** [comment]
> > _Please provide the crash log_
> 
> `mega.nz/folder/TZ91wAYL#b3FaWl-3h70XvdhrzcHKFA`
> 
> Please reply if I can delete the link. Idk if there's private info in there

Ok

**Comment by MrZomka** [comment]
It happens literally everywhere, not just shorts. This also happens on the vanilla app which is awful :(

I’m on 15.2.1, A15.

**Comment by qnblackcat** [comment]
Any update?
