### ISSUE TITLE
[Bug] iSponsorblock activated but missing

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#666]
### Device info
- iOS/iPadOS version: 16.2
- Device model: 14 Pro
- Sideload tool: Sideloadly
- The specific version of uYouPlus: v17.43.1-2.1

### Describe the bug
iSponsorblock is integrated and activated but it's icons are not showing up in the video player and it's not skipping. And the timestamp doesn't show the shortened time.

![image](https://user-images.githubusercontent.com/40891294/201362008-d25c22a5-855b-423f-872c-27f5d9623904.jpeg)

![image](https://user-images.githubusercontent.com/40891294/201361985-d7f84f57-fca5-4dc9-b76b-f158e9db1766.jpeg)

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_: lol

**Comment by qnblackcat** [comment]
https://status.sponsor.ajay.app/
