### ISSUE TITLE
[Bug] Google Sign in fix has no effect

### ISSUE THREAD

**Issue by ExperiBass** [qnblackcat/uYouPlus#667]
### Device info
- iOS/iPadOS version: 15.4.1
- Device model: iPhone 12 (13,2)
- Sideload tool: TrollStore
- The specific version of uYouPlus: 17.43.1_2.1

### Describe the bug

After enabling the TrollStore fix and restarting the app, logging in still fails. After you type in your email and hit "Next", the login page will infinitely load.

### How to reproduce the bug
1. Enable the TrollStore fix and restart.
2. Attempt to sign in.
3. Wait until the end of time.
<img src="https://cdn.discordapp.com/attachments/969745853562622003/1040758008931684452/IMG_0574.png" height="700"/>

### Crash log (if possible)
App didnt crash and theres no logs anyways (i checked)

### Are you using the newest version of uYouPlus? If not, why?
No, im in the future.

### Does the issue happen with the official YouTube from AppStore?
No.

**Comment by qnblackcat** [comment]
I can login just fine, even without the sign-in fix. Have you tried to login again?

**Comment by EscapeAltDelete** [comment]
i thought Trollstore didn't support 15.4.1

**Comment by ExperiBass** [comment]
yes, ive tried downgrading as well, no luck. i couldnt find any working solutions online either.

**Comment by PoomSmart** [comment]
@ExperiBass Does it work if you try this on a vanilla YouTube app (from App Store)?

**Comment by ExperiBass** [comment]
ye, signing in with the appstore youtube works perfectly.

**Comment by qnblackcat** [comment]
@ExperiBass I can’t reproduce this issue on any of my devices. Double-check your internet connection / VPN maybe?

**Comment by ExperiBass** [comment]
switching between wifi and data doesnt fix it, nor does switching my vpn on or off...

**Comment by qnblackcat** [comment]
@ExperiBass how about using another google account?

**Comment by ExperiBass** [comment]
same result @w@ 

this is odd. Could youtube have introduced something between the version uYou+ is on and the app store version?

**Comment by qnblackcat** [comment]
well, you could follow this method https://github.com/qnblackcat/uYouPlus/discussions/447

**Comment by ExperiBass** [comment]
yeah, that doesnt work either, same result.

**Comment by ExperiBass** [comment]
\*le gasp*

it just... started working? suddenly it got ahold of the youtube data and i was able to just tap my account. i dont know what the solution couldve been.
