### ISSUE TITLE
[Bug] YouTube homepage still showing shorts, YT premium ads and featured content.

### ISSUE THREAD

**Issue by EscapeAltDelete** [qnblackcat/uYouPlus#669]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.2
- Device model: iPad (8th gen)
- Sideload tool: Sideloadly
- The specific version of uYouPlus: 17.43.1_2.1

### Describe the bug
Sometimes when you're on the homepage it still shows premium ads, shorts and featured stuff. When clicked upon it vanishes. (i didn't click the X)

### How to reproduce the bug

https://user-images.githubusercontent.com/96600150/201450305-14c3cae2-5c77-4696-8886-f5c9cdbf4262.mov

https://user-images.githubusercontent.com/96600150/201450310-96dc3fc5-9057-40e2-b277-bb5a0c51384a.mov

### Crash log (if possible)
App didn't crash.

### Are you using the newest version of uYouPlus? If not, why?
yes

### Does the issue happen with the official YouTube from AppStore?
no

### Additional context: 
My A/B modified settings (Might be helpful idk)
Total: 6
YTColdConfig.enableCinematicContainer: 1
YTColdConfig.enableDarkerDarkMode: 1
YTColdConfig.uiSystemsClientGlobalConfigEnableModernButtonsForNativeLongTail: 1
YTColdConfig.uiSystemsClientGlobalConfigEnableRoundedDialogForNative: 1
YTHotConfig.enableLinearLiveUxIos: 1
YTHotConfig.enableLocationResolutionUxIos: 1

**Comment by qnblackcat** [comment]
That’s my attempt to remove YouTube promotion ads. Sr if you see it’s annoying, but I did my best

**Comment by EscapeAltDelete** [comment]
Oohh that's fine then, thanks for everything you do!

**Comment by Hex67** [comment]
> Oohh that's fine then, thanks for everything you do!

it happens to me too!! god it’s annoying

**Comment by Hex67** [comment]
> That’s my attempt to remove YouTube promotion ads. Sr if you see it’s annoying, but I did my best

can u give us an option if we want to turn off youtube premium ads or not?
