### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by AggressiveSharon** [qnblackcat/uYouPlus#676]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.6
- Device model: iPhone XR 
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) Alrstore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_  Version 17.43.1_2.1
### Describe the bug

Uplus option to download shorts, disappear after one download. None of the other options pop up either to download any other YT short. Even when you hold on for more options for the short, there’s no “uplus” option that pops up anymore.  

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
![834E709F-4843-4045-935C-8669844D3484](https://user-images.githubusercontent.com/118253273/201866899-d655ed80-8701-4be4-baf2-8e5af720b959.png)

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why? 
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_ 
I am using the newest version. 

### Does the issue happen with the official YouTube from AppStore? 
_(Well, YouTube itself is buggy sometimes...)_ 
no it doesn’t happen with the normal YouTube app.

**Comment by qnblackcat** [comment]
Just play a Short video, the Short download buttons are in the control overlay.
