### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by grohit1810** [qnblackcat/uYouPlus#681]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###
Hi,
I know that there is update on FAQ that YouTube unable to sign in issue is fixed and it is working in the latest version. I downloaded the latest version last week. I was able to login. Today I changed my Google password and it forced signed me out from the app and so when I tried to login again  I am unable to sign in since. Is the unable to sign in error back raised again?

**Comment by qnblackcat** [comment]
See https://github.com/qnblackcat/uYouPlus/discussions/683/
