### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by AggressiveSharon** [qnblackcat/uYouPlus#685]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 15.6
- Device model: iPhone XR 
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) Altstore
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 
The version is 17.43.1_2.1

### Describe the bug
No other options, than the basic options for downloading shorts. I wanna download a short using Uplus, but I don’t have those extra options, as showed in the screenshot. 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_ 
![9A8E9A3B-A311-4619-B540-B85676D4F130](https://user-images.githubusercontent.com/118253273/202080926-752596f3-c1ee-4d5d-a622-d023f26ec504.jpeg)
![3821040E-F03A-4781-8273-B38E1F6C34F6](https://user-images.githubusercontent.com/118253273/202080957-2c88b050-14c2-4f48-8f15-e2e7eab5b036.jpeg)

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_
I’m using the newest version. 

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
It does not

**Comment by qnblackcat** [comment]
Did you modify any value in YTABConfig‘s setting?

**Comment by AggressiveSharon** [comment]
> Did you modify any value in YTABConfig‘s setting?

Yes.

**Comment by qnblackcat** [comment]
> > Did you modify any value in YTABConfig‘s setting?
> 
> Yes.

Try to restore all values to default

**Comment by AggressiveSharon** [comment]
> > > Did you modify any value in YTABConfig‘s setting?
> > 
> > 
> > Yes.
> 
> Try to restore all values to default

It didn’t do anything
