### ISSUE TITLE
[Enhancement] Userscript to automatically prompt to open YouTube app

### ISSUE THREAD

**Issue by asportnoy** [qnblackcat/uYouPlus#69]
I made a userscript to automatically prompt you to open the YouTube app when you open a YouTube link in safari. I already had a Siri shortcut to do this, but I prefer this because it will automatically prompt you instead of having to dig through the share menu.

Safari extension to run user script (free): https://apps.apple.com/us/app/userscripts/id1463298887
Userscript code: https://gist.github.com/asportnoy/628b820184297f5fe296c1a5b79c8000

### How to install
1) Install [the app](https://apps.apple.com/us/app/userscripts/id1463298887)
2) Launch the app and choose path for scripts
3) Go to [this page](https://gist.githubusercontent.com/asportnoy/628b820184297f5fe296c1a5b79c8000/raw/open-youtube-app.user.js)
4) Open the extension and press install in the banner

**Comment by Write** [comment]
Thanks a lot for this script.
Would it be possible to add a way to open directly the link in the app, like Apollo app is doing ?

**Comment by asportnoy** [comment]
Automatic open in app (including from Apollo) works by using Apple's [smart banners](https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners). Those require you to get the app ID, which only app store apps have.

**Comment by Write** [comment]
Ok thanks a lot !

**Comment by tonysprenk** [comment]
I have downloaded the userscript extension, I have enabled it, I have set the userscript directory, I have downloaded the above script to the directory. When open a YouTube link I don’t get the open in YouTube pop-up, what am I doing wrong?

**Comment by ilm91** [comment]
Awesome! Can you write a code for BHTwitter+ too, which do the same thing, but for the modified Twitter "BHTwitter Plus"? 

BHTwitter Plus: https://github.com/qnblackcat/BHTwitter-Plus_Sideloaded/#download-ipa

**Comment by qnblackcat** [comment]
@asportnoy I‘ve added your solution to the FAQ page.
https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-deep-link-aka-open-in-the-youtube-app-doesnt-work

**Comment by asportnoy** [comment]
> Awesome! Can you write a code for BHTwitter+ too, which do the same thing, but for the modified Twitter "BHTwitter Plus"?
> 
> BHTwitter Plus: https://github.com/qnblackcat/BHTwitter-Plus_Sideloaded/#download-ipa

@ilm91 With Twitter, you would have to do more parsing of the URL to format it into the URL scheme. The URL schemes for Twitter are listed [here](https://github.com/takumi3y/URLScheme/wiki/Twitter).

**Comment by qnblackcat** [comment]
Technically , this is not an issue. I’ll close it but still keep it pinned.

**Comment by fefifofum** [comment]
Maybe this is worth checking out...

https://github.com/CokePokes/YoutubeExtensions

**Comment by qnblackcat** [comment]
[YouTubeExtensions](https://github.com/CokePokes/YoutubeExtensions) (by CokePokes) has been added since v17.17.4-2.1. This user script is most likely not needed anymore.

**Comment by aln4739** [comment]
Hey is it possible to modify the script code to also close the tab in safari as well?

Sorry for opening the issue up again, I wanted to ask because I can't set up YoutubeExtensions by CokePokes

**Comment by aln4739** [comment]
That didn't really help, but I added an update to the script that closes the tab after 5 seconds. You should be able to tap the open in app button quick enough for the tab to close by itself lol. It seems like it's working for me.

Modified script: https://gist.github.com/aln4739/2c04dc54d09e68c73eaccf13266950a1

**Comment by dudu-castro** [comment]
> I made a userscript to automatically prompt you to open the YouTube app when you open a YouTube link in safari. I already had a Siri shortcut to do this, but I prefer this because it will automatically prompt you instead of having to dig through the share menu.
> 
> Safari extension to run user script (free): https://apps.apple.com/us/app/userscripts/id1463298887 Userscript code: https://gist.github.com/asportnoy/628b820184297f5fe296c1a5b79c8000
> 
> ### How to install
> 1. Install [the app](https://apps.apple.com/us/app/userscripts/id1463298887)
> 2. Launch the app and choose path for scripts
> 3. Go to [this page](https://gist.githubusercontent.com/asportnoy/628b820184297f5fe296c1a5b79c8000/raw/open-youtube-app.user.js)
> 4. Open the extension and press install in the banner

Hey bro, how can I do a userscript to open Rocket Instagram and Tiktok automatically as you do? Can u help me?

**Comment by ryuya0124** [comment]
Some YouTube channel pages (youtube://www.youtube.com/@....) Fixed because it does not work correctly on

https://gist.github.com/ryuya0124/2ba4f56cf9e9dab781d3146c74a3f36b

**Comment by asportnoy** [comment]
> Some YouTube channel pages (youtube://www.youtube.com/@....) Fixed because it does not work correctly on
> 
> https://gist.github.com/ryuya0124/2ba4f56cf9e9dab781d3146c74a3f36b

I can't reproduce that issue, it works on my version too.

**Comment by ryuya0124** [comment]
I wrote a script for BHTwitter.
It analyzes the URL scheme and opens more pages.
The list redirects to the timeline because the URL scheme is unknown.
Pages that could not be handled are also redirected to the timeline to avoid errors.

https://gist.github.com/ryuya0124/e6e59ceba8f03bf40f3b5accedc52e44

**Comment by ryuya0124** [comment]
> > Some YouTube channel pages (youtube://www.youtube.com/@....) Fixed because it does not work correctly on
> > https://gist.github.com/ryuya0124/2ba4f56cf9e9dab781d3146c74a3f36b
> 
> I can't reproduce that issue, it works on my version too.

In older versions, for example, if you opened this link, the YouTube app could not process it and redirected you to the browser.

https://youtube.com/@wdsgame_official?si=m7_Yk-Vj02go6ozm
