### ISSUE TITLE
[Bug] history not updating and shorts repeating (likely tied)

### ISSUE THREAD

**Issue by 306bobby** [qnblackcat/uYouPlus#690]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: ios 15.1.1
- Device model: 12 mini
- Sideload tool (TrollStore,...)
- The specific version of uYouPlus: 17.431 on trollstore, 2.1 on app

### Describe the bug
History does not update on YouTube account. Youtube watched videos aren't showing up in history. Shorts are also repeating, which is probably related

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_
Unsure 
### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_
No crash
### Are you using the newest version of uYouPlus? If not, why?

As far as I know yes
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
No
### Additional context: 
Have none sorry

**Comment by 306bobby** [comment]
I actually believe it happened after casting to the youtube app on a Google TV.

**Comment by qnblackcat** [comment]
Did you mess up with your DNS? 
https://github.com/qnblackcat/uYouPlus/issues/476, https://github.com/qnblackcat/uYouPlus/issues/378, https://github.com/qnblackcat/uYouPlus/issues/127, https://github.com/qnblackcat/uYouPlus/issues/117

**Comment by 306bobby** [comment]
I have a pihole but the rules are the same for all devices and uyou+ works fine on my girlfriends phone
