### ISSUE TITLE
[Questions] Support downloading the whole playlist with multiple videos downloading at a time.

### ISSUE THREAD

**Issue by olivertzeng** [qnblackcat/uYouPlus#691]
Using latest uYou plus
when clicking on the uYou plus button on the whole playlist, it told me that nothing is in the playlist
my playlist be like:
https://www.youtube.com/playlist?list=PLNv1Xy2Vg8K0WyTd7ljnlhBxeAIEet6ke

**Comment by qnblackcat** [comment]
Dupicate of https://github.com/qnblackcat/uYouPlus/issues/608
