### ISSUE TITLE
[Bug] uYou brightness gesture control not working

### ISSUE THREAD

**Issue by nintyz** [qnblackcat/uYouPlus#696]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.1.1
- Device model: 14 Pro
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of uYouPlus: v17.43.1-2.1

### Describe the bug
uYou brightness gesture control does not work.

### How to reproduce the bug
set a gesture control for brightness under uYou settings "Gestures Controls Settings".

### Does the issue happen with the official YouTube from AppStore?
Does not apply

![image0](https://user-images.githubusercontent.com/45317597/202844849-e5d2c1a8-a9f5-4832-af70-20c977c8f778.png)

**Comment by nintyz** [comment]
Realised its a duplicate issue.

**Comment by MarioMastr** [comment]
> Realised its a duplicate issue.

Yes. Look at #506 for any updates.
