### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PizzaPizzaNow** [qnblackcat/uYouPlus#70]
**Device info:**
- iOS/iPadOS version: 14.6
- Device model: Iphone 12
- Sideload tool:AltStore
- Version of uYouPlus: v2.1

**Describe the bug:**
- I noticed that the video lengths are not showing in playlists. I’m not sure if this is on purpose and I am overlooking a setting.

**How to reproduce the bug:**
_(Please attach videos or screenshots if possible)_
When entering a playlist, the thumbnail does not have the small black square with the length of the video.

**Crash log (if possible):**
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Additional context:**
_(Add any other context about the problem here)_
Super small thing, sorry if this is the wrong place

**Comment by qnblackcat** [comment]
Please read the description in the Release page

![51FE7A93-76B8-4284-8A6A-E0E019271DAD](https://user-images.githubusercontent.com/52943116/155690583-26042d38-2a85-4173-92e4-fefdd9ed4383.png)
