### ISSUE TITLE
Feature request: YouTube wide mute button

### ISSUE THREAD

**Issue by MarioMastr** [qnblackcat/uYouPlus#700]
Like on desktop.

**Comment by qnblackcat** [comment]
No, sorry

**Comment by MarioMastr** [comment]
WAIT THE MUTE BUTTON ACTUALLY GOR ADDED IN THE MOST RECENT YOUTUBE UPDATE WHAT

**Comment by arichorn** [comment]
Wait, actually?

**Comment by MarioMastr** [comment]
> Wait, actually?

Nope turns out I'm an idiot and it was another tweak that you added in

**Comment by arichorn** [comment]
Oh 😅
you were talking about my forked version of uYouPlus, yeah my version has the mute button toggle.
