### ISSUE TITLE
How to return back to red progress bar?

### ISSUE THREAD

**Issue by dpyy** [qnblackcat/uYouPlus#703]
In the latest version it seems the bar changed from red to white. How to change it back?

**Comment by yodaluca23** [comment]
> In the latest version it seems the bar changed from red to white. How to change it back?

**Comment by yodaluca23** [comment]
https://github.com/PoomSmart/YTABConfig/discussions/31#discussioncomment-4151887

**Comment by arichorn** [comment]
> In the latest version it seems the bar changed from red to white. How to change it back?

YouTube enabled the `iosColorizedProgressBar` Flag by default, you can easily turn it off in “A/B” on uYou+!

**Comment by qnblackcat** [comment]
Your question has been answered above
