### ISSUE TITLE
[Questions] New Release after almost a month?

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#705]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###
Can you do a new release? The last one was 20d ago. Thanks!

**Comment by qnblackcat** [comment]
I don’t think so because some people may not be aware of the login issue and delete the current version, therefore can not sign in again

**Comment by Jul9389** [comment]
hello I have a problem with uYouPlus when I launch the application it closes directly
