### ISSUE TITLE
Dislikes are displayed in k, for example "54k" instead of 54.324

### ISSUE THREAD

**Issue by craftgeil** [qnblackcat/uYouPlus#710]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️
yes

Make sure you complete the template. Otherwise, it will be closed without further explanation!

### Device info
- iOS/iPadOS version: 16.1.1
- Device model: iPhone SE 2020
- Sideload tool: AltStore
- The specific version of uYouPlus: v17.43.1-2.1 

### Describe the bug
Dislikes are displayed in k, for example "54k" instead of 54.324
I found no setting to configure Return YouTube Dislikes, however the browser extension has a feature to switch the number format to for example 54.324.

### How to reproduce the bug
click on a video/short

### Crash log (if possible)
x

### Are you using the newest version of uYouPlus? If not, why?
x

### Does the issue happen with the official YouTube from AppStore?
no they removed dislikes .-.

### Additional context: 
![IMG_3929](https://user-images.githubusercontent.com/80261988/204156942-9939bf92-58f3-4817-ab22-c5db4caab972.jpg)
![IMG_3925](https://user-images.githubusercontent.com/80261988/204156944-9f4e8dfb-1688-45b4-b34e-774572e3197b.PNG)

**Comment by qnblackcat** [comment]
This should be requested on RYD‘s repo: https://github.com/PoomSmart/Return-YouTube-Dislikes
