### ISSUE TITLE
Back and forth keys showing when watching a video from a playlist

### ISSUE THREAD

**Issue by craftgeil** [qnblackcat/uYouPlus#711]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️
yes

Make sure you complete the template. Otherwise, it will be closed without further explanation!

### Device info
- iOS/iPadOS version: 16.1.1
- Device model: iPhone SE 2020
- Sideload tool: AltStore
- The specific version of uYouPlus: v17.43.1-2.1 

### Describe the bug
Back and forth keys showing when watching a video from a playlist

### How to reproduce the bug
click on a video in a playlist with the option to hide the back and forth buttons enabled

### Crash log (if possible)
x

### Are you using the newest version of uYouPlus? If not, why?
x

### Does the issue happen with the official YouTube from AppStore?
no you can not remove the back and forth keys in the offical YouTube app.

### Additional context: 
![IMG_3928](https://user-images.githubusercontent.com/80261988/204157311-72886fc2-93a8-4d44-b4b1-b6ee15c1bf57.PNG)
![IMG_3927](https://user-images.githubusercontent.com/80261988/204157312-59e21073-d1b7-4eea-b15c-ae2f06f2ec8c.jpg)

**Comment by qnblackcat** [comment]
This is expected behavior and I _won’t_ fix it.
