### ISSUE TITLE
[suggestion] add the highlight option from the sponsor block extension

### ISSUE THREAD

**Issue by craftgeil** [qnblackcat/uYouPlus#712]
wiki link:
https://wiki.sponsor.ajay.app/w/Highlight

![Screenshot 2022-11-27 211355](https://user-images.githubusercontent.com/80261988/204157542-9414bad4-7ec1-487f-9543-ac21864ea1e5.png)

**Comment by yodaluca23** [comment]
https://github.com/Galactic-Dev/iSponsorBlock/issues/49

**Comment by qnblackcat** [comment]
Answered above
