### ISSUE TITLE
[suggestion] option to remove the upper bar with the trends, all, gaming etc

### ISSUE THREAD

**Issue by craftgeil** [qnblackcat/uYouPlus#713]
![IMG_3926](https://user-images.githubusercontent.com/80261988/204157750-99af97fb-e7b8-4c53-9802-98088533a731.jpg)

**Comment by arichorn** [comment]
Actually this is pretty good, I didn’t care much about it but the idea of turning it off is.. okay?

**Comment by GeoSn0w** [comment]
That would actually be useful.

**Comment by Hex34568** [comment]
> That would actually be useful.

Agrred

**Comment by qnblackcat** [comment]
Please update to [v17.49.6-2.3~1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.49.6-2.3(1))
