### ISSUE TITLE
[Questions] is it possible to move the uYou tab left to the Libary?

### ISSUE THREAD

**Issue by craftgeil** [qnblackcat/uYouPlus#714]
is it possible to move the uYou tab left to the Libary?
Always clicking uYou, when i just want to go to the Libary .-.
![IMG_3930](https://user-images.githubusercontent.com/80261988/204157954-c453babb-a845-49d5-ab6e-1cf3376ade2a.png)

![edited](https://user-images.githubusercontent.com/80261988/204157957-3e762744-d746-47be-8839-066622e2a7f0.png)

**Comment by arichorn** [comment]
Well yeah!
I have mine on the left

go to the uYou Tab >> Red/Pinkish Settings Icon >> ReorderTabs and then move “uYou” above library

**Comment by qnblackcat** [comment]
Answered above
