### ISSUE TITLE
[Bug] Double Rotation

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#716]
### Device info
- iOS/iPadOS version: 16.2
- Device model: 14 Pro
- Sideload tool: Sideloadly
- The specific version of uYouPlus: v17.43.1-2.1

### Describe the bug:

The video rotates twice (watch full attached video!)

https://user-images.githubusercontent.com/40891294/204389160-0e5643fd-ae6a-4e98-82b2-9cb77f05e7ea.MOV

**Comment by Ketarmin** [comment]
Happens in Cercube+ too, can confirm that really annoying

**Comment by qnblackcat** [comment]
Please complete the issue template
