### ISSUE TITLE
[Bug] Video size

### ISSUE THREAD

**Issue by ErSpieltHD** [qnblackcat/uYouPlus#717]
### Device info
- iOS/iPadOS version: 16.2
- Device model: 14 Pro
- Sideload tool: Sideloadly
- The specific version of uYouPlus: v17.43.1-2.1

### Describe the bug:

Sometimes the video is scaled to small and out of screen. When rotating it gets worse.

I don't have a screenshot cause I forgot 💀

Will attach one asap if it happens again.

**Comment by yodaluca23** [comment]
> It's always tiny and in the top left

Yes, I've had this happen to me a multiple occasions as well. Usually, I just flip it around a few times, and it fixes itself...

**Comment by qnblackcat** [comment]
Please compelete the issue template
