### ISSUE TITLE
[Questions] Taking long time to install

### ISSUE THREAD

**Issue by zoplo** [qnblackcat/uYouPlus#72]
### Have you read the FAQ? Make sure you visit the FAQ page before asking any question!!!
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

I'm trying to install uYou+ through AltStore and it is taking a long time. Is there a way around this?

**Comment by qnblackcat** [comment]
Depending on your internet speed, the installation process might take a while. I suggest you download & save the IPA to the Files app, then open the saved IPA in AltStore

**Comment by qnblackcat** [comment]
Did it work?

**Comment by 9odqe** [comment]
The same here, I tried the .ipa file and it didn’t work.

**Comment by qnblackcat** [comment]
> It didn't work

Saying it doesn't help. What exactly **didn't work**? @9odqe

**Comment by 9odqe** [comment]
Sorry about that.
I mean it take long time to install the even with ipa file using altstore.

**Comment by 9odqe** [comment]
> > It didn't work
> 
> Saying it doesn't help. What exactly **didn't work**? @9odqe

Sorry about that.
I mean installing the app via altstore takes very long time even with ipa file.

**Comment by qnblackcat** [comment]
I don’t think this is an issue of uYou+. You can try Sideloadly instead of AltStore @9odqe

**Comment by 9odqe** [comment]
@qnblackcat thank you, installed via sideloadly.

**Comment by qnblackcat** [comment]
This problem is probably because of AltStore. Try Sideloadly instead of AltStore.
