### ISSUE TITLE
[Enhancement] Add some newer tweaks

### ISSUE THREAD

**Issue by yodaluca23** [qnblackcat/uYouPlus#722]
Could [YouMute](https://github.com/PoomSmart/YouMute) and [YTSilentVote](https://github.com/PoomSmart/YTSilentVote) be added to uYou+?

I think they would be great additions!

**Comment by arichorn** [comment]
YouMute is pretty good, but the problem is that people may hate it since you can’t hide the button. I don’t hate YouMute I was saying anyone else’s opinion about it. And YTSilentVote.. never heard of this one.

**Comment by qnblackcat** [comment]
Currently I have no plans to add YouMute to uYouPlus. However, you could add YouMute to uYou+ yourself: tweak injection or just add YouMute's soucre code to uYou+.

Enabling **Hide HUD Messages** will achieve the same result as what YTSilentVote does.

**Comment by yodaluca23** [comment]
> Enabling **Hide HUD Messages** will achieve the same result as what YTSilentVote does.

I have that enabled, but the giant thumbs up still shows...

**Comment by arichorn** [comment]
My tweak did disable the like animation but it’s not likely to now.

**Comment by arichorn** [comment]
> Could [YouMute](https://github.com/PoomSmart/YouMute) and [YTSilentVote](https://github.com/PoomSmart/YTSilentVote) be added to uYou+?
> 
> I think they would be great additions!

I tried adding YouMute and it is not buildable, I’m gonna guess that’s another reason why it isn’t added.
![0A271C79-AAE9-44F9-A851-179AFECD4716](https://user-images.githubusercontent.com/78001398/205168021-ffc73015-7e05-4e86-829b-9052980f49ee.jpeg)
