### ISSUE TITLE
[Bug]{CertubePlus} (Search results page has a blank gap)

### ISSUE THREAD

**Issue by gototheskinny** [qnblackcat/uYouPlus#727]
Seach results section of the app has an annoying and pointless gap instead of showing the searched words it's just showing mostly one word like this: ![Example](https://user-images.githubusercontent.com/51786709/205012054-7f3ec2cb-4231-410a-bc6c-7709343fe521.png)
 official latest version doesn't have this issue:![example official v.](https://user-images.githubusercontent.com/51786709/205012756-f0d7be8a-0b03-473c-8f51-44d19291a3be.png)
### Device info
- iOS/iPadOS version: 15.0
- Device model: ip 12
- Sideload tool: TrollStore
- The specific version of uYouPlus: v17.43.1

### Describe the bug
I already did

### How to reproduce the bug
Search something that has 3 words or more 

###

### Are you using the newest version of uYouPlus? If not, why?
I use CertubePlus not this tweak that repo doesn't have an issue part unfortunately

### Does the issue happen with the official YouTube from AppStore?
NO

### Additional context:

**Comment by arichorn** [comment]
https://github.com/arichorn/CercubePlusExtra/releases/tag/v17.46.4-5.3.12-(36) Try this
It uses a newer version of YouTube
and a new Cercube version
If this doesn’t resolve it I’ll grab A/B Flags then.

**Comment by gototheskinny** [comment]
> https://github.com/arichorn/CercubePlusExtra/releases/tag/v17.46.4-5.3.12-(36) Try this
> 
> It uses a newer version of YouTube
> 
> and a new Cercube version
> 
> If this doesn’t resolve it I’ll grab A/B Flags then.

Unfortunately it doesn't solve this issue. This part should be empty and only the search results (imo) at least there should be an option to get rid of that part. ![Example](https://user-images.githubusercontent.com/51786709/205173480-e57c07c9-c967-4fff-b6ea-357ad2e49251.jpeg)

**Comment by arichorn** [comment]
So it’s a Cercube issues.
Unfortunately I may not be able to resolve this then. try asking level3tjg or qnblackcat.
I don’t use Cercube that much so I have no idea on what to do with this problem.

**Comment by gototheskinny** [comment]
> So it’s a Cercube issues.
> 
> Unfortunately I may not be able to resolve this then. try asking level3tjg or qnblackcat.
> 
> I don’t use Cercube that much so I have no idea on what to do with this problem.

Thank you anyways. Certube doesn't have ANY ads(search results included) that's why I use it instead of Uyou.

**Comment by MarioMastr** [comment]
> > So it’s a Cercube issues.
> > 
> > Unfortunately I may not be able to resolve this then. try asking level3tjg or qnblackcat.
> > 
> > I don’t use Cercube that much so I have no idea on what to do with this problem.
> 
> Thank you anyways. Certube doesn't have ANY ads(search results included) that's why I use it instead of Uyou. 

I don't understand how people get ads in their search results. I get none.

**Comment by MarioMastr** [comment]
> > > > So it’s a Cercube issues.
> > > > 
> > > > Unfortunately I may not be able to resolve this then. try asking level3tjg or qnblackcat.
> > > > 
> > > > I don’t use Cercube that much so I have no idea on what to do with this problem.
> > > 
> > > Thank you anyways. Certube doesn't have ANY ads(search results included) that's why I use it instead of Uyou. 
> > 
> > I don't understand how people get ads in their search results. I get none. 
> 
> That's why I switched to certube but I'll try uyou+ again. Uyou is not updated for a while so I guess that's why I got those ads.

I think it might be because I use an AdGuard settings profile to essentially block all ad traffic coming to my phone.

**Comment by qnblackcat** [comment]
Closed because CercubePlus does not exist anymore

**Comment by arichorn** [comment]
Hmm. So what’s there a reason for this particular change?

I’ll guess it’s because you’re were unable to support 2 repositories of uYou+ & Cercube+
It’s fine if this was the reason since I still have the repository I guess.

**Comment by gototheskinny** [comment]
> Hmm. So what’s there a reason for this particular change?
> 
> 
> 
> I’ll guess it’s because you’re were unable to support 2 repositories of uYou+ & Cercube+
> 
> It’s fine if this was the reason since I still have the repository I guess.
> 
> 

He said it wasn't his decision on reddit. I guess the original dev of the certube is "asked" him to remove it. Or maybe even Google did because it can download vids so much faster than uyou.

**Comment by arichorn** [comment]
> > Hmm. So what’s there a reason for this particular change?
> > I’ll guess it’s because you’re were unable to support 2 repositories of uYou+ & Cercube+
> > It’s fine if this was the reason since I still have the repository I guess.
> 
> He said it wasn't his decision on reddit. I guess the original dev of the certube is "asked" him to remove it. Or maybe even Google did because it can download vids so much faster than uyou.

Ah that makes so much sense thanks.
