### ISSUE TITLE
sugestion

### ISSUE THREAD

**Issue by Epic0001** [qnblackcat/uYouPlus#729]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ
Sugestion add dltube u you download speed sucks and dltube is really fast
![8EACECFA-2A72-49CC-B7E2-A07AACA73AB5](https://user-images.githubusercontent.com/110989057/205115043-973a56af-ec87-4f97-ba83-43c5486b1b34.png)
![5D862125-FA3B-45D1-9B05-0FE11FCE0ACD](https://user-images.githubusercontent.com/110989057/205115057-9b451cf0-9357-4840-a1b7-030588423f67.png)

###

**Comment by qnblackcat** [comment]
No, sorry
