### ISSUE TITLE
[Bug] Can't download from altstore

### ISSUE THREAD

**Issue by NaufalF22** [qnblackcat/uYouPlus#73]
**Device info:**
- iOS/iPadOS version: 15.4 beta
- Device model: iPhone se 2016
- Sideload tool (Ex: AltStore, Sideloadly...) Altstore 1.4.8
- Version of uYouPlus: latest at github

**Describe the bug:**
- I can't download via altstore 

**How to reproduce the bug:**
When I click open with altstore it at this page It's loading but after asking the extension for yt and accept all extensions it just error like this 
![IMG_20220228_065006_054.jpg](https://user-images.githubusercontent.com/63091744/155905294-256c0662-55bc-4425-a6b1-4fe3221b98d0.jpg)

**Crash log (if possible):**
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Additional context:**
_(Add any other context about the problem here)_

**Comment by qnblackcat** [comment]
You must connect your phone with your PC running AltServer via cable
