### ISSUE TITLE
[Bug] (App crashes on startup when installed using BullfrogAssistant 1.2.2 )

### ISSUE THREAD

**Issue by Harumatsu91202024** [qnblackcat/uYouPlus#730]
### Device info
- iOS/iPadOS version: iOS 16.2 Beta 4
- Device model: iPhone 13 Pro Max
- Sideload tool BullfrogAssistant 1.2.2 (latest update)
- The specific version of uYouPlus:17.42.7

### Describe the bug
App crashes on startup when installed using BullfrogAssistant 1.2.2. I am pretty sure this is caused by Bullfrog’s latest update but since there’s no way to contact them, I’d be happy if this can be fixed from uYouplus side.

### How to reproduce the bug
sign and install uYouplus using bullfrog assistant.
Try opening the app and it keeps crashing.

https://imgur.com/a/wrw410x

### Crash log (if possible)
_(The crash log can be found in your device's Settings App > Privacy > Analytics & Improvements > Analytics Data > Youtube-xxx-xxx.ips)_

### Are you using the newest version of uYouPlus? If not, why?
Yes.

### Does the issue happen with the official YouTube from AppStore?
Couldn’t find unmodified YouTube ipa file but works fine with other apps (BHTwitter etc)

**Comment by Jul9389** [comment]
> i have the same problem i think it's from bullfrog and where did you find the ipa file for twitter ?

**Comment by Harumatsu91202024** [comment]
> i have the same problem i think it's from bullfrog and where did you find the ipa file for twitter ?

https://github.com/BandarHL/BHTwitter/releases

:)

**Comment by Jul9389** [comment]
> > i have the same problem i think it's from bullfrog and where did you find the ipa file for twitter ?
> 
> 
> 
> https://github.com/BandarHL/BHTwitter/releases
> 
> 
> 
> :)

> Thank's :)

**Comment by qnblackcat** [comment]
I can’t fix this. Sorry
