### ISSUE TITLE
Updated Workaround (20 Nov) for the “Google couldn't confirm this attempt to sign in is safe. If you think this is a mistake, you can close and try again to sign in” warning

### ISSUE THREAD

**Issue by Dream3Re** [qnblackcat/uYouPlus#732]
Hello when i press next after i add my email adress in the uyou i got "Google couldn't confirm this attempt to sign in is safe"
and when i try the uyouv2 i go that 
![vSaB1MDO](https://user-images.githubusercontent.com/119812810/205510848-c4f680c3-37de-4dd3-b1c2-6949cf19c7db.jpg)

**Comment by bangmaple** [comment]
have you resolved it?
