### ISSUE TITLE
[Bug] Blank comments section when OLED Dark mode is on (bug present on specific videos)

### ISSUE THREAD

**Issue by Cactus98** [qnblackcat/uYouPlus#733]
### Device info
- iOS/iPadOS version: iOS 15.7.1
- Device model: iPhone 13
- Sideload tool: AltStore
- The specific version of uYouPlus: 17.43.1

### Describe the bug
If you have OLED Dark Mode on and try to view a comments section where the the uploader has enabled 'reactions' (see below), the comments section is blank. This effect is not present on videos where the 'reactions' feature is not enabled.

### How to reproduce the bug
1. Turn on OLED Dark Mode.
2. Visit a video where reactions are enabled. (ex: https://youtu.be/RepW3taVceQ)
3. Open the comments.

OLED Dark Mode on:
https://user-images.githubusercontent.com/88598340/205539923-5880786e-3680-4c30-be8c-13133504266a.MOV

OLED Dark Mode off:
https://user-images.githubusercontent.com/88598340/205539987-231368fc-4cb4-4de7-958f-0d3331158e09.MOV

### Crash log (if possible)
Analytics are disabled on my device.

### Are you using the newest version of uYouPlus? If not, why?
I believe I am using the latest version. (As of 12/4/2022, yes.)

### Does the issue happen with the official YouTube from AppStore?
The official YouTube app does not have the OLED Dark Mode feature.

**Comment by qnblackcat** [comment]
Thanks. It will be fixed in the next release
