### ISSUE TITLE
[Bug] Video Quality selects 480p instead of 1080p50

### ISSUE THREAD

**Issue by NiceSk1ll3r** [qnblackcat/uYouPlus#74]
**Device info:**
- iOS/iPadOS version:  15.3
- Device model: iPad Air 2
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore
- Version of uYouPlus: Latest (17.06.3-2.1)

**Describe the bug:**
-  I have selected quality 1080p 60 fps, but when video is 1080p 50fps, it auto selects 480p and I have to manually select 1080p 50. 
Is it iPad specific problem? I don't have another iOS device to test unfortunately.

**How to reproduce the bug:**
_(Please attach videos or screenshots if possible)_
Have to find 1080p50 video.

**Crash log (if possible):**
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
It isn't crashing.

**Additional context:**
_(Add any other context about the problem here)_
Would be nice if I have 1080p60 it would select closest thing to it -> 1080p50 then.

**Comment by qnblackcat** [comment]
See https://github.com/MiRO92/uYou-for-YouTube/issues/56 and https://github.com/MiRO92/uYou-for-YouTube/issues/85

**Comment by NiceSk1ll3r** [comment]
> See [MiRO92#56](https://github.com/MiRO92/uYou-for-YouTube/issues/56) and [MiRO92#85](https://github.com/MiRO92/uYou-for-YouTube/issues/85)
Okay, thanks.

**Comment by oomek** [comment]
This has never been fixed. Linked issues are still unanswered and lead nowhere. Miro seems not interested in fixing that bug. Would you be able to fix it yourself by any chance?
