### ISSUE TITLE
[Questions]The video quality is up to 1080p.I can't watch 4k video.Does anyone know how to use it?

### ISSUE THREAD

**Issue by zcqxfjvcb** [qnblackcat/uYouPlus#741]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###The video quality is up to 1080p.I can't watch 4k video.Does anyone know how to use it?

**Comment by yodaluca23** [comment]
Read [here](https://github.com/PoomSmart/YTUHD) and [here](https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-why-cant-i-see-2k4k-quality). Please in the future read the [FAQ's](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) before making an issue...
