### ISSUE TITLE
[Questions] Old Layout

### ISSUE THREAD

**Issue by KingGamingYT** [qnblackcat/uYouPlus#746]
After reading over the FAQ and various links on it, I've seen how a lot of uYou's bugs have been fixed and improvements have been made in later v17.xx instances of the app. However, I'm not a huge fan of the new YouTube appearance and layout, so I've stayed back on v17.0.6.3_2.1 of the app for quite some time now as it doesn't get the new layout update. I was wondering if there was a way that I could receive uYou's improvements without having to update my youtube client, possibly through manually building. Thanks.

**Comment by qnblackcat** [comment]
I can't. This is server-side rendering

**Comment by yodaluca23** [comment]
You may be able to you [YTABConfig](https://github.com/PoomSmart/YTABConfig) and find the correct AB flags to toggle... Don't ask me though, [@arichorn](https://github.com/arichorn) is usually good at these...

**Comment by KingGamingYT** [comment]
> You may be able to use [YTABConfig](https://github.com/PoomSmart/YTABConfig) (Included in the latest uYou+ Version) and find the correct AB flags to toggle... Don't ask me though, [@arichorn](https://github.com/arichorn) is usually good at these...

I'll look into it, since youtube doesn't keep flags around forever (though usually they're too lazy to remove most of them for a good long while) it's more of a temporary solution, but since [aubymori](https://github.com/aubymori)'s excellent YouTube Patch Collection can revert most of the changes on desktop it wouldn't be a stretch to think it could be done on mobile as well.

**Comment by arichorn** [comment]
> You may be able to use [YTABConfig](https://github.com/PoomSmart/YTABConfig) (Included in the latest uYou+ Version) and find the correct AB flags to toggle... Don't ask me though, [@arichorn](https://github.com/arichorn) is usually good at these...

I’m not really good at them. Level3tjg is the one who thought me how to use A/B Flags.

**Comment by arichorn** [comment]
Here I’ll publicly give out this. I made it just for y’all! Implement this in your forked uYou+ here’s what this will do (hopefully)
Channel Menu (Uses old 16.42.3 Style), No Ambient Mode, No Modernized Buttons & No Rounded Thumbnails
also watch out this will break the options in uYouPlus >> Themes >> Default Dark Mode Setting
```
// YTNoModernUI - arichorn
%hook YTColdConfig
// Disable Modern Content - YTNoModernUI
- (BOOL)creatorClientConfigEnableStudioModernizedMdeThumbnailPickerForClient { return NO; }
- (BOOL)cxClientEnableModernizedActionSheet { return NO; }
- (BOOL)enableClientShortsSheetsModernization { return NO; }
- (BOOL)enableTimestampModernizationForNative { return NO; }
- (BOOL)uiSystemsClientGlobalConfigEnableRoundedThumbnailsForNative { return NO; }
- (BOOL)uiSystemsClientGlobalConfigEnableRoundedThumbnailsForNativeLongTail { return NO; }
- (BOOL)uiSystemsClientGlobalConfigEnableRoundedTimestampForNative { return NO; }
- (BOOL)uiSystemsClientGlobalConfigEnableRoundedDialogForNative { return NO; }
- (BOOL)uiSystemsClientGlobalConfigEnableModernButtonsForNative { return NO; }
- (BOOL)uiSystemsClientGlobalConfigEnableModernButtonsForNativeLongTail { return NO; }
- (BOOL)uiSystemsClientGlobalConfigEnableModernTabsForNative { return NO; }
- (BOOL)uiSystemsClientGlobalConfigIosEnableSnackbarModernization { return NO; }
- (BOOL)mainAppCoreClientIosEnableModernOssPage { return NO; }
// Disable Darker Dark Mode - YTNoModernUI
- (BOOL)enableDarkerDarkMode { return NO; }
- (BOOL)modernizeElementsTextColor { return NO; }
- (BOOL)modernizeElementsBgColor { return NO; }
- (BOOL)modernizeCollectionLockups { return NO; }
- (BOOL)uiSystemsClientGlobalConfigUseDarkerPaletteTextColorForNative { return NO; }
// 16.42.3 Styled YouTube Channel Page Interface - YTNoModernUI
- (BOOL)channelsClientConfigIosChannelNavRestructuring { return NO; }
%end
```

**Comment by KingGamingYT** [comment]
I'll give this a shot! Thanks a ton!

**Comment by arichorn** [comment]
No Problem!

**Comment by KingGamingYT** [comment]
> No Problem!

@arichorn Sorry for my lack of knowledge here, but would this go into the Header.h file, or as a separate file that you tie into the project/Header.h file?

**Comment by arichorn** [comment]
It goes in the uYouPlus.xm file
