### ISSUE TITLE
[Bug] Youtube Crashing upon receiving URL with File Sharing enabled

### ISSUE THREAD

**Issue by lupus0802** [qnblackcat/uYouPlus#748]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) page first!!! ⚠️ 

I did - couldn't find this issue.

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16.0.2
- Device model: iPhone 8
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) Sideloadly
- Version 17.43.1-2.1

### Describe the bug

I could tell a whole story about how I searched for a fix for this for two days, but I think I found the issue.
I recently switched from Altstore to Sideloadly because Sideloadly allows you to have File Sharing enabled instead of going through the hassle with iMazing to get the downloaded videos. 

Anyhow, I discovered that when I enable FIle Sharing with Sideloadly, the Open in Youtube Siri Shortcut (located [here](https://shortcutsgallery.com/shortcuts/open-in-youtube/)) and the share sheet extension won't work anymore. Generally when opening anything in Youtube (e. g. the callback for the youtube sign in needed to bypass google), the app will crash. It isn't that bug of a deal with the callback because Sideloadly provides a spoofer that makes the app think it's real, so the issue really is the Siri shortcut.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

1. Sideload any version of uYouPlus (I tried 43, 42 and 39) with Sideloadly with File Sharing enabled
2. Try using the [Siri Shortcut](https://shortcutsgallery.com/shortcuts/open-in-youtube/) or Open in Youtube Extension, if you have App Extensions enabled

### Crash log (if possible)

**Siri Shortcut**: See [here](https://drive.google.com/file/d/1XECt-53LGA4s4yNWg5kz2orqMNu6IErU/view?usp=sharing)
**Open in Youtube Extension:** See [here](https://drive.google.com/file/d/1AktXIHT2WjfbkKlucHZwUJqV2LdMYsED/view?usp=sharing)

### Are you using the newest version of uYouPlus? If not, why?

I am using the newest version - tried it with different versions too.

### Does the issue happen with the official YouTube from AppStore?

I can't verify that because Youtube official is using deep-link and has file sharing disabled.

### Additional context: 

I don't know if this is something you can fix, just wanted to let you know about it.
If this is something out of your control, please let me know and sorry for bothering you!

**Comment by PoomSmart** [comment]
Both crash logs lead to a runtime exception that the logs themselves are not really enough. You will want to connect your device with a Mac laptop and use its Console app to observe the error messages coming from YouTube process.

**Comment by lupus0802** [comment]
Alright, I'll try that, give me a moment.

**Comment by lupus0802** [comment]
Sorry, would you be able to link me to a resource or explain to me access the device's logs/console in order to see the error messages. I am not familiar with that and Google didn't seem to get what I'm saying.

**Comment by lupus0802** [comment]
Update: I got this to work and I'll share the logs with information tomorrow (probably a few hours or so). I tried to hide processes that I deemed unnecessary (such as wifid, Widgets etc.) before copying the whole thing, but the whole error/fault log is still 347 lines and the whole notifications log is 23000 (oh boy) - I also tried to pinpoint a specific fault that I think is related to the issue.

**Comment by PoomSmart** [comment]
You can filter the log with "YouTube" string...

**Comment by lupus0802** [comment]
That is true, but I think that other errors may also be relevant (such as from ShortcutsUI) - however.

All errors coming from Youtube are:
*Note that the first one is when I open Youtube with the Shortcut, the second one with the official extension*

`error	09:46:22.060034+0100	YouTube	nw_connection_copy_connected_local_endpoint_block_invoke [C3] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
error	09:46:22.060084+0100	YouTube	nw_connection_copy_connected_remote_endpoint_block_invoke [C3] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
error	09:46:22.060132+0100	YouTube	nw_connection_copy_protocol_metadata_internal_block_invoke [C3] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
error	09:46:22.114765+0100	YouTube	nw_connection_copy_connected_local_endpoint_block_invoke [C4] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
error	09:46:22.114825+0100	YouTube	nw_connection_copy_connected_remote_endpoint_block_invoke [C4] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
error	09:46:22.114897+0100	YouTube	nw_connection_copy_protocol_metadata_internal_block_invoke [C4] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
error	09:46:22.499454+0100	YouTube	Trying to set delaysTouchesBegan to NO on a system gate gesture recognizer - this is unsupported and will have undesired side effects`


`fault	09:50:50.042799+0100	Youtube	*** -[NSXPCDecoder validateAllowedClass:forKey:]: NSSecureCoding allowed classes list contains [NSObject class], which bypasses security by allowing any Objective-C class to be implicitly decoded. Consider reducing the scope of allowed classes during decoding by listing only the classes you expect to decode, or a more specific base class than NSObject. This will become an error in the future. Allowed class list: {(
    "'NSObject' (0x20cdf5c98) [/usr/lib]"
)}
NSXPCInterface: <NSXPCInterface: 0x281271200>
Protocol: EXExtensionContextHosting
SEL: _completeRequestReturningItems:forExtensionContextWithUUID:completion: (3 arguments, 0 proxies)
 Classes: [{NSError, NSArray, NSURL, NSData, NSUUID, NSExtensionItem, NSString, _EXItemProviderSandboxedResource, NSDictionary, NSDate, CKShare, NSItemProvider, _EXItemProviderExtensionVendorLoadOperator, UIImage, NSNull, NSNumber, _EXItemProviderCopyingLoadOperator, NSValue}, NSUUID, {}]
 Reply block: (arg #4, (0 arguments, 0 proxies), signature 'v@?') []
SEL: _loadPreviewImageForPayload:contextIdentifier:completionHandler: (3 arguments, 0 proxies)
 Classes: [{NSError, NSArray, NSURL, NSData, NSUUID, NSExtensionItem, NSString, _EXItemProviderSandboxedResource, NSDictionary, NSDate, CKShare, NSItemProvider, _EXItemProviderExtensionVendorLoadOperator, UIImage, NSNull, NSNumber, _EXItemProviderCopyingLoadOperator, NSValue}, NSUUID, {}]
 Reply block: (arg #4, (2 arguments, 0 proxies), signature 'v@?@@"NSError"') [{NSObject}, {NSError}]
SEL: _loadItemForPayload:contextIdentifier:completionHandler: (3 arguments, 0 proxies)
 Classes: [{NSError, NSArray, NSURL, NSData, NSUUID, NSExtensionItem, NSString, _EXItemProviderSandboxedResource, NSDictionary, NSDate, CKShare, NSItemProvider, _EXItemProviderExtensionVendorLoadOperator, UIImage, NSNull, NSNumber, _EXItemProviderCopyingLoadOperator, NSValue}, NSUUID, {}]
 Reply block: (arg #4, (2 arguments, 0 proxies), signature 'v@?@@"NSError"') [{NSObject}, {NSError}]
SEL: _cancelRequestWithError:forExtensionContextWithUUID:completion: (3 arguments, 0 proxies)
 Classes: [{NSError}, NSUUID, {}]
 Reply block: (arg #4, (0 arguments, 0 proxies), signature 'v@?') []

<NSXPCConnection: 0x28367ef80> connection from pid 7248<…>
error	09:50:50.533003+0100	Youtube	error from host: Error Domain=NSCocoaErrorDomain Code=4099 UserInfo={NSDebugDescription=<private>}
error	09:50:53.037352+0100	YouTube	nw_connection_copy_connected_local_endpoint_block_invoke [C3] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
error	09:50:53.037462+0100	YouTube	nw_connection_copy_connected_remote_endpoint_block_invoke [C3] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
error	09:50:53.037594+0100	YouTube	nw_connection_copy_protocol_metadata_internal_block_invoke [C3] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
error	09:50:53.069252+0100	YouTube	nw_connection_copy_connected_local_endpoint_block_invoke [C4] Client called nw_connection_copy_connected_local_endpoint on unconnected nw_connection
error	09:50:53.069350+0100	YouTube	nw_connection_copy_connected_remote_endpoint_block_invoke [C4] Client called nw_connection_copy_connected_remote_endpoint on unconnected nw_connection
error	09:50:53.069401+0100	YouTube	nw_connection_copy_protocol_metadata_internal_block_invoke [C4] Client called nw_connection_copy_protocol_metadata_internal on unconnected nw_connection
error	09:50:53.583936+0100	YouTube	Trying to set delaysTouchesBegan to NO on a system gate gesture recognizer - this is unsupported and will have undesired side effects
`

You can find a list with all errors here: [Pastebin](https://pastebin.com/2Mmq1G29)

I think mostly relevant are the errors coming from BackgroundShortcutRunner when using the Shortcut - it also throws the fault stated above (NSSecureCoding allowed classes list contains [NSObject class], which bypasses security).

**Comment by qnblackcat** [comment]
Since it’s obv not an issue of uYouPlus and its tweaks, I don’t see why we should cover this problem? 

Btw, you always can save your downloaded data to Camera roll. uYou already had that feature

**Comment by PoomSmart** [comment]
I agreed with Qn. This goes to feature addition and not the issue per se.

**Comment by lupus0802** [comment]
Alright, as said, just wanted to let you know - I also tried enabling file sharing manually and didn't seem to get it to work. 

Regarding the folder - I wanted to get access to re-add videos (file and plists) in case I need to reinstall (delete and install) the app for some reason.

Sorry for bothering you with this, thanks for the great work with uYou+.
