### ISSUE TITLE
[Questions] [Suggestion] [Request] AirPlay - Can’t change quality

### ISSUE THREAD

**Issue by Manujito** [qnblackcat/uYouPlus#75]
I’m on the latest version side loaded through AltStore. I just noticed that when you cast to a tv through AirPlay (only way to avoid ads) you can’t change the quality and the videos are streamed in very VERY low quality.

The vanilla app doesn’t exactly let you choose the quality, but it lets you change to something like “better quality”.

Would it be possible to restore that functionality, or even better, give full control on resolution when streaming through AirPlay?

Up until last week I was using a very very old version of YouTube++ on a jailbroken phone and could select the quality manually with no issue. I have no idea if it was the tweak or the old version of the app that allowed that.

Thanks a lot for all the work!

**Comment by qnblackcat** [comment]
Sorry. I don’t think it‘s possible :/

**Comment by Manujito** [comment]
Not even to restore the vanilla app functionality?
That's some bad news.
Thanks anyway.

**Comment by Manujito** [comment]
Ok, after trying again a few times it seems the quality adjusts itself to an acceptable state after a while. It just takes longer than expected.
Glad I can still use Airplay at least.
Once again, thanks for your time.
