### ISSUE TITLE
[Questions] workflow fail

### ISSUE THREAD

**Issue by QziP22** [qnblackcat/uYouPlus#751]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!
Yes

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###

End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of main/YouTube.ipa or
        main/YouTube.ipa.zip, and cannot find main/YouTube.ipa.ZIP, period.
Error: Process completed with exit code 9.

**Comment by qnblackcat** [comment]
You must use a direct URL to the IPA
