### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by sealants** [qnblackcat/uYouPlus#752]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###

Why are there no updates??

**Comment by EscapeAltDelete** [comment]
Dude be patient this guy is doing all this shit for free

**Comment by yodaluca23** [comment]
It's because all the newer YT versions, even directly from the App Store crash *A LOT!!!*
