### ISSUE TITLE
Background Playback Not Being Disabled When Turned Off in uYou Tab Settings

### ISSUE THREAD

**Issue by RyanPiao** [qnblackcat/uYouPlus#76]
On iOS 15.3.1 the "Background Playback" button in the uYou section does not affect the background playback, as it always remains on, even after the setting has been turned off.

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

**Comment by RichengPiao** [comment]
> https://github.com/qnblackcat/uYouPlus/wiki/FAQ

Q: The app stop playing when I turn off the screen?

A: I‘m pretty sure you have PiP enabled. PiP will stop playing when you lock the screen. This is iOS behave! Feel free to submit a feedback to Apple.

No! I did not turn on PIP
it is not turning off.

**Comment by qnblackcat** [comment]
**Q**: Why can't I disable Background playback?!? I turned off Background playpack in uYou Settings!

**A**: FYI, YouPiP enables Background playpack by default. Therefore, you can't completely disable Background playback.

> In case you hate Background playback that much: Extract the IPA, go to Payload > YouTube.app > Frameworks, delete YouPiP.dylib, and then re-create the IPA. Or you can just make your own version without YouPiP.

**Comment by RichengPiao** [comment]
I see. Thanks. I did not understand. Also than you for this wonderful tweek.

**Comment by qnblackcat** [comment]
In order to enable native-PiP, background playback must be enabled (by YouPiP). Therefore, you can‘t disable playground playback unless you remove YouPiP first
