### ISSUE TITLE
[Feature Request] Hide Shorts from Subscriptions Feed

### ISSUE THREAD

**Issue by Deagan** [qnblackcat/uYouPlus#761]
Would it be possible to identify and completely hide Shorts-type videos from the Subscriptions and Home feeds?

Perhaps there is an easier way to identify #Shorts specifically, but on YouTube Desktop, I filter out all videos under 60s long.

Maybe adding some feed filters to hide videos that have the following identifiers:

- "#Shorts" in the title/metadata
- A Shorts logo image within the thumbnail block
- A vertical aspect ratio
- And/or a video length within a specified time frame (ie. hide all videos between 0-60s)

I'd greatly appreciate not seeing these types of videos, while having some nice video feed filters!

**Comment by PoomSmart** [comment]
YTUnShorts

**Comment by Deagan** [comment]
> YTUnShorts

Woah, cool! Did you _just_ make this?

https://github.com/PoomSmart/YTUnShorts

How can we get this implemented with a toggle in uYouPlus?

**Comment by qnblackcat** [comment]
> Would it be possible to identify and completely hide Shorts-type videos from the Subscriptions and Home feeds?

Go to uYou‘s settings > Other Settings > Remove Shorts…

**Comment by Deagan** [comment]
> > Would it be possible to identify and completely hide Shorts-type videos from the Subscriptions and Home feeds?
> 
> 
> 
> Go to uYou‘s settings > Other Settings > Remove Shorts…

This setting does not remove Shorts videos from the Subscription feed.

**Comment by Deagan** [comment]
@PoomSmart @qnblackcat 

Does YTUnShorts remove Shorts videos from the Subscriptions feed?
