### ISSUE TITLE
[Bug] (YouPiP not working with premium Youtube account)

### ISSUE THREAD

**Issue by knighthawk127** [qnblackcat/uYouPlus#766]
iOS/iPadOS version: iOS 16.1 Device model: IPhone 12 Pro Sideload tool: issue present with AltServer & Signulous Version of uYouPlus: v17.41.2-2.1

Issue: 
Ever since I upgraded my YouTube account to be a premium subscription with native background playback I am no longer able to get PIP to work. When I minimize the app playback continues in the background but no PIP window is present. Additionally, when I enable “use PIP button” in the settings nothing happens at all when pressing the button. Sometimes after pressing the button and minimizing Youtube the video is just a blank image when opening the Youtube app again during playback (video attached of this behavior).  Even with legacy mode enabled I get no PIP. The only way to get some kind of PIP to work is to enable the uYou PIP settings and tap on the button while a video plays. This is much slower as it shows a “Loading” message on screen for a few seconds before it pulls up the pip video. This is not nearly as elegant as how it works with a non-premium  account. 

![B5BBF015-BE93-469B-93EF-155D713FE233](https://user-images.githubusercontent.com/34044911/207693225-c5ddd2cb-1cb9-4579-9947-35a4c8d503da.png)

![41056C23-A0D0-43A3-9E30-2926954FD5E6](https://user-images.githubusercontent.com/34044911/207693263-e00554a9-402b-4fd7-b437-fa99e275408d.png)

Link to video of pip button not working and black screen after having pressed it: 

https://drive.google.com/file/d/1Wa8RrzDZZEAFYSs8bxYsXdUqOwI6NVIt/view?usp=drivesdk

**Comment by l4kr** [comment]
It's in the General settings of the YouTube app for YT Premium users.
