### ISSUE TITLE
[Bug] YouTube Stories not playing with uYouPlus

### ISSUE THREAD

**Issue by arichornlover** [qnblackcat/uYouPlus#767]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16.2
- Device model: iPhone 11
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) AltStore
- The specific version of uYouPlus: 17.49.4-2.1 (this version I use was built by @arichorn)

### Describe the bug
So I decided to go into a story using uYou+ but for some reason it doesn’t play the story. Basically it is just not working by the looks of it.

### How to reproduce the bug (I tried)
https://user-images.githubusercontent.com/78001398/207726739-4f081a82-56b5-443f-b053-7ab7d6473f06.MOV

### Crash log (if possible)
unfortunately didn’t have one.

### Are you using the newest version of uYouPlus? If not, why?
Well yes, my iPhone only uses the newest version of uYou+ and obviously built by me. same uYou+ either way though.

### Does the issue happen with the official YouTube from AppStore?
Nope. Tested both apps and confirmed it was only happening in uYouPlus.

**Comment by PoomSmart** [comment]
Say someone reported you a bug but it was not reproduced from your original work but rather the randomly modified version of that, would you bother looking into it?

**Comment by PoomSmart** [comment]
Do we need a new issue label called "modified" just to indicate that this bug is reproduced from the non-original uYou+ or something?

**Comment by PoomSmart** [comment]
Not necessarily, I’m talking bug reporting in general.

**Comment by arichorn** [comment]
Well. It’s practically the same uYouPlus as before but with some “small” additions. but anyways the whole point is I do say bug reporting is still the same when using a different version of the app or having it modified.

**Comment by PoomSmart** [comment]
You never know. Software is unpredictable. Next time do include the actual additions you made to your uYouPlus build.

**Comment by arichorn** [comment]
There is a workaround for this issue:
Swipe up/down in the story and it should hopefully start playing the video

**Comment by jaff80** [comment]
YouTube Stories have been [discontinued](https://support.google.com/youtube/thread/217640760/youtube-stories-are-going-away-on-6-26-2023?hl=en) since June 26, 2023. So, I believe this issue should be closed now.
