### ISSUE TITLE
Cannot toggle on the *Remove Youtube ads* and *Disable age restriction* from the other settings in uYou settings.

### ISSUE THREAD

**Issue by ciaociaoweb** [qnblackcat/uYouPlus#768]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...)
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in your device's Settings App > Privacy > Analytics & Improvements > Analytics Data > Youtube-xxx-xxx.ips)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

**Comment by ciaociaoweb** [comment]
![Screenshot 2022-12-15 at 8 04 27 PM](https://user-images.githubusercontent.com/105258592/207888865-30fbd7d6-611b-4c9a-8cd9-4daf53abe0e8.png)

**Comment by arichorn** [comment]
Those were turned off in the code because those option’s don’t work anymore. if you had the ability to toggle “Remove YouTube Ads” the only thing it’ll do is remove timestamps on YT thumbnails instead. Which is why it’s been turned off in the first place.
