### ISSUE TITLE
[Enhancement] Vanced-like button to copy url with current timestamp

### ISSUE THREAD

**Issue by AuroraWright** [qnblackcat/uYouPlus#77]
I've been using this for a few weeks at this point after moving to iOS and I've been having a great time, thanks! There's just an enhancement I'd like to suggest: Android YT Vanced allows you to add a button on the video overlay to copy a video url including the current timestamp. I found myself using that feature pretty often to share specific timestamps with friends (it's no big deal to add ?t=XmYs to the url myself but it'd be nice to have it here as well). Thanks again for your hard work!

**Comment by qnblackcat** [comment]
This sounds good but it's beyond my knownledge. Someone else can do that but not me :/
