### ISSUE TITLE
YouTube Reborn being discontinued, cross-implementation welcome.

### ISSUE THREAD

**Issue by LillieH001** [qnblackcat/uYouPlus#773]
Hello, so you may know me as the dev of YouTube Reborn v3/v4, yesterday I switched to Android fully and have decided to pull the plug on my iOS projects, I changed YouTube Reborn v4 to mit so feel free to implement it in this project. It might be a good base for a lot of things since the source code of the preferences is full so you can add more customizability and so on.

https://github.com/LillieH001/YouTube-Reborn

**Comment by qnblackcat** [comment]
A bit sad when you left the jailbreak community :/ But I respect your decision. Wish you all the best!

**Comment by bishbash21** [comment]
We will miss you, good luck in your life endeavors.
