### ISSUE TITLE
Cerecube plus repo gone?

### ISSUE THREAD

**Issue by Macleykun** [qnblackcat/uYouPlus#775]
Heya, may I ask why ya deleted the repo?

**Comment by qnblackcat** [comment]
I can’t. Sorry

**Comment by Macleykun** [comment]
> I can’t. Sorry

Np, thank you for all your hard work nevertheless and a happy Christmas and new year :)

**Comment by yodaluca23** [comment]
> Np, thank you for all your hard work nevertheless and a happy Christmas and new year :)

My guess is that it got DMCA'ed or something, I just really hope the same doesn't happen to uYou+...
