### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by burgio777** [qnblackcat/uYouPlus#777]
is there any way to get updates in AltStore without the beta? am i wrong or it was possible before to add sources via a .json file without the beta? the settings not opening bug has been fixed btw 

## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###

**Comment by qnblackcat** [comment]
> is there any way to get updates in AltStore without the beta?

no, it isn’t
