### ISSUE TITLE
[Bug] <YT Video Quality on WiFi/Cellular>

### ISSUE THREAD

**Issue by NimboYT** [qnblackcat/uYouPlus#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): 17.48.2_2.1

### Describe the bug

YT Video Quality on WiFi/Cellular simply doesnt work as intended...

### Steps to reproduce the issue

1. Simply try to play any video
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment]
Did you enable LegacyPiP in YouPiP‘s setting?

**Comment by Cactus98** [comment]
I simply found that using uYou's own video quality management more effective.

If you want to try, tap the uYou tab at the bottom of the YouTube app > Cog icon at the top right > Under "Quality and Format" change the desired video quality on their respective network type.

**Comment by qnblackcat** [comment]
Closed due to inactive
