### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by Kief5555** [qnblackcat/uYouPlus#786]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###

Hi,

After reading the FAQ, my answer was not in the question.

I noticed after updating uyou+ to the latest version my video loading is horrible. When I play any video (shorts, regular videos) it seems to have the lowest quality for 3-7s before ramping it up to my preferred 1080p. The only workaround I found is to manually select 1080p from auto. I know 3-7s may seem like little time, but trust me, it will piss you off

**Comment by qnblackcat** [comment]
Check your internet speed

**Comment by Kief5555** [comment]
> Check your internet speed

700mbps

**Comment by Kief5555** [comment]
@qnblackcat
