### ISSUE TITLE
[Questions] How to disable thumbnail preview ?

### ISSUE THREAD

**Issue by Zegorax** [qnblackcat/uYouPlus#787]
Hello,

Is there a way to disable Thumbnail Previews ? I'm speaking about the playing of videos on the homescreen, when the scrolling stops.

There is the setting in the official YouTube app, as far as I know, but I cannot find it in uYouPlus.

Thanks a lot for your answer.

**Comment by qnblackcat** [comment]
Disable Thumbnail Previews in YouTube‘s settings > General > Playback in feeds

**Comment by Zegorax** [comment]
Thank you very much!

**Comment by ogkimra** [comment]
![image](https://github.com/qnblackcat/uYouPlus/assets/32086892/e73f1630-ae43-41ac-8be7-83672d8d04b4)
Can't see the option here.. My uYouPlus's version is `18.4.1-3.0`
