### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by Mhc1014** [qnblackcat/uYouPlus#79]
Video lengths are invisible in playlists and in watch history. I'm wondering why this is and how to fix it. In the first picture you can see it's visible in the subscriptions tab. It's visible in the home tab too, but whenever I open a playlist or look through my watch history, the length is invisible.
![9D23C6E2-83E0-4BF5-B771-00AEE96F28F6](https://user-images.githubusercontent.com/101130561/157081508-d61da6db-4b01-48b7-8d5b-ca88aaf84d78.jpeg)
![F2509400-D482-45C5-BC67-0F28244D33B0](https://user-images.githubusercontent.com/101130561/157081523-a2eaed6e-c092-46cc-9914-c13346b7a6b7.jpeg)

**Comment by Mhc1014** [comment]
Thank you so much!

**Comment by ramondunker** [comment]
My history from uYouPlus isn't tracked, only history from other devices is visble. I've checked every setting in the app but couldn't find anything. Is there a workaround for this?

**Comment by Mhc1014** [comment]
Yes, go to uYou's settings > Other Settings and Disable "Remove YouTube Ads"
