### ISSUE TITLE
Black screen issues

### ISSUE THREAD

**Issue by Kief5555** [qnblackcat/uYouPlus#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: LTS BETA
- Device model: iPhone 12
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): 17.48.2_2.1

### Describe the bug

Ever since I upgrade versions of uYouPlus, I got black screen issue and loading issues.

when I load a video sometimes it plays for 2 seconds then turns black.

when I load a video and play it (assuming it works (80%)) then I lock my phone (so pressing the side button) then waiting 5 sec or more, it would show a thumbnail of the last shorts I was playing (paused or playing)

as for the quality issues, I got 1GBPS and over 500 all the time to my phone. All shorts and videos quality start extremely poor, and get better after 10 seconds.

### Steps to reproduce the issue

explained in desc

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

✅ Yes, It does

### Additional context

The black screen issues happen with YouTube, but unable to test thumbnails problems due to no yt premium

quality issues only happens on uYouPlus

**Comment by Kief5555** [comment]
Switched between apps also has the extremely annoying thumbnail issue

**Comment by Kief5555** [comment]
More issues - videos with different audio (languages) never go English they go to something else, all of this makes me waste more time then watching ads lol

**Comment by qnblackcat** [comment]
Dupilcate of https://github.com/qnblackcat/uYouPlus/issues/567
