### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by Approvingss** [qnblackcat/uYouPlus#793]
![AC627644-F5DC-428D-BCCA-23CFEA1783E4](https://user-images.githubusercontent.com/90456362/209459787-5cf256ff-2629-4349-9af3-13a0380c49ac.jpeg)
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ
###

It says Restricted mode has hidden comments for this video and it doesn’t let me disable restricted mode it says “turned on by your network administrator to help hide potentially mature videos”

**Comment by RavanGami** [comment]
./sshrd.sh: line 218: 9062 Killed python3 -m pying4 in4p creat e -i work/ramdisk.dmg -o work/ramdisk.1m4p -f rdsk [-] An error occurred [-] An error occurred [*] A failure log has been made. If you're going ask for help, please attach the

**Comment by RavanGami** [comment]
![image](https://user-images.githubusercontent.com/114746710/209459838-bee4a298-b44b-4e3a-a39d-40bfcaf13874.jpeg)
