### ISSUE TITLE
[Questions] About Red progress bar

### ISSUE THREAD

**Issue by CySxL** [qnblackcat/uYouPlus#797]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!
Yes !
https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###

I wonder what tweak does v17.49.6-2.1 added to have red progress bar ? I've searched a bit for PoomSmart's YTABConfig and YouTube-X but kinda not found the changes tho.

Any help is appreciated !!

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/blob/0db45c7ce780ee3b22fcc9482d014695393b7a8b/uYouPlus.xm#L1227

**Comment by CySxL** [comment]
> https://github.com/qnblackcat/uYouPlus/blob/0db45c7ce780ee3b22fcc9482d014695393b7a8b/uYouPlus.xm#L1227

Thanks a lot !!
