### ISSUE TITLE
[Bug] Dislike count not showing

### ISSUE THREAD

**Issue by jaff80** [qnblackcat/uYouPlus#799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.1.2
- Device model: iPhone 13 Pro Max
- Sideload tool: AltStore
- The specific version of uYouPlus: v17.49.6-2.1

### Describe the bug

When you watch a video, the dislike button just says "Dislike". Enabling Exact dislike numbers does not fix the bug.
![IMG_ED865703EF93-1](https://user-images.githubusercontent.com/113552154/209486495-1e8a490b-6b2c-4d6b-8159-e053b819177f.jpeg)

### Steps to reproduce the issue

1. Open the YouTube app
2. Tap on a video
3. Dislike button should just say "Dislike"

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

I think this bug is happening because I have the old layout.

**Comment by PoomSmart** [comment]
Will be fixed in RYD 1.10.1

**Comment by qnblackcat** [comment]
[v17.49.6-2.3~1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.49.6-2.3(1))
