### ISSUE TITLE
[Bug] Video doesn’t play sometimes 

### ISSUE THREAD

**Issue by Dragoon853** [qnblackcat/uYouPlus#8]
This happens when I search for something and try to play or when I try to play a video from my subscriptions. The audio plays just fine but no video. It’s just black. Only when I close the video, open another one and then close that it starts working properly

**Comment by qnblackcat** [comment]
Thanks for the report. How do you reproduce the bug?

**Comment by Dragoon853** [comment]
I installed uYou (the latest version) with sideloady v0.23.1
1. Open the app and try to play any video/shorts. 
2. The audio play, the subtitles work but video doesn't play. It most commonly happens with [this](https://www.youtube.com/playlist?list=PLpMVXO0TkGpfeP4b7Cm8JbE0z-TztVF6U) playlist but I've noticed it happen with other videos.
3. Close the video/shorts
4. Play another video. Playing another short doesn't seem to do anything
5. Once the second video plays properly you can close it and then everything will be back to normal until step 1 repeats randomly

PS:  I thought it was a network issue and tried when connected with a good Wi-Fi but the issue persists.

**Comment by qnblackcat** [comment]
Close due to inactive (21 days)
