### ISSUE TITLE
[Enhancement] Add YTstockshare as one of the bundled tweaks to uYouPlus

### ISSUE THREAD

**Issue by PencilNotPen** [qnblackcat/uYouPlus#80]
Hi, I was wondering if it would be possible to include YTStockShare as one of the tweaks bundled into uYouPlus. It removes YouTube's proprietary share sheet and replaces it with the standard iOS one, matching the rest of the OS.

https://github.com/iCrazeiOS/YTStockShare

I have tested injecting the latest .deb of YTStockShare into the latest releases of uYouPlus using Sideloadly, and it works perfectly on uYouPlus_16.42.3_2.1.ipa. However, the tweak does not seem to work on uYouPlus_17.09.1_2.1.ipa. Something must have changed in YT v17.x. I have asked the dev on Github if he can update the tweak, but no response yet.

Perhaps it is a fix small and easy enough to be accomplished by someone here? Or perhaps someone knows how to get in touch with the dev directly. The code is open source if someone is able to tweak it to support YT v17.x.

Failing that, perhaps it could be incorporated as is into the legacy uYouPlus_16.42.3_2.1.ipa at least? This would require no changes as the tweak works perfectly on YT v16.x.

Thanks for a great tool, it is a must-have on non-jailbroken devices!

**Comment by qnblackcat** [comment]
YTStockShare is good but it's quite unreliable atm. I won't add it to uYou+ unless it is updated.

**Comment by qnblackcat** [comment]
Please re-open the issue once YTStockShare is updated

**Comment by PencilNotPen** [comment]
https://github.com/iCrazeiOS/YTStockShare/issues/1#issuecomment-1062353325

**Comment by PencilNotPen** [comment]
HI @qnblackcat, just wanted to let you know that a user has made a version of YTstockshare for newer YouTube versions:

https://github.com/iCrazeiOS/YTStockShare/issues/1#issuecomment-1975397230

I have tested it on Trollstore with the newest version of uYou+ and it works, in case you wanted to bundle it in uYou+.

Cheers!
