### ISSUE TITLE
[Bug] Missing uYou buttons in Shorts

### ISSUE THREAD

**Issue by therealFoxster** [qnblackcat/uYouPlus#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.3
- Device model: iPhone 13 mini
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): v17.49.6_2.1

### Describe the bug

When viewing shorts, there's no uYou button so I can't download Shorts videos. Weirdly, these buttons are present on my iPad running 16.3 and iPhone running 14.2, so only my 13 mini on 16.3 is experiencing this issue.

![IMG_2633](https://user-images.githubusercontent.com/77606385/209486601-d1ccc1df-1e27-4c92-84e5-29846c55badf.PNG)

### Steps to reproduce the issue

1. View Shorts video.
2. Observe.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment]
Did you change any value in YTABConfig?

**Comment by jluims** [comment]
Same for me. iOS 15.0.2

**Comment by therealFoxster** [comment]
> Did you change any value in YTABConfig?

No I never enabled it in the first place

**Comment by qnblackcat** [comment]
What is the value of `iosEnableShortsPlayerSplitViewController” in YTABConfig?

**Comment by therealFoxster** [comment]
It was on for some reason. I turned it off and the icons now show up. Thanks!

**Comment by qnblackcat** [comment]
> > It was on for some reason. I turned it off and the icons now show up. Thanks!
> 
> weird. I literally turned it off in uYou+
> 
> https://github.com/qnblackcat/uYouPlus/blob/0db45c7ce780ee3b22fcc9482d014695393b7a8b/uYouPlus.xm#L443

NVM, it should be`YTHotConfig`...

**Comment by CySxL** [comment]
> > > It was on for some reason. I turned it off and the icons now show up. Thanks!
> 
> > 
> 
> > weird. I literally turned it off in uYou+
> 
> > 
> 
> > https://github.com/qnblackcat/uYouPlus/blob/0db45c7ce780ee3b22fcc9482d014695393b7a8b/uYouPlus.xm#L443
> 
> 
> 
> NVM, it should be`YTHotConfig`...

I have the iosEnableShortsPlayerSplitViewController value disabled too, but still don't see the uYou buttons in shorts. Is there any difference if I use the uYou tweak instead ?
