### ISSUE TITLE
[Bug] 'Custom Double Tap To Seek Time' Not Working

### ISSUE THREAD

**Issue by korboybeats** [qnblackcat/uYouPlus#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 15.4.1
- Device model: M1 iPad Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): TrollStore
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): 17.49.6_2.1

### Describe the bug

I set a custom double tap length, for example 5 seconds, but whenever I double tap, it just skips 10 seconds no matter what.

### Steps to reproduce the issue

1. Set custom double tap length
2. Double tap on video

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment]
Please try [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)

**Comment by qnblackcat** [comment]
This option was removed in uYou 3.0.2
