### ISSUE TITLE
[Bug] Previous & Next button doesn’t hide from likes videos 

### ISSUE THREAD

**Issue by ShadowRoi** [qnblackcat/uYouPlus#804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:
15.4.1
- Device model:
13 Pro
- Sideload tool:
 TrollStore
- The specific version of uYouPlus: 17.49.6_2.1

### Describe the bug

Hiding previous and next button in control overlay doesn’t work when watching liked videos

### Steps to reproduce the issue

1. Turn Hide previous and next button in control overlay on
2. Go watch a video on your liked playlist

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment]
This is intentional because playlist is the only place where the next & previous buttons actually become useful
