### ISSUE TITLE
[Question] Will there be an option to hide all Products shown in the App?

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#806]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

### Device info

- iOS/iPadOS version: iPadOS 15.7.2
- Device model: iPad Pro 10.5 (2nd gen)
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...) AltStore
- The specific version of uYouPlus: 16.42.3-2.1 (this version I use was built by @arichorn + it also includes all of changes from qnblackcat’s current release 17.49.6-2.1!)

### Will there be an option to hide all Products on the App?
the reason why I’m talking about this is because YouTube won’t stop showing me about buying products constantly even if I’m on the oldest supported version and they still somehow manage to implement these type of annoying things that’s very dumb and unnecessary in the app. I may not be the only who finds this annoying.
![60436196-85B0-418F-BFDF-0E630F38E607](https://user-images.githubusercontent.com/78001398/209583457-29bcdd35-bf55-43e4-bc74-ca00ded9c1dd.jpeg)

**Comment by jaff80** [comment]
This is a feature that I would also like to see and use!

**Comment by arichorn** [comment]
I agree! uYouPlus is missing out on an opportunity for us to toggle and hide the Products. Right now Products is currently ruining the home feed with it. Especially on iPads

**Comment by qnblackcat** [comment]
No because this kind of ads is not even show up in my region. Therefore I can't investigate it

**Comment by arichorn** [comment]
maybe I can use FLEX on this issue. I'll try to Investigate the stuff it uses and try to probably hide it
