### ISSUE TITLE
[Bug] ads in search results

### ISSUE THREAD

**Issue by DetachHead** [qnblackcat/uYouPlus#81]
**Device info:**
- iOS/iPadOS version: 15.1.1
- Device model: iPhone 13
- Sideload tool: AltStore 
- Version of uYouPlus: v17.09.1-2.1

![7B91F59F-0BB3-4882-917D-403CF9DFF5EF](https://user-images.githubusercontent.com/57028336/157551528-7db8a2e9-7d31-4ae4-a032-601f03ab229c.jpeg)

**Comment by amit-bh** [comment]
Getting the same thing. Ads in search results only. On iPhone 11 iOS 15.3.1

**Comment by Slurpassassin** [comment]
Same issue here

**Comment by WoodpeckerBaby** [comment]
So?

**Comment by xericho** [comment]
Bump, any updates?

**Comment by WoodpeckerBaby** [comment]
😳

**Comment by wilsoncliu** [comment]
Wanted to see if there was a fix or is it still a bug?

**Comment by xericho** [comment]
Yup, I'm on latest release and I still see ads

**Comment by wilsoncliu** [comment]
> Yup, I'm on latest release and I still see ads

cool, thanks for confirming.

**Comment by qnblackcat** [comment]
Fixed in [v17.48.2-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.48.2-2.1) and higher. Credit goes to PoomSmart

**Comment by ButtSavage** [comment]
If you don't mind me asking what exactly was changed to make the ads not show up on searches? Was asking because I use an older version of uyouplus (16.42.3) on youtube 16.35.5 because youtube 17 feels like a step down to me in terms of UI.

**Comment by Proaxel** [comment]
> Fixed in [v17.48.2-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.48.2-2.1) and higher. Credit goes to PoomSmart

FINALLY
How do I get access to this fix via a jailbreak tweak?
