### ISSUE TITLE
[Questions] Asking to update to latest uYou version?

### ISSUE THREAD

**Issue by TheLidlMan** [qnblackcat/uYouPlus#811]
## 

![image](https://user-images.githubusercontent.com/75203773/209796475-cec55722-560e-42e0-ab31-f1a60c407eb7.jpeg)

###

**Comment by Racxie** [comment]
I'm getting this as well which doesn't make much sense considering even MiRO92's app is also on 2.1

**Comment by superfreeman1989** [comment]
I took the bait and tried to update, got the can't load plist error, and my old version stopped working. You've been warned.

**Comment by aco228** [comment]
Yep, I also got this notification but updating is not straightforward at all: it redirects me to https://miro92.com/repo/depictions/?p=com.miro.uyou and gives zero input on what to do. Is this a bug?

**Comment by SlimmerJarl4355** [comment]
please do not update. I did this and spent the next hour trying to reinstall my apps in which the newer version of uYou crashed instantly leaving me to uninstall and reinstall the older version, I am currently in the process of installing the newer uYou just to verify that it doesn't work

**Comment by Gertjan77** [comment]
Yeah update crashed for me as well. Luckily I could easily revert back to the previous version.

**Comment by Nexxol** [comment]
You guys do realise that the update button takes you to uYou and not uYouPlus right? That’s probably why it’s breaking.

**Comment by Sakooooo** [comment]
press skip and wait for qn to make the new release

**Comment by GyeongwonK** [comment]
+ I can't log into my google account due to this issue.

**Comment by abetl** [comment]
Same, it redirected me to miro92 and gave no other info, I'm not gonna update from that link. Sticking on my current version

**Comment by yodaluca23** [comment]
No one update!!! This is only gonna get uYou it will not get uYou+ please wait for @qnblackcat to release a new version of uYou+ with the latest uYou...

**Comment by qnblackcat** [comment]
> No one update!!! This is only gonna get uYou it will not get uYou+ please wait for @qnblackcat to release a new version of uYou+ with the latest uYou...

This is the answer

**Comment by arichorn** [comment]
> No one update!!! This is only gonna get uYou it will not get uYou+ please wait for @qnblackcat to release a new version of uYou+ with the latest uYou...

I tested out the new uYou 2.3 update and I avoided the errors, it worked fine until you go into the uYou Tab and pressing the pink settings icon on the top right. What I’m saying is the uYou settings will crash

also here’s the crash log. Be careful y’all [uYou 2.3~1 CrashLog](https://github.com/qnblackcat/uYouPlus/files/10326792/uYou2.3.1CrashLog.txt)
