### ISSUE TITLE
[Bug] DontEatMyContent doesn’t work properly - iPhone 14 Pro Max

### ISSUE THREAD

**Issue by Pheuk** [qnblackcat/uYouPlus#815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: iPhone 14 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore and Sideloadly.
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): 17.49.6

### Describe the bug

Tweak doesn’t work properly. Dynamic island is visible in landscape mode. Version 1.0.4 worked fine. 

### Steps to reproduce the issue

![8CCB558B-C309-4CFF-A893-7298AF6EC175](https://user-images.githubusercontent.com/41029042/209866945-edea4d86-c2c3-4644-8098-321fdd196149.jpeg)
![3D5264A1-B735-45E4-B1E0-8F1D945DEF47](https://user-images.githubusercontent.com/41029042/209866953-f6e2606a-0122-45bd-9352-572db64c9dbd.jpeg)
![10FED464-12A1-42AC-A9A3-94374CCCE208](https://user-images.githubusercontent.com/41029042/209866956-968d3641-e639-49b2-a437-dc5e53d0bc9f.jpeg)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment]
@therealFoxster

**Comment by therealFoxster** [comment]
Thanks for reporting. I tried to push the video a bit closer to the notch on the 13 mini but didn't realize it caused this. I'll increase the gap a bit. Let me know if it helps.

Also, just out of curiosity, is this the 14 Pro Max?

**Comment by therealFoxster** [comment]
Can you try [this version](https://github.com/therealFoxster/uYouPlus/releases/tag/v17.49.6-2.1-(38)) and let me know how it looks? It should look something like this: 
![IMG_2636](https://user-images.githubusercontent.com/77606385/209886046-c7661201-1d6b-48ad-8b2f-4aab1ead6edf.PNG)

**Comment by Pheuk** [comment]
> Thanks for reporting. I tried to push the video a bit closer to the notch on the 13 mini but didn't realize it caused this. I'll increase the gap a bit. Let me know if it helps.
> 
> Also, just out of curiosity, is this the 14 Pro Max?

Hi! Thanks for answering so quickly. Yes it is iPhone 14 PM. I'm going to test the version you indicated and then I'll give feedback. Thanks once more!

**Comment by Pheuk** [comment]
> Can you try [this version](https://github.com/therealFoxster/uYouPlus/releases/tag/v17.49.6-2.1-(38)) and let me know how it looks? It should look something like this:
> ![IMG_2636](https://user-images.githubusercontent.com/77606385/209886046-c7661201-1d6b-48ad-8b2f-4aab1ead6edf.PNG)

Here it is:

![8BC5BCE1-6EF8-405A-82D9-3E764AC9E462](https://user-images.githubusercontent.com/41029042/209891682-30e14394-f1e7-4090-94df-4f5ad92a634e.jpeg)


Just a little further down the dynamic island and it will be perfect. Thanks once again and keep the awesome work!

**Comment by therealFoxster** [comment]
Okay, can you please try [this version](https://github.com/therealFoxster/uYouPlus/releases/tag/v17.49.6-2.1-(40))? I have increased the gap a little more; hopefully it's enough to push the video away from the Dynamic Island. Thanks!

**Comment by Pheuk** [comment]
> Okay, can you please try [this version](https://github.com/therealFoxster/uYouPlus/releases/tag/v17.49.6-2.1-(40))? I have increased the gap a little more; hopefully it's enough to push the video away from the Dynamic Island. Thanks!

Here it is:

![1BE4E988-B8CC-450E-8958-3DA4C34DF419](https://user-images.githubusercontent.com/41029042/209934185-83c16dfc-00f9-4b9e-9726-13a21d5ba54a.jpeg)
![7E7A4135-5687-4A94-9898-A3CD7934C35D](https://user-images.githubusercontent.com/41029042/209934189-3bc36730-6d77-4c00-bbf4-b8833c6733f6.jpeg)

Just a little more tiny adjust and it’ll be perfect. Thanks, man. who can I donate you a coffee?

**Comment by therealFoxster** [comment]
Okay, hopefully [this](https://github.com/therealFoxster/uYouPlus/releases/tag/v17.49.6-2.1-(41)) will do the trick. I have increased the gap a fair bit more (even more than what I had set when I originally released the tweak).

Here's before and after on my device:
![IMG_2639_1](https://user-images.githubusercontent.com/77606385/209998301-f7de2ec1-4647-4b6d-ba81-70a285d1184d.png)

> Thanks, man. How can I donate you a coffee?

Nah come on bro this is nothing. I must also thank you for taking the time to test and help improve the tweak for everyone!

**Comment by Pheuk** [comment]
> 

It’s absolutely perfect now! Thank you so much! 

![3F47D5DD-7CC0-4BC4-8329-17A00777EF67](https://user-images.githubusercontent.com/41029042/210004991-128218bd-da87-4d3b-aaaa-d1b865371209.jpeg)

Best wishes for you and a happy new year!

**Comment by therealFoxster** [comment]
Awesome. Expect this change to be implemented in the next release of uYouPlus. Happy holidays and new year to you too!

**Comment by qnblackcat** [comment]
please update to [v17.49.6-2.3~1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.49.6-2.3(1))
