### ISSUE TITLE
[Questions] How to change name & have custom icons

### ISSUE THREAD

**Issue by Blockr22** [qnblackcat/uYouPlus#817]
Hi, sry if its not the right place to ask this question but if anyone can help me changing name & its icon. It would be awesome. @dvntm from appdb once told me how to do it but i forgot. Mainly I would like to have a black youtube & different name so that i can differentiate it better from original youtube. Thnx

**Comment by qnblackcat** [comment]
https://github.com/ethandgoodhart/IPAEdit 

Opencore there are other alternatives, Google is your friend

**Comment by Blockr22** [comment]
Thnx, but this needs a macbook. I need something that i can do on my iPhone or windows pc
