### ISSUE TITLE
[Questions] App says there is a new version, despite downloading latest version

### ISSUE THREAD

**Issue by DesperatePea** [qnblackcat/uYouPlus#823]
When i downloaded the latest release ipa from here, it says its version 17.49.6-2.1. Yet the app says it has an update available. Clicking and downloading the update from the site its linking, it gives me a different named app, called YouTube_16.42.3_uYou_2.1.ipa.

Which do i use?

**Comment by yodaluca23** [comment]
> When i downloaded the latest release ipa from here, it says its version 17.49.6-2.1. Yet the app says it has an update available. Clicking and downloading the update from the site its linking, it gives me a different named app, called YouTube_16.42.3_uYou_2.1.ipa.
> 
> 
> 
> Which do i use?

https://github.com/qnblackcat/uYouPlus/issues/811#issuecomment-1366979504 Please look at the other issues before opening a new one...
