### ISSUE TITLE
[Bug] New issue in latest update (v17.49.6-2.1) 

### ISSUE THREAD

**Issue by rajaomair** [qnblackcat/uYouPlus#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 15.4.1
- Device model: 12 pro max
- Sideload tool (AltStore)
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): [v17.49.6-2.1]

### Describe the bug

In this aforementioned latest version,

I am on videos tab of a channel, after opening a video, after going full screen, after exiting full screen, after minimising, 

then that videos tab page auto scroll down to 10-15 videos without me doing anything. I tried it multiple times on 2 devices but same issue.

It was definitely not present on previous versions, because I do view videos like this a lot and they just don’t scroll down auto when going and exiting full screen mode.

Thanks 😊.

### Steps to reproduce the issue

1. 

https://user-images.githubusercontent.com/20761578/210005119-2bd7a7e8-b64b-452d-9747-fa5c2bf9efdd.MOV

2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Hopefully you reply at least :)

**Comment by qnblackcat** [comment]
Known issue of YouTube itself. Pretty sure you haven't even tested this on the official YouTube app. 

We won’t fix this. Feel free to submit feedback to YouTube

**Comment by rajaomair** [comment]
Check it again mate 🤦🏻‍♂️, I can post a video of official youtube app here, will that satisfy you??
