### ISSUE TITLE
[Questions] YouTube randomly signs me out

### ISSUE THREAD

**Issue by craftgeil** [qnblackcat/uYouPlus#826]
So I do not know why, but now it happend the second time that YouTube just randomly signed me out on my iPhone (using uYou+ for about 2 months now).
I also have to use the workaround to log in, because my account just is not there anymore to click on (the account to log in was even there after deleting uYou+ entirely and reinstalling).
On my iPad I have not had any problems.
I did not delete the App or something like that.

I also noticed that BHTwitter asked for my password to verify its me (I think the first time YouTube signed me out, it also happend).

So has anyone an idea why this is? It is not really an issue because I can log in quite easily with the workaround again and my data is still there, but I would like to know if I can do anytithing to prevent it.

**Comment by qnblackcat** [comment]
Looks like this is a bug. Open a new issue with the bug template
