### ISSUE TITLE
[iPad Question]

### ISSUE THREAD

**Issue by TheGoldenSun** [qnblackcat/uYouPlus#828]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

### 

Hi I have a question, I tried downloading Uyouplus on my iPad Air two - version 15.5 tablet and when I did the file app only recognizes Uyouplus as an unknown source by placing a question mark icon logo within the file app, what can I do to fix this?

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/Installation
