### ISSUE TITLE
[Bug] Notification bell not working 

### ISSUE THREAD

**Issue by Casio7380** [qnblackcat/uYouPlus#83]
**Device info:**
- iOS/iPadOS version: IOS 15.2.1
- Device model: IPhone X 
- Sideload tool :AltStore
- Version of uYouPlus: v17.09.1-2.1

- crashes when I try to click the notification bell 

https://user-images.githubusercontent.com/101881483/159048652-6e562103-9778-4cd2-ba16-5eb445824857.MOV

**Comment by qnblackcat** [comment]
This is a known issue of uYou. Please follow this thread for more info: https://github.com/MiRO92/uYou-for-YouTube/issues/94
