### ISSUE TITLE
[Hint] MiRO92 released uyou 2.3

### ISSUE THREAD

**Issue by JMcrafter26** [qnblackcat/uYouPlus#834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:
- Device model:
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!):

### Describe the bug

Its not a bug, I just wanted to tell you

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by arichorn** [comment]
I know it released. Don’t use it or settings in uYou TAB won’t work.
