### ISSUE TITLE
[Questions] Hide or delete TAB uYou

### ISSUE THREAD

**Issue by thaibm1992** [qnblackcat/uYouPlus#836]
Please tell me is there any option to hide uYou tab or remove it from default setting i want it original like premium version 
thanks a lot, please help

**Comment by qnblackcat** [comment]
This should be requested on upstream uYou: https://github.com/MiRO92/uYou-for-YouTube

**Comment by yodaluca23** [comment]
https://github.com/MiRO92/uYou-for-YouTube/issues/181

**Comment by arichorn** [comment]
https://github.com/MiRO92/uYou-for-YouTube/issues/164
its also in here too
