### ISSUE TITLE
[Bug] in app notification indicates app is outdated and links to older version

### ISSUE THREAD

**Issue by alectprasad** [qnblackcat/uYouPlus#838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: iPhone 12
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): 17.49.6_2.1

### Describe the bug

![E8762F38-E161-4E59-B004-67FA40A3CCB1](https://user-images.githubusercontent.com/22129443/210166890-a6ea3f26-4593-4b16-969e-5d0b53b8e7d3.png)

pressing update now redirects to this site https://miro92.com/repo/depictions/?p=com.miro.uyou which links to this repo https://github.com/MiRO92/uYou-for-YouTube which is for version 16.42.3

### Steps to reproduce the issue

see above

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by ciaociaoweb** [comment]
It's the update of the core uYou by Miro92 on which uYouPlus is built.

**Comment by yodaluca23** [comment]
https://github.com/qnblackcat/uYouPlus/issues/811#issuecomment-1366979504 Please look at the other issues before opening a new one...
