### ISSUE TITLE
iSponsorBlock delays the skipping of Sponsor segments and maybe other sections too?

### ISSUE THREAD

**Issue by MarioMastr** [qnblackcat/uYouPlus#84]
**Device info:**
- iOS/iPadOS version:  15.4
- Device model: iPhone SE 2020
- Sideload tool: AltStore
- Version of uYouPlus: v17.09.1_2.1

In the title

**How to reproduce the bug:**
Simply let Youtube auto skip a sponsor segment.

**Comment by qnblackcat** [comment]
I cannot reproduce the bug and you need to provide more information. A screen record may help

**Comment by MarioMastr** [comment]
Sorry for the late response. iSponsorBlock doesn’t support decimal times so that’s probably why.

**Comment by qnblackcat** [comment]
I can’t even tell the difference between those two videos until you put them together. 

Well, if you think it‘s a real problem, please open a new thread on the [upstream iSponsorblock](https://github.com/Galactic-Dev/iSponsorBlock)
