### ISSUE TITLE
[Help] Building uYouPlus using M1 - 13.0.1 Xcode 14.1

### ISSUE THREAD

**Issue by siieo** [qnblackcat/uYouPlus#842]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###
hitori@Hitoris-Virtual-Machine uYouPlus % ./buildapp.sh
==> uYou v2.3~1 is not found. Downloading uYou (v2.3~1)...
+ curl https://miro92.com/repo/debs/com.miro.uyou_2.3~1_iphoneos-arm.deb --output Tweaks/uYou/com.miro.uyou_2.3~1_iphoneos-arm.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.4M  100 10.4M    0     0  1403k      0  0:00:07  0:00:07 --:--:--  768k
==> Extracting uYou...
> Extracted uYou!
==> Path to the decrypted YouTube.ipa or YouTube.app: /Users/hitori/Downloads/YouTube.ipa 
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
> Making all for tweak uYouPlus…
==> Preprocessing uYouPlus.xm…
Use of uninitialized value $1 in split at /Users/hitori/theos/bin/logos.pl line 604.
==> Compiling uYouPlus.xm (arm64)…
==> Preprocessing Settings.xm…
==> Compiling Settings.xm (arm64)…
==> Linking tweak uYouPlus (arm64)…
==> Generating debug symbols for uYouPlus…
==> Stripping uYouPlus (arm64)…
rm /Users/hitori/uYouPlus/.theos/obj/arm64/uYouPlus.xm.mm /Users/hitori/uYouPlus/.theos/obj/arm64/Settings.xm.mm
==> Merging tweak uYouPlus…
> Making all in Tweaks/Alderis…
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
> Making all for xcodeproj Alderis…
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:0000FE00-7789D84AEFE88A37 }
{ platform:macOS, arch:arm64, variant:Mac Catalyst, id:0000FE00-7789D84AEFE88A37 }
{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:0000FE00-7789D84AEFE88A37 }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
{ platform:iOS Simulator, id:95564C96-25CB-475F-BC07-5BE06F047CD9, OS:16.1, name:iPad (10th generation) }
{ platform:iOS Simulator, id:20EF1906-D766-4B15-B001-7357521C5C6C, OS:16.1, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:25B4C402-44B8-4422-A16C-791DF13FFAAC, OS:16.1, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:5F73156A-DF01-420B-9B39-5A0C87D522BE, OS:16.1, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:1827019F-8C9E-4503-B875-5DB643C8B84A, OS:16.1, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:BD9733DA-E186-4F44-B59D-46DCB951A2AA, OS:16.1, name:iPhone 14 }
{ platform:iOS Simulator, id:C1A64D42-1ABB-4C22-ABAA-35173B0C9289, OS:16.1, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:170D5285-C0FD-4D40-BB07-74A30A9F1D1A, OS:16.1, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:733E062F-AFE4-4CD8-ACFA-8CCA26B9ECB1, OS:16.1, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:95D6F839-E06B-4034-AE3A-BED828C968AD, OS:16.1, name:iPhone SE (3rd generation) }
Linting Swift files in current working directory
Linting 'FirstViewController.swift' (1/30)
Linting 'Assets.swift' (2/30)
Linting 'AppDelegate.swift' (3/30)
Linting 'ColorPickerInnerViewController.swift' (4/30)
/Users/hitori/uYouPlus/Tweaks/Alderis/Demo/Alderis Demo/AppDelegate.swift:17:1: warning: Superfluous Disable Command Violation: SwiftLint rule 'line_length' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)
Linting 'NSBeep.swift' (5/30)
Linting 'DialogButton.swift' (6/30)
Linting 'AccessibilityComplianceLabel.swift' (7/30)
Linting 'UIFontDescriptorAdditions.swift' (8/30)
Linting 'UIFloat.swift' (9/30)
Linting 'ColorPickerWheelView.swift' (10/30)
Linting 'ColorPickerSlidersViewController.swift' (11/30)
/Users/hitori/uYouPlus/Tweaks/Alderis/Demo/Alderis Demo/FirstViewController.swift:20:1: warning: Superfluous Disable Command Violation: SwiftLint rule 'function_body_length' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)
Linting 'SeparatorView.swift' (12/30)
Linting 'ColorPickerSwatchViewController.swift' (13/30)
Linting 'ColorWell.swift' (14/30)
Linting 'ColorPickerSlider.swift' (15/30)
Linting 'UIColorAdditions.swift' (16/30)
Linting 'BottomSheetTransition.swift' (17/30)
Linting 'ColorPickerAccessibilityViewController.swift' (18/30)
Linting 'TextViewLabel.swift' (19/30)
Linting 'ColorPickerConfiguration.swift' (20/30)
Linting 'AccessibilityContrastSelector.swift' (21/30)
Linting 'ColorPickerViewController.swift' (22/30)
Linting 'ColorPickerMapSlider.swift' (23/30)
Linting 'ColorPickerDelegate.swift' (24/30)
Linting 'ColorPickerNumericSlider.swift' (25/30)
Linting 'GradientView.swift' (26/30)
Linting 'ColorPickerTabViewController.swift' (27/30)
Linting 'ColorPickerMapViewController.swift' (28/30)
Linting 'Color.swift' (29/30)
Linting 'Package.swift' (30/30)
Done linting! Found 2 violations, 0 serious in 30 files.
note: Building targets in dependency order
warning: Run script build phase 'SwiftLint' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Alderis' from project 'Alderis')
==> Signing Alderis…
> Making all in lcpshim…
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
> Making all for library libcolorpicker…
==> Compiling ColorFunctions.m (arm64)…
==> Compiling HBColorPickerTableCell.m (arm64)…
==> Compiling PFColorAlert.m (arm64)…
==> Compiling PFColorCell.m (arm64)…
==> Compiling PFLiteColorCell.m (arm64)…
==> Compiling PFSimpleLiteColorCell.m (arm64)…
==> Compiling UIColor+PFColor.m (arm64)…
==> Linking library libcolorpicker (arm64)…
ld: warning: directory not found for option '-F/Users/hitori/uYouPlus/.theos/obj/xcode_derived/install/Library/Frameworks'
ld: warning: invalid -install_name (/Library/Frameworks/Alderis.framework/Alderis) in dependent dylib (/Users/hitori/theos/vendor/lib/Alderis.framework/Alderis.tbd). Dylibs/frameworks which might go in dyld shared cache cannot link with dylibs that won't be in the shared cache
==> Generating debug symbols for libcolorpicker…
==> Stripping libcolorpicker (arm64)…
==> Merging library libcolorpicker…
==> Signing libcolorpicker…
> Making all in Tweaks/iSponsorBlock…
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
> Making all for tweak iSponsorBlock…
==> Preprocessing iSponsorBlock.xm…
==> Compiling iSponsorBlock.xm (arm64)…
==> Compiling MBProgressHUD.m (arm64)…
==> Compiling SponsorBlockRequest.m (arm64)…
==> Compiling SponsorBlockSettingsController.m (arm64)…
==> Compiling SponsorBlockViewController.m (arm64)…
==> Compiling SponsorSegment.m (arm64)…
==> Compiling SponsorSegmentView.m (arm64)…
==> Linking tweak iSponsorBlock (arm64)…
==> Generating debug symbols for iSponsorBlock…
==> Stripping iSponsorBlock (arm64)…
rm /Users/hitori/uYouPlus/.theos/obj/arm64/iSponsorBlock.xm.mm
==> Merging tweak iSponsorBlock…
==> Signing iSponsorBlock…
> Making all in Tweaks/YTUHD…
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
> Making all for tweak YTUHD…
==> Preprocessing Common.x…
==> Compiling Common.x (arm64)…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
==> Preprocessing Settings.x…
==> Compiling Settings.x (arm64)…
==> Linking tweak YTUHD (arm64)…
==> Generating debug symbols for YTUHD…
==> Stripping YTUHD (arm64)…
rm /Users/hitori/uYouPlus/.theos/obj/arm64/Common.x.m /Users/hitori/uYouPlus/.theos/obj/arm64/Settings.x.m /Users/hitori/uYouPlus/.theos/obj/arm64/Tweak.x.m
==> Merging tweak YTUHD…
==> Signing YTUHD…
> Making all in Tweaks/YouPiP…
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
> Making all for tweak YouPiP…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
==> Preprocessing Settings.x…
==> Compiling Settings.x (arm64)…
==> Preprocessing LegacyPiPCompat.x…
==> Compiling LegacyPiPCompat.x (arm64)…
==> Linking tweak YouPiP (arm64)…
==> Generating debug symbols for YouPiP…
==> Stripping YouPiP (arm64)…
rm /Users/hitori/uYouPlus/.theos/obj/arm64/Settings.x.m /Users/hitori/uYouPlus/.theos/obj/arm64/LegacyPiPCompat.x.m /Users/hitori/uYouPlus/.theos/obj/arm64/Tweak.x.m
==> Merging tweak YouPiP…
==> Signing YouPiP…
> Making all in Tweaks/Return-YouTube-Dislikes…
==> Notice: Build may be slow as Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
> Making all for tweak YouTubeDislikesReturn…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
Tweak.xm:799:3476: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.1.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.1.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
Tweak.xm:799:3674: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.1.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.1.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
2 errors generated.
make[4]: *** [/Users/hitori/uYouPlus/.theos/obj/arm64/Tweak.xm.0bfaf8cf.o] Error 1
rm /Users/hitori/uYouPlus/.theos/obj/arm64/Tweak.xm.mm
make[3]: *** [/Users/hitori/uYouPlus/.theos/obj/arm64/YouTubeDislikesReturn.dylib] Error 2
make[2]: *** [internal-library-all_] Error 2
make[1]: *** [YouTubeDislikesReturn.all.tweak.variables] Error 2
make: *** [internal-all] Error 2
The file /Users/hitori/uYouPlus/packages does not exist.
==> Cleaning up...
shasum: packages/*.ipa: No such file or directory
==> SHASUM256: 
-----------------------
I don't know why it keeps showing that error do you guys have any idea ?

**Comment by siieo** [comment]
I got sdks from https://github.com/chrisharper22/sdks

**Comment by qnblackcat** [comment]
@PoomSmart what even is this? :(

**Comment by PoomSmart** [comment]
From the error message it's an issue with using `sprintf` function. This has been fixed quite a while ago in https://github.com/theos/logos/pull/88. Update your Theos instance via `$THEOS/bin/update-theos`. @siieo
