### ISSUE TITLE
[Help] Build failing on macOS 13.1 with XCode 14.2

### ISSUE THREAD

**Issue by eyeb0l** [qnblackcat/uYouPlus#843]
I have not added or removed any tweaks and am getting this error when trying to build uYouPlus
<img width="1039" alt="Screenshot 2023-01-03 at 11 18 28" src="https://user-images.githubusercontent.com/21983343/210347321-aac06827-9096-4364-a47a-39ab28bfee50.png">

**Comment by qnblackcat** [comment]
please try again with the last commit

**Comment by eyeb0l** [comment]
Thanks, it works now
