### ISSUE TITLE
[Bug] Scroll bar doesn’t work when holding it to fast scroll in channel page and scrolling down in comments to see the top and new bubbles in comments is glitchy and doesn’t always show enough of it to click.

### ISSUE THREAD

**Issue by justkeepwalking99** [qnblackcat/uYouPlus#844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 16
- Device model: iPhone XR
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): 17.49.6_2.1

### Describe the bug

Scroll bar doesn’t work when holding it to fast scroll in channel page and scrolling down in comments to see the top and new bubbles in comments is glitchy and doesn’t always show enough of it to click.

### Steps to reproduce the issue

1. Scroll bar doesn’t work when holding it to fast scroll in channel page
2. scrolling down in comments to see the top and new bubbles in comments is glitchy and doesn’t always show enough of it to click.
3. Please fix it if you can. This might be an issue YouTube needs to fix in its update or it might be uYou cause uYou didn’t use to have these problems.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment]
> Does the issue happen with the official YouTube from AppStore?

Have you really checked it? Because I can easily recall this issue on the official YouTube app

**Comment by qnblackcat** [comment]
Well, Google should fix it, not us
