### ISSUE TITLE
[Bug] Not installing on iPhone

### ISSUE THREAD

**Issue by Sleepdealr** [qnblackcat/uYouPlus#848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.2
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): v17.49.6-2.1

### Describe the bug

Fails to install
Have repeated installation multiple times over different days, both the IPA and link
Have reinstalled altstore twice with no changes
ID's get used up but with no app getting installed

### Steps to reproduce the issue

1. Install uyou+, either through link or IPA file

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment]
Try to use Sideloadly
