### ISSUE TITLE
[Bug] when I locked the screen in pip it pause’s the video

### ISSUE THREAD

**Issue by Almigo21** [qnblackcat/uYouPlus#85]
- iphone 13
- iOS 15.1.1:
- AltStore
- uYouPlus_16.42.3_2.1

when I locked the screen in pip it pause’s the video

**Comment by qnblackcat** [comment]
FAQ

https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-the-app-stop-playing-when-i-turn-off-the-screen
