### ISSUE TITLE
[Questions] how to force to pause when opening a video

### ISSUE THREAD

**Issue by ntomita** [qnblackcat/uYouPlus#851]
Hi, I'm looking for an option to auto-pause a video when opening the video. It's useful when I want to just check the description or comments of a video without watching/playing it. 

I'm asking this because it was somehow possible until I reinstalled the app. I don't remember how I could enable it. FYI I had to reinstall the app because prompted to install new version, meaning that I was probably using an older version (but definitely newer than 2022 September version). Thanks for your help!

**Comment by qnblackcat** [comment]
uYou's setting > Other settings > Disable Video Auto Play

**Comment by ntomita** [comment]
Ah, this is it, perfect, thanks!
