### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by romantra** [qnblackcat/uYouPlus#853]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###

why the latest release states that it has the 2.3.1 version of uYou but when you install it says 2.1 ?

**Comment by qnblackcat** [comment]
MiRO92 probably forgot to edit the version number inside the tweak. It's actually v2.3~1
