### ISSUE TITLE
[Bug] Sponsorbock dialog is unresponsive

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [qnblackcat/uYouPlus#854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [x] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 15.3.1
- Device model: iPad Pro (10.5 inch)
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Trollstore 
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): v17.49.6-2.3~1

### Describe the bug

I don't know if this is an iSponsorblock problem, or uYou+. The issue is, when I go to submit a segment, nothing except the player works. I mean, tapping the segment starts now button doesn't do anything, I can't tap and hold segments, submit segment button doesn't do anything, etc.

Uploading IMG_1734.mp4…

### Steps to reproduce the issue

1. Open the submit segment dialog
2. Tap anything
3. There is no 3rd step

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment]
Try [v18.01.6-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.01.6-2.3.1)

**Comment by ego-lay-atman-bay** [comment]
Thanks, it works!
