### ISSUE TITLE
[Bug] uYou version displays 2.1 instead of 2.3~1

### ISSUE THREAD

**Issue by korboybeats** [qnblackcat/uYouPlus#856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 15.4.1
- Device model: M1 iPad Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): TrollStore
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): 17.49.6_2.3.1

### Describe the bug

uYou version displays 2.1 still instead of 2.3~1.
[
![](https://i.imgur.com/m8ErDgC.jpg)
](url)

### Steps to reproduce the issue

1. Check uYou version.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by dayanch96** [comment]
Its not bug, its just MiRO’s mistake to bump version.

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/issues/853
