### ISSUE TITLE
I already update it to 2.3.1 but why it told me to update again?

### ISSUE THREAD

**Issue by ZentoSLY** [qnblackcat/uYouPlus#859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:14.8.1
- Device model:IPhone XS
- Sideload tool (AltStore, Sideloadly, TrollStore,...):Esign
- The specific version of uYouPlus (**latest** or **newest** is **NOT** a version number!): 2.3.1

### Describe the bug

I already download and install your new update lastest version of uYouPlus 2.3.1 IPa but when I’m opening the app itself told me to update to 2.3.1 again🤦🏻 
![83AA4FDC-9736-477E-BE3C-51ED77A27A9F](https://user-images.githubusercontent.com/122157576/211150160-6d6992bd-4d40-493d-bd44-2a986233f3ee.png)

### Steps to reproduce the issue

1. Fix the download that error failed to move to uYouPlus Album
2. fix the app itself told me to update when I’m already at the lastest version
3. The sound delay when I’m watching on PIP Mode and the picture doesn’t playing correctly 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by TheIronboy** [comment]
same issue here

**Comment by TheLidlMan** [comment]
same here

**Comment by qnblackcat** [comment]
It only ask you once time

**Comment by jerrygergov** [comment]
Hi, any solution here? i have the same issue. Is there any way to update the uYou?
