### ISSUE TITLE
[Enhancement] Speed Gestures

### ISSUE THREAD

**Issue by Serralq** [qnblackcat/uYouPlus#86]
Adding an option to either the top or bottom seeks to change the playback speed. I often listen to any audiobook or podcasts at 2x speed but music at 1x speed so a quick way to change between the two options would be nice. I'm aware that you can push the plus or minus button but given how often I switch between the two, the number of clicks, a small screen (iphone SE 2020), and most importantly accidentally going forwards since it faded out, a seek function would be nice.

**Comment by Serralq** [comment]
Also can anyone show me how to label it with Enhancement? This isn't a question since it's not possible right now and I noticed an older post with the label Enhancement.

**Comment by qnblackcat** [comment]
Since your request is related to uYou, you should open a new request on upstream uYou: https://github.com/MiRO92/uYou-for-YouTube
