### ISSUE TITLE
[Questions] successfully login google acount "with" deleting previous version

### ISSUE THREAD

**Issue by hotdog5785** [qnblackcat/uYouPlus#860]
i use 13 pro , ios16.2

I deleted previous version of uyou+(logged in status), and installed lastest version of uyou+

but no login problem occured. I just clicked blue login button (at the first pop-up page) and now i use my google acount with new version of uyou+. (17.49.6 - 2.3~1)

I used altstore (lastest version)

i don't remeber the previous version, but maybe 17.41.2

**Comment by qnblackcat** [comment]
Good for you then

**Comment by hotdog5785** [comment]
I thought this case can be a clue.... but ok. it's good for me then.
