### ISSUE TITLE
[Questions] uYouPlus still keeps telling me to upgrade my uYou version even after updating to uYouPlus latest version

### ISSUE THREAD

**Issue by eshack94** [qnblackcat/uYouPlus#866]
Hi, I am wondering if I'm doing something wrong while attempting to upgrade.

I just upgraded to the latest version of uYouPlus (which should include uYou v. 2.3-1 according to my understanding). However, within the app, I'm still prompted by uYou to upgrade my version to 2.3-1.

When I open the uYou tab and scroll down, I see that it reports v. 2.1. I am wondering how I can fix this. Am I doing something wrong while attempting the install? 

Would "Removing Extensions" while installing cause this behavior? I usually remove extensions while installing to save on my weekly allowance.

Attached images for reference:
<img src="https://user-images.githubusercontent.com/33649649/211174809-2fdf1580-8306-495e-bcd1-c5cfecdb616a.png" width="300">
<img src="https://user-images.githubusercontent.com/33649649/211174814-1a6c89ad-11cb-4725-9f35-fbe257a157a8.png" width="300">

**Additional info:**
* Using AltStore, installing the IPA manually. 
* non-jailbroken iPhone 13 Pro
* iOS v. 16.2 (20C65)

**Comment by ZentoSLY** [comment]
Same here

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/issues/859

**Comment by eshack94** [comment]
@qnblackcat I believe this was closed when it should not have been. The problem is that uYou is still reporting version 2.1, even after upgrading.

**Comment by eshack94** [comment]
@qnblackcat If I can help with a fix, please let me know.

**Comment by StarVore** [comment]
I am also having this issue when doing a fresh install or an update through both the AltStore link in the README.md as well as directly installed the 2.3(1).IPA file.

**Comment by jerrygergov** [comment]
Hi, any solution here? i have the same issue. Is there any way to update the uYou?

**Comment by yodaluca23** [comment]
> Hi, any solution here? i have the same issue. Is there any way to update the uYou?

Can you not read? Or is it that your just too incredibly lazy to search through all the previous issues? Their have been like 7 of the same ones and 5 of them have the same answer the rest of which they've just been so many that we close with no explanation..

https://github.com/qnblackcat/uYouPlus/issues/880#issuecomment-1381135951
