### ISSUE TITLE
SideStore repo

### ISSUE THREAD

**Issue by dxwil** [qnblackcat/uYouPlus#868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: IPad Air 5
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore
- The specific version of uYouPlus (**latest** or **newest** is **NOT** a version number!):  v17.49.6-2.3~1

### Describe the bug

Would it be possible to make the AltStore repo also work with AltStore forks such as SideStore. Currently when trying to add the repo to SideStore the following error is shown: “The data couldn’t be read because it isn’t in the correct format. The given data was not valid JSON.”

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by yodaluca23** [comment]
I have the repo working with SideStore just fine, for me....

**Comment by dxwil** [comment]
Looks like I needed to add https://qnblackcat.github.io/AltStore/apps.json and not just https://qnblackcat.github.io/AltStore/

Works for me now!
