### ISSUE TITLE
[Bug] Cannot submit segments to Sponsor Block

### ISSUE THREAD

**Issue by TimestaticYT** [qnblackcat/uYouPlus#87]
**Device info:**
- iOS/iPadOS version: 15.3.1
- Device model: iPhone 12
- Sideload tool: AltStore
- Version of uYouPlus: 2.1

**Describe the bug:**
- Cannot submit segments to SpnsorBlock sue to not being able to choose a category

**How to reproduce the bug:**
![385EF62A-BF4A-431E-A25A-CFCDEA14247E](https://user-images.githubusercontent.com/58912623/159368090-bf68a6b2-4b51-4e95-94eb-af03fb4c792c.png)

**Comment by qnblackcat** [comment]
You did it wrong then.
Press and hold (or 3DTouch) on the time segment, then select its category. 
![5012AA45-CA55-4E4A-831F-C7FBAEB8A214](https://user-images.githubusercontent.com/52943116/159400242-ee311ad3-72fc-4820-bf6a-45e4991d0ab0.png)

**Comment by TimestaticYT** [comment]
Ok that’s for the info! I would’ve just expected a dropdown menu as this seems really hidden and unintuitive without knowing
