### ISSUE TITLE
Short download error

### ISSUE THREAD

**Issue by Kynastone** [qnblackcat/uYouPlus#870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:16.2
- Device model: iphone 12 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...):altstore
- The specific version of uYouPlus (**latest** or **newest** is **NOT** a version number!):uYouPlus_17.49.6_2.1

### Describe the bug

I wanted to download a short from youtube and it stays in the downloading section forever not allowing me to move to photos. 
![B73CDE0C-E56C-49A8-A1B5-801BFB92619C](https://user-images.githubusercontent.com/86159418/211225556-98e6f7b9-02ec-4c82-8617-59baa8dcd542.jpeg)

### Steps to reproduce the issue

1. Try to download this short
2. (https://youtube.com/shorts/oF02-9LoPMA?feature=share)
3. 

### Crash log (if the app crashes)

```shell
No
```

### Are you using the newest version of uYouPlus? If not, why?

❌ No, I'll explain at the end of the template

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

I cannot try with the official youtube cause it ehmm cost money xD

i am not using latest version because it came out yesterday and I wouldn’t want to have problem signing in again.

**Comment by qnblackcat** [comment]
Should be fixed in uYou 3.0

**Comment by qnblackcat** [comment]
Fixed in [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)
