### ISSUE TITLE
[Bug] uYou is not updated

### ISSUE THREAD

**Issue by enderdragondan** [qnblackcat/uYouPlus#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version:
- 16.2
- Device model:
- iphone 14 pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...):
- AltStore
- The specific version of uYouPlus (**latest** or **newest** is **NOT** a version number!):
v17.49.6-2.3~1

### Describe the bug

uYou isn’t updated to version 2.3~1 and is instead still on 2.1 even in the updated ipa

### Steps to reproduce the issue

1. open app
2. check uYou version
3. it is 2.1 and not 2.3~1

![91C4852C-F765-40C9-B384-5D2AE33FBEE7](https://user-images.githubusercontent.com/116467379/211226017-92e0afa7-3bbd-430c-b72f-918055cf26a9.jpeg)

![984596FE-0A2F-4E15-9DC1-A38743729FCD](https://user-images.githubusercontent.com/116467379/211226028-c437ff0a-c568-4144-b5ed-51f12fb4e714.jpeg)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

app still works very well but would love to see it updated to latest uYou

**Comment by qnblackcat** [comment]
MiRO forgot to bump the version number inside the tweak. It’s actually v2.3~1
