### ISSUE TITLE
[Request] Update altstore Repo

### ISSUE THREAD

**Issue by Hex34568** [qnblackcat/uYouPlus#873]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###Update your altstore repo It's been 2 days since the uYou 2.3.1 version dropped but in the repository, it is still at uYou (2.1) plz fix the issue coz i wanna update through the repository.

**Comment by yodaluca23** [comment]
https://github.com/qnblackcat/AltStore/issues/9

**Comment by qnblackcat** [comment]
I’ll do it when I have time. Also, you‘re free to open a PR in my AltStore‘s repo
