### ISSUE TITLE
[Bug] Apple Tv not working anymore on the latest version

### ISSUE THREAD

**Issue by MaartenSomay** [qnblackcat/uYouPlus#878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: IOS 16.2
- Device model: IPhone 14 Pro Max
- Sideload tool: SideStore 
- The specific version of uYouPlus (**latest** or **newest** is **NOT** a version number!): 17.49.6_2.3-1

### Describe the bug

When trying to connect to my Apple Tv via AirPlay, I can’t click on my Apple Tv to connect. I did not have this issue before. Maybe because I use SideStore? But that can’t be the case because it is basically AltStore.

### Steps to reproduce the issue

1. Tap on chromecast button
2. Try to connect to a Apple Tv

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by eyeslow** [comment]
Try to use the button to share the entire screen to your AppleTV (from the control center).
As soon as you start to play an YouTube Video it will automatically enter the native AirPlay mode of YouTube itself. Might be a possible workaround, please let us know if it worked.

**Comment by MaartenSomay** [comment]
> Try to use the button to share the entire screen to your AppleTV (from the control center).
> As soon as you start to play an YouTube Video it will automatically enter the native AirPlay mode of YouTube itself. Might be a possible workaround, please let us know if it worked.

Hey, This works thanks! Any idea why the normal way stopped working (via chromecast button)?

**Comment by eyeslow** [comment]
I’m glad this has worked.
Without the debug info no one can tell where the problem lies. There could be different causes, it could be an glitch in YouTube itself, it could be an incompatibility with one of the many tweaks which are included in uYou+ and it could also be an issues which is only present on your specific iPhone model and iOS version.

It will _probably_ be fixed in the next release, and until then you need to use the workaround… :)

**Comment by MaartenSomay** [comment]
> I’m glad this has worked. Without the debug info no one can tell where the problem lies. AirPlay is working just fine on my device using uYou+. There could be different causes, it could be an glitch within YouTube itself, it could be an incompatibility with one of the many tweaks which are included in uYou+ and it could also be an issues which is only present on your specific iPhone model and iOS version.
> 
> It will _probably_ be fixed in the next release, and until then you need to use the workaround… :)

Thanks for the hard work!

**Comment by eyeslow** [comment]
> Thanks for the hard work!

I hope thats meant for @qnblackcat because I'm not in any way connected to uYou+ :)
The bug you described is now appearing on my device as well, looks like an bug on OS level.
Workarounds:
1) Screen Mirroring to AppleTV from ControlCenter
2) Choosing AppleTV as receiver from the Music Widget in ControlCenter or Lockscreen

**Comment by MaartenSomay** [comment]
> > Thanks for the hard work!
> 
> I hope thats meant for @qnblackcat because I'm not in any way connected to uYou+ :) The bug you described is now appearing on my device as well, looks like an bug on OS level. Workarounds:
> 
> 1. Screen Mirroring to AppleTV from ControlCenter
> 2. Choosing AppleTV as receiver from the Music Widget in ControlCenter or Lockscreen


Oh okey! I will reopen the issue. Maybe it will be fixed in the next release then :).
Its weird, once you do the workaround, and try doing it back via the Chromecast button, its works like usual.

**Comment by eyeslow** [comment]
>I will reopen the issue. Maybe it will be fixed in the next release then :). 
As I said it most likely is on OS level, if this is the case then uYou+ is not the problem.
>Its weird, once you do the workaround, and try doing it back via the Chromecast button, its works like usual.
Not for me, the selection view for AirPlay devices is completely bugging out... It registers tapping as swiping motion!😝

**Comment by MaartenSomay** [comment]
> > I will reopen the issue. Maybe it will be fixed in the next release then :).
> 
> As I said it most likely is on OS level, if this is the case then uYou+ is not the problem.
> 
> > Its weird, once you do the workaround, and try doing it back via the Chromecast button, its works like usual.
> 
> Not for me, the selection view for AirPlay devices is completely bugging out... It registers tapping as swiping motion!😝

Damn okay, so its not uyou+ problem, this will probally mean that the bug also occurs on the official youtube app.
