### ISSUE TITLE
[Feature Request] SponsorBlock Chapter Support

### ISSUE THREAD

**Issue by DolphinLaser** [qnblackcat/uYouPlus#879]
Sponsor block now has crowdsourced chapters. From my understanding while this feature is behind a paywall on the official sponsor block addon for browsers, it can be enabled client side or in third party apps.

**Comment by yodaluca23** [comment]
Please make an issue here instead.

https://github.com/Galactic-Dev/iSponsorBlock

**Comment by qnblackcat** [comment]
Answered above
