### ISSUE TITLE
Video Player [Bug] [From Original/Main Version of YouTube 17.09.1) 

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#88]
**Device info:**
- iOS/iPadOS version: 15.4
- Device model: iPad Pro 10.5 (Second Gen)
- Sideload tool (Ex: AltStore, Sideloadly...) AltStore
- Version of uYouPlus: 17.09.1

**Describe the bug:**
- this bug has been on the main youtube app and it's about the video player, it always gets positioned up, it's been on youtube for a few months and youtube hasn't fixed it, if you still don't know what I meant, I meant the Video Player Bar, I hate how it always positions higher.

**Additional context:**
I wish Y'all could add a new module for uYouPlus that stops those issues, may be impossible but love uYouPlus to improve and make the modified YouTube really awesome!

**Comment by qnblackcat** [comment]
IIRC, it is the new UI of YouTube. It‘s not a bug

**Comment by arichorn** [comment]
oh, I didn't know, It kept doing that so I thought it would be one
I did have a suggestion for this. It was an option to disable auto-rotating for iphones but It might be a bad idea
but anyways sorry, i didn't know about a ui change in youtube

**Comment by arichorn** [comment]
Also wait. We’re you talking about the YouTube UI for iPhone?
Lemme show you this. It’s on both YouTube and uYou, I don’t think it would be possible to revert this ever from happening but this is what I meant for the video player bug

![63B5F76E-CC45-43D6-85E2-E5782039CCB2](https://user-images.githubusercontent.com/78001398/167235075-5950eb39-87de-400e-a82a-aa96670972ac.jpeg)
