### ISSUE TITLE
[Bug] Cant update to 2.3

### ISSUE THREAD

**Issue by mightymist3ry** [qnblackcat/uYouPlus#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: Iphone SE2020
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloady
- The specific version of uYouPlus (**latest** or **newest** is **NOT** a version number!): 2.1

### Describe the bug

Im trying to install 2.3 after i previously installed v2.1 but it wont work, when i sideload 2.3 it just auto becomes 2.1? i did the shortcut thing to sign in google

### Steps to reproduce the issue

1. Installed 2.1
2. installed 2.3
3. is still 2.1

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by yodaluca23** [comment]
https://github.com/qnblackcat/uYouPlus/issues/856#issuecomment-1374404324

**Comment by yodaluca23** [comment]
> Seeing the same question over and over drive me nuts
> 
> Have you actually search for the existing issues? I don’t make a tick box just for cosmetics purpose. Next time please DON’T BLINDLY tick that box unless you actually did what you suppose to do

IKR!!
