### ISSUE TITLE
[Bug] YouPiP not showing the fake version when option enabled

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.2
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus: 17.49.6-2.3~1 (this version I use was built by @arichorn)

### Describe the bug

Even though I didn’t put this in YouPiP Repository to not disrupt PoomSmart I wanted to point out a small bug. This has been happening for a while but can’t say which version of YouTube sadly.

YouPiP’s Fake Version Option was intended to modify the app version number, change video player’s buttons and etc. App Version Number shows 17.49.6 or newer based on what version you’re using. It won’t show “16.46.5” as intended.

Also I only wanted to point it out, I checked all the issues to confirm that this wasn’t made as a duplicate.

### Steps to reproduce the issue

1. https://user-images.githubusercontent.com/78001398/212491560-b67eb5bb-da61-4795-ab13-2c1e4fc4edfb.MOV
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

### Additional context

Sure. Just want y’all to know, this bug isn’t really that bad, I was afraid to put this in the YouPiP repository because I was just scared. If this can’t be fixed I can supposely try to fix it if it’s worth it. 👍😭

**Comment by qnblackcat** [comment]
If you think this is an issue of YouPiP, open a new issue on YouPiP's repo.

**Comment by PoomSmart** [comment]
By intention YouPiP will fake the version ONLY when YouTube app makes a request for each video you tap to play to prevent unwanted side effects. If you think this should absolutely be clarified in the description of Fake YouTube version option then create an issue in YouPiP repo.
