### ISSUE TITLE
[Questions] How to change the language of uYouPlus?

### ISSUE THREAD

**Issue by kz0612** [qnblackcat/uYouPlus#886]
## Have you read the FAQ? Any questions that have been answered on the FAQ page will be closed without any explanation!

https://github.com/qnblackcat/uYouPlus/wiki/FAQ

###

How to change the language of uYouPlus?

**Comment by qnblackcat** [comment]
Google is your friend 🤷‍♂️

![AC1EAD98-2175-473D-A228-0EA993B32A5D](https://user-images.githubusercontent.com/52943116/212522025-7735d1be-4225-41aa-b93b-0aae923b85b0.png)
