### ISSUE TITLE
[Bug] ¨Installation failed¨

### ISSUE THREAD

**Issue by FLOOGETTA987** [qnblackcat/uYouPlus#887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 12.5.6
- Device model: A1549
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest** or **newest** is **NOT** a version number!): uYouPlus_17.39.5_2.1, uYouPlus_17.49.6_2.3.1, uYouPlus_17.37.3_2.1

### Describe the bug

Installation failed: 0 AppexBundleUnknownExtensionPointIdentifier (Appex bundle at /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.k1TjqE/extracted/Payload/YouTube.app/PlugIns/OpenYoutubeSafariExtension.appex with id com.google.ios.youtube++.OpenYoutube.Extension specifies a value (com.apple.Safari.web-extension) for the NSExtensionPointIdentifier key in the NSExtension dictionary in its Info.plist that does not correspond to a known extension point.)
Same message, 3 different versions
![Captura de pantalla 2023-01-15 001509](https://user-images.githubusercontent.com/35633612/212524073-aaecb610-6c73-48c7-b451-5ed1c79c5dfc.png)

### Steps to reproduce the issue

>Downloads any of the 3 versions already mentioned
>Connects iphone to pc
>Uses Sideloadly (Apple-Id or normal install, it doesn't matter)
>Selects any of the 3 versions that had been previously downloaded
>¨Start¨
>🗿 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by qnblackcat** [comment]
Looks like an issue of Sideloadly. Try AltStore. This I can’t fix
