### ISSUE TITLE
[Questions] Any link opens in Safari.

### ISSUE THREAD

**Issue by uivy17** [qnblackcat/uYouPlus#889]
When someone is shares video/i see a link in browser, it’s switching to Safari. Idk why, somewhen I downloaded via altstore (november 2022) and it worked — all links have to open in app, but then I miss altstore time (7d) and app is dead. Is there a way to fix this issue?

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/wiki/FAQ
