### ISSUE TITLE
[Bug] does not play video at the set quality

### ISSUE THREAD

**Issue by ev0tto** [qnblackcat/uYouPlus#89]
**Device info:**
- iOS/iPadOS version: iOS15.4 (19E241)
- Device model: iPhoneSE Gen2 
- Sideload tool: signulous
- Version of uYouPlus: v17.09.1-2.1

**Describe the bug:**
- Video does not play at the set quality. Video is played back in "Auto" mode.

**How to reproduce the bug:**
- Set the desired Video quality and play the video.

**Crash log (if possible):**
N/A

**Additional context:**
N/A

**Comment by qnblackcat** [comment]
Did you enable Lgacy PiP?

**Comment by ev0tto** [comment]
> Did you enable Lgacy PiP?

yeah, I enabled that setting.
Resolved! Thank you very much.
