### ISSUE TITLE
[Questions] uyuo+ 2.3.1 ipa keeps installing 2.1

### ISSUE THREAD

**Issue by hetzjagd** [qnblackcat/uYouPlus#892]
I had version 2.1 of uyou+ sideloaded via altstore on my phone (iphone 11 pro max ios 15.1).  It prompted me that 2.3.1 is available.  I downloaded the 2.3.1 .ipa onto my phone and I can see it says 2.3.1 in the file name.  Whenever I sideload it and then open up the Youtube app and go to the uyou tab it still shows 2.1 as the installed version and the "install the latest 2.3.1 version" prompt still appears every time I open the Youtube app.  I have read the FAQ and the installation guide and I'm not sure what I could be doing wrong.

**Comment by yodaluca23** [comment]
https://github.com/qnblackcat/uYouPlus/issues/880#issuecomment-1381135951

**Comment by arichorn** [comment]
This issue has been frequent huh. I’m gonna try to bump the version number if I fail then I just fail on implementing a small change.
