### ISSUE TITLE
[Feature Request] Option to Disable YouTube Shorts from the Home Page

### ISSUE THREAD

**Issue by 0x8ff** [qnblackcat/uYouPlus#895]
I really don't like YouTube Shorts.

**Comment by yodaluca23** [comment]
Their is already the option,
uYou Settings> Other Settings> Remove Shorts Section in YT Home.

And if you want to replace the Shorts tab at the bottom you can with the explore tab, 
uYou+ Settings> Miscellaneous> Replace Shorts tab with Explore tab

**Comment by 0x8ff** [comment]
@yodaluca23 i see, tysm
