### ISSUE TITLE
[Bug] Video watch history not saving

### ISSUE THREAD

**Issue by dwojc6** [qnblackcat/uYouPlus#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: 16.1.2
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): ESign
- The specific version of uYouPlus (**latest** or **newest** is **NOT** a version number!): 2.3.1 on 17.49.6

### Describe the bug

After watching a video, watch history does not save. 

### Steps to reproduce the issue

1.  Watch video
2. Check watch history 
3. Profit???

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by Hazem42** [comment]
Can confirm, this is happening to me too

**Comment by qnblackcat** [comment]
You read the FAQ, didnt you? @dwojc6

**Comment by qnblackcat** [comment]
And I'm sure you did search all existing issues as well?

![1D94FB95-0531-456F-9948-8591D5D08DB5](https://user-images.githubusercontent.com/52943116/213078960-5db85d57-aca9-410d-abc5-4b747e631163.png)

**Comment by dwojc6** [comment]
Added s.youtube.com to my allow filter in AdGuard Home and it syncs now.

**Comment by idolize** [comment]
I've turned off all ad blocking, no custom DNS or VPN on my phone and it still doesn't save any view history
