### ISSUE TITLE
[Questions]

### ISSUE THREAD

**Issue by Dj3ng1s** [qnblackcat/uYouPlus#899]
when you open it.  then it still says to update to uYou+ 2.3.  so it still says 2.1 when I install it![image](https://user-images.githubusercontent.com/89269779/213113686-42274ae6-dcc8-4865-ab51-deb825db0add.png)![image](https://user-images.githubusercontent.com/89269779/213113748-680441b5-819e-4086-98e7-dc9622e66e7f.png)

**Comment by yodaluca23** [comment]
https://github.com/qnblackcat/uYouPlus/issues/880#issuecomment-1381135951
