### ISSUE TITLE
Cannot install with Filza ? Altstore works perfectly

### ISSUE THREAD

**Issue by x4080** [qnblackcat/uYouPlus#9]
Hi, I tried install it with filza and just close immediately, but using altstore works perfectly

Is there any steps to do first before using filza ?

Thanks

**Comment by qnblackcat** [comment]
This IPA was built for **non-jb users**. Since you're jailbroken, please get YouTube from AppStore and install tweaks used in in uYou+ from Cydia.

**Comment by x4080** [comment]
@qnblackcat Thanks
