### ISSUE TITLE
[Bug] Fullscreen to the right completely inoperative in v18.01.6-2.3.1

### ISSUE THREAD

**Issue by tevyisertyin** [qnblackcat/uYouPlus#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS 16.2
- Device model: iPhone XS Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.01.6-2.3.1

### Describe the bug

This is NOT a duplicate of #453, where it was still possible to rotate the video to the right by pressing the button enough times.

In v18.01.6-2.3.1, the "Fullscreen to the Right" function is completely inoperative. Pressing the on-screen button does not rotate the video at all, even when rotation lock is off.

### Steps to reproduce the issue

1. Launch uYouPlus
2. Make sure Video Controls Overlay > uYou Fullscreen to The Right is enabled
3. Restart uYouPlus
4. Watch any video
5. Press the Fullscreen to the right button. Video plays in landscape mode to the left
7. Press the Fullscreen to the right button. Video remains in landscape mode to the left.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by tevyisertyin** [comment]
Just to update, this problem still remains in 18.07.5-2.3.1.

**Comment by mtp-24** [comment]
I'm encountering the same issue.

But I also just noticed that even in uYouPlus 18.07.4-2.3~1, if you go to uYou's settings page it still says "uYou 2.1" instead of 2.3~1. Can you confirm on your app if that is the case as well?

**Comment by tevyisertyin** [comment]
> I'm encountering the same issue. I wonder if this is an uYouPlus or uYou issue.
> 
> But I also just noticed that even in uYouPlus 18.07.4-2.3-1, if you go to uYou's settings page it still says "uYou 2.1" instead of 2.3-1. Can you confirm on your app if that is the case as well?

Huh, you're right, it does say "uYou 2.1", and when I tap "Check for updates" it tells me that 2.3-1 is available. How strange!

**Comment by tevyisertyin** [comment]
This issue still persists in v18.08.1-2.3.1 (and the uYou page still says "uYou 2.1" at the bottom of its settings page)

**Comment by qnblackcat** [comment]
Please try [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)

**Comment by mtp-24** [comment]
> Please try [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)

Unfortunately the bug is still present in 18.15.1-3.0

**Comment by qnblackcat** [comment]
please update to the latest version (19.02+)
