### ISSUE TITLE
[Bug] The "manually skip sponsor" (SponsorBlock) popup won't disappear

### ISSUE THREAD

**Issue by Oblivious02** [qnblackcat/uYouPlus#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS 16
- Device model: iPhone 13 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.01.6-2.3.1

### Describe the bug

To my understanding, the popup should disappear after the specified duration in the "Set How Long Skip Will Appear:" which the default of it is 3 seconds, but that doesn't happen; even when changing this value to any other, it won't disappear.

So, if I wanted to watch a specific sponsor for example, the popup will take like 50% of the video.

Please give an option/gesture to dismiss it while watching a video other than the timer, thanks.
![photo_2023-01-21_00-14-01](https://user-images.githubusercontent.com/29382999/213815342-6b4fc1d3-4904-4b6c-bfa7-b458541a7588.jpg)

### Steps to reproduce the issue

Open a video which has a sponsor that you want to watch

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by Oblivious02** [comment]
Still happens after latest update

**Comment by dayanch96** [comment]
You want it to be like this?

![CAFD7637-3CF0-4AAC-B3A0-48C2CA86E26D](https://github.com/qnblackcat/uYouPlus/assets/38832025/34ddbf64-6fbf-4397-99fa-281cec3792f5)

**Comment by NetAnarchy** [comment]
@dayanch96 
Yeah, it would be better than nothing😊
I dunno why but iSB’s Skip (this notice) feature is out of service, so this would be great idea for its replacement honestly🙂

**Comment by Oblivious02** [comment]
> You want it to be like this?
> 
> ![CAFD7637-3CF0-4AAC-B3A0-48C2CA86E26D](https://user-images.githubusercontent.com/38832025/243009696-34ddbf64-6fbf-4397-99fa-281cec3792f5.png)

Sorry I just saw this.
Yeah that’s perfect!
Also fixing the timer so that it disappears after a specific time is even better.

**Comment by dayanch96** [comment]
> > You want it to be like this?
> > ![CAFD7637-3CF0-4AAC-B3A0-48C2CA86E26D](https://user-images.githubusercontent.com/38832025/243009696-34ddbf64-6fbf-4397-99fa-281cec3792f5.png)
> 
> Sorry I just saw this. Yeah that’s perfect! Also fixing the timer so that it disappears after a specific time is even better.

if you dont touch, it will disappear with sponsor section

**Comment by NetAnarchy** [comment]
> @dayanch96
> Yeah, it would be better than nothing😊
> I dunno why but iSB’s Skip (this notice) feature is out of service, so this would be great idea for its replacement honestly🙂

@dayanch96 
I’m sorry for my rude reply, I couldn’t confirm it’s fake or not immediately, so we’ll appreciate your work so much!😊
