### ISSUE TITLE
[feature request] Add import/export for settings preference 

### ISSUE THREAD

**Issue by Tomasruscelli** [qnblackcat/uYouPlus#906]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

With the problem of sideloading ipa thru Scarlet/altstore/sidestore etc. It would be awsome to have the possibility to import the previous settings of the app, since it require to unistall uyou+ and reinstall in order to renew the certificates,  since refresh  fail to the absence of certain extension

**Comment by ego-lay-atman-bay** [comment]
I've used altstore for a while, and I haven't needed to uninstall uyou+. You just need to install the update without uninstalling the app.

**Comment by ego-lay-atman-bay** [comment]
Even though the issue they're having is pretty easy to solve, I do agree with their suggestion. It would be nice to be able to import and export settings, especially the A/B settings (I know it's possible to export A/B settings, but you can't import them).

**Comment by maxexcloo** [comment]
Agreed on this - there’s just so many settings to configure and sometimes things get out of whack (especially on multiple devices), would be a neat feature!
