### ISSUE TITLE
[Bug] error "unable to retrive channel list"

### ISSUE THREAD

**Issue by johnwatson122** [qnblackcat/uYouPlus#91]
### Device info
- iOS/iPadOS version: 
- Device model:
- Sideload tool (Ex: AltStore, Sideloadly...)
- Version of uYouPlus: 

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

### Additional context:
After signing in, an error "unable to retrive channel list" appears on the account name. This occurs for all of my google accounts. This is not the case for the official youtube app.

**Comment by qnblackcat** [comment]
You must provide more info!

**Comment by qnblackcat** [comment]
@robpneu have you tried AltStore/Sideloadly?

**Comment by robpneu** [comment]
I've used AltStore previously but this was my first attempt using iOS App Signer and my first attempt with this version of uYou+ (I had a previous one installed with AltStore; I don't recall which version though I never saw this issue in that circumstance)

**Comment by tathung095** [comment]
> I've used AltStore previously but this was my first attempt using iOS App Signer and my first attempt with this version of uYou+ (I had a previous one installed with AltStore; I don't recall which version though I never saw this issue in that circumstance). I can attempt with AltStore and report back.

This issue happens when we use iOS App Signer, please try to install it by AltStore. 
@qnblackcat Hope you can fix this issue.

**Comment by robpneu** [comment]
I was unable to test it using AltStore (the computer I have it running on, an old windows laptop, refuses to recognize one of my devices, which is part of why I moved away from it in the first place), however I tried the latest release (uYouPlus_17.14.2_2.1) using iOS App Signer, same method as I did before (signed once, loaded to iPhone and iPad), and it's now working on both devices. I don't know what could have made the difference.

**Comment by qnblackcat** [comment]
For those who use paid signing service and got this issue: please contact your signing service and ask them _how to keep the original app's bundle ID_ when sideloading. 

This issue rarely happens with free AltStore/Sideloadly user.

**Comment by LeonManolo** [comment]
Im having the same issue(with a paid developer account) any way to fix that?
