### ISSUE TITLE
Even with the option on or not, the notch keeps eating content when fullscreen is disabled.

### ISSUE THREAD

**Issue by NukeThief** [qnblackcat/uYouPlus#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.2
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.01.6-2.3.1

### Describe the bug

With the option to block the notch from eating videos or not, the notch in uYouPlus keeps eating videos.
![37A00A66-3BDD-4912-AC80-9C285F35206A](https://user-images.githubusercontent.com/81801547/215047494-df37d932-3560-428e-a783-f0839f2c94c0.jpeg)

### Steps to reproduce the issue

1. Maybe enable the eating block(?)
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
that’s not how the tweak (DontEatMyContent) works

**Comment by NukeThief** [comment]
Ok, it may not be a part of that, but the issue still remains! Whatdoido

**Comment by qnblackcat** [comment]
https://www.reddit.com/r/youtube/comments/yk64q9/iphone_14_pro_youtube_bug/iuvvrsw/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

https://www.reddit.com/r/youtube/comments/10b9p80/how_to_stop_youtube_from_playing_over_the_island/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by NukeThief** [comment]
That is really suprising, it dosen't happen on normal YT for me. 🤔

**Comment by NukeThief** [comment]
Sometimes, restarting the device is enough, or turning off uYouPlus and not using it for some minutes. This is.... uhh weird.
