### ISSUE TITLE
[Bug] splash screen not following device theme

### ISSUE THREAD

**Issue by miIktoast** [qnblackcat/uYouPlus#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS version: 16.3/16.2
- Device model: 14 pro max
- Sideload tool: AltStore
- The specific version of uYouPlus: 18.01.6-2.3.1

### Describe the bug

Splash screen upon opening app is supposed to be either gray or white depending on device theme. My device only shows the white splash screen whether or not device is set to dark mode.

This issue seems to be fairly unique to my phone as it persists across multiple uy+ and AltStore installs but doesn’t appear on my iPad. 

### Steps to reproduce the issue

1. Install uy+ through altstore
2. Open uy+
3. Make sure device is set up dark mode
4. White splash screen

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
I can't fix this, sorry
