### ISSUE TITLE
[Questions] Option to hide Sponsorblock

### ISSUE THREAD

**Issue by yusuf0142** [qnblackcat/uYouPlus#915]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Could you add an option to hide Sponsorblock icon in the navigation bar?

**Comment by arichorn** [comment]
Hold on I’ll do a Pull Request for this change since I’ll just learned how to hide the SponsorBlock Button thanks to dayanch96.

**Comment by arichorn** [comment]
You know what just use this version. https://github.com/arichorn/uYouPlusExtra/releases/tag/v18.04.3-2.3.1
uYouPlusExtra adds the ability to hide iSponsorBlock Button and the ability to hide the Notification Button
and the ability to do other stuff like changing the ui with the LowContrastMode tweak including color customization below the tweak. and there’s more. Most of the additions I added were denied by qn for some reason but hey hope this helps!

**Comment by yusuf0142** [comment]
thanks a lot! really helpfull
