### ISSUE TITLE
[Questions] How to actually save a gif from a community post?

### ISSUE THREAD

**Issue by AbsurdIdealist** [qnblackcat/uYouPlus#916]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

When saving a gif from a community post, the file saved is not actually a gif file but rather a .webp file and thus is not animate. Is there anyway to fix this?

**Comment by arichorn** [comment]
> When saving a gif from a community post, the file saved is not actually a gif file but rather a .webp file and thus is not animate. Is there anyway to fix this?
Hmmm no. But BandarHL might be able to do that but don’t know if I’m right or wrong. Saving pngs/gifs in community posts is a unique idea.

**Comment by AbsurdIdealist** [comment]
Hmmm no. Not my point, you can save images from community posts but whenever I try to save a Gif it saves as a .webp file

Check this image: https://imgur.com/a/HUnD9mt

**Comment by arichorn** [comment]
Oh you were talking about uYou. I’m guessing this is a uYou issue I suppose.

**Comment by qnblackcat** [comment]
You could convert webp file to gif using this https://cloudconvert.com/webp-to-gif
