### ISSUE TITLE
[QUESTION] YouTube background activity drains battery 

### ISSUE THREAD

**Issue by craftgeil** [qnblackcat/uYouPlus#918]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Hi,
So this morning, the official YouTube App drained my battery overnight (with charger plugged in) and I started the day with like 57% battery. (Video attachted (its the now deleted app))

Some info I can give:
- I have the official YouTube App installed only to receive notifications
- It happened for the third time or so over a month (every time it does this I reinstall YouTube and then it works for some time again without background activity)
- I have turned off the background activity for YouTube (Screenshot) and the app closed, but it still happens
- The same thing also happened with Google Drive some time ago

So my questions is if anybody knows why this happens and how to solve it.
I do not know if it has anything to do with uYou+, but I did not notice this behavior before I installed uYou+.
I also do not know where to ask except here, so if I am completely wrong it would be nice to know where to ask.

![DDC51E8D-B521-4089-BD40-C1F5838D7548](https://user-images.githubusercontent.com/80261988/215495514-e0b28c7b-e904-4e15-ae2c-01370a28937f.png)

https://user-images.githubusercontent.com/80261988/215495532-b52454f3-872d-4fec-8c06-312c4bfc8e40.MOV

**Comment by qnblackcat** [comment]
Sorry but I don’t think I can fix this. I suggest you use other alternatives to uYouPlus for now

**Comment by craftgeil** [comment]
I do not think uYouPlus is the problem, uYouPlus never drained the battery.
(uYouPlus does not interact with the official YouTube App at all (they are seperate, individual apps), or?)

It is the official YouTube App which drains my battery sometimes even when it is closed and background activity is off.
I have not found anything on the internet about this problem for now.

So I guess its some kind of problem with the offical App because like I mentioned, I think I had the same issue with Google Drive...
