### ISSUE TITLE
[Questions] Replace with your question

### ISSUE THREAD

**Issue by greifriday** [qnblackcat/uYouPlus#919]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Cant logon to uYou, even with using #904 method.
Any other way to log in?

**Comment by qnblackcat** [comment]
No, sorry
