### ISSUE TITLE
Crash after launch iPhone 14 Max Pro

### ISSUE THREAD

**Issue by mr-utilman** [qnblackcat/uYouPlus#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.3
- Device model: Iphone 14 Pro Max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore 1.4
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 16.42.3

### Describe the bug

Allways crashes after start

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
Please update to the latest version https://github.com/qnblackcat/uYouPlus/releases/latest

**Comment by arichorn** [comment]
> * The specific version of uYouPlus (**latest or newest is NOT a version number!**): 16.42.3

iPhone 14 Pro Model’s are NOT COMPATIBLE with this version. If this version is from **uYouPlusExtra** please update to the newest version

**Comment by mr-utilman** [comment]
When i use the newest version and try to launch the app just crashes immidatly..

**Comment by arichorn** [comment]
Hmm. Have you tried deleting the app’s data in Altstore. When it happens to me, I completely remove the whole app and install it again, it may not work for you but it did for me.
