### ISSUE TITLE
[Suggestion] Replace the vanilla YouTube download button with uYou download

### ISSUE THREAD

**Issue by DelofJ** [qnblackcat/uYouPlus#923]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Instead of having another button on the video to download the video with uYou downloads, it would be cool if clicking on the vanilla download button made uYou downloads (uYou or uYouLocal) appear

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/issues/876
