### ISSUE TITLE
Crashes on iOS 12.1, Why the dev does not mentioned supported iOS versions?

### ISSUE THREAD

**Issue by hosadokha** [qnblackcat/uYouPlus#93]
I tried both uyouplus version 16 and 17 and they both crash on start...
Did I waste my time and energy because dive didnt mention supported iOS versions?

**Comment by qnblackcat** [comment]
uYouPlus does not support iOS 12. You can try CercubePlus (Legacy): https://github.com/qnblackcat/CercubePlus/tree/iOS-12

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
@qnblackcat it just happened the same to me. It would be nice to add a disclaimer about this issue in the README, and redirect anyone with an iOS 12 device to alternatives (such as what you mentioned in your previous comment).

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus#download

> uYouPlus (or you can call it uYou+) requires iOS & iPadOS 13.0 or later. The latest version of uYouPlus can be found in the [Release tab](https://github.com/qnblackcat/uYouPlus/releases).

**Comment by qnblackcat** [comment]
@orphee-celui-qui-ne-sait-rien 
https://github.com/qnblackcat/uYouPlus#download

> uYouPlus (or you can call it uYou+) requires iOS & iPadOS 13.0 or later. The latest version of uYouPlus can be found in the [Release tab](https://github.com/qnblackcat/uYouPlus/releases).

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
Oh! I'm sorry I didn't see that...
