### ISSUE TITLE
[Bug] I can't install uyou after the altstore update 

### ISSUE THREAD

**Issue by Roll-Penut** [qnblackcat/uYouPlus#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.3
- Device model: iPhone 14 pro max
- Sideload tool (AltStore, Sideloadly, TrollStore,...): altstore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.01.6_2.3.1

### Describe the bug

It tries to install the app and gets like 99% complete and just stalls there

### Steps to reproduce the issue

1. Open altstore
2. Hit the "+" symbol on top
3. Open the app ipa

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

It's the latest version I can find but the app keeps telling me there's an update to it but the link it brings me to is an older version so idk. Also that older version doesn't work on ios 16

**Comment by story1234** [comment]
I think I have the same.  I refresh using Altstore and uYouPlus is "no longer installed".  I updated Altstore using a Mac. When I try installing uYou+ again, it doesn't install or update. Instead it install the IPA manually, keep extension and when it's all said and done, it's still on v2.1. 

I have the same problem with iPad and iPhone 11 Pro. iOS 15 on both.

**Comment by qnblackcat** [comment]
Try to remove AltStore and reinstall it. If nothing change, try other sideload tool
