### ISSUE TITLE
[Bug] Playback controls appear in a video from playlist when disabled

### ISSUE THREAD

**Issue by ShadowRoi** [qnblackcat/uYouPlus#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version:
16.2
- Device model:
iPhone 13 Pro
- Sideload tool
SideStore 0.1.1
-The specific version of uYouPlus (**latest or newest is NOT a version number!**):
18.01.6-2.3~1

### Describe the bug

Basically when playing a video from a playlist like “Music” that I have the video controls like Skip to next or previous video still appear when they are turned off in the settings 

### Steps to reproduce the issue

1. Turn on “Hide Previous and Next button”
2. Play a video from a playlist that u have and they will appear 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/issues/804

Did I answer you before?

**Comment by ShadowRoi** [comment]
@qnblackcat Omg Jesus Christ sorry. It seems I have amnesia and I didn’t know
