### ISSUE TITLE
[Bug] App crashes on startup

### ISSUE THREAD

**Issue by ObamaGaming45** [qnblackcat/uYouPlus#94]
### Device info
- iOS/iPadOS version: 14.8
- Device model: iPhone XR
- Sideload tool (Ex: AltStore, Sideloadly...) Filza
- Version of uYouPlus: 17.12.5_2.1

### Describe the bug

On startup, the app crashes instantly no matter the sideload method.

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

By opening the app

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

{"app_name":"YouTube","timestamp":"2022-04-02 18:01:21.00 -0400","app_version":"17.12.5","slice_uuid":"653bb4c4-8ec8-3e75-ae96-6df958f3d6ca","adam_id":"0","build_version":"17.12.5","platform":2,"bundleID":"com.google.ios.youtube","share_with_app_devs":0,"is_first_party":0,"etl_key":"3","bug_type":"309","os_version":"iPhone OS 14.8 (18H17)","incident_id":"2C27B341-098B-4386-88BE-36256F6A9E02","name":"YouTube"}
{
  "uptime" : 400000,
  "procLaunch" : "2022-04-02 18:01:20.6312 -0400",
  "procRole" : "Foreground",
  "version" : 2,
  "exception" : {
    "type" : "EXC_CRASH",
    "signal" : "SIGABRT",
    "codes" : "0x0000000000000000, 0x0000000000000000"
  },
  "userID" : 501,
  "modelCode" : "iPhone11,8",
  "coalitionID" : 891,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 14.8",
    "releaseType" : "User",
    "build" : "18H17"
  },
  "captureTime" : "2022-04-02 18:01:20.6768 -0400",
  "incident" : "2C27B341-098B-4386-88BE-36256F6A9E02",
  "pid" : 33307,
  "cpuType" : "ARM-64",
  "procName" : "YouTube",
  "procPath" : "\/Volumes\/VOLUME\/*\/YouTube.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"17.12.5","CFBundleVersion":"17.12.5","CFBundleIdentifier":"com.google.ios.youtube","DTAppStoreToolsBuild":"13E114"},
  "storeInfo" : {"applicationType":"User","itemID":"0","deviceIdentifierForVendor":"150E9F9B-AA35-4D42-942B-99AEF4D280E9"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.google.ios.youtube",
  "crashReporterKey" : "de79943f3b830c6789df21b79bc3e2beeebcef23",
  "basebandVersion" : "3.05.00",
  "isCorpse" : 1,
  "termination" : {"flags":518,"code":5,"namespace":"DYLD","indicator":"Code Signature","reasons":["Library not loaded: @rpath\/CydiaSubstrate.framework\/CydiaSubstrate","Referenced from: \/private\/var\/containers\/Bundle\/Application\/3C5B8BB7-0547-4723-B648-3FD05040EF01\/YouTube.app\/Frameworks\/uYouPlus.dylib","Reason: no suitable image found.  Did find:","\/private\/var\/containers\/Bundle\/Application\/3C5B8BB7-0547-4723-B648-3FD05040EF01\/YouTube.app\/Frameworks\/CydiaSubstrate.framework\/CydiaSubstrate: code signature invalid for '\/private\/var\/containers\/Bundle\/Application\/3C5B8BB7-0547-4723-B648-3FD05040EF01\/YouTube.app\/Frameworks\/CydiaSubstrate.framework\/CydiaSubstrate'"]},
  "asi" : {"dyld":[]},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":2893124,"threadState":{"x":[{"value":6},{"value":5},{"value":6126889728},{"value":185},{"value":6126888704},{"value":0},{"value":0},{"value":0},{"value":32},{"value":9},{"value":1},{"value":7511945216},{"value":4359065376},{"value":4359520256},{"value":99},{"value":6126854480},{"value":521},{"value":4358845576},{"value":0},{"value":0},{"value":6126888704},{"value":185},{"value":6126889728},{"value":5},{"value":6},{"value":4359014064},{"value":4359012352},{"value":6126893088},{"value":4359012352}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4358904456},"cpsr":{"value":0},"fp":{"value":6126888656},"sp":{"value":6126888592},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4358871112},"far":{"value":4358242304}},"frames":[{"imageOffset":366664,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":400008,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":400060,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":21264,"symbol":"dyld::halt(char const*)","symbolLocation":652,"imageIndex":0},{"imageOffset":35380,"symbol":"dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*)","symbolLocation":7820,"imageIndex":0},{"imageOffset":4696,"symbol":"dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*)","symbolLocation":476,"imageIndex":0},{"imageOffset":4152,"symbol":"_dyld_start","symbolLocation":56,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4358504448,
    "size" : 475136,
    "uuid" : "555bd852-5237-3f69-a23c-d73dab1c5191",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=807.7M resident=0K(0%) swapped_out_or_unallocated=807.7M(100%)\nWritable regions: Total=12.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                         16K        1 \nStack                             1008K        1 \nVM_ALLOCATE                        1.0G        2 \n__AUTH                            17.2M      441 \n__AUTH_CONST                      31.0M      580 \n__DATA                            65.7M      581 \n__DATA_CONST                      25.9M      583 \n__DATA_DIRTY                      2418K      503 \n__ETC                              112K        1 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       167.6M       13 \n__OBJC_CONST                      5956K      420 \n__OBJC_RO                         82.5M        1 \n__OBJC_RW                         2960K        1 \n__TEXT                           640.1M      602 \n__UNICODE                          588K        1 \n===========                     =======  ======= \nTOTAL                              2.0G     3732 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "reportNotes" : [
  "Failed to extract dyld error info: The size of the data is not what is expected"
]

**Comment by qnblackcat** [comment]
uYou+ is made for non-jailbreak user. If you‘re jailbroken, then install all the tweaks in uYou+ from Cydia

**Comment by Proaxel** [comment]
@ObamaGaming45 I have found that if you are completely outside of the jailbroken state, the app will work fine. It has to be completely out of the jailbroken state, not even safe mode allows the app to launch.

I too am jailbroken but I use checkra1n so if my battery runs out while I'm in the field the jailbreak tweaks will not work until I                                                                                                                                                  return to my PC. This is why I would like to install this to ensure that I can still have the benefits of the tweaks until then. I did have that same problem where it crashes on the splash screen regardless if AltStore or Sideloadly is used. However I then tried rebooting my phone so it is outside of the jailbroken state, and once I did the app ran fine. 

I did also find that AltStore allows you to install uYouPlus alongside the normal app from the App Store, so if you are jailbroken you can just use the normal app. With this, as long as you keep uYouPlus signed you can always have access to ad-free YouTube no matter what jailbreak state you are in. :)
