### ISSUE TITLE
[Questions] Why is the logo for the altstore repo version not the normal youtube logo?

### ISSUE THREAD

**Issue by nmcc1212** [qnblackcat/uYouPlus#942]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Why is the logo for the app found in the altstore repo version not the normal youtube logo but instead a similar but different logo? Whereas installing from the .ipa gives the normal youtube logo for the app

**Comment by nmcc1212** [comment]
Closing as when installed the app icon returns to normal

**Comment by yodaluca23** [comment]
Because that's the uYou+ logo, whenever you install it through
Altstore or SideStore however, it will install with the normal YouTube icon…
