### ISSUE TITLE
Break Timer?

### ISSUE THREAD

**Issue by RssolYeet** [qnblackcat/uYouPlus#946]
Don't see an option to enable break Timer anymore? Only see option to enable sleep reminder? Did it get removed?

Thanks.

**Comment by yodaluca23** [comment]
It's still their for me...

![image](https://user-images.githubusercontent.com/67206487/218344846-10944fbc-4424-4374-ba96-ceeca1af963b.png)

**Comment by RssolYeet** [comment]
Is there something I have to click to enable it? This is all I see. 
![46AB120B-824D-4870-861E-E3BEA1E44527](https://user-images.githubusercontent.com/114891431/218345085-6e11639a-6dfd-430e-b18c-c45bf450f3d5.png)

**Comment by RssolYeet** [comment]
...so it this a bug???

**Comment by arichorn** [comment]
> ...so it this a bug???

Most likely a bug. YouTube broke Autoplay so I can’t be surprised.

**Comment by yodaluca23** [comment]
I think you need to turn on A/B...
