### ISSUE TITLE
youtube is not available

### ISSUE THREAD

**Issue by hieuchi04** [qnblackcat/uYouPlus#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.1.2
- Device model: iphone 12
- Sideload tool (AltStore, Sideloadly, TrollStore,...):Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**):newest

### Describe the bug

youtube is not available
i can't open youtbe. when opening youtube it says youtube is not available

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by yodaluca23** [comment]
Please read the [FAQs](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) before making a new issue..

https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-i-cant-open-uyouplus-after-a-week-altstoresideloadly-it-said-youtube-is-no-longer-available

**Comment by cameroncc** [comment]
Did this happen after trying to refresh/update the app? I've had that happen to me and the only thing I found that worked was to delete the app and re-sideload it

**Comment by cameroncc** [comment]
This sometimes happens to me after updating the app (so definitely not expired because I just installed it). The only solution I found is to delete and reinstall. See #624, others commented on the same problem there

**Comment by qnblackcat** [comment]
This is not an issue of uYou+, check your sideload tool
