### ISSUE TITLE
Disable resume to Shorts not working

### ISSUE THREAD

**Issue by pocketrocketR** [qnblackcat/uYouPlus#951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.3
- Device model: iPhone 11
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.01.6-2.3~1

### Describe the bug

Disable resume to Shorts does not work

### Steps to reproduce the issue

1. User>Settings>uYouPlus>Shorts Controls Overlay Options> Enable “Disable resume to Shorts”
2. Close YouTube app while watching Shorts
3. Open YouTube app
4. Shorts automatically play on launch

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
I’ll see what I can do

**Comment by pocketrocketR** [comment]
@qnblackcat I downloaded the IPA file and sideloaded it with AltStore but this feature still does not work. Am I doing something wrong? Thank you!

**Comment by yodaluca23** [comment]
> @qnblackcat I downloaded the IPA file and sideloaded it with AltStore but this feature still does not work. Am I doing something wrong? Thank you!

Did you build it from the latest commit?

**Comment by pocketrocketR** [comment]
> > @qnblackcat I downloaded the IPA file and sideloaded it with AltStore but this feature still does not work. Am I doing something wrong? Thank you!
> 
> 
> 
> Did you build it from the latest commit?

No. Could you explain how to do that please? Thank you!

**Comment by yodaluca23** [comment]
> > Did you build it from the latest commit?
> 
> No. Could you explain how to do that please? Thank you!

Well, If I were you, I would just wait for the next release of uYou+, in which this fixture will be implemented, or you can follow the wiki guide [here](https://github.com/qnblackcat/uYouPlus/wiki/Building), on how to build it...

**Comment by pocketrocketR** [comment]
> > > Did you build it from the latest commit?
> 
> > 
> 
> > No. Could you explain how to do that please? Thank you!
> 
> 
> 
> Well, If I were you, I would just wait for the next release of uYou+, in which this fixture will be implemented, or you can follow the wiki guide [here](https://github.com/qnblackcat/uYouPlus/wiki/Building), on how to build it...

Got it thank you!
