### ISSUE TITLE
[Questions] Replace with your question

### ISSUE THREAD

**Issue by kocoman1** [qnblackcat/uYouPlus#958]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

is there youtube music of this? i need no audio ads and support for playing over mini home thx

**Comment by qnblackcat** [comment]
https://github.com/ginsudev/YTMusicUltimate
