### ISSUE TITLE
New Yt 1080p Premium Bitrate feature unlocking?

### ISSUE THREAD

**Issue by gototheskinny** [qnblackcat/uYouPlus#959]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

[https://www.theverge.com/2023/2/23/23612647/youtube-1080p-premium-subscription-bitrate](https://www.theverge.com/2023/2/23/23612647/youtube-1080p-premium-subscription-bitrate)  I wanted to ask if this could be unlocked in this tweak for free or premium subscribers who uses this tweak for the features? This would be awesome!!

**Comment by Avakining** [comment]
The new Premium features also include iOS SharePlay, which could be nice (if it doesn't require more app IDs)

**Comment by qnblackcat** [comment]
not possible

**Comment by gototheskinny** [comment]
> not possible

It's possible for Smarttube but OK. Uyouplus is not an unofficial open source youtube client. I'm currently using that feature on my Google TV with Smarttube BTW I'm not making this up. If it's possible Google would destroy this repo too IMO so there's no point I guess?
