### ISSUE TITLE
[Bug] Adding Metadata to the M4A hangs

### ISSUE THREAD

**Issue by mschink** [qnblackcat/uYouPlus#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.3.1
- Device model: iPhone 11 Pro
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): uYou v18.01.6-2.3~1

### Describe the bug

I start audio downloads. The downloads finish while the app is in the background. When I re-open the app, the completion is at 100% but the status says "Adding Metadata to the M4A.."

This status message never changes, and the only option is to cancel the download if I tap on the three dots.

If I force-quit the app and re-open it, the downloads show "Completed" but with incorrect values for how many megabytes downloaded. E.g. 10/25MB downloaded but status is still "Completed." They can only be cancelled, and not played at this point.

### Steps to reproduce the issue

1. Start a download as audio only
2. Let it finish while app is in background
3. Come back well after it's done to see the m4a message

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Thanks for this awesome tool!

**Comment by qnblackcat** [comment]
Should be fixed in uYou 3.0

**Comment by qnblackcat** [comment]
Fixed in [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)
