### ISSUE TITLE
Google Account

### ISSUE THREAD

**Issue by clementtech** [qnblackcat/uYouPlus#964]
Hi, I am facing problem to sign in to my Google account after using sidestore.
I just switched to sidestore from altstore and can't sign in even with the shortcut tricks.

Latest uYou+ from repo, shortcut version 2.2, ios 16.4, iPhone X

**Comment by yodaluca23** [comment]
> Hi, I am facing problem to sign in to my Google account after using sidestore.
> I just switched to sidestore from altstore and can't sign in even with the shortcut tricks.
> 
> Latest uYou+ from repo, shortcut version 2.2, ios 16.4, iPhone X

I'm using SideStore, and it's working fine for me...

**Comment by clementtech** [comment]
Seems like my skill issue then, could you please sende the latest shortcut for sign in?

**Comment by qnblackcat** [comment]
https://github.com/qnblackcat/uYouPlus/discussions/904
