### ISSUE TITLE
[Bug] Cannot switch back to ipad layout

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [qnblackcat/uYouPlus#965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 15.3.1
- Device model: ipad pro (10.5 inch)
- Sideload tool (AltStore, Sideloadly, TrollStore,...): trollstore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.07.5-2.3.1

### Describe the bug

After I switched to iphone layout, I noticed that the keyboard was all messed up (https://github.com/qnblackcat/uYouPlus/issues/966), so I decided to go back to the ipad layout. I went into settings > uYouPlus > miscellaneous, but there's no option for iphone or ipad layout. I am now stuck in iphone layout, which is not the most ideal.

### Steps to reproduce the issue

1. Go into settings > uYouPlus > Miscellaneous
2. Enable iphone layout
3. Restart app
4. Go into settings > uYouPlus > Miscellaneous
5. There is no option to disable iphone layout or switch to ipad layout.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
Try [v18.08.1-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.08.1-2.3.1) or higher.

**Comment by ego-lay-atman-bay** [comment]
Thanks, it shows up now.
