### ISSUE TITLE
[Questions] Is there any way to disable the uYou buttons in YouTube shorts?

### ISSUE THREAD

**Issue by oooooooooooooooo** [qnblackcat/uYouPlus#969]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Is there any way to disable the uYou buttons in YouTube shorts?

![Uploading 621A38AE-2CB7-4501-A060-906AD675CCBB.png…]()

**Comment by yodaluca23** [comment]
Kind of unconventional because it's more just using a glitch but you can 'enable' the A/B 'iosEnableShortsPlayerSplitViewController' and it will cause the buttons to not show up...

**Comment by qnblackcat** [comment]
Added in [v18.08.1-2.3.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.08.1-2.3.1) or higher.

**Comment by leewhat** [comment]
This doesn't seems to work anymore
