### ISSUE TITLE
[Bug] PiP not working correctly (manual PiP)

### ISSUE THREAD

**Issue by Charlie102308** [qnblackcat/uYouPlus#97]
### Device info
- iOS/iPadOS version: 15.4.1
- Device model:iphone 13 pro max
- Sideload tool (Ex: AltStore, Sideloadly...)Altstore
- Version of uYouPlus: v17.12.5-2.1-beta

### Describe the bug
Pip Button is not working properly

### How to reproduce the bug
When The pip button is opened,After i clicked the pip button in a video and swipe up, the video player disappear and go back to the original screen
_(Please attach videos or screenshots if possible)_
[RPReplay_Final1649302562 - HD 720p.mov.zip](https://github.com/qnblackcat/uYouPlus/files/8439532/RPReplay_Final1649302562.-.HD.720p.mov.zip)

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_

**Comment by isametry** [comment]
I get the same behavior. Just leaving the app normally by swiping up / pressing the home button works, but the custom PiP button will cause a crash.

**Comment by imloualvaro** [comment]
Same with iOS 15.4, iphone 11

**Comment by qnblackcat** [comment]
Thanks. This is an issue of manual PiP. Unfortunately, me and Poomsmart haven‘t found a solid way to reproduce this bug yet. That’s why it’s kinda hard to solve

**Comment by fnsroot** [comment]
Same issue for me - iOS 15.5 beta 2 and iOS 15.4.1. Surprisingly, this seems not to be an issue of never uYouPlus versions but something in iOS. Older version of this app which definitely did not had this problem (in iOS 15.1, .2, …) now behave the same. Hence, something must have changed with iOS 15.4…?

**Comment by qnblackcat** [comment]
@isametry @imloualvaro 
Can you please disable **Playback in Feeds** in YouTube’s setting > General, and lmk if this bug still occurs?

**Comment by tfurci** [comment]
> @isametry @imloualvaro
> Can you please disable **Playback in Feeds** in YouTube’s setting > General, and lmk if this bug still occurs?

This seems to fix it. Been working for me for some time now

**Comment by MarioMastr** [comment]
Same but different with me. Whenever I leave the app and come back in, the button seems to stop working. Quitting and coming back in seems to fix it, but other times when I open the app (e.g. after restarting), it’s essentially a coin toss as to whether it will work.

**Comment by qnblackcat** [comment]
This issue has been addressed in [v17.25.1-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.25.1-2.1). Please re-open the thread if issue persists
