### ISSUE TITLE
I don't really understand the login

### ISSUE THREAD

**Issue by JSMGAMING** [qnblackcat/uYouPlus#972]
hello, so as the new version suggests, you can now log in into uYou Plus using Google and without those shortcuts. But the problem is, i still can't log in. Google still says that log in is not safe. And yes, i downloaded the newest version of uYou Plus. Is it only for me like that?

**Comment by iRayanKhan** [comment]
How did you Sideload uYou+? 
Did you set the bundleID to com.google.iOS.youtube?

**Comment by JSMGAMING** [comment]
I sideloaded using Scarlet (userscarlet.com). Well, I just logged in using shortcuts method. And at Scarlet you can't set anything, you just directly sideload it. I didn't use a PC.

**Comment by yodaluca23** [comment]
> I sideloaded using Scarlet (userscarlet.com). Well, I just logged in using shortcuts method. And at Scarlet you can't set anything, you just directly sideload it. I didn't use a PC.

That's your problem, I think, Scarlet automatically changes the bundle ID…

**Comment by JSMGAMING** [comment]
Okay. So how should i install it in the future then? What should I use?

**Comment by qnblackcat** [comment]
Please complete the issue template?
