### ISSUE TITLE
[Bug] “Device limit exceeded”

### ISSUE THREAD

**Issue by reticivis-net** [qnblackcat/uYouPlus#980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.3.1
- Device model: iPad Pro 11” 2nd generation
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Scarlet + MapleSign developer certificate 
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v18.08.1-2.3.1

### Describe the bug

When trying to download a video via YouTube Premium but NOT via smart downloads, I get this popup
![AE271764-7F14-43CC-8970-A93F39213FC8](https://user-images.githubusercontent.com/35177464/222295077-eb5c72a5-b969-4196-aa7e-314efcd8ddab.png)
“Learn more” links to here https://support.google.com/youtube/answer/6308288?hl=en&nohelpkit=1

### Steps to reproduce the issue

I think downloading videos, deleting the app, then reinstalling it counts as one device since I’ve done that a lot to update sideloaded YouTube. YouTube’s help article on this says that 10 registered devices is the limit and 4 “swaps” after that gets you this error so 14 times in total

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

✅ Yes, I can reproduce this issue in the official YouTube from AppStore

### Additional context

I’m aware this is likely an issue on YouTube’s end but I was wondering if a workaround is possible?
I’d just use uYou to download but I’m experiencing #238 and uYou doesn’t do the cool smart downloads thing

oddly enough, recommended/smart downloads don’t give me this popup. They still don’t work but I think that’s #327 as the download does start. This is what makes me think a workaround might be possible. In the official app, I have working smart downloads but get the popup for regular downloads

**Comment by 420-420** [comment]
Try making another dummy appleID use that and it should work.

**Comment by HexCodeFFF** [comment]
I use a paid developer certificate via maplesign so I can’t
