### ISSUE TITLE
Not able to change its logo or upgrade to newer version using SideStore

### ISSUE THREAD

**Issue by Blockr22** [qnblackcat/uYouPlus#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS version: 16.3.1
- Device model: iPhone 14
- Sideload tool : SideStore
- The specific version of uYouPlus : Latest 18.08.1

### Describe the bug

Can’t upgrade or Change it logo using SideStore. Happening for some time now, upgrading/updating to newer version wasn’t an issue earlier. Didn’t tried changing icon before so i don’t know if its new or old issue.
If i sideload uYou+ it installs just fine & refresh just fine but whenever there is new update for uYou+ & i try to install that on top of already installed one to retain my settings, it doesn’t work anymore. SideStore fails to update with some error & then it refuses to refresh until I delete it & start over.
Same thing when trying to change its icon using change icon option in sidestore. Sidestore shows that the icon is changed but actually its not changed in & then app refuses to refresh.
Tried altstore aswell, same issues there.

### Steps to reproduce the issue

1. Open Sidestore & install any version of uYou+
2. Then try to install latest version of uYou+ without removing the older uYou+
3. It will give u some error & then refuse to refresh.
4. App will work until its expires, then have to be deleted and reinstalled via SideStore.

           Changing logo is same issue 
1. Open SideStore & install latest version of uYou+
2. Long press uYou+ and tap change icon
3. Select an icon & then it will install new icon
4. SideStore shows new icon without any error in Sidestore itself but in iOS homescreen icon is not changed to new one & uYou+ will refuse to refresh there after.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by Blockr22** [comment]
@arichorn yeah, thats why i m using iVanced for now. I m able to update it no problem but would like to have more options.

**Comment by theoccurrence** [comment]
This is due to how uYou+ is compliled. I don't know how qn compiles this app, but it's done in a way that causes staging issues with sideloaders like SideStore unfortunately.

I found the uYou+ fork "YouTube iVanced", and it works flawlessly. The only problem is that it's always behind on the updates.

I don't know if that's something that can be fixed from SideStore/AltStore's side, or if qn has to compile the app in a different way, but I'm with you that losing all your app data everytime you want to update uYou+ is very annoying.

**Comment by jaff80** [comment]
AltStore is planning to fix this in 2.0: https://twitter.com/altstoreio/status/1664018657087983617

**Comment by jaff80** [comment]
@arichorn AltStore is planning to fix this in 2.0: https://twitter.com/altstoreio/status/1664018657087983617
