### ISSUE TITLE
[Questions] Replace with your question

### ISSUE THREAD

**Issue by Anti-God** [qnblackcat/uYouPlus#982]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Why doesn't it cannot login on iPhone 13 Pro Max via iOS 16.3.1.2?

### Additional context

I have tried to login a lot of times. Please help! Thanks!

**Comment by yodaluca23** [comment]
Are you using Scarlet?
