### ISSUE TITLE
Scarlet for uyou+ 2.3.1

### ISSUE THREAD

**Issue by nlth** [qnblackcat/uYouPlus#985]
I tried to download and reinstall 2.3.1 many times by Scarlet but only 2.1 install on my device and keep remind of update to 2.3.1
My device: iPhone 12 - iOS 16.2
Why does it happened? Should i try to sideload or using other method?

**Comment by yodaluca23** [comment]
> I tried to download and reinstall 2.3.1 many times by Scarlet but only 2.1 install on my device and keep remind of update to 2.3.1
> My device: iPhone 12 - iOS 16.2
> Why does it happened? Should i try to sideload or using other method?

This has nothing to do with Scarlet as said in like 1 million different issues Mir0 forgot to bump the version number in the uYou tweak just press skip it is actually the latest version even though it says it's not...
