### ISSUE TITLE
[Questions] Replace with your question

### ISSUE THREAD

**Issue by lilyspad** [qnblackcat/uYouPlus#986]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Would it be possible to either enable or incorporate a way of copying/sharing links with a timestamp similar to desktop functionality? One of my biggest perpetual problems has been the inability to copy links with a timestamp similar to how you can on the web version via the share menu (via the "Start at" option). As I beleive this isn't a setting I'm missing and isn't something that can be enabled via flags, is it acceptable to make a feature request for this functionality in some capacity?

**Comment by qnblackcat** [comment]
No, sorry. However, there is a shortcut which can achieve that https://www.reddit.com/r/shortcuts/comments/u80qgl/share_youtube_link_at_time_another_shortcut_to/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
