### ISSUE TITLE
Enabling "Other Settings" options break videos & other issues

### ISSUE THREAD

**Issue by turkborough** [qnblackcat/uYouPlus#989]
Enabling "Remove Shorts Section in YT Home" causes videos to go black
Other settings such as "Remove YouTube Ads" are not remembered on app close.
It only took me two re-jailbreaks and 10 app reinstalls for me to find the problem.

Screen recording showing the problem: https://files.catbox.moe/5wlvnh.MP4

phone: 13 pro
ios: 15.1.1
trollstore: 1.5.1
uyouplus version: latest and the past few versions (every one that I tried)
other enabled tweaks for youtube: none
xina jb: various versions

edit: remove shorts function seems to be fine in the 18.01.7_2.3.1 version but it still does not save remove ads & disable age restriction functions. 

Thanks for the work.

**Comment by qnblackcat** [comment]
You must complete the issue template
