### ISSUE TITLE
[Bug] Disable under player buttons

### ISSUE THREAD

**Issue by imloualvaro** [qnblackcat/uYouPlus#99]
### Device info
- iOS/iPadOS version: iOS 15.4
- Device model: iphone 11
- Sideload tool: Appdb
- Version of uYouPlus: 17.2 — V2.1

### Description
It's not possible to disable cast on navigation/head bar, and same thing to buttons under player. I didn't get success to disable create, clip, download button.

**Comment by qnblackcat** [comment]
Duplicate of  https://github.com/qnblackcat/uYouPlus/issues/41
