### ISSUE TITLE
You cant sign in to this app because google cant confirm its safe

### ISSUE THREAD

**Issue by ZiyadAlahmadi** [qnblackcat/uYouPlus#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.1.1
- Device model:iphone XR
- Sideload tool : scarlet
- The specific version of uYouPlus : 18.08.01_2.3.1

### Describe the bug

I still cant sign even when i download the last version 18.08.01_2.3.1 .
I know there is another have complained about this issue but it supposed to be fixed in this version

### Steps to reproduce the issue

![9B41C629-1160-4A28-B226-58346268F438](https://user-images.githubusercontent.com/127003178/222941707-ea4e9f23-787c-44d1-bb3e-ba62c9b6376e.jpeg)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by qnblackcat** [comment]
Please use alternative sideload tool such as AltStore/Sideloadly. We won’t fix this
