### ISSUE TITLE
[Bug] Lag, stuttering and heating up when downloading videos.

### ISSUE THREAD

**Issue by lowerburh** [qnblackcat/uYouPlus#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.4 (20E5223e) (a) | Beta
- Device model: iPhone XR
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): 18.08.1-2.3~1

### Describe the bug

When downloading any video, whether it be through normal uYou or uYouLocal, the app becomes extremely laggy and unresponsive. During long downloads, the device will heat up way more than it should, and YouTube will restart, stopping the download. 

Here is an example of the issue using a very small download.
https://user-images.githubusercontent.com/127071090/223013694-5d41bbce-4f88-459d-b9f6-3b3ca6a17b68.MP4

### Steps to reproduce the issue

1. Start playing any video on the app.
2. Download the video using either uYou or uYouLocal.
3. The issue will last as long as the video takes to download.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Something that I've seen is that when download speeds are exceptionally low, at around 50kbps, there isn't that drastic of a slowdown in the app. However, this has not been an issue in the past, and I don't believe that my device isn't capable of downloading at 1mb/s.

**Comment by qnblackcat** [comment]
should be fixed in uYou 3.0

**Comment by qnblackcat** [comment]
Fixed in [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)
