### ISSUE TITLE
I want you to customize the heading to premium logo.

### ISSUE THREAD

**Issue by dezadx** [qnblackcat/uYouPlus#998]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

I want you to customize the heading to premium logo.

**Comment by dezadx** [comment]
Yes i mean like that

**Comment by qnblackcat** [comment]
We will not do it
